### ISSUE TITLE
vim-plug and Nixos?

### ISSUE THREAD

**Issue by peterstorm** [junegunn/vim-plug#1010]
Hello!

I really, really like vim-plug, but at the moment I am installing Nixos on all my systems, and it's a bit of a hassle to get vim-plug to be my prefered plugin manager, because I haven't figured out how to get vim-plug to start, without putting plug.vim in the corret autoload folder, but I have no idea how to do that with Nixos configuration files.

I have a `vim.nix` file where I override neovim, and ask it to start with vim-plug, but that doesn't seem to work. Anyone have any ideas?

```
with import <nixpkgs> {};

neovim.override {
  configure = {
    customRC = builtins.readFile "/home/peterstorm/.config/nvim/init.vim";
    packages.myVimPackage = with pkgs.vimPlugins; {
      start = [ vim-plug ];
    };
  };
}
```

**Comment by janlazo** [comment]
Did you check https://github.com/NixOS/nixpkgs/issues/56338?

**Comment by peterstorm** [comment]
> Did you check [NixOS/nixpkgs#56338](https://github.com/NixOS/nixpkgs/issues/56338)?

I did skim it, but reading it again, I'm not sure there is anything in there that can help me :( 
I just want to autoload vim-plug through my configuration file, without having to manually install vim-plug and then copy it from the store to the autoload dir.

**Comment by junegunn** [comment]
This is not something we can answer. Please use the issue tracker of NixOS.

FWIW, you can set up your Vim configuration file to automatically download vim-plug.

- https://github.com/junegunn/vim-plug/wiki/tips#automatic-installation

**Comment by grwlf** [comment]
I'm working on my test vim configuration in a Nixos project. vim-plug  _almost_ works for me, with the following configuration 
```nix 
  {
   # ...
    plugvim = pkgs.vim_configurable.customize {
      name = "plugvim";

      vimrcConfig.packages.myVimPackage = with pkgs.vimPlugins; {
        start = [
          vim-plug 
          # Below is an example of how to modify the plugin before installation.
          # This particular modification doesn't work for me.
          # (vim-plug.overrideAttrs (old: {
          #   postInstall = ''
          #    mkdir -pv $target/autoload
          #     ln -s $target/plug.vim $target/autoload
          #   '';
          # }))
        ];
      };
      vimrcConfig.customRC = ''

        runtime! plug.vim

        call plug#begin($HOME.'/_vim')
        Plug 'https://github.com/grwlf/litrepl.vim' , { 'rtp': 'vim' }
        call plug#end()
      '';
    };
  # ...
  }
```

The expression defines a barebone Vim with a single `vim-plug` plugin. It could be built with `nix-build -A plugvim` and run with `./result/bin/plugvim`.

The only problem I see is probably a Vim-related one. The `runtime!` line of the config line returns successfully, but `plug#*` functions don't appear _on this run_ of the config, so vim issues errors. If I re-type the commands manually or source the config (by looking its absolute path) then everything start to work.

Do you have an idea why

**Comment by tankorsmash** [comment]
@sergei-mironov Did you end up figuring out this issue?

**Comment by sergei-mironov** [comment]
> @sergei-mironov Did you end up figuring out this issue?

Hi @tankorsmash . As of vim-plug-2024-05-14 my Nix expression contains a workaround and looks like this.


``` vim
   vim-plug-test = pkgs.vim_configurable.customize {
      name = "vim-plug-test";

      vimrcConfig.packages.myVimPackage = with pkgs.vimPlugins; {
        start = [
          # vim-plug # <--- Does not work as-is, so the below override is required.
          (vim-plug.overrideAttrs (old: {
            postInstall = ''
              mkdir -pv $target/autoload
              ln -s $target/plug.vim $target/autoload
            '';
          }))
        ];
      };
      vimrcConfig.customRC = ''
        call plug#begin($HOME.'/_vim')
        Plug 'https://github.com/sergei-mironov/litrepl.vim' , { 'rtp': 'vim' }
        call plug#end()

        " Setting PATH is a custom requirement of the above Litrepl plugin
        let $PATH="${pkgs.socat}/bin:${litrepl python}/bin:".$PATH
      '';
    };
```

It defines a vim with Plug installing a single plugin. Note the absence of the `runtime! plug.vim` command. If I remove the autoload symlink hack I would see errors I described above (which do not appear if I call `runtime! plug.vim` and then re-type the lines manually). It makes me think there are some runtime path problems in Nix or maybe something I do not know about Plug setup. The hack makes everything works.
