### ISSUE TITLE
Change init directory

### ISSUE THREAD

**Issue by timsofteng** [junegunn/vim-plug#1015]
Hello.

How can I change directory where vim-plug should be install? For example I want to move it from root to `~/.config`.
If I change path in script vim-plug doesn't work
`curl -fLo ~/some_path/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim`

**Comment by janlazo** [comment]
Did you add `~/some_path/` to your `runtimepath`?

**Comment by timsofteng** [comment]
> Did you add `~/some_path/` to your `runtimepath`?

What do you mean? I just added path into init file into the shell config 
`VIMINIT = 'source ~/some_path/vimrc`

**Comment by janlazo** [comment]
`:help 'runtimepath'`

**Comment by timsofteng** [comment]
> `:help 'runtimepath'`

I'm using NixOS and here is output of `:set runtimepath` command:
`runtimepath=~/.vim,/nix/store/qx3f6nrqgsb0y0sswy4zdw0sv86dwk9x-vim-8.2.0013/share/vim/vimfiles,/nix/stor
e/qx3f6nrqgsb0y0sswy4zdw0sv86dwk9x-vim-8.2.0013/share/vim/vim82,/nix/store/qx3f6nrqgsb0y0sswy4zdw0sv86dwk9
x-vim-8.2.0013/share/vim/vimfiles/after,~/.vim/after`

How can I change ~./vim to~/another/path?

Thanks

**Comment by janlazo** [comment]
```vim
set runtimepath-=~/.vim runtimepath-=~/.vim/after
set runtimepath^=~/some_path
set runtimepath+=~/some_path/after
```

**Comment by timsofteng** [comment]
> ```viml
> set runtimepath-=~/.vim runtimepath-=~/.vim/after
> set runtimepath^=~/some_path
> set runtimepath+=~/some_path/after
> ```

awesome
It works.
Can I somehow add `:PlugInstall` command to autoloinstallation script as well?

**Comment by janlazo** [comment]
You can. I run `PlugInstall` on VimEnter event after cloning my config on a new machine.

**Comment by timsofteng** [comment]
> You can. I run `PlugInstall` on VimEnter event after cloning my config on a new machine.

Could you show me this please in this code?

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

**Comment by janlazo** [comment]
No comment on the code snippet you posted. I bundle vim-plug in my config to avoid that condition.

```vim
function! s:vim_enter()
    if exists('g:loaded_plug')
    \ && has('patch-7.4.1347')
    \ && empty(glob(g:plug_home . '/*'))
    \ && empty($CI)
      PlugInstall --sync
      q
    endif
    " Do whatever you want here
 endfunction

 augroup vimrc
    autocmd!
    if has('nvim') ? has('nvim-0.4') : has('patch-8.1.1113')
      autocmd VimEnter * ++nested ++once call s:vim_enter()
    else
      autocmd VimEnter * nested call s:vim_enter()
    endif
  augroup END
```
https://github.com/janlazo/dotvim8/blob/master/shared.vim
