### ISSUE TITLE
 Not an editor command: PlugInstall

### ISSUE THREAD

**Issue by Mryehua** [junegunn/vim-plug#1019]
Explain the problem here ...

------------------------------

```

```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by Alegarciy** [comment]
Same error, I'm currently using windows and idk why it happens. The path i have is 

I do the following: 
1) Run the Windows NeoVim

iwr -useb https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim |`
    ni "$env:LOCALAPPDATA/nvim-data/site/autoload/plug.vim" -Force

2) Check the path
C:\Users\alega\AppData\Local\nvim-data\site\autoload

3) Create a file to put the following code

"
call plug#begin(stdpath('data').'/plugged')

Plug 'dikiaap/minimalist'

call plug#end()


set t_Co=256
syntax on
colorscheme minimalist
"

4) Try tu run: PlugInstall
5) The error pops up -> E492: Not an editor command: PlugInstall

**Comment by janlazo** [comment]
Is step 3 in your init.vim or within `stdpath('data')`?

**Comment by Alegarciy** [comment]
> Is step 3 in your init.vim or within `stdpath('data')`?

Yes i had it all wrong. I finally manage to solve it been careful with the path and the location of the ini.vim file. I put it next to the plugin folder and did it this way.

![Screenshot 2020-10-07 031145](https://user-images.githubusercontent.com/41702000/95311444-d9d2b900-084a-11eb-997e-58c94fd7ee8e.png)

**Comment by janlazo** [comment]
No comments from @Mryehua to explain his situation.
@Alegarciy issue is resolved.
