### ISSUE TITLE
Flag for separation vim and neovim specific plugins

### ISSUE THREAD

**Issue by timsofteng** [junegunn/vim-plug#1021]
Hey. I have idea about new feature for vim-plug. Many people sharing their configs between vim and neovim. But unfortunately some of plugins works with neovim or with vim only. How about flag which will prevent loading plugin if user start editor which not support it?
It would looks something like this:
`Plug 'author/repo' [n];` - it should signal to load it only with neovim and ignore with vim.
Or you can create better syntax. It's just example.

What do you think about it?

**Comment by Happy-Dude** [comment]
It is possible to do this wrapping

```Vim
if has('nvim')
  Plug 'neovim-plugin'
endif
```

**Comment by junegunn** [comment]
You might want to check out https://github.com/junegunn/vim-plug/wiki/tips#conditional-activation
