### ISSUE TITLE
Load on demand for specific directories and git repositories

### ISSUE THREAD

**Issue by jzbor** [junegunn/vim-plug#1025]
I would be great to have to additional args like 'on' and 'for' to load a plugin on demand. It would be nice if you'd be able to specify certain directories instead of filetypes, so if you open a file in that directory (or a subdirectory of it) the plugin gets loaded. A possible use for this would be note directories or different directories for different languages. The second option that would be nice to have are plugins being loaded only when the file is in a directory containing an initialized git repository (containing a .git directory). A usecase here would be plugins like fugitive or git-gutter.

------------------------------

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [x] Feature Request
    - [ ] Question
- OS:
    - [x] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by janlazo** [comment]
It is possible to support the 2nd option via `autochdir` option or plugins like https://github.com/airblade/vim-rooter to handle directory switching. This feature will likely not be implemented in vim-plug because Vim/Neovim are fast enough even with a long `runtimepath` unless the user has 100+ plugins. However, a public API can be exposed so that plugins can handle this for vim-plug.

PRs are welcome for this public API.

**Comment by junegunn** [comment]
I believe you can achieve what you want with DirChanged autocmd and `plug#load` function.

- https://github.com/junegunn/vim-plug/wiki/tips#loading-plugins-manually

I've been trying to discourage users from using `on` or `for` option, so it's unlikely that we'll expand those options.

- https://github.com/junegunn/vim-plug/wiki/faq#when-should-i-use-on-or-for-option

**Comment by jzbor** [comment]
Ok thank you. The `plug#load` function sounds fine. Thank you for your quick response and great plugin manager. I am going to close this issue now. I agree that there is probably no need for this functionality for the project itself and the vast majority of its users. Have a nice day :)
