### ISSUE TITLE
Question: about a hack in the source code

### ISSUE THREAD

**Issue by zzxoto** [junegunn/vim-plug#1029]
Have you guys any insight into how [this](https://github.com/dyng/ctrlsf.vim/blob/89a8ec1e537297d902dbe01acf162136d26bea61/plugin/ctrlsf.vim#L63) hack solves the problem of `g:CtrlSFGetVisualSelection()`; because I stumbled into this problem that visual selection was "stale" when just plainly using that function

**Comment by janlazo** [comment]
I am not familiar with the https://github.com/dyng/ctrlsf.vim codebase. Submit your question to its issue tracker, not vim-plug.

**Comment by zzxoto** [comment]
Apologize for this blunder.
