### ISSUE TITLE
Not an editor command: PlugInstall

### ISSUE THREAD

**Issue by RaCs5** [junegunn/vim-plug#1030]
I need help I'm using vim-pug on Windows 10 and it won't let me use: PlugInstall I get error E492: Not an editor command: PlugInstall
this is the configuration that I put

call plug#begin('~/AppData/local/nvim/autoload')
2 Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries', 'for': 'go' }
3 Plug 'tpope/vim-surround'
4 Plug 'scrooloose/nerdtree'
5 Plug 'sheerun/vim-polyglot'
6 Plug 'PProvost/vim-ps1'
7 Plug 'tomasr/molokai'
8 Plug 'vim-airline/vim-airline'
9 Plug 'tpope/vim-fugitive'
10 Plug 'stamblerre/gocode'
11 Plug 'dense-analysis/ale'
12 Plug 'neoclide/coc.nvim', {'branch': 'release'}
13 call plug#end()
14
15 let g:go_addtags_transform = "snakecase"
16 " " Copy to clipboard
17 vnoremap y "+y
18 nnoremap Y "+yg_
19 nnoremap y "+y
20 nnoremap yy "+yy
21 " " Paste from clipboard
21 nnoremap p "+p
22 nnoremap P "+P
24 vnoremap p "+p
25 vnoremap P "+P
26 let g:go_auto_sameids = 1
27 let g:go_auto_info = 1`

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ √] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ √] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [ √] Neovim

**Comment by RaCs5** [comment]
Pls help

**Comment by janlazo** [comment]
> Did you install vim-plug by putting in your `autoload/` directory?

https://github.com/junegunn/vim-plug#windows-powershell-1

> `call plug#begin('~/AppData/local/nvim/autoload')`

You should never put vim-plug plugins in an `autoload/` directory. vim-plug should have caught that. It catches only `plugin`.

https://github.com/junegunn/vim-plug/commit/449b4f1ed6084f81a1d0c2c1136cd242ec938625

**Comment by TheSheepster** [comment]
did you have [git](https://git-scm.com/download/win) installed?

**Comment by y0l016** [comment]
> Did you install vim-plug by putting in your `autoload/` directory?
> 
> https://github.com/junegunn/vim-plug#windows-powershell-1
> 
> > `call plug#begin('~/AppData/local/nvim/autoload')`
> 
> You should never put vim-plug plugins in an `autoload/` directory. vim-plug should have caught that. It catches only `plugin`.
> 
> [449b4f1](https://github.com/junegunn/vim-plug/commit/449b4f1ed6084f81a1d0c2c1136cd242ec938625)

I face the same issue on gVim in Windows. I put plug in `autoload/` and in `plugin` . neither worked

**Comment by junegunn** [comment]
A common mistake people make on GVim is to put the configuration code in gvimrc instead of in vimrc.

https://github.com/junegunn/vim-plug/issues/540

**Comment by nikunj321** [comment]
i have vim installed and i have the same error. neither worked.
 and my all the stuff in vimrc

**Comment by nikunj321** [comment]
> > Did you install vim-plug by putting in your `autoload/` directory?
> > https://github.com/junegunn/vim-plug#windows-powershell-1
> > > `call plug#begin('~/AppData/local/nvim/autoload')`
> > 
> > 
> > You should never put vim-plug plugins in an `autoload/` directory. vim-plug should have caught that. It catches only `plugin`.
> > [449b4f1](https://github.com/junegunn/vim-plug/commit/449b4f1ed6084f81a1d0c2c1136cd242ec938625)
> 
> I face the same issue on gVim in Windows. I put plug in `autoload/` and in `plugin` . neither worked

try unix url it will work.

**Comment by BooleanCube** [comment]
I just had to move my init.vim file to AppData/Local/nvim/init.vim

**Comment by janlazo** [comment]
No comment from @RaCs5 and others have mentioned workarounds for this recurring issue so I'm closing this.

**Comment by zlqwerty123** [comment]
I have the same problem, vim catch the "plug.vim", but it also show the problem "Not  an editor command :PlugInstall

**Comment by bsweet2** [comment]
I had this issue because I had .vimrc open in a separate tab.  I tried using the 'e' command to reload it.  I tried closing out of the tab and opening it again.  I needed to close all tabs and reopen .vimrc for this to install.

**Comment by arilebedey** [comment]
I had this issue because I used the Neovim "Windows (PowerShell)" install from https://github.com/junegunn/vim-plug#windows-powershell-1 instead of the Vim one. Running the right install solved it.

**Comment by skorokithakis** [comment]
I'm having the same issue on Linux with the [automatic installation](https://github.com/junegunn/vim-plug/wiki/tips#automatic-installation) commands. It downloads the file fine, but then that command fails. Maybe that's a NeoVim command? I'm using plain vim.

**Comment by youganon** [comment]
> I just had to move my init.vim file to AppData/Local/nvim/init.vim

This worked.

**Comment by cad1994** [comment]
> call plug#begin('~/AppData/local/nvim/autoload')

Worked in windows 10, 2022.
Thanks!

**Comment by SafetyMary** [comment]
> I just had to move my init.vim file to AppData/Local/nvim/init.vim

This worked for me thanks. Since this worked for multple people, maybe the installaton guide should be updated?
