### ISSUE TITLE
error: Missing value for 'credential.helper'

### ISSUE THREAD

**Issue by walkerdu** [junegunn/vim-plug#1031]
When I `:Plugin Update`, then report blow error message:

```
4 - Finishing ... Done!                          
  5 x bufexplorer                                  
  6     error: Missing value for 'credential.helper'
  7     fatal: unable to parse command-line config 
  8 x vim-cpp-enhanced-highlight                   
  9     error: Missing value for 'credential.helper'
 10     fatal: unable to parse command-line config 
 11 x LeaderF                                      
 12     error: Missing value for 'credential.helper'
 13     fatal: unable to parse command-line config 
 14 x semantic-highlight.vim                       
 15     error: Missing value for 'credential.helper'
 16     fatal: unable to parse command-line config 
```

------------------------------

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct 21 2019 14:03:15)
Included patches: 1-207, 209-629

git version 1.8.3.1
```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
Caused by #1026.

We should avoid adding `-c credential.helper=` if git version is too low.

/cc @mattn

**Comment by janlazo** [comment]
Add a version check?

**Comment by junegunn** [comment]
Sounds good.

- Let's just remove the option from Ruby and Python installers; as they are only for old systems.
- Add the option only when Git 2.0.0 or above is available.

**Comment by mattn** [comment]
Thanks

**Comment by junegunn** [comment]
@walkerdu It should be fixed now. `:PlugUpgrade` and try again. Thanks for the report.

**Comment by walkerdu** [comment]
> @walkerdu It should be fixed now. `:PlugUpgrade` and try again. Thanks for the report.

Thanks

**Comment by walkerdu** [comment]
@junegunn Thanks~
