### ISSUE TITLE
Abiilty to run commands upon PlugUpdate completion

### ISSUE THREAD

**Issue by dsirov** [junegunn/vim-plug#1035]
There are plugins which have their own plugin ecosystem (see [coc.nvim](https://github.com/neoclide/coc.nvim) for example - it has its own plugin update command - `CocUpdate`).

It would be nice for a user to be able to create a single command in his `init.vim` that updates all plugins.

What I had in mind was something like this:
```
function! Update()
    PlugUpgrade
    PlugClean
    PlugUpdate
    CocStart
    CocUpdate
    UpdateRemotePlugins
endfunction
```

The problem is that it seems that the PlugUpdate command is completed before the update is actually complete.
Thus when CocUpdate is performed it may be initiated from a non-up-to-date Coc plugin itself.

It would be nice to have an ability to run commands upon PlugUpdate completion, whether with PlugUpdate (ot its variant) returning only  when updates are complete or with a command that can be hooked to run after update.

- Type:
    - [ ] Bug
    - [x] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [x] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
`PlugUpdate --sync` will block until completion (undocumented feature).

**Comment by dsirov** [comment]
Neat!
