### ISSUE TITLE
difficulty with automated calling of PlugInstall

### ISSUE THREAD

**Issue by ExpandingMan** [junegunn/vim-plug#1036]
Hello all, I'm trying to completely automate my neovim setup.  I am doing this in arch linux docker images.  My problem is that after installing `plug.vim` in to `~/.local/share/nvim/site/autoload/plug.vim` (I have verified it is there) when I run
```
nvim -c PlugInstall -c qa --headless
```
What is really especially bizarre is that this only seems to happen during the automated process... if I try running again after it works.  I've also tried calling `nvim -c qa --headless` first just in case it has something that it would normally initialize in that step.  Any idea what's going on?

```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconver
sion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/b
uild/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by jnnksdev** [comment]
So, what was it? Seems like I'm having the same problem:
`nvim --headless +'PlugInstall' +qall` fails in Dockerfile, but works fine during `docker run -it`

**Comment by ExpandingMan** [comment]
Your problem is not related to mine.  I don't remember exactly what I did here, but I called the wrong command or something, it wasn't a real issue at all.
