### ISSUE TITLE
curl: (6) Could not resolve host: raw.githubusercontent.com

### ISSUE THREAD

**Issue by miss1997yuan** [junegunn/vim-plug#1038]
Explain the problem here ...

------------------------------

```

```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by miss1997yuan** [comment]
would someone help me

**Comment by janlazo** [comment]
Which OS? Need more info on how you reached the error.

https://stackoverflow.com/questions/27761799/error-installing-homebrew-on-mac-curl-6-could-not-resolve-host-raw-githubus

**Comment by evan-chaney** [comment]
This does not seem like a vim-plug issue.
