### ISSUE TITLE
Feature Request:  Lookup a plugin on GitHub

### ISSUE THREAD

**Issue by Traap** [junegunn/vim-plug#1041]
```viml
" Assume the following plugins are present in your vimrc file.

Plug 'junegunn/fzf.vim'
Plug 'junegunn/gv.vim'
Plug 'junegunn/vim-easy-align'

" I use this code snippet to lookup the plugin on GitHub.com

if exists('g:loaded_plug_lookup')
  finish
endif
let g:loaded_plug_lookup = 1

function! PlugLookup(pat)
  if has('unix')
    let url = "xdg-open https://github.com/" . a:pat . ".git"
    call jobstart(url)
  endif
endfunction

" I use the following keybindings to invoke the lookup.

nnoremap <silent> <leader>pl    :call PlugLookup(expand("<cWORD>"))<cr>
xnoremap <silent> <leader>pl "gy:call PlugLookup(@g)<cr>gv

" I only have this working for Linux which is my target operating system.
"
" I offer this for your consideration.
```

**Comment by janlazo** [comment]
This would go into https://github.com/junegunn/vim-plug/wiki/tips. It is better to use `curl` or similar program to search using Github API than spawning a browser to open a url.

**Comment by junegunn** [comment]
Here is a version that uses netrw which should be more portable.

https://github.com/junegunn/vim-plug/wiki/extra#gx-to-open-github-urls-on-browser

While some may find this useful, I don't think it's an essential feature we have to add to vim-plug. I'd like to keep it on the wiki page, and let the users choose to opt-in.

**Comment by Traap** [comment]
Thank you for the feedback.
