### ISSUE TITLE
Randomly getting "Fatal: expected flush after ref listing" on `:PlugUpdate`

### ISSUE THREAD

**Issue by metalelf0** [junegunn/vim-plug#1043]
When I run `:PlugUpdate`, some of my plugins can't update and I get the following output:

```
...
- todoplus.vim: Already up to date.
- vim-easy-align: Already up to date.
x onehalf:
    error: RPC failed; curl 18 transfer closed with outstanding read data remaining
    fatal: expected flush after ref listing
- ctrlsf.vim: Already up to date.
...
```

Hitting `R` to retry causes most of the crashing plugins to be correctly installed, some still fail, so after a couple retries I usually get them all to update. 

------------------------------

```
NVIM v0.5.0-903-g6c344a75d
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /Library/Developer/CommandLineTools/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototyp
es -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECL
ARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/metalelf0/sources/neovim/build/config -I/Users/metalelf0/sources/neovim
/src -I/Users/metalelf0/sources/neovim/.deps/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/include -I/usr/local/opt/gettext/include -I/Users/metal
elf0/sources/neovim/build/src/nvim/auto -I/Users/metalelf0/sources/neovim/build/include
Compiled by metalelf0@Elsewhere
Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

Some additional info:

- git version is 2.29.2
- macOS big sur 11.0.1

Let me know if I can provide any additional info.

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [x] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by metalelf0** [comment]
It just happened outside my neovim, in my terminal, while running `git clone` on a repo. So I assume it's a git issue and not a `vim-plug` one. Strange thing is, it started happening today, never seen this issue in the past days. Leaving this here in case anyone has info, but this is 100% not a vim-plug issue.

**Comment by metalelf0** [comment]
The problem, today, seems to be totally gone after rebuilding latest neovim. The changelog shows nothing suspicious, at least to my eyes. Closing this as the issue is not reproducible anymore.

**Comment by UTarasevich-7S** [comment]
atlantis plan
