### ISSUE TITLE
linux E492: Not an editor command: PlugInstall

### ISSUE THREAD

**Issue by jclivi** [junegunn/vim-plug#1048]
![深度截图_选择区域_20201216210929](https://user-images.githubusercontent.com/14210650/102352778-27099e80-3fe3-11eb-8b0e-b8f28e6fc6ef.png)

**Comment by janlazo** [comment]
`plug.vim` is not installed or it is not sourced (via `runtime. There are lots of closed issues with the same complaint. Check those first issues first before opening a new issue. Reopen and edit the issue title if your situation is different from the rest.
