### ISSUE TITLE
Add support for colorthemes

### ISSUE THREAD

**Issue by andreicristianpetcu** [junegunn/vim-plug#105]
Hi! I'm trying to figure out if Plug does not have support for colorthemes or if 'sickill/vim-monokai' is built in a broken way. I have it declared in my vimrc and if I start vim on a new machine I get this:

E185: Cannot find color scheme 'monokai'
Press ENTER or type command to continue

Is there a problem with monokai or with Plug? This worked on Vundle and on NeoBundle. I manually run this command in order to fix it:

mkdir -p ~/.vim/colors/ && ln -s ~/.vim/plugged/vim-monokai/colors/monokai.vim ~/.vim/colors/monokai.vim

If this is because Plug does not have support for colorthemes, could you add such a feature?
Thank you!

**Comment by felixcuello** [comment]
Thanks for you GREAT vim plugins junegunn.

I have exactly the same issue. I have installed monokai.vim with vim-plug and to make it work I had to do this:

~/.vim/colors/monokai.vim -> ../plugged/vim-monokai/colors/monokai.vim

Not ideal, but it works :-)

**Comment by junegunn** [comment]
@felixcuello No you don't need it. I guess you tried to `colo monomai` before `plug#end()`? Plugins become available only after `plug#end()`.

**Comment by hristod** [comment]
Hey, same issue here. Just tried the following:
1) create a mini vimrc:

```
call plug#begin('~/.vim/plugged')                                                                                                                        
Plug 'chriskempson/base16-vim'                                                                                                                          
call plug#end()                                                                                                                                          
colorscheme base16-default
```

Did a :PlugClean, then a :PlugInstall and reloaded Vim. I still get the same message: E185: Cannot find color scheme 'base16-default'

Any ideas?

**Comment by vheon** [comment]
@hristod that is because there is no such colorscheme in that repo; there are two of them and are called  base16-default-dark and base16-default-light 👍

**Comment by ZelphirKaltstahl** [comment]
I am experiencing another case of this, can you help me out?

    call plug#begin('~/.vim/plugged')
    
    Plug 'https://github.com/kovisoft/slimv.git'
    Plug 'chriskempson/tomorrow-theme'
    
    " Add plugins to &runtimepath
    call plug#end()
    
    " load syntax theme
    colorscheme Tomorrow-Night-Eighties
    
    " activate syntax highlighting
    syntax on

I looked into the plugin's file and there is a line:

    let g:colors_name = "Tomorrow-Night-Eighties"

So I think this is the correct name, but it does not work. When I start `vim`, I get:

    Error detected while processing /home/xiaolong/.vimrc:
    line   10:
    E185: Cannot find color scheme 'Tomorrow-Night-Eighties'

When I check for which addons are installed with `:colorscheme <ctrl+d>`:

    blue       default    desert     evening    koehler    murphy     peachpuff  shine      torte
    darkblue   delek      elflord    industry   morning    pablo      ron        slate      zellner

Note: This is a vanilla vim with only these lines in the `~/.vimrc` file and only those plugins installed. I also found another directory, where colorschemes are installed:

    ls /usr/share/vim/vim74/colors/

Gives:

    blue.vim      delek.vim    evening.vim   morning.vim  peachpuff.vim  shine.vim  zellner.vim
    darkblue.vim  desert.vim   industry.vim  murphy.vim   README.txt     slate.vim
    default.vim   elflord.vim  koehler.vim   pablo.vim    ron.vim        torte.vim

How can I fix this?

**Comment by junegunn** [comment]
@ZelphirKaltstahl 

https://github.com/chriskempson/tomorrow-theme/tree/master/vim/colors

Vim color schemes are located inside `vim/colors` not in conventional `colors`. You can do `Plug 'chriskempson/tomorrow-theme', { 'rtp': 'vim' }`, but it's better to use the Vim-only repo: `Plug 'chriskempson/vim-tomorrow-theme'`.

**Comment by ZelphirKaltstahl** [comment]
@junegunn Thanks, I didn't know that the repo matters or that there is a specialized one for only VIM. Seems to work now.

**Comment by kevthanewversi** [comment]
I had to to symlink to make it work too > `sudo ln -s  ~/.vim/plugged/vim-monokai/colors/monokai.vim  ~/.vim/colors/monokai.vim`

**Comment by junegunn** [comment]
@kevthanewversi No, you don't have to. My guess is that you put `colorscheme monokai` before `call plug#end()`.
