### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by jarven-zhang** [junegunn/vim-plug#1050]
curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused

-------------------------------------------------------------
Anybody know that?

ubuntu@VM-0-12-ubuntu:~/soft$ curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to raw.githubusercontent.com:443

**Comment by janlazo** [comment]
You need the ssl certs to make requests to github.
