### ISSUE TITLE
Cannot load plugin for filetype.

### ISSUE THREAD

**Issue by DasOhmoff** [junegunn/vim-plug#1051]
When I try to load a plugin on demand it does not seem to be working.
For example:
```
call plug#begin("~/Vimfiles/plugged")
[...]
Plug 'OmniSharp/omnisharp-vim', { 'for': 'cs' }
[...]
call plug#end()
```
When I open up `cs` files, the plugin does not get loaded.
It does seem to work on some other plugins though, so I don't know whether this is a problem with omnisharp or vim-plug.

How can I make it happen so that OmniSharp is only loaded when `cs` files are opened?

Thank you very much for helping :)

**Comment by junegunn** [comment]
Are you trying to do it because Omnisharp takes long to load? Most of the time, the benefit of `for` option is insignificant and I don't recommend using it.

Please read https://github.com/junegunn/vim-plug/wiki/faq#when-should-i-use-on-or-for-option

**Comment by DasOhmoff** [comment]
Ah ok, thank you :)
