### ISSUE TITLE
Why is VimPlug enabling options that have nothing to do with it?

### ISSUE THREAD

**Issue by tal-zvon** [junegunn/vim-plug#1053]
I don't know if this has been discussed before, but it seems ridiculous to me that VimPlug would enable options that have nothing to do with it, and tell people who don't like it to turn them off in the documentation. I'm talking about this:

> You can remove filetype off, filetype plugin indent on and syntax on from your .vimrc as they are automatically handled by plug#begin() and plug#end().

When I buy a toaster, I don't expect my toaster to start running around my countertop trying to clean it just because the toaster developers decided that "no one wants dirty countertops". Yes, most people don't want dirty countertops, and yes, there are almost definitely people out there that would love to have their toaster clean their countertops, but the majority of people just want their toaster to make toast. If I buy what I think is a regular toaster, and it starts running around my counter, forcing me to unplug it and go read the instructions to find out why it's doing that, I'm not going to be happy it took the initiative to clean my counters. I'm going to be mad that this is a "feature", and mad that it's on by default.

Similarly, if I have a .vimrc file where my VimPlug enables features that have nothing to do with it (at least as far as a user of VimPlug is concerned), even if VimPlug happens to use those features internally, I'm not going to be happy it took the initiative. 

If I explicitly disabled these options, and later in that .vimrc file I enable VimPlug, I don't expect those features to come back on again. It's not even immediately apparent which part of my multi-hundred-line vimrc file enabled these features after I explicitly disabled them. I'm not going to read every line of the documentation for every one of my dozen plugins to try to find which plugin is doing it, so instead, I'm forced to go on a hunt, disabling parts of my file until I find out what caused this.

Even worse, with VimPlug doing this, it forces dependencies in the .vimrc file. Now, if I want to turn off these features, instead of doing it anywhere in the file, I need to know that VimPlug enables them again, and that I need to disable them after VimPlug.

Having VimPlug do this also sets a bad precedent. If every vim plugin starts setting whatever options it wants to whatever settings it feels like, the entire ecosystem is going to become a nightmare.

I'm clearly not the only one that has had issues with this in the past: https://github.com/junegunn/vim-plug/issues/759

Having VimPlug enable these features automatically is ridiculous, annoying, and should not happen. Sorry for the semi-aggressive tone. Other than this, VimPlug is pretty awesome.

Thanks

**Comment by junegunn** [comment]
vim-plug is an opinionated project and you can of course disagree with [its design choices](https://github.com/junegunn/vim-plug/issues/379#issuecomment-267800458). But whether you like it or not, changing the default behavior of this 7-year old project that many people rely on is not an option. It's a free open-source project, so please fork it and change it to your liking or use a different project that you like better. Thank you.

**Comment by EvanCarroll** [comment]
see: #1083 Stop Turning `syntax on`
