### ISSUE TITLE
"except filetype" option

### ISSUE THREAD

**Issue by ACiep** [junegunn/vim-plug#1055]
It would be nice to have opposite of `for` option.
There are some plugins that it doesn't make sense to use with specific file type and instead of defining all other languages for which I want to use them I could just exclude that one specific type.
For example if I work on Clojure file I don't want `auto-pairs` because I already have `paredit` but I still need it when working on Java, JavaScript or Scala . Auto completing is very useful while programming but can be annoying when working on blog post in markdown or e-mail.

**Comment by junegunn** [comment]
See https://github.com/junegunn/vim-plug/issues/928#issuecomment-619471207

You should probably write FileType autocmd for controlling the behavior of the plugin. vim-plug can't really help you with that.
