### ISSUE TITLE
how to set proxy on before plugin install/update

### ISSUE THREAD

**Issue by zanglg** [junegunn/vim-plug#1056]
I can export http_proxy, but I need type that every time I update my plugins.
I workded in a internal net environment, It's not able to switch proxy on all the time.

**Comment by adoyle-h** [comment]
[`let g:plug_url_format`](https://github.com/junegunn/vim-plug/blob/0.11.0/doc/plug.txt#L231)

**Comment by zanglg** [comment]
Thanks, I've solved it by a small script which toggle proxy before and after plug installing.

**Comment by maxrisk** [comment]
哪个脚本？

**Comment by aoenth** [comment]
@maxrisk You can put the following in your vimrc/init.vim which has worked for me.
call system('export http_proxy=<proxy url>')
call system('export https_proxy=<proxy url >')
