### ISSUE TITLE
E492 Not an editor command :PlugInstall

### ISSUE THREAD

**Issue by Johan-Palacios** [junegunn/vim-plug#1061]
Tengo un problema al ejecutar los plugins de vim-plug, uso el emulador de ubuntu en windows 10 WLS

Aclarado eso, les explicare mi situación, ejecute el comando correpondiente para instalar vim-plug de neovim y me genero el archivo de `plug.vim`, entonces trate de instalar unos plugins y me daba el error de "E492 Not an editor command :PlugInstall"

PD: Tengo el archivo init.vim, neovim funciona bien, tengo instalado vim-plug y he utilizado el modo superior para ejecutar nvim, pero no hay respuesta 

Quien me pueda dar una solución a mi problema se lo agradecere grandemente

**Comment by janlazo** [comment]
If the Windows instructions at https://github.com/junegunn/vim-plug#neovim does not work you,
create `autoload/` directory beside your `init.vim` and put https://github.com/junegunn/vim-plug/blob/master/plug.vim inside `autoload/`.

Example: https://github.com/janlazo/dotvim8/tree/master/autoload

**Comment by AlejandroVaqueraLopez** [comment]
hola mi solucion fue cambiar el archivo init.vim y plug.vim a la carpeta nvim, ya que por defecto me la habia colocado en la carpeta nvim-data, ahi no podia instalar mis plugins, otra solucion es instalar git a la mas reciente version, saludos espero ayudar

**Comment by Anyell0w** [comment]
> 

Te amo amigo, gracias.
