### ISSUE TITLE
Not working at all. Says "Unknown function: plug#begin"

### ISSUE THREAD

**Issue by hrqmonteiro** [junegunn/vim-plug#1062]
I was using it until, like, two days ago. Now i changed my distro and i am trying to install it again.

I copied the `plug.vim` file to my `.config/nvim/plugged/plug.vim` location.

And i am trying to call it using:

```
call plug#begin('~/.config/nvim/plugged')


call plug#end()
```

And i got: 

```
Error detected while processing /home/hrq/.config/nvim/init.vim:
line   10:
E117: Unknown function: plug#begin
line   11:
E492: Not an editor command:     Plug 'arcticicestudio/nord-vim'
line   28:
E117: Unknown function: plug#end
```

And:

```
E492: Not an editor command: PlugInstall
```

How do i solve this?

**Comment by junegunn** [comment]
Please follow the instruction here:
https://github.com/junegunn/vim-plug#neovim

**Comment by ErnieWhite** [comment]
I ended up using 
```
call plug#begin(stdpath('data').'/site/autoload/plugged')
```

**Comment by theJoshMuller** [comment]
Just had this issue. None of the solutions I found and tried ended up working.

In the end, I discovered my `autoload/plug.vim` file got blanked out somewhere along the line. It had 0 bytes in it. 

Don't know why. Bad update?

Anyways, ended up deleting the `plug.vim` file (effectively uninstalling vim-plug).

I have this at the start of my `init.vim` file:
```
let mapleader =","

if ! filereadable(system('echo -n "${XDG_CONFIG_HOME:-$HOME/.config}/nvim/autoload/plug.vim"'))
	echo "Downloading junegunn/vim-plug to manage plugins..."
	silent !mkdir -p ${XDG_CONFIG_HOME:-$HOME/.config}/nvim/autoload/
	silent !curl "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim" > ${XDG_CONFIG_HOME:-$HOME/.config}/nvim/autoload/plug.vim
	autocmd VimEnter * PlugInstall
endif
```

So, it automatically reinstalled the next time I opened into nvim. 

Mission accomplished. Hope that helps someone dealing with the same problem 👍🏽

**Comment by BerserkerViking** [comment]
What are some of the best and most popular vim plugins
