### ISSUE TITLE
Idiosyncratic use of full URL required for vim-projectionist

### ISSUE THREAD

**Issue by Per48edjes** [junegunn/vim-plug#1073]
**Note:** This is more of a question than a true bug as I see that, in the docs, [there exists the option to use full URLs](https://github.com/junegunn/vim-plug/wiki/faq#whats-the-deal-with-git-in-the-url) when specifying plugins to install.

---

Long time Vundle user, first time caller. Decided to make the jump today and I am so pleased how painless has been to migrate! Have immediately found it to be so enjoyable to use thus far.

One curiosity stood out to me: vim-plug (as did Vundle) ignored the specification for Tim Pope's `vim-projectionist` plugin:

```
Plug 'tpope/vim-projectionist'      " this doesn't get picked up by vim-plug
```

Found this to be odd as all other plugins (including Mr. Pope's others) installed without problem. I've checked my spelling (😅 ) about 20 times now, so I don't think I'm 100% off my rocker (yet). Luckily, using the full URL (https://github.com/tpope/vim-projectionist) works just as well (even if aesthetically it's a little less pleasing in my `.vimrc`).

```
Plug 'https://github.com/tpope/vim-projectionist'      " this works and installs fine
```

What am I missing?

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [x] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by janlazo** [comment]
That's unusual. I can download `vim-projectionist` without using full URLs.
It could be a bug if `vim-projectionist` doesn't appear in vim-plug's buffer when installing plugins.

Hard to debug without a minimal vimrc.

**Comment by Per48edjes** [comment]
Ran `PlugInstall` fine (i.e., it detected `tpope/projectionist` and installed it) with the following `.vimrc`:

```vimrc
set nocompatible

"=====================================================
"" vim-plug settings
"=====================================================

" Autoinstaller if vim-plug not installed
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -sfLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall | source ~/.vimrc
endif

call plug#begin('~/.vim/plugged_test')

" Test to see if vim-projectionist will install with abbreviated ref
    Plug 'tpope/vim-fugitive' 
    Plug 'tpope/vim-rhubarb'
    Plug 'tpope/vim-projectionist'
    Plug 'tpope/vim-unimpaired'

call plug#end()
```

I know I had saved my original `.vimrc` to disk before running `PlugInstall` so I'm not sure what caused this transient issue. (Maybe I forgot to source it in my haste...I don't think so, though. 🤔)

Will close this issue, though -- thanks, again, for a great plug-in!
