### ISSUE TITLE
Double quote

### ISSUE THREAD

**Issue by lkjell** [junegunn/vim-plug#1074]
Make it possible to use double quote instead of single quotes such as
`Plug "junegunn/vim-easy-align"`

------------------------------

```

```

- Type:
    - [x ] Bug
    - [ ] Enhancement
    - [ x] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by janlazo** [comment]
Can't you use `call plug#("junegunn/vim-easy-align")`?

**Comment by janlazo** [comment]
`Plug \"junegunn/vim-easy-align\"`

**Comment by lkjell** [comment]
No. Both alternative is ugly. From a user perspective if vundle is able to use double quotes then why cannot vim-plug?

**Comment by junegunn** [comment]
It's a design choice we made earlier to support in-line comments.

https://github.com/junegunn/vim-plug/issues/23

You can't do that with Vundle.
