### ISSUE TITLE
How to install a single plugin (.vim file) only?

### ISSUE THREAD

**Issue by XSven** [junegunn/vim-plug#1075]
The git repository **LucHermitte/lh-misc** contains a _plugin_ directory that contains several plugins. I do not want to install all of them but only the _let-modeline.vim_ plugin. How do I have to setup the **Plug** line in my _.vimrc_ file?

------------------------------

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
It's not supported. Consider maintaining your own fork of the plugin.
