### ISSUE TITLE
The root path cannot be used  /config/vim-config/.vim/plugged 

### ISSUE THREAD

**Issue by jicvi** [junegunn/vim-plug#1077]
Explain the problem here ...

------------------------------

```

```

- Type:
    - [ ] Bug
- OS:
    - [ ] Linux
- Vim
    - [ ] Terminal Vim

call plug#begin('/config/vim-config/.vim/plugged')

Vundle The root path can be used

set rtp+=$VIMPATH/config/vim-config/.vim/bundle/Vundle.vim
call vundle#begin('$VIMPATH/config/vim-config/.vim/bundle')

set rtp+=$VIMPATH/config/vim-config/.vim/autoload/plug.vim
call plug#begin('$VIMPATH/config/vim-config/.vim/plugged')
E492: Not an editor command: PlugInstall

**Comment by janlazo** [comment]
What is `$VIMPATH`?

```vim
set rtp+=$VIMPATH/config/vim-config/.vim/autoload/plug.vim
```
is wrong. `$VIMPATH/config/vim-config/.vim` should be in `rtp` already for Vim to source files in an `autoload/` directory. See `:h 'rtp'`.
