### ISSUE TITLE
Stop turning `syntax on`

### ISSUE THREAD

**Issue by EvanCarroll** [junegunn/vim-plug#1083]
I'm having a problem with the color behind folds. I just spent 2 hours troubleshooting this problem.

**Why?**

Is the goal here just to push a few preferences the developers like with their own plugin manager? This is a bad idea.

**Comment by junegunn** [comment]
The behavior is described here: https://github.com/junegunn/vim-plug#usage

Whether you like it or not, the ship has sailed long time ago and I can't afford to change it to break backward compatibility for many users.

**Comment by EvanCarroll** [comment]
Yes, you can.

This is such a stupid waste of time. No one reasonably expects this out of a plugin manager.

My quest to fix this:

* Use theme in kitty, it doesn't work with vim background.
* Google and find a solution for kitty with `let &t_ut=''`, that doesn't work.
* Remove all background/color/syntax options from my conf
* Set all colors in kitty to #000000
* Start to chop vim apart
   * Remove all vim options
   * Remove all plugins
   * Start to nuke ~/.vim/plugged
   * Isolate this problem to this f aweful plugin manager
   * Search for why it's f aweful.

You've solved your own problem, want to turn `syntax on`, create a plugin. Ship with it even! Document it.

```
call plug#begin('~/.vim/plugged')$
  Plug 'junegunn/vim-preferences'
```

**Comment by junegunn** [comment]
I'm going to block you as you're being disrespectful to a group of people who have voluntarily spent their time for free to create a free, open-source project. Please stay away from my projects.
