### ISSUE TITLE
Question: plug# function name conflicts with my plugins?

### ISSUE THREAD

**Issue by rickalex21** [junegunn/vim-plug#1095]
Explain the problem here ...

------------------------------
**Problem**: The name plug conflicts with my personal plugins.

**Version**: NVIM v0.5.0-dev+30befcdce

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [X] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [X] OS X
    - [ ] Windows
- Vim:
    - [X] Terminal Vim
    - [ ] GVim
    - [X] Neovim
    

Hello, I have personal plugins that I load with packadd. I didn't want to use 'myplug#somefunction'.
Instead I ended up using 'plug'. I already moved a plugin using ```plug#myfunction``` and it seems
to work fine. This should be fine as long as:

1. My plugins don't use a function that you may add in the future.
2. I don't use the names begin,end,helptags,load, and shellescape.

I could rename all the functions in plug.vim to vimplug#begin, vimplug#end,vimplug#helptags ....
but I don't think I want to do that. If you could do that, that would be awesome.

My path looks like this.

```text
~/.vim/pack/rick/opt/plugins/autoload/plug
```

I could also source all my scripts, but I like using packadd for my personal plugins and use vim-plug for
everything else.

What do you think?

Thanks for all the great work.

**Comment by junegunn** [comment]
> Instead I ended up using 'plug'

Why? You should choose another name if you're concerned about any potential name clash. There's no way around it.

**Comment by rickalex21** [comment]
@junegunn Because they are my personal plugins and I wanted to use simple names like plug,buffers, windows etc … If I was distributing my plugins to the public I would use unique names to avoid populating the global namespace with simple names.

Examples of unique names are:

```vim
call dein#add
EasyMotion#
UltiSnips#
```
 
Thanks

**Comment by junegunn** [comment]
We have used this name since 2013. What you're suggesting here is to break tens of thousands of other users' configuration because you want a specific name for your local code. You know that is not an option.

**Comment by rickalex21** [comment]
@junegunn I understand that. That would be a lot to ask. What is done is done, I will do what
I have to do. 

Thanks

**Comment by alopatindev** [comment]
I've got slightly different scenario: for some reason I want to maintain two versions of the same plugin: newest version from git and some old unmaintained fork of the same plugin. Currently it's not possible without renaming the forked plugin.

Something like this would be very handy to have:
```vim
Plug 'something/something'
Plug 'somebody-else/something', {'rename': 'something-fork-by-somebody'}
Plug '~/something-fork', {'rename': 'something-my-fork'}
```
But no idea how challenging is it to implement it properly.
