### ISSUE TITLE
unknown file attribute: ~

### ISSUE THREAD

**Issue by MicroMatrixOrg** [junegunn/vim-plug#1102]
Explain the problem here ...

------------------------------

```
.vimrc:3: unknown file attribute: ~
.vimrc:4: command not found: Plug
.vimrc:5: command not found: Plug
.vimrc:6: command not found: Plug
.vimrc:1: parse error near `\n'
there is my config,
  1 set nocompatible
  2 set nu!
  3 call plug#begin('~/.vim/plugged')
  4 Plug 'kien/ctrlp.vim'
  5 Plug 'vim-airline/vim-airline'
  6 Plug 'morhetz/gruvbox'
  7 call plug#end()
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [x] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by janlazo** [comment]
https://github.com/junegunn/vim-plug#installation
