### ISSUE TITLE
How to disable vim-plug from creating a file called "manager"?

### ISSUE THREAD

**Issue by lebeier** [junegunn/vim-plug#1103]
Recently, I have installed vim-plug, but one thing that annoys me is that it had crippled my vim command to open the file from commandline. Whenever I type `vim filename` it opens a file called `manager`. Is there a way to disable this default behaviour from vim-plug?

------------------------------

```

```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by AdaShoelace** [comment]
It has the same behaviour in Neovim on Debian buster.

**Comment by janlazo** [comment]
Nothing in the plug.vim code creates a file named manager. Lack vimrc to debug.
