### ISSUE TITLE
Show descriptions for installed plugins

### ISSUE THREAD

**Issue by hughesjj** [junegunn/vim-plug#1106]
Hey, is there any way to show descriptions for my installed plugins? If so, could you provide an example?  If not, would it be easy-ish to implement?

Currently, I manually copy-paste or paraphrase the READMEs from the plugin author's github into my `init.vim` so I remember what does what when i come back to edit/tinker with it.

This is a bit arduous, I wind up never updating them, and I was wondering if there was a standardized way to enumerate plugin + descriptions or otherwise walk the list.

I know I can do `:help somecommand` to show docs for certain plugins, but that assumes I know the command to begin with.  Also, for occasions where something breaks, it can be easier to isolate the problem plugin if i could list all descriptions in one command rather than list them individually/as needed.

------------------------------

```
NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-pa
rameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_G
NU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.0/build/config -I/build/neovim/src/neovim-0.5.0/src -I/usr/include -I/build/neovim/src/neovim-0.5.0/
build/src/nvim/auto -I/build/neovim/src/neovim-0.5.0/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [x] Feature Request
    - [x] Question
- OS:
    - [x] All/Other
- Vim:
    - [x] Terminal Vim
    - [x] GVim
    - [x] Neovim

**Comment by Shougo** [comment]
I don't think the feature is so useful. And github API calls are needed to get the information.

**Comment by Shougo** [comment]
I think you should upload example image for the feature.

**Comment by hughesjj** [comment]
Gotcha.  I'm ignorant to the format of vim plugins, and wasn't sure if there was a standardized "description" field available to us.  Feel free to close if there's no standardized way to do so upon installation of a plugin (ex during `:PlugInstall`)

**Comment by Shougo** [comment]
Unfortunately, nothing standard.
Vim plugins has not central repository.
So I have said `you should upload example image`.

**Comment by hughesjj** [comment]
Shoot, well thanks for your time.  I don't think there's anything actionable at this point, I'll close.  Please let me know if you have a donation link of any sorts (willing to donate 20USD for this interaction, hope that's fair), sorry to take up your time.

**Comment by Shougo** [comment]
Don't mind.
