### ISSUE TITLE
How to use 'do'  for  lua function?

### ISSUE THREAD

**Issue by kdurant** [junegunn/vim-plug#1107]
![QQ截图20210712104621](https://user-images.githubusercontent.com/2704364/125223477-6e000e00-e2fe-11eb-9b3d-8b2678c75f07.png)
I use code like below, and these is errors.
```viml
Plug 'git@github.com:preservim/nerdcommenter.git', {'do' : ":lua require('plugins.comment')"}
```

**Comment by b4skyx** [comment]
Bump! Can reproduce.
I also wish to load lua configuration files after the plugin has been loaded. The lua 'require' throws an error as shown by @kdurant

**Comment by wookayin** [comment]
I think there is a bug in command parsing before passing args to `plug#(...)` --- you should escape quotes. Example:
```
... {'do': ':lua require(\"plugins.comment\")'}
```
which is a bit odd.

@b4skyx `do` is post-update/install hook so it won't be executed on loading plugins. Consider using packer.nvim.

**Comment by kdurant** [comment]
> I think there is a bug in command parsing before passing args to `plug#(...)` --- you should escape quotes. Example:
> 
> ```
> ... {'do': ':lua require(\"plugins.comment\")'}
> ```
> 
> which is a bit odd.
> 
> @b4skyx `do` is post-update/install hook so it won't be executed on loading plugins. Consider using packer.nvim.

It can't solve this problem.

**Comment by kdurant** [comment]
Thank you!
