### ISSUE TITLE
PlugInstall fails with Git Version Requirement and missing :endif

### ISSUE THREAD

**Issue by clip222** [junegunn/vim-plug#1108]
This is a new installation on a new Windows 10 computer using Vim 8.2 and Git 2.32.0.   PlugInstall gives the following error:

![image](https://user-images.githubusercontent.com/41396159/125367337-d2d25d00-e32c-11eb-803c-dc7d6fe92f54.png)

------------------------------

![image](https://user-images.githubusercontent.com/41396159/125367467-08774600-e32d-11eb-9dc2-ca2b640bf0a9.png)
![image](https://user-images.githubusercontent.com/41396159/125367625-51c79580-e32d-11eb-9d05-64481f411fb1.png)

- Type:
    - [x ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [x ] Windows
- Vim:
    - [ ] Terminal Vim
    - [x ] GVim
    - [ ] Neovim

**Comment by nikki93** [comment]
Getting this same issue on a new macOS Big Sur computer.

**Comment by timothyas** [comment]
I had the same problem after updating to Big Sur. I ran `:PlugUpgrade` then `:PlugUpdate` while in vim and that fixed everything for me.

**Comment by taohaowei** [comment]
> I had the same problem after updating to Big Sur. I ran `:PlugUpgrade` then `:PlugUpdate` while in vim and that fixed everything for me.

3q，its works for me（It bothered me for two hours)

**Comment by junegunn** [comment]
Please try restarting Vim when you see an error regarding temp files.
