### ISSUE TITLE
suggestion: PlugClean exclusions

### ISSUE THREAD

**Issue by elig0n** [junegunn/vim-plug#1111]
I use the same configuration file to load plugins for both vim and nvim on which I wrap Plug lines with if has('vim') to be loaded only on nvim but yet this will still make them clean candidates when running PlugClean

An exclusion list option may be a possible solution

------------------------------

- Type:
    - [ ] Bug
    - [X] Feature Request
    - [ ] Enhancement
    - [X] Question
- OS:
    - [X] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [X] Terminal Vim
    - [X] GVim
    - [X] Neovim

**Comment by junegunn** [comment]
See https://github.com/junegunn/vim-plug/wiki/tips#conditional-activation
