### ISSUE TITLE
Invalid plug directory

### ISSUE THREAD

**Issue by eck3ko** [junegunn/vim-plug#1112]
Hi! i can not install any plug in, when i type the command :PlugInstall it says:

[vim-plug] Invalid plug directory: M:\.vim\plugged. Try to call plug#begin with a valid directory

i already tried to create the folder by my self and also check the permission of the folder but that didnt help. any ideas???
by looking at the error it seems that is looking the folder in M Drive, is it really doing that? because i do not have any M drive, the first line of my init.vim is:

" *************************** PLUGINS ***********************
call plug#begin("~/.vim/plugged")
  "Plug 'mhinz/vim-startify'
  Plug 'dracula/vim'
  "Plug 'scrooloose/nerdtree'
  "Plug 'kyazdani42/nvim-tree.lua'
  "Plug 'kyazdani42/nvim-web-devicons' " for file icons
  "Plug 'ryanoasis/vim-devicons'
call plug#end()

------------------------------

:version
NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 -DNVIM_TS_HAS_SET_MATCH_LIMIT /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az152-786

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info

------------------------------

- Type:
    - [ x ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ x ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [ x ] Neovim

**Comment by eck3ko** [comment]
I was able to fix the problem by entering the whole path to the file, the home "~/" variable was pointing to a cloud location where i didnt have enough permissions.

**Comment by Pumpkin139** [comment]
emm r u windows?
the windows system can not read the "~" this
Simply replacing ~ with an absolute path should do the trick
