### ISSUE TITLE
Don't load plugins in big files

### ISSUE THREAD

**Issue by ghost** [junegunn/vim-plug#1118]
I'm having trouble with a linter that is making vim go slow on a big file, making it difficult to edit.

It would be useful to have an option that would let me disable a plugin if a file has more lines than a number I specify.

**Comment by virus-found** [comment]
Hey.
This might work:

```
" Restrictions to large files > 2Mb
let s:large_file_size=1000 * 2048
autocmd BufReadPre * let s:f=getfsize(expand("<afile>")) | if s:f < s:large_file_size || s:f != -2 | Plug 'load-plugin-for-small-files' | endif
```

**Comment by junegunn** [comment]
I think this problem should be addressed by the linter plugin.

And there is no generic way to "unload"  a plugin once it's loaded.
