### ISSUE TITLE
`do` doesn't run after "installing" local plugin

### ISSUE THREAD

**Issue by jsatk** [junegunn/vim-plug#1119]
```vim
Plug '~/Developer/coc-metals', {'do': 'yarn install --frozen-lockfile'}
```

Strangely the `do` command there does not run after running `PlugInstall`. What am I missing?

------------------------------

```
VIM - Vi IMproved 8.2
```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [x] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by lars-vc** [comment]
I also have this issue, none of de do commands seem to run

**Comment by junegunn** [comment]
We use the term "unmanaged plugin".

https://github.com/junegunn/vim-plug#example

```vim
" Unmanaged plugin (manually installed and updated)
Plug '~/my-prototype-plugin'
```

vim-plug does not install or update such unmanaged plugins. There is no update, so no post-"update" hook. If you do want vim-plug to "manage" such plugins in your local file system, you can write `Plug 'file:///path-to/my-plugin'` and vim-plug will try to clone the directory to its own plugin repository (e.g. `~/.vim/plugged/my-plugin`). But when you do that, any changes in the original directory become unavailable, you'll have to manually run `:PlugUpdate` to synchronize the directories.

**Comment by lars-vc** [comment]
However I have this issue with managed plugins, telescope-fzf-native and markdown-preview.
Fzf has a do : make and md preview has cd app && yarn install. Neither of these run.

**Comment by junegunn** [comment]
Please see https://github.com/junegunn/vim-plug#post-update-hooks

> you can force it to run unconditionally with the bang-versions of the commands: `PlugInstall!` and `PlugUpdate!`.
