### ISSUE TITLE
fails to Plug* in powershell

### ISSUE THREAD

**Issue by comiluv** [junegunn/vim-plug#1124]
Explain the problem here ...
If the user has set up Vim to use pwsh or powershell, vim-plug fails to respond to the commands PlugInstall, PlugUpdate, PlugUpgrade, PlugClean, etc, but succeeds when Vim is set to use cmd.exe
------------------------------
vimrc shell settings:
```
set shell=pwsh
set shellcmdflag=-NoLogo\ -NoProfile\ -ExecutionPolicy\ RemoteSigned\ -Command
set shellquote=\" shellxquote= 
```
What happens when ```vim +PlugInstall``` on a command line
<img width="866" alt="화면 캡처 2021-08-16 083002" src="https://user-images.githubusercontent.com/19642705/129495895-2b71fca5-1a94-4be0-b8d5-b95dca07479a.png">

```
VIM - Vi IMproved 8.2 (2019 Dec 12, 빌드한 날짜 Aug 11 2021 10:31:39)
MS-Windows 64-bit GUI/console version OLE 지원
포함된 패치: 1-3326
```

- Type:
    - [X] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [X] Windows
- Vim:
    - [X] Terminal Vim
    - [X] GVim
    - [ ] Neovim

**Comment by janlazo** [comment]
Wrong shell settings to use powershell on Vim.

**Comment by comiluv** [comment]
> Wrong shell settings to use powershell on Vim.

Those are correct according to this [stackoverflow answer](https://stackoverflow.com/questions/7605917/system-with-powershell-in-vim)

**Comment by janlazo** [comment]
Those are wrong. Use mine, https://github.com/janlazo/dotvim8/blob/master/shared.vim#L216-L230, or what Vim nightly has.

**Comment by comiluv** [comment]
> Those are wrong. Use mine, [https://github.com/janlazo/dotvim8/blob/master/shared.vim#L216-L230](https://github.com/janlazo/dotvim8/blob/master/shared.vim?rgh-link-date=2021-08-25T02%3A18%3A06Z#L216-L230), or what Vim nightly has.

Thank you, although I had to remove
 ```viml
if has('win32') || has('win32unix')
  let &shellcmdflag = ' ' . &shellcmdflag
endif
```
 to make it work, its no longer giving me error when PlugInstall
