### ISSUE TITLE
Plugins don't get loaded globally 

### ISSUE THREAD

**Issue by thbake** [junegunn/vim-plug#1131]
Hey! I have the problem that my plugins are not loaded globally and instead, every time I open Vim on a directory that doesn't have the .vim directory (which holds the **plugged** and **autoload** directories). 

I would like for all my plugins to load every globally without having to run PlugInstall or PlugUpdate every time I start Vim on a new directory. Is there a way of achieving this? Maybe I overlooked one step. 

Thanks in advance!
------------------------------

```
VIM v8.1, NVIM v0.5
 
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [x ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x ] Terminal Vim
    - [ ] GVim
    - [x ] Neovim

**Comment by janlazo** [comment]
what's the vimrc or init.vim? vim-plug should behave as expected if the `.vim/`, `$HOME`,  directory is at the expected location based on the OS. Maybe you're changing the runtimepath such that vim and vim-plug fail to find plugins.

**Comment by thbake** [comment]
Thanks for answering!

My .vimrc is in the $HOME directory and the init.vim is configured such that the configurations of my .vimrc get passed to it:

.vimrc:

```
set guicursor=
set nohlsearch
set tabstop=4 softtabstop=4
set shiftwidth=4
set nu
set noswapfile
set smartindent
set incsearch
set scrolloff=8
set colorcolumn=80
set signcolumn=yes
set relativenumber
set termguicolors

syntax on
filetype plugin on

let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
 silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
   autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('.vim/plugged')
Plug 'gruvbox-community/gruvbox'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'jiangmiao/auto-pairs'
Plug 'bfrg/vim-cpp-modern'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()
```
init.vim:

```
 set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
source ~/.vimrc
```
The plugins do load when I call :PlugInstall or :PlugUpgrade in whatever directory I am, but before doing that they do not.

I have also noticed that after calling these commands a new .vim directory gets created within the current working directory. I would like to avoid having multiple copies of the .vim directory on every folder I want to use the plugins.

**Comment by junegunn** [comment]
`call plug#begin('.vim/plugged')` -> `call plug#begin('~/.vim/plugged')`

**Comment by thbake** [comment]
That was it! Thanks a lot!
