### ISSUE TITLE
make a Plugins folder or command where can search or explorer plugins?

### ISSUE THREAD

**Issue by frani** [junegunn/vim-plug#1137]
One of the problem that I am having is to find or don't know where explore to see a list of plugins to add to vim

------------------------------

```

```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [x] Feature Request
    - [ ] Question
- OS:
    - [ x] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
As far as I know, there still isn't a cental plugin registry.
VimAwesome was such an effort but I don't think it's actively maintained.
