### ISSUE TITLE
Wrong colors in .vimrc

### ISSUE THREAD

**Issue by wojciechGaudnik** [junegunn/vim-plug#1138]
Hi,
Is there a way to get the same colors in new vim, below one from Ubuntu 20.10 groovy:
![image](https://user-images.githubusercontent.com/32289094/138178554-1029137b-4424-4606-a1e8-081240dea40f.png)
and second from  Ubuntu 21.04 hirsute:
![image](https://user-images.githubusercontent.com/32289094/138178431-a60d2180-1793-4175-b0ad-bd6dc13cc6c2.png)

Precisely I'm asking about "Plug 'vim-scripts/AutoComplPop'" 

In the older version, word Plug was 'vimIsCommand' and string was as 'vimString'
in the newest, both are 'vimUsrCmd'

and I'm 99,9999% :) sure that is the matter of vim version. 

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
I can't reproduce the problem on the latest version of Vim. Please leave a comment if you still have the problem.
