### ISSUE TITLE
Plug Commands are not detected

### ISSUE THREAD

**Issue by IgnFed** [junegunn/vim-plug#1143]
![image](https://user-images.githubusercontent.com/70576040/139391889-abf0d80c-e6dd-437f-821d-cef49951faa7.png)

Only the Plug command appears.

I use Windows 10 and the version of neovim 0.5.0

**Comment by wookayin** [comment]
You probably did not set up plug properly: make sure `plug.vim` exists in your `autoload/` directory.

**Comment by IgnFed** [comment]
I've reseted my PC and no it's working

**Comment by junegunn** [comment]
Perhaps `git` is not available?

https://github.com/junegunn/vim-plug/blob/c9971346bb486ccff354aaee8606cc0d2d5a0c97/plug.vim#L265-L267

**Comment by IgnFed** [comment]
I've wrote bad, i meant "i resetted my PC and now i'ts working"
