### ISSUE TITLE
langmap breaks vim-plug

### ISSUE THREAD

**Issue by benibilme** [junegunn/vim-plug#1145]
Hello, 

I am using turkish-f keyboard and I newly discovered vim langmap feature. I have been long user of vim-plug and I really enjoy using it. 

After setting langmap, everytime I press backspace `<Plug>delimitMateBS`  is inserted into the text. I do not know if this is a vim or vim-plug problem. 

my langmap setting is as follows:

set langmap=kj,jk,mk,çm,th,ğt,ü\\;

**Comment by junegunn** [comment]
The problem is unrelated to vim-plug.
