### ISSUE TITLE
alternative git URL via SSH in additional to via HTTPS

### ISSUE THREAD

**Issue by tigerinus** [junegunn/vim-plug#1146]
Cloning via HTTPS is difficult from a server located within China. However cloning via SSH works fine.

It'd be nice for vim-plug to support SSH based cloning when HTTPS doesn't work.

------------------------------

```

```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [x] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
Put this before the first `Plug` statement.

```vim
let g:plug_url_format = 'git@github.com:%s.git'

Plug '...'
...
```

See https://github.com/junegunn/vim-plug#global-options
