### ISSUE TITLE
PlugClean wants to clean frozen diverged package

### ISSUE THREAD

**Issue by elig0n** [junegunn/vim-plug#1152]
I have a local package which diverged from its remote due to changes I committed. When I run `:PlugClean` it would appear as an invalid plugin prompted for deletion despite having it set `{ 'frozen': 1}`

------------------------------
Latest vim-plug version

- Type:
    - [X] Bug
- OS:
    - [X] Linux

**Comment by junegunn** [comment]
Currently `frozen` only means that vim-plug will not update the plugin. It doesn't mean that vim-plug will not try to inspect it and remove it. But I think it makes sense to make `PlugClean` ignore 'frozen' plugin.
