### ISSUE TITLE
'Function name required' and 'Undefined variable: a:0' error

### ISSUE THREAD

**Issue by jiangjianshan** [junegunn/vim-plug#1153]
hello,
I have build the newest version of vim which is 8.2.4167 on ubuntu20.04, and download the newest  plug.vim from this github.
But after I use the commmand 'vim +PlugUpgrade +PlugUpdate!', The following errors has been appeared:

------------------------------------------- start -------------------------------------------------------------
> vim +PlugUpgrade +PlugUpdate! +CocUpdate
Error detected while processing /home/janssen/.vimrc[251]../home/janssen/.vim/autoload/plug.vim:
line  709:
E129: Function name required
line  710:
E121: Undefined variable: a:0
line  711:
E133: :return not inside a function
Error detected while processing /home/janssen/.vimrc[251]../home/janssen/.vim/autoload/plug.vim[726]../home/janssen/.vimrc[251]../home/janssen/.vim/autoload/plug.vim:
line  725:
E133: :return not inside a function
Error detected while processing /home/janssen/.vimrc:
line  260:
E129: Function name required
line  261:
E129: Function name required
line  264:
E129: Function name required
line  265:
E129: Function name required
line  267:
E129: Function name required
line  268:
E129: Function name required
line  270:
E129: Function name required
line  275:
E129: Function name required
line  276:
E129: Function name required
line  279:
E129: Function name required
line  282:
E129: Function name required
line  285:
E129: Function name required
line  286:
E129: Function name required
line  287:
E129: Function name required
line  290:
E129: Function name required
line  293:
E129: Function name required
line  296:
E129: Function name required
line  299:
E129: Function name required
line  300:
E129: Function name required
line  303:
E129: Function name required
line  306:
E129: Function name required
line  309:
E129: Function name required
line  310:
E129: Function name required
line  311:
E129: Function name required
line  314:
E129: Function name required
line  318:
E129: Function name required
line  319:
E129: Function name required
Error detected while processing /home/janssen/.vimrc[322]..function plug#end[82]..<SNR>12_reorg_rtp:
line    1:
E121: Undefined variable: s:first_rtp
E116: Invalid arguments for function empty(s:first_rtp)
line   21:
E121: Undefined variable: s:first_rtp
E116: Invalid arguments for function empty(s:first_rtp)
Error detected while processing /home/janssen/.vimrc:
line  345:
E185: Cannot find color scheme 'gruvbox'
Press ENTER or type command to continue
--------------------------------------------------- end ----------------------------------------------------

The part of configuration of my .vimrc is here:
![image](https://user-images.githubusercontent.com/20179047/150494570-c2bf64cf-e5ac-481c-9606-4addf52b8394.png)

```

```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by sainnhe** [comment]
Looks like it's a bug of vim, temporary solution: https://github.com/vim/vim/issues/9580#issuecomment-1018051106

**Comment by jiangjianshan** [comment]
@sainnhe , thanks for your solution. After modified the plug.vim, it work now.

**Comment by junegunn** [comment]
https://github.com/vim/vim/commit/e6a4200ff47708febcd7cb2b8c3dd3801a975d43 should fix the problem.

Thanks for the report.
