### ISSUE TITLE
Use vim-plug with portable git

### ISSUE THREAD

**Issue by ForteDexe** [junegunn/vim-plug#1158]
I dont have permission to modify $PATH env on windows, how can I make vim-plug using git portable

Latest vim-plug

- Type:
    - [x] Question
- OS:
    - [x] Windows
- Vim:
    - [x] Neovim

**Comment by Meuhor** [comment]
I have tried change all *git* associateed command in *plug.vim*  to a local variable *git_exec* pointing to the *absolute path of portable git.exe*, which makes it work for portable git. Looking forward to official support for this. By the way, a configurable git mirror is also welcomed.

**Comment by junegunn** [comment]
You can change your `$PATH` in your Vim configuration file.

```vim
let $PATH = '/path/to/git/portable:'.$PATH
```

And vim-plug will use it.
