### ISSUE TITLE
For nvim, why does vim-plug not install plugins in ~/.local/share/nvim/site ?

### ISSUE THREAD

**Issue by stevespages** [junegunn/vim-plug#1162]
Explain the problem here ...
In nvim, the documentation seems to suggest plugins should go in ~/.local/share/nvim/site

It seems that vim-plug creates a directory called plugged in ~/.local/share/nvim/ Then it puts the plugins inside the plugged directories. 

I was wondering if the above is correct and if it is why vim-plug does not install plugins inside the ~/.local/share/nvim/site directory as suggested by (my reading) of the nvim documentation.

------------------------------

```
NVIM v0.6.1
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x ] Question
- OS:
    - [ ] All/Other
    - [ x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x ] Neovim

**Comment by junegunn** [comment]
You're correct. The path was suggested by the maintainer of Neovim. And we're following the guidance.

https://github.com/junegunn/vim-plug/issues/559#issuecomment-265746930
