### ISSUE TITLE
Only the last one works when multiple path are set.

### ISSUE THREAD

**Issue by xyegithub** [junegunn/vim-plug#1165]
When multiple install path are set, the command `PlugInstall` or `PlugClean` only works for the last path.
In the condition of the following config, the commands only work for plugins in `~/.vim_runtime/color_theme` .
```vim
call plug#begin('~/.vim_runtime/my_plugins')
Plug 'git@github.com:dkarter/bullets.vim.git'
Plug 'git@github.com:iamcco/markdown-preview.nvim.git', {'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-
Plug 'git@github.com:honza/vim-snippets.git'
call plug#end()

call plug#begin('~/.vim_runtime/color_theme')
Plug 'git@github.com:altercation/vim-colors-solarized.git'
call plug#end()
```

------------------------------

```

```

- Type:
    - Bug
- OS:
    - Linux

- Vim:

    - Neovim

**Comment by kuuote** [comment]
Why don't you use this option? It can change install directory to any path.
https://github.com/junegunn/vim-plug/blob/master/doc/plug.txt#L207

**Comment by junegunn** [comment]
Multiple `begin~end` blocks are not supported.

@kuuote Thanks for the comment.

**Comment by xyegithub** [comment]
> Why don't you use this option? It can change install directory to any path. https://github.com/junegunn/vim-plug/blob/master/doc/plug.txt#L207

Get it! Thank you!
