### ISSUE TITLE
How to self-develop vim plugins for plug-vim?

### ISSUE THREAD

**Issue by anqin** [junegunn/vim-plug#1166]
I Cannot find any docs to tell how to develop a custom vim plugin which can be managed (installed/loaded) by vim-plug.

Are there any rules should be obeyed?

**Comment by AlxHnr** [comment]
It's pretty much identical to writing a normal Vim plugin. There is nothing special you have to do to be compatible with vim-plug. There are many tutorials on the internet on plugin writing and you can use existing plugins as inspiration. All plugins basically follow the same structure and contain subdirectories like `plugin`, `autoload`, `doc` and so on. These are documented in Vim's build-in help. You just have to push your plugin to GitHub and that's all that has to be done to be installable via vim-plug.

**Comment by AlxHnr** [comment]
If you just want to develop locally, without publishing your plugin, make sure to use absolute paths in your vim config:

```diff
- Plug 'anqin/YourPluginName'
+ Plug '~/YourProjectDirectory/YourPluginName'
```

**Comment by junegunn** [comment]
@AlxHnr Thanks for the comment. 

> + Plug '~/YourProjectDirectory/YourPluginName'

Right. When you do that, vim-plug simply adds the path to `&runtimepath`, making the code available to Vim without PlugInstall or PlugUpdate.
