### ISSUE TITLE
vim-plug does not detect changed plugins in sourced files

### ISSUE THREAD

**Issue by openjck** [junegunn/vim-plug#1168]
Given a configuration like the following:

**$XDG_CONFIG_HOME/nvim/init.vim**

```vim
call plug#begin()
execute "source $XDG_CONFIG_HOME/nvim/plugins/general.vim"
call plug#end()
```

**$XDG_CONFIG_HOME/nvim/plugins/general.vim**
```vim
Plug 'tpope/vim-commentary'
```

If a plugin is added to or removed from *$XDG_CONFIG_HOME/nvim/plugins/general.vim* while Neovim is running, and then a vim-plug command is run (e.g., `PlugInstall` or `PlugClean`), vim-plug will report that there is nothing to do.

However, if `:source $XDG_CONFIG_HOME/nvim/init.vim` is manually run before running a vim-plug command, vim-plug will behave as expected.

------------------------------

```
NVIM v0.4.4       
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-u4YhjF/neovim-0.4.4=. -fstack-protector-strong -Wformat
 -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMI
N_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissi
ng-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GEN
ERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-u4YhjF/neovim-0.4
.4/build/config -I/build/neovim-u4YhjF/neovim-0.4.4/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-u4YhjF/neov
im-0.4.4/build/src/nvim/auto -I/build/neovim-u4YhjF/neovim-0.4.4/build/include
Compiled by team+vim@tracker.debian.org
                                        
Features: +acl +iconv +tui             
See ":help feature-compile"             
                                       
   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by AlxHnr** [comment]
This is expected behavior and not the responsibility of vim-plug. If you want to make your vim config hot-loadable, you can achieve this by using autocommands. Here is an untested example config:

```vim
" Setup an augroup to prevent autocmds to be duplicated/stacked on every reload.
augroup initvim | autocmd! | augroup END

" Reload your init.vim every time it gets saved/written to disk.
autocmd initvim BufWritePost ~/.config/nvim/init.vim source %

" Reload your settings when updating general.vim. I intentionally reload only the main init.vim here
" instead of just reloading general.vim alone. This ensures a cleaner reload with no side-effects.
autocmd initvim BufWritePost ~/.config/nvim/plugins/general.vim source ~/.config/nvim/init.vim
```

That way, every time you write your init.vim, it gets reloaded and all the settings are reapplied. You just have to make sure that you don't mess up the usage of augroups in all your other autocmds.

**Comment by openjck** [comment]
I see. Thank you very much for the detailed explanation!
