### ISSUE TITLE
conflict with yaml indent and tab setting 

### ISSUE THREAD

**Issue by connectluole** [junegunn/vim-plug#1171]
Explain the problem here ...
**what:**
vim-plug will make yaml file edit in vim insert mode be auto indent, details is:
- constant 2 space tab even set the tabstop/softtabstop to 4
- auto indent , it's annoying , this setting should not be done by vim-plug , especailly not inform me.
- if you comment below 2,3,4 lines in yaml in the line begin:
```
1   hello:
2      world:
3            yaml:
4                here
```
   it will be:
```
1   hello:
2      #world:
3      #     yaml:
4      #          here
```
as you see above shown , the # is not in the begin! it auto indent 2 , this is really unexpected.
- other format file seems not affected , python tab is ok.

**debug found reason**
     `425   filetype plugin indent on`
this line cause this issue i guess due to after i comment out this line , the yaml edit is normal.
i am very sure  this line caused this error , because i delete all the plugin and delete all my vimrc except vim-plug begin/end and dummy betweend them.

**how to re generate this issue**
1. pure vim 8.2 with no vimrc lines ;
2. only install vim-plug latest version
3. add below tab config in your vimrc, which make tab be 4:
    set tabstop=4
    set softtabstop=4
5. edit new.yml , try type   below:
    `hello:`
then carriage return to see what happens, it must will auto indent with 2 space 

------------------------------

```

```

- Type:
    - [yes] Bug
- OS:
    - [yes] Linux
- Vim:
    - [yes] Terminal Vim
![Snipaste_2022-04-13_22-51-43](https://user-images.githubusercontent.com/16472308/163208569-51e510e5-0480-45cd-9301-b5f9f56ff351.png)

**Comment by junegunn** [comment]
Vim is trying to do you a favor, providing filetype-specific indentation rules. But it's unfortunate you don't like it.
You can turn the setting off by adding `filetype indent off` after `plug#end()`. See https://github.com/junegunn/vim-plug?tab=readme-ov-file#usage
