### ISSUE TITLE
Cound you add a new option 'post-load'?

### ISSUE THREAD

**Issue by sunn4room** [junegunn/vim-plug#1173]
After `plug#end()`, I always write some plug-related configs. But If a plugin has not been downloaded locally, the config associated with the plugin will run without the plugin loaded and may generate errors.

So if vim-plug has a option 'post-load', I can write the config like this:

```vimscript
call plug#begin()
...
function! xxx-config()
    ...
endfunction
Plug 'xxx/xxx-plugin' { 'post-load': function('xxx-config') }
...
call plug#end()
```

any suggestions to solve this?...

**Comment by junegunn** [comment]
```vim
Plug 'junegunn/vim-after-object'
  autocmd VimEnter * silent! call after_object#enable('=', ':', '#', ' ', '|')
```

* You can use VimEnter autocmd to run some plugin code after vimrc is processed.
* Thanks to `silent!`, So you won't see any error messages even whn the plugin is not installed.
* If you do need to check if the plugin is actually installed, check if the directory exists like so
    * `isdirectory(g:plugs['nerdtree'].dir)`
