### ISSUE TITLE
[Feature Request] A way to review entire diff

### ISSUE THREAD

**Issue by simonweil** [junegunn/vim-plug#1174]
When I update plugins I like to see what has changed, but the only way to see it is commit by commit after pressing on `D`.
I would like a way to see the entire diff of a plugin that got updated, even opening it directly in Github as the previous and current HEAD commit are known.

Thanks for this very useful plugin!

------------------------------

```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.6.1/share/nvim"

Run :checkhealth for more info
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [x] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [x] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
You can now press enter on the line showing the name of a plugin to see the full diff of the commits. You might want to set up `g:plug_pwindow` like so to see it in a bigger window.

```vim
let g:plug_window = '-tabnew'
let g:plug_pwindow = 'vertical rightbelow new'
```

No GitHub support though, to keep the implementation simple.
