### ISSUE TITLE
Invalid arguments for function plug#

### ISSUE THREAD

**Issue by AbelRguezxd** [junegunn/vim-plug#1177]
Hi. I'm adding a new plugin, but I'm getting this error 
```
Error detected while processing /home/_art/.config/nvim/plugins/bufexplorer.vim:
line    1:
E116: Invalid arguments for function plug#
```

I have the Plug commands in different files where I can nest other related plugins and keep any extra config for them. The bufexplorer plugin is the only one having this problem with this. However if I just do the Plug command directly in the `call plug#begin` it doesn't throw the error, so the plugin is fine. 

```
call plug#begin('~/.config/nvim/plugged')
 source ~/.config/nvim/plugins/tmuxline.vim
 source ~/.config/nvim/plugins/airline.vim
 source ~/.config/nvim/plugins/snippets.vim
 source ~/.config/nvim/plugins/nerdtree.vim
 source ~/.config/nvim/plugins/nerdcommenter.vim
 source ~/.config/nvim/plugins/startify.vim
 source ~/.config/nvim/plugins/coc.vim
 source ~/.config/nvim/plugins/ultisnips.vim
 source ~/.config/nvim/plugins/bufexplorer.vim "not working
 Plug 'jlanzarotta/bufexplorer' "working
call plug#end()
```

For a comparison with other working vim files
```
" ~/.config/nvim/plugins/ultisnips.vim
Plug 'SirVer/ultisnips'
```

```
" ~/.config/nvim/plugins/bufexplorer.vim
Plug 'jlanzarotta/bufexplorer'
```

------------------------------

```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [X] Question
- OS:
    - [ ] All/Other
    - [X] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [X] Neovim

**Comment by junegunn** [comment]
Could be caused by a typo.

Can you post the exact content of `/home/_art/.config/nvim/plugins/bufexplorer.vim`?
