### ISSUE TITLE
Using Plug command in a $XDG_CONFIG_HOME/nvim/plugin file is not working

### ISSUE THREAD

**Issue by neur1n** [junegunn/vim-plug#1180]
Explain the problem here ...
------------------------------
I have a file, $XDG_CONFIG_HOME/nvim/plugin/n_plug.vim, which contains the `call plug#begin()`, `Plug 'some/plugin'`, `call plug#end()` lines. Such configurations made all the listed plugins loaded when they were in init.vim, but not in the n_plug.vim file. It seems that I can use `Plug 'some/plugin', {'on': []}` and `call plug#load('plugin')` to make a plugin loaded, but I don't understand why the addtional `call plug#load()` is needed. I've also tried to debug vim-plug but couldn't found the reason.

```
NVIM v0.7.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az320-113

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [x] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
Looks like the problem is that by doing so you effectively have multiple `plug#begin ~ end` blocks, and vim-plug doesn't support it.

See https://github.com/junegunn/vim-plug/issues/1016#issuecomment-2177447597
