### ISSUE TITLE
vim-plug alters indentation settings, since owners wont fix let's at least notify the user on install

### ISSUE THREAD

**Issue by tecfu** [junegunn/vim-plug#1182]
## Issue:

- As previously reported https://github.com/junegunn/vim-plug/issues/379, vim-plug unexpected sets `filetype plugin indent on` here:
https://github.com/junegunn/vim-plug/blob/8fdabfba0b5a1b0616977a32d9e04b4b98a6016a/plug.vim#L425

- The author has previous [stated](https://github.com/junegunn/vim-plug/issues/1053#issuecomment-748628684) that they reserve the right to  be opinionated about design and will not fix this issue.

- But it is reasonable that many, if not most people aren't expecting their plugin manager to cause indentation changes.

## Proposed Next Steps:

Can we add a text notification after `:PlugInstall` that informs the user that vim-plug may cause a side effect with indentation due to setting `filetype plugin indent on`?

If  you will merge it, I am willing to submit the PR. I'm thinking something *after* here: https://github.com/junegunn/vim-plug/blob/8fdabfba0b5a1b0616977a32d9e04b4b98a6016a/plug.vim#L1113

## Reasoning:

- The existing [documentation about this](https://github.com/junegunn/vim-plug/blob/8fdabfba0b5a1b0616977a32d9e04b4b98a6016a/README.md?plain=1#L94) is easy to overlook. 

- Consider that a user might encounter this issue (as I did) after configuring indentation long after installing `vim-plug`. Because this behavior has nothing to do with package management, users are unlikely to consult vim-plug documentation in an effort to resolve it. Adding a notification after `:PlugInstall` will raise visibility of this issue and increase the likelihood that users can link this issue to vim-plug.

## Also Note:

This tool is an incredible accomplishment. We are undoubtedly grateful for the author's work and how much time it has saved thousands of people. We just want to further that effort.

Thank you.

---

- Type:
    - [ ] Bug
    - [X] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [X] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [X] Terminal Vim
    - [X] GVim
    - [X] Neovim

**Comment by Shougo** [comment]
> Can we add a text notification after :PlugInstall that informs the user that vim-plug may cause a side effect with indentation due to setting filetype plugin indent on?

I think the message is just annoying to update pllugins.

> The existing [documentation about this](https://github.com/junegunn/vim-plug/blob/8fdabfba0b5a1b0616977a32d9e04b4b98a6016a/README.md?plain=1#L94) is easy to overlook.

User may not read the documentation, but it is just users fault.
Because it is already documented.

**Comment by junegunn** [comment]
Thanks for the suggestion but I agree with @Shougo.

[The usage section](https://github.com/junegunn/vim-plug#usage), which comes right after the installation instructions, contains only 6 sentences. That's by no means too long. I would not recommend using vim-plug before reading it. If one doesn't like the described behavior, they can revert the settings as described, or even choose a different plugin manager.

**Comment by Shougo** [comment]
Note: the bold text may help users if the texts are important.

**Comment by dansgithubuser** [comment]
I been toying with https://github.com/prabirshrestha/vim-lsp, and that pointed me to vim-plug. I was also surprised and [did not read the 6 lines in the readme](https://github.com/junegunn/vim-plug/issues/1184#issuecomment-1149927653). I understand the justification for the behavior from [here](https://github.com/junegunn/vim-plug/issues/379#issuecomment-267800458).

I'm curious if you're of the mind that, history ignored, you'd rather have it the other way around. Personally I think explicit is better than implicit... I'd rather see the indent config line right after `call plug#end()` in the main readme.

Keeping history in mind, I wonder if the readme can just be a bit more direct? Rather than separating the explanation about `plug#end()` from its use in the example, put the explanation and mitigation right in the example.

**Comment by junegunn** [comment]
@dansgithubuser 

> Personally I think explicit is better than implicit

That's understandable. There are trade-offs. Explicit is not always better than implicit, and vice versa.

Back when I started this project, Vundle was the de-facto standard plugin manager of the community, and this was how their documentation looked like.

* https://github.com/VundleVim/Vundle.vim/blob/f8fdaebb8ac81a59ce96446952d64e706bc0827e/README.md#quick-start

The extra 5 lines before and after were presented without any explanation, and some of the lines were tagged "required". And 99% of the users at the time were copy-pasting these lines into their vimrc without understanding what they were for. I didn't like the situation and it is one of the motivations that drove me to write vim-plug. So the brevity of the configuration is at the heart of vim-plug.

Fast-forward 9 years, do I regret the decision? No. I still think the current behavior is a good default. I don't have hard stats, but I can confidently say that most users prefer to have the syntax highlighting and file-type-specific indentation settings enabled. The default should be designed for the majority of the users. The majority of the users can have concise vimrc and everything works "automagically", yet the minority can still tweak the settings as they like.

> put the explanation and mitigation right in the example

That's a good point, will do.
