### ISSUE TITLE
Feature Request: Add a post plugin loading hook

### ISSUE THREAD

**Issue by abdalrahman-ali** [junegunn/vim-plug#1185]
Provide a post plugin loading hook - typically used to configure the plugin - like the `config` hook provided by packer.nvim.

**Comment by Shougo** [comment]
It is dup of https://github.com/junegunn/vim-plug/issues/1134 ?

**Comment by abdalrahman-ali** [comment]
Yes, I think so.
This comment explains it well: https://github.com/junegunn/vim-plug/issues/1134#issuecomment-1150688529

**Comment by abdalrahman-ali** [comment]
Duplicate of https://github.com/junegunn/vim-plug/issues/1134
