### ISSUE TITLE
On-demand loading on both conditions not working

### ISSUE THREAD

**Issue by gonzaru** [junegunn/vim-plug#1187]
Explain the problem here ...

Hello,

I'm trying to use the both on-demand conditions way, but as I understand, with the below command is supposed to load the plugin only if I use :GoFmt and the &filetype is go, but the results is that it loads vim-go plugin anyway without using :GoFmt manulally first. (looks like it uses the 'for' condition without the 'on').

Way to reproduce:

 Plug 'fatih/vim-go' { 'on': 'GoFmt', 'for': 'go' }

On the other hand, alone works as expected and does not load the plugin.

 Plug 'fatih/vim-go' { 'on': 'GoFmt' }

Regards,

------------------------------

```
version 9.0 patch 1-49

```

- Type:
    - [x ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ x] OS X
    - [ ] Windows
- Vim:
    - [ x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
> with the below command is supposed to load the plugin only if I use :GoFmt and the &filetype is go

No, the plugin is loaded when either of the conditions is met.
