### ISSUE TITLE
Plugins not fully disabled after commenting/removing

### ISSUE THREAD

**Issue by Subbeh** [junegunn/vim-plug#1189]
Plugins are not fully disabled after commenting them out or even removing them from my vimrc file.

I have been busy debugging an issue where auto-indent is not working correctly and is caused by one of the plugins that is loaded.

After removing each of the plugins from between the `call plug*` lines, the issue persists. Only after removing the entire plugin section, including the `call plug*` lines is the indenting issue gone.

```
call plug#begin('$XDG_DATA_HOME/vim/plugged') <-- removing plugged fixes the issue

  Plug ... <-- removing plugins does not help

call plug#end()
```

vim config [here](https://github.com/Subbeh/dotfiles/tree/master/vim/.config/vim)

------------------------------

```
VIM 9.0
```

- Type:
    - [X] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [X] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [X] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
https://github.com/junegunn/vim-plug#usage

That's probably because plug#end() enables indent setting for filetype plugins. You can disable it as described in the section.

**Comment by Subbeh** [comment]
Adding the `filetype indent off` option or running it in vim unfortunately doesn't help. The only way I seem to be able to fix it is by either removing plugged entirely or running `set indentkeys-=0#` inside a vim instance (doesn't work in vimrc)

**Comment by junegunn** [comment]
Check the output of `:scriptnames` to see the list of plugin directories loaded.

**Comment by Subbeh** [comment]
> Check the output of `:scriptnames` to see the list of plugin directories loaded. Vim will not load any of the plugins under `plugged` if there's no `Plug` statements.

These files are loaded additionally with just the call function and `filetype ident off` enabled (no plugins):

 ~/.dotfiles/vim/.config/vim/autoload/plug.vim
 /usr/share/vim/vim90/ftoff.vim
 /usr/share/vim/vim90/ftplugin.vim
 /usr/share/vim/vim90/ftplugin/yaml.vim
 /usr/share/vim/vim90/indent.vim
 /usr/share/vim/vim90/indent/yaml.vim

**Comment by Subbeh** [comment]
Sorry, I think I had the `filetype indent off` at the wrong place. I disabled the plugins and it looks like it's working now.
