### ISSUE TITLE
E492: Not an editor command: PlugInstall

### ISSUE THREAD

**Issue by evesdropper** [junegunn/vim-plug#1197]
I'm setting up neovim on my computer and I keep getting `E492: Not an editor command: PlugInstall` whenever I try to run `:PlugInstall`. I installed using powershell (and the file exists in `nvim-data/site/autoload` and this was the original result. Then I read online about adding adding `plug.vim` to `/autoload` like some of the issues stated, but again, this did not work as well. I thought this was perhaps a Git Bash problem, but it seems that it doesn't work when running nvim on Powershell either. If there's anything I missed or anything wrong with my setup, please let me know. Thanks!

------------------------------

```
NVIM v0.7.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az276-503

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

- Type:
    - [X] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [X] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [X] Windows
- Vim:
    - [X] Terminal Vim
    - [ ] GVim
    - [X] Neovim

**Comment by evesdropper** [comment]
My bad - I forgot to `source` the file I was calling the plugin installations. 😅 

It works fine after making sure I did that.

**Comment by abhi-k9** [comment]
Can you explain your solution in more detail?
