### ISSUE TITLE
Probably a user error

### ISSUE THREAD

**Issue by pepperoni42069** [junegunn/vim-plug#1199]
Im getting ''' E5112: Error while creating lua chunk: C:\Users\deven\AppData\Local\nvim\init.lua:17: '=' expected near 'plug' ''' this error.

```
NVIM v0.7.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az276-503

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

```
- Type:
    - [x] Bug
    - [x] Question
- OS:
    - [x] Windows
- Vim:
    - [x] Neovim

**Comment by igbanam** [comment]
What does your `init.lua` look like?
