### ISSUE TITLE
How to install vim plug ?

### ISSUE THREAD

**Issue by suvirbhargav** [junegunn/vim-plug#120]
Hi,

I added the setup file to auto load folder. Now i'm getting the error: `Not an editor command: PlugInstall`
As i see, you do call : `plug#begin('~/.vim/plugged')`
But my vim folder has no `plugged` directory. Do i need to install anything else to get the plug.

Regards
Suvir

**Comment by kingluddite** [comment]
I wasted two hours on this and could not figure it out. I'm embarrassed to share but hope my ignorance will save others time. I switched from Vundle to Plug and when I was trying to install plugins I was typing `:PluginInstall` instead of `:PlugInstall`

Shameful in Shangrila

**Comment by benfranklin79** [comment]
@kingluddite Just to make you feel better I did something similar when switching from Vundle to Plug. I didn't spend two hours but long enough to feel some degree of shame.

**Comment by kingluddite** [comment]
@benfranklin79 Misery loves company. Thanks for electricity.

**Comment by rebuilt** [comment]
I was also having trouble installing on a new machine. The :PlugInstall command did not work.  I corrected the issue by installing git before running :PlugInstall.

**Comment by aseemxandr** [comment]
> I wasted two hours on this and could not figure it out. I'm embarrassed to share but hope my ignorance will save others time. I switched from Vundle to Plug and when I was trying to install plugins I was typing `:PluginInstall` instead of `:PlugInstall`
> 
> Shameful in Shangrila

Do I type PlugInstall in VIM or in terminal
In Vim is get error `not an editor command : PlugInstall`
In terminal I get error `PlugInstall: command not found`

**Comment by janlazo** [comment]
> > I wasted two hours on this and could not figure it out. I'm embarrassed to share but hope my ignorance will save others time. I switched from Vundle to Plug and when I was trying to install plugins I was typing `:PluginInstall` instead of `:PlugInstall`
> > Shameful in Shangrila
> 
> Do I type PlugInstall in VIM or in terminal
> In Vim is get error `not an editor command : PlugInstall`
> In terminal I get error `PlugInstall: command not found`

@aseemxandr You do not have `autoload/` in your `~/.vim` or you did not put download https://github.com/junegunn/vim-plug/raw/master/plug.vim and put it in `~/.vim/autoload/plug.vim` or you silenced errors from vim-plug because `plug#begin()` will not define `:PlugInstall` command if git is missing or your Vim build is missing some features. If vim-plug is installed correctly and your environment and Vim build are all good, then you can run `PlugInstall` after `call plug#end()`.

**Comment by Wei-Mao** [comment]
> > > I wasted two hours on this and could not figure it out. I'm embarrassed to share but hope my ignorance will save others time. I switched from Vundle to Plug and when I was trying to install plugins I was typing `:PluginInstall` instead of `:PlugInstall`
> > > Shameful in Shangrila
> > 
> > 
> > Do I type PlugInstall in VIM or in terminal
> > In Vim is get error `not an editor command : PlugInstall`
> > In terminal I get error `PlugInstall: command not found`
> 
> @aseemxandr You do not have `autoload/` in your `~/.vim` or you did not put download https://github.com/junegunn/vim-plug/raw/master/plug.vim and put it in `~/.vim/autoload/plug.vim` or you silenced errors from vim-plug because `plug#begin()` will not define `:PlugInstall` command if git is missing or your Vim build is missing some features. If vim-plug is installed correctly and your environment and Vim build are all good, then you can run `PlugInstall` after `call plug#end()`.

Thanks a lot ! Installing git fixes this issue!

**Comment by chrisseanhayes** [comment]
WINDOWS USERS
whenever you see a file ref to `~/.vim` change it to `~/vimfiles`
vim is looking for these file in a different folder when on Windows

**Comment by ppdouble** [comment]
I was trying to install `wakatime/vim-wakatime` using `vim-plugin`.

Download and install with:
`curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim`

1. Modify `~/.vimrc` with:
```text
""""""""
" for vim-plug plugin manager
call plug#begin()
Plug 'wakatime/vim-wakatime'
call plug#end()
```
2. In vim, run `:so ~/.vimrc`
3. Re-open vim with proxy like `ALL_PROXY=socks5://127.0.0.1:1080 vim` 
4. run `:PlugInstall` in vim
And vim-waktime is installed in `~/.vim/plugged` folder.
