### ISSUE TITLE
It gives me E492 when using :PlugInstall

### ISSUE THREAD

**Issue by pleaseBcool** [junegunn/vim-plug#1203]
Explain the problem here ...

It gives me E492 when using :PlugInstall
------------------------------
My nvim folder:
![nvim 16_08_2022 12_19_41](https://user-images.githubusercontent.com/105559885/184856521-b821354f-544a-41a3-86c7-4f8e40da177e.png)
nvim-data:
![nvim 16_08_2022 12_20_23](https://user-images.githubusercontent.com/105559885/184856629-f0b3128e-62e2-4de2-bfcc-df49018c41e4.png)

```
NVIM v0.7.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilado por runneradmin@fv-az276-503

Features: -acl +iconv +tui
See ":help feature-compile"

```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [x] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by meop** [comment]
You have git installed and in PATH?

**Comment by igbanam** [comment]
```
							*E492*
  Not an editor command ~

You tried to execute a command that is neither an Ex command nor
a user-defined command.
```

More like are you sure vim-plug is installed correctly? I see you're in Neovim. Checkout #1218 for how someone used vim-plug in Lua

**Comment by thouger** [comment]
> You have git installed and in PATH?

solve the problem

**Comment by junegunn** [comment]
Make sure plug.vim is located in the right directory.

https://github.com/junegunn/vim-plug?tab=readme-ov-file#windows-powershell-1
