### ISSUE TITLE
post-update hook error lua

### ISSUE THREAD

**Issue by 0rtz** [junegunn/vim-plug#1207]
Hello, can not run post-update hook with the following installation https://github.com/EdenEast/nightfox.nvim/issues/203#issue-1355923330. 
Trying to call a command which defined as:
```vim
command! NightfoxCompile lua require('nightfox').compile()
```
Can it be a problem that it is mapped to a lua function? 

version:
```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by 0xRZ** [comment]
Calling explicitly after install from neovim works without error

**Comment by junegunn** [comment]
Related #1257 

Please let me know if you still have the issue with the latest version of vim-plug.
