### ISSUE TITLE
Plugins storage location??

### ISSUE THREAD

**Issue by Vanillma** [junegunn/vim-plug#1209]
Explain the problem here ...

------------------------------

```
Hello... no matter what I search, I couldn't find the place where the plugins installed by the plug are saved... it seems they are not in my .vim and home folder!!
So where are they??
Thanks
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ✓] Question
- OS:
    - [ ] All/Other
    - [ ✓] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ✓] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
It depends on your platform. You can check`:echo g:plug_home`
