### ISSUE TITLE
How to un-install plug-ins?

### ISSUE THREAD

**Issue by suvirbhargav** [junegunn/vim-plug#121]
Hi,

Is there a way i can uninstall plugins? May be removing single plugin or all plugins. 

Thanks
Suvir

**Comment by ashnur** [comment]
That didn't work for me in neovim.

**Comment by junegunn** [comment]
Make sure to reload your `init.vim` which should contain both `plug#begin` and `plug#end`. Or just restart nvim.

**Comment by ashnur** [comment]
I did reload `init.vim` and restarted neovim, but it didn't help. Eventually I deleted the plugin manually from `plugged`

**Comment by junegunn** [comment]
> and reports status ok

It indicates plug block is not correctly reloaded.

And what does `:PlugStatus` say now?

**Comment by ashnur** [comment]
Given the fact that since I uninstalled and installed neovim, I am not sure it's still relevant what it says. :)
But I checked with `:PlugStatus` both before and after I deleted it manually and first it said `OK` and then it just disappeared.

**Comment by junegunn** [comment]
We have test cases for PlugClean and no one has reported the problem, so I presume it was caused by a mistake or some misconfiguration.

**Comment by oluckyman** [comment]
Just tried in vim. Commenting lines with `Plug ...` does not work for me. Had to remove these lines from begin-end block to make PlugClean delete the plugins.
Anyway it should be section in README.md how to unisntall

**Comment by junegunn** [comment]
@oluckyman I guess you forgot to reload your vimrc. Because there's no difference between commented lines and non-existent lines in Vimscript.

vim-plug was written to replace Vundle and I assumed that the users should be familiar with the way Vundle works. But that was 3 years ago, and now we're seeing new users with no prior experience with Vundle and I can imagine that some things are not so obvious to them. I'll consider adding some tutorial stuff to README page or Wiki page. Thanks for the suggestion.

**Comment by oluckyman** [comment]
thanks for your efforts 🍉

**Comment by rlue** [comment]
@junegunn thanks so much for your work. If it makes it any easier for you, here is a proposed update to the “Commands” table in the README:

```markdown
| Command                             | Description                                                        |
| ----------------------------------- | ------------------------------------------------------------------ |
| `PlugInstall [name ...] [#threads]` | Install plugins                                                    |
| `PlugUpdate [name ...] [#threads]`  | Install or update plugins                                          |
| `PlugClean[!]`                      | Uninstall plugins (remove entries from `.vimrc` and source first)  |
| `PlugUpgrade`                       | Upgrade vim-plug itself                                            |
| `PlugStatus`                        | Check the status of plugins                                        |
| `PlugDiff`                          | Examine changes from the previous update and the pending changes   |
| `PlugSnapshot[!] [output path]`     | Generate script for restoring the current snapshot of the plugins  |
```

If this wording isn't precise enough for you, I'd be happy to rework it. 

Just migrated over from Pathogen. vim-plug is awesome!

**Comment by junegunn** [comment]
Thanks, I added a simple tutorial page to the wiki.

https://github.com/junegunn/vim-plug/wiki/tutorial

**Comment by markstos** [comment]
"Uninstall" is a basic function that should be at least mentioned in the README, Right now, searching for "uninstall" in the README yields no results:  https://github.com/junegunn/vim-plug/

**Comment by crizzy9** [comment]
I am still unable to Uninstall plugins this way in Neovim. I tried commenting it and removing it after i ran `:source ~/.config/nvim/init.vim` inside of neovim but it still seems to have the package.

**Comment by chbrandt** [comment]
Just had the same problem. Deleting only `nerdtree/` from my plugins directory didn't work either; even after removing the `Plug` call from `init.vim`, it (_neovim_) would not Clean (and even PlugInstall from out-of-nowhere!).

Anyhow, everything _was solved_ after closing all `nvim` instances and removing the plugins directory (in my case): `~/.local/share/nvim/plugged`. `PlugInstall` again and good to go (;

**Comment by arnthorla** [comment]
> Delete the Plug line(s) from your `.vimrc`, source the `.vimrc` and call `:PlugClean`

This, worked (like it should). But importantly, only after **restarting** vim.
