### ISSUE TITLE
How can I host my plugin on GitLab?

### ISSUE THREAD

**Issue by Invertisment** [junegunn/vim-plug#1217]
I've searched for "gitlab" in this repository and there were no topics on that.
So I want to know how can I host my plugin on gitlab instead of github? Other source hosting systems are also fine.

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] macOS
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by mschilli87** [comment]
[The example in the `README` ](https://github.com/junegunn/vim-plug#example) starts like this:

```vim
call plug#begin()
" The default plugin directory will be as follows:
"   - Vim (Linux/macOS): '~/.vim/plugged'
"   - Vim (Windows): '~/vimfiles/plugged'
"   - Neovim (Linux/macOS/Windows): stdpath('data') . '/plugged'
" You can specify a custom plugin directory by passing it as the argument
"   - e.g. `call plug#begin('~/.vim/plugged')`
"   - Avoid using standard Vim directory names like 'plugin'

" Make sure you use single quotes

" Shorthand notation; fetches https://github.com/junegunn/vim-easy-align
Plug 'junegunn/vim-easy-align'

" Any valid git URL is allowed
Plug 'https://github.com/junegunn/vim-github-dashboard.git'
```

So I see no reason why you shouldn't be able to replace `github.com` by `gitlab.com` or any other host for your `*.git` repo.
