### ISSUE TITLE
Reduce data it downloads

### ISSUE THREAD

**Issue by Tranquility** [junegunn/vim-plug#122]
You can use sparse checkouts (to download only the directory specified in "rtp") and shallow clone (to not download the full history) to drastically reduce the data it needs to download.

This is especially important with big repositories like rust. For exacmple: 

```viml
 Plug 'rust-lang/rust', {'rtp': 'src/etc/vim'}
```

**Comment by junegunn** [comment]
Closing by #218.

**Comment by junegunn** [comment]
The patch was reverted. The discussion will continue on #217.
