### ISSUE TITLE
执行PlugInstall时，报错：列表索引超出范围：2

### ISSUE THREAD

**Issue by xooch95** [junegunn/vim-plug#1221]
Explain the problem here ...

![image](https://user-images.githubusercontent.com/22408894/198981278-34a25eae-683e-42d3-8434-97008e2dbb57.png)
![image](https://user-images.githubusercontent.com/22408894/198981518-d101d226-7c38-45a5-b536-684d25b1e39d.png)

------------------------------

```
let s:is_win = has('win32')
let $v = $HOME.(s:is_win ? '\vimfiles' : '/.vim')

" Plug
let s:bundle_dir = $v.'/bundle'
call plug#begin(s:bundle_dir)
    Plug 'junegunn/vim-plug'
    Plug 'yianwillis/vimcdoc'
call plug#end()
```

```

```
![image](https://user-images.githubusercontent.com/22408894/198980570-fd20fb0d-5e00-4da3-97f8-fb77ecb4f2fa.png)

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] macOS
    - [x] Windows
- Vim:
    - [ ] Terminal Vim
    - [x] GVim
    - [ ] Neovim

git version:
git version 2.36.1.windows.1
cpu: x86_64
built from commit: e2ff68a2d1426758c78d023f863bfa1e03cbc768
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

**Comment by Arnie97** [comment]
What do you get when you run `:!git version` in GVim?
