### ISSUE TITLE
LInk is not opening

### ISSUE THREAD

**Issue by pripatfatcat** [junegunn/vim-plug#1224]
https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim 
~link is not opening
![Screenshot from 2023-01-12 18-09-37](https://user-images.githubusercontent.com/122454256/212069621-a4b95e96-806f-4dd3-9139-342059263415.png)

Terminal Vim
Linux Mint

**Comment by pripatfatcat** [comment]
the link to the raw file is not opening

**Comment by d-vignesh** [comment]
facing the same issue on mac os. @pripatfatcat where you able to resolve the issue

**Comment by d-vignesh** [comment]
This was because the ISP that i was using has blocked raw.githubusercontent.com site, trying with a different ISP solved the issue.

**Comment by Aj-Seven** [comment]
- Use VPN, URL is blocked in Jio Reliance ISP.
