### ISSUE TITLE
Can't find init.vim

### ISSUE THREAD

**Issue by irregularAbjad** [junegunn/vim-plug#1228]
I use *NeoVim* (unmodified so far) and I can't find my **init.vim**, please help.

**Comment by syrupsandwich** [comment]
Check step 7 under initialization. https://neovim.io/doc/user/starting.html#initialization

**Comment by Aj-Seven** [comment]
- It should be in the path $HOME/.config/init.vim

**Comment by CCurl** [comment]
I had that same question ... it can be the init.lua for neovim.
