### ISSUE TITLE
Generic On-Demand Loading

### ISSUE THREAD

**Issue by igbanam** [junegunn/vim-plug#1232]
We currently have on-demand loading for Plug triggers and for filetypes. I think it may be beneficial to have some generic on-demand loading.

Usage would be something like so

```
vim9script

# snipped ✂️  for brevity

Plug 'igbanam/bob.vim', { 'when': 'InBazelProject' }

def g:InBazelProject(): bool
  # function body ... snipped ✂️ 
enddef
```

This is just one example. Ideally, people should be able to craft any set of preconditions to load a plugin. The only requirement maybe could be that the function referenced in the `'when'` clause must meet two strict requirements

1. Must receive no arguments
2. Must be global — i.e. `g:FuncName`
3. Must return a `bool`

&nbsp;

---

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [x] Feature Request
    - [ ] Question
- OS:
    - [x] All/Other
    - [ ] Linux
    - [ ] macOS
    - [ ] Windows
- Vim:
    - [x] Terminal Vim — this is what I use, but I don't see why this feature can't apply to all
    - [ ] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
When should vim-plug call the function? For that to work, vim-plug needs to call the function on every Vim event, and that is neither possible nor practical.

To load a plugin on a custom event, see https://github.com/junegunn/vim-plug/wiki/tips#loading-plugins-manually
