### ISSUE TITLE
Support python requirements in remote plugins

### ISSUE THREAD

**Issue by eyalk11** [junegunn/vim-plug#1240]
I tried to install my plugin , and it doesn't seem to support python requirements (download the required etc).

This is the repo.
```
call plug#begin('C:\\Users\\User\\vimfiles\\plugged')
Plug 'eyalk11/nvim-voicerec'
call plug#end()
```
https://github.com/eyalk11/nvim-voicerec

- Type:
    - [ ] Bug
    - [X ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] macOS
    - [X ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [ X ] Neovim

**Comment by Shougo** [comment]
You can use this.
https://github.com/junegunn/vim-plug/blob/master/doc/plug.txt#L291-L291

**Comment by eyalk11** [comment]
It is true. But I think this is a functionality the plugin manager should ideally have.

**Comment by junegunn** [comment]
It would be easier to see what's going on under the hood if you use a function like so (maybe with some logging).

```vim
" You don't have to write the full path as the working directory is automatically set to the plugin directory
function! Dependencies()
  !pip install -r requirements.txt
  UpdateRemotePlugins
endfunction

Plug 'udalov/kotlin-vim', { 'do': { -> Dependencies() } }
```

**Comment by junegunn** [comment]
Also, instead of having users to define the function, your plugin can provide it as a autoload function, so the users can just write:

```vim
Plug 'eyalk11/nvim-voicerec', { 'do': { -> voicerec#install() } }
```
