### ISSUE TITLE
Multiple post install commands with "do"

### ISSUE THREAD

**Issue by PezCoder** [junegunn/vim-plug#1243]
### What?
I have a usecase where as part of installing coc.nvim through Plug, I want to specify multiple dependencies to be installed which are:
1. `:CocInstall <bunch of plugins>`
2. `!brew install watchman`
I'm unsure in terms of how to do that as `do` only support providing a single command.

------------------------------

### Minimal config
```vimrc
call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release', 'do': ':CocInstall coc-tsserver coc-json coc-css coc-html coc-pyright coc-styled-components'}
" I want to add 'brew install watchman' as a dependency when coc.nvim is installed
call plug#end()

```

### `:version`
```
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@Mac-1650023513425.local

```

- Type:
    - [ ] Bug
    - [x] Enhancement
    - [x] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by hashue** [comment]
coc.nvim, there is a variable called g:coc_global_extensions, and you can use that variable to automatically install LS.

so, you can write only `brew install watchman` to `do` of vim-plug

**Comment by junegunn** [comment]
You can specify a function as the post-update hook.

See https://github.com/junegunn/vim-plug/issues/944

**Comment by PezCoder** [comment]
Ah thanks, this worked! Thanks!

This is what I used for the above usecase:
```vimrc
" How post update hook works
" https://github.com/junegunn/vim-plug/blob/master/README.md#post-update-hooks
function! PostInstallCocNvim(info)
  if a:info.status == 'installed' || a:info.force
    !brew install watchman
    CocInstall coc-tsserver  "... other plugins
  endif
endfunction

Plug 'neoclide/coc.nvim', {'branch': 'release', 'do': function('PostInstallCocNvim') }

```
