### ISSUE TITLE
vim-plug buffer inside popup window

### ISSUE THREAD

**Issue by YuFei29** [junegunn/vim-plug#1247]
Hello, everyone. I wonder how can I open vim-plug buffer inside a popup window? I mean after `PlugInstall` I can get a popup window like this
<img width="920" alt="Screenshot 2023-07-15 at 13 22 36" src="https://github.com/junegunn/vim-plug/assets/125109356/dc01f64c-2a54-4a46-af68-0f7b5025958c">

I know there's a g:plug_window option, I searched vim help, seems like it only support normal window (vertical and horizontal).
No functional enhancements, just aesthetic considerations, I want this.

**Comment by benjaminchristie** [comment]
A solution using lua:
```
    local w = [[width = math.ceil(vim.api.nvim_get_option("columns") * 0.8), ]]
    local h = [[height = math.ceil(vim.api.nvim_get_option("lines") * 0.8), ]]
    local r = [[col = math.ceil(vim.api.nvim_get_option("columns") * 0.1 - 1), ]]
    local c = [[row = math.ceil(vim.api.nvim_get_option("lines") * 0.1 - 1), ]]
    local floating_opts = [[relative = 'editor', style='minimal', border = "single"]]
    vim.g.plug_window = [[lua vim.api.nvim_open_win(vim.api.nvim_create_buf(true, false), true, {]] ..
        w .. h .. r .. c .. floating_opts .. "})"
    vim.cmd("PlugUpdate")
--- reset to default vim-plug behavior after opening in new window
    vim.fn.timer_start(5000, function()
        vim.g.plug_window = [[vertical topleft new]]
    end)
```

**Comment by YuFei29** [comment]
thanks for your reply, but I use vim. seems like your solution based on neovim. anyway, thank you

**Comment by junegunn** [comment]
If I'm not mistaken, this is not possible due to the limitation of popup window of Vim. You can't put cursor on it.

See https://github.com/vim/vim/pull/7555.

**Comment by YuFei29** [comment]
Thank you for pointing that out. I think I may have been mistaken. I vaguely recall seeing vim-plug pinned in a floating window in vim, so I must have remembered incorrectly. I probably implemented that previously when I trying out neovim.
