### ISSUE TITLE
How to use submodules with vim-plug

### ISSUE THREAD

**Issue by AbdelrahmanDwedar** [junegunn/vim-plug#1248]
I'm making a plugin that relies on few other repositories that's open source (also plugins to be exact), and it's better for me to have these repositories as submodules and use in the project. So I was wondering if vim-plug would automatically initialize those submodules or if there's a way to enable that.

If there's none inform me so I'll be adding a line for them to add on installation.

Thanks.

**Comment by junegunn** [comment]
It does.

https://github.com/junegunn/vim-plug/blob/ca0ae0a8b1bd6380caba2d8be43a2a19baf7dbe2/plug.vim#L1318
