### ISSUE TITLE
Error when running :PlugUpgrade

### ISSUE THREAD

**Issue by 5S-OMAR-SWEIDAN** [junegunn/vim-plug#1249]
Hello, team!

When I try to run the `:PlugUpgrade` command, I get the following error:
```
Error detected while processing function <SNR>10_upgrade[24]..function <SNR>10_upgrade[7]..<SNR>10_system:
line 24: 
E282: Cannot read from "/tmp/va5hSWS/14"
```

Can you please support?

------------------------------

Your Plug block:
```
Plug 'matze/vim-move'
Plug 'csexton/trailertrash.vim'
Plug 'tpope/vim-eunuch'
Plug 'vim-airline/vim-airline'
Plug 'tpope/vim-obsession'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-sclow'
Plug 'djoshea/vim-autoread'
Plug 'kien/rainbow_parantheses.vim'
Plug 'svban/YankAssassin.vim'
```

The contents of `:version`:
```
VIM - VI Improved 9.0 (2022 Jun 28, compiled Nov 30 2022 12:12:57)
Included patches: 1-976
...
```

- Type:
    - [X] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [X] Linux
    - [ ] macOS
    - [ ] Windows
- Vim:
    - [X] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by FrodoBaggins74524** [comment]
Have you updated Update Plug.vim?

**Comment by 5S-OMAR-SWEIDAN** [comment]
> Have you updated Update Plug.vim?

No, how should I do that?

**Comment by junegunn** [comment]
Not reproducible. Please let me know if you still have the issue.
