### ISSUE TITLE
Handle Remote Plugins for neovim.

### ISSUE THREAD

**Issue by brendanjerwin** [junegunn/vim-plug#125]
http://neovim.org/doc/user/remote_plugin.html#remote-plugin

The Python sample works. I'd love to easily install the soon-to-be-a-torrent of awesome remote plugins for nvim.

As far as I can see, it'd need to know that its a remote plugin, place it into the right directory, and call :UpdateRemotePlugins after making changes.

Perhaps the Plugfile could come back to provide some of the needed meta-data about the plugin? (isRemotePlugin: true, host: python, etc...) If not that, then perhaps a `RemotePlug` function in addition to `Plug` would do the trick. (or, probably, both approaches would be best.)

**Comment by fwalch** [comment]
One example of a remote plugin is [Floobits](https://floobits.com/help/plugins/nvim).

**Comment by bruno-** [comment]
Hi,
I was just trying to setup neovim-floobits plugin locally with neovim and was totally confused to find out that none of the plugin commands (`:Floo...`) work..
So it seems the plugin is not sourced properly..

I found this issue via another one opened on neovim-floobits. I understand this is an "edgy" neovim feature that might not be supported immediately, but just wanted to let you know there are real people out there trying it out.

**Comment by junegunn** [comment]
@bruno- I see, but the installation instruction of the plugin clearly states that the command is required. At this stage, I don't see it as any different from the other plugins that require extra steps in installation such as YCM or vim-proc. I'm not following the development of Neovim, so I don't know what the technical hurdles are, but requiring users to manually execute the command does not seem like the most elegant way possible and probably there's room for improvement.

(Sorry I posted this comment on the wrong issue)

**Comment by starcraftman** [comment]
@junegunn I agree with your assessment. I'd just add that instructions also say a restart is required, I assume only for first install? So even if we added a built in hook, user would still be disrupted by restarting.

@bruno- If you just want automation, like YCM you can just use a simple do hook. Below works.

In your `.nvimrc`: 
`Plug 'Floobits/floobits-neovim', { 'do': function('hooks#floo') }`

Put this in ~/.nvim/autoload/hooks.vim
```vim
function! hooks#remote(info)
  if a:info.status == 'installed' || a:info.status == 'updated' || a:info.force
    UpdateRemotePlugins
    echom "Remember to restart!"
  endif
endfunction
```

Maybe we could put this into the troubleshooting faq?

**Comment by bruno-** [comment]
Hi guys,
thank you for the quick response and helpful responses.

Please feel free to \*not\* treat my previous comment as a request of any kind.. I had a problem and just wanted to inform you. I'm aware vim-plug has other design considerations and target audience.
"Chasing" the latest (neovim) features might not even be the best approach.

That said I was pretty disappointed with that plugin's functionality.
Neovim also seems to have some glitches after the upgrade.. so I'm back to vanilla vim (and I won't need `UpdateRemotePlugins` for some time).

Thanks again for being helpful and responsive!

**Comment by junegunn** [comment]
@bruno- No problem :)

@starcraftman Thanks, but it looks like `UpdateRemotePlugins` is also required [*after* removing the plugin](https://github.com/Floobits/floobits-neovim#removing-the-plugin). So `do` option here would not suffice, and we probably shouldn't tell users to do so. By the way, as for your `hook#remote` function, in this case, if-condition can be omitted. status == unchanged can only be seen when force is set (`PlugInstall!` or `PlugUpdate!`).

**Comment by starcraftman** [comment]
@junegunn Right. Hopefully they rethink that mechanism in future, seems a hassle. 

Thanks for the tip, simplifies things.

**Comment by fwalch** [comment]
@tarruda Are improvements planned/possible regarding the necessary explicit `:UpdateRemotePlugins` calls after installation/uninstallation of a remote plugin?

@bruno- If you want, report these glitches at neovim/neovim, maybe they can be sorted out :-)

**Comment by tarruda** [comment]
> @tarruda Are improvements planned/possible regarding the necessary explicit :UpdateRemotePlugins calls after installation/uninstallation of a remote plugin?

To remove the call we need is some sort of filesystem notification mechanism to trigger calls to `:UpdateRemotePlugins` when one of the directories in the runtime path change(such as when a package manager updates the plugin). There's some [work](neovim/neovim#1791) on a wrapper for libuv filesystem watchers but I'm unsure of the progress.

> . I'm not following the development of Neovim, so I don't know what the technical hurdles are, but requiring users to manually execute the command does not seem like the most elegant way possible and probably there's room for improvement.

This is done because remote plugin hosts are lazily loaded, eg: if a python plugin defines a vimscript command, then the python host will only be loaded when the command is first executed. `:UpdateRemotePlugins` is a command that generates a manifest(which is a vimscript file) containing stubs for the commands/autocommands/functions defined by all remote plugins, these stubs contain the information necessary to spawn the host the first time the plugin is used.

**Comment by junegunn** [comment]
@tarruda 
> To remove the call we need is some sort of filesystem notification mechanism

I see. Do you think that there could be an efficient way to detect the changes and update on startup? Floobits instruction says that a restart is required even after the command. If it's automatically done on startup, it will be easier for the users.

And thanks for the explanation. However, most users don't really care about technical details and just want things to work automagically. An yeah, I'm one of them. :smirk:

One thing that seems strange to me about `:UpdateRemotePlugins` is that it starts with an uppercase letter. It gives the wrong impression that it's a userland command from a plugin rather than being a builtin command.

**Comment by tarruda** [comment]
> I see. Do you think that there could be an efficient way to detect the changes and update on startup? Floobits instruction says that a restart is required even after the command. If it's automatically done on startup, it will be easier for the users.

I havent tested but it may be a valid approach

> And thanks for the explanation. However, most users don't really care about technical details and just want things to work automagically. And yeah, I'm one of them. :smirk:

:+1:  I agree we need to improve the setup for remote plugins. Some other fixes are still needed and I will probably focus on this after neovim/neovim#2076

> One thing that seems strange to me about :UpdateRemotePlugins is that it starts with an uppercase letter. It gives the wrong impression that it's a userland command from a plugin rather than being a builtin command.

The remote plugin infrastructure is implemented in vimscript: https://github.com/neovim/neovim/tree/master/runtime/autoload/remote . They build upon the native msgpack-rpc functions

**Comment by SevereOverfl0w** [comment]
A consideration for vim-plug is the lazy loading feature & it's interaction with lazy loading of plugins.

If a plugin is lazily loaded, :UpdateRemotePlugins will not detect it, and therefore it won't be registered unless you run :UpdateRemotePlugins when in the lazily loaded state.

**Comment by vito-c** [comment]
+1 are there any plans to add support for this? I think `UpdateRemotePlugins` will be around for awhile.

**Comment by starcraftman** [comment]
@vito-c Well I don't think either of us have worked on it since this discussion trailed off, so not in the short term. I'll have a look as time permits, I guess it has become a glaring hole as more neovim users use vim-plug.

**Comment by starcraftman** [comment]
@vito-c or @SevereOverfl0w is there a list of current remote plugins I can test with? Apart from the ensime you linked earlier, build status doesn't seem great.

**Comment by SevereOverfl0w** [comment]
nvim-parinfer.js or the latest unite.vim both use the remote plug in
system.

**Comment by Shougo** [comment]
@SevereOverfl0w The unite.vim remote plugin is for the testing purpose.
It will be removed later.

**Comment by starcraftman** [comment]
After looking into it again, nothing much seems changed. Importantly:
- You still need to restart, even if we call `UpdateRemotePlugins` for you. Additionally, that command can throw exceptions if the provider host is not working/setup right. If those exceptions come out of PlugInstall/Update I can see users being confused like #332 earlier.
- I tried sourcing the manifest post update, but if it was previously sourced (i.e. every time after first) duplicate registrations raise an exception. So it seems we can't really prevent need to restart.

So I'm not sure there is much to do. I did have one idea I guess we could document (maybe under the README YCM section), users could make use of post install hooks for remotes. For example:
```vim
" In user vimrc
function! UpdateRPlugin(info)
  if has('nvim')
    silent UpdateRemotePlugins
    echomsg 'rplugin updated: ' . a:info['name'] . ', restart vim for changes'
  endif
endfunction

Plug 'ensime/ensime-vim', { 'do': function('UpdateRPlugin') }
Plug 'snoe/nvim-parinfer.js', { 'do': function('UpdateRPlugin') }
```

Is that helpful? @SevereOverfl0w or @vito-c

**Comment by SevereOverfl0w** [comment]
We do have one slight issue in how lazy loading won't load the plug in,
therefore UpdateRemotePlugins won't work.

The obvious solution is to not use lazy loading. But that defeats the point
somewhat, I think? Maybe they're lazily loaded or something, no idea...

**Comment by starcraftman** [comment]
@SevereOverfl0w Well, yes, that is a shortage. Isn't that more something nvim should design for though? At current, its just one big manifest with all your plugins sourced at startup. Not much room for selection. Seems like short of us doing some manipulations to the manifest and then generating the required registrations, no lazy for remotes.

**Comment by SevereOverfl0w** [comment]
Is there a way to perhaps load all plugins before running the command?

**Comment by junegunn** [comment]
This:

```vim
" We use noautocmd to avoid triggering BufRead on every plugin
for name in keys(g:plugs) | silent noautocmd call plug#load(name) | endfor
```

Since `plug#load` takes varargs, you can alternatively do it this way,

```vim
call call('plug#load', keys(g:plugs))
```

but only when you use less than 20 plugins due to the limitation of vim varargs.

**Comment by SageEx** [comment]
@junegunn Any updates on this ?

**Comment by junegunn** [comment]
@SageEx Related: #450

**Comment by SageEx** [comment]
Thanks for the link.
