### ISSUE TITLE
Lua support?

### ISSUE THREAD

**Issue by anadon** [junegunn/vim-plug#1258]
There seems to be to mention of or support for lua configuration.  Neovim appears to be moving everything to lua and as a *vim newbie, the split between init.vim and init.lua are killing me.  I see that there are issues filed, but nothing in the README or FAQ.

I'd like there to be a section under https://github.com/junegunn/vim-plug#example that includes a working lua example. 

- Type:
    - [ ] Bug
    - [X] Enhancement
    - [X] Feature Request
    - [X] Question
- OS:
    - [ ] All/Other
    - [X] Linux
    - [ ] macOS
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [X] Neovim

**Comment by anadon** [comment]
Something like this would help: https://gitlab.com/sultanahamer/dotfiles/-/blob/master/nvim/lua/plugins.lua?ref_type=heads

**Comment by junegunn** [comment]
Thanks for the guidance. I added a Lua example section to the README. I'm not actually a Neovim/Lua user, so please let me know if I did something wrong.

https://github.com/junegunn/vim-plug?tab=readme-ov-file#example-lua-configuration-file-for-neovim
