### ISSUE TITLE
Improve for https://github.com/junegunn/vim-plug/wiki/tips#automatic-installation-of-missing-plugins

### ISSUE THREAD

**Issue by dracorp** [junegunn/vim-plug#1264]
Explain the problem here ...

After adding the code from https://github.com/junegunn/vim-plug/wiki/tips#automatic-installation-of-missing-plugins
I get error:
```
Error detected while processing /root/.vim/vimrc:
line   32:
E21: Cannot make changes, 'modifiable' is off: fileencoding=utf-8
```
The line 32:
```
set fileencoding=utf-8
```

Bellow fixed this error:
```
" Run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
            \| PlugInstall --sync |  quit! | wincmd p | source $MYVIMRC
            \| endif
```
Of course, this can only occur in my configuration.

**Comment by junegunn** [comment]
I think it's a little strange to have an option that modifies the current buffer in the global configuration file. How about setting `encoding` instead?

> 	When 'fileencoding' is empty, the same value as 'encoding' will be
>	used (no conversion when reading or writing a file).

So I'll leave the code as it is. But thanks for the suggestion.
