### ISSUE TITLE
Add a command to return vim-plug version

### ISSUE THREAD

**Issue by ridhwaans** [junegunn/vim-plug#1266]
should reflect current installed version i.e. 0.11.0 from https://github.com/junegunn/vim-plug/releases 
Can it get the version without entering vim?  (not plugin version)

**Comment by junegunn** [comment]
vim-plug was designed to be distributed as a single file and it doesn't have a version number in it, so it's not currently possible.

If we really want to do it, we have to add a variable to the file and make sure to manually update it, but I'm not sure if it's worth it.
