### ISSUE TITLE
How do I use VIM-PLUG? Where do I put it? (I'm on Windows 10 and my main VIM folder is at C:/Program Files/Vim and I use Ubuntu to use Linux on Windows Terminal)

### ISSUE THREAD

**Issue by khaledkanan** [junegunn/vim-plug#1284]
Explain the problem here ...

I don't know how to use this. I try to put it in my autoload file in my main vim folder but yet, when I use :PlugInstall it ends up with ```E492: Not an editor command: PlugInstall```
![bandicam 2024-07-03 19-09-39-460](https://github.com/junegunn/vim-plug/assets/107669387/00f0c0bf-7acb-423e-ab75-be3fafcc0f49)

```

```

```

```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [½ ] Linux (I use WSL for Windows)
    - [ ] macOS
    - [X] Windows
- Vim:
    - [X] Terminal Vim
    - [X] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
You should follow the instructions in https://github.com/junegunn/vim-plug?tab=readme-ov-file#installation

**Comment by khaledkanan** [comment]
I asked for help
