### ISSUE TITLE
My plugin don't work until I run PlugUpdate or PlugInstall. 

### ISSUE THREAD

**Issue by Lekebabiste** [junegunn/vim-plug#1290]
My ~/.config/nvim/init.vim file
```
call plug#begin('~/.config/nvim/plugged')

" List your plugins here
Plug 'andweeb/presence.nvim'
call plug#end()

```

```
NVIM v0.10.0                                                                                                                             
Build type: Release                                                                                                                      
LuaJIT 2.1.1720049189
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [X] Linux
    - [ ] macOS
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by Shougo** [comment]
Your plugin does not work until you install the plugin.
What do you mean the issue?

**Comment by Lekebabiste** [comment]
I mean they are installed, but they won't load automatically when I lanch nvim.
https://github.com/junegunn/vim-plug/wiki/faq#plugins-are-not-loaded-unless-i-run-pluginstall-or-plugupdate

**Comment by junegunn** [comment]
> My ~/.config/nvim/init.vim file
> 
> ```
> call plug#begin('~/.config/nvim/plugged')
> 
> " List your plugins here
> Plug 'andweeb/presence.nvim'
> call plug#end()
> ```

* Is that all you have in your `init.vim`?
* Any reason you decided to put `~/.config/nvim/plugged`? Because the argument is [optional](https://github.com/junegunn/vim-plug?tab=readme-ov-file#usage).
* What's the output of `:scriptnames` after you start Neovim?

**Comment by Lekebabiste** [comment]
My complete init.vim file 
```
 
call plug#begin('~/.config/nvim/plugged')

" List your plugins here
Plug 'andweeb/presence.nvim'
call plug#end()

" Configuration des plugins
" Sensible.vim est prêt à l'emploi
" Configuration pour NERDTree

```
I tried to put it for solving the problem but it doesn't.

Here's my output:
```
  1: /usr/share/nvim/runtime/ftplugin.vim
  2: /usr/share/nvim/runtime/indent.vim
  3: /etc/xdg/nvim/sysinit.vim
  4: /usr/share/nvim/archlinux.lua
  5: ~/.config/nvim/init.vim
  6: ~/.config/nvim/autoload/plug.vim
  7: /usr/share/nvim/runtime/filetype.lua
  8: /usr/share/nvim/runtime/syntax/syntax.vim
  9: /usr/share/nvim/runtime/syntax/synload.vim
 10: ~/.config/nvim/plugged/presence.nvim/plugin/presence.vim
 11: ~/.config/nvim/plugged/presence.nvim/autoload/presence.vim
 12: /usr/share/nvim/runtime/plugin/gzip.vim
 13: /usr/share/nvim/runtime/plugin/matchit.vim
 14: /usr/share/nvim/runtime/pack/dist/opt/matchit/plugin/matchit.vim
 15: /usr/share/nvim/runtime/plugin/matchparen.vim
 16: /usr/share/nvim/runtime/plugin/netrwPlugin.vim
 17: /usr/share/nvim/runtime/plugin/rplugin.vim
 18: ~/.local/share/nvim/rplugin.vim
 19: /usr/share/nvim/runtime/plugin/shada.vim
 20: /usr/share/nvim/runtime/plugin/spellfile.vim
 21: /usr/share/nvim/runtime/plugin/tarPlugin.vim
 22: /usr/share/nvim/runtime/plugin/tutor.vim
 23: /usr/share/nvim/runtime/plugin/zipPlugin.vim
 24: /usr/share/nvim/runtime/plugin/editorconfig.lua
 25: /usr/share/nvim/runtime/plugin/man.lua
 26: /usr/share/nvim/runtime/plugin/osc52.lua
 27: /usr/share/nvim/runtime/plugin/tohtml.lua


```

**Comment by junegunn** [comment]
> 10: ~/.config/nvim/plugged/presence.nvim/plugin/presence.vim
>  11: ~/.config/nvim/plugged/presence.nvim/autoload/presence.vim

This shows that your plugin is properly loaded. What made you think it's not loaded?

**Comment by Lekebabiste** [comment]
Because on discord it's not showing my status, it's showing when I update the module.

**Comment by junegunn** [comment]
Can you try completely commenting out the plug section and doing `set rtp+=...` instead in your init.vim?

```vim
" call plug#begin('~/.config/nvim/plugged')
" Plug 'andweeb/presence.nvim'
" call plug#end()

set rtp+=~/.config/nvim/plugged/presence.nvim
```

Does it work this way?

**Comment by junegunn** [comment]
> It doesn't work

So the plugin is not working even when you don't use vim-plug. This clearly shows that the problem you're having is unrelated to vim-plug. You might want to ask for help on the plugin's issue tracker.
