### ISSUE TITLE
Instructions for using a gist as a plugin

### ISSUE THREAD

**Issue by gryftir** [junegunn/vim-plug#136]
I use https://gist.github.com/AndrewRadev/1171559 in my vim setup.  There's a way to do this in neobundle, I'm not sure how to do it with vim-plug.

**Comment by expelledboy** [comment]
@gryftir Here is an alternative

```
if !filereadable(expand('~/.vim/plugin/source.vim'))
        silent !curl -fLo ~/.vim/plugin/source.vim --create-dirs https://raw.githubusercontent.com/suderman/source.vim/master/plugin/source.vim
endif

runtime plugin/source.vim
Source https://gist.githubusercontent.com/AndrewRadev/1171559/raw/7900abbaef6871dd58b2166d6e15cd265808055b/next_motion_mapping.vim
```

@junegunn I would personally love to see this part of vim-plug!!
```
Plug 'gist:AndrewRadev/1171559/next_motion_mapping.vim'
```

**Comment by junegunn** [comment]
@expelledboy 

If you really must:

```vim
Plug 'https://gist.github.com/1171559.git',
      \ { 'dir': g:plug_home.'/next_motion_mapping.vim',
      \   'do': 'mkdir -p plugin && ln -sfv $(pwd)/*.vim plugin' }
```

But I believe gists are there just for giving the idea of how something can be done, and not to be used as legitimate plugins.

> I would personally love to see this part of vim-plug!!
> Plug 'gist:AndrewRadev/1171559/next_motion_mapping.vim'

Thanks for suggestion, but no, I'm not interested in supporting gist plugins and introducing an arbitrary URL format (`gist:` prefix).
