### ISSUE TITLE
PlugUpdate does not handle new branches

### ISSUE THREAD

**Issue by sloria** [junegunn/vim-plug#139]
Ran into a bug when trying to pass the `branch` option with a newly-created branch. It seems that `PlugUpdate` does not fetch new branches because I get the following error:

```
error: pathspec 'issue23' did not match any file(s) known to git.
```

 I had to manually run `git fetch` in the plugin's repo folder before executing `PlugUpdate` for it to work.

**Comment by junegunn** [comment]
Thanks for the report. This is what vim-plug does on update:

```
git checkout -q NEW-BRANCH 2>&1 &&
git pull --progress --no-rebase origin NEW-BRANCH 2>&1 &&
git submodule update --init --recursive 2>&1
```

I'm not completely sure yet but I guess adding `-B` option to the first command will solve the issue.

```
git checkout -q -B NEW-BRANCH 2>&1 &&
git pull --progress --no-rebase origin NEW-BRANCH 2>&1 &&
git submodule update --init --recursive 2>&1
```
