### ISSUE TITLE
Disable colorcolumn highlight in vim-plug window

### ISSUE THREAD

**Issue by jonthn** [junegunn/vim-plug#140]
ColorColumn highlight isn't interesting in the vim-plug window so it would make sense to disable it, maybe there are some other settings that should be disabled in this window by default

I've disabled it in `s:prepare` function below `s:new_window()` by adding this

```
set colorcolumn=0
```

**Comment by junegunn** [comment]
Thanks for the suggestion. You can do it using `FileType` autocmd without editing the source.

```vim
autocmd FileType vim-plug setl colorcolumn=0
```

Yeah, I guess it makes sense for vim-plug to disable the option. But `colorcolumn` is a pretty recent addition to Vim. And if I want to unset it, I first have to check if the option is supported by calling `exists('&colorcolumn')`. So it's doable, but I kind of feel like it doesn't really worth it as it's already not impossible to customize the window using the aforementioned method.
