### ISSUE TITLE
Plugins defined in files sourced by .vimrc aren't auto-loaded

### ISSUE THREAD

**Issue by rothwerx** [junegunn/vim-plug#141]
When doing something like this in .vimrc:
```
" Source a .vimrc.local file if it exists. Allows for machine-local configuration
if filereadable(glob("~/.vimrc.local"))
    source ~/.vimrc.local
endif
```
vim-plug recognizes the Plug statements in the .vimrc.local, but after installing the plugins, they're not automatically loaded when I open vim. I'm not sure if this is a vim thing or a vim-plug thing. It's not a big deal to load the plugin I want, but I'm wondering if there's a way to automatically load it.

**Comment by vheon** [comment]
It should work if you put that line between `call plug#begin()` and `call plug#end()`

**Comment by junegunn** [comment]
Yes, as @vheon mentioned, `plug#begin()` ~ `plug#end()` block shouldn't appear more than once as `plug#begin()` will reset its internal data structures, so you lose all the `Plug` information added from the previous block.

```vim
call plug#begin('~/.vim/plugged')
" Global plugins
" ...

if filereadable(glob("~/.vimrc.local"))
    " Should not contain plug#begin or end
    source ~/.vimrc.local
endif

call plug#end()
```

**Comment by rothwerx** [comment]
Moving the block within the plug#begin() and plug#end() statements does the trick. Thanks!
