### ISSUE TITLE
Dependencies between lazy loaded plugins

### ISSUE THREAD

**Issue by Barthalion** [junegunn/vim-plug#145]
I want to lazy load [CtrlP](https://github.com/ctrlpvim/ctrlp.vim) and its external plugin [Funky](https://github.com/tacahiroy/ctrlp-funky). I expected the following snippet to load both CtrlP and Funky when `:CtrlPFunky` is called:

    Plug 'ctrlpvim/ctrlp.vim', { 'on': [ 'CtrlP', 'CtrlPFunky' ] },
    Plug 'tacahiroy/ctrlp-funky', { 'on': 'CtrlPFunky' }

Unfortunately it results in:

    E492: Not an editor command: CtrlPFunky

It also happens with Airline and plugins it supports. Is there anything that can be done about it?

**Comment by junegunn** [comment]
Hmm right, they shouldn't work. `on` option defines a proxy command for loading the plugin and rerunning the command from the loaded plugin. The second line in your case overrides the proxy command defined from the first line. It is possible that we make vim-plug not to override the previous one but to build the list of plugins to be loaded. Not sure if it's worth the effort though.

At the moment, you can define a proxy command yourself which calls `plug#load()` function.

```vim
Plug 'ctrlpvim/ctrlp.vim', { 'on': 'CtrlP' }
Plug 'tacahiroy/ctrlp-funky', { 'on': [] }

command! CtrlPFunky call plug#load('ctrlp.vim', 'ctrlp-funky') | CtrlPFunky
```

**Comment by junegunn** [comment]
@Barthalion Updated vim-plug to handle such cases. Please upgrade vim-plug and let me know if it doesn't work as expected. Thanks!

**Comment by Barthalion** [comment]
Thank you, works like a charm.

**Comment by alem0lars** [comment]
What is the order between the plugins loaded by `CtrlPFunky`? The same as the line order?

Because in some cases, it's mandatory that the dependency gets loaded before the dependant.

For example with:

```viml
Plug 'ctrlpvim/ctrlp.vim', { 'on': [ 'CtrlP', 'CtrlPFunky' ] },
Plug 'tacahiroy/ctrlp-funky', { 'on': 'CtrlPFunky' }
```

The `ctrlp` plugin is loaded before `ctrlp-funky` plugin because it's in the line above ?

**Comment by junegunn** [comment]
@alem0lars Yes.
