### ISSUE TITLE
API for testing if plugin is installed?

### ISSUE THREAD

**Issue by nfarrar** [junegunn/vim-plug#146]
I looked, but didn't see an API for testing if a plugin has been loaded. Is there a way to do this?

Right now I use a function that checks to see if the plugin's directory is present - but that doesn't actually guarantee that it was loaded. I conditionally load plugin settings (so I can leave extra stuff in there that only gets loaded when needed).

**Comment by junegunn** [comment]
Whether if a plugin is loaded and if it's installed are two separate concerns as vim-plug supports on-demand loading. There's no API for the purpose, but you can figure it out by comparing `g:plugs` variable and `&rtp`.

```vim
" installed?
echo isdirectory(g:plugs['vim-something'].dir)

" loaded?
echo stridx(&rtp, g:plugs['vim-something'].dir) >= 0
```

**Comment by nfarrar** [comment]
thank you :)
