### ISSUE TITLE
How to use custom commands to trigger plugin activation?

### ISSUE THREAD

**Issue by obxhdx** [junegunn/vim-plug#148]
Hi. I'm currently lazy loading fzf with this snippet:
``` vim
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': 'yes \| ./install', 'on': 'FZF' }
nnoremap <Leader>zf :FZF<CR>
```
Today I was trying the `FZFLines` command from the [examples wiki](https://github.com/junegunn/fzf/wiki/examples), but adding `FZFLines` in the lazy-loading config didn't seem to work:
``` vim
Plug 'junegunn/fzf', { 'dir': '...', 'do': '...', 'on': [ 'FZF', 'FZFLines' ] }
nnoremap <Leader>zf :FZF<CR>
nnoremap <Leader>zl :FZFLines<CR>

command! FZFLines call fzf#run({...}) " command definition
```
The `<Leader>zf` mapping works fine, but `<Leader>zl` gives me this error: `E117: Unknown function: fzf#run`.

Could you please give me a hint of what I'm doing wrong?
Thanks for your good work! All your plugins are truly outstanding.

**Comment by junegunn** [comment]
Unfortunately that shouldn't work. When `on` option is given, vim-plug defines a proxy command with the same name that loads the plugin, and reruns the command just loaded from the plugin. Depending on the relative position of `FZFLines` to `plug#end()`, either the proxy command overrides your definition, or your `FZFLines` shadows the one from vim-plug. In either way, it doesn't work the way you want it to.

So what should we do then?
1. I generally recommend against trying too hard to lazy-load everything. fzf loads within a millisecond (on my machine), so it doesn't help that much to defer loading of it.
2. If you really want to, you can update your `FZFLines` command to `call plug#load('fzf')`. However, `plug#load` reloads the plugin regardless of whether the plugin was loaded or not. So you may want to add additional check to see if it's already loaded; `stridx(&rtp, g:plugs.fzf.dir) >= 0`
