### ISSUE TITLE
Lazy loading: on (e.g. Limelight)

### ISSUE THREAD

**Issue by llfm** [junegunn/vim-plug#150]
Hello,

I'm having some trouble to lazy load limelight.
```vim
Plug 'junegunn/limelight.vim', {'on': 'LimeLight'}
```
When I try to execute it (:LimeLight): 
```error
Error detected while processing function <SNR>10_lod_cmd
Not an editor command: Limelight.
```
The way you do, June, in your .vimrc [works](https://github.com/junegunn/dotfiles/blob/master/vimrc#L1215).

vim on terminal ~ 7.4.1-580

**Thanks for the simplicity of your plugins!

**Comment by junegunn** [comment]
There's a typo in your `on` option. It's `Limelight`, not `LimeLight`. Will you try again after fixing it?

**Comment by llfm** [comment]
Oh lord, I hate when this kind of situation happens.. Sorry wasting your issues.
Thank you.
