### ISSUE TITLE
Un-installing plugin results in recurring error

### ISSUE THREAD

**Issue by sjmarshy** [junegunn/vim-plug#151]
Error detected while processing function <SNR>15_define_maps:
    line    3:
    junegunn/vim-pseudocl not found

This error is now showing every time I start vim after un-installing junegunn/vim-pseudocl and running PlugClean. It's not stopping anything else from working, as far as I can see, but obviously it's not ideal

**Comment by Pyrohh** [comment]
Assuming you are using this
https://github.com/sjmarshy/vim/blob/master/.vimrc

then the issue is most likely because vim-oblique requires vim-psuedocl (I can reproduce your issue that way).

**Comment by junegunn** [comment]
Yes, you can't use Oblique alone.

@Pyrohh Thanks!
