### ISSUE TITLE
Get force plugin loading

### ISSUE THREAD

**Issue by jakecraige** [junegunn/vim-plug#153]
I'm unable to get the [dirsettings plugin](https://github.com/mantiz/vim-plugin-dirsettings) working due to the lazy loading. 

I have this:
```
Plug 'mantiz/vim-plugin-dirsettings'
call dirsettings#Install()
```

This gives me an `Unknown function` error, I assume since it's lazy loading it. How can I get this working?

**Comment by junegunn** [comment]
Plugins become available only after `plug#end()`. So you have to relocate the function call so that it appears after `plug#end()`. Or if you really must put it there, you may take advantage of `VimEnter` event which is invoked after .vimrc is completely loaded.

```vim
autocmd VimEnter * call dirsettings#Install()
```
