### ISSUE TITLE
Error while updating plugins (invalid key)

### ISSUE THREAD

**Issue by orlp** [junegunn/vim-plug#154]
When trying to update my plugins I get the following errors:

    Updated. Elapsed time: 5.053988 sec.
    [xxxxxxxxxxxxxxxxxxxxxx]

    - Finishing ... Done!
    x vim-niji:
        error: invalid key: remote.origin.url)
        PlugClean required.
    x vim-repeat:
        error: invalid key: remote.origin.url)
        PlugClean required.
    x vim-textobj-comment:
        error: invalid key: remote.origin.url)
        PlugClean required.
    x vim-textobj-user:
        error: invalid key: remote.origin.url)
        PlugClean required.
    x vim-commentary:
        error: invalid key: remote.origin.url)
        PlugClean required.
    x a.vim:
        error: invalid key: remote.origin.url)
        PlugClean required.
    x nerdtree:
        error: invalid key: remote.origin.url)
        PlugClean required.
    x rust.vim:
        error: invalid key: remote.origin.url)
        PlugClean required.
    x supertab:
        error: invalid key: remote.origin.url)
        PlugClean required.
    x vim-fugitive:
        error: invalid key: remote.origin.url)
        PlugClean required.
    x xterm-color-table.vim:
        error: invalid key: remote.origin.url)
        PlugClean required.
    x OnSyntaxChange:
        error: invalid key: remote.origin.url)
        PlugClean required.
    x rainbow:
        error: invalid key: remote.origin.url)
        PlugClean required.
    x vim-surround:
        error: invalid key: remote.origin.url)
        PlugClean required.
    x vim-nerdtree-tabs:
        error: invalid key: remote.origin.url)
        PlugClean required.
    x vim-bufferline:
        error: invalid key: remote.origin.url)
        PlugClean required.
    x incsearch.vim:
        error: invalid key: remote.origin.url)
        PlugClean required.
    x tagbar:
        error: invalid key: remote.origin.url)
        PlugClean required.
    x vim-easy-align:
        error: invalid key: remote.origin.url)
        PlugClean required.
    x vim-easymotion:
        error: invalid key: remote.origin.url)
        PlugClean required.
    x unite.vim:
        error: invalid key: remote.origin.url)
        PlugClean required.
    x wildfire.vim:
        error: invalid key: remote.origin.url)
        PlugClean required.

Latest version of vim-plug, on Windows 7. My dotfiles directory is located in a directory with spaces in the name (Program Files), that might be related. To reproduce all I have to do is `:PlugClean<CR>:PlugInstall<CR>:PlugInstall`.

**Comment by junegunn** [comment]
Thanks for the report. I don't have a Window PC so I may not be able to promptly look into it. I assume you see the same errors on `:PlugStatus`, right?

**Comment by starcraftman** [comment]
@junegunn I noticed this while testing my branch and decided to test on Linux. This isn't just confined to Windows. Usting stock ruby version & plugin path with a space will cause problems. 

```vim
Error detected while processing function <SNR>3_install..<SNR>3_update_impl..<SNR>3_update_finish..<SNR>3_finish..plug#end..<SNR>3_source:
line    3:
E172: Only one file name allowed: source /tmp/vim space/csv.vim/ftdetect/csv.vim
```

This immediate problem is tied to s: s:source function doesn't escape globbed path at 131ish I believe, but likely will cause a cascade until we identify all places in need of escaping paths.

**Comment by junegunn** [comment]
@starcraftman Good catch. I'm doing space-escaping everywhere using `s:esc` in Vimscript and `esc` in Ruby. `s:source` is one of the two places where I forgot to do so. I'll fix it.

**Comment by junegunn** [comment]
@starcraftman Fixed it!

@orlp We spotted some bugs in escaping paths and fixed it. I'm not sure this will solve your problem, so please test it and let me know if you still run into problems. Thanks!

**Comment by orlp** [comment]
@junegunn I upgraded my vim-plug and did a `:PlugClean<CR>:PlugInstall<CR>:PlugInstall`, but the same problem with the same errors still exists.

**Comment by starcraftman** [comment]
@junegunn I just did a quick test, on Windows the command being executed is:

`cd /d C:\Users\starcraftman\vim\ files\bundle\taghighlight\ && git rev-parse --abbrev-ref HEAD 2>&1 && git config remote.origin.url`

The problem is the \ before the space on `vim\ files`. Without a slash it wouldn't be an issue on Windows, spaces aren't delimiters only backslashes. 

Shell escaping is annoying. Will try to come up with a more portable solution to s:esc(path).

**Comment by starcraftman** [comment]
hi @orlp , do you mind testing a branch of mine with a possible fix. See https://github.com/starcraftman/vim-plug/tree/win_spaces

Please try all standard commands Install, Update, Status and Clean. If it works, we can put this on after my larger PR.

**Comment by orlp** [comment]
@starcraftman  I'll test it today. What do you mean with disabling at least one plug before running?

**Comment by starcraftman** [comment]
@orlp  In your vimrc you list plugins with ` Plug 'user/branch'` format. To temporarily disable one you can put a double quote in front (vimL comment)` "Plug 'user/branch'`. Then run PlugClean and disabled one will prompt to be removed. You can reinstall later by simplying removing quote.

NB: Restart vim between vimrc changes.

**Comment by starcraftman** [comment]
Additional information, appears rtp should not have spaces escaped i.e. '\ ' in the strings. See SirVer/ultisnips#445

**Comment by junegunn** [comment]
@starcraftman Hmm, all the plugins I use work just as expected even when &rtp contains escaped spaces. But they also seem to work fine when the spaces are not escaped. You mean, there are exceptions?

**Comment by starcraftman** [comment]
@junegunn Try using 
```vim
call plug#begin('/tmp/j jjj/bundle')
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets' " Default snippets for ultisnips
call plug#end()
``` 

in your vim config. Won't work. Most plugins probably won't display any issues. Ultisnips in particular has a large python module it is trying to import. That import seems to fail when escaped spaces in rtp.

**Comment by junegunn** [comment]
@starcraftman Okay, thanks for letting me know. I'll fix the code.

**Comment by junegunn** [comment]
@starcraftman Fixed it and added a test case for it. Thanks.

**Comment by starcraftman** [comment]
@orlp Did you try `win_spaces` branch?

**Comment by orlp** [comment]
@starcraftman I'm sorry, I haven't had the time, and when I did I had no access to my windows machine.

Either way, your patch has an error, you're only passing 3 arguments to `substitute`:

![](http://i.imgur.com/Q5J6rhg.png)

(I apologize for the cardinal sin of posting an error message as an image, but gvim really doesn't like copy paste while there's an error.)

After adding the `'g'` flag to the `substitute` call everything worked perfectly.

**Comment by orlp** [comment]
@starcraftman I created a pull request for the change I've made. You can accept that and then pull request for @junegunn master branch.

https://github.com/starcraftman/vim-plug/pull/22

**Comment by starcraftman** [comment]
@orlp K, thanks for testing. I'll just make a new branch to put this change on since that one is so old.

**Comment by starcraftman** [comment]
This will be a little longer. Two things. With that patch, I'm betting a bunch of source errors. I think it should be pushed down to the s:system/s:with_cd area, rather than the broader s:esc func.

Secondly, I was trying to reproduce this on my main Windows, but when I set path into my Program Files directory I get an odd bug where nothing appears to be in the folder but clones fail. I think It's a perm/ownership issues, will investigate so I can reproduce before making PR.

**Comment by orlp** [comment]
Well, I had the issue that `:PlugInstall` doesn't work unless my current working directory is in the git repository containing my vim dotfiles. This happened on the master branch too, however, so it might be an orthogonal issue.

**Comment by starcraftman** [comment]
@orlp So to clarify, even with the patch, you had to do something like `cd C:\Program Files\somewhere` inside GVim in order for `PlugInstall` to work. Is this true?

**Comment by junegunn** [comment]
@orlp @starcraftman I finally got a chance to work on Windows PC, so I looked into the problem. And I just pushed the above commit. Works for me in all cases. Does this work for you?

https://raw.githubusercontent.com/junegunn/vim-plug/fix-154/plug.vim

**Comment by starcraftman** [comment]
@junegunn I'll give that a test, I was testing a fix of the following form. Like you, I think the main issue here was just the with_cd func. I think the other problem above is ownership/write perms into Program Files.

```vim
function! s:with_cd(cmd, dir)
  returrn (s:is_win ? 'cd /d '.s:shellesc(a:dir) : 'cd '.s:esc(a:dir)).' && '.a:cmd
endfunction
```

**Comment by orlp** [comment]
@starcraftman Yes, but it seems for reasons unknown to me that that issue has magically resolved itself when I tried to reproduce it just now. I don't know what the real cause might've been.

**Comment by orlp** [comment]
@junegunn I just gave it a test, and `:PlugClean` doesn't remove any bundles, and just says that everything is already clean.

**Comment by junegunn** [comment]
@orlp What about the other commands? And I can't reproduce the problem of `:PlugClean`. Did you make sure that you reloaded vimrc?

**Comment by starcraftman** [comment]
@orlp It seems to work for me as well. I think you may have run into the issue I had regarding perms. Can you make a new test folder in Program Files to test this cleanly. Lets call it `C:\Program Files\plug vim\plugins folder`, pass that to plug#begin and try install/update/clean etc....

@junegunn Still testing but it looks ok to me I believe.

**Comment by starcraftman** [comment]
@orlp See the second answer [here][http://answers.microsoft.com/en-us/windows/forum/windows_7-files/windows-7-file-explorer-shows-a-non-empty-folder/37b032b1-bfc8-4c09-9d47-9556dde9181c] for information on taking ownership of files from adimn. If you recursively give yourself ownership in the subfolder should be good. Do that before installing stuff.

**Comment by junegunn** [comment]
@starcraftman Viewing the content of a commit in PlugDiff is broken due to the same problem. I'll push another commit.

**Comment by orlp** [comment]
@starcraftman @junegunn What I did was create a new folder at `C:\tmp\vimplug`, and changed my `plug#begin` to `call plug#begin('C:/tmp/vimplug')`.

`:PlugInstall` correctly fills the folder with the modules, but `:PlugClean` doesn't remove anything and claims everything is already clean.

So I doubt this is a permission issue.

**Comment by starcraftman** [comment]
@orlp Unless your Windows PC is radically different than norm, you shouldn't have any permissions to write to any folder under C:\ and not under C:\Users.

A better test would be `C:\Users\username\new folder\vim plugins`.

**Comment by junegunn** [comment]
@orlp I'm a bit confused by your description of what you did. PlugClean should clean what?

**Comment by starcraftman** [comment]
@junegunn Will retest on my system.

Related slight concern from maintenance POV, in the file we now seem to be using escape(), we already have s:esc, s:escrtp, s:shellescape & I remembered a while ago that vim itself has shellescape(). Might be a bit patchwork.

**Comment by junegunn** [comment]
@starcraftman The default shellescape() does more than what's actually needed and caused problems in the past. See https://github.com/junegunn/vim-plug/pull/13

**Comment by orlp** [comment]
@junegunn Oh wow. In the past `:PlugClean` would remove __all__ plugin directories, the behaviour I was used to apparently was a bug. In the latest version it actually does what it was supposed to, I just never realized that what it did on my machine wasn't what was intended.

Knowing this, I haven't found any other issues.

**Comment by starcraftman** [comment]
@orlp Huh? I don't remember any recent version doing that...... 

And wait, are you saying its all fixed using latest master or @junegunn's fix branch?

**Comment by orlp** [comment]
@starcraftman Yes, all is fixed.

**Comment by junegunn** [comment]
@starcraftman Haha, it looks like we're having some miscommunication here. It's apparent though that @orlp is mentioning the fix branch, as the problem was obviously reproducible on the latest master. I'll merge the fix to master.

**Comment by starcraftman** [comment]
@junegunn Well this has been a weird issue to say the least. I haven't seen any issues so I guess merge.

**Comment by junegunn** [comment]
Merged. Thank you all for your support.
