### ISSUE TITLE
Lazy load supertab plugin ?

### ISSUE THREAD

**Issue by fazibear** [junegunn/vim-plug#157]
Hi, 

Is there any way to lazy load `supertab` plugin, when `<tab>` pressed ?

Thanx.

**Comment by junegunn** [comment]
If supertab exposes a `<Plug>` mapping, you can put it on `on` option like follows

```vim
Plug 'supertab', { 'on': ['<Plug>(supertab-something)', '<Plug>(supertab-somethingelse)']}
...
imap <tab> <Plug>(supertab-something)
```

I don't use supertab, so I haven't really checked or tried but you get the idea.
