### ISSUE TITLE
How to lazy load plugin options?

### ISSUE THREAD

**Issue by cparadis6191** [junegunn/vim-plug#158]
I just switched to vim-plug and I have a problem with setting certain options with lazy loaded plugins. Syntastic is an example. Here are the recommended syntastic settings:

```vim
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
```

If I load syntastic with

```vim
Plug 'https://github.com/scrooloose/syntastic.git', { 'on': 'SyntasticCheck' }
```

 and then say jump into a help menu (before loading syntastic) it will complain about

```vim
E117: Unknown function: SyntasticStatuslineFlag
```

Is there a way to set options while loading a lazy plugin? I couldn't find any info on how to do this and my vim-fu is weak. Thanks.

**Comment by junegunn** [comment]
This might work:
```vim
set statusline+=%{exists('g:loaded_syntastic_plugin') ? SyntasticStatuslineFlag() : ''}
```

**Comment by vheon** [comment]
@junegunn It would not work when Syntactic is loaded though.

**Comment by junegunn** [comment]
@vheon Hmm, I don't understand why it should work, I haven't tested though. Could you elaborate? By the way, I have a similar line in my vimrc for fugitive:
```vim
set statusline=%<[%n]\ %F\ %m%r%y\ %{exists('g:loaded_fugitive')?fugitive#statusline():''}\ %=%-14.(%l,%c%V%)\ %P
```

**Comment by vheon** [comment]
@junegunn Oh. I thought of it in a different way. Sorry for the noise.

**Comment by junegunn** [comment]
@vheon No problem. The initial answer was invalid anyway (whitespaces.)

**Comment by cparadis6191** [comment]
Great thanks for the quick responses.

```vim
set statusline+=%{exists('g:loaded_syntastic_plugin')?SyntasticStatuslineFlag():''}
```

does exactly what I needed.
