### ISSUE TITLE
On-demand loading of vim-fugitive

### ISSUE THREAD

**Issue by esn89** [junegunn/vim-plug#164]
Using this command on my .vimrc:

Plug 'tpope/vim-fugitive', { 'on': 'Gstatus' }

will set it so that the fugitive plugin will load when I invoke that command, which, essential is akin to 'git status'

when I do that however, and run :Gstatus, vim says that it isn't a recognized command, which leads me to think that the plugin isn't loaded even when I go :Gstatus. 

Any ideas?

(I'm pretty positive that it isn't a syntax error of any sorts, as i have successfully got CtrlP to do on demand loading)

**Comment by Pyrohh** [comment]
Are you in a git repo when you run `:Gstatus`. If you aren't, vim will say `Not an editor command`.

**Comment by esn89** [comment]
I am for sure in a git repo

**Comment by Pyrohh** [comment]
I can reproduce that, but I'm not sure what the issue is. I assume you got this message as well before the `Not an editor command` error:
```
Error detected while processing function <SNR>2_lod_cmd:
```

**Comment by esn89** [comment]
Hey, 

Yup, that's exactly what I'm getting.

**Comment by vheon** [comment]
You can't load vim-fugitive lazily without some massive hack. The reason is that vim-fugitive detect when you are in a git repo and only then define the commands. If you do `Plug 'tpope/vim-fugitive', { 'on': 'Gstatus' }`, when then you fire the `:Gstatus` command vim-plug load vim-fugitive and then tries to fire the real `:Gstatus` which do not exists because vim-fugitive couldn't do its check for the git repo and so it could not defines the commands. Bottom line, vim-fugitive is not designed to be loaded lazily, so you should not.

**Comment by esn89** [comment]
Aaaah, okay.  That makes sense.  Thanks for your clarifications.

**Comment by junegunn** [comment]
@vheon Thanks for the explanation! :+1:

**Comment by blueyed** [comment]
There is some way to do it, see: https://github.com/junegunn/vim-plug/issues/525#issuecomment-256169881.

**Comment by jeromedalbert** [comment]
Thanks to @blueyed's comment, here's how I lazy load fugitive:

```vim
Plug 'tpope/vim-fugitive', { 'on': ['Gdiff', 'Glog', 'Gblame'] }

command! Gdiff call LazyLoadFugitive('Gdiff')
command! Glog call LazyLoadFugitive('Glog')
command! Gblame call LazyLoadFugitive('Gblame')
command! Gdiff call LazyLoadFugitive('Gdiff')

function! LazyLoadFugitive(cmd)
  call plug#load('vim-fugitive')
  call fugitive#detect(expand('%:p'))
  exe a:cmd
endfunction
```

The `LazyLoadFugitive` function is called only once, the first time it is invoked. After that, vim-fugitive overrides the proxy commands above with the real fugitive ones.

**Comment by kreedz** [comment]
@jeromedalbert
Commands are duplicated:
![1603-gdiff](https://user-images.githubusercontent.com/2128965/37527863-de044390-2954-11e8-969f-775df6509c4b.png)

**Comment by kreedz** [comment]
@jeromedalbert,
It's not a big deal, but when you call one of these defined commands (Gstatus, Gdiff, Glof, GBlame), then those commands will be duplicated in suggested list in command line:
![1603-gdiff](https://user-images.githubusercontent.com/2128965/37529303-a0f10246-2958-11e8-8b8f-ac8093dea322.png)
