### ISSUE TITLE
FuncUndefined autocmd

### ISSUE THREAD

**Issue by justinmk** [junegunn/vim-plug#167]
I just read `:help FuncUndefined` and wondered if you knew about it. It doesn't seem to be mentioned in this repo. It could be useful for implementing the `on` feature of vim-plug.

Reason I mention this is I've noticed the `on` feature doesn't seem to work with some plugins. Possibly it's because those plugins have essential problems, but, as we all know, `on` feature is a workaround to fix buggy (i.e., not autoloaded, or pollute the keymap namespace unreasonably, etc.) plugins in the first place.

For example, dbext plugin:

     Plug 'dbext.vim', { 'on': [ 'DBExecRangeSQL', 'DBExecVisualSQL'  ] }

Seems to have issues if I initiate with `:DBExecRangeSQL`. I will add more details later when I get a chance...

**Comment by junegunn** [comment]
Thanks for letting me know. I didn't know it. But `exists(':CommandName')` was good enough for my purpose.

> I will add more details later when I get a chance...

Thanks. I'll also try out dbext.

**Comment by junegunn** [comment]
Some thoughts on this.

I think this can be used to detect and handle untimely invocation of autoload function before `plug#end()` which is actually a common mistake among the new users of vim-plug. By using this autocmd, we could automatically call `plug#end()` at the point and retry the call. But however tempting the idea may be, it'll encourage poor practice and complicate the &rtp management of vim-plug, I don't think we should do so. (The idea here is partially related to the discussion in #249)

**Comment by vheon** [comment]
> By using this autocmd, we could automatically call plug#end() at the point and retry the call. But however tempting the idea may be, it'll encourage poor practice and complicate the &rtp management of vim-plug, I don't think we should do so. 

If instead of calling `plug#end()` repeatedly we accumulate the autoload functions called before `plug#end()` and call them all together at the end of `plug#end()`? In that way we could basically translate something like:

```viml
call plug#begin()
Plug 'user/foo'
call foo#function()

Plug 'user/bar'
call bar#function()

call plug#end()
```

in

```viml
call plug#begin()
Plug 'user/foo'
Plug 'user/bar'
call plug#end()

call foo#function()
call bar#function()
```

In this way a user can keep the plugin declaration and its configuration closer even if the plugin uses autoload functions for configuring itself.

**Comment by vheon** [comment]
I spoken too early, I didn't thought that `FuncUndefined` do not save the parameters, at least I didn't find a way to save them, so what I proposed early is unfeasible.

**Comment by junegunn** [comment]
@vheon Oops, I missed that too, interesting idea though. Another point we both missed is that a function call is an expression rather than a statement.

```vim
let foo = bar#baz()
if foo == 'foo'
" ...
```
So automatic resolution is probably not possible anyway.
