### ISSUE TITLE
Current master won't `:PlugInstall` on Ubuntu 14.04

### ISSUE THREAD

**Issue by vectorstorm** [junegunn/vim-plug#170]
It claims to be successful, but doesn't actually clone any repositories.

>  1 Updated. Elapsed time: 0.063159 sec.
>  2 
>  3
>  4 - Finishing ... Done!
 
(Other commands, such as `:PlugStatus`, correctly show the set of plugins which *ought* to be installed.)

This issue appears to have started in commit 308fb9bc.  ("Use :pgroup option when starting subprocesses")

This is a little outside my realm of experience, so I'm not sure just why it's going wrong, but I was able to `git bisect` it to the first problematic commit, which hopefully might give somebody else a starting point for tracking down the problem.  

For the moment, under Ubuntu 14.04 at least, the last working revision is 4a96db8.

**Comment by junegunn** [comment]
Sorry for the trouble. I just reverted the commit. I thought it would be fine as it's passing on travis-ci.

**Comment by junegunn** [comment]
I could reproduce the problem on Ubuntu 14.04. Fixing it was easy (`RUBY_VERSION.dup`). However, it turned out that it makes Vim less responsive there contrary to my expectation, so I decided not to reapply the commit. I really appreciate your investigation on this. Thanks!

**Comment by starcraftman** [comment]
@junegunn Well that's dissapointing, too bad.

**Comment by junegunn** [comment]
@starcraftman Yeah, it was totally unexpected, as the new method worked really well on OS X.
