### ISSUE TITLE
“No matching autocommands”

### ISSUE THREAD

**Issue by tsuflux** [junegunn/vim-plug#172]
When loading a plugin prematurely – as shown in the following vimrc – vim will show the warning “No matching autocommands.”

```vim
call plug#begin()
Plug 'kana/vim-arpeggio'
call plug#load('vim-arpeggio')
call plug#end()
```

This is a result of `plug#load()` calling `doautocmd BufRead` as seen [here](https://github.com/junegunn/vim-plug/blob/c74fae9f8ecaae201bf43f7a326b75322e444228/plug.vim#L357) while there hasn’t been any autocommand for `BufRead` defined yet. A simple `silent` should fix this.

**Comment by vheon** [comment]
The question would be: why one would do such thing? The fix for this case is really easy as you suggested but should vim-plug prevent misused feature?

**Comment by junegunn** [comment]
Adding `silent` to vim-plug is easy, but I'm worried that it might also hide important/useful messages that need attention. So I'd suggest just changing the line to `silent call plug#load('vim-repeat')` if you really must.

The only case I can imagine that one would want to call `plug#load()` before `plug#end()` is the case of vim-sensible. One might be tempted to write:

```vim
call plug#begin('/tmp/plugged')
Plug 'tpope/vim-sensible'

" (If the user prefers to interleave plugin settings in vim-plug block)
call plug#load('vim-sensible')
" Override sensible defaults

call plug#end()
```

But loading vim-sensible causes some BufRead events to be set, so you won't see the warning message in this case anyway.

**Comment by vheon** [comment]
I use vim-sensible myself but is easy enough to use it like https://github.com/vheon/home/blob/master/.vim/vimrc#L111

**Comment by tsuflux** [comment]
I realized that putting a `silent` in `plug#load()` is merely a workaround. Maybe wrapping the `doautocmd` with a check on whether there are any `BufRead` autocommands defined is an alternative.

**Comment by junegunn** [comment]
@tsuflux That's the first thing that came to my mind, but realized that simple `exists('#BufRead')` was not enough for the purpose and stopped looking further. You haven't told us why you want to do it in the first place. I think you probably shouldn't.
