### ISSUE TITLE
PlugInstall returns immediately with no error message without installing anything

### ISSUE THREAD

**Issue by vexplore** [junegunn/vim-plug#173]
This is on a CentOS 6.4 machine, with a fairly recent vim 7.4.582 compiled with +ruby support (:echo has('ruby') shows 1; :ruby puts RUBY_VERSION shows 1.9.3.

I copied my .vimrc from an Ubuntu 12.04 box, so :PlugStatus shows all the "Not found. Try PlugInstall". But :PlugInstall returns immediately without installing anything and no error message:

Updated. Elapsed time: 0.068371 sec. 
                                                                                                              
- Finishing ... Done!

Is there a verbose mode that I can turn on to troubleshoot the problem?

**Comment by junegunn** [comment]
Seems like the same problem as #170. Could you upgrade vim-plug and try again?

**Comment by junegunn** [comment]
Confirmed that it's currently fixed and I extended Travis CI build so that these problems can be detected early. Sorry for the trouble.
