### ISSUE TITLE
managing plugins that require autoloading

### ISSUE THREAD

**Issue by jamarr81** [junegunn/vim-plug#178]
Some vim plugins, like [phpcomplete.vim](https://github.com/shawncplus/phpcomplete.vim), contain autoload (/.vim/autoload) scripts. However, when these are installed via vim-plug these do not seem to be taken into account. I'm not sure how to address this other than manually symlinking from /.vim/autoload to the relevant file (in this case ./vim/plugged/phpcomplete.vim/autoload/phpcomplete.vim).

**Comment by vheon** [comment]
Can you post your test case? Because there are test for it and they pass.

**Comment by junegunn** [comment]
> However, when these are installed via vim-plug these do not seem to be taken into account

This is not true, many of the plugins we use daily have most of their code in autoload directory. I'm not sure why you're getting the impression. Maybe you're trying to call an autoload function before `plug#end()` call?
