### ISSUE TITLE
Looking at commits after update

### ISSUE THREAD

**Issue by ianks** [junegunn/vim-plug#180]
Is there currently a mechanism for reviewing diffs from various plugin updates? For example, I would like to press <Enter> on the list of commit changes and view it. This would be an awesome feature IMO, and I may build it out if it isn't there.

**Comment by starcraftman** [comment]
@ianks `PlugDiff` I believe is what your looking for, shows you recent updates to plugins and their log messages.

**Comment by fenuks** [comment]
I have related question to ask, so I thought I won't open separate issue. Can I load all patches in buffer? I know I can move cursor on commit hash and press `<Enter>`, but that's pretty tiresome. I would like to review all changes in all plugins since last update at once.
