### ISSUE TITLE
Commit ID support for options

### ISSUE THREAD

**Issue by pratz** [junegunn/vim-plug#181]
Can we please add commit id support for options similar to branch/tags.

**Comment by junegunn** [comment]
Sorry, but it is not planned. See https://github.com/junegunn/vim-plug/wiki/faq#freezing-plugin-version-with-commit-hash

You can use NeoBundle if you want the feature.

**Comment by junegunn** [comment]
FYI, if you notice something's broken after update, you can try `:PlugDiff` and revert the updated change, and add `frozen` option to the plugin so that it's no longer updated unless explicitly specified.

**Comment by pratz** [comment]
{"frozen": 1} works, thanks
