### ISSUE TITLE
Managing multiple Plugin folders

### ISSUE THREAD

**Issue by webdesserts** [junegunn/vim-plug#182]
Is there any way that a user might be able to manage plugins for multiple directories? I am building a small boilerplate for vim that would have a folder for the "core settings" that are used to get the boilerplate up and running, and another for "user settings" that will can be changed by the user. I would also like there to be a distinction between "core plugins" and "user plugins". I made a quick test to see if it works as is that looked something like this:

```viml
let g:core_packages = '~/.vim/core/packages/'
let g:user_packages ='~/.vim/user/packages/'

call plug#begin(g:core_packages)
Plug 'tpope/vim-repeat'
plug#end()

call plug#begin(g:user_packages)
Plug 'tpope/vim-surround'
plug#end()
```

When I run this only `vim-surround` is installed. Any ideas? I understand if this isn't really on your roadmap.

**Comment by vheon** [comment]
At every call to `plug#begin(...)` all the variables keeping track of your plugins are overwritten so thats a no go. What you can do to activate certain plugins only if some condition are met is:

```viml
call plug#begin(g:all_packages)
if g:core_package
Plug 'tpope/vim-repeat'
endif
if g:user_packages
Plug 'tpope/vim-surround'
endif
plug#end()
```

**Comment by vheon** [comment]
You should look at the discussion at #137 too.

**Comment by webdesserts** [comment]
How would conditionally including plugins allow me to change the directories in which they are installed?

I did just see the `dir` option which get's me halfway there. I could make the default directory `g:user_packages` and maybe do something like this?

```viml
call plug#begin(g:user_packages)
source 'path/to/core/plugins.vim'
source 'path/to/user/plugins.vim'
call plug#end()
```
where `user/plugins.vim` would just be a file containing only the `Plug` commands

```viml
Plug 'tpope/vim-surround'
```

**Comment by webdesserts** [comment]
The only thing that would make this better is if I can find a way to automate tagging the core plugins with the `dir` option. Anyway, I think this solves my problem, so I'm going to go ahead and close this.

**Comment by junegunn** [comment]
@vheon Thanks for the comment :)

@webdesserts Yes you can use `dir` option for the purpose but notice that `:PlugClean` will not be able to handle those. Anyway, I don't plan to support multiple `g:plug_home`s to keep it simple. Thanks.

**Comment by webdesserts** [comment]
@junegunn Ya, I saw that. I figured it would kinda be out of scope for this project. I'm settling on another solution for now. Thanks
