### ISSUE TITLE
Plug depends option (Specify a list of plugins a plugin depends on.)

### ISSUE THREAD

**Issue by alexanderjeurissen** [junegunn/vim-plug#183]
I migrated to vim-plug from NeoBundle. So far i like the simplicity and yet the power vim-plug provides.
One option i really miss is the 'depends' option that is available in NeoBundle.
the documentation of NeoBundle describes this option as follows:
>	Specify a list of plugins a plugin depends on.
>	List items are '{plugin-name}' or ['{plugin-name}', {args}].
>	Those specified in the list are installed automatically.

Below is an example:
```vim
NeoBundle 'mxw/vim-jsx', { 'depends': 'pangloss/vim-javascript' }
```

in case multiple dependencies are present:
```vim
NeoBundle 'Shougo/neocomplcache', {'depends' :
		    \ [ 'Shougo/neosnippet.git',
		    \   'rstacruz/sparkup'
		    \ ]}
```
I think it would be a nice addition to vim-plug to have a `depends` option as it really cleans up your .vimrc (less Plug lines)

**Comment by junegunn** [comment]
Hmm, I'm not convinced, and I don't think the option is in the spirit of vim-plug which tries hard to keep its feature set as small as possible.

I personally don't see how it's different from laying out your code as follows:

```vim
Plug 'mxw/vim-jsx' | Plug 'pangloss/vim-javascript'

Plug 'Shougo/neocomplcache'
  \| Plug 'Shougo/neosnippet.git'
  \| Plug 'rstacruz/sparkup'
```
(okay, having the multiple Plug lines for the same plugin can lead to duplicate entries in `&rtp`, but it's a separate issue of its own)

vim-plug has and will have less features than NeoBundle which is inarguably a great plugin manager. If you do need features from NeoBundle, switching to vim-plug may not be the right path to take. Anyway, thanks for your suggestion.

**Comment by alexanderjeurissen** [comment]
@junegunn so if i understand your correctly, adding a pipe character '|' between two plug statements on the same line achieves the same behaviour ?  if so thanks for pointing that out i wasn't aware of such syntax.

I understand your concerns and motivation of keeping the API small and respect your decision in this mather. thanks for making vim-plug and I'm sure i made the right switch nonetheless.

**Comment by junegunn** [comment]
@alexanderjeurissen I'm not perfectly sure what `depends` option of NeoBundle does, but as far as I can tell from the description, it looks like a syntactic sugar for specifying multiple, related plugins at once.

`|` is not vim-plug-specific, it's just a command separator of Vim. See `:help :bar`.

> I understand your concerns and motivation of keeping the API small and respect your decision in this mather

Thanks for your understanding!

**Comment by vheon** [comment]
@junegunn basically it does the same as the deprecated Plugfile. It declare that one plugin depends on some other plugin, so it loads them before and if those plugin depends on something else it install and load them too.

**Comment by junegunn** [comment]
@vheon Okay, only that the dependencies are manually specified in user's vimrc. I can imagine that it can be helpful in some lazy-loading scenarios. But, as you know, the basic standpoint we have established in that matter is that lazy-loading is merely a workaround for poorly laid-out plugins, and vim-plug shouldn't try too hard doing it.
