### ISSUE TITLE
Duplicate paths in &rtp when the same plugin is specified multiple times

### ISSUE THREAD

**Issue by junegunn** [junegunn/vim-plug#184]
```vim
vim -Nu <(cat << EOF
call plug#begin()
Plug 'junegunn/seoul256.vim'
Plug 'junegunn/seoul256.vim'
call plug#end()
EOF
) +'echo &rtp'

/Users/jg/.vim,/Users/jg/.vim/plugged/seoul256.vim/,/Users/jg/.vim/plugged/seoul256.vim/,/usr/local/share/vim/vimfiles,/usr/local/share/vim/vim74,/usr/local/share/vim/vimfiles/af
ter,/Users/jg/.vim/after
```

We may not need to fix it cause
- it does not break anything
- it is likely the result of a misconfiguration
    - Except, there are users who prefer explicit specification of plugin dependencies, in that case the same entry can appear multiple times
```vim
Plug 'plugin1'
  \| Plug 'plugin0'

Plug 'plugin2'
  \| Plug 'plugin0'
  \| Plug 'plugin1'
```

The fix is trivial, a single `uniq()` call will do, and I don't think it'll have noticeable effect on startup tie.

**Comment by vheon** [comment]
The fix was simpler than you thought :+1:

**Comment by junegunn** [comment]
Yeah, it was :) Thanks for the review.

Whoa, travis build failed. Need to remove `uniq` from the test code.

By the way, FYI, this time I used this script again to check the average startup time.

```sh
#!/usr/bin/env bash

niter=100

rm -f _.log
for _ in $(seq 1 $niter); do
  vim --startuptime _.log +q
  tail -1 _.log >> $vpm.log
done
cat $vpm.log | awk '{ sum += $1 } END { print sum / NR }'
rm -f _.log
```
