### ISSUE TITLE
Why cant I do this?

### ISSUE THREAD

**Issue by AndrieVorster** [junegunn/vim-plug#190]
"Below is my basic --.vimrc--...
"This is the way to do it with Vundle...
"Examples are here: https://www.google.co.za/search?client=opera&q=dotfiles%2F.vimrc+if+!filereadable(%27~%2F.vim%2Fbundle%2Fvundle%2FREADME.md%27)+search+site%3Ahttp%3A%2F%2Fgithub.com%2F&sourceid=opera&ie=UTF-8&oe=UTF-8#q=dotfiles%2F.vimrc+if+!filereadable(%27~%2F.vim%2Fbundle%2Fvundle%2FREADME.md%27)+search+site:http:%2F%2Fgithub.com%2F
"It for what I can understand for some-or-other reason doesn't source my --plug.vim--...
"---- Plug
"Install Plug
let install_Plug=1
let Plug_file=expand('$HOME/.vim/plugged/plug/README.md')
if !filereadable(Plug_file)
	echo "Installing Plug..."
	echo ""
	silent !mkdir -p $HOME/.vim/plugged
	silent !git clone git://github.com/junegunn/vim-plug $HOME/.vim/plugged/plug
	let install_Plug=0
endif

"Add Plug to the runtime path
set runtimepath+=$HOME/.vim/plugged/plug/
"Select plugins to be installed
call plug#begin()
Plug 'rking/ag.vim'
Plug 'sjl/gundo.vim'
Plug 'ntpeters/vim-better-whitespace'
Plug 'altercation/vim-colors-solarized'
call plug#end()
"Install plugins if Plug was just installed
if install_Plug == 0
	echo "Installing Plugins..."
	echo ""
	:PlugClean
	:PlugInstall
	:PlugUpgrade
endif

**Comment by junegunn** [comment]
Because vim-plug is not vundle? :) The repository of vim-plug is not designed to be cloned.
If you want automatic installation, please follow the instruction in the following page:
https://github.com/junegunn/vim-plug/wiki/faq#automatic-installation

**Comment by AndrieVorster** [comment]
Sorry I never saw that... Thanks for your quick reply!!! And thanks for creating the best Vim plugin manager!!!
