### ISSUE TITLE
Missing:curl executable,ruby support or python support

### ISSUE THREAD

**Issue by NixusCN** [junegunn/vim-plug#192]
I had installed python , but when I :PlugUpgrade, the missing tip will be display in the command line.
I check the %PATH%, it's not any wrong.

What's wrong with my vim-plug?
Please help me, thank you very much.

**Comment by junegunn** [comment]
Having Python on your system is different from having Vim with Python support. Looks like your Vim is not compiled with Python support and `:echo has('python')` will print 0. We may improve `:PlugUpgrade` in the future to make use of system python (or ruby) when it's the only option. But for now, you'll have to install curl, or reinstall Vim with Python or Ruby support. Or of course, you can just manually download the latest plug.vim from GitHub.

**Comment by NixusCN** [comment]
@junegunn  Thanks for your reply.
:echo has('python') print 1. 
Sorry, I don't know How to install curl? Which one is the right curl ?

**Comment by junegunn** [comment]
> :echo has('python') print 1. 

Aha, then you don't have to install curl, sorry. I realized that vim-plug unnecessarily disallowed using python for `:PlugUpgrade` on Windows, which I just fixed. Could you manually download the latest [plug.vim](https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim) and retry `:PlugUpgrade`?

**Comment by NixusCN** [comment]
:+1: 
Wow, every thing is ok now! Bingo.
Thanks a lot. I love this plugin!

**Comment by junegunn** [comment]
Great, thanks for the report!
