### ISSUE TITLE
On demand loading for operating system

### ISSUE THREAD

**Issue by oschrenk** [junegunn/vim-plug#197]
Is it possible to add syntax for plug loading based on os? For instance:

```
Plug 'glidenote/newdayone.vim', { 'os': 'darwin' } " write dayone entries
Plug 'rizzatti/dash.vim', { 'os': 'darwin' }       " search in dash
```

Or is it out of scope?

**Comment by vheon** [comment]
what is wrong with:

```viml
if has('macunix')
Plug 'glidenote/newdayone.vim'
Plug 'rizzatti/dash.vim'
endif
```
??

**Comment by vheon** [comment]
Similar question #137

**Comment by oschrenk** [comment]
Is having one line instead of three and be visually be more pleasing a good reason?

I know of `if has('macunix')` and the  likes. Seeing #137, it seems the way for Plug is to be lean, which is not a bad way.

**Comment by vheon** [comment]
> Seeing #137, it seems the way for Plug is to be lean, which is not a bad way.

Yes. I know @junegunn thinks there are too many options for the `Plug` command already.

> Is having one line instead of three and be visually be more pleasing a good reason?

Just to counterpoint this: Is having 5 `Plug`s all with `{ 'on': 'darwin' } better than close them in an `if`?? IMHO it's a lot redundant. But everyone has its taste ;)

**Comment by junegunn** [comment]
@oschrenk We have concluded that the addition of such an option does not give enough benefit to justify the added complexity. You can see more discussion on the topic on #108 and #115. Thanks.

@vheon Thanks for the comment!
