### ISSUE TITLE
Unmanaged plugin path not recognized.

### ISSUE THREAD

**Issue by mlr-msft** [junegunn/vim-plug#205]
I am attempting to develop a Vim plugin and I use git as my SCM. I don't want vim-plug to attempt to install or update the plugin, so I have added this to my `vimrc`:

`Plug '~/vimfiles/wip/vim-myplugin`

Unfortunately, plug-vim still attempts to install the plugin and reports the following when I use the `PlugInstall` command:

```
x vim-myplugin:
    Cloning into 'C:\Users\mirobert\vimfiles\bundle\vim-myplugin'...
    remote: Please upgrade your git client.
    remote: GitHub.com no longer supports git over dumb-http: https://github.com/blog/809-git-dumb-http-transport-to-be-turned-off-in-90-days
    fatal: unable to access 'https://git::@github.com/~/vimfiles/wip/vim-myplugin.git/': The requested URL returned error: 403
```

It seems that vim-plug should recognize that a path starting with a `~` is a local path and that the associated plugin in unmanaged.

I've also tried adding `, {'frozen': '1'}` to the `Plug` statement, which doesn't seem to make a difference.

Thanks in advance!

**Comment by junegunn** [comment]
Thanks for the report. vim-plug have always recognized paths with `~` prefix as local plugins on non-windows platforms, but it had a different rule on Windows.

```vim
if s:is_win
  function! s:is_local_plug(repo)
    return a:repo =~? '^[a-z]:'
  endfunction
else
  function! s:is_local_plug(repo)
    return a:repo[0] =~ '[/$~]'
  endfunction
endif
```
Anyway, the above commit should fix the problem. Could you upgrade and check if it solves the issue?

**Comment by mlr-msft** [comment]
That did the trick! Thanks for responding so quickly.
