### ISSUE TITLE
Plugins are downloaded quicker with Vim than NeoVim

### ISSUE THREAD

**Issue by evanrelf** [junegunn/vim-plug#206]
When I first was using vim-plug a couple weeks ago, NeoVim downloaded plugins seemingly instantly and asynchronously. For some reason, recently NeoVim has slowed to a crawl compared to normal Vim. Normal Vim is still not as fast as what NeoVim once was, but it is much faster than current NeoVim.

NeoVim can check that all plugins are "Already up-to-date." in 42 seconds, while normal Vim reports almost 7 seconds.

I have checked [the FAQ section](https://github.com/junegunn/vim-plug/wiki/faq#plugins-are-not-installedupdated-in-parallel) regarding parallel downloads: NeoVim has `exists('##JobActivity')` and normal Vim has `+python` and `+ruby`. Also, I have installed the Python module thing from `pip install neovim` if that matters.

I've also tried forcing it to download more at once using more threads, but to no effect.

One graphical change I've noticed is that NeoVim adds the plugins to the list one at a time as they are downloaded and installed, whereas normal Vim has all the plugins already in the list from the start, and then updates the status text as their installation progresses.

**Comment by junegunn** [comment]
Hi, sorry about the outdated FAQ entry. Neovim recently changed its job API and vim-plug was updated accordingly:
https://github.com/junegunn/vim-plug/pull/198
With the update, parallel installation on older versions of Neovim is now disabled. You have to either downgrade vim-plug, or install the latest version of Neovim.

**Comment by starcraftman** [comment]
@junegunn We could have a simple message on startup, like how YCM warns to rebuild:

```vim
if has('nvim') && exists('##JobActivity')
  echomsg "vim-plug: update neovim for parallel installer'
endif
```

**Comment by junegunn** [comment]
@starcraftman Good idea. But I think we should print the message on `PlugInstall` or `PlugUpdate`, no need to bother users who aren't planning to update. I'll push a commit.

**Comment by junegunn** [comment]
I also updated the outdated FAQ page. I'll close the issue.

https://github.com/junegunn/vim-plug/wiki/faq#plugins-are-not-installedupdated-in-parallel
