### ISSUE TITLE
Use neovim terminal emulator for 'do' hooks

### ISSUE THREAD

**Issue by euclio** [junegunn/vim-plug#209]
Currently, commands use `!` which works fine, but cannot handle ANSI escape sequences. It would be great to see the CMake output from YouCompleteMe's install script in color instead of seeing a bunch of garbage characters in the output.

Perhaps if people like the current behavior, an option to opt-in to this behavior could be provided?

**Comment by starcraftman** [comment]
@euclio Do you actually want to see all that? It is a long build, you can just run the command in background while you work with ending `&` like normal sh commands.

**Comment by vheon** [comment]
@starcraftman well `:terminal` is a nvim buffer which means that while it's building YouCompleteMe for example I could do other stuff but if something went wrong I can just copy from the buffer and report it. While doing that with `:!` or `&` with the shell is not that friendly.

**Comment by vheon** [comment]
@euclio you can already do it yourself if you use the `funcref` instead of the plain string for `do` hooks.

**Comment by starcraftman** [comment]
@vheon Interesting. Perhaps we could simply have the `:terminal` replace/split the vim-plug buffer so user could watch post hooks. I can see that being neat. That would have to be opt-in though, some people might find it distracting.

**Comment by junegunn** [comment]
- Neovim not correctly showing colors sounds like a bug to me. Have you tried contacting the Neovim team on the problem? We don't need YCM to reproduce the problem. A simple script like [this](https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/tools/screenshotTable.sh) should suffice.
- This need, again, seems very specific to YCM. Correct me if I'm wrong, but I haven't seen any other plugin with such an extensive installation procedure. I do not want to extend vim-plug just because of one exceptional plugin.
- There are non-trivial issues to be addressed
    - Which window to use: A horizontal/vertical split? A tab? Or take over plug buffer? Or should we add another option like `g:plug_window`?
    - AFAIK, there's no way to synchronously wait for the completion of `:terminal` as of now. It's not going to be equivalent to the current behavior in a number of ways. The code becomes harder to test and maintain.
    - A single `PlugInstall` or `PlugUpdate` can invoke multiple post-update hooks at once. Without synchronous execution of each command, we have to either merge multiple post-update hooks into a single chain of commands or to open multiple windows. (sigh)
- Therefore, I don't think I want to do it at the moment as I think it hurts the simplicity of vim-plug without good enough reason. And as @vheon said, we can already do it with funcref. Maybe we should just update [the example on the README page](https://github.com/junegunn/vim-plug#post-update-hooks) so that it uses `:terminal` if `has('nvim')`
- To see what's going on in post-update hooks, we can redirect the output:
    - `Plug 'something', { 'do': 'make > /tmp/something.log' }`

**Comment by vheon** [comment]
@junegunn as much as I'd love to see this, I tried and the `:terminal` feature was not really meant for this, (at least for what I tried). If anyone succeeded in doing it please let me know :+1:

**Comment by euclio** [comment]
I know this can be done with a FuncRef. However, in addition to avoiding having to write a new function for every plugin that has an external installation procedure (e.g., I have a number of plugins that depend on nodejs), I thought that it would be more aesthetically pleasing to have the output appear in another buffer, rather than slowly creeping up the screen at the bottom (lack of color notwithstanding). Additionally, my thought was that the terminal would take over the plug buffer, requiring no additional customization.

It seems to me that not being able to wait on `:terminal` synchronously is a flaw.

Anyways, feel free to close the issue if you're not interested in such functionality.

**Comment by vheon** [comment]
> Additionally, my thought was that the terminal would take over the plug buffer, requiring no additional customization.

I don't understand this part.

**Comment by starcraftman** [comment]
@vheon what @euclio is suggesting is that once we finish the normal update/install (i.e. time elapsed is posted), we then simply replace the vim-plug split with `:terminal` & sequentially run the post install do hooks. I like the idea, as users can watch while working instead of having screen taken over. 

@junegunn Might have been premature, it seems there exists [this](https://github.com/neovim/neovim/blob/master/runtime/doc/eval.txt#L6322-L6332). Looks like you call `termopen()`, get a jobid back & wait on it with jobwait(), rinse & repeat. I might give this a little experiment.

**Comment by junegunn** [comment]
> my thought was that the terminal would take over the plug buffer, requiring no additional customization

@euclio But the plug buffer may contain information that requires further examination (e.g. Some plugins failed to install/update) and it provides useful key mappings like `D`, `R`, `U`, so I don't think we should just discard the buffer.

> in addition to avoiding having to write a new function for every plugin that has an external installation procedure  (e.g., I have a number of plugins that depend on nodejs)

It would be nice if we could define a higher-order function that returns a reference to curried funcref like follows:
```vim
Plug 'foo', { 'do': TermDo('make foo') }
Plug 'bar', { 'do': TermDo('make bar') }
```
But it's not readily possible in Vimscript without some hacks. An alternative is to use the `name` field in the dictionary passed to the function, so we can avoid writing multiple functions although it may not be as elegant as the HOF I mentioned above.

```vim
function! TermDo(info)
  let command = {
  \ 'foo': 'make foo',
  \ 'bar': 'make bar'
  \ }[info.name]
  " ...
endfunction

Plug 'foo', { 'do': function('TermDo') }
Plug 'bar', { 'do': function('TermDo') }
```

@starcraftman Nice find. I'm still not convinced that we should add it vim-plug, but I guess it's worth further investigation.

**Comment by junegunn** [comment]
@starcraftman By the way, I noticed that the neovim team has spotted the cause of the errors we ran into when we tried to apply `jobwait()` on `PlugInstall` during `has('vim_starting')`.

https://github.com/neovim/neovim/issues/2371

**Comment by starcraftman** [comment]
@junegunn Good catch, though seems like that's a ways off from being fixed.

**Comment by vheon** [comment]
For anyone who wants to try:

```viml
function! s:install(cmd)
  if has('nvim')
    botright new

    let install = { 'buf': bufnr('%') }
    function! install.on_exit(id, code)
      execute 'bd!' self.buf
    endfunction

    call termopen(a:cmd, install)

    wincmd p
  else
    execute '!'.a:cmd
  endif
endfunction
```

and then I use it in my `funcref` for installing. So for example YCM:

```viml
Plug 'Valloric/YouCompleteMe', { 'do': function('startup#YCMInstall') }
```

and in `autoload/startup.vim`:

```viml
function! startup#YCMInstall(info)
  if a:info.status == 'installed' || a:info.force
    call s:install('./install.sh --clang-completer')
  endif
endfunction
```

**Comment by vheon** [comment]
I believe that my function from above do not recognise if the build went well and let it know to vim-plug.

**Comment by junegunn** [comment]
@vheon Thanks. It's understandable. It can be unnecessarily complex. (plug buffer might have already been closed, etc.)

We have two *orthogonal* reasons to want `:term` integration:
- Prettier output
    - Nothing wrong with that. I just don't like having to add a considerable amount of code just for Neovim. 
    - If this is the sole purpose, we can make it synchronous with `jobwait()`, but it's currently unstable.
        - Synchronous version should be much more simpler, that we can consider adding it to vim-plug.
    - I talked about how we should open the window, but I guess we can just use a horizontal split below. It's not configurable with `:!` either.
- Asynchronous execution
    - This makes sense for monstrous plugins like YCM.
    - But as I mentioned earlier, it's complicated. It's inconsistent with the original version using `:!` and we lose the testability of the code
    - So I think async should not be the default even if we decide to use `:term` on neovim.
        - User can still write his/her own funcref

**Comment by vheon** [comment]
> User can still write his/her own funcref

I completely agree with this. IMHO this is not really a killer feature that many could benefit from. The only plugin which require a serious build is YCM and adding a bunch of code just for few cases is not worth it. I was just try to do it in a `funcref` so then we could put it in the wiki and pointing user to that if they really want/need it.

**Comment by ryneeverett** [comment]
> To see what's going on in post-update hooks, we can redirect the output:
>     Plug 'something', { 'do': 'make > /tmp/something.log' }

Am I right to interpret this as meaning that hook logs are not recoverable by default?

**Comment by junegunn** [comment]
@ryneeverett Yep, we use `:!` to execute the command, and do not store the log somewhere.

**Comment by ryneeverett** [comment]
@junegunn Is that ideal? Any reason not to store them in tmp files by default and make them accessible via a key-mapping?

**Comment by junegunn** [comment]
@ryneeverett I wouldn't say so. At first, the feature was implemented using `system()`, but as we can't see the progress before the process completes, it was replaced with `:!`.

https://github.com/junegunn/vim-plug/issues/38#issuecomment-50241266

`tee` maybe? But I'm a bit wary of introducing external dependencies because of portability, e.g. Windows.

**Comment by ryneeverett** [comment]
I see there's a `tee.exe` that ships with some windows distributions of vim, but I'm not sure how commonly used those distributions are.

**Comment by junegunn** [comment]
@ryneeverett Related to this issue, you might want to check out https://github.com/junegunn/vim-plug/issues/521#issuecomment-248676948. vim-plug doesn't wait for its completion so it doesn't know if the command succeeded, but at least we can see the progress and have the log in a buffer.

**Comment by ryneeverett** [comment]
@junegunn Thanks, I hadn't figured out that pipes need escaping.
