### ISSUE TITLE
Start vim, update plugins, close vim

### ISSUE THREAD

**Issue by bitboxer** [junegunn/vim-plug#210]
With Vundle I could start vim with `vim +BundleInstall! +qall` and it would update all plugins and quit vim afterwards. If I try the same with `vim-plug` it quits instantly. Can I make something similar here?

**Comment by junegunn** [comment]
You're on Neovim, right? Until #104 is done, you'll have to use ordinary Vim for that purpose.

**Comment by bitboxer** [comment]
Yes, sorry. Forgot to mention. Closing this.
