### ISSUE TITLE
Checking for missing packages?

### ISSUE THREAD

**Issue by fortes** [junegunn/vim-plug#212]
Is there a way to check for missing packages? This is a nice feature of NeoBundle, in order to make sure everything in `.vimrc` has been installed.

**Comment by starcraftman** [comment]
@fortes I believe you want `PlugStatus`.

**Comment by fortes** [comment]
@starcraftman Awesome, not sure how I missed that! Is there a way to have it autoclose the window that pops?

**Comment by junegunn** [comment]
This is probably what you want:
```vim
if !empty(filter(copy(g:plugs), '!isdirectory(v:val.dir)'))
  autocmd VimEnter * PlugInstall | q
endif
```

**Comment by starcraftman** [comment]
@fortes `q` instantly closes it. Otherwise, you need some solution like junegunn's.

**Comment by starcraftman** [comment]
@junegunn I think we can close this one, doesn't seem to have any more questions.
