### ISSUE TITLE
Slow when vim start with open a file.

### ISSUE THREAD

**Issue by tthanh** [junegunn/vim-plug#213]
If I start vim without a file, I only need aroud 300 ~ 350ms, but when start vim with open a file, vim take 900 ~ 1000 ms to start (example sh file). I saw it source a lot of plugin file in start up but in vimrc, I set only use some plugin with filetype.
![screenshot from 2015-04-14 09 37 23](https://cloud.githubusercontent.com/assets/8962973/7129389/f5b7c7c4-e289-11e4-9685-cbda0e07297f.png)

My [vimrc](https://github.com/tthanh/dotfiles/blob/master/vimrc)

**Comment by Shougo** [comment]
You should upload your .vimrc.

**Comment by tthanh** [comment]
@Shougo Thank you for remind me, I will update.

**Comment by junegunn** [comment]
Even if you use `for` option, `ftdetect` files are loaded unconditionally. So that's normal and the screenshot you posted shows that loading them takes only a small amount of time. Can you post the entire output of `--startuptime` log?

**Comment by tthanh** [comment]
I found load youcompleteme took a lot of time. Sorry for my missunderstanding. I just don't know how vim autoload a lot of file when open a file compare with start vim alone. I will try lazyload youcompleteme
