### ISSUE TITLE
With upgrade new plugins are sought in a weird (and broken) URL on GitHub

### ISSUE THREAD

**Issue by mcepl** [junegunn/vim-plug#214]
I have upgraded `vim-plug` via `PlugUpgrade` and suddenly when I add new plugin to my list (just plain `Plug 'shumphrey/fugitive-gitlab'` nothing more fancy than that), `vim-plug` tries to look for it in a weird URL and it breaks:

```
- Finishing ... Done!
x fugitive-gitlab:
    Cloning into '/home/matej/.vim/plugged/fugitive-gitlab'...
    remote: Invalid username or password.
    fatal: Authentication failed for 'https://git::@github.com/shumphrey/fugitive-g
```
The section of my `~/.vimrc` with `vim-plug` configuration is:
```vim
call plug#begin('~/.vim/plugged')


Plug 'mcepl/vimoutliner'
Plug 'mustache/vim-mustache-handlebars'
Plug 'tpope/vim-scriptease'
Plug 'airblade/vim-gitgutter'
Plug 'bps/vim-textobj-python'
Plug 'editorconfig/editorconfig-vim'
Plug 'freitass/todo.txt-vim'
Plug 'fs111/pydoc.vim'
Plug 'garbas/vim-snipmate'
Plug 'geekjuice/vim-spec'
Plug 'honza/vim-snippets'
Plug 'jceb/vim-orgmode'
Plug 'kana/vim-textobj-user'
Plug 'kien/ctrlp.vim'
Plug 'clausreinke/typescript-tools.vim'
Plug 'MarcWeber/vim-addon-local-vimrc'
Plug 'MarcWeber/vim-addon-mw-utils'
Plug 'marijnh/tern_for_vim'
"Plug 'mattn/webapi-vim'
Plug 'mcepl/ropevim'
Plug 'mileszs/ack.vim'
Plug 'nvie/vim-flake8'
Plug 'othree/javascript-libraries-syntax.vim'
Plug 'reinh/vim-makegreen'
Plug 'rust-lang/rust.vim'
Plug 'scrooloose/syntastic'
Plug 'sjl/splice.vim'
Plug 'tomtom/tlib_vim'
Plug 'tpope/vim-characterize'
Plug 'tpope/vim-cucumber'
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-fugitive'
Plug 'shumphrey/fugitive-gitlab'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-speeddating'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'vim-scripts/closetag.vim'
Plug 'vim-scripts/TaskList.vim'
Plug 'https://gitlab.com/mcepl/vim-diff_navigator.git'
Plug 'https://gitlab.com/mcepl/evervim.git'
Plug 'https://gitlab.com/mcepl/html5-natalian.git', { 'branch': 'local_modifications' }
Plug 'https://gitlab.com/mcepl/vim-colors-solarized.git', { 'branch': 'pull77-less-drasticSignColumn'}
Plug 'https://gitlab.com/mcepl/slovnik-seznam.git'
call plug#end()
```

And I am using 'VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan 30 2014 10:56:21)' on RHEL-7.

**Comment by mcepl** [comment]
OK, so my mistake was that the name of the repo is `shumphrey/fugitive-gitlab.vim` (I missed `.vim` in the end), but this is a very weird way how to signal bad parameter.

**Comment by junegunn** [comment]
I think this should answer your question:
https://github.com/junegunn/vim-plug/wiki/faq#whats-the-deal-with-git-in-the-url

It's all because there's no way to tell if the repository doesn't exist, try this:

```vim
git clone https://github.com/junegunn/emacs-plug.git
```

**Comment by mcepl** [comment]
Well, my point was that this error should be somehow captured by `vim-plug` and some more reasonable should be told to the user rather than this obvious nonsense. Yes, I blame git as well.

**Comment by u2berggeist** [comment]
I'd agree on this. It should have a more helpful error message than this. Or at least a suggestion to make sure the plugin was typed correctly. Wasted 20 minutes trying to figure out why it thought my username and password was wrong.
