### ISSUE TITLE
Ignore case of repos url

### ISSUE THREAD

**Issue by mtglsk** [junegunn/vim-plug#216]
Even though vim-plug clones repos correctly with lower case, when you change case of `Plug 'repo'` statement it fails.

Example:

    Plug 'Shougo/neocomplete.vim'
    :PlugInstall
    Plug 'shougo/neocomplete.vim'
    :PlugInstall
    x neocomplete.vim:
        Invalid URI: https://git::@github.com/Shougo/neocomplete.vim.git
        Expected:    https://git::@github.com/shougo/neocomplete.vim.git
        PlugClean required.

Maybe lower case should be always used to avoid mismatches?

**Comment by junegunn** [comment]
Correct me if I'm wrong, but as far as I know, there's no guarantee that a Git URL is case-insensitive. GitHub does seem to use case-insenstive URLs, but it's not always the case for other repositories.

```
# OK
git clone https://github.com/apache/hbase.git

# OK
git clone https://github.com/apache/HBASE.git

# OK
git clone git://git.apache.org/hbase.git

# NOT OK
git clone git://git.apache.org/HBASE.git
  Cloning into 'HBASE'...
  fatal: remote error: access denied or repository not exported: /HBASE.git
```

Which means vim-plug should not ignore case.

**Comment by mtglsk** [comment]
https://help.github.com/articles/error-repository-not-found/

According to this above actually it is case sensitive for github? I can't find any repo to test this. Normally I can clone with lower case without problem.

**Comment by junegunn** [comment]
Well actually it doesn't matter whether if GitHub is case-insensitive or not, as vim-plug was not built just for GitHub although the default `g:plug_url_format` points to it as most plugins are maintained on GitHub. Here's another example of case sensitivity:
```
git clone git://git.postgresql.org/git/postgresql.git
git clone git://git.postgresql.org/GIT/postgresql.git
```
