### ISSUE TITLE
Is it possible to silence warnings?

### ISSUE THREAD

**Issue by rgrinberg** [junegunn/vim-plug#220]
I get annoying warnings like

```
perl: warning: Setting locale failed. perl: warning: Please check that your locale settings:
```

when updating. Is it possible to get rid of the warnings by adding `2>/dev/null` to the commands?

**Comment by starcraftman** [comment]
@rgrinberg You mean post install do hooks right? This project has no perl component. Sure, you can suppress output of such commands. You can even background them with ampersand, anything valid in your shell should work. If you need even more control, see the funcref example.

**Comment by rgrinberg** [comment]
Yeah I understand there's no perl component but I have this annoying problem with my shell/perl. Would be great to just silence these harmless warnings. Here's a screenshot of what I mean

https://www.evernote.com/shard/s417/sh/dfd8cb6e-f045-4e1a-b3ad-96f160364e33/84e6437fe8d072ad134e487f2a2d8c22

**Comment by starcraftman** [comment]
@rgrinberg I see, so it is a warning captured during update by the stream intercept. We intentionally run those commands with `2>&1` to capture all output and ensure user can see errors.

Also, if that happens on something as simple as a clone command, doesn't that mean you get that on every command? That's annoying. Seems like you should fix the perl issue or remove it from your path. You could even just build a new one under $HOME & prepend it to your path.

**Comment by junegunn** [comment]
vim-plug cannot know, and does not want to know whether if a certain log entry can be ignorable or not. And `2> /dev/null` will suppress progress report from git command. You should just fix the issue on your system.
