### ISSUE TITLE
Does plug activate newly added plug-ins on .vimrc reload or after :PlugInstall?

### ISSUE THREAD

**Issue by pickfire** [junegunn/vim-plug#222]
Take a look at https://github.com/gmarik/Vundle.vim#todo, I wanted to know if plug can activate **plugged** after `:PlugInstall`?

**Comment by junegunn** [comment]
Yes, it loads/reloads plugins after `:PlugInstall` or `:PlugUpdate`, so you don't have to restart Vim. However, it may not always work as expected. For example, some plugins initialize themselves on `VimEnter` event. We might consider making vim-plug manually trigger the event after install/update, but currently it does not do it.

**Comment by pickfire** [comment]
What about `helptags`?

**Comment by junegunn** [comment]
https://github.com/junegunn/vim-plug/wiki/faq#does-vim-plug-generate-help-tags-for-my-plugins

**Comment by pickfire** [comment]
Does the following generate `helptags` or during the first run?
```vimscript
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall
endif
```
