### ISSUE TITLE
Load plugin on demand is not working?

### ISSUE THREAD

**Issue by oz123** [junegunn/vim-plug#223]
I copied your basic vimrc, and did PlugInstall.

Now when I issue `:NERDTreeToggle`, I expected to see the NerdTree pane opened. 
Instead, I am seeing and error: `E492: Not an editor command: NERDTreeToggle`.

Is something wrong with my setup or did I understand `Load plugin on demand` wrongly?

**Comment by junegunn** [comment]
Can't reproduce. Does it work when you remove `on` option from the line?

**Comment by oz123** [comment]
@junegunn, It works as expected on vim installed in Debian (compile with `hugh`). The system I had problems with it is a gentoo. Can you give me a clue which specific vim feature of vim is needed for this plugin to work?

**Comment by junegunn** [comment]
> The system I had problems with it is a gentoo.

1. Does it work when you remove on option from the line on gentoo? I'm trying to see if the problem is in on-demand loading or not.
2. What is the Vim version installed there? Please post the output of `:version`.

**Comment by oz123** [comment]
> Does it work when you remove on option from the line on gentoo? I'm trying to see if the problem is in on-demand loading or not.
Yes. The plugin manager work. Only the load on demand is not working. I also got it to work with 'on' and doing `PlugStatus` and then pressing `L` to load NERDTree.

**Comment by junegunn** [comment]
So you have `Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }` in your config, right?
Please post the output of `:echo g:plugs.nerdtree` and `:command NERD`.

**Comment by oz123** [comment]
```
{'uri': 'https://git::@github.com/scrooloose/nerdtree.git', 'dir': '/home/ozn/.v
im/plugged/nerdtree/', 'frozen': 0, 'on': 'NERDTreeToggle', 'branch': 'master'}
Press ENTER or type command to continue
```

**Comment by junegunn** [comment]
`:command NERD`?

**Comment by oz123** [comment]
Weired, I compiled vim with the exact same options on another Gentoo system, and now it works as expected... I still need to check that other system, but I don't have access to it now.

**Comment by junegunn** [comment]
Aight, let me know if you run into the problem again. Most features of vim-plug are tested against different versions of Vim, so I don't think it was caused by a bug in vim-plug.

https://github.com/junegunn/vim-plug/blob/master/test/workflow.vader#L351
https://travis-ci.org/junegunn/vim-plug/builds

**Comment by haolian9** [comment]
same here, I have the same config: `Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }`

finally, I found `set wildignore+=*/plugged/*` will impact vim-plug, causes the above error: `Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }`

I need to work in XDG_HOME/nvim, and ctrlp will show plenty files under plugged dir, so I ignored this dir.
