### ISSUE TITLE
Windows GVim doesn't recognize :PlugInstall

### ISSUE THREAD

**Issue by drobati** [junegunn/vim-plug#224]
I have GVim73 installed to C:\Program Files (x86)\Vim ($VIM).

Within there is a vim73/, vimfiles/, and _vimrc. I have tried variations of dropping plug.vim into autoload in both vim73/ and vimfiles/.

I tried `call plug#begin('~/.vim/plugged')`, `call plug#begin('~/vimfiles/plugged')`, `call plug#begin('~/vim73/plugged')`. I even tried `call plug#begin('$VIM/vimfiles/plug')` and other variations.

I can not figure out why this doesn't work.

**Comment by junegunn** [comment]
So, no error when you call plug#begin() but `PlugInstall` command is not defined? Do you have git installed on your system? What does `:echo executable('git')` say?

**Comment by Shougo** [comment]
@drobati You should upload whole .vimrc.

**Comment by drobati** [comment]
@junegunn `:echo executable('git')` returned `0`. I use GitHub for Windows and the included git shells so maybe that's why VIM doesn't know where git is. I'll see if I can fix it later today.

**Comment by junegunn** [comment]
Well, that is the reason. vim-plug requires git and when it's not found, `plug#begin()` stops with a warning message: "`git` executable not found. vim-plug requires git." You didn't see it?
https://github.com/junegunn/vim-plug/blob/master/plug.vim#L112-L114

**Comment by drobati** [comment]
Yeah I'm not sure why I didn't see that output. I believe this is resolved. Thanks for answering my question. :+1:
