### ISSUE TITLE
Add 'run' to options

### ISSUE THREAD

**Issue by thebillywayne** [junegunn/vim-plug#231]
##### Abstract
It would be convenient to add another option for the Plug lines; namely, the ability to execute a certain command or external script subsequent to an 'on' or 'for' option. This would allow users a central location for customizing behavior based upon the selective loading of certain plugins.

##### Rationale
Many times I'd like certain commands to be executed upon the loading of certain plugins. Adding this functionality to vim-plug represents a elegant, compact solution. 

##### Example Use Case
I use Neocomplete. Neocomplete is loaded on certain filetypes. The Plug command I have is
```Plug 'Shougo/neocomplete.vim', {'for': ['python', 'scheme', 'shell', 'clojure']}```
This works very well.  
However, I have certain custom keymappings which are specific to Neocomplete. For filetypes other than those specified for Neocomplete, these  keymappings, do not apply, creating a conflict, resulting in error messages such as
* ```E117: Unknown function:Neocomplete#smart_close_popup```                                                                 
* ```E15: Invalid expression: neocomplete#smart_close_popup()."\^H"```

I realize that a workaround would be an autocommand that set the appropriate keymappings upon loading those same filetypes. This, however, leads to duplicate specifications scattered over the config files.  
An elegant solution for vimplug would be something along the lines of:
```Plug 'Shougo/neocomplete.vim', {'for': ['python', 'scheme', 'shell', 'clojure'], 'run': 'myfunction'}```  
For my case, the "function" would simply be to source a file containing my custom NeoComplete keybindings.  
I think that this enhancement would be a great feature to have in vim-plug.

**Comment by junegunn** [comment]
Hi, thanks for the suggestion. Looks like the suggested feature makes more sense for `on` option rather than for `for` option where it's already possible with `FileType` autocmd as you described above. However in this case, using `User` autocmd that is triggered only on deferred loading seems like a better and a less intrusive approach than to add an option which only benefits a few advanced users. By using autocmd, you don't have to define a function for taking its reference. And it's much simpler to implement. (A single line of `doautocmd` will do)

```vim
Plug 'Shougo/neocomplete.vim', {'for': 'xxx', 'on': 'Xxx'}
autocmd! User neocomplete.vim inoremap foo bar
```

**Comment by thebillywayne** [comment]
This is a reasonable solution. I fully understand opting for a less intrusive approach. I was unaware of the `User` autocmd. I've tested it and it works very well. Thanks for the pointer.

**Comment by vheon** [comment]
@junegunn but it is a `neocomplete.vim` feature the `User` autocmd??

**Comment by junegunn** [comment]
Ugh, vim-plug currently does not trigger User autocmd. I was just suggesting a different approach to implement the idea. What do you mean "it works well"?

**Comment by junegunn** [comment]
Maybe my previous comment was misleading. The feature is not implemented yet.

**Comment by thebillywayne** [comment]
@junegunn 
>What do you mean "it works well"?  

If I prepend the `neocomplete.vim` specific keybinding with `au User neocomplete.vim` then the keybindings are only activated if `neocomplete.vim` is activated upon sourcing the appropriate file. For example, 
```vim
au User neocomplete.vim inoremap <expr><BS> neocomplete#smart_close_popup()."\<C-h>"
```
works as expected if `neocomplete.vim` is active. If it is inactive, then BS works as expected, i.e. simply deleting chars. But if `neocomplete.com` is not active and `au User neocomplete.vim` isn't prepended to the `inoremap`  then `neocomplete#smart_close_popup()` is undefined and E117 is raised:
```vim
E117: Unknown function:Neocomplete#smart_close_popup
```
This is what I meant by saying that your suggestion works well.  
Is what I'm doing some unexpected behavior? I'm not proficient in vimscript and `:help autocmd` wasn't very informative about how to combine `doautocmd` with `User`.  
Hope that clarifies what I stated earlier.

**Comment by junegunn** [comment]
> Is what I'm doing some unexpected behavior?

Yes, the code after `au User neocomplete.vim` is never executed unless `doautocmd User neocomplete.vim` is done by some code, and vim-plug does not do it (yet). So you don't see the error when neocomplete is inactive, but it won't run even when it becomes active. I think you're somehow confused.

**Comment by junegunn** [comment]
FYI, a similar suggestion was made in the past (#149) but rejected. But unlike the last time you succeeded to convince me that this might actually be useful. I still do not want to add an option, but I like the implicit User autocmd approach. I'll try to take a stab at it.

**Comment by thebillywayne** [comment]
>I think you're somehow confused.  

This is quite likely the case. It's apparent that I need to familiarize myself more with vimscript and think more clearly about the issue.

**Comment by thebillywayne** [comment]
@junegunn I'm glad to have contributed in some small way to the development of this great plugin. Your openness to your users speaks highly of your character.

**Comment by junegunn** [comment]
@thebillywayne Thanks, now you can attach your code to `User` autocmds. See #232.
