### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Pyrohh** [junegunn/vim-plug#234]
Would you mind if I wrote some documentation for vim-plug (unless you want to instead)?

For example, I seem to only need to specify a specific branch once a month, and It's annoying having to open a web browser to see the docs as opposed to being able to do `:h vim-plug`.

**Comment by junegunn** [comment]
Thanks. I have a secret script that translates markdown file into vimdoc. If the contents of the README page is enough, I could post the converted file.

**Comment by Pyrohh** [comment]
That would be great. Do you think the FAQ/troubleshooting section should be included as well?

**Comment by junegunn** [comment]
Maybe, but then I'll have to merge the pages into a single markdown document, and need to fix some formatting in the pages. Anyway, this is the converted file.

https://gist.github.com/junegunn/3ddbb03f3da624e01d28

**Comment by Pyrohh** [comment]
Here's an early WIP: https://github.com/Pyrohh/vim-plug/commit/1f7f8f84f232b3a5781e04db3432d19fbfbb5be5

You don't need to read the whole thing, I just want to know what you think regarding the style/structure so I don't dig myself into a hole.

**Comment by junegunn** [comment]
Looks good. One concern I have is that vim-plug (*intentionally*) does not follow pathogen-compatible directory structure. So even if we put the file in `doc` directory, users will have to manually copy the file to their `~/.vim/doc` and it can be confusing to some.

What if we make an external repository (named vim-plug-ext) with pathogen-compatible layout that contains extra stuff? Such as vimdoc, [VimAwesome completion](https://gist.github.com/junegunn/5dff641d68d20ba309ce), [`gx` key binding](https://github.com/junegunn/vim-plug/issues/204#issuecomment-89312471), etc. Just an idea. Maybe it's too much?

**Comment by Pyrohh** [comment]
IMO the documentation shouldn't be equated with the stuff you mentioned; I think plugin documentation is much more important than such scripts, or at least will be used more. Perhaps there could be `vim-plug-doc`, and then you could put the scripts you mentioned in a `contrib` folder here?

If they were in a separate repository they probably wouldn't get much exposure.

**Comment by junegunn** [comment]
Okay, fair enough. And I would just place the file on the root directory instead of in doc directory. The presence of `doc` directory might give the wrong impression that the repository is pathogen-compatible.

**Comment by starcraftman** [comment]
So if I'm following this correctly, we'll have a top level vimdoc file in this repo. Then the plan is to at some point during `plug.vim` init (or first command) we download that file onto user computer & gen tags on it? I guess we could cache the doc in the plugin dir like `plugged/.plug/plug.txt`.

Alternative - but messier - we could just inline the vimdoc inside plug.vim & have it extract/write the vimdoc on first run/upgrade. Saves the second download.

**Comment by junegunn** [comment]
> we download that file onto user computer & gen tags on it? 

I was thinking of not doing it automatically. I personally believe that vim-plug is small enough that the documentation is unnecessary for most users, though I'm obviously not in the position to speak for ordinary users.

> we could just inline the vimdoc inside plug.vim

That's a good idea, we could simply put the content after `finish`. However, I think some users may not appreciate vim-plug touching their file system other than `plug.vim` and `plugged` directory.

**Comment by starcraftman** [comment]
> That's a good idea, we could simply put the content after finish. However, I think some users may not appreciate vim-plug touching their file system other than plug.vim and plugged directory.

It wouldn't be that unheard of, ctrlp & jedi write files to my cache folder by default. Besides, the user already gave permission to automatically download files to the plugged dir, not a big leap to say they wouldn't mind one extra vimdoc there. 

I'm open to alternatives. Though if the mechanism isn't automatic, I'd say most users will just continue assuming we have no vimdoc.

**Comment by junegunn** [comment]
I personally wouldn't mind either, but the difference between `plugged` and `~/.vim/doc` is that the former is explicitly specified by the user (it could even be a directory on a different partition), while the latter is not. To be honest I'm not convinced that we **need** a local vimdoc (is it really hard to remember "branch"?), though I don't deny that it's good to have one. So I'm okay with it being an opt-in feature. The simplest way is to show how to install it on wiki.

**Comment by Pyrohh** [comment]
Regarding 'branch', no it's not that hard to remember, but that doesn't mean I (or others) necessarily want to go to the vim-plug repo every time we need to learn something about it.

**Comment by junegunn** [comment]
A part of the reason I've been trying to keep vim-plug as small as possible is to make documentation almost unnecessary: once you skim through the example section of the README page (or [the comment section](https://github.com/junegunn/vim-plug/blob/master/plug.vim#L11-L33) in plug.vim), you're done, you know everything you need to know. Guess it's too ideal of a goal.

**Comment by Pyrohh** [comment]
> A part of the reason I've been trying to keep vim-plug as small as possible is to make documentation almost unnecessary

I think you've mostly succeeded in that, but as you said it's good to have one if people forget something. Anyways, I'll try to finish this up soon-ish.

**Comment by starcraftman** [comment]
@junegunn An alternative idea popped into my brain since you didn't want the local doc. I'm tired so I just write it quick. 

* We inline the vimdoc to plug,vim.
* We add a new command `PlugHelp`
* When user calls command, we open a buffer, then `set ft=help`, then copy contents of vimdoc into it from plug.vim. 

No local file or extra download. Con, no direct `:h plug-branch`. Could allow command to take search term like `PlugHelp branch`.

**Comment by junegunn** [comment]
@starcraftman It's not that I don't want local doc. I just don't know if it's okay to install it by default without user's consent. I'd thought about the exact same idea, but it feels a little hacky :)

Once the file is on repo, we can update the wiki page to provide simple instructions to open it on Vim:

```vim
:e https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.txt
```

Or install it locally

```vim
:!curl https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.txt ...
" ... helptags ...
```

Another idea is to add an option to `PlugUpgrade`. `:PlugUpgrade -doc`.

**Comment by Pyrohh** [comment]
I feel a bit silly having suggested this, because I've since lost motivation :sweat_smile:. If it's going to be this complicated to manage the documentation, then I'd rather just not deal with it. Feel free to close this issue, unless of course you plan on adding docs.

**Comment by junegunn** [comment]
I see, I'll close it for now. Honestly, launching a web browser once a few months to look up the documentation doesn't sound so terrible to me :)
