### ISSUE TITLE
"not an editor command" with lazy loading and neovim

### ISSUE THREAD

**Issue by mhinz** [junegunn/vim-plug#238]
Hi!

I have this:

```vim
call plug#begin()
  Plug 'junegunn/vim-github-dashboard',  { 'on': 'GHDashboard' }
call plug#end()

nnoremap <f4> :GHDashboard! mhinz<cr>
```

With regular Vim this works without problems, but with nvim I get:

```
Error detected while processing function <SNR>2_lod_cmd:
line    2:
E492: Not an editor command: GHDashboard! mhinz
```

It's no escaping issue since manually typing `:GHDashboard` doesn't work either. (Same error.)

`:command GHDashboard` gives the expected result: `!   GHDashboard * call s:lod_cmd('GHDashboard', "<bang>", <line1>, <line2>, <q-args>, ['vim-github-dashboard'])`

All the other entries marked for lazy loading (https://github.com/mhinz/dotfiles/blob/master/vim/vimrc#L12-L42) work without problems with vim _and_ nvim.

I'm a bit puzzled by this one.

**Comment by junegunn** [comment]
[Ouch](https://github.com/junegunn/vim-github-dashboard/blob/master/plugin/github_dashboard.vim#L1-L3) :)

**Comment by mhinz** [comment]
Oh, wow. I actually took a look at that file to see when the commands get defined and didn't see it either.. thanks. :]
