### ISSUE TITLE
VTALRM on OSX 10.9.5

### ISSUE THREAD

**Issue by bsandrow** [junegunn/vim-plug#239]
I got this while running default `vim` on Mavericks (OSX 10.9.5).

```
work/config.vim :) /usr/bin/vim                                                                                                                                         g:m[4/694]
vim-pandoc: 'bibliographies' and 'command' modules require vim >= 7.4 and have been disabled.
Press ENTER or type command to continueVim: Caught deadly signal VTALRM

Vim: Finished.












































[1]    67444 virtual time alarm  /usr/bin/vim
```

Vim version:

```
work/config.vim :) /usr/bin/vim --version
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Dec 19 2013 15:19:49)
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
-arabic +autocmd -balloon_eval -browse +builtin_terms +byte_offset +cindent
-clientserver -clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments
-conceal +cryptv +cscope +cursorbind +cursorshape +dialog_con +diff +digraphs
-dnd -ebcdic -emacs_tags +eval +ex_extra +extra_search -farsi +file_in_path
+find_in_path +float +folding -footer +fork() -gettext -hangul_input +iconv
+insert_expand +jumplist -keymap -langmap +libcall +linebreak +lispindent
+listcmds +localmap -lua +menu +mksession +modify_fname +mouse -mouseshape
-mouse_dec -mouse_gpm -mouse_jsbterm -mouse_netterm -mouse_sysmouse
+mouse_xterm +multi_byte +multi_lang -mzscheme +netbeans_intg -osfiletype
+path_extra -perl +persistent_undo +postscript +printer -profile +python/dyn
-python3 +quickfix +reltime -rightleft +ruby/dyn +scrollbind +signs
+smartindent -sniff +startuptime +statusline -sun_workshop +syntax +tag_binary
+tag_old_static -tag_any_white -tcl +terminfo +termresponse +textobjects +title
 -toolbar +user_commands +vertsplit +virtualedit +visual +visualextra +viminfo
+vreplace +wildignore +wildmenu +windows +writebackup -X11 -xfontset -xim -xsmp
 -xterm_clipboard -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -D_FORTIFY_SOURCE=0 -Iproto -DHAVE_CONFIG_H -arch i386 -arch x86_64 -g -Os -pipe
Linking: gcc -arch i386 -arch x86_64 -o vim -lncurses
```

**Comment by vheon** [comment]
That has nothing to do with vim-plug. The vim you're using does not meet the requirements for `vim-pandoc` apparently.

**Comment by bsandrow** [comment]
This error was transient. For example, just now:

```console
$ /usr/bin/vim +PlugInstall +qall
vim-pandoc: 'bibliographies' and 'command' modules require vim >= 7.4 and have been disabled.
Press ENTER or type command to continue
$
```

The

**Comment by vheon** [comment]
Try opening vim without any plugin and then do `:py print 1` does it segfault? Try with ruby also `:ruby puts 1`.

**Comment by bsandrow** [comment]
Well, the `SEGV`s are a slightly different issue because they are happening with consistency, and on a different install of Vim. I ran your tests (on *that* Vim), and `:ruby` was causing segfaults. I tracked it down to [this issue](https://github.com/Homebrew/homebrew/issues/23938), which I resolved with by running `brew uninstall vim; rvm system; brew install vim`, per [this comment](https://github.com/Homebrew/homebrew/issues/23938#issuecomment-31549058).

That said, I'm unable to reproduce the `VTALRM` crash on my end (which was with the Apple-provided, system-installed `/usr/bin/vim`).

**Comment by junegunn** [comment]
I agree with @vheon that the first case you mentioned has nothing to do with vim-plug though I can't be sure if it's caused by vim-pandoc. I would examine plugins that depend on foreign language interfaces. vim-plug is one of them but only so when you run `:PlugInstall` or `:PlugUpdate`.

When you run `:PlugInstall`, vim-plug will use Ruby interface of Vim, and that of OS X default vim has been known to be unstable to some degree and there's not much we can do about it. But the segfault you ran into with homebrew-vim is caused by the broken installation as you have noticed and it's obviously unrelated to the VTALRM in the first case.
