### ISSUE TITLE
plugins remove

### ISSUE THREAD

**Issue by alex93ushakov** [junegunn/vim-plug#241]
How to remove plugin?

**Comment by vheon** [comment]
Delete the appropriate line from the `vimrc`, re-source the `vimrc` and then `:PlugClean` (like `:source $MYVIMRC | PlugClean`), you will be prompted to confirm the deletion of the plugin files.

**Comment by vyp** [comment]
Remove the relevant `Plug` line in your vimrc, then run `:PlugClean`.

**Comment by alex93ushakov** [comment]
Thanks for reply.
