### ISSUE TITLE
On :PlugUpdate - "Too many arguments for function: jobstart"

### ISSUE THREAD

**Issue by mikedfunk** [junegunn/vim-plug#243]
On NVIM 0.0.0-alpha+201506110903 (compiled Jun 11 2015 10:20:04), Mac OSX 10.10.3. Screenshot:

![screen shot 2015-06-11 at 10 40 59 am](https://cloud.githubusercontent.com/assets/661038/8114005/912b9388-1026-11e5-804e-8ada180a179b.png)

It just hangs and never updates any of my plugins.

**Comment by junegunn** [comment]
Hi, so you mean you updated neovim and it suddenly stopped working? Or is it your first time running vim-plug on neovim?

I also have a relatively new neovim (`NVIM 0.0.0-alpha+201506091331 (compiled Jun 10 2015 00:06:46) Commit: 6270d431aaeed71e7a8782411f36409ab8e0ee35`) but it's not reproducible.

**Comment by junegunn** [comment]
Ah, the code on the screenshot shows that you have an old version of vim-plug, please `:PlugUpgrade`.

**Comment by mikedfunk** [comment]
Thanks! I though :PlugUpdate handled vim-plug too.
