### ISSUE TITLE
How do I detect when plugins are finished loading.

### ISSUE THREAD

**Issue by ivanalejandro0** [junegunn/vim-plug#246]
I want to override some plugin mappings, that needs to be done after the specific plugin is loaded and since the load is done async the settings are loaded before and had no effect. I can't find a way to achieve this.

Is there any trigger that I can hook to or any place where I can save a .vim file to accomplish this?
The closer I've been to this is to add some .vim files on a `custom/after/plugin` folder and add a `Plug '~/.vim/custom`` line at the end of the plugin list.

Thanks!

**Comment by junegunn** [comment]
If a plugin ignores your mappings then it's doing it wrong. But anyway, you could do stuff on VimEnter autocmd which is triggered after plugins are loaded. See `:help startup`.

**Comment by ivanalejandro0** [comment]
The plugins are not really ignoring my mappings, what happens is for instance:
```vim
if !exists('g:user_emmet_leader_key')
  let g:user_emmet_leader_key = '<c-y>'
endif
```
So if my `g:user_emmet_leader_key` definition is loaded **after** the emmet plugin loads, it won't use my mapping and it will load the default one.

And, for the other case that bothers me: I want to define a mapping and some plugin defines the same mapping, if I can't load my mapping **after** the plugin load, it won't override the plugin's one.

I've looked at `:help initialization` (that seems to be the same) in the past, but I missed the `VimEnter` thing, thanks for that :)

I've managed to load my configs *before* the plugins load just by sourcing them before the `Plug` lines and *after* the plugin loading using `VimEnter` which is great since now I don't have the problem anymore, but it feels like a hack more than a fix.

Also, (using `vim --startup vim.log`) I've found that some `*.vim` files (within the `autoload/` folder) are loaded last... is this a vim thing or a vim-plug thing?

Thanks!

**Comment by junegunn** [comment]
> So if my g:user_emmet_leader_key definition is loaded after the emmet plugin loads, it won't use my mapping and it will load the default one.

It's because you have your settings in a separate config file which vim treats as another plugin, so it's loaded after your .vimrc is loaded (`:help load-plugins`). So in that case you have to manually source them, and there's nothing surprising about it.

> I want to define a mapping and some plugin defines the same mapping, if I can't load my mapping after the plugin load, it won't override the plugin's one.

This is what I said about plugins doing it wrong. A well-bahaved plugin does not override existing mapping and/or provides `<Plug>` mappings for easier customization.

> Also, (using vim --startup vim.log) I've found that some *.vim files (within the autoload/ folder) are loaded last... is this a vim thing or a vim-plug thing?

It's a vim thing.

**Comment by ivanalejandro0** [comment]
Gotcha! thanks for helping me with this.
