### ISSUE TITLE
Per-plugin configuration files

### ISSUE THREAD

**Issue by samvv** [junegunn/vim-plug#247]
Most of the time a plugin needs a little configuration/keymapping in order to work. I was thinking about autoloading a per-plugin configuration file, say `plugin/config.vim`. This would make it possible to enable/disable specific plugins without messing up the global configuration and would make the  `--on` feature more robust.

Example `~/.vim/plugged/vim-gitgutter/config.vim`:
````vim
let g:gitgutter_max_signs = 1000

nmap ]h <Plug>GitGutterNextHunk
nmap [h <Plug>GitGutterPrevHunk

nmap <Leader>ha <Plug>GitGutterStageHunk
nmap <Leader>hu <Plug>GitGutterRevertHunk

nmap <Leader>hv <Plug>GitGutterPreviewHunk
`````

One could go even further and auto-include a `config.local.vim` for computer-local configuration compatible with [dotfiles](http://dotfiles.github.io), though this might be a bit overkill.

**Comment by junegunn** [comment]
Hi, thanks for the suggestion, but I don't think the feature is crucial to vim-plug which tries to be simple and small. I suggest that you write your own function for doing that using `g:plugs` variable which holds all the information you need and simply call it on `VimEnter` event. Let me know if you need further assistance.

**Comment by samvv** [comment]
No problem, I get the design principle. Thanks for the tip!

**Comment by epeli** [comment]
How about creating a hook `enabled` which would get the plugin data `g:plugs` as an argument?

Btw, here's what I wrote for neovim:

```viml
for plugin in keys(g:plugs)
    let s:plugin_config = $HOME . '/.config/nvim/plugin.d/' . plugin . '.vim'
    if filereadable(s:plugin_config)
        execute 'source ' . s:plugin_config
    endif
endfor

```
