### ISSUE TITLE
Ending a plugin location in .git refuses to download.

### ISSUE THREAD

**Issue by ecogiko** [junegunn/vim-plug#250]
Hello, 

I decided to try out vim-plug because of it's flexibility and I stumbled on a problem. Any plugin location name ending in .git won't be downloaded with a weird git error about not finding the Username.

**Comment by starcraftman** [comment]
@ecogiko Can you please check for typo. If you get part of the URL wrong, git usually assumes it is a private repo and prompts for credentials. You can verify that vim-plug should work with this example line in your vimrc:

`Plug 'https://github.com/junegunn/vim-github-dashboard.git'`

**Comment by ecogiko** [comment]
@starcraftman With the full url of the repository it succeeds. I forgot to include an example, sorry my bad.

    Plug 'junegunn/vim-github-dashboard.git'

**Comment by starcraftman** [comment]
@ecogiko Ah, I see what you mean. If I understand this correctly, you are saying that were there a reponame that ended in .git (i.e. `github.com/junegunn/vim-plug.git` it wouldn't work. I don't think this is a valid use case, github.com prevents any repo from ending in `.git` (try yourself). I'm pretty sure most other git services will to. It might even be invalid in the git spec, though I haven't looked.

Do you actual have a repo that is like this or is this more hypothetical?

**Comment by junegunn** [comment]
It's not supported. When the argument to `Plug` command is not a full URL, clone URL is built using `g:plug_url_format` which defaults to `https://git::@github.com/%s.git` and vim-plug doesn't do anything other than simply replacing `%s` with the given argument.
