### ISSUE TITLE
Feature request: default to Y for PlugClean

### ISSUE THREAD

**Issue by larryhynes** [junegunn/vim-plug#253]
It's a small thing, and it may be only personal to me, but I thought I would say it out loud and see what happens. :smile:

When I invoke `PlugClean`, the dialog defaults to `N`, not `Y`. I have never invoked `PlugClean` by accident, or without wanting to remove a certain plugin, so I think it might make more sense if it defaulted to `Y`.

Thank you for all your work on this, and on `:Goyo`... they're terrific.

**Comment by junegunn** [comment]
Hi, have you tried `PlugClean!`?
https://github.com/junegunn/vim-plug#commands

**Comment by larryhynes** [comment]
Aha! Excellent – thank you.
