### ISSUE TITLE
Install ~/.vim or ~/.nvim?

### ISSUE THREAD

**Issue by dfroger** [junegunn/vim-plug#256]
Hello,

I'm very new to neovim.

README.md usage says to install in `~/.vim`:

    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

But why isn't it installed in `~/.nvim`?

Thanks.

**Comment by dfroger** [comment]
Just undersand that `vim-plug` works with `vim` or `neovim`, so I guess I have to adapt `~./.vim` to `~/.nvim` when using `neovim`.

**Comment by junegunn** [comment]
Yes vim-plug was initially written for vim. Parallel installer for neovim support was added later.
