### ISSUE TITLE
vim-plug downloads old commit of distinguished.vim from Lokaltog/vim-distinguished repo

### ISSUE THREAD

**Issue by kazarmy** [junegunn/vim-plug#257]
On my computer, the latest vim-plug (commit 69d6c9d54510cf3c22b8359be5534c6895f2d314) downloads an old commit of colors/distinguished.vim from the [Lokaltog/vim-distinguished](https://github.com/Lokaltog/vim-distinguished) repo when it should be downloading the latest commit. Apparently, the commit downloaded is Lokaltog/vim-distinguished@395d32b30b899c5ef8fc2b439e6ee833ef7f10f8 (I say "apparently" because I have not checked whether there is a later commit that results in an identical distinguished.vim). There were no previous downloads of the plugin.

I'm using [gVim 7.4.11](http://sourceforge.net/projects/cream/files/Vim/7.4.711/) from the Cream project on Windows 8.1. The installed version of git is 2.4.0.windows.2.

I have only the following in my vimrc:

```
call plug#begin('~/vimfiles/bundle')
Plug 'Lokaltog/vim-distinguished'
call plug#end()
```

Apart from vim-plug, no other customizations have been made to gVim.

**Comment by junegunn** [comment]
```vim
Plug 'Lokaltog/vim-distinguished', { 'branch': 'develop' }
```

:)

**Comment by kazarmy** [comment]
Fyi, Vundle has different behavior in this case.

Thanks for the answer! :)

**Comment by junegunn** [comment]
Vundle does not support branches and only picks up the default one. vim-plug, on the other hand, allows you to choose any branch and verifies if the right branch is being used. So it can be confusing if the default branch can change over time, so it defaults to `master` when not specified.

**Comment by kazarmy** [comment]
Thanks for the info. I think it's best if it was also stated in the FAQ.

**Comment by junegunn** [comment]
Thanks. Will see if there's better way to address the default branch issue.
