### ISSUE TITLE
YCM not loading for: 'rust'

### ISSUE THREAD

**Issue by miguelmartin75** [junegunn/vim-plug#259]
In my vimc I have the following line:
```vim
Plug 'Valloric/YouCompleteMe', { 'do': './install.sh --clang-completer', 'for': 'c,cpp,objc,objcpp,cs,python,rust' }
```
Oddly enough, it does not load the YouCompleteMe plugin for rust file types (`.rs` files). However, I also have these lines specific for rust, but they seem to be loaded:
```vim
Plug 'phildawes/racer', { 'do': 'cargo build --release', 'for': 'rust' }
Plug 'wting/rust.vim', { 'for' : 'rust' }
``` 
If I remove the `'for': 'c,cpp,objc,objcpp,cs,python,rust' ` then it works fine, i.e. if I have the following instead:
```vim
Plug 'Valloric/YouCompleteMe', { 'do': './install.sh --clang-completer' }
```

Note for those interested, I'm using YCM to automatically pop-up Racer's omni-complete via manually setting an entry for rust in `g:ycm_semantic_triggers`.

**Comment by junegunn** [comment]
See YCM example here: https://github.com/junegunn/vim-plug#on-demand-loading-of-plugins

The reason YCM does not load is that it only executes its Enable function on `VimEnter`, so it has to be manually triggered.

**Comment by miguelmartin75** [comment]
I changed my line to:

```
Plug 'Valloric/YouCompleteMe', { 'do': './install.sh --clang-completer', 'for': ['c', 'cpp', 'objc', 'objcpp', 'cs', 'python', 'rust'] }
```

and it works, without the 

```
autocmd! User YouCompleteMe call youcompleteme#Enable()
```

:confused:

**Comment by junegunn** [comment]
Maybe they changed something? I don't know, I don't use YCM.

Anyway, `for` option was designed to take a string or a list, and there's no code in vim-plug that processes comma-separated file types. It may not work correctly if you have multiple plugins with overlapping sets of `for` options.

```vim
Plug 'foo', { 'for': 'a,b,c' }
Plug 'bar', { 'for': 'b,c' }
```

When a file of type `a` is open, `foo` is loaded, and vim-plug will try to clear the hook by executing `autocmd! PlugLOD Filetype a,b,c`, which will cause the autocmds for `bar` to be cleared as well, and `bar` will never get loaded.

But if you specify the types as a list, vim-plug will correctly handle such cases.

```vim
Plug 'foo', { 'for': ['a', 'b', 'c'] }
Plug 'bar', { 'for': ['b', 'c'] }
```
