### ISSUE TITLE
Question: Is it possible to checkout a revision (SHA) instead of tag 

### ISSUE THREAD

**Issue by wikimatze** [junegunn/vim-plug#26]
`Plug 'user/repo1', 'branch_or_tag_or_sha'`

**Comment by vyp** [comment]
(Sorry for the bump, ignore. This is just to help future readers. But imo this ticket should be closed with wontfix label or similar.)

There is however the `:PlugSnapshot` command documented in the README, for those who haven't read it fully and came here first, like me.

**Comment by seb-mueller** [comment]
Just in case someone still comes across this issue. This now seems to be resolved , there is an `commit` option along with branch and tag as described in https://github.com/junegunn/vim-plug#plug-options

Below is an example on how checkout a specific commit (SHA) only :
```
Plug 'kassio/neoterm', { 'commit': '6389a24c42572020e0978600e632fd90094fe642' }
```
