### ISSUE TITLE
Document plugins loading after plug#end() in README/ FAQ

### ISSUE THREAD

**Issue by mattboehm** [junegunn/vim-plug#260]
I was having a problem because it was not clear to me that plugins are only loaded after plug#end(). I think it would help to explicitly say this in the installation instructions to avoid confusion.

~~It also appears that mappings I define between plug#begin() and plug#end() do not work. Assuming this is because of vim-plug and not something else I did wrong, it might be nice to mention this in the docs too.~~

**Comment by mattboehm** [comment]
Sorry, the second part of that is not due to vim-plug. To fix issue 1, I moved the plug section to the top, which put it above where I set my mapleader.

**Comment by junegunn** [comment]
Good point, will do, thanks.

Technically, `plug#end()` will update `&runtimepath` and plugins are loaded only after Vim has finished processing .vimrc. (`:help startup`) So `plug#end()` will make it possible to call autoload functions, but plugin `:Commands` are not available at the point.

**Comment by mattboehm** [comment]
Thanks, that helps a lot =). Yep I meant when the plugins were in `&rtp` (in my case, couldn't find a colorscheme). As plugins don't normally load until after the .vimrc, it should behave exactly as people expect.
