### ISSUE TITLE
textobj-word-column fails to install (manual install works)

### ISSUE THREAD

**Issue by khouli** [junegunn/vim-plug#261]
When I try to install the plug at this repo:

https://github.com/coderifous/textobj-word-column.vim

I get this error:

    x textobj-word-column:
        Cloning into '/home/khouli/.vim/plugged/textobj-word-column'...
        git credential-if [[ $(uname) -eq Darwin ]]; then HELPER='osxkeychain'; else HELPER=':'; fi; $HELPER get: -c: line 0: syntax error near unexpected token `then'git credential-if [[ $(uname) -eq Darwin ]]; then HELPER='osxkeychain'; else HELPER=':'; fi; $HELPER get: -c: line 0: `git credential-if [[ $(uname) -eq Darwin ]]; then HELPER='osxkeychain'; else HELPER=':'; fi; $HELPER get'
        fatal: could not read Username for 'https://github.com': terminal prompts disabled

Manual install with a git clone works.

**Comment by junegunn** [comment]
> Cloning into '/home/khouli/.vim/plugged/textobj-word-column'...

Looks like you omitted `.vim` suffix. Try `Plug 'coderifous/textobj-word-column.vim'`.
