### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by artofhuman** [junegunn/vim-plug#262]
Hi, i have problem with update plugins
I run PlugUpgrade and then PlugUpdate and get errors UnicodeDecodeError, see screen
![1 artofhuman-ubuntu 28ssh 29 2015-07-29 11-27-08](https://cloud.githubusercontent.com/assets/1192122/8951234/042e2c54-35e5-11e5-836a-218c4cfcfaf3.png)

**Comment by junegunn** [comment]
@starcraftman Hi, any idea on this?

**Comment by starcraftman** [comment]
@junegunn Hi there, been a while. Offhand, my assumption would be he's using python3 installer & some char popped into the stream that the character decoder couldn't handle. Probably not a difficult fix, but I need to reproduce it on my end. Mainly still use 2.

@artofhuman To debug, please provide:
1. Output of: `vim --version`
2. Output of: `echo "$SHELL $LANG $LC_CTYPE`
For step 2, ensure that is run in the shell vim-plug is using (unless otherwise specified your default at /bin/sh).
3. Smallest part of your `.vimrc` that reproduces this.
4. Does this always happen? Or does the install/update sometimes succeed without error?

**Comment by junegunn** [comment]
@starcraftman Thanks for looking into it. I added you as a collaborator and assigned you to this. Hope you don't mind.

**Comment by starcraftman** [comment]
@junegunn Sounds good, I'll try pitch in when around. No problem on this bug, once I can reproduce should be simple. Probably just involves detecting encoding of terminal & using that encoding instead of default to decode. A slight nuisance from their new 3.0 strings.

**Comment by artofhuman** [comment]
@starcraftman 
1.
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:32)
Заплатки: 1-52
С изменениями, внесёнными pkg-vim-maintainers@lists.alioth.debian.org
Скомпилирован  buildd@
Огромная версия без графического интерфейса.  Включённые (+) и отключённые (-) особенности:
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
            общесистемный файл vimrc: "$VIM/vimrc"
         пользовательский файл vimrc: "$HOME/.vimrc"
  второй пользовательский файл vimrc: "~/.vim/vimrc"
          пользовательский файл exrc: "$HOME/.exrc"
          значение $VIM по умолчанию: "/usr/share/vim"
Параметры компиляции: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Сборка: gcc   -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl    -L/usr/lib/python2.7/config-x86_64-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
```

2.
`/bin/zsh ru_RU.UTF-8`

I think its happen because my locale is RU

You can see my vimrc in this repo
https://github.com/artofhuman/vim/blob/master/vimrc

**Comment by starcraftman** [comment]
@artofhuman I'm not sure how best to test this on my end, short of setting my whole system to RU. If you don't mind, could you try this version of [plug](https://raw.githubusercontent.com/starcraftman/vim-plug/fix_codec/plug.vim). Just overwrite your plug.vim file with it, you can revert to the master version with `:PlugUpgrade`.

**Comment by artofhuman** [comment]
@starcraftman I tried this version and update works. Thanks.

**Comment by starcraftman** [comment]
@artofhuman Interesting. By default seems decode only interprets ascii chars. A bit inconvenient given prevalence of UTF-8. I guess performance?

I'll make a PR promptly.

**Comment by junegunn** [comment]
@starcraftman Great job. I'm cool with that you merge the PR yourself or just push the commit to master if it's a fix for python installer and you find it more convenient.
