### ISSUE TITLE
PlugClean required

### ISSUE THREAD

**Issue by gerases** [junegunn/vim-plug#263]
Hi,

I use dfm for my dot file management. And as such, .vim is under git management. So, the various plugins that PlugClean manages are git repos within that git repo. When I clone my dot file repo on another machine, the various plugin directories are empty (per git design). When I run PlugInstall, I get "PlugClean required" based on this code:

    def update(self):
      match = re.compile(r'git::?@')
      actual_uri = re.sub(match, '', self.repo_uri())
      expect_uri = re.sub(match, '', self.args['uri'])
       if actual_uri != expect_uri:
        msg = ['',
               'Invalid URI: {0}'.format(actual_uri),
               'Expected     {0}'.format(expect_uri),
               'PlugClean required.']
...

The expect URI it prints is the parent dfm repo URI.

After I do the clean, it does install correctly.

**Comment by junegunn** [comment]
I don't know what dfm is and how it works. Maybe it's not compatible with vim-plug and if so, you may need to make exceptions for vim plugins. Can you post the output of `:PlugStatus` when that happens?

**Comment by starcraftman** [comment]
@gerases Out of curiosity, can you post a link to this dfm program? Not familiar with it either.

> When I clone my dot file repo on another machine, the various plugin directories are empty (per git design). 

Lets say your plugin folder is `~/.vim/plugged`, are you saying that when you clone your dot files you have a whole bunch of empty folders like `~/.vim/plugged/plugin1` and `~/.vim/plugged/plugin2`. Where plugin1 & plugin2 are names of plugins in your vimrc.

**Comment by gerases** [comment]
Hi guys,

Here it is: https://github.com/justone/dfm

Basically, you create a repo with all your dot files, go to a machine,
check it out, run "dfm install" and it creates symlinks to all the dot
files inside the repo. So, at the root of that repo there's a .git
directory.

And now, because the vim plugins are also git repositories, there are
additional repos underneath. So, the structure looks like this:


$HOME/.dotfiles/.git
$HOME/.dotfiles/.vim/plugged/vim-abolish/.git
$HOME/.dotfiles/.vim/plugged/vim-repeat/.git
...

These additional .git folders become submodules in git and when the parent
repo is checked out, they are not checked out by default. Instead, an empty
directory is there. So, those additional .git directories are not there.

So, when I go to a new machine and check out the dotfiles repo, I run
:PluginInstall

What I get is a block of this for each plugin:

...
 x vim-easy-align

     Invalid URI: git@github.org:gerases/dfm.git
     Expected:    https://git::@github.com/junegunn/vim-easy-align.git
     PlugClean required.
...

Hope this makes sense,
   Sergei

**Comment by junegunn** [comment]
I'm not sure if I correctly understood the way dfm works, but I think you should add `.vim/plugged` to `.gitignore` file of the repository so that they are not added to it.

**Comment by starcraftman** [comment]
@gerases I agree with @junegunn, you should git ignore the whole plugin directory. Don't forget to purge the existing plugin submodules too. If you want dfm to track & update these git repos then I'd suggest a lighter plugin manager like pathogen, that only updates the runtime. If you use vim-plug, you should let us handle the repos entirely.

**Comment by gerases** [comment]
Hmm, yeah, that might be a good idea to put those into the ignore file.
I'll think about it.

But I was thinking that vimplug could detect that the target directory is
completely empty and just clone the corresponding repo in there?

Thanks!!

**Comment by gerases** [comment]
I believe Vundle handles this situation

**Comment by junegunn** [comment]
@gerases Well, I don't think it "handles" the situation. It simply ignores what's already there. vim-plug on the other hand is trying to play it safe, which I think is the right approach.
