### ISSUE TITLE
ctrlspace and vim plug lazy load

### ISSUE THREAD

**Issue by agauniyal** [junegunn/vim-plug#265]
Skipping straight to issue : https://github.com/szw/vim-ctrlspace/issues/133

**Comment by starcraftman** [comment]
@agauniyal I believe you are having an issue we've seen before. This is a YCM specific problem. See the response in issue #259 . Does adding that autocmd fix it?

**Comment by agauniyal** [comment]
@starcraftman yes it works after adding that particular statement. Should I report this issue to YCM maintainer or is this just required behavior of that plugin?

**Comment by junegunn** [comment]
@vheon is one of the maintainers of YCM and has been an active contributor to vim-plug, thus the best person we can ask about this.

@vheon Can you comment on this issue?

**Comment by vheon** [comment]
After #149 I did some digging and experiments and the results can be found at https://github.com/Valloric/YouCompleteMe/issues/1331#issuecomment-72748155. Now, Ultisnips dropped the support for vim 7.3, so we have to do it like we do it right now just for backward compatibility. When, and if, we drop the support for vim 7.3 then you can lazy load YCM without the additional line. If I misunderstood or I wasn't clear on something let me know ;)

**Comment by starcraftman** [comment]
@vheon Alright, that makes sense. So as expected, its a plugin behavior, and works that way for old vimmers.

@agauniyal I think that answers everything, I don't see any need for a change. I'll be closing this then, happy vimming.
