### ISSUE TITLE
suggestion: use vimproc on windows, if installed

### ISSUE THREAD

**Issue by VanLaser** [junegunn/vim-plug#266]
(as title says, and if possible) Using [vimproc](https://github.com/Shougo/vimproc.vim) instead of `system()` may help hiding the `cmd` console windows when running git.

**Comment by junegunn** [comment]
Hi, thanks for the suggestion, but I'd like to avoid adding external dependency even if it's optional and keep vim-plug as simple/small as possible. Relatedly, I mentioned my reluctance to have to depend on compiled binary in the [blog post](http://junegunn.kr/2013/09/writing-my-own-vim-plugin-manager/) I first wrote about vim-plug.

The `cmd` console stays minimized in the background, right? So personally I'm not really bothered by it that much and adding more code just to hide the flashing icons in the taskbar doesn't seem worthwhile to me.
