### ISSUE TITLE
Add help file

### ISSUE THREAD

**Issue by m1foley** [junegunn/vim-plug#268]
Like many users, I rely primarily on the Vim help system to get information about my plugins. I expected `:help Plug`, `:help PlugClean`, etc. to work, but vim-plug doesn't have a help file. I suggest installing a help file, maybe alongside `plug.vim` in the `curl` command, and during `PlugUpgrade` as well.

**Comment by vheon** [comment]
Duplicate of #234?

**Comment by m1foley** [comment]
Yes. Closing.
