### ISSUE TITLE
Markdown Errors appear when used with eclim

### ISSUE THREAD

**Issue by matthewfranglen** [junegunn/vim-plug#269]
### Steps to Reproduce

* Install vim 7.4.764

* Using the .vimrc:

```vimrc
silent !mkdir --parents ~/.vim/autoload
silent !curl --fail --location --output ~/.vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

call plug#begin('~/.vim/plugged')
call plug#end()
```

* Install eclim 2.4.1

* Open the following file named README.md:

```markdown
A Sample File
=============
```

* Save the file with `:w`

### Expected Results

No errors.

### Actual Results

The first line of the file is highlighted and the following message appears in the statusline:
```
loc - (1 of 1): plain text isn't allowed in <head> elements
```

**Comment by matthewfranglen** [comment]
I don't know which plugin is responsible for the errors so I have opened this against eclim too: https://github.com/ervandew/eclim/issues/425

**Comment by starcraftman** [comment]
@matthewfranglen Well I just made a test user to give this a go. I used local vim 7.4.803 & downloaded latest stable Eclipse 4.5 java EE edition (Mars). I then followed eclim gui install instructions for 2.5.0 (latest stable). I tested all that worked, no issues with README example so far. Then I added your .vimrc, still no issues.

Maybe it is a 2.4.1 bug? I suggest you try a fresh install of eclipse 4.5 with eclim 2.5.0 and seeing if you can reproduce. I can't.

**Comment by matthewfranglen** [comment]
Thanks for looking into this. I will update my plugins.
