### ISSUE TITLE
bin/install script to install plugins from cli,script

### ISSUE THREAD

**Issue by breerly** [junegunn/vim-plug#271]
I'd like to be able to install plugins from a script, like with ansible for example.

Examples:

* https://github.com/Shougo/neobundle.vim/tree/master/bin
* https://github.com/tmux-plugins/tpm/tree/master/bin

**Comment by junegunn** [comment]
Have you tried `vim +PlugInstall +qa`?

**Comment by breerly** [comment]
I tried that but it hangs from a script - probably because it uses a vim window for all the visualizations

**Comment by junegunn** [comment]
It's probably something in your config. There are many number of users including myself using that without a problem. See: https://github.com/search?utf8=%E2%9C%93&q=%22vim+%2BPlugUpdate%22&type=Code&ref=searchresults

**Comment by starcraftman** [comment]
@breerly We definitely work from command line, I use that in one of my update scripts. If you want to easily test for a vimrc issue, move your `~/.vimrc` -> `~/.vimrc_bak and `~/.vim` -> `~/.vim_bak` and then simply try any simple config. Like the following, if it doesn't work something serious wrong :/

```vim 
call plug#begin('~/.vim/plugged')

" Make sure you use single quotes
Plug 'junegunn/seoul256.vim'
Plug 'junegunn/vim-easy-align'

" Group dependencies, vim-snippets depends on ultisnips
Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'

" On-demand loading
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'tpope/vim-fireplace', { 'for': 'clojure' }

" Using git URL
Plug 'https://github.com/junegunn/vim-github-dashboard.git'

" Plugin options
Plug 'nsf/gocode', { 'tag': 'v.20150303', 'rtp': 'vim' }

" Plugin outside ~/.vim/plugged with post-update hook
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': 'yes \| ./install' }

" Add plugins to &runtimepath
call plug#end()
```
