### ISSUE TITLE
[feature request] Option for Plug to put plugin runtime paths at the end (append, not prepend).

### ISSUE THREAD

**Issue by trusktr** [junegunn/vim-plug#275]
Plug seems to prepend plugin `rtp`s to the `&runtimepath`. This means any plugin can override my

```
runtime foo.vim " without exclamation mark
```

which is a security concern. Could you add an option to have Plug append instead of prepend? Perhaps on a per-plugin basis, but also a default global option?

**Comment by junegunn** [comment]
vim-plug keeps the first path of &rtp at the front. So in my case it becomes:

`/Users/jg/.vim,PLUGINS,PLUGIN-AFTERS,/Users/jg/.vim/after`

So if you haven't manipulated the &rtp, you don't have to worry. And if you do add other paths to &rtp manually, you can prepend them to the front, right? `set rtp^=...`

**Comment by trusktr** [comment]
An option to make it do `/Users/jg/.vim,/Users/jg/.vim/after,PLUGINS,PLUGIN-AFTERS` no amtter what would be nice!

**Comment by junegunn** [comment]
You can add this after `plug#end()`:

```vim
set rtp-=~/.vim
set rtp-=~/.vim/after
set rtp^=~/.vim/after
set rtp^=~/.vim
```

But I'm curious, do you really need `after` directory to be there? Isn't the purpose of `after` directory is to finally override the settings?

**Comment by trusktr** [comment]
@junegunn Well, specifically, neovim adds these autoamtically:

```
/home/trusktr/.nvim,/usr/share/nvim/vimfiles,/usr/share/nvim/runtime
```

So I'd like them to be 

```
/home/trusktr/.nvim,/usr/share/nvim/vimfiles,/usr/share/nvim/runtime,PLUGINS,PLUGIN-AFTERS
```

I don't mind if anything put stuff in `after` but I don't want system folders overriden. I suppose plugins could override them too.

I wonder if there's a way to get the system folders (without knowing what system you're on) to prepend them after loading plugins?

**Comment by junegunn** [comment]
I see, assuming that you don't manually update `&rtp`:

```vim
for d in reverse(filter(split(&rtp, ','), 'stridx(v:val, g:plug_home) < 0'))
  execute 'set rtp-='.d
  execute 'set rtp'.(d =~ 'after$' ? '+=' : '^=').rtp
endfor
```

If the assumption is not true, you can use `$VIMRUNTIME` for filtering.

Not sure if this should be the default behavior, though. Some people might prefer that the plugins they installed override the system defaults.
