### ISSUE TITLE
Does not works when inside a `git worktree`

### ISSUE THREAD

**Issue by KangOl** [junegunn/vim-plug#277]
When launching vim inside a git worktree [1] and running `PlugUpdate`, the wrong repository is used.

[1] https://github.com/blog/2042-git-2-5-including-multiple-worktrees-and-triangular-workflows

**Comment by starcraftman** [comment]
@KangOl When making bug reports, please provide as many details as possible. For instance, exact steps to reproduce or a screen capture/text of the error. I don't know what to do on my system to reproduce this problem. Please give me steps to reproduce from a clean config, including a min vimrc to test with.

Side Note: This new feature seems a bit superfluous considering the ease of `stash` and branch switching.

**Comment by junegunn** [comment]
@starcraftman Thanks.
@KangOl Yeah, we need a simple scenario to reproduce the problem. It would be great if you could explain why someone would want to use `git worktree` (which I'm not familiar with) with vim-plug.

**Comment by KangOl** [comment]
My bad :(

I well know that bug report should include as much details as possible, and even I make the mistake.

`git worktree` may be use full when you need to compare files in 2 different branches, or if you switch a lot between branches. 

Whatever, when trying the create a reproduce scenario, I failed and cannot reproduce the bug I got.

The bug was that vim-plug told me to run `PlugClean` because the remote of my plugged plugins were wrong. For all plugins, it was the remote of the git in my current directory (which was a worktree, that why I thought that was the source of the problem).

Closing this issue as "Not Reproductible"

**Comment by starcraftman** [comment]
@KangOl Well if it happens again, feel free to reopen or make a new bug report.
