### ISSUE TITLE
nvim +PlugInstall

### ISSUE THREAD

**Issue by vaxXxa** [junegunn/vim-plug#279]
Hi. Just want to update my plugins from shell script.

```bash
$ nvim +PlugInstall +qall &> /dev/null
```
Error: [1]    4593 abort      nvim +PlugInstall +qall &> /dev/null

Only works with interactive mode:
```bash
$ nvim +PlugInstall
```

**Comment by junegunn** [comment]
1. See #104.
2. Does your nvim `has('python')`?

**Comment by starcraftman** [comment]
@vaxXxa Did your issue get resolved? It has been a few days...

**Comment by starcraftman** [comment]
Well it has been 12 days from original post, if you have a problem still ping me here or make a new issue.

**Comment by vaxXxa** [comment]
@starcraftman I just use:
```bash
$ nvim +PlugInstall +qall
```
and it's ok (plugins installed and I can use this in my shell scripts).. But when I append "&> /dev/null", get the same error, as I described.
