### ISSUE TITLE
Functions on load

### ISSUE THREAD

**Issue by azure-satellite** [junegunn/vim-plug#282]
It would be useful to execute a callback when a plugin has been loaded. For example sometimes I undo settings from some plugins but I would not want to do that if the plugin in question has not been loaded.

**Comment by junegunn** [comment]
> if the plugin in question has not been loaded

How so? You can be sure that the plugins are loaded when you run some code on `VimEnter` event. For lazy-loaded plugins, you call attach callbacks to their `User` autocmds.

**Comment by azure-satellite** [comment]
I didn't know about `User`, but wouldn't the plugin author have to provide this functionality? If that's so, I wouldn't count on it.

**Comment by junegunn** [comment]
> wouldn't the plugin author have to provide this functionality

Nope. `autocmd! User PLUGINNAME YOURCODE` will do.

See https://github.com/junegunn/vim-plug#on-demand-loading-of-plugins

**Comment by azure-satellite** [comment]
Awesome! Thank you

**Comment by davidosomething** [comment]
@junegunn does that au only run for lazy loaded plugins, or always after any plugin is loaded?

**Comment by junegunn** [comment]
Only when a plugin with `on` or `for` option is loaded. Unnecessary otherwise.
