### ISSUE TITLE
AD7six/vim-activity-log not work

### ISSUE THREAD

**Issue by liuyang1** [junegunn/vim-plug#284]
vim-plug is great! it's fast, even I work with 50+ plugin.

Today, I find this plugin
    https://github.com/AD7six/vim-activity-log
However, it cannot work when with "Plug 'AD7six/vim-activity-log'".
vim-plug could install this plugin, but cannot make it work.

copy the vim-activity-log plugin content to .vim, it works.

I am not sure detail of vim plugin. Anyone could give me hints?

**Comment by junegunn** [comment]
It works for me. It's probably an issue of your configuration file.
Post your vimrc here and we'll take a look.

**Comment by starcraftman** [comment]
Works for me too. Local config problem surely.
