### ISSUE TITLE
Problem (and a solution) when running vim-plugin with cygwin

### ISSUE THREAD

**Issue by bruno-** [junegunn/vim-plug#287]
Hi,
thanks for making and maintaining this great plugin!

I experienced problems when using `vim-plug` with cygwin on windows 10 with **default packages** installed.
When the command `PlugInstall` was invoked, vim would quit with `Caught deadly signal SEGV`. As described in [this wiki entry](https://github.com/junegunn/vim-plug/wiki/faq#vim-caught-deadly-signal-segv), adding `let g:plug_threads=1` solves the issue.

However, I dug a little deeper and realized that by default `ruby` does not work when cygwin's default packages are installed. For example:

    ruby -e "puts RUBY_VERSION"

would error with `cannot load such file -- rubygems.rb (LoadError)`.

Logically, just installing `rubygems` cygwin package fixes ruby issue. This also fixes `vim` + `vim-plug` segfault so things work fine (even when `let g:plug_threads=1` is removed).

I propose adding the following to [this wiki section](https://github.com/junegunn/vim-plug/wiki/faq#vim-caught-deadly-signal-segv):

```text
If you're on cygwin please also verify that ruby is working by running the following line in the terminal:

    ruby -e "puts RUBY_VERSION"

If you get the error: `cannot load such file -- rubygems.rb (LoadError)`, then installing `rubygems` cygwin package should fix the issue. After that, `vim-plug` should work fine.
```

Hopefully that will save people some time.

Feel free to close this issue whenever as the problem is resolved.

**Comment by starcraftman** [comment]
Hi @bruno- glad you like vim-plug. The Windows experience definitely isn't perfect. I see no problem adding that information to the wiki, will go do it now. Might be good if I checked the Windows python experience too, been a while.

You may also be interested in [babun](https://github.com/babun/babun), if you hadn't heard of it. Has some nice improvements over vanilla cygwin including a package manage like interface called pact.

**Comment by starcraftman** [comment]
Edit made, is that clear enough for you @bruno- ?

**Comment by junegunn** [comment]
Thank you both :+1:

**Comment by bruno-** [comment]
Thanks @starcraftman, the update looks good :+1:
I'll look into babun, didn't know about it.

Feel free to close the issue guys!
