### ISSUE TITLE
Problems cloning vim-powerline

### ISSUE THREAD

**Issue by thomasba** [junegunn/vim-plug#291]
Hello,
I having problems cloning the [Lokaltog/vim-powerline](https://github.com/Lokaltog/vim-powerline) repo. After installing or updating the plugins using Plug this is the full git log:

```
commit 114f8e5c204f1cac9b2443065910fa182de39fb8
Author: Kim Silkebækken <kim.silkebaekken@gmail.com>
Date:   Fri Nov 18 17:02:14 2011 +0100

    Initial commit
```

also setting `let g:plug_shallow=0` doesn’t resolve the problem. The problem occurs on several different systems (Arch Linux and Ubuntu).
What informations do you need?

**Comment by junegunn** [comment]
vim-plug uses `master` branch by default but the default branch of the plugin you mentioned is `develop` so you have to write `{ 'branch': 'develop' }`. By the way the plugin seems to be abandoned. You might want to check out airline or lightline instead.

**Comment by junegunn** [comment]
Related: #257 #288

**Comment by starcraftman** [comment]
+1 for airline. Nothing much else to contribute.

**Comment by thomasba** [comment]
Oh, didn’t see that it’s another branch… Thanks for the alternatives, airline looks good :+1:
