### ISSUE TITLE
How do you specify plugins from local directories on windows?

### ISSUE THREAD

**Issue by jimmyharris** [junegunn/vim-plug#292]
I am trying to create a plugin for local additions to my vim config that are not tracked by my repository and I figured the easy way to do that would be to add the path that would be local to my vim runtime path.  Unfortunately expressing the path: `$HOME\vimfiles\local` or `$HOME/vimfiles/local` makes Plug think that I am trying to source a github repository.  What is the proper syntax for this? Is there a proper syntax for this on windows?

**Comment by junegunn** [comment]
I don't use windows, so I'm not perfectly sure if it's appropriate but anyway this is the checker function on windows:

```vim
  function! s:is_local_plug(repo)
    return a:repo =~? '^[a-z]:\|^[%~]'
  endfunction
```

So it should be either an absolute path starting with a drive letter, or path starting with an environment variable in %VAR% form.

**Comment by jimmyharris** [comment]
Thanks! I will let you know if that works.

**Comment by jimmyharris** [comment]
One thing to consider. Drive letters should be case insensitive right? Other than that using ~ worked perfectly.

**Comment by junegunn** [comment]
Yeah, `=~?` is a vim operator for case-insensitive match. So everything okay?

**Comment by jimmyharris** [comment]
I did not know that. If that is the case then we are good to go.

**Comment by starcraftman** [comment]
@jimmyharris It wasn't obvious to me when I started writing vimscript either. It's an old language, with some incredibly dated ideas.

**Comment by jimmyharris** [comment]
Thanks again for your help!
