### ISSUE TITLE
Parallel install and update not working on Windows 10

### ISSUE THREAD

**Issue by amosbird** [junegunn/vim-plug#294]
I've manually compiled `Vim` and `Ruby` on Windows 10 with VS2013, and set `g:plug_threads = 16`. There is still only one working thread.

**Comment by junegunn** [comment]
So the ruby interface works find just as expected?
1. `:echo has('ruby')` should print 1
2. `:ruby puts RUBY_VERSION` prints the Ruby version used

**Comment by amosbird** [comment]
Thanks for the reply. I forgot to add ruby dll to `PATH`. After I did, `:echo has('ruby')` prints 1, but `:ruby puts RUBY_VERSION` corrupts gvim.
![5 f49hsqm8 nfb0p7 l_vc](https://cloud.githubusercontent.com/assets/5085485/10443461/2b4970f2-718e-11e5-9559-7b0fb94a9a40.png)
![2qf nagrf gd 3 a0u9](https://cloud.githubusercontent.com/assets/5085485/10443462/2d34623c-718e-11e5-8047-8eae6cc419d3.png)

**Comment by amosbird** [comment]
Thanks for the reply. I forgot to add ruby to `PATH`. Now I ran into the same issue with #81 . Hope it be fixed someday:)
