### ISSUE TITLE
Vim Segfaults when adding more than Plugin on Fedora 23

### ISSUE THREAD

**Issue by Aikidouke** [junegunn/vim-plug#295]
Fedora 23 - xfce4-terminal - Vim - version 7.4.827.

I follow the install instructions in the README. I call plug#begin and plug#end as described. I add;

    Plug 'scrooloose/nerdtree'

I source vimrc with;

     :so ~/.vimrc 

and run :PlugInstall and everything works. When I try to add another Plugin either as above or via git url, I can source the new .vimrc, but running :PlugInstall results in a crash and segfault of vim.

**Comment by junegunn** [comment]
- Check the output of `:echo has('ruby')`
    - If it's `1`, see if `:ruby puts RUBY_VERSION` works
        - If it causes segfault, it means your Ruby interface is broken. How did you install Vim? Can you try rebuilding it?
- Check `:echo has('python')`
    - See if `:python import sys; print(sys.version)` works

**Comment by Aikidouke** [comment]
It was Ruby. I must've installed Ruby before vim-plug on my last set up and forgotten about it. Thanks for your help.

**Comment by junegunn** [comment]
So did you resolve the problem?

**Comment by Aikidouke** [comment]
Yes, thank you.
