### ISSUE TITLE
vim startup statistics

### ISSUE THREAD

**Issue by hyiltiz** [junegunn/vim-plug#298]
I have created a set of simple scripts that deal with startup timing. The raw vim log output has timing for each function call, but not for each plugins. So doing a simply statistics would be great. This is written in bash (and awk, sed, grep) along with R:ggplot2 package. It would be great if you could mention this project the lazy-loading and optimization section in the README.md for your project. Would that be possible?

https://github.com/hyiltiz/vim-plugins-profile

**Comment by junegunn** [comment]
Hi, that looks pretty cool, thanks. I'll try it out and give you feedback when I get home.

**Comment by hyiltiz** [comment]
Great! I can imagine making it require less packages (e.g. R, R:ggplot2), because as long as we do not do the plotting, all the computations would be done with Python/Perl/Ruby, or even Awk (which I prefer). Given that everyone has `awk`, then we can do the parsing all by itself. However, I feel that mostly it is too much a work just to optimize for an 100-300ms of vim startup. Do you think restricting the project into only using Bash and `awk` and not using R a necessary direction?

**Comment by junegunn** [comment]
> Download the .zip here and then simply run the bash script

The download link seems to be broken. Anyway it looks like the script needs some improvements:
- It silently fails if the required binary (R) is not found. The script should check the availability of the binaries.
- It also should check if the execution was successful (`$?`). Having `set -eu` at the top of the script is a recommended way to write safer shell scripts.
- In that case, you might want to remove `-q` flag, so that the user can see what went wrong.
- I don't think many users are familiar with R ecosystem. I had to google how to install R package. I think the README file should show how to install prerequisites.
- I'm getting `Error in eval(expr, envir, enclos) : object 'V4' not found` from R command (w/o `-q`)
- The script also has a bug of looking for `results.csv` instead of `profile.csv`. Right?

> because as long as we do not do the plotting

Actually the plotting part was what I found interesting. I don't really have problem reading the output of `--startuptime`, but I thought a chart would be cool. How about using `gnuplot`? It's more universal and probably simpler to install than R and ggplot package on most platforms. Or you can just fall back to ascii charts that looks like:

```
plugin-a: *******
plugin-b: ***
plugin-c: **************
...
```

**Comment by hyiltiz** [comment]
Yeah, I am also familiar with gnuplot but it's figures look less shiny. I
can give it a shot, though, checking the availability of gnuplot then using
whichever is there.

I am sorry for the V4 issue: it should be a scope problem. I could run the
program without issues so maybe we have different versions of packages?

I will fix the csv bug now. Thx!


On Sun, Oct 18, 2015 at 8:55 AM Junegunn Choi <notifications@github.com>
wrote:

> Download the .zip here and then simply run the bash script
>
> The download link seems to be broken. Anyway it looks like the script
> needs some improvements:
>
>    - It silently fails if the required binary (R) is not found. The
>    script should check the availability of the binaries.
>    - It also should check if the execution was successful ($?). Having set
>    -eu at the top of the script is a recommended way to write safer shell
>    scripts.
>    - In that case, you might want to remove -q flag, so that the user can
>    see what went wrong.
>    - I don't think many users are familiar with R ecosystem. I had to
>    google how to install R package. I think the README file should show how to
>    install prerequisites.
>    - I'm getting Error in eval(expr, envir, enclos) : object 'V4' not
>    found from R command (w/o -q)
>    - The script also has a bug of looking for results.csv instead of
>    profile.csv. Right?
>
> because as long as we do not do the plotting
>
> Actually the plotting part was what I found interesting. I don't really
> have problem reading the output of --startuptime, but I thought a chart
> would be cool. How about using gnuplot? It's more universal and probably
> simpler to install than R and ggplot package on most platforms. Or you can
> just fall back to ascii charts that looks like:
>
> plugin-a: *******
> plugin-b: ***
> plugin-c: **************
> ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/junegunn/vim-plug/issues/298#issuecomment-149008801>.
>
-- 
from Google Inbox

**Comment by hyiltiz** [comment]
I have updated the scripts and thanks for your feedback! I believe the issues are resolved now in `master` branch. You are very welcome to check out, and please let me know if something turns out unexpectedly.

**Comment by junegunn** [comment]
Unfortunately I'm still running into some R issue that I have no clue about.

```
Generating vim startup profile...
Assuming your vimfiles folder as `~/.vim/`
vim-plug has been detected.
Parsing vim startup profile...
Crunching data and generating profile plot ...

Loading required package: ggplot2
Package R caused a warning:
Here's the original warning message:
Removed 43 rows containing missing values (stat_summary).
Your plugins startup profile graph is saved
as `result.png` under current directory.

==========================================
Top 10 Plugins That Slows Down Vim Startup
==========================================
cat: result.csv: No such file or directory
==========================================
Done!
```

- `R version 3.2.2 (2015-08-14) -- "Fire Safety"`
- Installed `ggplot2_1.0.1` with `install.packages("ggplot2")`

**Comment by starcraftman** [comment]
@hyiltiz Pretty cool, I shall give it a spin later.

@junegunn Are you thinking of including this some way? Maybe as a wiki tip?

**Comment by junegunn** [comment]
@starcraftman Yeah, [wiki](https://github.com/junegunn/vim-plug/wiki/extra) seems to be the right place for this. I was intrigued by the bar chart image. Unfortunately, installing R and the package on OS X isn't as trivial as I would like it to be, so I'm a bit reluctant to mention it on the front page.

**Comment by vheon** [comment]
@hyiltiz be aware that some plugin (YouCompleteMe) do not actually fully load when vim starts up but rather on `VimEnter` autocmd. I don't know if you care/cover this but could result in a not-so-true statistic.

**Comment by hyiltiz** [comment]
@junegunn Yes, I hate to admit that I used R and one popular but not default package for it. It should even be possible using some functionality that ships with the OS by default, such as Python or Perl libraries (I was looking at the git-cal project and it seems they only use Perl to get the shiny terminal figures). I am considering to add a feature where the program checks the availability of some other popular plotting tools, namely `Python:matplotlib` or `gnuplot`. I am not familiar with Perl, or we could even have been doing the plots even without any extra packages.

Sure, the project goes *against* `vim-plug`s minimalist approach (not for me, though, since I always have `R:ggplot2` and `gnuplot` installed. So front page could be disgraceful. The wiki sounds a better idea. Thanks!

**Comment by hyiltiz** [comment]
@vheon I did not expect that! If we cannot get the profiling raw data for `VimEnter`ed plugins by vim --startuptime vim.log -c q`, do you know any way we could simulate the `VimEnter`? Maybe open `Vim` then kill it externally?

**Comment by vheon** [comment]
I usually do it like this:

* start vim like [in this script](https://github.com/vheon/home/blob/138f475174f0223754a9397da89984aafc9070c0/bin/startvimprofile)
* once vim starts end profiling with [this command](https://github.com/vheon/home/blob/ea91f443b33bc15d0deaa34e172a0317db63a53d/.vim/vimrc#L247) (look at the function definitionthen)

**Comment by DSIW** [comment]
I [rewrote this script](https://gist.github.com/DSIW/326627a1024026c31774) and it uses ruby without any dependency. The graph will be displayed as stars:
```
surround: (0.156ms) **********************
   ctrlp: (0.153ms) ******************
  switch: (0.141ms) ****************
```

I'm not sure if I it's correct to add source time and exec time of the vim log entry ([see this line](https://gist.github.com/DSIW/326627a1024026c31774#file-vim-plugins-profile-rb-L34)).

**Comment by hyiltiz** [comment]
​Hi junegunn,

This seems cool! I am not proficient in Ruby though I can read simple Ruby.
Could you tell me how the seconds are calculated? Does it follow the same
logic, a simple sum aggregation of the profile table based on file name? I
see you are using a hash table, which seems to be what I mean. If you could
make sure that this script produces the same numeric output as the bash+R
case, I would be more than glad to merge a pull request.​

**Comment by DSIW** [comment]
Now it calculates the exact same numbers. I've created a [pull request](https://github.com/hyiltiz/vim-plugins-profile/pull/7).

**Comment by junegunn** [comment]
@hyiltiz Not me :)
