### ISSUE TITLE
Running PlugInstall freezes vim

### ISSUE THREAD

**Issue by gblock0** [junegunn/vim-plug#299]
I just updated to El Capitan and when I run PlugInstall vim freezes up. I am not using Tmux, just iTerm. I have tried updating to the latest plug.vim file but it still freezes up on cloning of a repository.

Any ideas of a work around?

**Comment by junegunn** [comment]
I didn't have the problem after the upgrade. Not sure what is going on. Does this command work?

```
:ruby puts RUBY_VERSION
```

And have you checked which processes are running with ps command during the time vim is unresponsive?

**Comment by gblock0** [comment]
After a restart it looks like it's working...It may have been LittleSnitch, although it's never given me trouble before.

Thanks!
