### ISSUE TITLE
feature request: add configuration for full path to git

### ISSUE THREAD

**Issue by jpleau** [junegunn/vim-plug#301]
Hi ! Thanks for this great plugin !

My use case: I have Git (2.6.2) installed on a Windows installation, but I cannot add it to my $PATH.

I've looked at plug.vim, and couldn't find a place to overwrite the git executable with a configuration.

Is this something that could be added ? I don't mind working on it if time is an issue (will need someone to review as I'm not well versed in VimL)

Cheers

**Comment by junegunn** [comment]
We don't add features/options that only apply to specific corner cases and it usually turns out that there are workarounds that do not require any change in vim-plug.

Note that you can set `$PATH` in vim just like any other variable. So you can put `let $PATH = $PATH . " ... "` in your .vimrc to have extended `$PATH` just for vim.

**Comment by starcraftman** [comment]
@jpleau Restricted your user admin have they? That will be annoying for development. 

Just a note regarding the possible patch @junegunn suggested, if you work on Windows & Linux frequently and want to alter your vimrc based on the platform. You can try this section in your vimrc. You may want to read up on `:h win32` and `:h win32unix`, latter flag indicates cygwin.

```viml
let g:win_shell = (has('win32') || has('win64')) && &shellcmdflag =~ '/'

if g:win_shell
let $PATH = 'git/location:' . $PATH
else
echo 'do stuff for posix only'
endif
```

**Comment by jpleau** [comment]
@starcraftman thanks ! This will do the job perfectly.

I can add Git to my PATH, but it conflicts with my multiple MinGW installations (the only reason I use Windows is to test that my code compiles and runs). I could have looked at fixing this instead, but the only problem I had with Git not in my path was with vim-plug, and your code fixes it rather beautifully.

Cheers

**Comment by starcraftman** [comment]
@jpleau What a nuisance Windows can be sometimes. Just a note, but there are services like [appveyor](http://www.appveyor.com) for Windows CI. Might alleviate having to maintain multiple setups on same machine.

In any event, happy vimming, whichever platform you find yourself on :)
