### ISSUE TITLE
Support to notFor configuration

### ISSUE THREAD

**Issue by jeanCarloMachado** [junegunn/vim-plug#302]
This would be the opposite of the ``for`` configuration.

I'm wanting to disable the loading of vim abolish for html, but I don't have a official way to achieve that through vim-plug.

**Comment by junegunn** [comment]
Considering the fact that it's not a common requirement and the added complexity (e.g. using both `for` and `not-for`), I'm not going to add the option.

You'll be able to implement your own loading strategy using `'for': []` (empty), `autocmd` and `plug#load()` function.
