### ISSUE TITLE
why not move plug.vim to autoload or symbol link it?

### ISSUE THREAD

**Issue by Treri** [junegunn/vim-plug#303]
why not move plug.vim to `autoload` directory or symbol link it to `autoload/plug.vim`?

If plug.vim is in autoload directory, we can just setup vim-plug like normal plugin.

When we firstly initialize vim-plug and other plugins, we can just git clone the repo to `~/.vim/plugged/vim-plug`, and then set below lines in vimrc

```
set rtp+=~/.vim/plugged/vim-plug

call plug#begin('~/.vim/plugged')

Plug 'junegunn/vim-plug'
Plug 'junegunn/fzf.vim'

call plug#end()
```

And maybe we can also use vim-plug to self update.

**Edit**:
I used vim-plug as what describe above, and moving plug.vim to autoload/plug.vim.
Work perfectly~

**Comment by junegunn** [comment]
See: https://github.com/junegunn/vim-plug/wiki/faq#shouldnt-vim-plug-update-itself-on-plugupdate-like-vundle
