### ISSUE TITLE
Add support for URLs pointing to zip files

### ISSUE THREAD

**Issue by emanuelez** [junegunn/vim-plug#304]
This would be useful to install plugins not using Git, such as this one: https://bitbucket.org/sw-samuraj/vim-gradle

**Comment by junegunn** [comment]
Sorry, it's beyond the scope of this project. Check out neobundle.

**Comment by starcraftman** [comment]
@emanuelez Might not have all the features, but when I mucked around with gradle before used this plugin: `Plug 'tfnico/vim-gradle'`.

Alternatively, if you don't want to mirror that on github, I'd suggest making a little script of your choice to fetch it via hg into the plugin dir, then simply set it to unmanaged by vim-plug. Not ideal, but workable.
