### ISSUE TITLE
Can't get plugin to load.

### ISSUE THREAD

**Issue by trusktr** [junegunn/vim-plug#305]
I'm trying to get [vim-qml](https://github.com/peterhoeg/vim-qml) or [qml.vim](https://github.com/calincru/qml.vim) to work, but no luck.

Here's what I've tried with both (i'll use only one for example):

```viml
https://github.com/calincru/qml.vim
```

```viml
https://github.com/calincru/qml.vim, { 'for': 'qml' }
```

```viml
https://github.com/calincru/qml.vim, { 'on': [] }
call plug#load('qml.vim')
```

and I've also tried `set ft=qml` with each of the above and with vim-qml. Any hints?

**Comment by junegunn** [comment]
calincru/qml.vim is not correctly laid out. peterhoeg/vim-qml works for me with or without `for` option.

Please note that `for` option for such filetype-specific plugins has no value. Such plugins are not loaded until a file of the type is open, so there's no point of using the option.
