### ISSUE TITLE
feature request: per language block for on demand

### ISSUE THREAD

**Issue by mooreniemi** [junegunn/vim-plug#308]
It'd be nice to do:

       Plug 'eagletmt/ghcmod-vim', 'bitc/vim-hdevtools', { 'for': 'haskell' }

instead of:

       Plug 'eagletmt/ghcmod-vim', { 'for': 'haskell' }
       Plug 'bitc/vim-hdevtools', { 'for': 'haskell' }

**Comment by vheon** [comment]
@mooreniemi actually in this particular example the `for` option is pretty basically useless :stuck_out_tongue_winking_eye:

**Comment by mooreniemi** [comment]
@vheon to rephrase, it'd be nice to do a block of plugins that all are on-demand loaded by language.

**Comment by vheon** [comment]
@mooreniemi yeah I know that yours was just an example, but my point was actually that the amount of plugins which could benefit from the `for` option is limited and for that I don't think that the amount of work required by this feature is justified. But I'm not the maintainer, so, who knows :)

**Comment by mooreniemi** [comment]
@vheon right now i have 6 plugins for Ruby, so that's why it appeals to me :)

**Comment by vheon** [comment]
@mooreniemi just out of curiosity can you post those plugins?

**Comment by mooreniemi** [comment]
sure:

    Plug 'ck3g/vim-change-hash-syntax'
    Plug 'vim-ruby/vim-ruby'
    Plug 'jgdavey/vim-blockle'
    Plug 'KurtPreston/vim-autoformat-rails'
    Plug 'tpope/vim-rails'
    Plug 'thoughtbot/vim-rspec'

**Comment by vheon** [comment]
A suggestion that I would like to do is to drop `jgdavey/vim-blockle` and `ck3g/vim-change-hash-syntax` in favor of [AndrewRadev/switch.vim](/AndrewRadev/switch.vim).

In any case how much do you gain using the `for` option? Have you measure it?

**Comment by junegunn** [comment]
I'd like to keep it simple since a one-liner helper command suffices:

```
command! -nargs=* Plugs for _ in [<args>][:-2] | Plug _, [<args>][-1] | endfor
Plugs 'eagletmt/ghcmod-vim', 'bitc/vim-hdevtools', { 'for': 'haskell' }
```
(what's missing is the type check of the last argument, but that's just a few lines of vimscript)

Anyway, as @vheon suggested, you should always [measure the `--startuptime`](https://github.com/junegunn/vim-plug#on-demand-loading-of-plugins) before applying `for` option. Most of the time, they're useless and incur unnecessary overhead (not noticeable though).

**Comment by mooreniemi** [comment]
@junegunn makes sense! thanks for the reply. @vheon nice find, thanks!
