### ISSUE TITLE
plug.vim not autoloading in ~/.config/nvim/autoload

### ISSUE THREAD

**Issue by RatanRSur** [junegunn/vim-plug#310]
I'm not sure if I'm placing this in the right directory, as the installation instructions assume vim but neovim recently switched to having the config files in `~/.config/nvim/` so I assumed that `~/.config/nvim/autoload` would be the analogous place to put `plug.vim`. Alas, it doesn't seem so.

**Comment by RatanRSur** [comment]
Nevermind, I found a stupid mistake!

**Comment by Arelav** [comment]
What is correct location? I have a same issue.

**Comment by RatanRSur** [comment]
My mistake was simply not closing the quotes around the plug path. The line currently looks like:

`call plug#begin('~/.config/nvim/plugged')`

**Comment by starcraftman** [comment]
@Arelav Hmmm, maybe we'll have to rethink front page documentation now that neovim and windows there. I thought it was fairly clear you'd have to change the begin call.

**Comment by Arelav** [comment]
@starcraftman The issue was when ~/.config/nvim/autoload/plug.vim is simlink to ~/.config/nvim/plugged/plug.vim

If i install plug.vim directly into autoload - it's work (In other case i haven't Plug option). But i not really happy, because i can't auto update plug with plug.

**Comment by starcraftman** [comment]
@Arelav I'd advise against that symlinking setup. Vim-plug works best from autoload, we provide `PlugUpgrade` to do an upgrade. One of the advantages of separate upgrade system is regardless how we might break an installer method (say nvim or python) the upgrade always works.

If you really must upgrade and update at once you can use a command alias to something like `PlugUpdate | PlugUpgrade` or if scripting you can use `vim +PlugUpdate +PlugUpgrade +qa`.

**Comment by diegocarrion-wk** [comment]
My solution is to symlink .config/nvim/ to ~/.vim/  and include a symlink within the same directory from init.vim to vimrc

**Comment by Curry2323** [comment]
Thanx
