### ISSUE TITLE
Add global option to disable .old backup file

### ISSUE THREAD

**Issue by svenstaro** [junegunn/vim-plug#311]
Some people like me would perhaps prefer for vim-plug not to make a .old backup file of itself. For instance, I keep plug.vim in a dotfiles git repo and thus it's annoying and superfluous.

**Comment by starcraftman** [comment]
@svenstaro I'd suggest just add it to your .gitignore for the repository. For example, if its in your root:
 `.vim/autoload/plug.vim.old`

Since @junegunn likes to keep it simple, pretty certain his answer shall be no.

**Comment by svenstaro** [comment]
I'd like to leave this open. I know what the obvious solution would be. It just feels wrong that there is a file being created without you being able to shut that down.

**Comment by junegunn** [comment]
How about simply deleting the file yourself after `PlugUpgrade`? Defining a custom command that does that should be just a single line of vimscript.

**Comment by junegunn** [comment]
Or we could consider adding a bang version of PlugUpgrade. Not sure if it'll turn out to have been a short-sighted decision.

**Comment by starcraftman** [comment]
@junegunn Seems a bit unusual that your entertaining a command change for this kind of small issue.

IMO, this is for the tips/faq and we add an entry titled: `Bothred by backup file?` or some such with solutions:
1. gitignore it
1. command wrapper example for vimrc that deletes it

I guess I'm just too easy going with my programs creating files.

**Comment by junegunn** [comment]
@starcraftman I know, but by convention the bang command is a "dangerous" version of its non-bang counterpart (e.g. like we do in `:PlugClean!`), so I just thought it's a sensible choice to add `:PlugUpgrade!` that deletes the backup. However I agree that the change is largely unnecessary.
