### ISSUE TITLE
Post update hook not executing

### ISSUE THREAD

**Issue by helpermethod** [junegunn/vim-plug#312]
Hi,

I have following post update hook configured to setup YCM:

    Plug 'Valloric/YouCompleteMe', { 'do': 'sudo apt-get install -y build-essential cmake python-dev \| ./install.py' }

While the `./install.py` gets executed it seems the `apt-get` to install the necessary dependencies is never called.

**Comment by starcraftman** [comment]
@helpermethod Hello. Remember that whatever is in the string value of `do` gets executed on the system shell. I think you should try the following set of commands in your shell to see the difference. The last line is what you want. The first is equivalent to what you asked plug to send.

```bash
echo "Hello" | echo "Hello2"
echo "Hello" || echo "Hello2"
echo "Hello" && echo "Hello2"
```

Hint: The '|' operator is the pipe in most shells, hence the output gets redirected into the second command. Where as `||` is logical or and '&&' is logical and.

**Comment by helpermethod** [comment]
Thank you very much for your explanation, that makes sense.
