### ISSUE TITLE
Segfault loading plugin

### ISSUE THREAD

**Issue by pwilkins** [junegunn/vim-plug#313]
When I add this line to my .vimrc, 
``Plug 'https://github.com/Rykka/riv.vim.git'``
I get a segmentation fault and vim exits.

I'm running vim 7.4 on OSX 10.10.5. I'm new to vim so the problem is probably user error. What additional information may I provide to resolve this problem.

Thank you, peter

**Comment by starcraftman** [comment]
@pwilkins Hello. Few notes/questions:

1. You can use the following shorthand for plugins on github.com. `Plug 'Rykka/riv.vim`
1. Can you try the scripting interfaces with the following lines. Start vim with`vim -u NONE` to prevent loading your config.
    1. `:python print 1`
    1. `:ruby puts 1`
1. If you are using homebrew, and one of the interfaces is causing it, can you try reinstalling vim from scratch.

**Comment by pwilkins** [comment]
Thank you for your prompt response! 
``:python print 1``  return ``1``
but 
``:ruby puts 1``
caused the same segfault I reported.
Trying vim reinstall through Homebrew.

**Comment by starcraftman** [comment]
@pwilkins I had figured as much. Seems on OSX ruby and vim always having trouble. :/ vim-plug uses the ruby interface for parallel downloading, hence the segfault. Any plugin would have caused the crash.

Incidentally, was the original vim version the default one or homebrew version?

**Comment by pwilkins** [comment]
I installed the original vim using Homebrew.  I just uninstalled and reinstalled vim using Homebrew and I still get the segfault from ``:ruby puts 1``.

This is the Homebrew command to install vim:
``brew install vim --override-system-vim --with-features=huge --disable-nls --enable-interp=lua,ruby,perl,python``
My primary language is Python and though I have Ruby installed through ``rvm`` I don't need vim support for it in my daily vim use.

**Comment by junegunn** [comment]
Try reinstalling vim after `rvm use system`.

**Comment by pwilkins** [comment]
Thanks, junegunn.  Reinstalling vim after ``rvm use system`` worked.  I'm now able to load plugins using ``vim-plug``.  :-)

**Comment by junegunn** [comment]
Cool, I'll have to update [the wiki page](https://github.com/junegunn/vim-plug/wiki/faq#vim-caught-deadly-signal-segv). It already mentions issues with rvm / rbenv but doesn't suggest `use system`.
