### ISSUE TITLE
Document example of how to use `on` combined with <Plug>

### ISSUE THREAD

**Issue by andrewferrier** [junegunn/vim-plug#317]
Hi - in `README.md`, you mention that on-demand loading with `on` can be enabled for "On-demand loading: Commands or <Plug>-mappings". I see examples of the former but not the latter (and I can't find any Vader test that uses the latter either). I think it would be very helpful to include one or two examples in the documentation; this sounds useful but I can't figure out what the syntax would be.

Thanks for your work on `vim-plug`; it's great!

**Comment by junegunn** [comment]
```vim
Plug 'junegunn/vim-easy-align', { 'on': ['<Plug>(EasyAlign)', 'EasyAlign'] }

" ...

" Start interactive EasyAlign in visual mode
xmap ga <Plug>(EasyAlign)

" Start interactive EasyAlign with a Vim movement
nmap ga <Plug>(EasyAlign)
```

This is how it's done. vim-easy-align will be loaded when `:EasyAlign` command is executed or when you hit `ga` which is mapped to `<Plug>(EasyAlign)`. I'm not sure if you're familiar with `<Plug>`-mappings but it's the recommended way for a plugin to provide users with a way to customize its key bindings.

The reason I did not give an example of that it's when I first implemented the feature, I was not so sure about its stability. Actually, on-demand loading in general is somewhat hacky, and may not work well with certain plugins, so it should be used judiciously and I'm worried that more examples will unintentionally encourage users to overuse it even when they don't need it. I'll think about it more later, thanks for the suggestion.

**Comment by atweiden** [comment]
Interesting. What are the best practices for lazy loading?

**Comment by junegunn** [comment]
> What are the best practices for lazy loading?

A rule of a thumb is: not doing it unless it's necessary.
Vim already has its builtin mechanism for not loading script files until they're needed, i.e. autoload functions, so a carefully structured plugin shouldn't take long to load. But since there are plugins that are not (e.g. NERDtree), we provide this workaround. In a perfect world, we can tell the developers to fix their code to load faster, but you know.
