### ISSUE TITLE
Repo Change 

### ISSUE THREAD

**Issue by kevinastone** [junegunn/vim-plug#320]
I updated my vimrc to use the ctrlp fork (`kien/ctrlp.vim => ctrlpvim/ctrlp.vim`) but I have to manually remove the git checkout to have it clone from the new repo location.  It would be nice if this could have re-cloned the repo on an install or update.

**Comment by starcraftman** [comment]
Well, this would be a behaviour change as currently only command that removes anything is PlugClean. Install or Update notify to run Clean when required. Update is already double duty doing install and update of plugins. I prefer the user having to remove it separately, while inconvenient he is aware of what is happening on his system. 

Also, I imagine if @junegunn wanted the kind of automatic resolution you described he'd have implemented it by now. He can give his final say when he's back, but I don't imagine he'd go for it.

For now you can make use of command aliases to expand something to `PlugClean! | PlugInstall`. Note on this last bit, cabbrevs sometimes cause problems (notably they expand in searches (`/` or `?`), you may want to look at my fork of [cmdalias](https://github.com/starcraftman/cmdalias.vim).

**Comment by junegunn** [comment]
> I prefer the user having to remove it separately, while inconvenient he is aware of what is happening on his system.

Nicely put. Repo changes are quite rare and I don't think we should risk losing local changes that might be in the directory for saving a few keystrokes for `PlugClean`. I'm closing the issue, thanks for the suggestion anyway.
