### ISSUE TITLE
Loading a plugin only on git project ? 

### ISSUE THREAD

**Issue by elrrrrrrr** [junegunn/vim-plug#322]
Is there anyway ? 
```
Plug 'airblade/vim-gitgutter' , {'for': git_project}
```

**Comment by vheon** [comment]
If you use [tpope/vim-fugitive](/tpope/vim-fugitive) then a simple solution would be:

```viml
Plug 'user/plugin', { 'on': [] }

...

autocmd User Fugitive call plug#load('user/plugin')
```

**Comment by starcraftman** [comment]
@elrrrrrrr You usually don't need these kinds of micro optimizations. Can I ask what plugin you are concerned about? Most plugins should behave well.

**Comment by elrrrrrrr** [comment]
@starcraftman 
such as
```
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-fugitive'
Plug 'Xuyuanp/nerdtree-git-plugin', {'on': ['NERDTreeToggle', 'NERDTreeFind']}
```

**Comment by starcraftman** [comment]
@elrrrrrrr Just my 2 cents, but those plugins don't strike me as being very heavy compared to other plugins like YCM. Have you done startup profiling with `vim --startuptime` to see the slow down when not in a git repo? I think Knuth had a quote on this. :) 

Regardless, I think @vheon's suggestion is adequate here. If there isn't anything else I guess you can close the ticket.

**Comment by elrrrrrrr** [comment]
@vheon  @starcraftman 3x for your help .

**Comment by starcraftman** [comment]
@elrrrrrrr Happy vimming :).
