### ISSUE TITLE
Wording in FAQ regarding g:plug_threads

### ISSUE THREAD

**Issue by nicolaiskogheim** [junegunn/vim-plug#323]
Hi!

I suggest changing the sentence in the FAQ, under [Vim: Caught deadly signal SEGV](https://github.com/junegunn/vim-plug/wiki/faq#vim-caught-deadly-signal-segv) (last sentence in that section),
from
> In the meantime, you can set `g:plug_threads` to 1, so that Ruby installer is not used at all.  

to

> In the meantime, you can use `let g:plug_threads=1`, so that Ruby installer is not used at all.  

or something along those lines.
________________

I just needed to do that after encountering the issue in #318, but I always get the vim script syntax messed up and try to do stuff like `set g:plug_threads = 1`. And, yes, setting that option resolved the freezing issue.

I could post my specs in that issue if you want to. To be brief I run
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 20 2015 09:52:41)
Included patches: 1-207, 209-801, 803-808, 810-827
+ruby/dyn +python/dyn +python/dyn
```
which is the standard distribution of huge vim on Fedora (package is called vim-enhanced).

EDIT: I didn't realize I didn't have ruby installed (this is on a fairly fresh install of Fedora). Installing ruby was definitively a better solution in this case, hehe.

**Comment by starcraftman** [comment]
@nicolaiskogheim Works for me, I updated the wiki.

Regarding the problem, I'm sorry to hear you are also suffering from freezes :( I will spend time tomorrow looking into this. Follow #318 for updates.
