### ISSUE TITLE
plug#load("some-plugin") fires BufReadPost event

### ISSUE THREAD

**Issue by khalidchawtany** [junegunn/vim-plug#327]
Calling load manually fires **BufReadPost** event. This alone may not be a problem. However, combined with the following it is. It may fire other events I may not be aware of, since sometimes the cursor moves to places that are not defined by the ```'"``` register.

I have the following in my **init.vim**
``` vim
"restore cursor position
au BufReadPost *
      \ if line("'\"") > 0 && line("'\"") <= line("$") |
      \     execute 'normal! g`"zvzz' |
      \ endif
```

Is this intentional? How can I prevent this?

minimal **init.vim** to reproduce
```vim
call plug#begin('~/.config/nvim/plugged')

  Plug 'kana/vim-textobj-user'   " Any plugin
  "Plug 'kana/vim-textobj-user', {'on': []} "The same as above

call plug#end()
au BufReadPost * echo "BufReadPost Fired"
```
Just execute the following:
```:call plug#load('vim-textobj-user')```

**Comment by starcraftman** [comment]
@khalidchawtany Hello. Had a look in the function, we fire the **BufRead** autocmd before returning from the load. I looked in the git history and that dates back to the addition of the plug#load function itself before I was here. You will have to wait for @junegunn to comment. I imagine he had a good reason, it must in some way relate to loading the plugin.

**Comment by khalidchawtany** [comment]
I took a look at the source code and saw the code too. If it is necessary and there is no way to remove it, cannot we at least set a variable before ```doautocmd``` and free the variable after it? This way we can check for this variable's existence and act accordingly.

**Comment by khalidchawtany** [comment]
I wonder if firing ```BufRead``` implicitly fires ```BufReadPost```?

**Comment by vheon** [comment]
I beleive it is needed for lazy loading plugin that have the `ftplugin` folder: since we "potentially" already loaded the buffer then we have to fire the event again for the `ftplugin` script to be sourced.

**Comment by khalidchawtany** [comment]
There must be workaround (At least what I suggested should work :point_up:  ). If you have a plugin that is lazy loaded with a ```<Plug>(Do_Something_With_Text_Under_Cursor)```, you find your cursor jumps miles away, after the operation is finished :(

**Comment by khalidchawtany** [comment]
I can use the following to work around this issue. However, it is a hack :(
```vim
    au BufReadPost *
          \ if exists('g:current_file_path') |
          \   if g:current_file_path != expand("%:p") |
          \     if line("'\"") > 0 && line("'\"") <= line("$") |
          \       execute 'normal! g`"zvzz' |
          \       let g:current_file_path=expand("%:p") |
          \     endif |
          \   endif |
          \ else |
          \     if line("'\"") > 0 && line("'\"") <= line("$") |
          \       execute 'normal! g`"zvzz' |
          \       let g:current_file_path=expand("%:p") |
          \     endif |
          \ endif

```

**Comment by junegunn** [comment]
@vheon is correct. File type detection by convention is performed on `BufRead` event. So if we don't fire it, filetype-specific plugin that we load with the function will not be activated immediately for the current buffer, until we "reopen" it with something like `:e` command.

If you see the output of `:autocmd BufRead`, you'll also notice that `BufRead` event is usually used for setting up the plugin state for the current buffer. e.g. fugitive, signify, etc. So I figured that it would be beneficial for most users that `plug#load` triggers the event, though the approach is a little crude and can have unwanted side effects like you experienced.

You can suppress the event with `:silent noautocmd call plug#load('vim-textobj-user')`.

**Comment by starcraftman** [comment]
@khalidchawtany Did you try what junegunn suggested? I'd like to know if we can close this, as he's explained everything.

And damn my noobishness for forgetting about noautocmd!

**Comment by khalidchawtany** [comment]
@starcraftman I have tried his solution it works. However, as @junegunn stated, it is needed by some plugins, usually to setup some variables.

I still use the variable solution to prevent restoring cursor position.
