### ISSUE TITLE
Neovim Remote Plugins

### ISSUE THREAD

**Issue by vito-c** [junegunn/vim-plug#330]
Does vim-plug work with neovims remote plugins? Does it call `UpdateRemotePlugins` after loading? I've had issues getting https://github.com/ensime/ensime-vim/ to work

**Comment by vheon** [comment]
I think this is a duplicate of #125

**Comment by starcraftman** [comment]
@vito-c Hi, see #125 for our discussion. Seems we left off waiting to see if the API would change again (i.e. not need UpdateRemotePlugins). So no support at present. I can imagine that might be inconvenient. Maybe time to revisit.

**Comment by starcraftman** [comment]
I'll close this for now, please follow the other thread for updates @vito-c

**Comment by junegunn** [comment]
@vheon @starcraftman Thanks guys.

@vito-c Note that the installation instruction of the plugin clearly states that a manual `UpdateRemotePlugins` is required.
