### ISSUE TITLE
[question] How to handle plugins with identical names

### ISSUE THREAD

**Issue by iwyg** [junegunn/vim-plug#331]
Is it possible to handle plugins that have identical names?

e.g. I want to install `honza/vim-snippets` and `iwyg/vim-snippets`

I've tried using the `dir` option

```vim
Plug 'honza/vim-snippets'
Plug 'iwyg/vim-snippets', { 'dir' : $HOME.'/.vim/plugged/mysnippets' }
```

Problem is, it still installs just the latter one.

**Comment by starcraftman** [comment]
@iwyg Hi. The problem in question is that the second plugin causes a name collision in the internal g:plugs dictionary used to store plugins. The dir flag only tells vim-plug where to download a plugin. Not sure if we want to add another flag to deal with such collisions, not common.

Regardless, I think you may want to reconsider this setup though, see `:h g:UltiSnipsSnippetsDir` to tell ultisnips where to find your own private snippets. These can then be stored in any github repo, or just inside your versioned or not `~/.vim`. Alternatively, you could simply rename your vim-snippets repo my-vim-snippets.

**Comment by starcraftman** [comment]
I think vundle made a 'name' entry for this, might see about adding it. Though not sure @junegunn would go for the PR.

**Comment by junegunn** [comment]
I'd rather not add the option. Adding it is trivial, but it's more important that we try to keep vim-plug as small as possible. No "because we can" features. I suggest that you simply rename the repo to `vim-snippets-ext`, `my-vim-snippets`, or something like that. But I'm interested in hearing about some real use cases. Are there any relevant plugins that share the same name and should be used at the same time?

**Comment by starcraftman** [comment]
@junegunn Figured as much. Guess that wraps this up. Hope the vacation was nice :).

**Comment by junegunn** [comment]
@starcraftman Thanks :sunglasses:

**Comment by iwyg** [comment]
Probably will do this, just wanted to know if there's an `alias` option I wasn't aware of. 
Thanks for the clarification an for this great plugin.

**Comment by rstacruz** [comment]
Hello from 2021! For the benefit of those that got here through a Google search, vim-plug now supports an `as` option for this use case.

```vim
Plug 'challenger-deep-theme/vim', {'as': 'challenger-deep-theme-vim'}
Plug 'embark-theme/vim', {'as': 'embark-theme-vim'}
```
