### ISSUE TITLE
UpdateRemotePlugins fails with an exception

### ISSUE THREAD

**Issue by PonderingGrower** [junegunn/vim-plug#332]
While I try to use the [deoplete](https://github.com/Shougo/deoplete.nvim) or [unite](https://github.com/Shougo/unite.vim) plugin and use `UpdateRemotePlugins` I get the following exception:

    Vim(if):Channel was closed by the client
    Error detected while processing function <SNR>18_UpdateRemotePlugins..<SNR>18_RegistrationCommands..remote#host#Require..<SNR>18_RequirePythonHost:
    line   21:
    E605: Exception not caught: Failed to load Python host. You can try to see what happened by starting Neovim with the environment variable $NVIM_PYTHON_LOG_FILE set to a file and opening the generated log file. Also, the host stderr will be
     available in Neovim log, so it may contain useful information. See also ~/.nvimlog.
    Error detected while processing function <SNR>18_UpdateRemotePlugins..<SNR>18_RegistrationCommands..remote#host#Require:
    line   10:
    E171: Missing :endif
    Error detected while processing function <SNR>18_UpdateRemotePlugins:
    line    5:
    E171: Missing :endif

Example `init.nvim`:

    call plug#begin('~/.config/nvim/bundle')
    Plug 'Shougo/deoplete.nvim'
    call plug#end()

or:

    call plug#begin('~/.config/nvim/bundle')
    Plug 'Shougo/unite.vim'
    call plug#end()

The `~/.nvimlog` file does not contain any related messages.

**Comment by starcraftman** [comment]
@PonderingGrower I believe you may have been a bit quick to blame us. Message says you are missing the required python host. Reading [deoplete](https://github.com/Shougo/deoplete.nvim#requirements), the plugin requires the python3 hosr. I imagine then if you start nvim and do `:echo has('python3')` it returns 0. So try doing (assuming debian based) `sudo apt-get install python3-pip && sudo pip3 install neovim`.

If that resolves it, please close. Just a warning, but remember that nvim is still alpha and so is that plugin, we aren't responsible for either.

**Comment by PonderingGrower** [comment]
I guess I should have mentioned that as well. No, I get `1` when I run `:echo has('python3')` with either of those minimal configs.

And I already did all the things you mentioned.

**Comment by PonderingGrower** [comment]
I did make an issue for `neovim` (https://github.com/neovim/neovim/issues/3749) but I closed it since I figured it's probably more related to this plugin. I might be wrong.

**Comment by PonderingGrower** [comment]
>To be clear, we don't maintain UpdateRemotePlugins either, that's a command exported by neovim.

Really? Then why when I run `nvim -u NONE` and try to use `UpdateRemotePlugins` I get:

    E492: Not an editor command: UpdateRemotePlugins

**Comment by starcraftman** [comment]
@PonderingGrower Well I just tried the deoplete plugin with nvim using vim-plug and it seems to register fine :/. Seems to be a local issue on your machine. I'd recommend purging the python3 pip package and reinstalling. Also, try clearing your nvim folder and starting fresh.

Regarding `UpdateRemotePlugins`, see `:h remote-plugin-manifest`. The Command in question is exported by vimscript sourced on init but provided by neovim.

**Comment by PonderingGrower** [comment]
I just did what you suggested.

 1. Removed `neovim` pip package,
 2. Installed it again.
 3. Created new empty `~/.config/nvim`
 4. Created this minimal `init.vim`
    call plug#begin('~/.config/nvim/bundle')
    "Plug 'Shougo/deoplete.nvim'
    Plug 'Shougo/unite.vim'
    call plug#end()
 5. Installed `unite` using `PlugInstall`.
 6. Resterted `neovim`
 7. Tried using `UpdateRemotePlugins`:

And I get:

    Vim(if):Channel was closed by the client Error detected while processing function <SNR>22_UpdateRemotePlugins..<SNR>22_RegistrationCommands..remote#host#Require..<SNR>22_RequirePythonHost:
    line   21:
    E605: Exception not caught: Failed to load Python host. You can try to see what happened by starting Neovim with the environment variable $NVIM_PYTHON_LOG_FILE set to a file and opening the generated log file. Also, the host stderr will be
     available in Neovim log, so it may contain useful information. See also ~/.nvimlog.
    Error detected while processing function <SNR>22_UpdateRemotePlugins..<SNR>22_RegistrationCommands..remote#host#Require:
    line   10:
    E171: Missing :endif
    Error detected while processing function <SNR>22_UpdateRemotePlugins:
    line    5:
    E171: Missing :endif

**Comment by PonderingGrower** [comment]
I think it might make more sense to reopen the `neovim` issue I created in the first place considering `UpdateRemotePlugins` really is a neovim command. The thing is it's loaded only if there's at least an empty `init.vim`. It's not available with `nvim -u NONE`.

**Comment by starcraftman** [comment]
@PonderingGrower This is the expected behavior from vim. The sourcing of the command is part of default initializations.

Excerpt of `man vim`:

```
-u {vimrc}  Use the commands in the file {vimrc} for initializations.  All the other initializations are
                   skipped.  Use this to edit a special kind of files.  It can also be used to  skip  all  ini‐
                   tializations  by  giving  the  name  "NONE".  See ":help initialization" within vim for more
                   details.
```

As to the continuing neovim plugin problem, I can't say I'd be much help. I'm not a major neovim user. I'd say reopen the neovim ticket or even make another, you might ping shougo since he''s done a lot of work on the python host. Sorry couldn't fix it.

**Comment by PonderingGrower** [comment]
It's cool, you helped me figure out that this is not vim-plug specific. I'm closing this. Cheers!

**Comment by d-gubert** [comment]
For anyone that came here looking for a solution to this problem, I ended up finding out that my `python-neovim` plugin, installed with `pip3`, was at version 0.2.0, which is incompatible with deoplete, as per [their documentation](https://github.com/Shougo/deoplete.nvim#requirements)
