### ISSUE TITLE
`rvm use system && brew reinstall vim` fails on El Capitan

### ISSUE THREAD

**Issue by JESii** [junegunn/vim-plug#333]
I followed your instructions on rebuilding vim from the system ruby when using rvm (did this successfully on 10.10) but failing in 10.11.1 with:
```
Last 15 lines from /Users/yc98js1/Library/Logs/Homebrew/vim/02.make:
^
/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:16:12: note: previous definition is here
@interface NSArray<__covariant ObjectType> : NSObject <NSCopying, NSMutableCopying, NSSecureCoding, NSFastEnumeration>
           ^
/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:26:32: error: method type specifier must start with '-' or '+'
@interface NSArray<ObjectType> (NSExtendedArray)
                               ^
/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:26:33: error: expected a type
@interface NSArray<ObjectType> (NSExtendedArray)
                                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
```

**Comment by junegunn** [comment]
Thanks for the heads up. Have you reported the issue to Homebrew?

**Comment by junegunn** [comment]
I'm running El Capitan, but have no problem re-installing vim. I don't have rvm installed though, but `rvm use system` means that we're using the system ruby, I don't think it should make a difference.

**Comment by JESii** [comment]
If you compile vim with the `+ruby` option and try to use the rvm ruby, eventually you'll wind up with SEGV errors; the `rvm use system` resolves that issue. With El Capitan and XCode 6.4, `homebrew install vim` fails with compile errors. Upgrading to XCode 7.2. beta-3 fixes that problem.

**Comment by junegunn** [comment]
Thanks for the summary. FYI I have XCode 7.1.1.
