### ISSUE TITLE
Custom keybindings

### ISSUE THREAD

**Issue by silenc3r** [junegunn/vim-plug#336]
I prefer ```PlugUpdate``` to create new buffer instead of a new window, so I changed ```g:plug_window``` to ```"enew"``` but now pressing ```q``` after update closes the vim instead of wiping the buffer. Is it possible to rebind ```q``` to ```:bw``` or ```:bd```? I want to rebind it _only_ for this buffer, not globally.

**Comment by junegunn** [comment]
You can bind keys with `autocmd FileType vim-plug`, but in this case `bd` seems to be a better default, so I updated the code. Thanks.
