### ISSUE TITLE
cfg: plug path for every plugin?

### ISSUE THREAD

**Issue by pale3** [junegunn/vim-plug#341]
What do you think to have cfg plug option. With this, user can specifiy location of his plugins config file,
by default cfg will read plugin-name.cfg inside git plugin dir. One can specify other location of cfg file on Plug line or using some global option. 

Why?
This can lead to cleaner vimrc file, and every plugins config can be stored in some other location.

**Comment by vheon** [comment]
What would be the content of said `plugin-name.cfg`?

**Comment by starcraftman** [comment]
@pale3 I'm not sure I understand. How does this clean up the vimrc if it is an option for the Plug flags? Or are you proposing a file that acts as a list of Plug invocations?

Can you make an example vimrc and cfg file in code blocks to illustrate what you are proposing. If it has to do with dependencies, junegunn's not interested.

**Comment by pale3** [comment]
> What would be the content of said plugin-name.cfg?

@vheon 
Content of `plugin-name.cfg` is all options which are related to specific plugin. Take a look at `YouCompleteMe.cfg` bellow.

@starcraftman 
e.g if in .vimrc there is no cfg option, or cfg argument is empty, then plug shouldn't do nothing here. 
`Plug 'Valloric/YouCompleteMe', { 'cfg': '' }`

If there is cfg option with argument which points to cfg file, then plug should source content of cfg argument when this plugin is loaded.
`Plug 'Valloric/YouCompleteMe', { 'cfg': '/path/to/plugin/config/YouCompleteMe.cfg' }`

if there is global cfg variable inside vimrc, like:
let g:plug_cfg = "~/.vim/configs"
then plug should assume that every plugin has it's specific config inside ~/.vim/configs.
In this example plugin-name.cfg is YouCompleteMe.cfg. Basically plug will load
`Plug 'Valloric/YouCompleteMe', { 'cfg': '/path/to/plugin/config/YouCompleteMe.cfg' }`

Content of `YouCompleteMe.cfg:`
```
let g:ycm_seed_identifiers_with_syntax = 1
let g:ycm_register_as_syntastic_checker = 1
let g:ycm_complete_in_comments = 1
let g:ycm_add_preview_to_completeopt = 1
let g:ycm_autoclose_preview_window_after_insertion = 1
...
```

This way in vimrc we can have separate options in way that vimrc could have defined options only for vim and cfg location can have options which are related only for loaded plugin.

I think that this can lead to managing plugin config more easily and efficiently. Every options which is related for e.g to YouCompleteMe can be stored in ~/.vim/config/YouCompleteMe.cfg and not in vimrc.

**Comment by starcraftman** [comment]
@pale3 You can already do something like this by just splitting your vimrc across files. Example below. I'm doubtful @junegunn would be interested in adding this, feel like it conflicts a bit with his minimal idea.

Example:

File: `~/.vimrc`
```viml
call plug#begin('~/.vim/plugged')j
for path in glob('~/.vim/config/*')
  source path
endfor
call plug#end()
```

File: `~/.vim/config/ycm.vim`
```viml
Plug 'Valloric/YouCompleteMe'
let g:ycm_seed_identifiers_with_syntax = 1
let g:ycm_register_as_syntastic_checker = 1
let g:ycm_complete_in_comments = 1
let g:ycm_add_preview_to_completeopt = 1
let g:ycm_autoclose_preview_window_after_insertion = 1
```

**Comment by junegunn** [comment]
I'm not convinced that we really need this. @starcraftman showed a nice and simple, and possibly more flexible way to organize the config without having to add an option to vim-plug.

Or you can simply add `source` command for each plugin like follows.

```vim
Plug 'Valloric/YouCompleteMe' | so /path/to/plugin/config/YouCompleteMe.cfg
```

(Note that plugins are not added to `&rtp` until `plug#end()`, so if you have to call autoload functions before it, you should hook them to `VimEnter` autocmd.)

We do provide the mechanism to execute some code when a plugin is loaded on-demand, but that's because there's no other way to achieve it.

```vim
" Code to execute when the plugin is loaded on demand
Plug 'Valloric/YouCompleteMe', { 'for': 'cpp' }
autocmd! User YouCompleteMe call youcompleteme#Enable()
```

NeoBundle as far as I know provides [such feature](https://github.com/Shougo/neobundle.vim/blob/master/doc/neobundle.txt#L1287-L1299), so if you absolutely need it, you might want to consider it instead. We'd like to keep vim-plug small.

**Comment by wsdjeg** [comment]
hi @junegunn any possible put plug.vim into autoload directory of this repo.
i am using vim-plug and neobundle together,
here is my split example vimrc 
```vim
if has('vim_starting')
    if &compatible
        set nocompatible
    endif
    set runtimepath+=~/.vim/bundle/neobundle.vim/
endif
call neobundle#begin(expand('~/.vim/bundle/'))
scriptencoding utf-8
NeoBundleFetch 'Shougo/neobundle.vim'
" some plugins need neobunle features
NeoBundle 'junegunn/vim-plug'
call neobundle#end()
call plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
"some other plugins
call plug#end()
```
i want do not need mkdir ~/.vim/autoload and put plug.vim into it

**Comment by junegunn** [comment]
@wsdjeg 

> i am using vim-plug and neobundle together,

Why? You shouldn't.

**Comment by wsdjeg** [comment]
What is conflict，now it works well,maybe just because  I have not meet it

**Comment by pale3** [comment]
Thx to all, I can use this solution. 

@junegunn, I am thinking, if I create patch for this path cfg thing, will you merge it? If not I will stick to solution provided in this thread.

**Comment by junegunn** [comment]
@pale3 Sorry, but no. We're saying no to this not because it's hard to implement the feature or we can't spare time for it, but because we think it's more important that we control the complexity of this ever-changing project and keep it simple and small as intended.
