### ISSUE TITLE
multiple commands

### ISSUE THREAD

**Issue by teamblubee** [junegunn/vim-plug#344]
Hi there I have a request that might be able to do now but I am doing it incorrectly.

```shell
call plug#begin('~/.config/nvim/plugins')

Plug 'Valloric/YouCompleteMe', { 'for': ['c', 'cpp'] }
autocmd! User YouCompleteMe call youcompleteme#Enable()
Plug 'rhysd/vim-clang-format', { 'for': ['c', 'cpp'] }
Plug 'scrooloose/nerdtree'
Plug 'drmikehenry/vim-headerguard', { 'for': ['c', 'cpp'] }

call plug#end()
```

that's my vim config for this plugin.
I would like to add a do command to vim-clang format such as
```shell
Plug 'Valloric/YouCompleteMe', { 'for': ['c', 'cpp'] } { 'do': './install.py --clang-completer' }
```

adding that on the same line as listed above I get an error on that line.

How can I correct this configuration?

**Comment by junegunn** [comment]
It's a vim dictionary. See `:help dict` for more info.

```vim
{ 'for': ['c', 'cpp'], 'do': './install.py --clang-completer' }
```
