### ISSUE TITLE
`:PlugInstall` URL checking is too greedy

### ISSUE THREAD

**Issue by monokrome** [junegunn/vim-plug#346]
When you have a bundle such as `Plug 'monokrome/vim-user-configuration'`, `:PlugInstall` will fail to update the repository of it has a writable github URL. It fails with an error like this:

```
x vim-user-configuration
    Invalid URI: github.com:monokrome/vim-user-configuration
    Expected:    https://git::@github.com/monokrome/vim-user-configuration.git
    PlugClean required.
```

I think that it'd be nice if these cases didn't break the install process. I'm not sure why the URL checking is useful, but if parsing the URLs seems like too much magic then this could also by solved required setting up a variable for packages that can skip this check:

```
let g:plug#ignore_bundle_urls=["monokrome/vim-user-configuration"]
```

**Comment by junegunn** [comment]
Hi, you can write full git urls like `Plug 'git@github.com:monokrome/vim-user-configuration'`, or temporarily set `g:plug_url_format`, which is what I'm doing [with my plugins](https://github.com/junegunn/dotfiles/blob/master/vimrc#L15-L44). URL checking is useful for catching configuration errors up-front and will not go away.

**Comment by monokrome** [comment]
Thanks, @junegunn. Just to clarify, I wasn't trying to suggest removing the feature.
