### ISSUE TITLE
Support functions (or booleans) for `on`.

### ISSUE THREAD

**Issue by gaffneyc** [junegunn/vim-plug#347]
There are a couple plugins in my config that don't work in all environments. It would be nice to be able to disable them using on and passing method or just a boolean.

For example:
```vim
Plug 'kassio/neoterm', { 'on': has('nvim') }
Plug 'zerowidth/vim-copy-as-rtf', { 'on': has('mac') }
```

**Comment by vheon** [comment]
I think this has been discussed before and the fact that you can do it like:

```viml
if has('nvim')
Plug 'kassio/neoterm'
endif
if has('mac')
Plug 'zerowidth/vim-copy-as-rtf', { 'on': has('mac') }
endif
```

discourage adding the feature. Moreover if in your config you have more than one plugin to activate only when a certain condition is matched then you have to repeat `'on': has(condition)` to each plugin.

At least that is what I think and what I remember but wait for @junegunn or @starcraftman ;)

**Comment by gaffneyc** [comment]
Did a search through the history and it does look like it's come up in #197 and #137 (possibly others). And yes, it seems the consensus has been that using `if mac("os")` is good enough.

It may be worth considering as it has come up a few times. It was the first thing I tried and was surprised it didn't work. It may be enough to support `0` and `1` in [the `has_key('on')` inside `plugin#end`](https://github.com/junegunn/vim-plug/blob/master/plug.vim#L183) for static loading of plugins.

**Comment by junegunn** [comment]
> It was the first thing I tried and I was surprised it didn't work.

Meaning that you misinterpreted `on` as an adjective when it's used as a preposition :) And the documentation does not mention anything about it taking boolean values.

> support 0 and 1

I don't think it's the right way though it may seem easy and tempting. It will make the option ambiguous and what if you want to superimpose the two different uses, say, you want to load the plugin when some command is invoked but only when the static condition is met.

Using native if-statement is the most flexible and the easiest way to conditionally define plugins. The only downside is that `PlugClean` may remove plugins that you use in different situations on the same machine, e.g. Terminal Vim vs. GVim, Neovim vs. Vim. Conditions like `has('mac')` should be no problem as you don't want to install the plugin on different platforms in the first place. Anyway, we still have a ways to handle such cases though it's a bit verbose, but the verbosity can be reduced with the use of external variables or helper functions/commands.

```vim
Plug 'foo/nvim-only', has('nvim') ? {} : {'on': []}
```

**Comment by starcraftman** [comment]
@gaffneyc Just an additional suggestion allow groups of settings for windows/linux etc, or just to prevent cluttering vimrc you could...

```viml
let conf_path = '~/.vim/cond'
for feature in ['win32', 'unix']
    if has(feature)
        source cond_path . '/' . cond . '.vim'
    endif                                                                                          
endfor
```

I'm not an OSX user, but imagine a simple `system('uname')` check can differentiate it from the rest of *NIX easily.  Have fun vimming.

**Comment by gaffneyc** [comment]
Thanks for the response, I appreciate it.

> Plug 'foo/nvim-only', has('nvim') ? {} : {'on': []}

Thanks, while it is verbose, it lets me keep it on one line which is helpful.

**Comment by junegunn** [comment]
```vim
let nvim_only = has('nvim') ? {} : {'on': []}

Plug 'foo/nvim-only1', nvim_only
Plug 'foo/nvim-only2', nvim_only
```

:)
