### ISSUE TITLE
--progress on Windows installer

### ISSUE THREAD

**Issue by junegunn** [junegunn/vim-plug#349]
@starcraftman 

Should we now enable `--progress` option on Windows?

https://github.com/junegunn/vim-plug/blob/060c0e6/plug.vim#L263

I disabled it since Ruby installer on Windows does not support [streaming of the output](https://github.com/junegunn/vim-plug/blob/060c0e6/plug.vim#L1560-L1567), but it was when we didn't have Python installer which seems to handle that.

**Comment by starcraftman** [comment]
@junegunn Not needed. On Windows we aren't intercepting/streaming the output as I can't use O_NONBLOCK. So we just don't call the func that gets the last line. We only ever read last line when done. See [here](https://github.com/junegunn/vim-plug/blob/master/plug.vim#L1246-L1248).

**Comment by junegunn** [comment]
Oh, okay, thanks!
