### ISSUE TITLE
plugin mapping overrides vimrc/init.vim

### ISSUE THREAD

**Issue by dschein** [junegunn/vim-plug#351]
I have a plugin that provides a default mapping.  Below my plug section, I map the same keys but they do not take effect.  Looking at a verbose log, I see the plugin load after my init, which explains the problem.  (If I just rerun the :map command it works fine.)  

Is there something I can do to force my mappings to run after all the plugins?

Thanks.

**Comment by junegunn** [comment]
Plugins are loaded **after** your vim configuration is processed. It's the expected behavior. See `:help startup` for the details.
You can either execute the code on `VimEnter` event

```vim
autocmd VimEnter * nnoremap ...
```

Or place the script as an external file in `after` directory.

**Comment by dschein** [comment]
Ah, thank you much, for the help and all the contributions to my productivity!
