### ISSUE TITLE
Why do we need to call `filetype off` in `plug#end()` ?

### ISSUE THREAD

**Issue by leomao** [junegunn/vim-plug#352]
When profiling the vim startup time, I noticed that `filetype.vim` was loaded multiple times.
And I found that if I remove `filetype off` in `plug.vim`, I can get some improvement on the startup time.
But I don't know if there is any problem if we don't call `filetype off`.

**Comment by junegunn** [comment]
See https://github.com/VundleVim/Vundle.vim/issues/176 for the details.
vim-plug also does `filetype plugin indent on` after `filetype off`, so the extra overhead you're having can be removed if you simply do not do it by yourself in advance and let vim-plug handle it, i.e. remove https://github.com/leomao/pika-vim/blob/master/.vimrc#L55-L57.

**Comment by leomao** [comment]
Thanks for the explanation!

But I think the extra overhead is not cause by `filetype indent plugin on` in my vimrc.
I have tried to remove them but vim still load `filetype.vim` multiple times.
It seems that the problems is caused by `filetype off`.
Calling `filetype indent plugin on` multiple times doesn't increase the startup time.
Now I understand that this is for the compatibility of older vim so it can't be removed.

Thanks again.

**Comment by junegunn** [comment]
> It seems that the problems is caused by filetype off.

The problem is you turned it on before `plug#end()` (on / off / on) and that's why I suggested that you shouldn't do so.

> I have tried to remove them but vim still load filetype.vim multiple times

No it doesn't. This is my `--startuptime` log: https://gist.github.com/junegunn/da8aa58ef7360fff2aae

**Comment by leomao** [comment]
Yes I know that the problem is (on / off / on).
Finally, I found that there is a file containing `filetype on` in the system path.
Thanks!

**Comment by junegunn** [comment]
Yeah, I guessed so.

http://superuser.com/questions/140913/how-to-start-vim-without-executing-etc-vimrc
