### ISSUE TITLE
No parallel installation on Windows

### ISSUE THREAD

**Issue by KabbAmine** [junegunn/vim-plug#363]
The parallel installation on Gvim 7.4 (`+python`, `+python3`) in Windows 7 is not working.

No errors or anything, it just shows me that no plugin was found.

e.g `PlugInstall`
![2015-12-17_17-05-26](https://cloud.githubusercontent.com/assets/5658084/11871401/6ac8903e-a4e0-11e5-8872-0107ec13e0a6.png)
`PlugInstall --verbose`
![2015-12-17_17-07-07](https://cloud.githubusercontent.com/assets/5658084/11871438/9e5fdb46-a4e0-11e5-9360-ba481856b46a.png)

Meanwhile, I'm using the vimscript installer (1 thread) and its working as expected.

As requested in #353:
- `echo &shell` : `C:\Windows\system32\cmd.exe`
- `python import sys; print sys.version_info[0:3]` : Error because no python2 on my system.
- `python3 import sys; print(sys.version_info[0:3])` : `(3, 4, 3)` (Should I upgrade to 3.5.11?)
- `!ls path-to-my-plugs` : Shows my plugins installed with normal viml installer.

I'm a unix user most of the time so it would be great to have same installation speed on my windows machine.

**Comment by junegunn** [comment]
Can you post the output of `:echo g:plugs`?

**Comment by KabbAmine** [comment]
> No plugin to install message must be caused by unsupported --verbose flag, which was recognized as the name of a plugin, which of course does not exist.

:stuck_out_tongue: My bad.

The plugins directory is recognized without problem (`g:plugs_home`), the installation with 1 thread goes normally. The only problem is with the python or ruby parallel installation, is there any way to specify which one to use?

**Comment by junegunn** [comment]
Do you have the latest version of vim-plug? We recently decided to disable Ruby installer on Windows GVim, leaving only Python installer.

**Comment by KabbAmine** [comment]
Yes, last version, that means that the python implementation is the culprit. I don't know how to start debugging that.

**Comment by starcraftman** [comment]
@KabbAmine I usually resort to logging to see where the interpreter is failing. When nothings printed, usually means some import or syntax error. Though that is pecular, since we do test it on UNIX. I'll give it a look with my VM as time permits.

**Comment by starcraftman** [comment]
@KabbAmine I've done a quick test with the following two configurations on Windows 10 VM, both seem to work.
- [gvim] + [py32]
- [gvim35] + [py35]

It seems that the code is fine, unless there is a particular bug with your configuration. Can you link me your build of vim? I will try your setup in my VM. In the mean time, you may wish to try one of the ones that worked for me.

[gvim]: http://www.vim.org/download.php#pc
[gvim35]: https://tuxproject.de/projects/vim/
[py32]: https://www.python.org/downloads/release/python-326/
[py35]: https://www.python.org/downloads/release/python-351/

**Comment by KabbAmine** [comment]
@starcraftman Thanks for your interest.
About the vim build, I don't remember well but I'm pretty sure its an old one from tuxprojects, I'll check when I will be on my windows machine.

Also, I will try with a simple vimrc to see if its related to my vim config or not.

**Comment by KabbAmine** [comment]
Ok.

First of all it was a python issue specific to my system, I had a completely messed up python installation on my windows (Done via chocolatey). I've reinstalled and configured both python versions and they are now working correctly.

I was using a vim version compiled by haroogan (The bitbucket repository doesn't exist anymore) which was supporting not so old versions of lua, ruby, python2/3 & perl. Now I'm using the one from tuxproject (thanks to @starcraftman for the link) and after adding the appropriate DLLs everything seems fine.

The parallel installation using python is working as expected :smile: 
The issue can be closed.

**Comment by starcraftman** [comment]
@KabbAmine Happy that is all settled. One does need to be careful with python installs, try using virtualenvs when possible to isolate when testing/modifying things.

I guess I'll just close this ticket then.
