### ISSUE TITLE
How to control the load sequence of plugins.

### ISSUE THREAD

**Issue by d0u9** [junegunn/vim-plug#365]
I want some plugins to be loaded before others, how to control such a load sequence? For example, `vim-devicons` needs `NERDTree` is loaded before.

**Comment by junegunn** [comment]
Plugins are added to `&runtimepath` in the order they are defined with `Plug` commands. Just make sure `Plug` command for nerdtree comes before the other.

**Comment by d0u9** [comment]
Well, I get it! Thank you!
