### ISSUE TITLE
Have vim-plug manage itself (similar to vundle)

### ISSUE THREAD

**Issue by hallzy** [junegunn/vim-plug#367]
I think it would be nice to have the repo restructured so that it is easy to use vim-plug to manage vim-plug. It would be useful for pulling updates that are made to this repo, and it is the same thing that vundle recommends doing.

The changes would not be complex, in fact, there is already a fork of this repo that has this set up: see this [fork](https://github.com/frtmelody/vim-plug)

**Comment by hallzy** [comment]
Sorry, I just saw #364 saying that you have decided not to do this.

**Comment by starcraftman** [comment]
@hallzy Its okay, you probably won't be the last to suggest it. :)
