### ISSUE TITLE
Windows neovim-qt and plug not working

### ISSUE THREAD

**Issue by jrock2004** [junegunn/vim-plug#368]
This may not be a vim-plug issue but wanted to validate The appropriate location to where plug.vim needs to be put for it to work with nvim-qt

Locations tried:
- C:\Users\costanzoj\.config\nvim\plugged
- C:\Users\costanzoj\AppData\Local\nvim\autoload

Not matter which I choose it does not work

**Comment by starcraftman** [comment]
@jrock2004 plug.vim goes in the default autoload directory. On Windows, I'm fairly certain it should be your second choice. [Says so on the wiki](https://github.com/neovim/neovim/wiki/Installing-Neovim#vimrc-file-in-windows).

You can check where it is looking for autoload dirs by examining he runtimepath manually. Like `echo &rtp`. First dir usually main config location. Then under one of those paths should be `autoload/plug.vim`.

**Comment by starcraftman** [comment]
@jrock2004 Did you get this working? It has been over a week. I will probably close this if you don't respond again.

**Comment by jrock2004** [comment]
Yep we are good "C:\Users\costanzoj\AppData\Local\nvim" this worked

**Comment by aemonge** [comment]
Please update the windows install instructions. This post is really helpful but also extremely hard to find.

**Comment by aemonge** [comment]
Also, try setting it the following way:

```
 call plug#begin('$LOCALAPPDATA/nvim')
```

**Comment by junegunn** [comment]
I believe our installation instruction already points to the path.
https://github.com/junegunn/vim-plug#neovim

>  call plug#begin('$LOCALAPPDATA/nvim')

Not sure if it's a good choice. Prepend `plugged` or something to make sure that it doesn't clash with the default Vim directories.
