### ISSUE TITLE
Disable Plugin Option

### ISSUE THREAD

**Issue by zQueal** [junegunn/vim-plug#369]
Would it be feasible to enable options to temporarily disable a plugin without having it marked for cleaning?

I was running into a bunch of issues with my installed plugins and instead of being able to temporarily disable them from loading, I had to remove them, `PlugClean` then add them one by one and `PlugInstall` until I found the conflict. It was tedious and unnecessary. I'm sure there was probably a much smarter way to accomplish it, but the idea is useful just the same.

It would be amazing to be able to do the following;

    call plug#begin('~/.vim/plugged')
        Plug 'rking/ag.vim', { "disabled": true }
        Plug 'sjl/gundo.vim'
        Plug 'scrooloose/nerdtree'
        Plug 'mattn/webapi-vim' | Plug 'mattn/gist-vim'
        Plug 'vim-php/vim-composer'
        Plug 'tomtom/checksyntax_vim'
        Plug 'roman/golden-ratio'
        Plug 'vim-scripts/buffet.vim'
        Plug 'itchyny/lightline.vim'
    call plug#end()

Then be able to have that specific plug _not_ load at all, but be immune to `PlugClean`.

**Comment by vheon** [comment]
The think not clear is why you would do a `PlugClean` :confused: Comment the plugin, restart vim and see if the conflict is still there. What am I missing?

**Comment by zQueal** [comment]
Well, I didn't know if it would make a difference, for one. I wasn't sure if any residual files would be causing an error, so I opted to clean. Like I said, I'm sure there's a much smarter way to do it than I did. But the fact of the matter remains, temporarily disabling plugins is a pretty good idea. 

I get what you're saying about commenting them out--but if that's your approach to it, then why have a plugin manager at all? Why not just do everything manually?

**Comment by vheon** [comment]
> I get what you're saying about commenting them out--but if that's your approach to it, then why have a plugin manager at all? Why not just do everything manually?

Because doing it manually the "vim" way would mean that delete plugins would be a pain. So, yes I use a plugin manager to "manage" the `runtimepath` (and to ease the update step). If you look at other plugin manager which have the feature you suggest like [tpope/vim-pathogen](/tpope/vim-pathogen) all they do for disabled plugins is to not add their path to `runtimepath` which in the "vim-plug world" is identical to comment out the plugin you want to disable.

**Comment by junegunn** [comment]
> I wasn't sure if any residual files would be causing an error, so I opted to clean

They don't. And I personally don't see a big difference between prepending `"` to the `Plug` line and appending option for disabling it, but Anyway you can make vim-plug not load the plugin by (ab)using `on` option.

```vim
Plug 'foo/bar', { 'on': [] }
```
