### ISSUE TITLE
Allow Shallow Cloning of Plugins

### ISSUE THREAD

**Issue by jalcine** [junegunn/vim-plug#370]
This might be a very particular case to me, but I'll shoot my shot anyway.

The plugin [`cmake.vim`][1] has a few submodules that it relies on for testing. I'm confident that no one runs these tests for production use. However, whenever I install or update my plugins, this plugin is cloned _deeply_. I'm proposing a _thin clone_ option that allows one to only clone the top-level Git tree and nothing more.

[1]: https://github.com/jalcine/cmake.vim

**Comment by junegunn** [comment]
Hi, let's not use the term "shallow clone" here as it can be confusing. "Recursive cloning" seems like a more accurate term. Anyway, this doesn't look like a common requirement among the users of vim-plug so I do not feel like adding an option just for the plugin. And I believe other plugin managers also do recursive cloning. Do you have to use submodules in your test? How about cloning them in the Rakefile?

**Comment by starcraftman** [comment]
@jalcine It seems convention at this point that vim plugin submodules are runtime not testing dependencies. Given that, making the cloning of them optional would just invite problems as users would inevitably disable it on a plugin needing it. In my opinion that makes this won't fix.

I'd say put it in the Rake or even just use some shell script wrapper to launch your tests doing env setup/teardown as required. Sometimes a little bash goes a long way :).

**Comment by jalcine** [comment]
Thanks @junegunn for that clarification. That's a valid stance (I can just update my plugin to do so!).

@starcraftman That sounds like a better solution.

I'll close this and work on that. Thanks y'all.
