### ISSUE TITLE
PlugInstall frequently hangs and waits for timeout before finishing

### ISSUE THREAD

**Issue by BobWhitelock** [junegunn/vim-plug#373]
Hi, I have been having an issue where installing new plugins with `PlugInstall` often causes Vim (and enclosing Tmux session) to hang for about 60 seconds, before continuing and completing successfully. This doesn't always happen but does a lot more often than not.

For instance just now after adding a plugin it got stuck at this:

`vim-operator-user: Resolving deltas:  97% (40/41)`

and then eventually 60+ seconds later it completes successfully:

`Updated. Elapsed time: 66.225249 sec.`.

I'm using terminal Vim 7.4 on Debian with vim-plug 0.8.0, although this occurred with previous versions too. Since I can't find the exact same issue mentioned anywhere I'm assuming this is something peculiar to my setup; I can provide any further info which might help. Thanks!

**Comment by junegunn** [comment]
- How long does it take when you manually clone the repo outside of vim?
- Can you check the status of the git process when that happens (with `ps` command) and see if there's anything strange going on?
- Does it still happen when you use single-threaded vimscript installer? `:PlugInstall 1`

**Comment by BobWhitelock** [comment]
>How long does it take when you manually clone the repo outside of vim?

I've just tried running `time git clone <repo url>` several times for different repos, and it's always very quick:

```
0.05s user 0.01s system 4% cpu 1.482 total
0.04s user 0.00s system 2% cpu 1.507 total
0.04s user 0.02s system 4% cpu 1.428 total
0.02s user 0.02s system 2% cpu 1.450 total
```

>Can you check the status of the git process when that happens (with ps command) and see if there's anything strange going on?

I'm guessing you mean something like this, which I ran at the same time as one of the above was running:

```
$ ps aux | grep git
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
bob      18623  0.0  0.0  16236  1700 pts/14   S    23:14   0:00 git-credential-cache--daemon /home/bob/.git-credential-cache/socket
bob      24186  0.0  0.0  18840  3840 pts/8    S+   23:20   0:00 git clone https://github.com/tpope/vim-eunuch
bob      24187  1.0  0.1 158320 12192 pts/8    S+   23:20   0:00 git-remote-https origin https://github.com/tpope/vim-eunuch
bob      24192  0.0  0.0  27004  3316 pts/8    Sl+  23:20   0:00 git fetch-pack --stateless-rpc --stdin --lock-pack --thin --check-self-contained-and-connected --cloning https://github.com/tpope/vim-eunuch/
bob      24194  0.0  0.0  19452  3396 pts/8    S+   23:20   0:00 git index-pack --stdin -v --fix-thin --keep=fetch-pack 24192 on bob-alces --check-self-contained-and-connected --pack_header=2,212
bob      24196  0.0  0.0  12724  2172 pts/15   S+   23:20   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn git
```

I can't see anything unusual, but then I don't really know what I'm looking for.

> Does it still happen when you use single-threaded vimscript installer? :PlugInstall 1

I haven't been able to reproduce it using this just now with several tries, however it also seems to be happening less often in general today. Out of 20+ times of removing and re-installing plugins just now to test, this has only occurred 3 times. It seems to come and go though; a couple of weeks ago this was happening almost every time I ran `PlugInstall`.

I'm not sure why this would be then, possibly related to having other things running or the network being bad? What situations and how often should the timeout occur normally?

**Comment by junegunn** [comment]
I've never experienced something like that. So I have no idea. Maybe it could be a network issue, or are you behind some kind of a firewall? vim-plug by default clones/updates plugins with 16 concurrent processes. You might want to try with smaller number (`:PlugUpdate 4` or `let g:plug_threads =4`).

> What situations and how often should the timeout occur normally?

Let's clarify the situation here. Did vim-plug terminate the running processes with `Timeout. Will retry in 3 seconds ...` message, or it's just that you observed that they took long to finish?

**Comment by starcraftman** [comment]
I remember a while ago I experienced something similar (with python installer), but I believe it was around the time github was being DDOSed regularly so I figured it was just a hiccup on the remote. One of the threads would timeout then retry and succeed. Went away after a short while.

If it is intermittent network issues, not sure much we can do. You could simply try lowering your g:plug_timeout value to say 20 or 30 at least reduce the wait. Long as you aren't regularly building YCM.

**Comment by easysid** [comment]
I am also facing similar problem with respect to [jedi-vim](https://github.com/davidhalter/jedi-vim). 
I have 
```
   Plug 'davidhalter/jedi-vim'
```
but PlugInstall just hangs while installing it. I can git clone the repo manually just fine, so can Vundle.

**Comment by junegunn** [comment]
@easysid Thanks.

- This is the full command vim-plug uses to clone the repo. Try it and see if it works as expected.
```sh
git clone --depth 1 --no-single-branch --progress --recursive https://github.com/davidhalter/jedi-vim.git -b master jedi-vim
```
- vim-plug ships with three (or four) versions of installer. We need to know which installer is activated in your case. If you're using Vim, not Neovim, and the parallel installer, either ruby or python, is enabled, the process will time out if there was no update for the last 60 seconds. It is not supposed to just hang.
- Please check if the git process is still alive when you observe the hang.

**Comment by junegunn** [comment]
@easysid BTW, I have no problem installing it with vim-plug, though it takes longer than the others (in my case 16 seconds) due to recursive cloning of submodules.

**Comment by easysid** [comment]
@junegunn 
Thanks. Yes, my connection is slow. The recursive cloning of submodules is what was indeed causing the delay. 

Is it necessary though, to clone the submodules as well, and not just the top repo? I have the jedi library already installed systemwide.

**Comment by junegunn** [comment]
@easysid It depends. It seems optional for jedi-vim, but some plugins like YCM require that. So vim-plug simply does recursive cloning by default. Vundle as far as I know does the same. I'm not considering adding an option for switching it off per plugin as there are very few Vim plugins that come with submodules.
