### ISSUE TITLE
[minor] Plug fails to update plugin installed as git submodule

### ISSUE THREAD

**Issue by Xerkus** [junegunn/vim-plug#374]
In my case plugin in question is vim-plug itself but issue is more generic.
When i run `PlugUpdate` I get `Invalid URI` error:
```
x vim-plug:
    Invalid URI: https://github.com/junegunn/vim-plug
    Expected:    https://github.com/junegunn/vim-plug.git
    PlugClean required.
```

Submodule is defined using expected path but then git strips `.git`:
```
[submodule "bundle/vim-plug"]
	path = bundle/vim-plug
	url = https://github.com/junegunn/vim-plug.git
	branch = master

$ git remote -v
origin	https://github.com/junegunn/vim-plug (fetch)
origin	https://github.com/junegunn/vim-plug (push)
```
I believe vim-plug should recognize and accept such uri.

I install vim-plug initially as submodule and then it manages itself as git installed plugin. I see potential for improvement: `PlugUpgrade` can check if plug.vim is in local repo with origin pointing to `https://github.com/junegunn/vim-plug` and update it as git repo instead of as standalone file

**Comment by junegunn** [comment]
We officially do not support updating vim-plug via `:PlugUpdate`. This was discussed many times before and that's the conclusion. There are workarounds, yes, but I suggest that you don't declare vim-plug with `Plug` command. After all vim-plug is not Vundle.

Thanks for your suggestion on `:PlugUpgrade`, but as we officially instruct the users to download the standalone file into `autoload` directory which is probably not under version control, I think it's okay that the command only handles *the configuration*. Users who decided to take different path will easily figure out their own way of updating vim-plug without using `:PlugUpgrade`. Should be a one-liner script. But anyway, I'll take note of your suggestion and see if we can improve the usability somehow.
