### ISSUE TITLE
Helptags not getting generated?

### ISSUE THREAD

**Issue by telemenar** [junegunn/vim-plug#375]
I'm on a Mac using neovim 0.1.1 and help tags are not getting generated. It is possible that this is a bug in the helptags command in neovim rather than in vim-plug. I started trying to debug it and when I remove the ``silent!`` from the front of ``execute helptags`` in ``plug#helptags()`` I get errors about the paths not being directories. They are clearly directories however. I discovered I can work around this is I change:
```
let docd = join([spec.dir, 'doc'], '/')
```
to
```
let docd = join([spec.dir, 'doc/'], '/')
```

Then I get helptags

**Comment by starcraftman** [comment]
@telemenar Hello. I tested on Linux the latest master commit for neovim and I don't see any problem with tag generation. I also did a build of tag `v0.1.1` with the same results. Don't have a Mac so I can't test it specifically.

Does tag generation work if you change the docd line to this? `let docd = spec.dir . 'doc'`

I did notice one peculiarity, the spec.dir has a trailing slash, and we are joining it with another slash, so the docd path always becomes `plugin_root//doc`. Extra slashes are usually ignored though on the shell, perhaps `isdirectory` func has become stricter on neovim than vim?

Perhaps @vheon or @junegunn can do a mac test to confirm it is working when they get a moment?

**Comment by junegunn** [comment]
@starcraftman @telemenar 
Not reproducible on OSX El Capitan + neovim 0.1.1. Tags are created just fine and `isdirectory('/usr/local//bin///')` returns 1 as expected. No problem with `:helptags /Users/jg/.vim/plugged/vader.vim/doc` or with `:helptags /Users/jg/.vim/plugged/vader.vim//doc`, tags file is created with no error.

**Comment by junegunn** [comment]
Maybe there's some setting that affects the behavior? Consider trying it again with nothing but plug block on your nvimrc.

**Comment by telemenar** [comment]
Huh, it does work when I use a bare init.vim file. I'll try to figure that out at some point.

**Comment by Xunius** [comment]
Hi all, I'm on linux and I also noticed that all my plugins installed via `vim-plug` have no helptags. I only get to see them after adding `call plug#helptags()` after `call plug#end()` in my `init.vim`.

Some specs:
```
NVIM v0.6.1
Build type: Release
LuaJIT 2.0.5
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
