### ISSUE TITLE
:PlugInstall command in windows gvim makes vim crash and shutdown

### ISSUE THREAD

**Issue by kuc2477** [junegunn/vim-plug#377]
I've been using vim-plug happily on Windows8 but it suddenly crashed without any error messages when I tried to install additional plugins.. Other commands work without any problems but the `:PlugInstall` command is keep crashing gvim.

**Comment by junegunn** [comment]
This is probably the result of our recent decision to enable parallel installer on Windows by default. And it looks like the python interface of your GVim is broken somehow. Please post the output of the following commands:

- `:echo has('python')`
- `:echo has('python3')`
- `:silent python import platform; print(platform.python_version())`

And can you try reinstalling GVim after installing Python on your system and see if it helps?

Meanwhile you can disable parallel installer either by
- specifying the number of threads, e.g. `:PlugInstall 1`
- or setting `let g:plug_threads = 1` in your configuration file

Ping: @starcraftman @mattn

**Comment by mattn** [comment]
@kuc2477 what is your python & vim setup?

* which do you use vim.exe or gvim.exe?
* where did you get the binary of vim?
* where did you get the binary of python?
* could you please show me your `%PATH%`?

**Comment by kuc2477** [comment]
@junegunn 
- `:echo has('python')` -> 1
- `:echo has('python3')` -> 0
- `silent python import platform; print(platform.python_version())` -> **CRASH**

@mattn 
- gvim.exe
- From vim official site
- From python official site
- %PATH%: see below

C:\Program Files(x86)\PHP\;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Wi
ndows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQLServer\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\ProgramFiles\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files(x86)\Git\cmd;C:\Program Files (x86)\Notepad++\;C:\Program Files (x86)\MySQL\MySQL Fabric1.5.4

* It's weird that `echo %PATH%` prints no python paths although I can see it's configured properly in system settings

C:\Program Files (x86)\PHP\;C:\ProgramData\Oracle\Java\javapath;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Notepad++\;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5.4 & MySQL Utilities 1.5.4 1.5\;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5.4 & MySQL Utilities 1.5.4 1.5\Doctrine extensions for PHP\;C:\Program Files (x86)\gettext-iconv;C:\Program Files (x86)\Vim\vim74;C:\Users\geo\AppData\Local\Programs\Python\Python35;C:\Users\geo\AppData\Local\Programs\Python\Python35\Scripts;C:\Program Files (x86)\Atlassian\SourceTree;%NVM_HOME%;%NVM_SYMLINK%

*  I was first using Python2.7 then I replaced with Python3.5.1 and it started to crash from then. It seems like gvim is still looking at uninstalled Python2.

**Comment by mattn** [comment]
Thanks. You python setup seems broken. It occur on python prompt also? 
```
import platform; print(platform.python_version())
```

**Comment by kuc2477** [comment]
No, that expression works in python prompt and prints `3.5.1`

**Comment by junegunn** [comment]
@kuc2477 Hmm, I think you'll have to uninstall the current vim and reinstall vim with python3 on %PATH%.

**Comment by starcraftman** [comment]
@kuc2477 Hello. Been quiet as @mattn asked all the questions I would have.

A few comments:

1. Are you certain the GVim architecture matches the python 3 architecture? (i.e. both 64/32 bit). I have from time to time misclicked, that would definitely cause immediate crash.
1. Please try disabling all plugins, then adding back just this one: `Plug 'junegunn/seoul256.vim'` to test. I want to rule out a plugin using python forcing the 2 interface. Examples would include YCM, ultisnips, Gundo/Mundo and quite a few more. Sadly even though vim-plug is prepared for 3, most of the community is still stuck in 2.

**Comment by kuc2477** [comment]
@starcraftman 1. yes 2. Yeah, I switched back from 3 to 2

It seems the problem was with the python version change that I made. It works after I reinstalled python2.7 and gvim.

- Installed gvim with python2.7 -> Used `vim-plug` happily
- Uninstalled python2.7 and replaced it with python 3.5.1 -> GVim broke on `PlugInstall` command
- Reinstalled python2.7 and GVim in order -> Now it works

**Comment by starcraftman** [comment]
@kuc2477 Well ok, it is weird because we definitely do support `+python3`. If you don't want to pursue it further that is ok. If I get a moment, I'll try one of my VMs with python3 just to be sure nothing has regressed.

**Comment by NickWer** [comment]
Hi all. 

I just ran into the same issue on gvim, but not vim. (Sadly, colorschemes don't seem to work with vim on windows, so it's basically unusable. Am I missing something here?). Using `:PlugInstall 1` works, but it doesn't resolve the fact that other python dependent plugins were failing. Anyways, I had instaled python 2.7.11 and 3.5.1 originally (the two latest binaries from python.org), producing the following output:

`:echo has('python')` = 1
`:echo has('python3')` = 0
`:silent python import platform; print(platform.python_version())` = 1

After reading various stackoverflow threads, I patched together that I needed the following python 2.7.9 and 3.2.5

After removing the existing versions and installing these ones, all my python-dependent plugins (this one and others) now work as expected, and I receive the following output


`:echo has('python')` = 1
`:echo has('python3')` = 1
`:silent python import platform; print(platform.python_version())` = nothing. Removing `silent` makes it return 2.7.9

Thanks for the information here - it proved to be pretty useful in debugging the issue, and hopefully what I've posted here will prove helpful to someone else

**Comment by starcraftman** [comment]
@NickWer Glad it is fixed, not sure what the SO information was that lead you to downgrade. It should work with the latest without issue. Though the last 2.7.11 release has a rather pernicious [bug](https://github.com/junegunn/vim-plug/wiki/faq#python-2711-windows-registry-bug). I believe it affects the result of the platform line we use :/.

As to terminal vim on Windows, most users wanting that favor a unixy shell in my experience. For instance, msys2, cygwin, babun, etc... They emulate a unix shell including colors.

**Comment by NickWer** [comment]
Right. I figured the information may have been a bit outdated, but I don't really use python much, so I don't particularly care what version I have, as long as it meets dependencies. 


I'll try it out on cygwin and see how it goes, thanks.

**Comment by buchmoyerm** [comment]
I had this same issue with python 2.7.11 and I was able to solve it with http://stackoverflow.com/a/35620795

**Comment by junegunn** [comment]
@buchmoyerm Thanks for sharing.
