### ISSUE TITLE
Terrible magic of plug#end()

### ISSUE THREAD

**Issue by chemzqm** [junegunn/vim-plug#379]
According to the documentation, plug#end() should only `add the plugins to &runtimepath`, but it also includes commands `filetype plugin indent on` and `syntax enable`.
It might be sensible to someone else, since it help them to simplify their `.vimrc`, but when it comes to debugging, the only way to disable them is by changing the code inside vim-plug.

I got this because I found comment the line `filetype plugin indent on` in my own `.vimrc` refuse to work after I use vim-plug, that confuse me a lot.

Please, at least add documentation for that.

**Comment by junegunn** [comment]
I'm not sure what really is the problem. Having extra `filetype plugin indent on` in your .vimrc is unnecessary but it does not break anything and it barely affects the startup time.

> the only way to disable them is by changing the code inside vim-plug

```vim
...
call plug#end()
filetype off
syntax off
```

I have mixed feelings about your suggestion on the documentation; make it as complete as possible vs. do not waste people's time with implementation details they don't need to care. I'll just update the sentence to describe what it does in an abstract way.

**Comment by himdel** [comment]
@junegunn could we possibly reopen?

I do have an actual issue.. I don't mind it setting syntax on or even filetype on, but it actually seems to enable some kind of autoindent behaviour for me which is definitely not what I want.. (and I don't know how to undo that)

Calling `plug#end` seem to enable `indentexpr`, `indentkeys`, `suffixesadd`, `include`, `includeexpr`, `formatoptions`, `comments`, `commentstring` and `balloonexpr`. Are you telling me I really need to unset all those if I want to use plug?

**Comment by vheon** [comment]
`filetype indent off` right after `call plug#end()` #156

**Comment by junegunn** [comment]
@himdel Yeah, `filetype indent off` will do. See `:help :filetype-overview`.

**Comment by laktak** [comment]
@junegunn could you please add this to the README? Took me ages to find that your plugin was doing this.

**Comment by romainl** [comment]
@junegunn, if that command is not necessary for your script to work and harms your users you should remove it.

**Comment by accolade** [comment]
Links to the offending line(s?°):
Permalink: https://github.com/junegunn/vim-plug/blob/a4aac4cf567bb060356694991064f687f8758a81/plug.vim#L276
Current revision: https://github.com/junegunn/vim-plug/blob/master/plug.vim#L276
° (Dunno if the `syntax enable` 3 lines below  could also cause trouble for some users.)
___

This issue is pointed out in a popular thread on the vi StackExchange since recently (by @laktak): http://vi.stackexchange.com/questions/388/what-is-the-difference-between-the-vim-plugin-managers?noredirect=1&lq=1#comment18609_397
___

@junegunn, you may also want to tack the

> …  and initialize plugin system

`plug#end()` description supplement, from your above Jan 14 issue-closing commit https://github.com/junegunn/vim-plug/commit/03504f26b1f5f7d17e21fbf4bee27a45172d8348, onto the respective comment a few lines below, in the vim-plug vimrc section  code example: https://github.com/junegunn/vim-plug/commit/03504f26b1f5f7d17e21fbf4bee27a45172d8348?diff=unified#diff-04c6e90faac2675aa89e2176d2eec7d8R92

**Comment by junegunn** [comment]
It's a design choice I made from the beginning (*"Should be easier to setup, require less boilerplate code"*) when I started vim-plug, and changing it now will break many users' configurations. I can understand that some don't like it, but there are also others, myself included, who like the idea that vim-plug does the things that are required to enable most plugins. vim-plug is not just a runtimepath manager, but a plugin manager that is responsible for setting up the environment where plugins work out of the box without extra configuration, so I don't think it's an abomination that it enables some settings most plugins require. I can add more description to the README page though.

As pointed out in the above, you can easily undo the things `plug#end()` does with just a single line in your configuration. And vim-plug is an open-source after all, you can always change it to your liking.

Also related: #83, #156

**Comment by romainl** [comment]
@junegunn that was a very reasonable way to handle it.

**Comment by EvanCarroll** [comment]
see: #1083 Stop Turning `syntax on`

**Comment by mangelozzi** [comment]
> It's a design choice I made from the beginning (_"Should be easier to setup, require less boilerplate code"_) when I started vim-plug, and changing it now will break many users' configurations. I can understand that some don't like it, but there are also others, myself included, who like the idea that vim-plug does the things that are required to enable most plugins. vim-plug is not just a runtimepath manager, but a plugin manager that is responsible for setting up the environment where plugins work out of the box without extra configuration, so I don't think it's an abomination that it enables some settings most plugins require. I can add more description to the README page though.
> 
> As pointed out in the above, you can easily undo the things `plug#end()` does with just a single line in your configuration. And vim-plug is an open-source project after all, you can always change it to your liking.
> 
> Also related: #83, #156

Which plugins don't work with `auto indent on`? Surely those plugins document their requirements, or set the setting as required. If not then those plugins will only work with `vim-plug`. 

Are you not confusing `filetype plug on` with ``filetype indent on`?

Judging by the response from the community response, it is a surprising and unrelated behaviour. It's like say I make a color theme plug in that changes your tab indentation. It's a serious abstraction code smell.

**Comment by junegunn** [comment]
> Which plugins don't work with `auto indent on`?

All language-support plugins with indent files.

* https://github.com/fatih/vim-go/blob/feef9b31507f8e942bcd21f9e1f22d587c83c72d/doc/vim-go.txt#L2573-L2577
* https://github.com/vim-ruby/vim-ruby/issues/214#issuecomment-115276430
* https://github.com/rust-lang/rust.vim/blob/889b9a7515db477f4cb6808bef1769e53493c578/README.md?plain=1#L11-L17
* https://github.com/guns/vim-clojure-static/blob/fae5710a0b79555fe3296145be4f85148266771a/README.markdown?plain=1#L47-L53
* https://github.com/dag/vim-fish/blob/50b95cbbcd09c046121367d49039710e9dc9c15f/README.md?plain=1#L26-L33

All these plugins encourage their users to put `filetype plugin indent on` and `syntax enable` in the configuration file.

> Judging by the response from the community response

You're only looking at one side of the story. On the other side, there are a bunch of users scratching their heads why their Vim is not indenting the lines as expected, not syntax highlighting the code after they installed language-support plugins.
