### ISSUE TITLE
Issue with ignore files in .gitignore

### ISSUE THREAD

**Issue by LandonSchropp** [junegunn/vim-plug#380]
I'm a Vim newbie here, so I apologize if this is a dumb question. I'm tying to configure CtrlP to ignore files in my .gitignore file without much luck. I'm using [Thoughtbot's .vimrc file](https://github.com/thoughtbot/dotfiles/blob/master/vimrc), and I copied the following line into my .vimrc.local file from the readme:

```
let g:ctrlp_user_command = ['.git/', 'git --git-dir=%s/.git ls-files -oc --exclude-standard']
```

When I try to open Vim, I get this error:

```
Error detected while processing /Users/landon/.vimrc.local:
line   38:
E706: Variable type mismatch for: g:ctrlp_user_command
Press ENTER or type command to continue
```

I'm using Vim 7.4.1063 and the latest version of CtrlP from [vim-plug](https://github.com/junegunn/vim-plug). Here's my full .vimrc.local file:

```
" Enable text wrapping

set textwidth=105
set formatoptions+=t
set formatoptions-=l
set linebreak
set breakindent
set breakindentopt=shift:2

" Remap the default movement keys to work with wrapped lines
nmap <buffer> <silent> k gk
nmap <buffer> <silent> j gj
nmap <buffer> <silent> 0 g0
nmap <buffer> <silent> ^ g^
nmap <buffer> <silent> $ g$

" Prevent the cursor from jumping when joining lines
nnoremap J mzJ`z

" Center the cursor when jumping positions
nnoremap n nzz
nnoremap } }zz

" Make Vim's search case-sensitive, but only when the search string contains an uppercase letter
set smartcase

" Make Y's behavior match D and C
nnoremap Y y$

" Add wildcards for CtrlP and Vim to ignore
set wildignore+=*/tmp/*,*.zip,*/build/*,*.png,*.gif,*.jpg
let g:ctrlp_custom_ignore = {
\  'file': '\v\.(zip,png,gif,jpg)$',
\  'dir': '\v(build|tmp|log)'
\ }

" Ignore .gitignore files in CtrlP
let g:ctrlp_user_command = ['.git/', 'git --git-dir=%s/.git ls-files -oc --exclude-standard']
```

Thanks in advance!

**Comment by starcraftman** [comment]
@LandonSchropp Hello, this isn't really the right place to ask. In future, I'd confine general plugin questions to reddit's r/vim or irc channels. The issue tracker is just for vim-plug specific problems, whereas this is just a ctrlp usage question.

That said, I like CtrlP and so shall reply. The main problem is you made the user_command variable a simple list, whereas what I believe you were trying for is the dictionary type configuration where you specify a default command and specific ones for certain VCS like git. You should also have a fallback. I've made it from things I've seen. You probably don't need all the ignores I've put.

You may also want to look at one of the auxiliary matchers that work to varying degrees faster, like Plug 'FelikZ/ctrlp-py-matcher'.

```viml
if executable('ag')
  let &grepprg = 'ag --nogroup --nocolor'
  let s:ctrlp_fallback = 'ag %s
      \ --nocolor --nogroup --depth 5
      \ --hidden --follow --smart-case
      \ --ignore .bazaar
      \ --ignore .bzr
      \ --ignore .git
      \ --ignore .hg
      \ --ignore .svn
      \ --ignore .ccache
      \ --ignore .DS_Store
      \ --ignore .opt1
      \ --ignore .pylint.d
      \ --ignore .shell
      \ --ignore .wine
      \ --ignore .wine-pipelight
      \ --ignore "**/*.pyc"
      \ --ignore "**/*.class"
      \ --ignore "**/*.o"
      \ -g ""'
elseif g:win_shell
  let s:ctrlp_fallback = 'dir %s /-n /b /s /a-d'
else
  let s:ctrlp_fallback = 'find %s -type f'
endif

let g:ctrlp_user_command = {
    \ 'types': {
      \ 1: ['.git', 'cd %s && git ls-files . --cached --others --exclude-standard'],
      \ 2: ['.hg', 'hg --cwd %s locate -I .'],
    \ },
    \ 'fallback': s:ctrlp_fallback
\ }

" Faster matcher
if has('python')
  let g:ctrlp_match_func = { 'match': 'pymatcher#PyMatch' }
endif
```

**Comment by LandonSchropp** [comment]
Oops, I'm sorry, I accidentally posted this into the wrong repo. My bad. Still, thanks for replying!

**Comment by starcraftman** [comment]
@LandonSchropp No problem. :)
