### ISSUE TITLE
Custom plugin settings

### ISSUE THREAD

**Issue by magicalbanana** [junegunn/vim-plug#382]
So I have a modular vim approach. What would be the best place to put the custom settings I have for some plugins I have if I have the on load demand options activated?

**Comment by vheon** [comment]
Depends on the plugins:

- Some plugin use regular `g:plugin_option` style, so if you put those configuration in your vimrc then when the plugin gets loaded it would find those configuration already in place.
- Other plugins uses functions to specify the settings or autoloaded variables (i.e. g:plugin#variable ); those kind of settings need the plugin to be loaded so I believe that the best way to configure them is:

```viml
Plug 'author/plugin', { 'on': [] }
augroup plugin_
autocmd!
autocmd User plugin call plugin#setup()
augroup END
```

Here I used the function setup but if they are autoloaded variables just do `let g:plugin#variable`

**Comment by junegunn** [comment]
@vheon Thanks for the comment. Correct me if I'm wrong but as far as I know, a variable containing `#` in its name is nothing special and does not require special handling. It's just a naming convention coined to match that of autoload function.

```vim
" No problem
let g:foo#bar#baz = 1
```

@magicalbanana There is no "best" way to configure plugins. It's just a matter of preference.

- Most plugins are configured with just `g:` variables, and there's no restriction on how you define them.
- But as @vheon mentioned, if a plugin should be configured via its function, you need to use autocmd.
    - You still need autocmd even when you don't use on-demand loading facility of vim-plug since plugins are loaded after vim finished processing .vimrc
        - `autocmd VimEnter * call foo#bar()`
    - `autocmd User [PLUGIN_NAME]` otherwise

**Comment by vheon** [comment]
>@vheon Thanks for the comment. Correct me if I'm wrong but as far as I know, a variable containing # in its name is nothing special and does not require special handling. It's just a naming convention coined to match that of autoload function.
>
```viml
" No problem
let g:foo#bar#baz = 1
```

Yeah sorry. Anyway they have a different semantics when you read from them http://vimdoc.sourceforge.net/htmldoc/eval.html#E746

**Comment by junegunn** [comment]
@vheon Interesting. Didn't know about that. Thanks.

**Comment by vheon** [comment]
:+1:

**Comment by magicalbanana** [comment]
But I have my vim plugins's configuration via their own .vim files. When using your plugin, can I put them in the plugged folder?

**Comment by starcraftman** [comment]
@magicalbanana You mean to say for each plugin, it has its own `plugin.vim` file somewhere inside your `.vim` folder? Sure you can source them manually, vim-plug won't do it for you. I'd advise against putting them inside `.vim/plugged`, you may run into a name collision when cloning. Just use any other folder path and source em with a for loop/globbing.

**Comment by nhooyr** [comment]
@junegunn 
> You still need autocmd even when you don't use on-demand loading facility of vim-plug since plugins are loaded after vim finished processing .vimrc

Interesting. Does neovim do it a bit differently? I can call functions right after `call plug#end()` without an autocmd.

**Comment by junegunn** [comment]
@nhooyr It's the same. The startup process is described in `:help startup`. `plug#end()` updates `&runtimepath` so you can call autocmd functions right after that, but the script in `plugin` directory are normally loaded after  vimrc.

**Comment by nhooyr** [comment]
ah ok
