### ISSUE TITLE
ban some plugins for specific file types

### ISSUE THREAD

**Issue by skt041959** [junegunn/vim-plug#383]
Is there a method to ban some plugins for specific file types?

**Comment by vheon** [comment]
What is the use case?

**Comment by junegunn** [comment]
A Vim plugin is just a collection of scripts and loading it means that we execute those scripts. They change the global state of Vim in arbitrary ways and the change is irreversible. So it's simply not possible to "unload" a plugin, though a plugin may provide its own command for disabling it.

So even if we provide something like `not-for` option (put aside the inevitable complication of the implementation), it's not going to be really useful as the plugin will be globally activated as soon as you open a file of different type.

**Comment by skt041959** [comment]
@junegunn Thank you. I have understand the meaning. The case is that I have installed the deoplete.nvim and YouCompleteMe. Both of them provides completion for multiple program languages. I would like to use ycm in C/C++, and deoplete in other languages but C/C++. Maybe I can add `{'for': ['python', 'lua', 'vim', 'sh']}` option to the deoplete. But I just want to do it more general.

**Comment by junegunn** [comment]
I see. Specifying disjoint sets of filetypes in `for` option is the best we can. Maybe you can set up your own `autocmd filetype` for disabling a particular plugin if it provides such a command, but I have no prior experience with them.
