### ISSUE TITLE
Gracefully degrade if git is not available

### ISSUE THREAD

**Issue by nedbat** [junegunn/vim-plug#384]
I use vim-plug to manage plugins, but then I tar up my dotfiles and .vim directory, and copy it to remote machines.  This works great, except if the machine has no git installed, vim-plug will produce a message on startup: 
```
[vim-plug] `git` executable not found. vim-plug requires git.
```
It works fine though, to run the plugins from the plugged directory, even without git.  Would it be possible to make it more graceful in this case somehow? Maybe a setting to say, "I don't have git, that's fine, I won't use the PlugInstall, etc, commands, but I still want you to run the plugins in the plugged directory."

**Comment by vheon** [comment]
That is exactly what is happening. The only command available would be `Plug`. I think is not that obvious though...

**Comment by nedbat** [comment]
That is what's happening, but gvim pops up an alert box telling me that vim-plug requires git.  I don't want it to do that.

**Comment by junegunn** [comment]
Prepend `silent!` to `call plug#begin()`, that will silence the message.

**Comment by Gon-Zales** [comment]
@junegunn Hello. But how can I tell vim where to find git? Should I add path in the PATH variable or modify some vim options in .vimrc like :set gitpath='c:/program files/git/git.exe'?

**Comment by junegunn** [comment]
> Should I add path in the PATH variable

Yes, vim-plug uses `executable('git')` function to see if git command is available.

```
executable({expr})					*executable()*
		This function checks if an executable with the name {expr}
		exists.  {expr} must be the name of the program without any
		arguments.
		executable() uses the value of $PATH and/or the normal
		searchpath for programs.
```
