### ISSUE TITLE
How can I install new plugins, after modifying my ~/.vim/vimrc

### ISSUE THREAD

**Issue by chrisbra** [junegunn/vim-plug#389]
Hi,
I often have to install some plugins temporary to test vim-airline against a certain configuration. Therefore I open up my .vimrc, add another `Plug 'user/repository'` and would like to have a way, to install those plugins afterwards, without having to restart vim in order to have those lines take effect.
On a simple `:PlugInstall` it won't obviously not find those newly added lines. 

What would be the prefered way to install new plugins in that case?

**Comment by junegunn** [comment]
Basically I do `:source $MYVIMRC | PlugInstall` (actually reloading via BufWritePost autocmd).

**Comment by chrisbra** [comment]
Okay, that would work I suppose. What about a `:PlugInstall user/repository` extensions?

**Comment by junegunn** [comment]
I heard that Vundle supports such one-time installation. But we are probably not going to support it.
