### ISSUE TITLE
Please provide a redraw action on confirmation of :PlugClean command

### ISSUE THREAD

**Issue by chrisbra** [junegunn/vim-plug#391]
Running :PlugClean, it prompts for `Proceed? y/N`
Unfortunately i couldn't read all the output, so I increased the terminal size. While the terminal was redrawn correctly, it did not redraw the buffer contents, and still prompting me. So please add another option to redraw manually. thanks.

**Comment by junegunn** [comment]
Hmm, I don't know if it's possible to redraw during `input()`, is it? If it's not, you'll have to answer no to the prompt and do it again.

**Comment by chrisbra** [comment]
On Mi, 27 Jan 2016, Junegunn Choi wrote:

> Hmm, I don't know if it's possible to redraw during `input()`, is it? If it's not, you'll have to answer no to the prompt and do it again.

Can't you call :redraw! on e.g. ctrl-l keypress?

**Comment by junegunn** [comment]
`autocmd VimResized` seems to work, though I'm not sure if we really have to set up (and clean up) an autocmd or a key binding for this. It's pretty easy to "no", check, and retry.

**Comment by chrisbra** [comment]
On Mi, 27 Jan 2016, Junegunn Choi wrote:

> `autocmd VimResized` seems to work, though I'm not sure if we really have to set up (and clean up) an autocmd or a key binding for this. It's pretty easy to "no", check, and retry.

yes, it is probably not worth the trouble. Go ahead and close it.
