### ISSUE TITLE
`ValueError: failed to parse CPython sys.version`

### ISSUE THREAD

**Issue by summivox** [junegunn/vim-plug#393]
When attempting to run `:PlugInstall` it gives me this:

![screenclip 3](https://cloud.githubusercontent.com/assets/1770521/12662983/fd8f5a42-c5f1-11e5-825c-27a7e8a8cc29.png)

I'm using Anaconda Python distribution and it works fine with other Python-based plugins.

**Comment by starcraftman** [comment]
@summivox Hello. Interesting.

The line in question is pretty simply. You can try it from within vim with:
```py
python import platform; print(platform.python_version())
```

If this line fails, can you try the following one. Not sure why brackets are round the print since its only 2.x code.
```py
python import platform; print platform.python_version()
```

**Comment by starcraftman** [comment]
I just tried the latest stable [Anaconda python 2.7, 32bit build](https://www.continuum.io/downloads) with stock 32 bit GVim. Setup works fine for me. Weird, do you still have the exe? Perhaps try reinstalling? Alternatively, it could be as simple as your revision of python broke this call.

 I notice yours seems to be a specific revision build, why? Do you have the installer link for it?

**Comment by summivox** [comment]
@starcraftman I tried both lines and they both failed with the same message as original.

I remember using the official installer long time ago.

```
C:\WINDOWS\system32>conda --version
conda 3.19.0

C:\WINDOWS\system32>python --version
Python 2.7.7 :: Anaconda 2.0.1 (64-bit)
```

**Comment by summivox** [comment]
Ah crap. This is 64-bit python. Does it matter?

**Comment by starcraftman** [comment]
@summivox Well seems your system has both 32 and 64 bit versions, I imagine the GVim exe is 32bit hence it selects that one. If you open a 32bit conda terminal I assume the platform line fails. Maybe just simply reinstall with the latest stable anaconda 32 release?

If the other plugins just worked, it could be that only the platform.python_version() call is broken, but that would be anaconda's problem. It is a standard call.

**Comment by summivox** [comment]
64-bit gVim build works. It's not maintained officially though so I'm still hesitant.
IIRC vim is using `python27.dll`, right? I wonder where that 32-bit dll comes from, since I only installed anaconda 64-bit.

**Comment by starcraftman** [comment]
@summivox Well if you aren't sure, that is curious. I mean it is your computer. :)

Anyway, I think that settles this bug. If the 32 bit version continues to be problematic just install another version like the official python.org one. Unfortunately the vim project doesn't provide a 64bit build. I have used [this project](https://tuxproject.de/projects/vim/) when on Windows for 64bit. They provide a batch script to compile it yourself if you want to.

Happy Vimming.
