### ISSUE TITLE
weird neovim key not present in dictionary errors

### ISSUE THREAD

**Issue by nhooyr** [junegunn/vim-plug#394]
If I run `:PlugUpdate` and press `D` or `S` neovim starts throwing out errors about keys not being present in dictionaries. I'm not sure what the problem is. I don't think it has to do with my neovim configuration because it still happens with a init.vim with only one plugin.

<img width="1440" alt="screen shot 2016-01-29 at 10 31 50 am" src="https://cloud.githubusercontent.com/assets/10180857/12679696/86274230-c673-11e5-9df8-012172513519.png">

It continues and continues and continues with more keys not found and stuff.

**Comment by starcraftman** [comment]
@nhooyr When you say "happens with init.vim with only one plugin" do you mean your `init.vim` is as minimal as this? If not, try this.

```vim
call plug#begin('~/.vim/plugged')
Plug 'junegunn/vim-easy-align'
call plug#end()
```

I just rebuilt neovim from latest master and cannot reproduce any problem. My build was: NVIM v0.1.2-391-g4c960c3 with Build type: RelWithDebInfo. What is the version of your neovim build? Also, since we are using the shell, what shell/platform are you using?

The line it fails on is:  `let job = s:jobs[a:name]`. Would seem for some reason the job is no longer in our s:jobs dictionary. I am not certain why, I don't have a guess without reproducing.

**Comment by nhooyr** [comment]
@starcraftman happens to me with it as minimal as that.

I'm using the latest master as well. My build type is Dev. However I tried the latest release with RelWithDebInfo and both have the same problem. I use brew and it only gets the latest master if I use the option head which means it compiles as dev, if I use latest release it builds as RelWithDebInfo.

 I'm using zsh as my shell.

**Comment by nhooyr** [comment]
It also happens on linux, with that tiny init.vim

**Comment by nhooyr** [comment]
Also I meant run `:PlugUpdate` and as it is running press `D` (shift-d)

**Comment by starcraftman** [comment]
@nhooyr 
> Also I meant run :PlugUpdate and as it is running press D (shift-d)

Ah now this is a whole different story. This fails for me too in the same way, but you aren't supposed to push 'D' until the jobs are all finished. Naughty user! :)

I assume you imagined it would keep working without issue and diff would populate as jobs completed? Or was this just a random button press?

The current mappings are shared with the synchronous installers whose work can't be interrupted in such a way. Perhaps we should simply map these post update/install finish. @junegunn thoughts?

**Comment by nhooyr** [comment]
@starcraftman but then why is there `pending updates`?

**Comment by starcraftman** [comment]
@nhooyr What do you mean `pending updates`? The reason the jobs still running when 'D' pushed? None of those bindings (D, S...) abort current job, only 'q' does that currently.

**Comment by nhooyr** [comment]
@starcraftman If press D after plug update it says Last Update: and Pending Update:. What is the point of pending updates if you aren't supposed to press `D` while updating?

**Comment by starcraftman** [comment]
@nhooyr Ah, I think you are confused about what was meant by 'Pending updates' in the diff buffer. This was put in for people who regularly use the 'commit' and 'tag' options, they can then preview new commits/tags before moving their locked state. It never displays anything for Plugs without one of those two options.

There is no support for the PlugDiff command during the update/install. Though it might be wise to unbind these during execution to prevent such mishaps.

**Comment by nhooyr** [comment]
Ah, i understand now thanks.

**Comment by junegunn** [comment]
@starcraftman I think we should disable the mappings during installation. Are you working on this? And as you pointed out `Pending updates` are always empty without `commit` or `tag`, so we can consider not showing the section when those options are not being used.

**Comment by starcraftman** [comment]
@junegunn Yes, I just made a branch/PR. I will go and disable the `Pending updates` bit when empty.
