### ISSUE TITLE
Directories with the same basename are ignored

### ISSUE THREAD

**Issue by mikew** [junegunn/vim-plug#401]
```bash
vim -Nu <(cat << EOF
source ~/plug.vim
call plug#begin()
Plug '/plugin1/before'
Plug '/plugin2/before'
call plug#end()
EOF
) +'echo &rtp'
```

`/plugin2/before` will not be listed in the `rtp`

Maybe the `as` can be abused to get them to load, but checking if `repo` looks like a local path seems to work:

```vim
    if s:is_local_plug(repo)
      let name = repo
    endif
```

**Comment by starcraftman** [comment]
@mikew Are you sure you don't have it backwards, plugin2 should be on the rtp since it is the last one put in the g:plugs dictionary. The 'as' option would fix this, why do you think it is "abuse" to use that?

Is this purely a theoretical use case? Why would you have two local plugins with same base folder name? You could always just rename one as well.

**Comment by junegunn** [comment]
@starcraftman Looks like he's trying to organize his plugin-wise settings using (abusing?) vim-plug.

@mikew Your suggestion makes sense but I have the feeling that it breaks consistency we take it for granted now, so I'm not sure if we should do this. Most users don't use it that way and there are many other ways to handle this. Care to share your dotfiles? We can probably suggest alternative ways.

**Comment by starcraftman** [comment]
@junegunn Ah perhaps, hadn't thought of that. Doesn't seem like a great idea to me though.

**Comment by mikew** [comment]
[I forked janus to use vim-plug](https://github.com/mikew/janus/tree/master) and they have things organized like `core/before, core/after, tools/before, tools/after, colors/before, colors/after`. [Currently for these I am just managing `rtp` manually](https://github.com/mikew/janus/blob/5540f70b4919ad3fb625698c5383830556a9c013/janus/vim/core/before/plugin/janus.vim#L170-L178) and took another shot at seeing what was going on.

Agreed that this isn't much of an issue. The same thing will happen if someone has two plugins with the same name from different Github users, but that's not a great example.

**Comment by junegunn** [comment]
> Currently for these I am just managing rtp manually

That's a completely legitimate way of doing it :)

Support for local plugins was added mainly for prototyping. You work on a prototype locally, release it on github, and you switch the argument. There are a few places where vim-plug uses the "name" of the plugin, the public `g:plugs` data structure, and `autocmd User PLUGIN_NAME` for lazy initialization. So I don't think it's a good idea to name local plugins differently, unless explicit `as` option is given. I'll close this. Anyway thanks for the feedback.
