### ISSUE TITLE
Windows 7 gvim cannot use more than one plugin at a time

### ISSUE THREAD

**Issue by Tabby-** [junegunn/vim-plug#402]
Happening on most commands, am not getting any errors. Works fine if I only use one plugin, it just wont process anything if I uncomment more than one `Plug '___'` line.

More than 1 plugin:
![asfa](https://cloud.githubusercontent.com/assets/10349680/12842597/b01b4424-cbeb-11e5-8df3-fe53a2c71a19.PNG)
1 plugin:
![dsf](https://cloud.githubusercontent.com/assets/10349680/12842598/b030f5ee-cbeb-11e5-8f5a-7f91fae1f44b.PNG)

**Comment by starcraftman** [comment]
@Tabby- Peculiar. If you do `:PlugUpdate 1` with all the Plug lines enabled does it work? 

If that works, please tell me where you got...
- GVim
- Git (i.e. GitSDK, msysgit...)
- python version and vendor (i.e. python.org, activestate...)

**Comment by Tabby-** [comment]
@starcraftman `:PlugUpdate 1` works perfectly, thanks.

- Vim first from https://tuxproject.de/projects/vim/, and then from https://bintray.com/veegee/generic/vim_x64, neither of which worked.
- Git version 2.7.0 64 bit from http://www.git-scm.com/
- I have version 3.5.1 and 2.7.11 of python installed, both 64 bit versions from https://www.python.org/

**Comment by starcraftman** [comment]
@Tabby- Alright, I am testing this in one of my VMs but this seems like a standard setup I've run before so it should work. I can only test 32bit in my VM but I don't see architecture as being a problem. I did notice this new [step](https://github.com/k-takata/vim/commit/435be6dc61347d92029768f1678fdfdb9a543005) for 2.7.11 regarding regedit. May have to document this annoying registry issue.

To confirm local setup can you do the following commands, report any errors:
```viml
:echo system('git --help')
:python import platform; print platform.python_version()
:python3 import platform; print(platform.python_version())

**Comment by Tabby-** [comment]
@starcraftman the second command came up with an error, so I tried the registry change and it now comes up with 2.7.11 as expected, all of the vim-plug commands now seem to be working as intended. Thanks.

**Comment by starcraftman** [comment]
@Tabby- Quite a nuisance, just found the [bug](https://bugs.python.org/issue25824). Seems a bit disappointing they made a release with this.

Also, when both python 2 and python 3 present, we prefer the 2 interface because a lot of other plugins are not 3 compatible. Hence why it didn't work when 3 installed. So if you had removed 2 entirely, it probably would have worked, though other plugins might not have.

I think we might have to document this, might have been the cause of other Windows python bugs.
