### ISSUE TITLE
Can I suppress warnings on opening Vim?

### ISSUE THREAD

**Issue by githorse** [junegunn/vim-plug#405]
Most of the time I run MacVim, in which all of my plugins work fine. Sometimes I use my `vimrc` on a different system without MacVim. When I do so, I get some harmless warnings on opening Vim:

```
YouCompleteMe unavailable: requires Vim 7.3.598+
UltiSnips requires Vim >= 7.4
Press ENTER or type command to continue
```

Is there some way to make the plugins fail silently? Or maybe put them inside a predicate that would know if MacVim or system Vim is running? 

[Note that this is a different question than #220, which seems to be asking about post-install hooks.]

**Comment by vheon** [comment]
> Is there some way to make the plugins fail silently?

The plugin are echoing on their own, I don't think there is a way to silent them.

> Or maybe put them inside a predicate that would know if MacVim or system Vim is running?

Yes, 

```viml
if has("gui_macvim")
  Plug 'Valloric/YouCompleteMe'
  Plug 'SirVer/ultisnips'
endif
```

**Comment by starcraftman** [comment]
@githorse To add on what vheon said, you could manually check the patch level like follows. Similarly if a plugin needs python put it in a has('python') block.

```viml
 if has('nvim') || (v:version >= 704 || (v:version == 703 && has('patch584')))
    Plug 'Valloric/YouCompleteMe', { 'do': function('hooks#YCMInstall') }
  endif
```

It is a bit of a nuisance, but vim-plug doesn't maintain any info on what a plugin needs so they all emit warnings on sourcing.

**Comment by githorse** [comment]
Thanks @vheon, @starcraftman -- I think either of these will do what I need.

**Comment by githorse** [comment]
@vheon - This is still bugging me, a bit. I guess plugins don't provide any consistent way to query themselves about minimum version / build requirements (without just running them and seeing if they produce an error message)? 

[This article](https://sanctum.geek.nz/arabesque/gracefully-degrading-vimrc/) suggests using `silent! call pathogent#infect()` to prevent plugin errors with Pathogen (haven't tried it myself). I'm still wondering if we couldn't achieve something like this with vim-plug. Silent doesn't seem to do the trick. 

Would be nice not to have to know the requirements for each plugin (e.g. `has('gui_macvim')`).

**Comment by vheon** [comment]
@githorse using `silent!` would not work because is YouCompleteMe itself that is telling you that you don't have the right version of vim.

> Would be nice not to have to know the requirements for each plugin

Considering the amount of plugin that actually have this kind of limitation I guess that doing it by hand would be the best thing here.
