### ISSUE TITLE
Add FAQ entry about "E116: Invalid arguments for function <SNR>2_add"

### ISSUE THREAD

**Issue by nicolaiskogheim** [junegunn/vim-plug#407]
This is an example of loading a plugin on-demand:

```vim
Plug 'junegunn/goyo.vim', { 'on' : 'Goyo' }
```

But, if you forget the comma (`,`), like this

```vim
Plug 'junegunn/goyo.vim' { 'on' : 'Goyo' }
```

you get a nasty message:

```
Error detected while processing /path/to/.vimrc:
line  119:
E116: Invalid arguments for function <SNR>2_add
```

I know this most probably is vimscript-specific, and that you can get this kind of error from any function-call (if that is what `Plug` is), but I imagine *vim-plug* has a lot of users that are new to Vim, and wouldn't know what to do. The error message points to the line, but the missing comma can be hard to spot none the less.

Just bringing it up in case you wanted to put a note about it in the FAQ.

**Comment by junegunn** [comment]
Hmm, there's really not much we can do about such basic syntactic mistakes. One thing we can do though is to rename `s:add()` to `s:Plug()` so that it's easier for the users the figure out what's going on.

**Comment by nicolaiskogheim** [comment]
Looks good to me :)
