### ISSUE TITLE
Change folder from ~/.vim to ~/.config/nvim

### ISSUE THREAD

**Issue by RenatoUtsch** [junegunn/vim-plug#408]
Hello,

I'm starting to use neovim, and I wanted to change the default folder for the plugins from `~/.vim/plugged` to `~/.config/nvim/plugged` to keep all neovim files in the same nvim folder.

Is there an option for this? If not, how can I contribute to add support for it?

**Comment by vheon** [comment]
```viml
call plug#begin('~/.config/nvim/plugged')
Plug 'user/plugin'
...
call plug#end()
```

**Comment by RenatoUtsch** [comment]
Thanks! I can't believe I didn't notice that.
