### ISSUE TITLE
vim-plug causes concealed entities to be revealed in tex files

### ISSUE THREAD

**Issue by Lavvrence** [junegunn/vim-plug#409]
```
:syn match Entity 'e' conceal
:set cole=3
```

causes all 'e's to be concealed. but this does not work if the filename is *.tex and vim-plug is active. minimal .vimrc:

```
call plug#begin()
call plug#end()

```

**Comment by junegunn** [comment]
That's because vim-plug enables filetype plugins in `plug#end()` (`filetype plugin indent on`), and you can turn it off by adding `filetype off` after the line, though I don't think you should. See `:help tex-conceal` for more info.
