### ISSUE TITLE
Include graph in changes log

### ISSUE THREAD

**Issue by vhda** [junegunn/vim-plug#411]
Using `--graph` in `git log` improves, in general, the readability of the changes, allowing analyzing groups of commits according to each individual merge.

Would it make sense to use this option in the vim-plug?

**Comment by junegunn** [comment]
<img width="642" alt="screen shot 2016-02-27 at 12 21 27 am" src="https://cloud.githubusercontent.com/assets/700826/13356344/18585ab0-dce8-11e5-9117-443ef61033c0.png">

I'm trying this out locally, trying to see if I like the new look better or not. Merging this will cause some [extra scripts to break](https://github.com/junegunn/vim-plug/wiki/extra), so I'll have to update the wiki page as well.

**Comment by vhda** [comment]
That simple linear graph looks very nice, but before you commit to such change please guarantee that you like what happens if there are "cross" merges. I suggest that you test `vim-airline`, which has some complex merge graphs.

**Comment by starcraftman** [comment]
@junegunn Do you intend to make that default behavior? Or maybe opt in via a global? It is interesting and nice, have you tested against more exotic merges and how that looks?

**Comment by junegunn** [comment]
@vhda @starcraftman 

If I decided to merge this, I'd like to make it default. Not a fan of more options. It simply uses the output of `git --log` graph, so it works with more complex cases.

<img width="525" alt="screen shot 2016-02-27 at 11 24 27 am" src="https://cloud.githubusercontent.com/assets/700826/13370209/b023f58c-dd44-11e5-9ede-94c0801ae331.png">

I'll also see if it makes sense to keep the coloring of the graph.

**Comment by vhda** [comment]
That's great. I'm looking forward to see these graphs in the log output.

**Comment by vhda** [comment]
Thanks!
