### ISSUE TITLE
Use git:// protocol instead of https:// to clone from github?

### ISSUE THREAD

**Issue by chaoren** [junegunn/vim-plug#412]
I'm running into a weird problem where github keeps asking for my username and password.
See: https://help.github.com/articles/why-is-git-always-asking-for-my-password

This doesn't usually happen, so it's probably a problem with my environment right now, but should be avoidable by vim-plug if it just used the git:// protocol instead of https://.

Also another benefit, from https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols

The Git protocol is often the fastest network transfer protocol available. If you’re serving a lot of traffic for a public project or serving a very large project that doesn’t require user authentication for read access, it’s likely that you’ll want to set up a Git daemon to serve your project. It uses the same data-transfer mechanism as the SSH protocol but without the encryption and authentication overhead.

There could be some headache trying to migrate people's existing projects from https:// to git:// though.

**Comment by chaoren** [comment]
Oh, heh, apparently it's because the repository is down due to DMCA takedown. I didn't even know that happens on github.

Anyway, the speedup of git:// over https:// is still something to consider. You could make it so vim-plug recognizes and respects existing URLs with any protocol, but create new clones with git:// only. That would solve the migration problem.

**Comment by junegunn** [comment]
`Plug` command takes any valid git url, so you can already do it, right?
There is also [`g:plug_url_format` option](https://github.com/junegunn/vim-plug#global-options).

**Comment by chaoren** [comment]
Yeah, but it's arguably a better default.

**Comment by junegunn** [comment]
I disagree. For me it doesn't work in corporate environment where I'm behind http proxy. And I don't think we should choose unencrypted protocol for marginal performance benefit it provides considering that most vim plugins are relatively small. And GitHub officially [recommends https protocol](https://help.github.com/articles/which-remote-url-should-i-use/#cloning-with-https-urls-recommended) for cloning. I can understand someone prefers it, but it's not a good default.

**Comment by chaoren** [comment]
Okay. Fair enough.

**Comment by aemonge** [comment]
So how are you using vim-plug through a proxy ? I'm currently blocked by this, any ideas ?
