### ISSUE TITLE
Functions not being defined in Neovim

### ISSUE THREAD

**Issue by zovt** [junegunn/vim-plug#413]
Hello. Unless I'm doing something wrong in my config, I can't seem to get Plug working with neovim. I'm using windows, and have ~\vimfiles\autoload in my runtime path with plug.vim inside that folder. However, neovim gives me errors saying that plug#begin(), Plug, and plug#end are undefined. I also have no access to :PlugInstall or anything like that.

**Comment by zovt** [comment]
And never mind. Figured out my directory structure was wrong. My bad

**Comment by starcraftman** [comment]
@zovt Ya, unfortunately that XDG move strikes again. I'm not sure it was entirely warranted given all the confusion it has likely lead to.

**Comment by zovt** [comment]
Wasn't the XDG move. Since I'm on Windows I'm not sure that really applies to me anyways. My problem was that ~\vimfiles\autoload was the _actual folder_ in my rtp, so it was looking for an autoload folder _inside_ that one.

**Comment by starcraftman** [comment]
@zovt Ah, heh. Ok then, glad you got it sorted then.
