### ISSUE TITLE
Consider ISSUE_TEMPLATE.md

### ISSUE THREAD

**Issue by junegunn** [junegunn/vim-plug#416]
https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by starcraftman** [comment]
@junegunn Man that's a bit late to the game, but a welcome change nonetheless. We definitely need to mention not raising issues/PRs like #367, since that seems to crop up frequently. I'll have a think on what to mention, perhaps a few simple diagnostics and a checklist of what to include in an issue (i.e. version, python version, ruby version, steps to reproduce...).

**Comment by junegunn** [comment]
Thanks. I'll also think about it. At the very minimum, these are the most basic things we should have.

- Type:
    - [ ] Bug
    - [ ] Feature
    - [ ] Question
    - [ ] Suggestion
- OS:
    - [ ] General/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by starcraftman** [comment]
@junegunn I made a branch and tried this feature out, how are these simple templates? I think I covered all the major things, though I'm not sure about your 'type' field. What's the difference between suggestion and feature (I assume meaning feature request)?

- [Issue Template](https://github.com/starcraftman/vim-plug/blob/master/.github/ISSUE_TEMPLATE.md)
- [PR Template](https://github.com/starcraftman/vim-plug/blob/master/.github/PULL_REQUEST_TEMPLATE.md)
- In issues, I linked a [new wiki](https://github.com/starcraftman/vim-plug/wiki/requirements) page I made a while ago, details both requirements and tested working configurations (especially Windows). This combines diagnosing requirements work, with configurations you or I tested that people can fall back on.

**Comment by junegunn** [comment]
@starcraftman Looks pretty good. Thanks. The wiki page looks solid. I'll take a closer look later in the day. Oh, and I noticed that some projects use `<!--`  `-->` comment around the section that should not be visible when submitted.

> What's the difference between suggestion and feature (I assume meaning feature request)?

Suggestions of minor adjustment or enhancement of the preexisting feature? Something like #411. "New feature" and "Enhancement" might be more appropriate.

**Comment by junegunn** [comment]
> put a tag in the title

We can consider that. Do you think it will be easier for the users than checkboxes? One "hyphothetical" advantage of checkboxes is that it allows multiple selections.

Regarding "Installer Affected" section, the user may not have enough knowledge to determine what's going on, though the general guidance is given in the requirements page, it will be easier both for them and for us that we just ask them for the output of a few commands, such as `:echo [has('ruby'), has('python'), has('python3')]`, `:version`, etc. Please note that I updated the OS X + Ruby section of your page. Other than that, looks good to me. Good job!

**Comment by starcraftman** [comment]
@junegunn 
>  Oh, and I noticed that some projects use  comment around the section that should not be visible when submitted.

Good point, saves on them deleting.

> "New feature" and "Enhancement" might be more appropriate.

These seem better, though I still see not a huge difference. 

> We can consider that. Do you think it will be easier for the users than checkboxes?

I think I'll take back my idea, not sure I want tags in titles. We'll leave it via boxes.

> Regarding "Installer Affected" section, the user may not have enough knowledge to determine what's going on, though the general guidance is given in the requirements page, it will be easier both for them and for us that we just ask them for the output of a few commands, such as :echo [has('ruby'), has('python'), has('python3')], :version, etc.

This is true. I guess it might be best to just link to said requirements page, saves space.

> Other than that, looks good to me. Good job!

Ok, I'll move it over to the main. We'll link it from the README once we settle on a template. I'll go update my branch in a bit and maybe make a PR to continue commenting directly onto it.
