### ISSUE TITLE
Removing `plug ''` statements?

### ISSUE THREAD

**Issue by mtglsk** [junegunn/vim-plug#418]
VAM somehow allows to write `VAMActivate PLUGIN_NAME PLUGIN_NAME ...` in vimrc.

I find the `Plug 'PLUGIN_NAME'` tedious to write for every plugin I test out and it would be nicer to be able to just paste the github link and be done with it.

**Comment by junegunn** [comment]
That can be done with a helper command. You may or may not want to `plug#begin` and `plug#end` in it.
```vim
function! s:plugs(args)
  call plug#begin()
  for arg in split(a:args)
    Plug arg
  endfor
  call plug#end()
endfunction
command! -nargs=+ Plugs call s:plugs(<q-args>)
```

**Comment by mtglsk** [comment]
Thanks, great stuff.
