### ISSUE TITLE
E492: Not an editor command: PlugInstall on Windows 10

### ISSUE THREAD

**Issue by Givemeyourgits** [junegunn/vim-plug#421]
I cannot get this to work on Windows 10 x64 Pro.  I've manually created ~/vimfiles/autoload/plug.vim and I've used the install commands from powershell.  I've put them in ~/.vim/autoload and ~/vim/autoload, I've even tried ~/vimfiles/plugins.  Nothing will get vim to detect the plugin and allow me to use :Pluginstall.

The .vimrc file is being picked up (but complains about plugins as they are not installed).  It works great under linux, but I cannot get it to work in Windows no matter what I try.

I am running vim 7.4.872 and git 2.7.1 for windows, I have python 2.7.10 installed as well if that matters.

**Comment by starcraftman** [comment]
@Givemeyourgits Interesting. For the record, I'd stick to vimfiles. Let's see. Can you give the output of `:scriptnames` in a code block? I assume plug.vim won't be in there.

Assuming it isn't, can you paste the output of `echo &rtp`, the folder above the autoload directory should be at the front. If it isn't, try putting in your vimrc `set rtp^=path`, where path is aforementioned base path.

**Comment by Givemeyourgits** [comment]
Ok, after some digging I figured out some more and got it working a different way.

For scriptnames I'm getting the following:

` 1: /etc/vimrc
  2: /usr/share/vim/vim74/syntax/syntax.vim
  3: /usr/share/vim/vim74/syntax/synload.vim
  4: /usr/share/vim/vim74/syntax/syncolor.vim
  5: /usr/share/vim/vim74/filetype.vim
  6: ~/.vimrc
  7: /usr/share/vim/vim74/syntax/nosyntax.vim
  8: /usr/share/vim/vim74/autoload/plug.vim
  9: /usr/share/vim/vim74/plugin/getscriptPlugin.vim
 10: /usr/share/vim/vim74/plugin/gzip.vim
 11: /usr/share/vim/vim74/plugin/logiPat.vim
 12: /usr/share/vim/vim74/plugin/matchparen.vim
 13: /usr/share/vim/vim74/plugin/netrwPlugin.vim
 14: /usr/share/vim/vim74/plugin/rrhelper.vim
 15: /usr/share/vim/vim74/plugin/spellfile.vim
 16: /usr/share/vim/vim74/plugin/tarPlugin.vim
 17: /usr/share/vim/vim74/plugin/tohtml.vim
 18: /usr/share/vim/vim74/plugin/vimballPlugin.vim
 19: /usr/share/vim/vim74/plugin/zipPlugin.vim
 20: /usr/share/vim/vim74/ftoff.vim
 21: ~/.vim/plugged/vim-polyglot/ftdetect/polyglot.vim
 22: ~/.vim/plugged/vim-polyglot/after/ftdetect/rspec.vim
 23: /usr/share/vim/vim74/ftplugin.vim
 24: /usr/share/vim/vim74/indent.vim`

This is Windows, so those paths look weird, but they are relative to C:\Program Files\Git.  So I went in there, and dropped plug.vim into /usr/share/vim/vim74/autoload and it worked great.  Looks like git is setting the runtime path to it's folder no matter where I run vim from (I have two installs, one from git for Windows and one from cmdr for windows which has it's own git for windows).

**Comment by starcraftman** [comment]
@Givemeyourgits Yup that does look a bit weird. As you said though, there are many ways for setting up git/vim on Windows leading to many different configs, An alternative to what you did could have been to simply add a small snippet like below, as long as HOME or some equivalent environment variable pointed to your user root where you'd like to store vim files.

```viml
if has('win32')
  set rtp^=$HOME
endif
```

Your way is fine if you are happy, I'm closing this.
