### ISSUE TITLE
Ruby throws an error on PlugInstall

### ISSUE THREAD

**Issue by tandrewnichols** [junegunn/vim-plug#422]
Trying to switch from Vundle and when I run `:PlugInstall`, ruby complains about rubygems.rb. I'm not a Ruby developer (I have it because it's used by other programs and because I like the idea of potentially using it), so I'm having trouble figuring out what to do to fix this. Is this script dependent on a particular version of Ruby? I'm using rvm to manage Ruby and am running on 2.1.1 at the moment (haven't tried another version). Here's the output I see at the bottom:

<img width="1005" alt="screen shot 2016-02-23 at 1 12 22 pm" src="https://cloud.githubusercontent.com/assets/2755760/13261742/8549e7b2-da2f-11e5-963c-32399983d1af.png">

Any ideas?

**Comment by tandrewnichols** [comment]
Oh, I just found this in your FAQ: https://github.com/junegunn/vim-plug/wiki/faq#vim-caught-deadly-signal-segv and indeed `:ruby puts RUBY_VERSION` throws the same error.

**Comment by tandrewnichols** [comment]
Yep, the hint on `rvm use system` when installing vim with homebrew worked. Hey, thanks for listening to my problems! Please don't charge me too much. ;)

**Comment by starcraftman** [comment]
@tandrewnichols Happy you got it working, great that the faq was useful.
