### ISSUE TITLE
"PlugUpdate"  as command line argument in neovim does not show progressbars

### ISSUE THREAD

**Issue by soysal** [junegunn/vim-plug#423]
On Xubuntu 14.04

`nvim +PlugUpdate`

starts the updater, but it does not show progress bars.

**Comment by junegunn** [comment]
Thanks for the report. I can also reproduce the problem with neovim 0.1.2.
@starcraftman can you look into this?

**Comment by starcraftman** [comment]
@junegunn I believe this is a dupe of #278, which has remained broken for a while. If I recall, it has to do with the difference in buffer append() behaviour of the python interface. We decided against a hack to vim-plug, and nobody including myself has yet made a patch to neovim's python interface.

**Comment by junegunn** [comment]
@starcraftman Ah, sure. I forgot about that one.

```vim
:python import vim; vim.current.buffer.append("hello", len(vim.current.buffer))
```

still fails on the latest neovim. Hmm.

**Comment by junegunn** [comment]
Closing as a duplicate of #278.

**Comment by justinmk** [comment]
The python-client repo has been getting some attention lately, though not by me. Things might improve soon.
