### ISSUE TITLE
Nerdtree filetype detection

### ISSUE THREAD

**Issue by tandrewnichols** [junegunn/vim-plug#424]
Your example for defering loading of nerdtree (`Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }`) is nice if you only ever open Nerdtree using the drawer toggle, but if you actually open a directory from the command line (something like `vim foo/bar/baz`), that command is not run. I tried adding `'for': 'nerdtree'` to the config for that (as `set filetype?` reports `nerdtree` in a nerdtree window), but that also did not work. Is there a way to load Nerdtree on a command as per the example AND when the filetype is "nerdtree"?

EDIT:
The filetype for a directory (if nerdtree has not loaded) is `netrw`, but setting `'for': 'netrw'` does not work either. It probably does load Nerdtree, but nerdtree doesn't have a chance to intercept the "file" and open it in its own panel.

**Comment by junegunn** [comment]
Good point.
NERDtree clears the autocmd from netrw and sets up its own when it's loaded:

https://github.com/scrooloose/nerdtree/blob/4ebbb533c3faf2c480211db2b547972bb3b60f2b/plugin/NERD_tree.vim#L162-L167

So in order to have the same behavior while not loading nerdtree upfront, you'll have to set up your own autocmd that does the trick and it's not something vim-plug can easily provide. This seems to do the trick though it's ugly.

```vim
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
augroup nerd_loader
  autocmd!
  autocmd VimEnter * silent! autocmd! FileExplorer
  autocmd BufEnter,VimEnter *
        \  if isdirectory(expand('<amatch>'))
        \|   call plug#load('nerdtree')
        \|   execute 'autocmd! nerd_loader'
        \| endif
augroup END
```

**Comment by tandrewnichols** [comment]
Meh, that doesn't seem significantly uglier than other vim hacks. Thanks, I'll try it out!

**Comment by tandrewnichols** [comment]
Just to follow up (9 months later). That example works fine, although I'm doing:

```
{ 'on': ['NERDTreeToggle', 'NERDTreeFind', 'NERDTree'] }
```

because I have mappings for those commands as well.

**Comment by tandrewnichols** [comment]
I take that back. It works if you open a directory first or if you use one of those commands, but if you're already in vim and you do something like `:e some/directory` or `:vsp some/directory` or `:tabe some/directory` (etc), an empty buffer is loaded. The problem seems to be that Nerdtree is loaded too late because the next time I try to open a directory, it works fine. It's only the first time that it's blank.
