### ISSUE TITLE
Some way to append to the plugin list

### ISSUE THREAD

**Issue by kwstannard** [junegunn/vim-plug#425]
here is a simplification of my current situation.
file_1.vim
```
call plug#begin("/path")
Plug 'floobits/floobits-neovim'
call plug#end()
```
file_2.vim
```
call plug#begin("/path")
Plug 'scrooloose/nerdcommenter'
call plug#end()
```
vimrc
```
source file_1.vim
source file_2.vim
```
I want to have both floobits and nerdcommenter plugins when I start vim, but plug#begin clears the plugin list.

**Comment by Shougo** [comment]
You should like this:

vimrc
```vim
call plug#begin("/path")
source file_1.vim
source file_2.vim
call plug#end()
```

**Comment by kwstannard** [comment]
Nice. Had to make a couple new files, but not too concerned about that.

**Comment by junegunn** [comment]
@Shougo Thanks :)

**Comment by roachsinai** [comment]
But, multiple section support is better.
