### ISSUE TITLE
Add option to track latest tagged release

### ISSUE THREAD

**Issue by vilhalmer** [junegunn/vim-plug#427]
The `tag` Plug option is very nice for being able to use the latest stable release of a plugin. However, it also essentially removes the autoupdate functionality of vim-plug. This is fine if you're using it to stick with a known good version of the plugin, but less good if you're just trying to stay on the latest stable version. Many vim plugins do not have a separate development branch that can be tracked.

Therefore, I suggest the addition of a `track` Plug option, which can be set to always check out the most recent tag, as determined by `git tag --list --sort -version:refname | head -1` (or similar).

The syntax of this command is obviously up to you, perhaps there is a nice way it could be worked in to specify either this or the current behavior (e.g. `'track': 'branch'`, `'track': 'tags'`, etc). This may or may not be a useful way to express this. Alternatively, perhaps some sort of "magic" value of the existing `tag` option could be used, though this seems trickier from a collision standpoint.

Thanks for your consideration!

------------------------------

```
:version
NVIM 0.1.2
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedan
tic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostic
s-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20160211-20191-1u5l9yc/ne
ovim-0.1.2/build/config -I/tmp/neovim20160211-20191-1u5l9yc/neovim-0.1.2/src -I/tmp/neovim20160211-2
0191-1u5l9yc/neovim-0.1.2/deps-build/usr/include -I/tmp/neovim20160211-20191-1u5l9yc/neovim-0.1.2/de
ps-build/usr/include -I/tmp/neovim20160211-20191-1u5l9yc/neovim-0.1.2/deps-build/usr/include/luajit-
2.0 -I/tmp/neovim20160211-20191-1u5l9yc/neovim-0.1.2/deps-build/usr/include -I/tmp/neovim20160211-20
191-1u5l9yc/neovim-0.1.2/deps-build/usr/include -I/tmp/neovim20160211-20191-1u5l9yc/neovim-0.1.2/dep
s-build/usr/include -I/tmp/neovim20160211-20191-1u5l9yc/neovim-0.1.2/deps-build/usr/include -I/usr/l
ocal/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim20160211-20191-1u5l9yc/neovim-0.
1.2/build/src/nvim/auto -I/tmp/neovim20160211-20191-1u5l9yc/neovim-0.1.2/build/include
Compiled by vil@featherweight

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.2/share/nvim"
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [x] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [x] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
Before

![Uploading image.png…]()

**Comment by junegunn** [comment]
Oops, pushed the wrong button.

Before we start the discussion, I want to mention that you can currently see the newer tags with `PlugDiff`.

![](https://cloud.githubusercontent.com/assets/700826/11957194/87e65576-a903-11e5-970f-82ec3bbdb416.png)

But it's understandable that one wants to update the plugins to the latest tags without manual examination. It's not ideal to use "a magic value", but adding another option will make the situation more complex and ambiguous when combined. What should we do on `{'tag': 1.0.0, 'track': 'tags'}`? We should then introduce an arbitrary precedence between the two. So I'm leaning towards the magic-value solution. We can use something like `{'tag': '*'}` since it's not a valid tag name.

**Comment by vilhalmer** [comment]
I like the asterisk solution, a magic value that is guaranteed to never appear in the tag is perfect.

One possible extension would be to allow for something like `{'tag': '1.*'}`, to allow sticking with a semver major version until a potentially breaking upgrade can be manually inspected. However, since that gets into string parsing, I completely understand if you don't want to go down that road, especially since tags don't really have a defined format.

**Comment by junegunn** [comment]
I'll look into this after refactoring the installers. We currently have three versions of installers (vimscript, ruby, and python) that are supposed to work the same and adding a feature means that I have to update all three at the same time. So I'd like to refactor some duplicate logic out of them beforehand.

**Comment by vilhalmer** [comment]
Sounds good, thanks so much!
