### ISSUE TITLE
Add the ability to exclude plugins for filetypes

### ISSUE THREAD

**Issue by blockloop** [junegunn/vim-plug#431]
The negative version of 'for' would be 'not' so I could specify a plugin to *not* load with certain filetypes.

e.g. `Plug 'Valloric/YouCompleteMe', { 'not': 'go' }`

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [x] Feature Request
    - [ ] Question
- OS:
    - [x] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [x] GVim
    - [x] Neovim

**Comment by vheon** [comment]
@blockloop I'm sure you have other use cases for this but why don't you want YouCompleteMe for go?

Also with a configuration like this as soon as you open another filetype, like a markdown file, YCM (or whatever plugin) gets loaded, so I'm not sure how useful this would be :confused:

**Comment by junegunn** [comment]
Please see #383 for why we don't implement the feature.
But if really want, you can set up your own autocmd as described in #63.
