### ISSUE TITLE
autocmd User sometimes doesn't work?

### ISSUE THREAD

**Issue by tony** [junegunn/vim-plug#432]
This is either something that needs more documentation, my mistake (probably worth documenting) or a bug.

I notice sometimes `autocmd User <plug name>` doesn't call.

Take example these plugins: https://github.com/tony/vim-config-framework/commit/5f9466ec140600ab0f5d5d5fc0a8648a931186cd, both [deoplete](https://github.com/Shougo/deoplete.nvim) and [dahu/EditorConfig](https://github.com/dahu/EditorConfig) don't work with `autocmd User ...`.

In cases for plugins like [clang_complete](https://github.com/Rip-Rip/clang_complete), at ([config](https://github.com/tony/vim-config-framework/blob/5f9466ec140600ab0f5d5d5fc0a8648a931186cd/bundles.settings/contrib/clang_complete.vim)), it works fine.

Related: https://github.com/junegunn/vim-plug/issues/382

Is there a one-size-fits-all way to load settings after a plugin is loaded? That is one feature NeoBundle had I really liked.

**Comment by junegunn** [comment]
I see a typo: `deoplete.nvim`.

**Comment by tony** [comment]
Yes, in the example, there was a typo inside of it.

In its current form, I'm trying:

```viml
function StartDeoplete()
    echo 'inside deoplete'
    " deoplete.vim
    " credit: https://gist.github.com/zchee/c314e63ae8b6bea50bb4
    let g:deoplete#enable_at_startup = 1
    set completeopt+=noinsert
    set completeopt-=preview
    let g:deoplete#enable_ignore_case = 'ignorecase'
    let g:deoplete#auto_completion_start_length = 0
    let g:min_pattern_length = 0
    " https://github.com/Shougo/deoplete.nvim/issues/117
    let g:deoplete#omni#input_patterns = {}
    let g:deoplete#omni#input_patterns.html = '<[^>]*'
    let g:deoplete#omni#input_patterns.xml  = '<[^>]*'
    let g:deoplete#omni#input_patterns.md   = '<[^>]*'
    let g:deoplete#omni#input_patterns.css   = '^\s\+\w\+\|\w\+[):;]\?\s\+\w*\|[@!]'
    let g:deoplete#omni#input_patterns.scss   = '^\s\+\w\+\|\w\+[):;]\?\s\+\w*\|[@!]'
    let g:deoplete#omni#input_patterns.sass   = '^\s\+\w\+\|\w\+[):;]\?\s\+\w*\|[@!]'
    let g:deoplete#omni#input_patterns.c = '[^.[:digit:] *\t]\%(\.\|->\)\w*'
    let g:deoplete#omni#input_patterns.cpp = ['[^. *\t]\.\w*', '[^. *\t]\::\w*', '[^. *\t]\->\w*', '[<"].*/']
 
    let g:deoplete#omni#input_patterns.javascript = '[^. \t]\.\%(\h\w*\)\?'
    let g:deoplete#omni#input_patterns.go = '[^.[:digit:] *\t]\.\w*'
    let g:deoplete#omni#input_patterns.ruby = ['[^. *\t]\.\w*', '\h\w*::']

    if !exists('g:spf13_no_neosnippet_expand')
      imap <C-k> <Plug>(neosnippet_expand_or_jump)
      smap <C-k> <Plug>(neosnippet_expand_or_jump)
      xmap <C-k> <Plug>(neosnippet_expand_target)
      smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
      \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

      " For conceal markers.
      if has('conceal')
        set conceallevel=2 concealcursor=niv
      endif
    endif

    let g:deoplete#ignore_sources = {}
    let g:deoplete#ignore_sources._ = ['buffer', 'vim', 'member']
    let g:deoplete#sources#go = 'vim-go'

    inoremap <expr><C-n> deoplete#mappings#manual_complete()
endfunction
```
with both

```viml
autocmd! User deoplete.nvim call StartDeoplete()
```

and

```viml
autocmd! User deoplete call StartDeoplete()
```

**Comment by junegunn** [comment]
`User` autocmd is triggered [only when lazy loading (`on` or `for`) is enabled](https://github.com/junegunn/vim-plug#on-demand-loading-of-plugins). Maybe that is the reason?

So for now you can doing something like this:

```vim
function! s:on_load(name, exec)
  if has_key(g:plugs[a:name], 'on') || has_key(g:plugs[a:name], 'for')
    execute 'autocmd! User' a:name a:exec
  else
    execute 'autocmd VimEnter *' a:exec
  endif
endfunction

call s:on_load('deoplete.nvim', 'call Setup()')
```

But we can reconsider triggering the User autocmd unconditionally even when `for` or `on` is not set if the overhead in startup time turns out to be negligible.

@starcraftman Thoughts?

**Comment by tony** [comment]
The expected behavior (for me) is regardless of a ``for`` or ``on``, however that's out of habit I've grown accustomed to using neovim.

I also have conditionals where I wrap ``if has('nvim')`` and ``if executable('go')``.

I'm fine either way, it simplifies things for me to have autocmd always run, but I can start wrapping in the ``s:on_load`` in case that's a no go. Another idea - if not willing to make ``autocmd`` always load (even without for/on), make a permanent solution for ``s:on_load`` so configs don't break if internal API changes in the future.

**Comment by timgreen** [comment]
`g:plugs` also contains the name of the plugin not yet installed. My expected behavior for `s:on_load` should only execute the command after plugin actually loaded.

@junegunn, do you have any suggestion?

**Comment by junegunn** [comment]
You can filter out plugins that are not installed by checking the directories. `isdirectory(g:plugs[name].dir)`.

Honestly, my suggestion is that you don't try too hard tweaking these settings. I no longer think on-demand loading is a good idea.

https://github.com/junegunn/vim-plug/wiki/faq#when-should-i-use-on-or-for-option
