### ISSUE TITLE
How to now why does a plugin stuck in PlugInstall?

### ISSUE THREAD

**Issue by acgtyrant** [junegunn/vim-plug#433]
```
:version
NVIM 0.1.2
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack
-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.2/src -I/usr/include -I/usr/include -I/usr/include/luajit
-2.0 -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

- Type:
    - [ ] Question
- OS:
    - [ ] Linux
- Vim:
    - [ ] Neovim

I want to Install YCM, I execute `PlugInstall YouCompleteMe`, and clone fine, but it then stuck in `cloning 'third_party/ycmd'...` everytime, I can not intall it successfully. I want to know why does it suck? Thank you!

**Comment by junegunn** [comment]
It's downloading the submodules of YCM, depending on the internet connection, it can take really, really long. Be patient and wait.

You can try using [this version](https://raw.githubusercontent.com/junegunn/vim-plug/refactor-installer/plug.vim) of plug.vim, it'll be easier to see the progress with it.
