### ISSUE TITLE
BUG with multiple syntax and after with vim-syntax-shakespeare

### ISSUE THREAD

**Issue by wolftune** [junegunn/vim-plug#434]
This was working fine, but with new PlugUpgrade I get errors.

My .vimrc has:

    Plug 'pbrisbin/vim-syntax-shakespeare', { 'for': ['hamlet', 'cassius', 'julius', 'haskell'] }

And whenever I open a .hs file (even new blank one), I get this:

```
Error detected while processing /home/aaron/.vim/plugged/vim-syntax-shakespeare/after/syntax/haskell.vim:
line    7:
E121: Undefined variable: b:current_syntax
E15: Invalid expression: b:current_syntax
line    8:
E108: No such variable: "b:current_syntax"
line   54:
E121: Undefined variable: old_syntax
E15: Invalid expression: old_syntax
```

I see several recent changes in the Plug history that could be at fault here. Hope this can be fixed quickly. Thanks

**Comment by junegunn** [comment]
Thanks for the report. It's an exceptional case where the plugin only has `after/syntax/haskell.vim` file without `syntax/haskell.vim`. Using `runtime` command to load the file instead of picking up the file using `globpath` within the plugin directory fixes the issue.
