### ISSUE TITLE
Open the plugins documention from plugin status page

### ISSUE THREAD

**Issue by zamaterian** [junegunn/vim-plug#435]
It would be nice with a shortcut to open the help file/documention for a given plugin. From the PluginStatus page.

/cheers
------------------------------

```

<!-- Check all that apply. -->
- Type:
    - [ ] Bug
    - [X] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ 
X] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x ] Neovim

**Comment by junegunn** [comment]
Thanks for the suggestion, we can currently do this without changing vim-plug like follows:

```vim
function! s:plug_doc()
  let name = matchstr(getline('.'), '^- \zs\S\+\ze:')
  if has_key(g:plugs, name)
    for doc in split(globpath(g:plugs[name].dir, 'doc/*.txt'), '\n')
      execute 'tabe' doc
    endfor
  endif
endfunction

augroup PlugExtra
  autocmd!
  autocmd FileType vim-plug nnoremap <buffer> <silent> H :call <sid>plug_doc()<cr>
augroup END
```

On <kbd>H</kbd>, it will find the name of the plugin on the line, find its directory using `g:plugs` dictionary, and open `doc/*.txt` files in new tabs.

We can consider adding it as one of the default key bindings, but we've tried not to touch the core if it can be done externally. I'll add the above solution to [the wiki page](https://github.com/junegunn/vim-plug/wiki/extra) for now.
