### ISSUE TITLE
Subdirectory Checkouts with git sparse-checkout

### ISSUE THREAD

**Issue by zamaterian** [junegunn/vim-plug#436]
Would it be possible to enable git sparse checkout

the problem :
The vim syntax plugin for DockerFile is included in their main repository. 
It would be very nice to only checkout/clone the relevant subdirectory.

ex:
https://github.com/docker/docker/tree/master/contrib/syntax/vim

This would require an additional syntax for the vim-plug format. 

/Cheers 

------------------------------

```

```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [x] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
Hi, thanks for the suggestion but the topic was discussed in the past (#122), and we decided not to support it as there are few plugins where it really matters and it's much more complicated than I'd like it to be. I mean it's just not worth it to make the code complex just for one or two plugins. For Dockerfile support, there are alternative implementations you might want to check out; see https://github.com/search?utf8=%E2%9C%93&q=docker+vim
