### ISSUE TITLE
Gibberish shows on screen when working directory is removed outside of vim

### ISSUE THREAD

**Issue by mtglsk** [junegunn/vim-plug#439]
Explain the problem here ...

------------------------------

Something like this:

mkdir test
cd test
vim
^z
rm -r ../test/
fg
:PlugUpdate

giberrish shows on screen

- Type:
    - [x ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [x ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x ] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
Thanks, I just updated the code to throw an exception and suspend in that case.
