### ISSUE TITLE
Why ~/.vim/plugged instead of the widely used ~/.vim/bundle?

### ISSUE THREAD

**Issue by jooize** [junegunn/vim-plug#440]
> Since all the other major plugin managers store plugins in "bundle" directory, you might want to pass it to plug#begin() if you do not wish to reinstall plugins.

— https://github.com/junegunn/vim-plug/wiki/faq#migrating-from-other-plugin-managers

Why not just only use `~/.vim/bundle`?

**Comment by junegunn** [comment]
Using the same directory implies that vim-plug is compatible with the others. For now, it is true, but it wasn't so in the past. And with no promise of compatibility, I can freely try different things in the future
