### ISSUE TITLE
On-demand Loading Plugins

### ISSUE THREAD

**Issue by tleish** [junegunn/vim-plug#441]
When using a plugin, how can I search the plugins vim code to identify the correct command or sytnax to use in dynamic loading?

BACKGROUND

I'm trying to use On-demand loading of the NERDCommenter plugin

```vim
call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdcommenter', { 'on':  'NERDCommenterToggle' }
call plug#end()
```

And then I have the following key binding to invoke NERDCommenterToggle

```vim
" NERDCommenterToggle
nmap <D-/> <Plug>NERDCommenterToggle<CR>
vmap <D-/> <Plug>NERDCommenterToggle<CR>
```

However, the dynamic on-demand loading is not loading the plugin (based on behavior and ```:PlugStatus```).  With removing ```, { 'on':  'NERDCommenterToggle' }```, everything works as expected.

------------------------------

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct 25 2013 20:05:26)
MacOS X (unix) version
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [X] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [X] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [X] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
Try this
```vim
{ 'on': '<Plug>NERDCommenterToggle' }
```

**Comment by tleish** [comment]
@junegunn: Thanks for the quick response.  I had originally tried using <Plug>:

```vim
call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdcommenter', { 'on':  '<Plug>NERDCommenterToggle' }
call plug#end()
```

Then when invoking the keymap, I get a bunch of errors.  So, I thought I was doing it wrong or it's not possible because of the way the plugin was authored.

```
Error detected while processing function NERDComment..<SNR>38_IsInSexyComment..<SNR>38_FindBoundingLinesOfSexyCom..<SNR>38_Multipart..<SNR>38_Right:
line    3:
E121: Undefined variable: b:NERDCommenterDelims
E15: Invalid expression: has_key(params, 'alt') ? b:NERDCommenterDelims['rightAlt'] : b:NERDCommenterDelims['right']
line    5:
E121: Undefined variable: delim
E15: Invalid expression: delim == ''
line   17:
E121: Undefined variable: delim
E15: Invalid expression: delim
Error detected while processing function NERDComment..<SNR>38_IsInSexyComment..<SNR>38_FindBoundingLinesOfSexyCom..<SNR>38_AltMultipart:
line    1:
E121: Undefined variable: b:NERDCommenterDelims
E15: Invalid expression: b:NERDCommenterDelims['rightAlt'] != ''
Error detected while processing function NERDComment..<SNR>38_Left:
line    3:
E121: Undefined variable: b:NERDCommenterDelims
E15: Invalid expression: has_key(params, 'alt') ? b:NERDCommenterDelims['leftAlt'] : b:NERDCommenterDelims['left']
line    5:
E121: Undefined variable: delim
E15: Invalid expression: delim == ''
line   17:
E121: Undefined variable: delim
E15: Invalid expression: delim
line    3:
E121: Undefined variable: b:NERDCommenterDelims
E15: Invalid expression: has_key(params, 'alt') ? b:NERDCommenterDelims['leftAlt'] : b:NERDCommenterDelims['left']
line    5:
E121: Undefined variable: delim
E15: Invalid expression: delim == ''
line   17:
E121: Undefined variable: delim
E15: Invalid expression: delim
Error detected while processing function NERDComment..<SNR>38_CommentLinesToggle..<SNR>38_CanToggleCommentLine..<SNR>38_Left:
line    3:
E121: Undefined variable: b:NERDCommenterDelims
E15: Invalid expression: has_key(params, 'alt') ? b:NERDCommenterDelims['leftAlt'] : b:NERDCommenterDelims['left']
line    5:
E121: Undefined variable: delim
E15: Invalid expression: delim == ''
line   17:
E121: Undefined variable: delim
E15: Invalid expression: delim
...
```

**Comment by junegunn** [comment]
> it's not possible because of the way the plugin was authored

Hmm, I guess so. Some plugins don't work with on-demand loading, and there's not much we can do about it. I wouldn't bother. And I personally recommend [tpope's plugin](https://github.com/tpope/vim-commentary).

**Comment by tleish** [comment]
Is there a way to use an on keymap to load a plugin?

```vim
Plug 'scrooloose/nerdtree', { 'on':  '<D-/>' }
```
Not only would the keymap load the plugin, but it would also pass it along to the plugin?

**Comment by junegunn** [comment]
Only supports `<Plug>something`, not arbitrary key sequences. But theoretically you can do anything with `plug#load` function and custom mappings. But don't try too hard. I'd like to stress that on-demand loading facility of vim-plug (or any other plugin manager) is just a workaround for plugins that are not carefully designed. It's best to fix those plugins.

Anyway this is how I load NERDtree (related: #424):

```vim
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
augroup nerd_loader
  autocmd!
  autocmd VimEnter * silent! autocmd! FileExplorer
  autocmd BufEnter,BufNew *
        \  if isdirectory(expand('<amatch>'))
        \|   call plug#load('nerdtree')
        \|   execute 'autocmd! nerd_loader'
        \| endif
augroup END

nnoremap <F10> :NERDTreeToggle<cr>
```
