### ISSUE TITLE
Idea: variable to disable registration of plugin

### ISSUE THREAD

**Issue by mikew** [junegunn/vim-plug#442]
It would be cool if vim-plug checked the name against a list of "disabled" plugins, and if the name is included, simply do nothing in `s:Plug()`.

The idea being if people use vim-plug in their distributions (janus, spf-13, dotvim, etc), they wouldn't all need to write their own disabling logic.

Basically:

```vim
" This would be in the users' vimrc
let g:plugs_disabled = ['nerdtree']

" This would be somewhere in the distribution, not controlled by the user
Plug 'scrooloose/nerdtree'
Plug 'mileszs/ack.vim'

" NERDTree won't be installed or loaded
```

------------------------------

- Type:
    - [ ] Bug
    - [x] Enhancement
    - [x] Feature Request
    - [ ] Question
- OS:
    - [x] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [x] GVim
    - [x] Neovim

**Comment by vheon** [comment]
Personally I don't see the use case :confused:

**Comment by mikew** [comment]
It's more for users and maintainers of vim distributions.

Hypothetical use case: I use `$VimDistrib`, which includes `neocomplete`, `vim-rails` and `vim-vroom`. I will never use these, but `$VimDistrib` has no way of disabling them aside from editing files (that will be overridden next time updated).

Now `$VimDistrib` could write a `disable_plugin(...)` function, but then `$OtherDistrib` would have to write one as well, and so on and so on.

**Comment by vheon** [comment]
With vim-plug configurability has always been "external" so you would do the logic around vim-plug's primitives (like `Plug`). What you're asking is similar to #137.

**Comment by mikew** [comment]
Similar, yeah. But that issue is for when you control the vimrc, and mine is for when you don't. Also, this solution would allow that reporter to use a single list of plugins and manipulate `g:plugs_disabled` based on his environment.

Anyways, [this is what I've come up with](https://gist.github.com/mikew/5b8c00e6b896951e1f4e), but it relies on `g:plugs` and `g:plugs_order` being global, which could change in the future.

**Comment by junegunn** [comment]
Thanks for the suggestion, but however, to me it clealy looks like a responsibility of each distribution. As you might have noticed while coming up with your own solution, implementing the blacklist is easy and requires just a few lines of Vimscript, so I wouldn't worry too much about the duplicate effort. `g:plugs` is not going away, but it can be done in different ways without having to rely on the variable. e.g. defining a command that conditionally executes `Plug` command; `MyPlug 'foo/bar', {'baz': 1}`

And to be honest, I believe "Vim distribution" is a bad practice and I wouldn't add a feature that I don't need just for the ease of development of those distributions.
