### ISSUE TITLE
weird startup behavior when Plug'ing vim-airline and using if-block

### ISSUE THREAD

**Issue by stevenpollack** [junegunn/vim-plug#443]
I searched and couldn't find anything for this prior. I've noticed that there seems to be some issues with neovim running code in an `if` block, when `vim-airline` is being `Plug`d. Here's a minimal example that you can see with
```bash
nvim -u test.vim test.vim
```
```vim
" test.vim
call plug#begin()
" airline plugin + themes
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes' 
call plug#end()

if 2
  echo "in block"
  colorscheme blue
endif

" airline settings
if exists(":AirlineRefresh")
  echo "entered block"
  set laststatus=2
  colorscheme elflord
  let g:airline#extensions#tabline#enabled = 1
  let g:airline_powerline_fonts = 1 
  let g:airline_theme='luna'
endif 
```
Running `nvim -u test.vim test.vim` ***should*** result in two echo'd statements in the terminal; however, you just see one:
```
$ nvim -u test.vim test.vim
in block
Press ENTER or type command to continue
```
Furthermore, if you run `:source test.vim` and then change to insert move, everything seems to be properly evaluated.
- before `:source`:

![started](https://cloud.githubusercontent.com/assets/2607235/13611358/6de29338-e562-11e5-9831-ea2d2ddde657.png)
- after `:source`: 

    ![after_source](https://cloud.githubusercontent.com/assets/2607235/13611374/7f580d14-e562-11e5-8112-5daac38058c0.png)

------------------------------

```
NVIM 0.1.3-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-UlDudH/neovim-0.1.2ubuntu1+git201603052300+2355+17~ubuntu15.10.1/build/config -I/build/neovim-UlDudH/neovim-0.1.2ubuntu1+git201603052300+2355+17~ubuntu15.10.1/src -I/build/neovim-UlDudH/neovim-0.1.2ubuntu1+git201603052300+2355+17~ubuntu15.10.1/.deps/usr/include -I/build/neovim-UlDudH/neovim-0.1.2ubuntu1+git201603052300+2355+17~ubuntu15.10.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/neovim-UlDudH/neovim-0.1.2ubuntu1+git201603052300+2355+17~ubuntu15.10.1/.deps/usr/include -I/build/neovim-UlDudH/neovim-0.1.2ubuntu1+git201603052300+2355+17~ubuntu15.10.1/.deps/usr/include -I/build/neovim-UlDudH/neovim-0.1.2ubuntu1+git201603052300+2355+17~ubuntu15.10.1/.deps/usr/include -I/build/neovim-UlDudH/neovim-0.1.2ubuntu1+git201603052300+2355+17~ubuntu15.10.1/.deps/usr/include -I/usr/include -I/build/neovim-UlDudH/neovim-0.1.2ubuntu1+git201603052300+2355+17~ubuntu15.10.1/build/src/nvim/auto -I/build/neovim-UlDudH/neovim-0.1.2ubuntu1+git201603052300+2355+17~ubuntu15.10.1/build/include
Compiled by buildd@lgw01-31

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
`echom exists(":AirlineRefresh")` to check if the condition is true. It is false, right? Because plugins are loaded *after* your vimrc is processed (see `:help startup`).

You might want to defer the execution of block to `VimEnter` event. Or you can alternatively check if the plugin is installed like follows:

```vim
if isdirectory(g:plugs['vim-airline'].dir)
  " ...
endif
```

Does this answer your question?

**Comment by stevenpollack** [comment]
The `isdirectory` snippet totally works. How do I defer execution to a `VimEnter` event, though?

**Comment by junegunn** [comment]
Using `autocmd`. Consult vim help page for more info.

**Comment by stevenpollack** [comment]
Right on, thanks!

**Comment by stevenpollack** [comment]
Head's up, I just wanted to let you know, doing something like
```vim
function! SetupAirline()
    let airline_theme = 'luna'
    " more stuff
endfunction

au VimEnter * call SetupAirline()
```
Has some funky behaviour that results in errors being thrown. I'm not sure whether this is due to `vim-plug` or `vim-airline`, but I figure I'd follow up here, just in case.
