### ISSUE TITLE
Plugins may not be loaded because of 'for' option

### ISSUE THREAD

**Issue by Shaac** [junegunn/vim-plug#444]
Hello,

I have a plugin activated only for cpp files. So it set `for: 'cpp'`. It works well in most cases except the following.

If I launch `nvim` without argument, then do `:e file.cpp`, the plugin in not loaded. If I do `nvim file.cpp` it works fine.

I’m not sure if it should be a bug or an improvement.

------------------------------

```
NVIM
0.1.3-dev
 
Build type:

RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -
D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer
-size=4 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-u9LuGn/neovim-0.1.2ubuntu1+git201603052300+2355+17~ubuntu14.04.1/build/c
onfig -I/build/neovim-u9LuGn/neovim-0.1.2ubuntu1+git201603052300+2355+17~ubuntu14.04.1/src -I/build/neovim-u9LuGn/neovim-0.1.2ubuntu1+git201603052300+2355+17~u
buntu14.04.1/.deps/usr/include -I/build/neovim-u9LuGn/neovim-0.1.2ubuntu1+git201603052300+2355+17~ubuntu14.04.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/
build/neovim-u9LuGn/neovim-0.1.2ubuntu1+git201603052300+2355+17~ubuntu14.04.1/.deps/usr/include -I/build/neovim-u9LuGn/neovim-0.1.2ubuntu1+git201603052300+2355
+17~ubuntu14.04.1/.deps/usr/include -I/build/neovim-u9LuGn/neovim-0.1.2ubuntu1+git201603052300+2355+17~ubuntu14.04.1/.deps/usr/include -I/build/neovim-u9LuGn/n
eovim-0.1.2ubuntu1+git201603052300+2355+17~ubuntu14.04.1/.deps/usr/include -I/usr/include -I/build/neovim-u9LuGn/neovim-0.1.2ubuntu1+git201603052300+2355+17~ub
untu14.04.1/build/src/nvim/auto -I/build/neovim-u9LuGn/neovim-0.1.2ubuntu1+git201603052300+2355+17~ubuntu14.04.1/build/include
Compiled by buildd@lgw01-10
```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
Which plugin?

**Comment by Shaac** [comment]
The plugin is 'YouCompleteMe'.
I plug it with `Plug 'Valloric/YouCompleteMe', { 'do': './install.py --clang-completer', 'for': 'cpp' }`.

**Comment by vheon** [comment]
`YouCompleteMe` cannot be loaded with the `for` option because it does some initialization on `VimEnter`, so you have to load it manually. Something like:

```viml
Plug 'Valloric/YouCompleteMe', { 'on': [] }

augroup load_ycm
  autocmd!
  autocmd FileType cpp call plug#load('YouCompleteMe')
                     \| call youcompleteme#Enable() | autocmd! load_ycm
augroup END
```

**Comment by junegunn** [comment]
You can find the recommended setup here:
https://github.com/junegunn/vim-plug#on-demand-loading-of-plugins

**Comment by Shaac** [comment]
I did not though it could be plugin specific.

Thanks for the solution, and sorry for wasting your time.
