### ISSUE TITLE
Vim-plug should quit when it's the last open window

### ISSUE THREAD

**Issue by mtglsk** [junegunn/vim-plug#448]
---

Currently when you close all other windows (while vim-plug is still visible), you need to issue another `:q` to quit. It's superfluous, because there is no risk of losing any data, so generally i think vim should quit when vim-plug is the last buffer / window (like some other plugins do already, for example, undotree).

```
head
```

- Type:
  - [ ] Bug
  - [ ] Enhancement
  - [x] Feature Request
  - [ ] Question
- OS:
  - [x] All/Other
  - [ ] Linux
  - [ ] OS X
  - [ ] Windows
- Vim:
  - [x] Terminal Vim
  - [ ] GVim
  - [ ] Neovim

**Comment by junegunn** [comment]
I think the case of vim-plug is different from that of undotree in the respect that undotree does not make any sense without its host buffer, but the buffer of vim-plug is independent in itself.

**Comment by Aluriak** [comment]
I had the habit to launch a vim session just for plugins update. Consequently, i was also running into that superfluous `:q`.
My solution is the following:

    alias vu='vim -c PlugUpgrade -c PlugUpdate -c qa'

Note that it's the apocalypse in case of errors.
