### ISSUE TITLE
Put the plugin into the autoload folder.

### ISSUE THREAD

**Issue by Yggdroot** [junegunn/vim-plug#449]
I think it's better to put the plugin into the autoload folder.
The advantage is:
 1. It's easier to migrate from another plugin manager. For example, I am using Vundle, I can install this plugin by adding `Plugin 'junegunn/vim-plug'`  instead of using `curl `, then I can manage plugin using vim-plug.
 2. The plugin can manage itself easily by `Plug 'junegunn/vim-plug'`.

------------------------------

```

```

- Type:
    - [ ] Bug
    - [x] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
Thanks, but moving it will break [thousands of scripts people use](https://github.com/search?utf8=%E2%9C%93&q=curl+junegunn%2Fplug.vim&type=Code&ref=searchresults). Actually this was suggested many times in the past but we decided that it's not worth the trouble. After all, vim-plug was not designed to be completely compatible with Vundle.

See this page for more info: https://github.com/junegunn/vim-plug/wiki/faq#shouldnt-vim-plug-update-itself-on-plugupdate-like-vundle
You can simply symlink `plug.vim` to `autoload` directory if you really want.

**Comment by Yggdroot** [comment]
What a pity! 
OK, I fork one and put it into `autoload` in my use.
