### ISSUE TITLE
:PlugUpdate stopped working in OSX/Yosemite 10.10.5 - ruby 2.3.0preview1

### ISSUE THREAD

**Issue by jm3** [junegunn/vim-plug#458]
This is likely *not* a `vim-plug` bug, but maybe someone here can point me in the right direction to fixing my ruby-vim setup? In OSX/Yosemite 10.10.5, **:PlugUpdate** no longer works for me (**:PlugUpgrade** works.) I assume it's something related to rvm, but I have no other ruby issues except in VIM: ruby + rvm/gems work fine outside of vim.

```bash
➜ git --version
git version 2.6.4

➜ gem --version
2.5.0

➜ rvm list
rvm rubies
   ruby-1.9.3-p194 [ x86_64 ]
   ruby-2.0.0-p451 [ x86_64 ]
   ruby-2.0.0-p576 [ x86_64 ]
   ruby-2.1.2 [ x86_64 ]
   ruby-2.1.3 [ x86_64 ]
   ruby-2.1.5 [ x86_64 ]
   ruby-2.2.3 [ x86_64 ]
=* ruby-2.3.0-preview1 [ x86_64 ]

➜ ruby --version
ruby 2.3.0preview1 (2015-11-11 trunk 52539) [x86_64-darwin14]
```

from within vim:
```vim
:ruby puts RUBY_VERSION
<internal:gem_prelude>:1:in `require': cannot load such file -- rubygems.rb (LoadError)
from <internal:gem_prelude>:1:in `<compiled>'
```

(:PlugUpdate reports the same error.)

do i need to recompile vim each time I `rvm install` new rubies? :cry:

**Comment by junegunn** [comment]
Building Vim against the system default Ruby will do:

```
rvm use system
brew reinstall vim
```

**Comment by jm3** [comment]
that worked perfectly. i saw this in #422 but i didn't realize that it was the same problem. sorry / thanks!

also thanks for making releasing so many great vim. plugins. I love Plug and Limelight and Easy-Align,  all super useful to me.

**Comment by junegunn** [comment]
Thanks. I think I'm going to update the wiki page or even consider putting it on the README page.
