### ISSUE TITLE
The RETRY tip remains after a success retry.

### ISSUE THREAD

**Issue by winsphinx** [junegunn/vim-plug#459]
Explain the problem here ...
After the recent update, there's a bug: when use PlugUpdate to update the plugins and some of them fail, the tip "Press 'R' to retry, and press 'D' to..." appears as before, but if press R to retry and success, the tip remains "Press 'R' to retry, and press 'D' to ...", while before the update, the tip is only "Press 'D' to ...".

------------------------------

```

```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [x] Windows
- Vim:
    - [x] Terminal Vim
    - [x] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
Thanks, I'll look into it.

**Comment by junegunn** [comment]
Should be fixed now, thanks for the report.

**Comment by winsphinx** [comment]
Sorry for the delayed reply, because till today I met the retry case.
That commit fixed that bug, but a new one is out - Now, after the retry case and then success, the 'D' message lost. (as before a 'D' message should be shown)

**Comment by junegunn** [comment]
Thanks for letting me know, but I don't see it as a bug. `R` will start a new installer and it does not remember the result of the previous installer.
