### ISSUE TITLE
Fall back to Python installer when Ruby interface is broken

### ISSUE THREAD

**Issue by junegunn** [junegunn/vim-plug#460]
We are steadily receiving inquiries from the unfortunate RVM users who ended up having Vim with broken Ruby interface. The correct solution for them is to reinstall Vim with system default Ruby, but we might as well just fall back to Python installer when broken Ruby does not crash Vim.

**Comment by jm3** [comment]
smart, good idea.

**Comment by starcraftman** [comment]
Makes sense, shame so many people getting RVM issues.
