### ISSUE TITLE
A way to reload a plugin without restarting vim

### ISSUE THREAD

**Issue by sassanh** [junegunn/vim-plug#461]
Is there anyway I can reload a plugin when I edit its files without restarting vim?

------------------------------

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [x] Feature Request
    - [ ] Question
- OS:
    - [x] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by vheon** [comment]
if you re-source your vimrc it should work I think... but if you had in your plugin something like `let g:myvariable = 1` and you remove the definition in your plugin it will not go away unless you `unlet g:myvariable` by hand.

**Comment by junegunn** [comment]
Yeah, resourcing vimrc will definitely do, or you can use `:call fzf#load(PLUGIN_NAME)` to reload a single plugin. However, most plugins have [guard variables](https://github.com/tpope/vim-fugitive/blob/57afba5bdd49b59d57485f90aa0cf3f3a6c47f63/plugin/fugitive.vim#L6-L9) so reloading will have no effect unless you unlet such variable. Vim does not enforce any naming rule in variables so you have to read the source to look for it.

**Comment by vheon** [comment]
> or you can use :call fzf#load(PLUGIN_NAME)

Did you mean `plug#load(PLUGIN_NAME)`?

> However, most plugins have guard variables so reloading will have no effect unless you unlet such variable. Vim does not enforce any naming rule in variables so you have to read the source to look for it.

I didn't thought of that. Anyway if someone want to experiment with something there's `Disarm` in [tpope/vim-scriptease](/tpope/vim-scriptease)

**Comment by sassanh** [comment]
@junegunn thanks for info, restarting vim is indeed faster and more reasonable solution than reading the source and unletting all variables. But I guess `:call [fz|plug]#load(PLUGIN_NAME)` will help. I think sourcing vimrc does not re-let variables to new values, I should try it more precisely.

@vheon Everything in vim reaches to tpope somehow. You want to launch a rocket? tpope has a plugin for it!

**Comment by junegunn** [comment]
@vheon 

> Did you mean plug#load(PLUGIN_NAME)?

Oops. Yeah, of course. Disarm should be useful in most cases though [the implementation](https://github.com/tpope/vim-scriptease/blob/master/plugin/scriptease.vim#L335-L356) looks a bit fragile.

**Comment by thorlucas** [comment]
This appears to not actually reload the autoload files?
