### ISSUE TITLE
VimPlug Update not updating?

### ISSUE THREAD

**Issue by FuzzOli87** [junegunn/vim-plug#464]
I usually update neovim every day. For the last few days, there hasn't been a single Plug upgrade which is extremely weird. There is almost always an update to some plugin. How can I verify this? Does this sound normal?

NVIM v0.1.2-324-gbcbcf23
Build type: Release
Compilation: /usr/lib/hardening-wrapper/bin/cc -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/home/fuzz/neovim/build/config -I/home/fuzz/neovim/src -I/home/fuzz/neovim/.deps/usr/include -I/home/fuzz/neovim/.deps/usr/include -I/home/fuzz/neovim/.deps/usr/include/luajit-2.0 -I/home/fuzz/neovim/.deps/usr/include -I/home/fuzz/neovim/.deps/usr/include -I/home/fuzz/neovim/.deps/usr/include -I/home/fuzz/neovim/.deps/usr/include -I/usr/include -I/home/fuzz/neovim/build/src/nvim/auto -I/home/fuzz/neovim/build/include
Compiled by fuzz@satsuki

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x ] Question
- OS:
    - [ ] All/Other
    - [x ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [ x] Neovim

**Comment by starcraftman** [comment]
@FuzzOli87 Hi. The easiest way would be to use a for loop and fetch the origin master and compare. All vim-plug does is execute git commands so it shouldn't suddenly stop working unless something on the system changed.

For example, if your plugins are in: `~/.vim/plugged` something like this would quickly show if origin differs from current master.

```bash
ORIG=$(pwd)
for repo in ~/.vim/plugged/*; do
    cd $repo
    git fetch origin
    git log master..origin/master
done
cd $ORIG
```

If any logs are shown, then we can confirm a problem.

**Comment by junegunn** [comment]
My guess is that it was just a coincidence. Let us know if you still have the issue.
