### ISSUE TITLE
:PlugInstall - fatal: could not read Username for 'https://github.com': terminal prompts disabled

### ISSUE THREAD

**Issue by ashee** [junegunn/vim-plug#465]
When I invoke :PlugInstall, it fails as follows

x vim-go:
    Cloning into '/Users/amitava/.config/nvim/plugged/vim-go'...
    fatal: could not read Username for 'https://github.com': terminal prompts disabled

------------------------------

```
NVIM v0.1.4-17-g91c5005
Build type: Release
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20160410-30535-yuuit1/build/config -I/tmp/neovim20160410-30535-yuuit1/src -I/tmp/neovim20160410-30535-yuuit1/deps-build/usr/include -I/tmp/neovim20160410-30535-yuuit1/deps-build/usr/include -I/tmp/neovim20160410-30535-yuuit1/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20160410-30535-yuuit1/deps-build/usr/include -I/tmp/neovim20160410-30535-yuuit1/deps-build/usr/include -I/tmp/neovim20160410-30535-yuuit1/deps-build/usr/include -I/tmp/neovim20160410-30535-yuuit1/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim20160410-30535-yuuit1/build/src/nvim/auto -I/tmp/neovim20160410-30535-yuuit1/build/include
```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [x] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
My guess is you have a typo in the argument. Please post plug section of your configuration.

**Comment by ashee** [comment]
Here is .vimrc section
```
call plug#begin()
Plug 'rking/ag.vim'
Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': 'yes \| ./install' }
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'junegunn/vim-easy-align'
Plug 'easymotion/vim-easymotion'
Plug 'wting/rust.vim'
Plug 'Valloric/YouCompleteMe'
Plug 'rizzatti/dash.vim'
Plug 'faith/vim-go'
call plug#end()
```
Here is the output from :PlugUpdate
```
Updated. Elapsed time: 1.209827 sec.
[x===========]

- Finishing ... Done!
- ultisnips: Already up-to-date.
- fzf: Already up-to-date.
x vim-go:
    Cloning into '/Users/amitava/.config/nvim/plugged/vim-go'...
    fatal: could not read Username for 'https://github.com': terminal prompts disabled
- vim-easy-align: Already up-to-date.
- dash.vim: Already up-to-date.
- vim-commentary: Already up-to-date.
- vim-surround: Already up-to-date.
- vim-easymotion: Already up-to-date.
- vim-snippets: Already up-to-date.
- ag.vim: Already up-to-date.
- YouCompleteMe: Already up-to-date.
- rust.vim: Already up-to-date.
```

**Comment by junegunn** [comment]
That confirms my suspicion; it's `fatih` not `faith`.

**Comment by Zeroman** [comment]
use ```   Plug 'scrooloose/nerdcommenter' ``` instead of ```Plug 'scrooloose/nerdcommenter.git'```
it will be ok.

**Comment by nestawei** [comment]
> That confirms my suspicion; it's `fatih` not `faith`.
> 
> Try `git clone https://github.com/no-such/repo.git`, git will ask for username and password in case it's a private repository. To suppress the prompt, vim-plug sets `$GIT_TERMINAL_PROMPT` to 0.

when I Try  `git clone https://github.com/no-such/repo.git`, terminal prompt me :
remote: Repository not found.
fatal: repository 'https://github.com/no-such/repo.git/' not found

how 。。。

**Comment by mkx000** [comment]
> My guess is you have a typo in the argument. Please post plug section of your configuration.
Thanks for providing us with such awesome software!
