### ISSUE TITLE
Question: Dealing with huge repos

### ISSUE THREAD

**Issue by ahmedelgabri** [junegunn/vim-plug#466]
For example Apple has vim plugin for swift inside the [swift repo](https://github.com/apple/swift/tree/master/utils/vim) but of course I don't want to pull the whole repo on updates, etc... so is there is a way to handle this properly with vim-plug? something like `git clone --depth 1` or something?

**Comment by junegunn** [comment]
vim-plug already clones with `--depth 1` unless otherwise specified. Maybe what you have in mind is sparse checkout, which we previously discussed and decided not to do it because of its complexity.

You might want to use something like https://github.com/keith/swift.vim instead.

**Comment by ahmedelgabri** [comment]
> vim-plug already clones with --depth 1 unless otherwise specified.

Cool, I didn't know this.

 > You might want to use something like https://github.com/keith/swift.vim instead.

I tried it but the Apple one seems better to me.

Thanks for your answer and your amazing vim work :+1:
