### ISSUE TITLE
Polyglot compatibility

### ISSUE THREAD

**Issue by joaoponceleao** [junegunn/vim-plug#468]
This is a note to an issue that I think should be, either taken care of by vim-plug, or added to the faq, as the workaround is quite easy.
Polyglot (https://github.com/sheerun/vim-polyglot), which is quite a handy plugin, has issues with the way vim-plug loads the plugin. The workaround, is to configure its settings before loading vim-plug. Nothing huge, but a bit unexpected, and perhaps other plugins that have to check the filetype suffer from the same issue?

Link to issue in polyglot:
https://github.com/sheerun/vim-polyglot/issues/108

------------------------------

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr  5 2016 12:50:11)
MacOS X (unix) version
Included patches: 1-1707
Compiled by Homebrew
```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [x] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
I'm pretty certain that it's something vim-polyglot should address as vim-plug is not doing anything non-standard. Vim loads files in ftdetect directories on `filetype plugin on` (which is done by `plug#end()`), so you have the same issue with the following minimal vimrc without vim-plug:

```vim
set nocompatible
set rtp+=~/.vim/plugged/vim-polyglot
filetype plugin indent on
syntax enable
```

And you have to make sure that the variable comes before `filetype` line. The plugin can be fixed to refer to the variable when the file is open not on vim startup, so I would say it's a limitation of the current implementation.

**Comment by joaoponceleao** [comment]
> And you have to make sure that the variable comes before filetype line.
I see... I did notice that the problem did not exist if the file was already open on startup.
Thanks.
