### ISSUE TITLE
Misleading errors about vim-plug on :PlugUpdate

### ISSUE THREAD

**Issue by qstrahl** [junegunn/vim-plug#470]
I have vim-plug managing itself as a plugin. When I run `:PlugUpdate`, I get this output:

```
x vim-plug:
    master
    PlugClean required.
```

All the other plugins are fine. Running `:PlugClean` does not solve the issue. What is happening?
Here is the relevant section of my vimrc:

```viml
let confdir = expand('<sfile>:h')
source ~/.config/nvim/vim-plug/plug.vim
call plug#begin(confdir . '/bundle')

Plug 'junegunn/vim-plug', { 'dir': confdir. '/vim-plug' }
"" ( lots more plugins, snipped for space... )

call plug#end()
```

------------------------------

```
NVIM 0.1.4-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prot
otypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-FDBOmC/neovim-0.1.2ubuntu1+git201604111702+2397+17~ubuntu15.10.1/build/config -I/build
/neovim-FDBOmC/neovim-0.1.2ubuntu1+git201604111702+2397+17~ubuntu15.10.1/src -I/build/neovim-FDBOmC/neovim-0.1.2ubuntu1+git201604111702+2397+17~ubuntu15.10.1/.deps/usr/include -I/build/neovim-FDBOmC/neovim-0.1.2ubuntu1+git201604111702+2397
+17~ubuntu15.10.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/neovim-FDBOmC/neovim-0.1.2ubuntu1+git201604111702+2397+17~ubuntu15.10.1/.deps/usr/include -I/build/neovim-FDBOmC/neovim-0.1.2ubuntu1+git201604111702+2397+17~ubuntu15.10
.1/.deps/usr/include -I/build/neovim-FDBOmC/neovim-0.1.2ubuntu1+git201604111702+2397+17~ubuntu15.10.1/.deps/usr/include -I/build/neovim-FDBOmC/neovim-0.1.2ubuntu1+git201604111702+2397+17~ubuntu15.10.1/.deps/usr/include -I/usr/include -I/bu
ild/neovim-FDBOmC/neovim-0.1.2ubuntu1+git201604111702+2397+17~ubuntu15.10.1/build/src/nvim/auto -I/build/neovim-FDBOmC/neovim-0.1.2ubuntu1+git201604111702+2397+17~ubuntu15.10.1/build/include
Compiled by buildd@lcy01-07

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
What does `:PlugStatus` say?

**Comment by qstrahl** [comment]
Same thing. Every plugin is `OK` except for vim-plug, which is exactly the same as above.

**Comment by junegunn** [comment]
Go to the directory, execute the following commands and let me know of their output:

```sh
git rev-parse --abbrev-ref HEAD 2>&1
echo $?
git config -f .git/config remote.origin.url
echo $?
```

**Comment by qstrahl** [comment]
```
~/dotfiles/nvim/.config/nvim (master*) $ git rev-parse --abbrev-ref HEAD 2>&1
master
~/dotfiles/nvim/.config/nvim (master*) $ echo $?
0
~/dotfiles/nvim/.config/nvim (master*) $ git config -f .git/config remote.origin.url
~/dotfiles/nvim/.config/nvim (master*) $ echo $?
1
```

I think I see the issue, now; vim-plug assumes that `.git/config` will be the location of the git config. My vim config is a git submodule of my greater dotfiles config, so this is not the case.

**Comment by qstrahl** [comment]
I'm pretty sure you can fix this simply by removing `-f .git/config` from the arguments you pass to `git config`. Is there a reason for doing this that I'm not seeing?

**Comment by junegunn** [comment]
Yes, see #455. vim-plug is not designed to manage submodules as plugins so I'm not going to merge your PR. Also take a look at https://github.com/junegunn/vim-plug/wiki/faq#shouldnt-vim-plug-update-itself-on-plugupdate-like-vundle

**Comment by qstrahl** [comment]
@junegunn I see. I need to be able to clone my vim config easily from any new machine I need to set up; if I can't include vim-plug a a submodule of my vim config, how would you recommend I accomplish this?

**Comment by junegunn** [comment]
1. I have installer script in my dotfiles repo that downloads plug.vim
2. https://github.com/junegunn/vim-plug/wiki/faq#automatic-installation
3. Include plug.vim directly in your repo. It's just a single file. vim-plug has been extremely stable and frequent upgrade is in my opinion not really necessary.

**Comment by qstrahl** [comment]
All right. Thanks for the help!
