### ISSUE TITLE
Cloning over SSH using keys with passphrases

### ISSUE THREAD

**Issue by siddharthist** [junegunn/vim-plug#472]
In my global git config, I have 
```
[url "ssh://git@github.com/"]                                                   
    insteadOf = https://github.com/ 
```
When I run `:PlugInstall` to get a new plugin, I intermittently am asked for the passphrase to my SSH key. When this happens, it is also impossible to enter said key correctly. I have to change the above lines in my gitconfig to prevent this. Is there a way that vim-plug could handle cloning over ssh with a passphrase protected key? 
```
NVIM v0.1.2-483-g827e267
Build type: Debug
Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter
-Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto
-DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/home/siddharthist/Dropbox/code/misc
/clones/neovim/build/config -I/home/siddharthist/Dropbox/code/misc/clones/neovim/src -I
/home/siddharthist/Dropbox/code/misc/clones/neovim/.deps/usr/include -I/home/siddharthi
st/Dropbox/code/misc/clones/neovim/.deps/usr/include -I/home/siddharthist/Dropbox/code/
misc/clones/neovim/.deps/usr/include/luajit-2.0 -I/home/siddharthist/Dropbox/code/misc/
clones/neovim/.deps/usr/include -I/home/siddharthist/Dropbox/code/misc/clones/neovim/.d
eps/usr/include -I/home/siddharthist/Dropbox/code/misc/clones/neovim/.deps/usr/include
-I/home/siddharthist/Dropbox/code/misc/clones/neovim/.deps/usr/include -I/usr/include -
I/home/siddharthist/Dropbox/code/misc/clones/neovim/build/src/nvim/auto -I/home/siddhar
thist/Dropbox/code/misc/clones/neovim/build/include
Compiled by siddharthist@nova

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```

- Type: Bug
- OS: Linux
- Vim:
    - [x] Neovim

**Comment by junegunn** [comment]
Hmm, I'm not sure if there's a perfect solution to this. The Ruby and Python installers execute git commands in parallel and Neovim installer starts the processes in the background, so getting the password is tricky.

As far as I know the only way to ignore `~/.gitconfig` is [to override `$HOME`](http://stackoverflow.com/questions/23400449/how-to-make-git-temporarily-ignore-gitconfig). Maybe you can consider using a custom command that temporarily sets `$HOME` to an empty string like follows:

```vim
function! s:plug_update(bang, args)
  try
    let home = $HOME
    let $HOME = ''
    execute 'PlugUpdate'.a:bang a:args
  finally
    let $HOME = home
  endtry
endfunction

command! -bang -nargs=* MyPlugUpdate call s:plug_update('<bang>', <q-args>)
```

Does this answer your question?

**Comment by siddharthist** [comment]
I mean, there are definitely workarounds, I was just wondering if `vim-plug` could do anything. Maybe there could be a flag for passphrase encoded SSH keys that diables parallel git commands and allows user input on them?

**Comment by junegunn** [comment]
On vim you can `:PlugInstall1` and `:PlugUpdate1` to use the synchronous, single-threaded installer so you can type in the password. On Neovim, it's always asynchronous, so um..

An easy workaround I think is to provide an option that tells vim-plug to always use synchronous, single-threaded installer. But I don't think there's a high demand for that especially when we already have workarounds. Theoretically, yes, vim-plug could do more, like detecting if any of the plugins require password prompt and switching the execution mode accordingly, but I'm afraid that it'll over-complicate the implementation.

**Comment by evoludigit** [comment]
Tim Pope’s vim-fugitive plugin also requires to input ssh passphrases from Neovim.

On Arch Linux and neovim, I use ```x11-ssh-askpass```, that works great. It is also available on Debian and other distros as ```ssh-askpass```, and it is built on X11 libraries.
