### ISSUE TITLE
You set USE_PYTHON2 to make CMake find python2 libs only, but CMake found   python3 libs instead.

### ISSUE THREAD

**Issue by d0u9** [junegunn/vim-plug#473]
Explain the problem here ...

I want to compile ycm server with python3.5 which I installed via pyenv. I installed the cmake and downloaded the newest llvm+clang from official site. However, I was stuck when I run the following command:

    cmake -G "Unix Makefiles" -DPYTHON_INCLUDE_DIR=~/.pyenv/versions/3.5.1/include/python3.5m -DPYTHON_LIBRARY=~/.pyenv/versions/3.5.1/lib/libpython3.5m.so -DPATH_TO_LLVM_ROOT=~/ycm_temp/llvm_root_dir . ~/.dot/nvim/plugged/YouCompleteMe/third_party/ycmd/cpp

It reported：

    -- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
Your C++ compiler supports C++11, compiling in that mode.
-- Found PythonLibs: /home/doug/.pyenv/versions/3.5.1/lib/libpython3.5m.so (found suitable version "3.5.1", minimum required is "2.6") 
CMake Error at CMakeLists.txt:207 (message):
  You set USE_PYTHON2 to make CMake find python2 libs only, but CMake found
  python3 libs instead.  Either don't set USE_PYTHON2 or install the
  necessary python2 headers & libraries.

 
------------------------------

```
NVIM v0.1.3
Build type: Debug
Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector
--param ssp-buffer-size=4 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/home/doug/Git/repositories/neovim/build/config -I/
home/doug/Git/repositories/neovim/src -I/home/doug/Git/repositories/neovim/.deps/usr/include -I/home/doug/Git/repositories/neovim/.deps/usr/in
clude -I/home/doug/Git/repositories/neovim/.deps/usr/include/luajit-2.0 -I/home/doug/Git/repositories/neovim/.deps/usr/include -I/home/doug/Gi
t/repositories/neovim/.deps/usr/include -I/home/doug/Git/repositories/neovim/.deps/usr/include -I/home/doug/Git/repositories/neovim/.deps/usr/
include -I/usr/include -I/home/doug/Git/repositories/neovim/build/src/nvim/auto -I/home/doug/Git/repositories/neovim/build/include
Compiled by doug@Trident-Linux

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/doug/Applications/neovim/share/nvim"
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
Is this relevant to vim-plug?
Shouldn't you be reporting this to https://github.com/Valloric/YouCompleteMe/issues instead?

/ping @vheon

**Comment by d0u9** [comment]
Sorry, I posted this issue wrong place....
