### ISSUE TITLE
Plans for using native plugin manager when available?

### ISSUE THREAD

**Issue by vheon** [junegunn/vim-plug#479]
On the latest vim we have a native package manager. Are there any plans to use it underneath vim-plug if the feature is available? This way we would have:
- single vimrc for old/new vim
- the `PlugUpgrade` feature

---

```

```

- Type:
  - [ ] Bug
  - [ ] Enhancement
  - [ ] Feature Request
  - [x] Question
- OS:
  - [x] All/Other
  - [ ] Linux
  - [ ] OS X
  - [ ] Windows
- Vim:
  - [x] Terminal Vim
  - [x] GVim
  - [ ] Neovim

**Comment by junegunn** [comment]
You mean the "package" stuff? I haven't had a chance to look into it yet. Is it any good?

I'm not sure if I'll want to replace the current implementation with a new feature of Vim. One of the strong points of vim-plug I think is its extremely generous backward compatibility; most features of vim-plug work on Vim 7.0, and I don't want to give it up unless there's a very good reason.

**Comment by vheon** [comment]
> You mean the "package" stuff? I haven't had a chance to look into it yet. Is it any good?

I didn't play with it yet, so I can't tell.

> I'm not sure if I'll want to replace the current implementation with a new feature of Vim

I didn't mean to replace the current implementation but to transparently use the new API when available.

**Comment by nhooyr** [comment]
AFAIK there are no advantages to using it. It does the exact same thing that vim-plug already does, namely adding directories to `rtp`.

**Comment by vheon** [comment]
> AFAICT there are no advantages to using it. It does the exact same thing that vim-plug already does, namely adding directories to rtp.

Even if they are the same thing one would do it in C while the other would do it in VimL and I prefer the former, that's all but I'm fine also the way it is today :+1:

**Comment by janlazo** [comment]
@junegunn vim-plug works (tested `PlugInstall` and `PlugUpdate`) in Vim 7.2 on Windows because vim-plug uses batchfiles to run commands in `:!` and `system()`. I prefer that vim-plug maintains Vim 7 support (at least 7.4) so I don't have use case for `:packadd` (maybe on the 8.1 release).

**Comment by SevereOverfl0w** [comment]
One big benefit to vim-plug is that code for ordering is unnecessary. Which also means plug#begin and plug#end can be eliminated (ref/ #615).

**Comment by janlazo** [comment]
@SevereOverfl0w Which version of Vim are you referring for the ordering of packages?

**Comment by SevereOverfl0w** [comment]
I'm not sure exactly when it came in. I would suspect since very early in packages being introduced. The after directories have to be at the end.

**Comment by janlazo** [comment]
7.4.1840 and 7.4.2164 are required for packages with `after/`.

**Comment by junegunn** [comment]
Most features of vim-plug work just fine on Vim 7.0 and I'm proud of that. Believe it or not, there are users who have to work with such old versions of Vim from time to time. Not having to write two lines of code or cutting down a couple milliseconds in startup time doesn't seem like a compelling reason to switch. If you really want to use Vim 8 package for some reason, there are alternatives to vim-plug you can use instead.
