### ISSUE TITLE
Load plugin on entering Insert

### ISSUE THREAD

**Issue by joshaw** [junegunn/vim-plug#48]
Is it possible to trigger a plug-in to load on entering insert mode?

I'm basically just trying to reduce the start-up time of vim. I quite often use vim to view a file and never get round to editing it, so loading plug-ins that are used for editing is not necessary (I'm thinking Ultisnips mainly cause it increases load time noticeably).

I tried creating a command that does nothing and setting the `'on'` parameter and then having an autocommand call this when entering Insert mode, but it didn't work. Having a look at the code, it looks like the command has to be provided by the plug-in that is being loaded, is that right? Any way around this (I'm versed in VimL enough to figure it out)?

```
Plug 'SirVer/ultisnips', {'on': 'InsertEnterCustom'}
...
function! InsertEnterCustom()
    echo "Nothing"
endfunction
command! InsertEnterCustom call InsertEnterCustom()
...
autocmd InsertEnter * InsertEnterCustom
```

Thanks for your work.

**Comment by BlueDrink9** [comment]
I've just written a wrapper for this, to make it more general. This is one of the main places that google shows for this issue.

```
" Plug installs the plugin, but only loads on InsertEnter.
" url: the normal first arg to Plug
" name: the last part of the url
" options: a dict with the plug options. Should include 'on': [] to prevent
" load.
function! PlugOnInsertEnter(url, name, options)
  exec "Plug '" . a:url . "', a:options"
  let l:plugLoad = 'autocmd InsertEnter * call plug#load("'
  let l:plugLoadEnd = '")'
  let l:undoAutocmd = 'autocmd! ' . a:name . '_insertenter'
  exec "augroup " . a:name . '_insertenter'
    autocmd!
    exec  l:plugLoad . a:name . l:plugLoadEnd . ' | ' . l:undoAutocmd
  augroup END
endfunction

" Usage example
call PlugOnInsertEnter('SirVer/ultisnips', 'ultisnips', { 'for': 'c', 'on': [] })
```
