### ISSUE TITLE
vim-plug timeout on Linux subsystem (beta), Windows 10

### ISSUE THREAD

**Issue by fredrikaverpil** [junegunn/vim-plug#486]
I realize this is a corner case. In [the beta of bash running in Windows 10](https://msdn.microsoft.com/en-us/commandline/wsl/about), I can't get vim-plug to work. I'm using the same config as on my OS X laptop where vim-plug works great, which is just the standard installation procedure.

![vimplug1](https://cloud.githubusercontent.com/assets/994357/15349054/035f1c34-1cd0-11e6-9736-9edbb158267e.png)
![vimplug2](https://cloud.githubusercontent.com/assets/994357/15349055/060e9464-1cd0-11e6-8bb4-f56cb48519b1.png)

In the folder which plugins are cloned into, I can see each plugin's folder name. Inside there's a .git folder with the basic .git structure. But then it seems it stops there.

The workaround is to manually `git clone` each plugin respectively.

---

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:32)
Included patches: 1-52
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
Huge version without GUI.  Features included (+) or not (-):
+acl             +cmdline_hist    -dnd             -footer          +lispindent      -mouse_jsbterm   -perl            +scrollbind      -tcl             +viminfo         -xterm_save
+arabic          +cmdline_info    -ebcdic          +fork()          +listcmds        +mouse_netterm   +persistent_undo +signs           +terminfo        +vreplace        -xpm
+autocmd         +comments        +emacs_tags      +gettext         +localmap        +mouse_sgr       +postscript      +smartindent     +termresponse    +wildignore
-balloon_eval    +conceal         +eval            -hangul_input    -lua             -mouse_sysmouse  +printer         -sniff           +textobjects     +wildmenu
-browse          +cryptv          +ex_extra        +iconv           +menu            +mouse_urxvt     +profile         +startuptime     +title           +windows
++builtin_terms  +cscope          +extra_search    +insert_expand   +mksession       +mouse_xterm     +python          +statusline      -toolbar         +writebackup
+byte_offset     +cursorbind      +farsi           +jumplist        +modify_fname    +multi_byte      -python3         -sun_workshop    +user_commands   -X11
+cindent         +cursorshape     +file_in_path    +keymap          +mouse           +multi_lang      +quickfix        +syntax          +vertsplit       -xfontset
-clientserver    +dialog_con      +find_in_path    +langmap         -mouseshape      -mzscheme        +reltime         +tag_binary      +virtualedit     -xim
-clipboard       +diff            +float           +libcall         +mouse_dec       +netbeans_intg   +rightleft       +tag_old_static  +visual          -xsmp
+cmdline_compl   +digraphs        +folding         +linebreak       +mouse_gpm       +path_extra      -ruby            -tag_any_white   +visualextra     -xterm_clipboard
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl    -L/usr/lib/python2.7/config-x86_64-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
```
- Type:
  - [x] Bug
  - [ ] Enhancement
  - [ ] Feature Request
  - [ ] Question
- OS:
  - [ ] All/Other
  - [ ] Linux
  - [x] Linux subsystem (Windows 10)
  - [ ] OS X
  - [ ] Windows
- Vim:
  - [x] Terminal Vim
  - [ ] GVim
  - [ ] Neovim

**Comment by junegunn** [comment]
Interesting. I don't have a Windows PC, so any help is appreciated. How about the single-threaded Vimscript installer, does it work? (`:PlugInstall1` or `:PlugUpdate1`)

**Comment by fredrikaverpil** [comment]
No, it seems `:PlugInstall1` exhibits the same issue, although only the first plugin (in my case vim-flake8) is shown in the list:

    1 Installing plugins (0/11)
    2 [________]
    3
    4 + vim-flake8: Installing ...

...and it doesn't even seem like it's getting a timeout. I've been waiting for ~5 minutes now and had to cancel via ctrl+c.

Same thing with `:PlugUpdate1`.

**Comment by yyolk** [comment]
I've been playing around with a yoga recently and was able to install via plug just fine with the latest windows susbsystem for Linux and latest windows creators update (I think they get the same sources so creator's update may be not relevant)

I think this issue may be closed... YMMV

Using both the Unix install command and the same config I have on my MacBook, the most recent Plug works fine

![image](https://user-images.githubusercontent.com/134478/27773507-dbe13a7a-5f40-11e7-810d-ca6c5c5d0bda.png)

![image](https://user-images.githubusercontent.com/134478/27773510-e414ae3e-5f40-11e7-8dc6-8f95ec1eb029.png)

**Comment by janlazo** [comment]
Please test with https://github.com/junegunn/vim-plug/pull/860 if this is resolved.

**Comment by janlazo** [comment]
Reopen if this occurs again with recent releases of Windows 10 and WSL.
