### ISSUE TITLE
Lazy loading plugins does not source from after/ftplugin

### ISSUE THREAD

**Issue by kshenoy** [junegunn/vim-plug#489]
I'm trying to lazy-load vim-textobj-function with the following: `{'on': '<Plug>(textobj-function'}`

The above works. Before I use a map, `:PlugStatus` shows that the plugin is not sourced and after I use a map, it says it's sourced. However, from `:scriptnames` I can see that any files in `after/ftplugin` are not sourced.

Please let me know if I'm missing something here.

Thanks

------------------------------

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 12 2016 11:29:40)
Included patches: 1-1724
Huge version with GTK2 GUI.  Features included (+) or not (-):
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [x] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
Thanks for the report. Looks like we should trigger `BufRead` autocmd when a plugin with `on` option is loaded.

**Comment by junegunn** [comment]
Should be fixed now. Please `:PlugUpgrade` and try again.

**Comment by kshenoy** [comment]
Thanks, it works now. Out of curiosity, why trigger BufRead and not FileType? Won't the latter also read after/ftplugin?

**Comment by junegunn** [comment]
Because of filetype detection (ftdetect), see https://github.com/junegunn/vim-plug/issues/327#issuecomment-160174323.
