### ISSUE TITLE
Git SubModules

### ISSUE THREAD

**Issue by miguelmartin75** [junegunn/vim-plug#49]
For YouCompleteMe, I currently have in my `.vimrc` the following line:

``` viml
Plug 'Valloric/YouCompleteMe', { 'do': './install.sh --clang-completer' }
```

However, it seems to me that the install script must have failed (either that or it did not run). As it would not compile the binaries (when I ran vim again, YouCompleteMe would tell me that I have not ran the `install.sh` script). I decided to manually go to the `~/.vim/plugged/YouCompleteMe` directory, and run `./install.sh --clang-completer` from there. However, I got this error:

```
Some folders in ./third_party are empty; you probably forgot to run:

    git submodule update --init --recursive
```

Therefore, would it be possible to update/init submodules when you run `PlugInstall`/`PlugUpdate`? Otherwise, I would have to manually go to the repository and update/init the submodules; or alternatively make a function that does this for me (but this seems tedious, especially for other plugins that may require git submodules). 

Also, I believe Vundle does update/init submodules for repositories (source: https://github.com/Valloric/YouCompleteMe#full-installation-guide).

I am currently running OS X 10.9.2, with git version 1.8.5.2 (Apple Git-48), if this issue is only occurring for me, or if it is due to the fact I am using the `--clang-completer` argument for the install script.

**Comment by reilg** [comment]
Just wanted to point out that this is still an issue it seems. 

Installing or updating from did not work for me.
It showed an error that a bundle was missing or somesuch. 

When I went into the YCM folder and ran `install.sh` manually, it showed the "empty folders" error.

Running the bang version fixed it, though.
