### ISSUE TITLE
Issues when trying to lazy-load a plugin which uses omaps

### ISSUE THREAD

**Issue by kshenoy** [junegunn/vim-plug#491]
I don't use some text-object plugins often so I thought I'd lazy load them.  An example is [vim-textobj-line](https://github.com/kana/vim-textobj-line) and I lazy load using:

    Plug  'kana/vim-textobj-line', {'on': '<Plug>(textobj-line'}
    xmap i_ <Plug>(textobj-line-i)
    omap i_ <Plug>(textobj-line-i)

but it works only for xmap and not for omap.

I don't know if this is intentionally not supported or I'm doing something wrong. If it's not supported in order to keep the plugin simple, then I'm in favor of simplicity and I don't mind using `vi_d` instead of `di_` once after startup. But, just thought I'd mention this. However, if I'm doing something wrong, please let me know what it is. Thanks.

------------------------------

```
Vim 7.4.1724
```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [x] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
Thanks for the report. Seems like we need extra processing for omaps.

**Comment by junegunn** [comment]
Should be fixed now. Let me know if you still have issues.

FYI, the feature relies on `feedkeys()` call which cannot be tested using Vader.

**Comment by kshenoy** [comment]
Yep, works perfectly now. Thanks :+1:
