### ISSUE TITLE
nvim variables reset after loading vim-plug

### ISSUE THREAD

**Issue by ssampang** [junegunn/vim-plug#492]
Using nvim 0.1.5-dev, vim-plug seems to override my vim settings. My .vimrc (which is sourced by ~/.config/nvim/init.vim) is [here](https://gist.github.com/ssampang/4561749809c57b6d48e808f6ad7bba60). When I open any python file, I can try `set ts?` and `set shiftwidth?`, which output 8 and 4, respectively. However, if I manually execute `source ~/.vimrc` again, then they are assigned the values that I dictate in my .vimrc.

Furthermore, this seems to be caused by the vim-plug code in my .vimrc. If I remove `call plug#begin`...`call plug#end`, then the values are set correctly on initialization. It shouldn't be a specific plugin either because I can delete all the plugin calls ie. write
```
call plug#begin('~/.vim/plugged')

call plug#end()
```
and the issue persists. Besides this, everything functions perfectly with respect to vim-plug.

```
0.1.5-dev
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by ssampang** [comment]
I had originally filed this as a bug, but I just found the line that causes my issue is in the ftplugin for python. I'm leaving this open as a question though because I would appreciate it if anyone could shed light on how vim-plug could still be somehow affecting this issue given that the ftplugin stuff shouldn't really be interacting with it in any way. I've also found out that even if all my vim-plug code is removed, if I also remove my `syntax on` line (which was right before my vim-plug code), then the problem returns.

**Comment by mklabs** [comment]
I'm also really interested in this. Can't say if it's a bug or a misconfiguration, but I noticed some inconsistencies vim / nvim with how vim-plug loads (or not loads for nvim) bundles.

**Comment by junegunn** [comment]
Consider moving plug section to the top of your init.vim before any `set` statements. `plug#end()` internally enables [filetype plugins and syntax highlighting](https://github.com/junegunn/vim-plug/blob/master/plug.vim#L261-L264), so probably the settings before it are overridden by the filetype plugin. I believe you'll experience the same problem even without vim-plug if you do `filetype plugin indent on` (which I can't imagine you don't want) after `set` statements. It also means that you don't need `filetype plugin indent on` or `syntax on` in your configuration.

**Comment by ssampang** [comment]
I've tried to reorder the statements in my vimrc in multiple ways including the one you mentioned, but that doesn't seem to make any difference. If I look at `:help initialization`, I see that the vimrc is loaded before any plugins or scripts, so that wouldn't make a difference right? [Here](https://gist.github.com/ssampang/4f62ddfade943e832f4f5a9407222fca) is the output of `:scriptnames`. Or are you saying that vim-plug does some kind of nested loading? So far I've been able to think of two solutions:

1. Use something like `autocmd VimEnter * set shiftwidth=2`
2. creating a `$HOME/vimfiles/ftplugin/python.vim` and setting the variables that are being written there

Neither of these solutions seem optimal, but perhaps 2 is the right way to go...

BTW, I've changed the original text of this issue to reflect that I'm only having this problem with python files. C files are fine.

**Comment by ssampang** [comment]
Now that I'm thinking more about this, maybe this is more a question of style? The ftplugin for C doesn't enforce any shiftwidth, and the ftplugin for python may only be enforcing such constraints because the language is so dependent on indentation. I still think its odd that they just override my settings, but solution 2 above is probably not "half-baked" since I will probably only need to implement it for languages which heavily rely on indentation

**Comment by ssampang** [comment]
[This link](http://stackoverflow.com/questions/21073496/why-does-vim-not-obey-my-expandtab-in-python-files) mirrors what I've written above and says that the best thing to do is to create a`~/.config/nvim/after/ftplugin/python.vim` file and reset the changed variables there.

**Comment by junegunn** [comment]
Yeah, ignore my previous comment. The issue is unrelated to vim-plug.
