### ISSUE TITLE
how to get rid of gofmt in vim-plug?

### ISSUE THREAD

**Issue by sameeroak** [junegunn/vim-plug#496]
Hello,
So far, it's be a wonderful journey with vim-plug, except one thing. I don't want gofmt to do any unnecessary formatting for my code.

I'm using vim-plug for go-lang. I've my own "set tabstop=4" in my .vimrc.
I add header section to .go sources to help the reader understand what exactly the source file is all about. Additionally, I add more than 1 line in the code for cleaner segregation.
By including following 2 lines in my .vimrc
let g:go_fmt_fail_silently = 1
let g:go_fmt_autosave = 0
I've gotten rid of unnecessary errors and formatting gofmt applies to my .go source files.

However, I'm not being able to remove the extra tab gofmt adds to make it an 8 blank character tab. I read that gofmt has 8 blank character wide tabspace.

As a result, I want to get rid of gofmt. Please advice me how can I do that.

Version information:
I use vim-7.4 on CentOS 7.2

- Type: Question
- OS  : Linux (CentOS 7.2)
- Vim : Terminal Vim (vim-7.2)

**Comment by vheon** [comment]
I don't think you posted in the right place :stuck_out_tongue_closed_eyes: Are you sure you didn't want to post on https://github.com/fatih/vim-go

**Comment by sameeroak** [comment]
No, it's correct. I'm using vim-plug.

**Comment by vheon** [comment]
> I'm using vim-plug for go-lang

vim-plug is a package manager which let you manage your plugin but it stops there. The problem that you're facing regards a plugin for go-lang I imagine.

**Comment by junegunn** [comment]
@vheon is right. The question is not related to the specifics of vim-plug. Please use the issue tracker of vim-go.
