### ISSUE TITLE
`call youcompleteme#Enable` is not needed anymore

### ISSUE THREAD

**Issue by vheon** [junegunn/vim-plug#501]
Since https://github.com/Valloric/YouCompleteMe/commit/c44489af16de6ae86294de7dd194bd6e53adaf1e the `call youcompleteme#Enable()` is not needed when loading YCM lazily.

------------------------------

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [x] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [x] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
Great to know. Thanks. I'll update the pages.

**Comment by junegunn** [comment]
The updated example on the README page is not a good one though since `{ 'on': 'Goyo' }` makes more sense. But I can't think of a better example now.
