### ISSUE TITLE
Selective PlugClean

### ISSUE THREAD

**Issue by sassanh** [junegunn/vim-plug#503]
Suppose that I apply a local commit to a plugin. With the new `PlugClean` it tries to remove it as it's diverged. It'd be great if we could somehow disable cleaning diverged plugins or `PlugClean` worked interactively and let user select which candidates he wants to clean.

------------------------------

```
NVIM 0.1.4
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-para
meter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/ne
ovim-20160524-70013-14wksgv/neovim-0.1.4/build/config -I/tmp/neovim-20160524-70013-14wksgv/neovim-0.1.4/src -I/tmp/neovim-20160524-70013-14wksgv/neovim
-0.1.4/deps-build/usr/include -I/tmp/neovim-20160524-70013-14wksgv/neovim-0.1.4/deps-build/usr/include -I/tmp/neovim-20160524-70013-14wksgv/neovim-0.1.
4/deps-build/usr/include/luajit-2.0 -I/tmp/neovim-20160524-70013-14wksgv/neovim-0.1.4/deps-build/usr/include -I/tmp/neovim-20160524-70013-14wksgv/neovi
m-0.1.4/deps-build/usr/include -I/tmp/neovim-20160524-70013-14wksgv/neovim-0.1.4/deps-build/usr/include -I/tmp/neovim-20160524-70013-14wksgv/neovim-0.1
.4/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20160524-70013-14wksgv/neovim-0.1.4/build/src/nv
im/auto -I/tmp/neovim-20160524-70013-14wksgv/neovim-0.1.4/build/include
Compiled by sassanharadji@MacBook-Pro

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.4/share/nvim"
```

- Type:
    - [ ] Bug
    - [x] Enhancement
    - [x] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [x] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
Makes sense. How about this?

1. `:PlugClean`
2. Say no to `Proceed? (y/N)`
3. Press `D` on each line to delete the directory on the line.

**Comment by sassanh** [comment]
It totally satisfies my need but I think a more user friendly version would be like this:
1. `:PlugClean`
2. Press `C` (or something else, idk) to delete all listed directories.
3. Press `D` on each line to delete the directory on the line.

And it'd be really cool if it worked with `dd`, `dgg`, `dG`, `d3k` or likes, but thats like science fiction 😆  as I said your own suggestion totally satisfies my need.

**Comment by junegunn** [comment]
> but thats like science fiction

It's actually pretty simple :) Here's what I came up with. It overrides `d` so you can delete plugins in the range.

https://raw.githubusercontent.com/junegunn/vim-plug/clean-interactively/plug.vim

I'd like to check if there's room for improvement before deciding to merge it, feedbacks are appreciated.

**Comment by sassanh** [comment]
Thanks. It's working perfect except for a minor issue, suppose this is the situation:
```
- .../.config/nvim/plugged/1.vim/
- .../.config/nvim/plugged/2.vm/
    Diverged from origin/master by 1 commit(s).
- .../.config/nvim/plugged/3.vm/
- .../.config/nvim/plugged/4.vm/
```
If I go to the last line and press `dk` and then `yy` or `a` it'll change to this:
```
- .../.config/nvim/plugged/1.vim/
- .../.config/nvim/plugged/2.vm/
```
But it should change to this:
```
- .../.config/nvim/plugged/1.vim/
- .../.config/nvim/plugged/2.vm/
    Diverged from origin/master by 1 commit(s).
```
I was trying it and suddenly thought I accidentally removed the diverged plugin, but then noticed this issue.
Other than that it's really fantastic. I'd like to read the relevant piece of code, can you show me where is it?

**Comment by junegunn** [comment]
Nice catch, that's a bug :)

Here's the commit.
https://github.com/junegunn/vim-plug/commit/91ea5ae1c36b2ed818d76e33fac7244ca154fe5f

**Comment by sassanh** [comment]
Thanks, I learnt a lot reading that commit :-)

**Comment by junegunn** [comment]
Merged to master. I tried to improve the UI. Please try it and let me know if you see any issues. Thanks.
