### ISSUE TITLE
[Question] Make preview window layout configurable

### ISSUE THREAD

**Issue by mhinz** [junegunn/vim-plug#504]
Hi,

[this line](https://github.com/junegunn/vim-plug/blob/master/plug.vim#L2137) opens a new 12-line height window at the top. I'd prefer if it were created next to the current window instead. Basically like in gv. ;-)

I looked through the code but couldn't find a way to hook into it.

I'd prefer any wild hack before suggesting to introduce a new option, but I don't see any other way. According to `g:plug_window` maybe `g:plug_preview_window`? But just setting it to `vertical pedit` doesn't allow to set the window size..

Maybe it would be best to emit a User event at the end of `s:preview_commit()`?

```vim
if exists('#User#PlugPreview')
  doautocmd User PlugPreview
endif
```

Then, in my case, I could hook into it with:

```vim
autocmd User PlugPreview wincmd p | wincmd L | wincmd p
```

What do you think?

**Comment by junegunn** [comment]
> autocmd User PlugPreview wincmd p | wincmd L | wincmd p

Yeah we could do that except that it's a little more complicated with the default layout (split to the left). I suppose you use non-default `g:plug_window`? But anyway, if we don't have a choice but to add something to vim-plug, wouldn't it be simpler for the users that we just provide `g:plug_preview_window` (or `g:plug_pwindow`)?

```vim
let g:plug_window = '-tabnew'
let g:plug_pwindow = 'vertical rightbelow new'

" vs.

let g:plug_window = '-tabnew'
autocmd User PlugPreview wincmd P | wincmd L | wincmd p
```

I wish there was a native option for configuring the preview window, but it looks like `&previewheight` is all we have. Given the situation, I think it makes sense to add a way to configure the layout. I'll look into it.

**Comment by mhinz** [comment]
Yea, User events are more general and for people with very specific wishes. From the point of view of a user who just wants to influence the preview window layout, using a simple variable is probably much more comfortable.

And yes, `&previewoptions` is definitely missing. :-)

Thanks for considering.

**Comment by junegunn** [comment]
> User events are more general and for people with very specific wishes

Do you think it's worth it? Anyway for `g:plug_pwindow`, the patch is pretty simple.

```patch
diff --git a/plug.vim b/plug.vim
index ff1827b..d769553 100644
--- a/plug.vim
+++ b/plug.vim
@@ -2140,9 +2140,14 @@ function! s:preview_commit()
     return
   endif
 
-  execute 'pedit' sha
-  wincmd P
-  setlocal filetype=git buftype=nofile nobuflisted modifiable
+  if exists('g:plug_pwindow') && !s:is_preview_window_open()
+    execute g:plug_pwindow
+    execute 'e' sha
+  else
+    execute 'pedit' sha
+    wincmd P
+  endif
+  setlocal previewwindow filetype=git buftype=nofile nobuflisted modifiable
   execute 'silent read !cd' s:shellesc(g:plugs[name].dir) '&& git show --no-color --pretty=medium' sha
   normal! gg"_dd
   setlocal nomodifiable
```

**Comment by mhinz** [comment]
> Do you think it's worth it?

No, either solution is fine. The patch looks good! :shipit:
