### ISSUE TITLE
UX: g:plug_home

### ISSUE THREAD

**Issue by mhinz** [junegunn/vim-plug#507]
Hi,

This is really just a "remark" and less an issue report.

`g:plug_home` doesn't get mentioned in the README and the [wiki](https://github.com/junegunn/vim-plug/wiki/api#global-variables-read-only) says it's read-only. Fair enough.

The code says otherwise, though. :-) Proof: https://github.com/junegunn/vim-plug/blob/master/plug.vim#L116-L117

Assuming the wiki is outdated, I think `g:plug_home` should be expanded internally. I always used `plug#begin('~/.vim/bundle')` until I had to use the same directory in another place in my vimrc. So I found `g:plug_home` somewhere and changed it to:

```vim
let g:plug_home = '~/.vim/bundle'
call plug#begin()
```

I knew the argument to `plug#begin()` got expanded automatically (as the example in the README shows) and assumed the same would happen for `g:plug_home`. But that wasn't the case,  so plug actually created a path `~/.vim/bundle` below my current working directory at the time of `:PlugUpdate`.

I understand that `plug#begin(g:plug_home)` would avoid this, it's just that `g:plug_home` and the argument to `plug#begin()` seem to be the same to the user, so the code should treat them the same as well.

What do you think?

**Comment by junegunn** [comment]
> Assuming the wiki is outdated

No, the code you mentioned predates the wiki page. I know it's not super obvious and honestly it took me a while to conclude that it's not some vestigial code we can safely remove.

1. When `plug#begin()` is first called without an argument, vim-plug creates `plugged` directory inside the first directory in `&runtimepath`.
    - I no longer recommend calling it without an argument, but that's another topic.
2. The earlier versions of vim-plug used to *prepend* plugin directories to `&runtimepath`, changing the "first directory" in `&runtimepath`.
3. When .vimrc is reloaded, `plug#begin()` is called again, and we have to make sure that it still chooses the same directory as before.
4. Although number 2 is no longer the case (#34), the user can manually prepend some directory to `&runtimepath`.
    ```vim
    call plug#begin()
    Plug ...
    Plug ...
    call plug#end()

    set rtp^=~/yolo
    ```
5. So `g:plug_home` is really not supposed to be set by the user, thus read-only. Resistance is futile.

**Comment by mhinz** [comment]
Ah, that makes sense. Thanks for the explanation.

Closing!
