### ISSUE TITLE
superfrozen feature to prevent also installation

### ISSUE THREAD

**Issue by enricobacis** [junegunn/vim-plug#513]
I would love to have a keyword similar to `frozen` that would also prevent installation if not forced. I understand this may seem illogical, but for example `YouCompleteMe` takes ages to install and requires a lot of dependencies. Sometimes I log in a new environment and it would lovely for me to be able to specify plug-ins that must be installed only on my main machines and not in the more "casual" ones.

I understand that I could use a custom install function, but this would require me to write an additional function for every plug-in as such. Moreover it would not display the "not yet installed plugins" status in the vim-plug status.

Feel free to close this if I'm the only one that would use this feature ;)

---

```
:version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug  4 2016 15:30:16)
MacOS X (unix) version
Included patches: 1-2152
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +clipboard       +dialog_con      +file_in_path    +job             -lua             +mouse_sgr       +path_extra      +rightleft       +tag_old_static  +user_commands   +writebackup
+arabic          +cmdline_compl   +diff            +find_in_path    +jumplist        +menu            -mouse_sysmouse  +perl            +ruby            -tag_any_white   +vertsplit       -X11
+autocmd         +cmdline_hist    +digraphs        +float           +keymap          +mksession       +mouse_urxvt     +persistent_undo +scrollbind      -tcl             +virtualedit     -xfontset
-balloon_eval    +cmdline_info    -dnd             +folding         +lambda          +modify_fname    +mouse_xterm     +postscript      +signs           +termguicolors   +visual          -xim
-browse          +comments        -ebcdic          -footer          +langmap         +mouse           +multi_byte      +printer         +smartindent     +terminfo        +visualextra     -xsmp
++builtin_terms  +conceal         +emacs_tags      +fork()          +libcall         -mouseshape      +multi_lang      +profile         +startuptime     +termresponse    +viminfo         -xterm_clipboard
+byte_offset     +cryptv          +eval            -gettext         +linebreak       +mouse_dec       -mzscheme        +python          +statusline      +textobjects     +vreplace        -xterm_save
+channel         +cscope          +ex_extra        -hangul_input    +lispindent      -mouse_gpm       +netbeans_intg   -python3         -sun_workshop    +timers          +wildignore      -xpm
+cindent         +cursorbind      +extra_search    +iconv           +listcmds        -mouse_jsbterm   +num64           +quickfix        +syntax          +title           +wildmenu
-clientserver    +cursorshape     +farsi           +insert_expand   +localmap        +mouse_netterm   +packages        +reltime         +tag_binary      -toolbar         +windows
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework
 Cocoa   -mmacosx-version-min=10.11 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.24.0_1/lib/perl5/5.24.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc -F/usr/local/Cellar/
python/2.7.12/Frameworks -framework Python   -lruby.2.3.0 -lobjc -L/usr/local/Cellar/ruby/2.3.1/lib
```

- Type:
  - [ ] Bug
  - [ ] Enhancement
  - [X] Feature Request
  - [ ] Question
- OS:
  - [X] All/Other
  - [ ] Linux
  - [ ] OS X
  - [ ] Windows
- Vim:
  - [X] Terminal Vim
  - [X] GVim
  - [X] Neovim

**Comment by vheon** [comment]
How would you install the plugin when needed then? I'm asking because I don't understand this part:

> I understand that I could use a custom install function, but this would require me to write an additional function for every plug-in as such.

If you have different plugin that require an installation that you don't want on every machine you should still have to do the installation for every plugin when you decide that in fact you need them, so where's the gain?

**Comment by enricobacis** [comment]
you would install it with:

    :PlugInstall!

It's similar to the `frozen` concept extended to installations

**Comment by vheon** [comment]
Yes, I understand that (which is already achievable with a custom function) but with YouCompleteMe for example (or any plugin that you would rather not have it than install it on some machine) there is an additional step for actually installing the plugin, like the `install.py --all` for YCM. How would you do that?

**Comment by enricobacis** [comment]
Probably I don't get it. You would have something like:

    Plug 'Valloric/YouCompleteMe', { 'superfrozen': True, 'do': './install.py --all' }

Then:

    :PlugInstall

will ignore the plug-in, while

    :PlugInstall!

will clone the repo and perform the additional step.

**Comment by vheon** [comment]
is that the same as:

```viml
function! InstallYCM
  if a:info.force
    !./install.sh --all
  endif
endfunction
Plug 'Valloric/YouCompleteMe', { 'do': function('InstallYCM') }
```

(Maybe with the new vim lambdas you could even inline the function)

**Comment by vheon** [comment]
But you're right that this would still clone the plugin 😕

**Comment by junegunn** [comment]
I see, your suggestion does make sense. But I'm also reluctant to add a new option just for a single plugin, I mean, YCM. Are there any other plugins that we really need this option for?

If you don't mind editing and reloading your vimrc before installing/updating the plugin, there are workarounds, for example, you have these lines in your vimrc:

```vim
Plug 'Valloric/YouCompleteMe', { 'do': function('InstallYCM') }
Plug g:plugs.YouCompleteMe.dir
```

The second line is passing a directory as the argument to `Plug` command so it makes YouCompleteMe "unmanaged". vim-plug will add the directory to `&runtimepath`, but it will not try to install or update it.

And when you want to install or update YCM, you can comment out the line, reload vimrc, and `PlugUpdate`.

```vim
Plug 'Valloric/YouCompleteMe', { 'do': function('InstallYCM') }
" Plug g:plugs.YouCompleteMe.dir
```

**Comment by enricobacis** [comment]
I think this would be useful for every plugin that has a compiled part or system dependency (i.e., [ternjs/tern_for_vim](https://github.com/ternjs/tern_for_vim), [ervandew/eclim](https://github.com/ervandew/eclim)) that are the ones that may incur in errors due to missing dependencies, all the others rarely have errors while installing.

This way we would have a kind of failsafe installation and a complete one.

**Comment by junegunn** [comment]
If the compilation step is the problem, we can use the workaround @vheon suggested above.

```vim
function! BuildForce(info, command)
  if a:info.force
    execute '!'.a:command
  endif
endfunction

" Using new lambda syntax
Plug 'Valloric/YouCompleteMe', {'do': {info -> BuildForce(info, './install.sh --all')}}
Plug 'ternjs/tern_for_vim',    {'do': {info -> BuildForce(info, 'npm install')}}
```

> But you're right that this would still clone the plugin 😕

😕

**Comment by enricobacis** [comment]
I do believe that the clone is not such a problem, but of course in order to be completely lazy, why should we clone something that is not being installed right now..

**Comment by junegunn** [comment]
We can consider using `frozen == 2` instead of adding a new option.

```diff
diff --git a/plug.vim b/plug.vim
index d6f7afc..22192aa 100644
--- a/plug.vim
+++ b/plug.vim
@@ -904,7 +904,7 @@ function! s:update_impl(pull, force, args) abort
                   \ remove(args, -1) : get(g:, 'plug_threads', 16)
 
   let managed = filter(copy(g:plugs), 's:is_managed(v:key)')
-  let todo = empty(args) ? filter(managed, '!v:val.frozen || !isdirectory(v:val.dir)') :
+  let todo = empty(args) ? filter(managed, 'v:val.frozen == 0 || v:val.frozen == 1 && !isdirectory(v:val.dir)') :
                          \ filter(managed, 'index(args, v:key) >= 0')
 
   if empty(todo)
diff --git a/test/workflow.vader b/test/workflow.vader
index 81e8115..436e7b1 100644
--- a/test/workflow.vader
+++ b/test/workflow.vader
@@ -653,7 +653,7 @@ Execute (Common parent):
 ~ Frozen plugins
 **********************************************************************
 - We've decided to install plugins that are frozen: see #113
-Execute (Frozen plugin are not ~~installed nor~~ updated):
+Execute (Frozen plugins are not updated):
   " Remove plugins
   call plug#begin()
   call plug#end()
@@ -704,6 +704,16 @@ Execute (But you can still install it if the name is given as the argument):
   AssertEqual 1, len(filter(getline(1, '$'), 'v:val =~ "vim-easy-align"'))
   q
 
+Execute (Plugins with frozen = 2 are not installed (#513)):
+  call plug#begin()
+  Plug 'junegunn/vim-fnr', { 'frozen': 2 }
+  call plug#end()
+
+  redir => out
+  silent PlugInstall
+  redir END
+  Assert out =~ 'No plugin to install'
+
 **********************************************************************
 ~ Retry
 **********************************************************************
```

Note that we currently don't use bang commands for updating frozen plugins. They force-trigger post update hooks and submodule update. In order to update plugins that are frozen, one has to pass the names as the argument to PlugInstall or PlugUpdate.

**Comment by enricobacis** [comment]
Uhm.. yes you are right, that would be probably strange to understand (! installs frozen plugins but ! does not update frozen plugins).

Do you have any idea to simplify this?

**Comment by junegunn** [comment]
>  that would be probably strange to understand (! installs frozen plugins but ! does not update frozen plugins).

`!` is not related to frozen-ness of a plugin.

I presume that "superfrozen" option will be used for a very limited number of plugins, and the user should probably know about those exceptional plugins. So having to provide the name doesn't sound too bad to me. Or one can press `U` on `:PlugStatus` screen.

**Comment by enricobacis** [comment]
Yes, this makes sense
