### ISSUE TITLE
Plugins do not load on startup

### ISSUE THREAD

**Issue by TxHawks** [junegunn/vim-plug#519]
When I start neovim, plugins are not automatically loaded. 

`PlugStatus` shows:
![screenshot](https://cloud.githubusercontent.com/assets/5658514/18383846/0e18dc72-7690-11e6-8ffc-6668eed467b9.jpg)

If I manually load the plugins with `L` everything works just fine, until I exit and restart neovim.

I've tryied starting up with a minimal `init.vim`, loading only a single plugin and which contains no other configuration, but the issue persists:

```vim
"  VIM-Plug {{{

  " Automatically install Vim-Plug if it is not yet installed
  if empty(glob('~/.config/nvim/autoload/plug.vim'))
    silent !curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs
      \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall | source $MYVIMRC
  endif

  " Call vim-plug to manage plugins
  call plug#begin('~/.config/nvim/plugged')

  Plug 'morhetz/gruvbox'

" }}} End VIM-Plug


" gruvbox settings {{{

  set background=dark
  colorscheme gruvbox
  let g:gruvbox_contrast_dark='hard'

" }}} End gruvbox settings
```

Both the Python and Ruby providers are installed can be called with `:python`, `python3` and `ruby`.

Any help would be appreciated.

------------------------------

Output of `:version`:
```
NVIM 0.1.6-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=formatecurity -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstck-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-TFsDzh/neovim-0.1.5ubuntu1+git201609060743+2753+21~ubuntu16.04.1/build/config -I/build/neovim-TFsDzh/neovim-0.1.5ubuntu1+git201609060743+2753+2~ubuntu16.04.1/src -I/build/neovim-TFsDzh/neovim-0.1.5ubuntu1+git201609060743+2753+21~ubuntu16.04.1/.deps/usr/include -I/build/neovim-TFsDzh/neovim-.1.5ubuntu1+git201609060743+2753+21~ubuntu16.04.1/.deps/usr/include -I/build/neovim-TFsDzh/neovim-0.1.5ubuntu1+git20169060743+2753+21~ubuntu16.04.1/.deps/usr/include -I/build/neovim-TFsDzh/neovim-0.1.5ubuntu1+git201609060743+2753+21~ubuntu16.04.1/.deps/usr/include -I/build/neovim-TFsDzh/neovim-0.1.5ubuntu1+git201609060743+2753+21~ubuntu16.04.1/.deps/usr/include -I/build/neovim-TFsDz/neovim-0.1.5ubuntu1+git201609060743+2753+21~ubuntu16.04.1/.deps/usr/include -I/usr/include -I/build/neovim-TFsDzh/neovim-0.1.5ubuntu1+git201609060743+2753+21~ubuntu16.04.1/build/src/nvim/auto -I/build/neovim-TFsDzh/neovim-0.1.5ubuntu1+git201609060743+2753+21~ubuntu1.04.1/build/include
Compiled by buildd@lcy01-02

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

system vimrc file: "$VIM/sysinit.vim"
fall-back for $VIM: "/usr/share/nvim"
```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
You missed to put `plug#end()` after Plug commands.

**Comment by TxHawks** [comment]
Oh, wow, that's embarrassing...

Thanks

**Comment by Opineda930** [comment]
I have the same problem and I do have the `call plug#end` . Any Ideas ?

**Comment by mert-microsoft** [comment]
@junegunn , i have the same issue. The plugins don't load unless i run ":PlugInstall" every time.

**Comment by pr1s10n3r** [comment]
@mert-microsoft I've the exact same issue using gVim under Windows. Could you figured it out ?

**Comment by mert-microsoft** [comment]
no, i switched to WSL

**Comment by junegunn** [comment]
Since you mentioned that you use gVim, make sure not to put the configuration in `.gvimrc` but in `.vimrc`

See https://github.com/junegunn/vim-plug/issues/540#issuecomment-258325522

**Comment by junegunn** [comment]
Added a section to the wiki page: https://github.com/junegunn/vim-plug/wiki/faq#plugins-are-not-loaded-unless-i-run-pluginstall-or-plugupdate
