### ISSUE TITLE
Run commands in :term [neovim] not to block ui

### ISSUE THREAD

**Issue by teto** [junegunn/vim-plug#521]
Explain the problem here ...
Would it be possible in neovim to run commands in a :term (i.e. a new vim window) instead of :!command which blocks the ui.
For instance, when YCM updates itself it takes a long time to compile and blocks neovim.

To reproduce, run PlugUpdate with 
Plug 'Valloric/YouCompleteMe' , {   'do': './install.py --system-libclang --clang-completer' }

------------------------------

```

```

- Type:
    - [ ] Bug
    - [x] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
I suppose you can try something like this:

```vim
Plug 'Valloric/YouCompleteMe', { 'do': ':new \| call termopen("./install.py --system-libclang --clang-completer")' }
```

Does this work for you?

**Comment by teto** [comment]
Following justinmk's advice, I tried
Plug 'Valloric/YouCompleteMe', { 'do': ':term ./install.py --system-libclang --clang-completer' } 
which seemed to work, YouCompleteMe got updated without blocking the UI.

Nevertheless I had errors like:
```
'modifiable' is disabled
<SNR>2_job_handler[24]..<SNR>2_tick[7]..<SNR>2_update_finish 
```

**Comment by justinmk** [comment]
@junegunn Does vim-plug expect the current buffer to stay at the vim-plug buffer? Note that since 0.1.5 nvim API is exposed to vimscript so you can modify other buffers without switching to them, e.g. to add lines to the end of the buffer:

    call nvim_buf_set_lines(42, -1, -1, v:true, ['line1','line2'])

where `42` is the vim-plug buffer.

**Comment by justinmk** [comment]
For backwards compatibility with nvim before 0.1.5, you can use the `cat` hack to open a "loopback" channel to the current nvim instance:

```vim
let chan=jobstart(['cat'], {'rpc': v:true})
call rpcrequest(chan, 'nvim_buf_set_lines', 16, -1, -1, v:true, ['line1','line2'])
```

**Comment by junegunn** [comment]
@teto 
> 'modifiable' is disabled
<SNR>2_job_handler[24]..<SNR>2_tick[7]..<SNR>2_update_finish

That's why I suggested `new` and `termopen` in the code I gave you above. Have you tried it?

@justinmk 

> Does vim-plug expect the current buffer to stay at the vim-plug buffer?

No but it expects the buffer to be visible somewhere. In Ruby/Python installer, we can hit CTRL-C to interrupt the installation process. The equivalent for nvim async installer is to close the buffer, or to hide it since `&bufhidden=wipe`.

**Comment by teto** [comment]
Sorry forgot to tell you I had tried your solution and it resulted in:
 `E115: Missing quote: ':new | call termopen()`
with latest neovim/vim-plug.

**Comment by junegunn** [comment]
@teto `|` should be escaped.

**Comment by teto** [comment]
the | is escaped, the \ got removed in the error message for some reason. I tried doubling the escape "\\|" and in the error message it appears as "\|":
```
E115: Missing quote: ':new \| call termopen()
E116: Invalid arguments for function plug#
```

**Comment by junegunn** [comment]
@teto Try this instead:

```vim
{ 'do': ':new \| call termopen(''./install.py --system-libclang --clang-completer'')' }
```

**Comment by junegunn** [comment]
The problem with using `:term` without `:new` is that it hides and destroys vim-plug buffer (`&bufhidden=wipe`) and clearly vim-plug isn't prepared for that situation (during `do` processing).

Then I tried `:new \| term ...`, but I had issues because of implicit `:startinsert`, so I ended up with `termopen`.

**Comment by teto** [comment]
Works great ! I am glad you helped me on this one, this escaping is insane xD

**Comment by junegunn** [comment]
@teto Glad to hear that it works. But I wonder if there's a simpler way to do this. Hmm.

@justinmk 

> Note that since 0.1.5 nvim API is exposed to vimscript so you can modify other buffers without switching to them

That's nice. Switching is actually what vim-plug constantly does during async installation. But I'm not sure if I should add more neovim-only constructs at this point as there are users demanding [Vim 8 async support](#498). I haven't decided what I'm going to do though.
