### ISSUE TITLE
Overload netrw-gx to handle abbreviated notation in Plug 'junegunn/vim-plug'

### ISSUE THREAD

**Issue by kiryph** [junegunn/vim-plug#524]
I use the mapping `gx` of netrw to  open urls given in a text file when viewing in vim.

When I am in my vimrc and I want to quickly open the github webpage of a plugin, I can also do this with `gx` as long as I have written `Plug 'https://github.com/justinmk/vim-gtfo'` and not `Plug 'justinmk/vim-gtfo'`

Any chance to overload `netrw-gx` in vimscript to check if the current line follows your pattern, otherwise invoke standard `netrw-gx`? Actually, I am not sure whether this is possible in a sensible way.

It's only a convenience mapping, but I certainly would appreciate it.

------------------------------

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [x] Feature Request
    - [ ] Question
- OS:
    - [x] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [x] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
Not exactly what you want, but please take a look at: https://github.com/junegunn/vim-plug/wiki/extra#gx-to-open-github-urls-on-browser

It defines `gx` mapping inside vim-plug window. The code is a bit long as it also handles commits in `:PlugDiff` screen. Overriding key bindings for `vimrc` seems a bit beyond the scope of this project. If you know some vimscript, you'll be able to implement similar thing for vimrc. Does this answer your question?

**Comment by kiryph** [comment]
It definitely helped me to figure out a possible solution:

I have created the file `.vim/after/ftplugin/vim.vim` with following content

```viml
function! s:plug_gx()

  if getline('.') !~ '^Plug '
      call netrw#BrowseX(expand((exists("g:netrw_gx")? g:netrw_gx :
                  \ '<cfile>')), netrw#CheckIfRemote())
      return
  endif

  let cfile = expand('<cfile>')
  if cfile !~ 'github\.com'
      call netrw#BrowseX(expand((exists("g:netrw_gx")? g:netrw_gx :
                  \ 'https://github.com/'.cfile)), netrw#CheckIfRemote())
  else
      call netrw#BrowseX(expand((exists("g:netrw_gx")? g:netrw_gx : 
                  \ cfile)),  netrw#CheckIfRemote())
  endif
endfunction

nnoremap <buffer> <silent> gx :call <sid>plug_gx()<cr>
```

Right now it does what I want. I am not an expert in vimscript if have any suggestions for improvement I happy to hear them.

Thanks for your help.

**Comment by kiryph** [comment]
A lightly modified version with check if file path exists
```viml
function! s:plug_gx()

  if getline('.') =~ '^Plug\s'
      let cfile = expand('<cfile>')
      if cfile !~ 'github\.com' && empty(glob(cfile))
          call netrw#BrowseX(expand((exists("g:netrw_gx")? g:netrw_gx :
                      \ 'https://github.com/'.cfile)), netrw#CheckIfRemote())
      endif
  endif 

  call netrw#BrowseX(expand((exists("g:netrw_gx")? g:netrw_gx :
              \ '<cfile>')), netrw#CheckIfRemote())
endfunction
```

**Comment by junegunn** [comment]
Looks good, you sure seem to know more about netrw API than me.
