### ISSUE TITLE
Load plugin on entering insert mode

### ISSUE THREAD

**Issue by harendra-kumar** [junegunn/vim-plug#528]
Loading YCM takes time which slows down vim startup significantly. I was wondering if it is possible and makes sense to load the plugin when entering insert mode so that if you are just viewing a file YCM startup does not trouble you.

**Comment by vheon** [comment]
https://github.com/junegunn/vim-plug/wiki/faq#loading-plugins-manually

**Comment by harendra-kumar** [comment]
Thanks! Sorry about not looking at the faq carefully.
