### ISSUE TITLE
Speed up opening buffer (might be irrelevant)

### ISSUE THREAD

**Issue by lazywei** [junegunn/vim-plug#53]
Hi,
I found my vim became slow recently, so I decide to migrate to `vim-plug` from `vundles`. Just switching from `vundles` to `vim-plug` reduces the start-up time about half of original time (without even setting any on-demand loading). That's really amazing, thanks!

However, I'm wondering if it is possible to speed up my buffer opening through `vim-plug` (currently, my vim open buffers very slow) ? In fact, I have no idea how to speed up buffer opening. `vim --startuptime xxx` can only give me the profiling of start up time. Do you have any thought on this?

Thanks for the amazing plug-in.

**Comment by agauniyal** [comment]
This needs to go into readme!

**Comment by kminh** [comment]
It seems that the above snippet to lazy load Ultisnips doesn't work anymore. This is what I see in `ultisnips/ftdetect/Ultisnips.vim`:

```vim
if has("autocmd") && &loadplugins
    augroup UltiSnipsFileType
        autocmd!
        autocmd FileType * call UltiSnips#FileTypeChanged()
    augroup END

    " restore 'filetypedetect' group declaration
    augroup filetypedetect
endif
```

I find that this works:
```vim
Plug 'SirVer/ultisnips', { 'on': [] }
augroup load_us
  autocmd!
  autocmd InsertEnter * call plug#load('ultisnips') | call UltiSnips#FileTypeChanged() | autocmd! load_us
augroup END
```

And I agree with @agauniyal that this should go into readme, found out about this gem accidentally :)

**Comment by ruiafonsopereira** [comment]
To build on @kminh's answer, one can also lazy load UltiSnips using a `FileType` event. For instance, if you only have snippets for `c` and `javascript`, one might not want to load this plugin on a `InsertEnter ` event of another filetype.

```vimL
Plug 'sirver/ultisnips', { 'on': [] }
augroup ulti_snips_lazy_load_on_file_type
  autocmd!
  autocmd FileType javascript,c call plug#load('ultisnips')
        \| call UltiSnips#FileTypeChanged()
        \| autocmd! ulti_snips_lazy_load_on_file_type
augroup END
```
