### ISSUE TITLE
Make s:compare_git_uri smarter?

### ISSUE THREAD

**Issue by blueyed** [junegunn/vim-plug#530]
I have seen the FAQ in this regard (https://github.com/junegunn/vim-plug/wiki/faq#whats-the-deal-with-git-in-the-url), but it looks like vim-plug could be made to accept e.g. `git@github.com:blueyed/neomake.git` and `github.com:neomake/neomake.git` as valid/matching URLs for when `https://git::@github.com/neomake/neomake.git` (the default) is expected.

This should work in both directions probably then, so that with `let g:plug_url_format = 'git@github.com:%s.git'` `https://github.com/neomake/neomake.git` would be considered valid.

I am just looking into vim-plug now, coming from Neobundle, and use `git@github.com:neomake/neomake.git` for own plugins, and `git://github.com/junegunn/vim-plug.git` for others.

I could use `plug_url_format` to work around this, but would be happy to provide a PR in case you think it makes sense.

- Type:
    - [ ] Bug
    - [x] Enhancement
    - [x] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
Hi, thanks for looking into it.
We know for sure that `git@github.com:junegunn/vim-plug.git` and `https://github.com/junegunn/vim-plug.git` point to the same repo on GitHub, but is it a git thing or a GitHub thing? I wonder if such pattern conversion rule applies to other hosting services as well, like bitbucket or gitlab for example. The reason I'm wondering is that although the default URL format points to GitHub, it would be nice if we can keep vim-plug as vendor-agnostic as possible.

**Comment by blueyed** [comment]
Agreed. As far as I know it it a general git thing.

**Comment by junegunn** [comment]
Good, I could find the list of url patterns in `git help clone`. There's a lot. I'll take a look at in a few days.

```
The native transport (i.e. git:// URL) does no authentication and should be used with caution on unsecured networks.

The following syntaxes may be used with them:

o   ssh://[user@]host.xz[:port]/path/to/repo.git/

o   git://host.xz[:port]/path/to/repo.git/

o   http[s]://host.xz[:port]/path/to/repo.git/

o   ftp[s]://host.xz[:port]/path/to/repo.git/

An alternative scp-like syntax may also be used with the ssh protocol:

o   [user@]host.xz:path/to/repo.git/

This syntax is only recognized if there are no slashes before the first colon. This helps differentiate a local path that contains a colon. For example the
local path foo:bar could be specified as an absolute path or ./foo:bar to avoid being misinterpreted as an ssh url.

The ssh and git protocols additionally support ~username expansion:

o   ssh://[user@]host.xz[:port]/~[user]/path/to/repo.git/

o   git://host.xz[:port]/~[user]/path/to/repo.git/

o   [user@]host.xz:/~[user]/path/to/repo.git/
```

**Comment by blueyed** [comment]
Thanks!
For reference, you might want to look at what dein (https://github.com/Shougo/dein.vim/blob/d63858c8f2b42c1ddab9c9296148b169240cc74b/autoload/dein/types/git.vim#L47-L49) and Neobundle (https://github.com/Shougo/neobundle.vim/blob/30c40ccbfc6371fb922eece6e0657eb5da9e479b/autoload/neobundle/types/git.vim#L62-L90) does.

**Comment by junegunn** [comment]
Thanks, this is what I just came up with:

```diff
diff --git a/plug.vim b/plug.vim
index 2d22299..1da64a9 100644
--- a/plug.vim
+++ b/plug.vim
@@ -1873,9 +1873,15 @@ function! s:progress_bar(line, bar, total)
 endfunction
 
 function! s:compare_git_uri(a, b)
-  let a = substitute(a:a, 'git:\{1,2}@', '', '')
-  let b = substitute(a:b, 'git:\{1,2}@', '', '')
-  return a ==# b
+  " See `git help clone'
+  " https:// [user@] github.com[:port] / junegunn/vim-plug [.git]
+  "          [git@]  github.com[:port] : junegunn/vim-plug [.git]
+  " file://                            / junegunn/vim-plug        [/]
+  "                                    / junegunn/vim-plug        [/]
+  let pat = '^\%(\w\+://\)\='.'\%([^@/]*@\)\='.'\([^:/]*\%(:[0-9]*\)\=\)'.'[:/]'.'\(.\{-}\)'.'\%(\.git\)\=/\?$'
+  let ma = matchlist(a:a, pat)
+  let mb = matchlist(a:b, pat)
+  return ma[1:2] ==# mb[1:2]
 endfunction
 
 function! s:format_message(bullet, name, message)
```

**Comment by blueyed** [comment]
Thanks a lot!
