### ISSUE TITLE
Feature request: 'ext' option

### ISSUE THREAD

**Issue by Alok** [junegunn/vim-plug#536]
Similar to the `for:` option, but it takes an extension (e.g. `'ext': ['md',  'mmd',  'markdown']` would load only for those extensions).

**Comment by vheon** [comment]
what can you achieve with this that you can't with `for`? I mean all those extension are for markdown, so it will be the same as `'for': 'markdown'`

**Comment by junegunn** [comment]
Yeah, I don't think we need it. If the file type for a file with one of those extensions is not correctly set, you can set up an autocmd (BufNewFile and BufRead; refer to ftdetect part of filetype plugins), and `for` option of vim-plug will eventually pick it up.

Unrelated to this very issue, it's possible to load a plugin on any event as we provide `plug#load()` function. Some examples can be found here: https://github.com/junegunn/vim-plug/wiki/faq#loading-plugins-manually. We can probably suggest a reusable helper function.

```vim
function! LoadOn(name, autocmd)
  let group = 'plug-load-'.a:name
  execute 'augroup' group
    autocmd!
    execute 'autocmd' a:autocmd
          \ printf('call plug#load("%s") | autocmd! %s', a:name, group)
  augroup END
endfunction

call LoadOn('goyo.vim', 'BufNewFile,BufRead *.md')
```
