### ISSUE TITLE
See output of run hook commands?

### ISSUE THREAD

**Issue by deanishe** [junegunn/vim-plug#550]
When a plugin install/update fails, how do I see the output from the commands run by post-update hooks?

The mini buffer that shows the output while the hook is running disappears immediately when the command finishes, and all I'm left with is `Post-update hook ... Exit status: 2`. I don't even know which command's exit status that is 😞 

Is there some vim-plug (or nvim) option I'm missing?

Thanks

------------------------------

```
NVIM v0.2.0-15-gd37c2e5
Build type: Release
Compilation: /usr/bin/cc -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict
-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer-size=4 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/home/daj/src/neovi
m/build/config -I/home/daj/src/neovim/src -I/home/daj/src/neovim/.deps/usr/include -I/home/daj/src/neovim/.deps/usr/include -I/home/daj/src/neovim/.deps/usr/
include -I/home/daj/src/neovim/.deps/usr/include -I/home/daj/src/neovim/.deps/usr/include -I/home/daj/src/neovim/.deps/usr/include -I/usr/include -I/home/daj
/src/neovim/build/src/nvim/auto -I/home/daj/src/neovim/build/include
Compiled by daj@snarf.deanishe.net

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [X] Question
- OS:
    - [X] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [X] Neovim

**Comment by junegunn** [comment]
A couple things you can do for troubleshooting:
- Add `read` to the command: `{ 'do': './foobar; read' }`
- Redirect the output to a log file: `{ 'do': './foobar >> /tmp/log 2>&1' }`

Note that you can re-run the hooks by running bang versions of the commands: `:PlugInstall!` or `:PlugUpdate!`, optionally with the names of the plugins. e.g. `:PlugInstall! foobar`

**Comment by deanishe** [comment]
Thanks very much. That helped me track down and fix the problem.

**Comment by esetnik** [comment]
Related to #910 839
