### ISSUE TITLE
Cannot install new plugins due to error of another plugin

### ISSUE THREAD

**Issue by linkin8834** [junegunn/vim-plug#555]
Explain the problem here ...

I want to install some new plugins and I typed 'PlugInstall'. However, I observe the following:
Error Detected while processing .vim/plugged/LaTeX-Suite-aka-Vim-Latex/plugin/remoteOpen.vim
line 33:
Command already exists: add ! to replace it

After that, I find that my new plugin is not installed...

------------------------------

:version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:47)
Included patches: 1-52
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
Huge version with GTK2-GNOME GUI.  Features included (+) or not (-):
+acl             +conceal         +farsi           +libcall         +mouse_netterm   +profile         +syntax          +visualextra
+arabic          +cryptv          +file_in_path    +linebreak       +mouse_sgr       +python          +tag_binary      +viminfo
+autocmd         +cscope          +find_in_path    +lispindent      -mouse_sysmouse  -python3         +tag_old_static  +vreplace
+balloon_eval    +cursorbind      +float           +listcmds        +mouse_urxvt     +quickfix        -tag_any_white   +wildignore
+browse          +cursorshape     +folding         +localmap        +mouse_xterm     +reltime         +tcl             +wildmenu
++builtin_terms  +dialog_con_gui  -footer          +lua             +multi_byte      +rightleft       +terminfo        +windows
+byte_offset     +diff            +fork()          +menu            +multi_lang      +ruby            +termresponse    +writebackup
+cindent         +digraphs        +gettext         +mksession       -mzscheme        +scrollbind      +textobjects     +X11
+clientserver    +dnd             -hangul_input    +modify_fname    +netbeans_intg   +signs           +title           -xfontset
+clipboard       -ebcdic          +iconv           +mouse           +path_extra      +smartindent     +toolbar         +xim
+cmdline_compl   +emacs_tags      +insert_expand   +mouseshape      +perl            -sniff           +user_commands   +xsmp_interact
+cmdline_hist    +eval            +jumplist        +mouse_dec       +persistent_undo +startuptime     +vertsplit       +xterm_clipboard
+cmdline_info    +ex_extra        +keymap          +mouse_gpm       +postscript      +statusline      +virtualedit     -xterm_save
+comments        +extra_search    +langmap         -mouse_jsbterm   +printer         -sun_workshop    +visual          +xpm
   system vimrc file: "$VIM/vimrc"

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [x ] Linux (Ubuntu 14.04)
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [x ] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
It doesn't sound like a bug of vim-plug. Can you provide the steps to reproduce the problem? Preferably with a minimal vimrc like follows:

```vim
call plug#begin('/tmp/plugged')
Plug 'LaTeX-Suite-aka-Vim-Latex'
" Plug your another plugin
call plug#end()
```

**Comment by linkin8834** [comment]
Hi,
   On my laptop, using the minimal configuration

call plug#begin('~/.vim/plugged')
Plug 'https://github.com/vim-scripts/LaTeX-Suite-aka-Vim-LaTeX.git' 
call plug#end()

would create the problem.

Another issue is that I cannot delete the LaTeX-Suite-aka-Vim-LaTeX plugin. I tried to delete the folder ~/.vim/plugged/LaTeX-Suite-aka-Vim-LaTeX and remove Plug 'https://github.com/vim-scripts/LaTeX-Suite-aka-Vim-LaTeX.git' from .vimrc. However, whenever I run PlugInstall, it keeps trying to install the plugin for me which consistently run into the same problem 

Error Detected while processing .vim/plugged/LaTeX-Suite-aka-Vim-Latex/plugin/remoteOpen.vim
line 33:
Command already exists: add ! to replace it

**Comment by junegunn** [comment]
It means that the plugin is installed but it is broken. You might want to look for the alternatives.

> Another issue is that I cannot delete the LaTeX-Suite-aka-Vim-LaTeX plugin. 

Make sure to restart Vim or reload your .vimrc after modifying the plug section.

**Comment by rgb250** [comment]
If you already created another vim source file (vimrc or init.vim) that pointed on the same folder than '/tmp/plugged', it is normal.
To one Plug folder associate an unique vim  source file!
