### ISSUE TITLE
:PlugInstall - Error - Too Many Arguments

### ISSUE THREAD

**Issue by tjharman** [junegunn/vim-plug#565]
Explain the problem here ...

Trying to :PlugInstall gives me the following error:

x vimwiki:
    Too many arguments.
    
Now - :PlugUpdate works just fine - plugins are updating OK.  But I can't install anything new.  This _was_ working previously, so something has broken recently.  This is a Windows box (vim 8.0.69)

The latest version of vim-plug on my unix machines doesn't exhibit this problem.

Therefore, I'm pretty certain I've done something to my windows box to break this.

However - I can't figure out how to debug what command vim-plug is handing git.

If I do a git clone --depth 1 <url> it works fine from the CLI.

What can I change/edit in vim-plug so I can see what exactly is being passed and what the error that git's producing is?

------------------------------

```

```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [X] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [X] Windows
- Vim:
    - [ ] Terminal Vim
    - [X] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
Add `echom a:cmd` as the first line of `s:spawn` function (line 1162), restart Vim, and run `:PlugInstall1`. You can review the messages after the installer finished using `:messages` command.

**Comment by tjharman** [comment]
Thanks - the command that outputs is valid and works perfectly when run from a cmd shell.

Not sure what I've broken - but it's obviously not vim-plug's fault.

Thanks!

**Comment by tjharman** [comment]
So I have finally managed to debug what the issue is!
Not sure if this is a vim-plug issue or so, but I'll document it here in the hope that someone might have a fix, or it might be something that can be fixed in vim-plug.

My windows _vimrc has:

```
" Load all configuration from Owncloud
set runtimepath+=C:\Users\Tim\ Harman\Owncloud\vim\vimfiles
source C:\Users\Tim\ Harman\Owncloud\vim\vimrc.vim
```

Then in C:\Users\Tim\ Harman\Owncloud\vim\vimrc.vim I have:

```
" TiM's .vimrc
set nocompatible 			" No Compatible - must be first!
"vim-plug - Load silently because some boxes don't have git
silent!call plug#begin('~/Owncloud/vim/vimfiles/plugged')
```

The error that I'm getting from git when I do a :PlugInstall is the following:

```
09:22:47.139958 git.c:371               trace: built-in: git 'clone' '-v' '--depth' '1' 'https://git::@github.com/vimwiki/vimwiki.git' 'C:\Users\Tim' 'Harman\Owncloud\vim\vimfiles\plugged\vimwiki'
Too many arguments.
```

The space in my username under Windows is causing the problem.

Is there any simple way this can be fixed?

Kind Regards,
Tim

**Comment by wngrtn** [comment]
I can confirm this. Same problem here.

**Comment by junegunn** [comment]
> the command that outputs is valid and works perfectly when run from a cmd shell.

Can you post the command? Is the command at the stage correct?

**Comment by dbger** [comment]
My vim had the same issue,

echom a:cmd
this prompt after :messages
git clone --depth 1 --no-single-branch "https://git::@github.com/junegunn/vim-easy-align.git" "D:\Program Files\vim\vimfiles\plugged\vim-easy-align" 2>&1

But I find the truly cmdline by ProcMonitor is : 	git  clone --depth 1 --no-single-branch  ""https://git::@github.com/junegunn/vim-easy-align.git"" ""D:\Program Files\Vim\vimfiles\plugged\vim-easy-align""

**Comment by junegunn** [comment]
Hmm, the command looks right. Do you use Vim 8? I'm suspecting that it can be an issue of new Vim 8 jobstart function

- What is the output of `:echo has('patch-8.0.0039') && exists('*job_start')`?
- If it's 1, please check if the following patch (which disables Vim 8 asynchronous installer) helps.

```diff
diff --git a/plug.vim b/plug.vim
index b245aa7..a8e3dd3 100644
--- a/plug.vim
+++ b/plug.vim
@@ -1180,7 +1180,7 @@ function! s:spawn(name, cmd, opts)
       let job.lines   = [jid < 0 ? argv[0].' is not executable' :
             \ 'Invalid arguments (or job table is full)']
     endif
-  elseif s:vim8
+  elseif 0
     let jid = job_start(argv, {
     \ 'out_cb':   function('s:job_cb', ['s:job_out_cb',  job]),
     \ 'exit_cb':  function('s:job_cb', ['s:job_exit_cb', job]),
```

**Comment by tjharman** [comment]
Your patch fixes the problem, thank you.

**Comment by junegunn** [comment]
@mattn Hi, sorry to bother. It looks like there are some Windows users having trouble with job_start. Do you have any clue on this?

**Comment by mattn** [comment]
Why you use shell(cmd.exe) ?

**Comment by junegunn** [comment]
@mattn Thanks for taking a look. Actually, the code was from you :)

https://github.com/junegunn/vim-plug/commit/b32169ff30eb7375453ab35eb23a14dc4e7ddd6a#diff-0467dc3d01e54437b08868e627565c40R1182

Anyway, looking at `:help job_start`, we are advised to just pass the command string to the function on Windows?

```diff
diff --git a/plug.vim b/plug.vim
index b245aa7..08221c9 100644
--- a/plug.vim
+++ b/plug.vim
@@ -1163,8 +1163,8 @@ function! s:spawn(name, cmd, opts)
   let job = { 'name': a:name, 'running': 1, 'error': 0, 'lines': [''],
             \ 'new': get(a:opts, 'new', 0) }
   let s:jobs[a:name] = job
-  let argv = add(s:is_win ? ['cmd', '/c'] : ['sh', '-c'],
-               \ has_key(a:opts, 'dir') ? s:with_cd(a:cmd, a:opts.dir) : a:cmd)
+  let cmd = has_key(a:opts, 'dir') ? s:with_cd(a:cmd, a:opts.dir) : a:cmd
+  let argv = s:is_win ? cmd : ['sh', '-c', cmd]
 
   if s:nvim
     call extend(job, {
@@ -1177,7 +1177,7 @@ function! s:spawn(name, cmd, opts)
     else
       let job.running = 0
       let job.error   = 1
-      let job.lines   = [jid < 0 ? argv[0].' is not executable' :
+      let job.lines   = [jid < 0 ? 'Failed to execute '.cmd :
             \ 'Invalid arguments (or job table is full)']
     endif
   elseif s:vim8
```

@tjharman Can you check if the above patch fixes the problem?

**Comment by tjharman** [comment]
This seems to make things worse:

:PlugUpdate

```
- Finishing ... Done!
x badwolf:
    Failed to start job
x scratch.vim:
    Failed to start job
x vim-peekaboo:
    Failed to start job
x vim-buffergator:
    Failed to start job
x twitvim:
    OK
x vim-colors-solarized:
    Failed to start job
x vim-junos-syntax:
    Failed to start job
x vim-grepper:
    Failed to start job
x vim-airline-themes:
    Failed to start job
x vim-sensible:
    Failed to start job
x gruvbox:
    Failed to start job
x vim-mucomplete:
    Failed to start job
x ctrlp.vim:
    Failed to start job
x vim-airline:
    OK
x vim-unimpaired:
    Failed to start job
x vim-dirvish:
    Failed to start job
```

**Comment by junegunn** [comment]
Hmm, this could be a bug of Vim. With the above patch, I can confirm that vim-plug generates correct commands that work fine when run manually. But for some reason, `job_start()` fails to run the commands.

```vim
function! JobCallback(self, data) abort
  echom string([a:self, a:data])
endfunction

let command = printf('git clone "https://github.com/junegunn/seoul256.vim.git" "%s\vimfiles\plugged yolo\seoul256.vim" 2>&1', $HOME)
let j = job_start(command, {'out_cb': 'JobCallback', 'exit_cb': 'JobCallback'})
" [process #### dead, 129]
```

**Comment by mattn** [comment]
Because `2>&1` is shell word. job_start doesn't use shell. On Windows, it doesn't use cmd.exe

**Comment by junegunn** [comment]
Thanks for the comment @mattn. `job_start` works if I remove the part. Hmm, but that means we can't easily drop `cmd /c`, because there are several places where we use "shell" constructs such as `2>&1` and `&&`.

**Comment by junegunn** [comment]
I was able to workaround the problem by using a temporary batch file containing the command to run. Please let me know if you run into any issues or know better ways to handle this.

**Comment by tjharman** [comment]
This has fixed the issue, thank you.
