### ISSUE TITLE
Errors when loading nerdtree

### ISSUE THREAD

**Issue by HiddenPython** [junegunn/vim-plug#568]
**Env:**
- OS: Ubuntu 16.04.1 LTS
- NVIM: 0.2.0-dev
- nerdtree: 5.0 or master
- vim-plug: master or 0.9.0

Similar errors also happen when loading neocomplete.vim. Other plugins, eg neomake and tagbar, are all right. All these plugins including nerdtree work with pathogen without any issue in the same env.

**Error msgs:**
```
E121: Undefined variable: g:NERDTreeSortOrder
E116: Invalid arguments for function index(g:NERDTreeSortOrder, '*')
E15: Invalid expression: index(g:NERDTreeSortOrder, '*')
Error detected while processing /home/leo/configs/dotfiles/nvim/plugin/nerdtree/lib/nerdtree/tree_dir_node.vim:
line    6:
E121: Undefined variable: g:NERDTreeFileNode
E116: Invalid arguments for function copy(g:NERDTreeFileNode)
E15: Invalid expression: copy(g:NERDTreeFileNode)
line    7:
E121: Undefined variable: s:TreeDirNode
E15: Invalid expression: s:TreeDirNode
line   11:
E121: Undefined variable: s:TreeDirNode
line   12:
E121: Undefined variable: b:NERDTree
E15: Invalid expression: b:NERDTree.root
line   13:
E121: Undefined variable: currentNode
E15: Invalid expression: currentNode.parent != {}
line   16:
E133: :return not inside a function
line   17:
E193: :endfunction not inside a function
line   20:
E121: Undefined variable: s:TreeDirNode
line   21:
E121: Undefined variable: s:TreeDirNode
line   22:
E121: Undefined variable: a:0
E15: Invalid expression: a:0 ? a:1 : {}
line   23:
E121: Undefined variable: self
line   24:
E121: Undefined variable: self
line   25:
E121: Undefined variable: self
line   26:
E193: :endfunction not inside a function
line   34:
E121: Undefined variable: s:TreeDirNode
line   35:
E121: Undefined variable: self
E116: Invalid arguments for function add
line   36:
E121: Undefined variable: self
E15: Invalid expression: self
```

**Comment by Shougo** [comment]
You should upload the init.vim.

**Comment by HiddenPython** [comment]
**My whole init.vim, which is quite minimum as I am trying vim-plug:**
```
call plug#begin('~/.config/nvim/plugin')

Plug 'neomake/neomake'
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/nerdtree'
Plug 'Shougo/neocomplete.vim'
Plug 'majutsushi/tagbar'

" Initialize plugin system
call plug#end()
```

**Comment by junegunn** [comment]
You're not supposed to install plugins inside `~/.config/nvim/plugin` or any `plugin` directory under any path included in `&runtimepath` (see `:help &runtimepath` for the details). Every Vimscript file inside `plugin` directory will be loaded unconditionally and it's certainly not what you want.

Manually remove the installed plugins, and reinstall them in the suggested path `~/.local/share/nvim/plugged` instead.

In the meanwhile, vim-plug can be improved to prevent such user errors.

**Comment by HiddenPython** [comment]
Thanks a lot for your helpful information and prompt reply, junegunn and shougo. I can confirm the solution works. Plug looks very impressive and I quite like it so far. I will star it.

One thing I don't quite understand is that why the same setup doesn't encounter the same issue with Pathogen? Any idea?

**Comment by junegunn** [comment]
I think you're confused somehow. You should have the same issue with pathogen.

```vim
mkdir -p ~/.config/nvim/plugin/vim-foobar/autoload
echo 'echom "foobar loaded"' > ~/.config/nvim/plugin/vim-foobar/autoload/foobar.vim
```

`autoload/foobar.vim` will be loaded unconditionally, when it shouldn't.
