### ISSUE TITLE
s:preview_commit() doesn't work in the fish shell

### ISSUE THREAD

**Issue by nhooyr** [junegunn/vim-plug#572]
https://github.com/junegunn/vim-plug/blob/d5e9f91c7baae9f17a68c093500d51e478cf7f50/plug.vim#L2291 doesn't run correctly on fish because it uses `; and` to run a command if the previous one was successful.

**Comment by junegunn** [comment]
Nice find, thanks for the report. I just pushed the fix which temporarily switches `&shell` to `sh`.
