### ISSUE TITLE
How to do post activate action?

### ISSUE THREAD

**Issue by rawaludin** [junegunn/vim-plug#573]
After I activate my tagbar, I want to set 
```
let g:airline#extensions#tagbar#enabled = 1
```

Currently I only have this 
```
Plug 'majutsushi/tagbar', { 'on': ['TagbarToggle'] } 
```

My goal is to lazy load tagbar and still make airline work by setting tagbar options on airline default to 0. But, when first time majutsushi/tagbar activated, I want to change that option to 1.

How can I do this?
Thanks.. :)

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [x] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
`User PLUGIN_NAME` auto command is triggered when a plugin is lazy-loaded, so:

```vim
autocmd! User tagbar echom 'tagbar loaded'
```

Reference: https://github.com/junegunn/vim-plug#on-demand-loading-of-plugins
