### ISSUE TITLE
:PlugUpdate hang

### ISSUE THREAD

**Issue by jonleopard** [junegunn/vim-plug#576]
Hello! This is probably an error on my part and not a bug. I'm still very new to vim and customising.

Vim-plug hangs for some reason when I run :PlugUpdate. I thought this might be caused by a missing repo, but when I run :PlugUpdate 1, each plugin updates without any freezing. However, when I omit the thread value, it freezes. Here's a recording of this happening:
https://www.dropbox.com/s/s65zali32iukpme/plugupdate-3.mov?dl=0

Sorry if this is a silly question, any assistance would be greatly appreciated :)

Cheers!

```
NVIM 0.1.7
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion
 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wn
o-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong
 -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tm
p/neovim-20161128-6030-fehc8d/neovim-0.1.7/build/config -I/tmp/neovim-20161128-6
030-fehc8d/neovim-0.1.7/src -I/usr/local/include -I/usr/local/include -I/usr/loc
al/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr
/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20161128-
6030-fehc8d/neovim-0.1.7/build/src/nvim/auto -I/tmp/neovim-20161128-6030-fehc8d/
neovim-0.1.7/build/include
Compiled by jon@Jons-MacBook-Air.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.7/share/nvim"
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [X] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [X] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [X] Neovim

**Comment by junegunn** [comment]
That's strange. A few basic things:
- Make sure that you have the latest version of vim-plug and Neovim (0.1.7. is fine)
- Comment out everything but the plug section (`plug#begin()` ~ `plug#end()`) in your init.vim and see if it helps
- If the installer does not show any progress, open another terminal and see if the corresponding git processes are running. i.e. `ps -ef | grep git`

**Comment by jonleopard** [comment]
Someone over at reddit pointed me to this issue:
https://github.com/neovim/neovim/issues/5681

I ran: brew reinstall --without-jemalloc neovim

:PlugUpdate seems to be working now. Weird! Anyways thanks for looking into this :)
