### ISSUE TITLE
Post hook issue for the plugin YouCompleteMe

### ISSUE THREAD

**Issue by jiangjianshan** [junegunn/vim-plug#578]
Hello，

    My GVim version is 8.0.160, which is running on Windows 7 SP1. The Vim-Plug setting on my _vimrc is as folloiwng:
![image](https://cloud.githubusercontent.com/assets/20179047/21760393/baf1c7aa-d686-11e6-98db-f752cf6ac233.png)

    After I run the command :PlugUpdate! on the Vim, for handling of the post hook for Plugin YouCompleteMe, it throw the following window.
![image](https://cloud.githubusercontent.com/assets/20179047/21760439/0a22b046-d687-11e6-976d-3ec48413e347.png)

    As you seen, there two issues at here:
1. The current directory is "C:\Windows\System32" but not "D:\Vim\vimfiles\plugged\YouCompleteMe".
2. "ERROR: ycmd library is currently in use." on the CMD window.

    What is the reason for above issues and how to solve them?

Kindly regards,
Tomas Janssen

**Comment by junegunn** [comment]
1. `C:\Windows\System32\cmd.exe` is the full path of `cmd.exe`, not current working directory. Directory is correct. I can tell that because it found `install.py`.
2. I have no idea. Have you tried reaching out to the maintainers of YCM?

**Comment by vheon** [comment]
> I have no idea. Have you tried reaching out to the maintainers of YCM?

@junegunn I think I can respond to this: when you are installing YCM we re-compile the ycmd server which has a compiled component. Now that component is loaded when YCM is in use and while on *nixes a loaded library can be swapped without problem on Windows loaded libraries are actually locked. So you are in vim with YCM loaded (hence the ycmd library is locked) and you're trying to remove it and re-compile it. So to make it short: on Windows you have to run the `install.py` script outside of vim and with YCM not loaded by any instance of vim.

**Comment by jiangjianshan** [comment]
@junegunn , @vheon , Thanks.

**Comment by jiangjianshan** [comment]
@vheon, I have found that there is different behaviour on my another system on same laptop, which is openSUSE Leap 42.2. The trace are following:

-------------------------------------------------- start -------------------------------------------------------------
error: Your local changes to the following files would be overwritten by checkout:                                                                                                           
        .gitignore                                                                                                                                                                           
        .travis.yml                                                                                                                                                                          
        TESTS.md                                                                                                                                                                             
        ci/appveyor/appveyor_install.bat                                                                                                                                                     
        ci/travis/travis_install.linux.sh                                                                                                                                                    
        codecov.yml                                                                                                                                                                          
        cpp/BoostParts/CMakeLists.txt                                                                                                                                                        
        cpp/BoostParts/boost/atomic/detail/atomic_template.hpp                                                                                                                               
        cpp/BoostParts/boost/atomic/detail/config.hpp                                                                                                                                        
        cpp/BoostParts/boost/atomic/detail/ops_emulated.hpp                                                                                                                                  
        cpp/BoostParts/boost/atomic/detail/ops_gcc_alpha.hpp                                                                                                                                 
        cpp/BoostParts/boost/atomic/detail/ops_gcc_arm.hpp
        cpp/BoostParts/boost/atomic/detail/ops_gcc_atomic.hpp
        cpp/BoostParts/boost/atomic/detail/ops_gcc_ppc.hpp
        cpp/BoostParts/boost/atomic/detail/ops_gcc_sparc.hpp
        cpp/BoostParts/boost/atomic/detail/ops_gcc_sync.hpp
        cpp/BoostParts/boost/atomic/detail/ops_gcc_x86.hpp
        cpp/BoostParts/boost/atomic/detail/ops_gcc_x86_dcas.hpp
        cpp/BoostParts/boost/atomic/detail/ops_linux_arm.hpp
        cpp/BoostParts/boost/atomic/detail/ops_msvc_arm.hpp
        cpp/BoostParts/boost/atomic/detail/ops_msvc_x86.hpp
        cpp/BoostParts/boost/atomic/detail/ops_windows.hpp
        cpp/BoostParts/boost/bind/arg.hpp
        cpp/BoostParts/boost/config/compiler/intel.hpp
        cpp/BoostParts/boost/config/compiler/nvcc.hpp
        cpp/BoostParts/boost/config/compiler/sunpro_cc.hpp
        cpp/BoostParts/boost/config/compiler/visualc.hpp
        cpp/BoostParts/boost/config/stdlib/dinkumware.hpp
        cpp/BoostParts/boost/config/stdlib/libcomo.hpp
        cpp/BoostParts/boost/config/stdlib/libcpp.hpp
        cpp/BoostParts/boost/config/stdlib/libstdcpp3.hpp
        cpp/BoostParts/boost/config/stdlib/modena.hpp
        cpp/BoostParts/boost/config/stdlib/msl.hpp
        cpp/BoostParts/boost/config/stdlib/roguewave.hpp
        cpp/BoostParts/boost/config/stdlib/sgi.hpp
        cpp/BoostParts/boost/config/stdlib/stlport.hpp
        cpp/BoostParts/boost/config/stdlib/vacpp.hpp
        cpp/BoostParts/boost/container/detail/copy_move_algo.hpp
        cpp/BoostParts/boost/container/detail/iterators.hpp
        cpp/BoostParts/boost/container/detail/pair.hpp
        cpp/BoostParts/boost/container/detail/variadic_templates_tools.hpp
        cpp/BoostParts/boost/container/detail/workaround.hpp
        cpp/BoostParts/boost/container/uses_allocator_fwd.hpp
        cpp/BoostParts/boost/container/vector.hpp
        cpp/BoostParts/boost/core/lightweight_test.hpp
        cpp/BoostParts/boost/current_function.hpp
        cpp/BoostParts/boost/date_time/gregorian/greg_facet.hpp
        cpp/BoostParts/boost/exception/detail/error_info_impl.hpp
        cpp/BoostParts/boost/exception/errinfo_api_function.hpp
        cpp/BoostParts/boost/exception/errinfo_errno.hpp
        cpp/BoostParts/boost/exception/exception.hpp
        cpp/BoostParts/boost/exception/get_error_info.hpp
        cpp/BoostParts/boost/exception/info.hpp
        cpp/BoostParts/boost/filesystem/operations.hpp
        cpp/BoostParts/boost/filesystem/path.hpp
        cpp/BoostParts/boost/format/alt_sstream_impl.hpp
        cpp/BoostParts/boost/functional/hash/detail/hash_float.hpp
        cpp/BoostParts/boost/functional/hash/hash.hpp
        cpp/BoostParts/boost/graph/adjacency_iterator.hpp
        cpp/BoostParts/boost/graph/adjacency_list.hpp
        cpp/BoostParts/boost/graph/properties.hpp
        cpp/BoostParts/boost/graph/reverse_graph.hpp
        cpp/BoostParts/boost/interprocess/detail/nothrow.hpp
        cpp/BoostParts/boost/interprocess/detail/shared_dir_helpers.hpp
        cpp/BoostParts/boost/interprocess/detail/workaround.hpp
        cpp/BoostParts/boost/interprocess/mapped_region.hpp
        cpp/BoostParts/boost/interprocess/streams/bufferstream.hpp
        cpp/BoostParts/boost/intrusive/detail/workaround.hpp
        cpp/BoostParts/boost/lexical_cast/detail/converter_lexical_streams.hpp
        cpp/BoostParts/boost/lexical_cast/detail/converter_numeric.hpp
        cpp/BoostParts/boost/lockfree/detail/prefix.hpp
        cpp/BoostParts/boost/lockfree/queue.hpp
        cpp/BoostParts/boost/lockfree/stack.hpp
        cpp/BoostParts/boost/move/detail/move_helpers.hpp
        cpp/BoostParts/boost/move/detail/workaround.hpp
        cpp/BoostParts/boost/move/make_unique.hpp
        cpp/BoostParts/boost/mpi/communicator.hpp
        cpp/BoostParts/boost/mpi/datatype.hpp
        cpp/BoostParts/boost/optional/detail/optional_config.hpp
        cpp/BoostParts/boost/optional/detail/optional_reference_spec.hpp
        cpp/BoostParts/boost/optional/optional.hpp
        cpp/BoostParts/boost/pending/container_traits.hpp
        cpp/BoostParts/boost/property_map/parallel/parallel_property_maps.hpp
        cpp/BoostParts/boost/property_map/property_map.hpp
        cpp/BoostParts/boost/python/converter/registered.hpp
        cpp/BoostParts/boost/python/converter/shared_ptr_from_python.hpp
        cpp/BoostParts/boost/python/converter/shared_ptr_to_python.hpp
        cpp/BoostParts/boost/python/detail/value_is_shared_ptr.hpp
        cpp/BoostParts/boost/python/make_constructor.hpp
        cpp/BoostParts/boost/python/object/class_metadata.hpp
        cpp/BoostParts/boost/python/object/make_ptr_instance.hpp
        cpp/BoostParts/boost/python/object/pointer_holder.hpp
        cpp/BoostParts/boost/python/object/py_function.hpp
        cpp/BoostParts/boost/python/object_core.hpp
        cpp/BoostParts/boost/python/str.hpp
        cpp/BoostParts/boost/python/to_python_indirect.hpp
        cpp/BoostParts/boost/python/to_python_value.hpp
        cpp/BoostParts/boost/range/size_type.hpp
        cpp/BoostParts/boost/regex/pending/unicode_iterator.hpp
        cpp/BoostParts/boost/smart_ptr/bad_weak_ptr.hpp
        cpp/BoostParts/boost/smart_ptr/detail/sp_counted_base.hpp
        cpp/BoostParts/boost/smart_ptr/detail/sp_counted_base_clang.hpp
        cpp/BoostParts/boost/smart_ptr/detail/spinlock.hpp
        cpp/BoostParts/boost/smart_ptr/make_shared_object.hpp
        cpp/BoostParts/boost/test/execution_monitor.hpp
        cpp/BoostParts/boost/test/impl/compiler_log_formatter.ipp
        cpp/BoostParts/boost/test/impl/execution_monitor.ipp
        cpp/BoostParts/boost/test/impl/framework.ipp
        cpp/BoostParts/boost/test/impl/test_tree.ipp
        cpp/BoostParts/boost/test/impl/unit_test_parameters.ipp
        cpp/BoostParts/boost/test/included/unit_test.hpp
        cpp/BoostParts/boost/test/tools/collection_comparison_op.hpp
        cpp/BoostParts/boost/test/tools/cstring_comparison_op.hpp
        cpp/BoostParts/boost/test/tools/fpc_op.hpp
        cpp/BoostParts/boost/test/tree/test_case_template.hpp
        cpp/BoostParts/boost/test/unit_test_log_formatter.hpp
        cpp/BoostParts/boost/test/unit_test_parameters.hpp
        cpp/BoostParts/boost/test/utils/is_cstring.hpp
        cpp/BoostParts/boost/test/utils/is_forward_iterable.hpp
        cpp/BoostParts/boost/test/utils/iterator/token_iterator.hpp
        cpp/BoostParts/boost/test/utils/runtime/cla/parser.hpp
        cpp/BoostParts/boost/test/utils/runtime/parameter.hpp
        cpp/BoostParts/boost/thread/pthread/condition_variable.hpp
        cpp/BoostParts/boost/type_index/detail/compile_time_type_info.hpp
        cpp/BoostParts/boost/unordered/detail/allocate.hpp
        cpp/BoostParts/boost/unordered/detail/buckets.hpp
        cpp/BoostParts/boost/unordered/detail/equivalent.hpp
        cpp/BoostParts/boost/unordered/detail/extract_key.hpp
        cpp/BoostParts/boost/unordered/detail/fwd.hpp
        cpp/BoostParts/boost/unordered/detail/map.hpp
        cpp/BoostParts/boost/unordered/detail/set.hpp
        cpp/BoostParts/boost/unordered/detail/table.hpp
        cpp/BoostParts/boost/unordered/detail/unique.hpp
        cpp/BoostParts/boost/unordered/detail/util.hpp
        cpp/BoostParts/boost/unordered/unordered_map.hpp
        cpp/BoostParts/boost/unordered/unordered_set.hpp
        cpp/BoostParts/boost/utility/compare_pointees.hpp
        cpp/BoostParts/boost/version.hpp
        cpp/BoostParts/libs/atomic/src/lockpool.cpp
        cpp/BoostParts/libs/filesystem/src/operations.cpp
        cpp/BoostParts/libs/filesystem/src/path.cpp
        cpp/BoostParts/libs/filesystem/src/unique_path.cpp
        cpp/BoostParts/libs/python/src/str.cpp
        cpp/CMakeLists.txt
        cpp/ycm/CMakeLists.txt
        cpp/ycm/ClangCompleter/CompilationDatabase.cpp
        cpp/ycm/ClangCompleter/CompilationDatabase.h
        cpp/ycm/CustomAssert.cpp
        cpp/ycm/CustomAssert.h
        cpp/ycm/standard.h
        cpp/ycm/tests/CMakeLists.txt
        cpp/ycm/ycm_core.cpp
        test_requirements.txt
        third_party/tern_runtime/package.json
        ycmd/completers/all/tests/__init__.py
        ycmd/completers/cpp/flags.py
        ycmd/completers/cpp/tests/__init__.py
        ycmd/completers/general/tests/__init__.py
        ycmd/completers/javascript/tern_completer.py
        ycmd/extra_conf_store.py
        ycmd/handlers.py
        ycmd/identifier_utils.py
        ycmd/request_wrap.py
        ycmd/tests/clang/__init__.py
        ycmd/tests/clang/debug_info_test.py
        ycmd/tests/clang/flags_test.py
        ycmd/tests/clang/get_completions_test.py
        ycmd/tests/client_test.py
        ycmd/tests/get_completions_test.py
        ycmd/tests/identifier_completer_test.py
        ycmd/tests/identifier_utils_test.py
        ycmd/tests/misc_handlers_test.py
        ycmd/tests/testdata/.ycm_extra_conf.py
        ycmd/utils.py
Please commit your changes or stash them before you switch branches.
Aborting
Unable to checkout 'd19f9c5e8e5ca47a9784a78a3aa39a49f8c3e7c6' in submodule path 'third_party/ycmd'

shell returned 1
------------------------------------------------------------- end ----------------------------------------------

      How to solve this problem on my Linux system?

**Comment by vheon** [comment]
looks like you have changes in the YouCompleteMe repo. Did you do something by hand?

**Comment by jiangjianshan** [comment]
@vheon , I think I have directly copied the YouCompleteMe folder from other drive to ~/.vim/plugged/YouCompleteMe before.  Any way I can do a fully revert the local change by git command for the repo and its submodules?

**Comment by vheon** [comment]
@jiangjianshan why copying plugin directory from one drive to another if you use a plugin manager that downloads the code for you? :confused: I think you either delete the directory and start fresh (maybe is better to avoid other problems ) or I think if you do `git reset --hard HEAD && git submodule update --init --recursive` but again, vim-plug will take care of it for you if you start fresh.

**Comment by junegunn** [comment]
@vheon Thanks for the comment.

@jiangjianshan I believe you can figure it out now.

**Comment by jiangjianshan** [comment]
@vheon , Previously I have reinstalled my Linux system and want to avoid to wait for a long time to download the whole YouCompleteMe plugin again, so that I copied the previous .vim folder, which included the YouCompleteMe folder, from another drive. Now I follow your suggestion to do a fresh install for the YouCompleteMe plugin, it is work now for my setting on ~/.vimrc. Thanks very much.
    But for the Windows system, I still have to find the solution to solve it.

**Comment by vheon** [comment]
> But for the Windows system, I still have to find the solution to solve it.

I've already given you the solution: do the install outside of vim

**Comment by jiangjianshan** [comment]
@vheon , your solution is to run install.py script outside of vim, this is the way what I have done before I use Vim-Plug. This morning I have found another solution. It is I just type "vim +PlugInstall +qall" on the cmd windows. The reason why I use PlugInstall but not PlugUpdate, is because I have just deleted the whole YouCompleteMe folder inside $VIM\vimfiles\plugged, and do a fresh install for YouCompleteMe. It is just want to test whether I can use the following setting for Vim-Plug.
![image](https://cloud.githubusercontent.com/assets/20179047/21918316/07717600-d98b-11e6-8cec-ff3b260e9b0e.png)

    Now, the problem has been solved I think. Later I have put this comand but change "+PlugInstall" to "+PlugUpdate" into my script which name is build-vim.cmd. After test, It works well now. 

      The whole scripts is as below:

------------------------------------- start ------------------------------------------------
@echo off
@rem to build big Vim with OLE, Perl, Python, Ruby and Tcl

set INCLUDE=D:\GnuWin64\include;D:\Lua\include;D:\Ruby\include;%INCLUDE%
set LIB=D:\GnuWin64\lib;D:\Lua\lib;D:\Ruby\lib;%LIB%
set TOOLDIR=D:\
set INSTALL_DIR=D:\Vim
set VIM_SRC_DIR=E:\Gits\vim

cd /d %~dp0

@rem uninstall previous version if it exist
if exist %INSTALL_DIR%\Vim80 (
    cd /d %INSTALL_DIR%\Vim80
    uninstal
)

if exist %VIM_SRC_DIR% (
  cd /d %VIM_SRC_DIR%
  git fetch --all
  git reset --hard origin/master
) else (
  echo "Downloading Vim ..."
  git clone https://github.com/vim/vim.git E:\Gits\vim
)

cd /d %VIM_SRC_DIR%\src

if exist .\ObjCULYHTRAMD64 rmdir /s /q .\ObjCULYHTRAMD64
if exist .\ObjGOULYHTRAMD64 rmdir /s /q .\ObjGOULYHTRAMD64


@rem build for no-GUI version
nmake -f Make_mvc.mak CPU=AMD64 FEATURES=HUGE debug=no GUI=no MBYTE=yes IME=yes DYNAMIC_IME=yes GIME=yes CSCOPE=yes ICONV=yes GETTEXT=yes NETBEANS=yes OPTIMIZE=MAXSPEED SNIFF=yes POSCRIPT=yes PERL=%TOOLDIR%Perl DYNAMIC_PERL=yes PERL_VER=524 PYTHON=%TOOLDIR%python27 DYNAMIC_PYTHON=yes PYTHON_VER=27 PYTHON3=%TOOLDIR%python35 DYNAMIC_PYTHON3=yes PYTHON3_VER=35  LUA=%TOOLDIR%Lua DYNAMIC_LUA=yes LUA_VER=53 RUBY=%TOOLDIR%Ruby DYNAMIC_RUBY=yes RUBY_VER=23 RUBY_VER_LONG=2.3.0 RUBY_PLATFORM=x64-mswin64_90 TCL=%TOOLDIR%Tcl TCL_VER=86 TCL_VER_LONG=8.6 DYNAMIC_TCL=yes %1

@rem build for GUI version
nmake -f Make_mvc.mak CPU=AMD64 FEATURES=HUGE debug=no GUI=yes OLE=yes MBYTE=yes IME=yes DYNAMIC_IME=yes GIME=yes CSCOPE=yes ICONV=yes GETTEXT=yes NETBEANS=yes OPTIMIZE=MAXSPEED SNIFF=yes POSCRIPT=yes PERL=%TOOLDIR%Perl DYNAMIC_PERL=yes PERL_VER=524 PYTHON=%TOOLDIR%python27 DYNAMIC_PYTHON=yes PYTHON_VER=27 PYTHON3=%TOOLDIR%python35 DYNAMIC_PYTHON3=yes PYTHON3_VER=35  LUA=%TOOLDIR%Lua DYNAMIC_LUA=yes LUA_VER=53 RUBY=%TOOLDIR%Ruby DYNAMIC_RUBY=yes RUBY_VER=23 RUBY_VER_LONG=2.3.0 RUBY_PLATFORM=x64-mswin64_90 TCL=%TOOLDIR%Tcl TCL_VER=86 TCL_VER_LONG=8.6 DYNAMIC_TCL=yes %1

@rem Copy the "runtime" files into "Vim80"
xcopy /I /Y /F /E ..\.\runtime\* %INSTALL_DIR%\Vim80

@rem Copy the new binaries into the "Vim80" directory
xcopy /I /Y /F *.exe %INSTALL_DIR%\Vim80
xcopy /I /Y /F vimtbar.dll %INSTALL_DIR%\Vim80
xcopy /I /Y /F .\GvimExt\gvimext.dll %INSTALL_DIR%\Vim80
xcopy /I /Y /F .\xxd\xxd.exe %INSTALL_DIR%\Vim80

@rem Copy vimtutor into "Vim80"
xcopy /I /Y /F ..\vimtutor.* %INSTALL_DIR%\Vim80

@rem install vim
cd /d %INSTALL_DIR%\Vim80
install

xcopy /F /Y E:\Releases\_vimrc %INSTALL_DIR%
xcopy /F /Y E:\Releases\.ycm_extra_conf.py %INSTALL_DIR%

@rem Update the plugins
vim +PlugUpdate +qall

cd /d %~dp0
--------------------------------------------- end --------------------------------------

     Thanks for your hints before to help me to solve this issue.
