### ISSUE TITLE
Help installing vim-plug in gVim under Windows 10 please

### ISSUE THREAD

**Issue by carlca** [junegunn/vim-plug#580]
Explain the problem here ...
Using Windows 10 Pro 64 bit insider preview build 15007

I have followed the Powershell instructions to download the Plug.vim file which is now sitting in C:\Users\Carl\vimfiles\autoload . So far so good (I think). However, I am making changes to my _vimrc file (the Windows equivalent of .vimrc) which is situated in C:\Program Files (x86)\Vim . Any changes I make here such as adding:
`call plug#begin()`
`Plug 'fatih/vim-go', { 'tag': '*' }`
`call plug#end()`

all result in error messages when gVim starts.
Can I issue a : command in gVim to confirm that the vim-plug files has been correctly found and loaded?
How can I complete the installation of vim-plug so that I can get vim-go up and running?

------------------------------

```
Cannot figure out how to get :version info here, either via clipboard or disk. Sorry.
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [X] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [X] Windows
- Vim:
    - [ ] Terminal Vim
    - [X] GVim
    - [ ] Neovim

**Comment by nfischer** [comment]
@carlca could you provide the error message? Does it work without the `, { 'tag': '*' }` at the end? Could you at least provide the version number of vim (e.g. vim 8.0.95)?

**Comment by carlca** [comment]
Vim is version 8.0.69

I've tried your suggestion and the error messages have disappeared and :scriptnames now reveals the fact that win-plug has been loaded. So thanks very much for that. I've just discovered that the :PlugInstall command is case sensitive, as that is working now. Thanks again for your help, I think I should be able to load any plugin I want now!!

**Comment by junegunn** [comment]
@nfischer Thanks for the comment.

@carlca Are you sure that removing `tag` option helped? I'm doubtful because you said that you had errors during startup, but vim-plug doesn't do anything with the option until you start the installer.
