### ISSUE TITLE
Support installing multiple plugins from same repo when using 'rtp'

### ISSUE THREAD

**Issue by dbarnett** [junegunn/vim-plug#582]
I'm wanting to install one plugin from the root of a GitHub repository and another helper plugin from a subdirectory using vim-plug's `rtp` option:
```vim
Plug 'google/vim-maktaba'
Plug 'google/vim-maktaba', {'as': 'helloworld', 'rtp': 'examples/helloworld'}
```
but the second install from the same repository seems to override the first. Is there a way I can achieve that effect of having both plugins independently installed from that repo?

- Type:
    - [ ] Bug
    - [X] Enhancement
    - [X] Feature Request
    - [ ] Question
- OS:
    - [X] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [X] Terminal Vim
    - [X] GVim
    - [X] Neovim

**Comment by junegunn** [comment]
This should work, using `g:plugs` data structure incrementally built with `Plug` statements.

```vim
Plug 'google/vim-maktaba'
Plug g:plugs['vim-maktaba'].dir.'examples/helloworld'
```

vim-plug will interpret the second line and register "unmanaged" plugin named "helloworld".

**Comment by junegunn** [comment]
Oh wait, you want them to be separately installed? Then what you did above is correct. vim-plug will clone them into two separate directories. What problem did you have exactly?

> the second install from the same repository seems to override the first.

Can you elaborate?

**Comment by dbarnett** [comment]
I can try some variations on my repro case to be sure, but what I saw was the first path wasn't on rtp after `plug#end()` and then a lot of errors about its autoload functions being missing.

**Comment by dbarnett** [comment]
Yeah, I confirmed I just can't get the first plugin (vim-maktaba itself) to be on runtimepath with any variation of the `'rtp': 'examples/helloworld'` pattern in the description above, with or without the `'as': 'helloworld'`. It only creates the vim-maktaba directory from the first line in plugged but it's only the 'helloworld' path I see on runtimepath:
```vim
:set runtimepath?
  runtimepath=~/.vim,~/.vim/plugged/vim-maktaba/examples/helloworld/,/var/lib/vim/addons,
/usr/share/vim/vimfiles,/usr/share/vim/vim80,/usr/share/vim/vimfiles/after,/var/lib/vim/
addons/after,~/.vim/after
```

Your `g:plugs['vim-maktaba'].dir.'examples/helloworld'` suggestion does seem to work alright, though.

FWIW, I found and reported a similar problem in Vundle: VundleVim/Vundle.vim#780.

**Comment by junegunn** [comment]
Works for me

```vim
call plug#begin('~/.vim/plugged-test')
Plug 'google/vim-maktaba'
Plug 'google/vim-maktaba', {'as': 'helloworld', 'rtp': 'examples/helloworld'}
call plug#end()
```

```
  runtimepath=~/.vim,~/.vim/plugged-test/vim-maktaba/,~/.vim/plugged-test/helloworld/examples/helloworld/,/usr/local/share/vim/vimfiles,/usr/local/share/vim/vim80,/usr/local/share/v
im/vimfiles/after,~/.vim/after
        Last set from ~/.vim/autoload/plug.vim
```

**Comment by dbarnett** [comment]
Oh, I updated my copy of vim-plug and it does work now (cloning a 2nd copy of the repo on `:PlugInstall`). Thanks!

BTW, There's no easy way to identify the version of vim-plug to include in bug reports, is there?

**Comment by junegunn** [comment]
No. Maybe I should request users to `:PlugUpgrade` before submitting an issue. We almost never make breaking changes, so it's not an unreasonable demand.

**Comment by pingsoli** [comment]
@junegunn , hi, sorry to bother you, I got some troubles, please give me some advice.

The below is my github repo directory tree.
```
vim-plugins/
├── a.vim
│   ├── plugin
│   └── README
├── BufOnly.vim
│   ├── plugin
│   └── README
└── readme.md
```

the following is my .vimrc.
```
Plug 'pingsoli/vim-plugins', {'as': 'a.vim', 'rtp': 'a.vim'}
Plug 'pingsoli/vim-plugins', {'as': 'BufOnly.vim', 'rtp': 'BufOnly.vim'}
```
the above settings will create a duplicate same as vim-plugins directory, **I just want only one copy.**


amd, I want the `rtp` add the subdirectory name automatically, like this.
```
rtp += vim-plugins/BufOnly.vim
rtp += vim-plugins/a.vim
```
any idea to do this ?
