### ISSUE TITLE
Error when installing plugins (NeoVim)

### ISSUE THREAD

**Issue by sprainbrains** [junegunn/vim-plug#596]
When I try install plugin on Windows 10 I get the following error:

![nvim-qt error](https://2.downloader.disk.yandex.ru/disk/ac3be429d340606bc1d118518ee3b7c3c1551584795d44cd7a573d1ca488c169/58a5a33d/_2gIsBJm-lTIl7aq-xeBCb4qii3J5tSJrMNrehjj8MaGeA7dbXo-aPHwRwfvcLrPfZzOboQBvNe706z4XAod-A%3D%3D?uid=0&filename=2017-02-16_11-58-11.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&fsize=14632&hid=c474dd51e217e481f08910f2ca1a2af1&media_type=image&tknv=v2&etag=512ffedb133d888ea9b95e195ff72c2a)

my minimal vimrc:
```vim
call plug#begin('~/nvim/plugged')
Plug 'tomasr/molokai'
call plug#end()
```

If I use a simple Vim(gVim) everything is fine.

------------------------------

```

```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [x] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
https://github.com/junegunn/vim-plug/issues/599#issuecomment-282140942

**Comment by christianrondeau** [comment]
@sprainbrains your image seems broken ;) Can you put the actual error text you have? I think I might have the same issue, but without seeing the error it's hard to say!
