### ISSUE TITLE
incorrectly show highlight when SHA 7+ digits 

### ISSUE THREAD

**Issue by winsphinx** [junegunn/vim-plug#597]
Explain the problem here ...
after excute `:PlugUpdate` and press `D` to show the changes, when commit sha is more than 7 digits, it is not correctly shown the highlight. one picture is more than 1000 words, see the snapshot bellow.
i noticed the defination in plug.viim:
      `syn match plugSha /[0-9a-f]\{7}/ contained`
maybe because of this?

![snap](https://cloud.githubusercontent.com/assets/5674054/23052400/e074812c-f50b-11e6-8f9a-c7e90e86c195.gif)

------------------------------

```

```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [x] Windows
- Vim:
    - [ ] Terminal Vim
    - [x] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
Yes, you're right. I'll change it to 7 to 9 chars, hoping that it will never exceed 9 chars :)

**Comment by junegunn** [comment]
Fixed it, thanks for the report. Try `:PlugUpgrade` and `:PlugDiff`.
