### ISSUE TITLE
Error installing plugins with Neovim on Windows 10

### ISSUE THREAD

**Issue by nickvanderstel** [junegunn/vim-plug#599]
When trying to install plugins through `:PlugInstall` I'm encountering the following error:
```
- Finishing ... Done!
x vim-sleuth:
    fatal: could not create leading directories of '"C:\Users\nick\AppData\Local\nvim\plugged\vim-sleuth"': Invalid argument
```

My init.vim:
```
call plug#begin()
Plug 'tpope/vim-sleuth'
call plug#end()
```

Trying the same thing with gvim works fine:
```
- Finishing ... Done!
- vim-sleuth: Cloning into 'C:\vimplug\vim-sleuth'...
```
Looks to me like extra quotes are being added at some point and they are causing the error. I'm guessing the issue is actually with Neovim but I figured I would start here.

------------------------------

```
NVIM v0.2.0-686-g163ad52e
Build type: Release
Compilation: C:/msys64/mingw64/bin/gcc.exe -Wconversion -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -D__USE_MINGW_ANSI_STDIO -D_WIN32_WINNT=0x0600 -Wvla -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Optional features included (+) or not (-): -acl   +iconv    -jemalloc -tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"
```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [x] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by justinmk** [comment]
It's a known issue in neovim. 0.2. hasn't been released yet, and Windows support has not been announced...

**Comment by rmolin88** [comment]
**Workaround**: `pip2 install neovim --user && pip3 install neovim --user`
It still complains. But at list installs the plugins

**Comment by akiya64** [comment]
I have same problem in Windows 10, "PlugInstall" is not work. 
I tried `pip3 install neovim --user` and `pip3 install neovim --user` on Windows PowerShell, install process is stopped in pip3 `Visual C++ 14.0 is required / visual-cpp-build-tools`
But "PlugInstall" is worked! "PlugClean" is not worked...vim-plug can not remove folder.

```
NVIM v0.2.0-781-g59ea30ad
```

**Comment by justinmk** [comment]
See https://github.com/junegunn/vim-plug/issues/599#issuecomment-282140942

**Comment by nickvanderstel** [comment]
You say that Windows support has not been announced, yet on https://github.com/neovim/neovim/wiki/Installing-Neovim there are clear instructions for installing on Windows with no mention of it not being officially supported. Maybe a note should be added so that people are aware that Windows support is experimental at this point.

I couldn't find a related issue in neovim. Could someone link it here?

**Comment by Himura2la** [comment]
I also faced this issue. It's sad to face such a showstoppers. `pip2 install neovim --user` helps not

**Comment by justinmk** [comment]
I updated https://github.com/neovim/neovim/wiki/Installing-Neovim#windows to mention that Windows support hasn't been announced yet.

**Comment by sho-87** [comment]
Is this fix planned for neovim 0.2?

**Comment by justinmk** [comment]
Yes

**Comment by oboudry** [comment]
I have the same problem on Windows 7 Pro. I used Process Monitor from Sysinternals to try understand what was going wrong, and it looks like git is trying to clone the plugin into: 

`<NeoVim Path>\"<Plugged PATH>"`

E.g. on my computer:

`C:\Users\obou\Downloads\Neovim\bin\"C:\Users\obou\AppData\Local\nvim\plugged\phoenix.vim"`

Could be that the installation path is not formatted correctly on Windows.

**Comment by gglanzani** [comment]
It does work now with Neovim 0.2 (remember to update vim-plug).

I think it can be closed :)

**Comment by junegunn** [comment]
@gglanzani Good to hear that, thanks.

**Comment by tutysara** [comment]
I still see the issue, getting an error "Invalid plug directory"

using Neovim v0.2.1-25 with latest vim-plug on win 7

**Comment by sebpardo** [comment]
I also still have this issue with the extra quotation marks: 

    fatal: could not create leading directories of '"C:\..."': Invalid argument

Using NVIM v0.2.0-993-gee72bc24 with the latest vim-plug version on Windows 10.
