### ISSUE TITLE
Avoid git submodules in Windows hanging on "Hit any key to close this window..."

### ISSUE THREAD

**Issue by dezza** [junegunn/vim-plug#606]
To make vim-plug completely unattended while installing plugins on Windows it should avoid the "Hit any key to close this window..." for repos with submodules by not using `!` syntax which is used in the [`s:bang(cmd, ...)`](https://github.com/junegunn/vim-plug/blob/master/plug.vim#L784-L790) function used in [`s:update_finish()`](https://github.com/junegunn/vim-plug/blob/master/plug.vim#L1080)

Instead it could use the Python [Command()](https://github.com/junegunn/vim-plug/blob/master/plug.vim#L1430) class OR
`silent !` but that is the unlikely solution - my guess is that there's a good reason it's not silent so you can verify it's not failing - so I guess the Python option is the best choice?

Please advice if this could be changed so we can avoid the `cmd.exe` window awaiting ENTER on each submodule.

I will submit a commit/pullrequest if you agree.

**Comment by junegunn** [comment]
Actually `s:bang` function implements a trick for skipping "ENTER key" prompt.

https://github.com/junegunn/vim-plug/blob/master/plug.vim#L791

Seems like it's not working on Windows, right? I'd like to see a pure Vim script solution to this rather than relying on python interface which is not guaranteed to be available.

**Comment by dezza** [comment]
Oh I see.

No on my official Windows Vim this still shows the prompt

```
:version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov  6 2016 17:20:44)
MS-Windows 32-bit GUI version with OLE support
Included patches: 1-69
Compiled by mool@tororo        
```

I will be willing to experiment with fixing this later and I agree I also do as much as possible in VimScript 👍

**Comment by nzbart** [comment]
@dezza did you make much progress on this? It would make unattended installations a lot smoother...

**Comment by dezza** [comment]
@nzbart I opted for another solution (https://github.com/airblade/voom)

I guess it's pretty easy once you find the offending line.

**Comment by nzbart** [comment]
@dezza thanks; something simple like voom sounds really good... unfortunately, it's not cross-platform, which I need it to be.

**Comment by dezza** [comment]
It is for me since I utilize WSL for Windows (shell) and mac already has shell.

**Comment by janlazo** [comment]
Is this for GVim only?

**Comment by janlazo** [comment]
@junegunn I can fix this but I need `fzf#shellescape` to replace `s:shellesc` for `s:with_cd`.

**Comment by junegunn** [comment]
@janlazo I believe we can safely replace the code of `s:shellesc` with that of `fzf#shellescape`.

**Comment by janlazo** [comment]
I'm plan on using a batchfile for this but it will take awhile.
A short term fix to bypass the prompt is to prefix `g:_plug_bang` with `silent`
```viml
let g:_plug_bang = (s:is_win && has('gui_running') ? 'silent ' : '').'!'.escape(cmd, '#!%')
```

**Comment by janlazo** [comment]
If `shellxquote` is unset and `fzf#shellescape` is slightly modifed for escaping `%`, then we can run a `:!` command directly in Windows without temp files.
I'm experimenting with it for the accessing the help files for powershell in https://github.com/janlazo/dotvim8/blob/master/after/ftplugin/ps1.vim with the autoload functions in https://github.com/janlazo/dotvim8/blob/master/autoload/dotvim8.vim.
