### ISSUE TITLE
Unable to install plugins on cygwin

### ISSUE THREAD

**Issue by oscarnyl** [junegunn/vim-plug#612]
I am unable to install plugins on cygwin through calling :PlugInstall - output:
Updated. Elapsed time: 0.641096 sec.
[xxxxxxxxxxxxxxx]

- Finishing ... Done!
x completor.vim:
    fatal: destination path '/home/username/.vim/plugged/completor.vim' already exists and is not an empty directory.
x vim-fugitive:
    fatal: destination path '/home/username/.vim/plugged/vim-fugitive' already exists and is not an empty directory.
x vim-dispatch:
    fatal: destination path '/home/username/.vim/plugged/vim-dispatch' already exists and is not an empty directory.
x validator.vim:
    fatal: destination path '/home/username/.vim/plugged/validator.vim' already exists and is not an empty directory.
x vim-repeat:
    fatal: destination path '/home/username/.vim/plugged/vim-repeat' already exists and is not an empty directory.
x vim-jsx:
    fatal: destination path '/home/username/.vim/plugged/vim-jsx' already exists and is not an empty directory.
x vim-css-color:
    fatal: destination path '/home/username/.vim/plugged/vim-css-color' already exists and is not an empty directory.
x vim-desert-warm-256:
    fatal: destination path '/home/username/.vim/plugged/vim-desert-warm-256' already exists and is not an empty directory.
x vim-surround:
    fatal: destination path '/home/username/.vim/plugged/vim-surround' already exists and is not an empty directory.
x vim-sensible:
    fatal: destination path '/home/username/.vim/plugged/vim-sensible' already exists and is not an empty directory.
x omnisharp-vim:
    fatal: destination path '/home/username/.vim/plugged/omnisharp-vim' already exists and is not an empty directory.
x vim-javascript:
    fatal: destination path '/home/username/.vim/plugged/vim-javascript' already exists and is not an empty directory.
x vim-airline:
    fatal: destination path '/home/username/.vim/plugged/vim-airline' already exists and is not an empty directory.
x ctrlp.vim:
    fatal: destination path '/home/username/.vim/plugged/ctrlp.vim' already exists and is not an empty directory.
x css.vim:
    fatal: destination path '/home/username/.vim/plugged/css.vim' already exists and is not an empty directory.

The directory '/home/username/.vim/plugged' exists, but it is empty (no hidden files, either).

Possibly related, when calling :PlugUpgrade I get this output -

Error detected while processing function <SNR>8_upgrade:                                                                                                                                                                     
line   12:
E484: Can't open file /tmp/vwB0dJ5/0/plug.vim

------------------------------

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 19 2017 17:16:07)
Included patches: 1-494
Modified by <cygwin@cygwin.com>
Compiled by <cygwin@cygwin.com>
Huge version without GUI.  Features included (+) or not (-):
+acl             -clientserver    +cursorbind      +ex_extra        +gettext         +libcall         +mouse           +mouse_xterm     +persistent_undo +ruby/dyn        +tag_old_static  -toolbar         +wildmenu        -xterm_save
+arabic          +clipboard       +cursorshape     +extra_search    -hangul_input    +linebreak       -mouseshape      +multi_byte      +postscript      +scrollbind      -tag_any_white   +user_commands   +windows
+autocmd         +cmdline_compl   +dialog_con      +farsi           +iconv           +lispindent      +mouse_dec       +multi_lang      +printer         +signs           -tcl             +vertsplit       +writebackup
-balloon_eval    +cmdline_hist    +diff            +file_in_path    +insert_expand   +listcmds        -mouse_gpm       -mzscheme        +profile         +smartindent     +termguicolors   +virtualedit     -X11
-browse          +cmdline_info    +digraphs        +find_in_path    +job             +localmap        -mouse_jsbterm   +netbeans_intg   +python/dyn      +startuptime     +terminfo        +visual          -xfontset
++builtin_terms  +comments        -dnd             +float           +jumplist        +lua/dyn         +mouse_netterm   +num64           +python3/dyn     +statusline      +termresponse    +visualextra     -xim
+byte_offset     +conceal         -ebcdic          +folding         +keymap          +menu            +mouse_sgr       +packages        +quickfix        -sun_workshop    +textobjects     +viminfo         -xpm
+channel         +cryptv          +emacs_tags      -footer          +lambda          +mksession       -mouse_sysmouse  +path_extra      +reltime         +syntax          +timers          +vreplace        -xsmp
+cindent         +cscope          +eval            +fork()          +langmap         +modify_fname    +mouse_urxvt     +perl/dyn        +rightleft       +tag_binary      +title           +wildignore      -xterm_clipboard
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim80"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/usr/src/ports/vim/vim-8.0.0494-1.x86_64/build=/usr/src/debug/vim-8.0.0494-1 -fdebug-prefix-map=/usr/src/ports/vim/vim-8
.0.0494-1.x86_64/src/vim-8.0.0494=/usr/src/debug/vim-8.0.0494-1 -fstack-protector-strong -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -fstack-protector  -fstack-protector-strong -L/usr/local/lib -Wl,--as-needed -o vim.exe        -lm    -lncursesw -liconv -lacl -lattr -lintl   -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-bas
e -fstack-protector-strong  -L/usr/lib/perl5/5.22/x86_64-cygwin-threads/CORE -lperl -lpthread -ldl -lcrypt

```

- Type:
    - [X] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [X] Windows
- Vim:
    - [X] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
Possibly a duplicate of #556?

**Comment by oscarnyl** [comment]
It sure was. Thanks a lot!
