### ISSUE TITLE
Unknown Functions

### ISSUE THREAD

**Issue by JasonB579** [junegunn/vim-plug#620]
I followed all of the instructions for installing on a Unix based system, and having checked my filesystem it seems like everything went correctly (plug.vim is in ~/.vim/autoload), but when I put the lines `plug#begin(~/.vim/plugged)` and `plug#end()` in my .vimrc files I get an error. When I try to open any file with vim I get errors saying 

> E117: Unknown function: plug#begin

and 

> E117: Unknown function: plug#end

None of the solutions to this that I was able to find applied to me or solved my problem.

Any help would be appreciated!

------------------------------

```

```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [X] Question
- OS:
    - [ ] All/Other
    - [X] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [X] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by vheon** [comment]
Can you post your vimrc?

**Comment by JasonB579** [comment]
It's no longer really an issue. I switched to NeoVim and now it seems to be working without too much trouble. Sorry.

**Comment by AntouanK** [comment]
I have the same problem trying to install `vim-plug`.

```
13:41:10 antouank@i7 ~ vim ~/.vimrc
Error detected while processing /home/antouank/.vimrc:
line    2:
E117: Unknown function: plug#begin
line    3:
E492: Not an editor command: Plug 'tpope/vim-sensible'
line    4:
E117: Unknown function: plug#end
Press ENTER or type command to continue
13:41:47 antouank@i7 ~ cat ~/.vimrc

call plug#begin()
Plug 'tpope/vim-sensible'
call plug#end()

13:41:53 antouank@i7 ~ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar  6 2017 14:13:23)
```
