### ISSUE TITLE
Remove vim-scripts as a plugin source

### ISSUE THREAD

**Issue by airblade** [junegunn/vim-plug#625]
Please could we stop assuming vim-scripts is a good place to get plugins?

This was discussed in #202.  vim-scripts.org is not maintained and I don't think vim-plug should look for plugins there (without telling the user, which compounds the problem).

I raise this because I have had several people opening issues on my own plugins because they didn't know that `Plug 'some-plugin'` actually downloads a stale version from vim-scripts.

Instead I think that vim-plug should show an error message to the user, e.g. "You haven't specified where to find 'some-plug'."

**Comment by junegunn** [comment]
Yeah, I agree that we should drop support for vim-scripts.

**Comment by airblade** [comment]
Thank you!

**Comment by docwhat** [comment]
Yes, thank you! I had (accidentally) been using the vim-scripts ancient version of `netrw` instead of the built-in one for vim and neovim.  Your new warning let me catch that!

**Comment by oryband** [comment]
People, you should document this somewhere on the front page, this is going to break things for people out of the blue.

**Comment by junegunn** [comment]
@oryband I don't think it's necessary as it was an undocumented feature. vim-plug has never suggested that it implicitly prepends `vim-scripts/`.

**Comment by neybar** [comment]
I agree that notice on the front page would be nice.  Or at least some where that is easy to find.  I had to search through closed issues to find this thread.  An entry in the wiki? anything really. 

I don't mind the change, but it was rather jarring, with no explanation on why.

**Comment by codelahoma** [comment]
As someone that was just caught out of the blue, I have to +1 the front page notice.

If it hadn't been the latest commit, and therefore shown on the front page file listing, I'd still be looking for a solution.

**Comment by docwhat** [comment]
Would it be possible to improve the warning message so that a readme change isn't need?

**Comment by codelahoma** [comment]
That would work, I think. Something along the line of 'vim-scripts is no longer maintained, and its use has been deprecated'?
