### ISSUE TITLE
Drupal vimrc plugin installation?

### ISSUE THREAD

**Issue by danshumaker** [junegunn/vim-plug#626]
Explain the problem here ...

------------------------------

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr  6 2017 09:14:00)
MacOS X (unix) version
Included patches: 1-543
Compiled by Homebrew
H
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ x] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [x ] OS X
    - [ ] Windows
- Vim:
    - [x ] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

I was hoping to install the vimrc plugin with Plug but when I goto the .vim/plugged/vimrc directory after running "PlugInstall", the files don't seem to be installed.

What I'm trying is:
```bash
call plug#begin()
Plug 'https://git.drupal.org/project/vimrc.git', { 'branch': '8.x-1.x', 'rtp': 'bundle/vim-plugin-for-drupal/plugin' }
call plug#end()
```

The plugin README is here: http://cgit.drupalcode.org/vimrc/tree/README.txt

And if you scroll down in that README file you'll see what should be in place after installation is:
```
        autoload/drupal.vim
        compiler/coder.vim
        doc/drupal.txt
        ftdetect/drupal.vim
        ftplugin/drini.vim
        ftplugin/drupal.vim
        plugin/drupal.vim
        snipmate/drupal/php.snippets
        snipmate/drupal6/php.snippets
        snipmate/drupal7/php.snippets
        syntax/drini.vim
        syntax/drupal.vim
        tagfiles/drupal6.tags
        tagfiles/drupal7.tags
        tagfiles/drupal8.tags
```

Any idea on how to install this plugin using Plug?

Many thanks!

**Comment by junegunn** [comment]
Try `'rtp': 'bundle/vim-plugin-for-drupal'` (no plugin)

**Comment by danshumaker** [comment]
Thank you Junegunn! That did it.   Everything seems to work except the ftplugin/drini.vim and syntax/drini.vim filetypes are not getting picked up... but that's no fault of Plug I'm sure.

**Comment by danshumaker** [comment]
Re drini.vim issues: https://www.drupal.org/node/2845607#comment-12065205
