### ISSUE TITLE
How to continue using bib_autocomp.vim after #625

### ISSUE THREAD

**Issue by Hunter-Github** [junegunn/vim-plug#627]
Problem: bib_autocomp.vim stopped working

Resolution: replace `Plug "bib_autocomp.vim"` with `Plug "vim-scripts/bib_autocomp.vim"`

------------------------------

```
NVIM v0.2.0
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer-size=4 -DINCLUDE_GENERATED_DEC
LARATIONS -D_GNU_SOURCE -I/neovim-0.2.0/build/config -I/neovim-0.2.0/src -I/neovim-0.2.0/.deps/usr/include -I/neovim-0.2.0/.deps/usr/include -I/neovim-0.2.0/.deps/usr/include -I/neovim-0.2.0/.deps/usr/include -I/neovim-0.2.0/.deps/usr/include -I/neovim-0.2.0/.deps/usr/include -I/usr/include -I/neovim-0.2.0/build/src/nvim/auto -I/neovim-0.2.0/build/include
Compiled by XXX

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by Hunter-Github** [comment]
Closing: see **resolution** in the initial report. This issue was submitted to enable others with the same problem to find an answer quickly.

**Comment by junegunn** [comment]
Thanks. It's an intentional change as vim-scripts is no longer maintained. Actually, vim-plug has never suggested that it prepends `vim-scripts` implicitly like Vundle does, so I think it's fair to say that it's not a breaking change. But I think we should probably mention the difference in the wiki page for the future converts.
