### ISSUE TITLE
Plug 'enabled' option

### ISSUE THREAD

**Issue by laktak** [junegunn/vim-plug#628]
I'm using vim for different tasks with different sets of plugins.

For example for development I start it with `VIMDEV=1 vim` with this in my `.vimrc`:

```
if $VIMDEV == 1
  Plug 'vim-scripts/Conque-GDB'
  Plug 'davidhalter/jedi-vim'
  Plug 'artur-shaik/vim-javacomplete2'
  Plug 'OmniSharp/omnisharp-vim'
endif
```

This works fine except that the `PlugUpdate`/`PlugClean` commands don't know about these plugins if I just run `vim`.

Would it be possible to add an optional `enabled` option like this?

```
  Plug 'vim-scripts/Conque-GDB', { 'enabled': $VIMDEV == 1 }
```

The plugin wouldn't get loaded if `enabled` is set to `false` but the `Plug*` commands would handle it correctly.

**Comment by junegunn** [comment]
You can find the answer here: https://github.com/junegunn/vim-plug/wiki/faq#conditional-activation
