### ISSUE TITLE
A command to generate a catalogue for installed plugins

### ISSUE THREAD

**Issue by sassanh** [junegunn/vim-plug#629]
It's a suggestion, I have 135 plugins installed over years some installed around 6 years ago (using Vundle/Bundle at the time). Some of vim plugins have really irrelevant names or names that are relevant but you can't guess the name based on the feature you know it's providing you. So when you decide to change configs for a plugin you've been using 5 years sometimes you'll have hard time finding out the plugin's name. I even sometimes end up traversing on all `Plug '...` lines in my vimrc and check them one by one reading their readme file, checking the project website, etc.
It'd be great if there was a `PlugCatalogue` command that does this traverse and generates a buffer with name of each plugin as the title of sections, each section containing a description of the plugin maybe based on their readme file or doc file. I think the description that comes in each section can get better and better over time in future versions of vim-plug. This way I can open that buffer and search for some relevant words and it eases finding the related plugin.

**Comment by vheon** [comment]
I think this would be another feature that could be external to vim-plug, like the other in https://github.com/junegunn/vim-plug/wiki/extra. Once you have `g:plugs` you know the plugin you have loaded, you know the directory where they are cloned so you can iterate over them and grab the `README.md` and do whatever you want with it.

**Comment by sassanh** [comment]
I see, thanks for quick response.

**Comment by junegunn** [comment]
Interesting idea, although it can be tricky as the structure of README.md (or even the presence of it) is not at all standardized.

FYI, I have the following command in my vimrc for looking up README.md files of plugins that do not have vimdoc files.

https://github.com/junegunn/dotfiles/blob/fe97a04709ce0b7afa66ab41d09f53dee06a657a/vimrc#L1751-L1766

**Comment by sassanh** [comment]
@junegunn thanks for sharing.
