### ISSUE TITLE
Vim is not responsive when a vim-plug command is running

### ISSUE THREAD

**Issue by sassanh** [junegunn/vim-plug#630]
While vim-plug commands are running, vim is unusable (doesn't respond to input) though the vim-plug buffer is updated (redrawed) constantly.

------------------------------

```
:version
NVIM v0.2.0
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g
 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DIN
CLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170505-72607-jjidmu/neovim-0.2.0/build/config -I/tmp/neovim-20170505-72607-jjidmu/neovim-0.2.0/src -I/usr/l
ocal/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -
I/usr/include -I/usr/include -I/tmp/neovim-20170505-72607-jjidmu/neovim-0.2.0/build/src/nvim/auto -I/tmp/neovim-20170505-72607-jjidmu/neovim-0.2.0/build
/include
Compiled by sassanharadji@MacBook-Pro

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.0/share/nvim"
```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [x] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
I don't understand what you mean. Can you elaborate? Everything works as expected on Neovim for me.

**Comment by sassanh** [comment]
I run `PlugUpdate` it takes around 30 seconds to finish its job. While updaing plugins it updates its window (moving the progress bar, etc) but I can't type in another buffer. Vim is no responsive while it's updating. I can work while it's doing its job.

**Comment by junegunn** [comment]
I see. Updating plug window is pretty inefficient at the moment; whenever there's an update, vim-plug moves the cursor to the plug window, update the line, move the cursor back to the previous window, so it's understandable that vim or neovim is not as responsive as usual.

Unfortunately there's really no good solution to the problem that applies both to Vim 8 and Neovim, you might want to just spawn more processes so that the task completes faster, i.e. `PlugUpdate99`

**Comment by sassanh** [comment]
I see, thanks for info, if you have no plans for it we can close it.

**Comment by sassanh** [comment]
Can we add an option to disable updating the `PlugUpdate` window and maybe just show a progress bar in command line or nothing at all (just report when it's finished and inform that how user can see the results)

**Comment by junegunn** [comment]
I personally don't need it. I would simply start a new tmux pane if I need to do that. But if you want to contribute, patches are welcome.
