### ISSUE TITLE
unhandled exception when calling plug functions in vim started in a directory since deleted

### ISSUE THREAD

**Issue by ShadowPhrogg32642342** [junegunn/vim-plug#631]
% mkdir derp; cd derp; vim &; cd ..; rm -r derp; fg
:PlugStatus "or any other vim-plug command
Error detected while processing function <SNR>4_status[1]..<SNR>4_prepare:
line    2:
E605: Exception not caught: Invalid current working directory. Cannot proceed.
------------------------------
- Type:
    - [X] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [X] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [X] Terminal Vim
    - [X] GVim
    - [X] Neovim

**Comment by junegunn** [comment]
Yeah, it's a known issue, and there's no right way to resolve the situation automatically.
https://github.com/junegunn/vim-plug/issues/439

You can `:cd` to a valid directory and retry.
