### ISSUE TITLE
Install Plugin Error

### ISSUE THREAD

**Issue by Fashaun** [junegunn/vim-plug#632]
[vim-plug] Invalid argument: bash-support.vim (implicit `vim-scripts' expansion is deprecated)

and the Plug 'matchit.zip' is still with this problem, but others are not.
------------------------------

```
:version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Feb  4 2017 00:48:24)
Included patches: 1-898, 8056
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
+acl             +cmdline_compl   +diff            +find_in_path    -keymap          +modify_fname    +mouse_xterm     -profile         -sniff           +termresponse    +vreplace        -xterm_save
-arabic          +cmdline_hist    +digraphs        +float           -langmap         +mouse           +multi_byte      +python/dyn      +startuptime     +textobjects     +wildignore      -xpm
+autocmd         +cmdline_info    -dnd             +folding         +libcall         -mouseshape      +multi_lang      -python3         +statusline      +title           +wildmenu
-balloon_eval    +comments        -ebcdic          -footer          +linebreak       -mouse_dec       -mzscheme        +quickfix        -sun_workshop    -toolbar         +windows
-browse          -conceal         -emacs_tags      +fork()          +lispindent      -mouse_gpm       +netbeans_intg   +reltime         +syntax          +user_commands   +writebackup
+builtin_terms   +cryptv          +eval            -gettext         +listcmds        -mouse_jsbterm   +path_extra      -rightleft       +tag_binary      +vertsplit       -X11
+byte_offset     +cscope          +ex_extra        -hangul_input    +localmap        -mouse_netterm   -perl            +ruby/dyn        +tag_old_static  +virtualedit     -xfontset
+cindent         +cursorbind      +extra_search    +iconv           -lua             -mouse_sgr       +persistent_undo +scrollbind      -tag_any_white   +visual          -xim
-clientserver    +cursorshape     -farsi           +insert_expand   +menu            -mouse_sysmouse  +postscript      +signs           -tcl             +visualextra     -xsmp
-clipboard       +dialog_con      +file_in_path    +jumplist        +mksession       -mouse_urxvt     +printer         +smartindent     +terminfo        +viminfo         -xterm_clipboard
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -o vim        -lm -lncurses  -liconv
```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [x] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by Fashaun** [comment]
This is my first time to post issue, if there's any missing description, please feel free to let me know

**Comment by junegunn** [comment]
What do you expect from vim-plug when you write `Plug 'matchit.zip'`? `Plug 'foo/bar'` expands to `Plug 'https://github.com/foo/bar.git'` as documented, but vim-plug does not know what to do when 'bash-support.vim' is given because 'https://github.com/bash-support.vim.git' is not a valid git repository. You can consider using https://github.com/vim-scripts/bash-support.vim, but I don't recommend using anything under `vim-scripts` since it's no longer maintained.

**Comment by Fashaun** [comment]
Hi ,

thanks for reply,

the install method is because I'm using the tutorial from "vim awsome "
http://vimawesome.com/

and it works before,


2017-05-16 13:28 GMT+08:00 Junegunn Choi <notifications@github.com>:

**Comment by junegunn** [comment]
Then I must say that the tutorial is wrong. vim-plug never documented that it supports that form of specification. It used to implicitly prepend `vim-scripts/` in those cases, but it was unofficial, undocumented feature which we decided to remove for good as it caused troubles and confusions.

**Comment by Fashaun** [comment]
Oh really ,well ~ but I think it provide a convenient way to configure vim
, but may be  it can be more reliable in the future

2017-05-16 17:48 GMT+08:00 Junegunn Choi <notifications@github.com>:

**Comment by junegunn** [comment]
vim-scripts mirror is no longer updated so it's discouraged that you use it unless you are absolutely sure what you are doing.

**Comment by trusktr** [comment]
> vim-scripts mirror is no longer updated so it's discouraged that you use it unless you are absolutely sure what you are doing.

What is the alternative? How do you know  https://github.com/vim-scripts is no longer maintained? I thought maybe it was updated by automatic robot script?

**Comment by Shougo** [comment]
> What is the alternative?

Unfortunately, non alternative.
I don't recommend for you to use vim.org plugins.

**Comment by Fashaun** [comment]
Please accept my invitation to WorkFlowy


  
  Hi,

Join me and 2 million other people using WorkFlowy to get organized. 

Please accept my invitation (and get us both free space!) using this invite link: https://workflowy.com/invite/307b5b13.emlx

Thanks,FaSean Lin
  

  
    
      You are receiving this invitation because FaSean Lin invited you to WorkFlowy.
    
  
  
    Workflowy · PO Box 40507 · San Francisco, CA 94140

**Comment by bwakkie** [comment]
Just as a side note:
I got this error too because I forgot to add the git package user in front of the package e.g.:
```
I had:     Plug 'vim-fugitive'
should be: Plug 'tpope/vim-fugitive'
```

**Comment by msooseth** [comment]
If anyone has a similar issue... I accidentally had a
```
Plug ''
```

In my `init.rc`, which caused the same error to appear.

**Comment by christianrickert** [comment]
```term
implicit `vim-scripts' expansion is deprecated
```
also occurs when using a backslash `\` in the package's address (gVim).

**Comment by junegunn** [comment]
There is no bug and there is no problem in the documentation. The README page currently does not mention anything about name-only arguments or `vim-scripts/` mirrors.

* You can't install plugins from https://www.vim.org/scripts using vim-plug. vim-plug only works with Git repositories. `vim-scripts` organization on GitHub used to mirror plugins in vim.org, but it's no longer maintained.
* You can't install some plugin using `:PlugInstall` without putting `Plug` statement for it in your Vim configuration file first. You first need to specify the list of plugins you want to use using `Plug` statements. `:PlugInstall` will install all plugins, `:PlugInstall NAMES...` will install a subset of the list.
*`:PlugInstall` only takes the name part excluding the org/user prefix. Try using the tab completion to find the right name to pass to it.
