### ISSUE TITLE
What is PlugCond()?

### ISSUE THREAD

**Issue by kshenoy** [junegunn/vim-plug#640]
Explain the problem here ...
I noticed that I have the following line in my vimrc:

    Plug 'SirVer/ultisnips',  PlugCond(has('python'))

It looks like the intent is to not load ultisnips if it isn't available. And it seems to work since I don't see UltiSnips in my runtimepath. 

However, I'm not able to find any documentation on the `PlugCond`. Is this a valid vim-plug command?

If yes: I tried modifying the condition with `PlugCond(has('python')||has('python3'))` but it errors out saying

> E116: Invalid arguments for function plug#

------------------------------

```

```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [x] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [x] GVim
    - [ ] Neovim

**Comment by kshenoy** [comment]
Sigh, nvm. I realized that `PlugCond` is a function that I created:

````
function! PlugCond(cond, ...)
  let opts = get(a:000, 0, {})
  return a:cond ? opts : extend(opts, { 'on': [], 'for': [] })
endfunction
````

I just need to get this working when I pass in `has('python')||has('python3')` as an argument.

**Comment by junegunn** [comment]
Yeah, I think you got it from https://github.com/junegunn/vim-plug/wiki/faq#conditional-activation.

The reason Vim complains on `has('python')||has('python3')` is because `Plug` command is defined with `-bar` (see `:help :command-bar`) and it interprets `|` differently.

```vim
" 1. Escape |
Plug 'SirVer/ultisnips', PlugCond(has('python')\|\|has('python3'))

" 2. Use extra var
let has_python = has('python')||has('python3')
Plug 'SirVer/ultisnips', PlugCond(has_python)

" 3. Use plug# function instead of Plug command
call plug#('SirVer/ultisnips', PlugCond(has('python')||has('python3')))
```

**Comment by kshenoy** [comment]
Thanks, that worked 👍
