### ISSUE TITLE
could not read Username for github.com

### ISSUE THREAD

**Issue by rotsix** [junegunn/vim-plug#641]
Hi guys,
I'm switching to vim-plug, but when launching PlugInstall, i got these errors:
`fatal: could not read Username from 'https://github.com': terminal prompt disabled`

Here is my config:
https://ptpb.pw/-j9Y

------------------------------

```
NVIM v0.2.0
Build type: Release
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -DNVIM_MSGPA
CK_HAS_FLOAT32 -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=g
nu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/bui
ld/neovim/src/build/config -I/build/neovim/src/neovim-0.2.0/src -I/usr/include -I/usr/include -I/usr/include -I/us
r/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src
/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

- Type:
    - [X] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [X] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [X] Neovim

Thanks !
Regards,
rotsix

EDIT: working with `Plug 'https://github.com/<username>/<repo>'`

**Comment by junegunn** [comment]
Remove `.git` at the end and it'll work. To understand how vim-plug expands the arguments, see:

- https://github.com/junegunn/vim-plug#global-options
- https://github.com/junegunn/vim-plug/wiki/faq#whats-the-deal-with-git-in-the-url
