### ISSUE TITLE
New path to vimfiles on windows

### ISSUE THREAD

**Issue by vegangaro** [junegunn/vim-plug#642]
Explain the problem here ...

VIM on Windows changed its default path of ~\vimfiles to ~\Vim\vimfiles

```
md ~\vimfiles\autoload
$uri = 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
(New-Object Net.WebClient).DownloadFile($uri, $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath("~\vimfiles\autoload\plug.vim"))

```

------------------------------

```

```

- Type:
    - [ ] Bug
    - [x] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [x] Windows
- Vim:
    - [ ] Terminal Vim
    - [x] GVim
    - [ ] Neovim

**Comment by chrisbra** [comment]
Using gvim 8.0.586 I cannot confirm. ´~/vimfiles` does still work and I haven't seen any patches changing that path.

**Comment by vegangaro** [comment]
yep. And I noticed that VimPlug does install all its files in a hidden folder called .vim on User\

Although all Vim 8 files are installed,  by default, on User\Vim

**Comment by junegunn** [comment]
I believe that's because you specifically told vim-plug to do so. i.e. `call plug#begin('~/.vim/plugged')`. You can change the path in the argument as you like.

**Comment by vegangaro** [comment]
haha...yep,  my bad
