### ISSUE TITLE
disallow cloning into a standard vim runtime folder

### ISSUE THREAD

**Issue by chrisbra** [junegunn/vim-plug#646]
some [user of vim-airline](https://github.com/vim-airline/vim-airline/issues/1440#issuecomment-286749990) did use `call plug#begin('~/.vim/plugin')` 
That is just asking for plain trouble and should probably at least be warned against. So please either disallow cloning into ~/.vim/{syntax, ftplugin, after, plugin, colors, ftdetect, spell} (probably only relevant is ~/.vim/plugin or have vim-plug at least warn to use such a folder.

**Comment by junegunn** [comment]
Thanks for the suggestion. Although we can thoroughly compare it against every path in `&rtp`, it should probably suffice to just look at the first path in `&rtp`, i.e. `~/.vim/plugin`.

```diff
diff --git a/plug.vim b/plug.vim
index a7f1030..e0dc78f 100644
--- a/plug.vim
+++ b/plug.vim
@@ -121,6 +121,9 @@ function! plug#begin(...)
   else
     return s:err('Unable to determine plug home. Try calling plug#begin() with a path argument.')
   endif
+  if fnamemodify(home, ':t') ==# 'plugin' && fnamemodify(home, ':h') ==# s:first_rtp
+    return s:err('Invalid plug home. '.home.' is a standard Vim runtime path and is not allowed.')
+  endif
 
   let g:plug_home = home
   let g:plugs = {}
```

What do you think?

**Comment by chrisbra** [comment]
sounds good enough. Perhaps make a mention in the README as well not to use the 'plugin' folder.

**Comment by junegunn** [comment]
Fixed, thanks.
