### ISSUE TITLE
question : cannot update using command PlugInstall

### ISSUE THREAD

**Issue by tanglianggithub** [junegunn/vim-plug#648]
already download vim-plug in ~/.vim/autoload
install plugin. Failed. use PlugStatus to find status.

status file, install status, vimrc are as follows:
![image](https://user-images.githubusercontent.com/3445470/27684593-4415d808-5cfd-11e7-8606-15259e1d716d.png)
![image](https://user-images.githubusercontent.com/3445470/27684605-4ddb2bae-5cfd-11e7-9c94-71657c4ea3b0.png)
![image](https://user-images.githubusercontent.com/3445470/27684614-5333b4ea-5cfd-11e7-89fb-92509bbe3d94.png)

vim version: 8.0
OS: Linux
Vim: Terminal Vim

**Comment by junegunn** [comment]
- Do you have the latest version of vim-plug?
- Can you manually clone the repositories without problems?
