### ISSUE TITLE
Working with vimtemplates (another folder)

### ISSUE THREAD

**Issue by drbeco** [junegunn/vim-plug#653]
It doesn't quite work with the plugin **vimtemplates**
 https://github.com/drbeco/vimtemplates

The plugin need to install things in a different subdirectory

`~/.vim/templates` # For template files
and
`~/.vim/plugged/vimtemplates/plugin/vimtemplates.vim` # For the plugin itself

Other than that, just to say, this plugin manager is AWSOME!

Thanks a lot

**Comment by drbeco** [comment]
Just to be sure, to install it one should just add:

```
" Vimtemplates - templates for diverse files
Plug 'drbeco/vimtemplates'
```

Is it as simple as that, right? It will then clone the whole repository?

**Comment by drbeco** [comment]
Oh, never mind. I changed the reference to the directory `~/.vim/templates/` to `~/.vim/plugged/vimtemplates/templates/`

It work as a charm now, and it is better that the templates keep inside the repository.

It is a good thing that this plugin manager clone the entire repository, so plugin authors have a little freedom. 

Thanks a lot.

**Comment by junegunn** [comment]
No problem, good to hear that you figured it out.
