### ISSUE TITLE
plug option "source"

### ISSUE THREAD

**Issue by while0pass** [junegunn/vim-plug#655]
It would be great if there were a plug option indicating a path to the file with the settings for the plugin. Suppose I've plugged `Valloric/YouCompleteMe` plugin:
```
Plug 'Valloric/YouCompleteMe', { 'for': ['c', 'cpp', 'javascript', 'rust'] }
```
and want to add some settings for it:
```
let g:ycm_key_list_select_completion = ['CTRL-N', 'Down']
let g:ycm_key_list_previous_completion = ['CTRL-P', 'Up']
" ...
```
Suppose these settings are kept in `vimrc.d/ycm` file, it could look something like that:
```
Plug 'Valloric/YouCompleteMe', { 
    \ 'for': ['c', 'cpp', 'javascript', 'rust'],
    \ 'settings': 'vimrc.d/ycm' }
```

- Type:
    - [ ] Bug
    - [x] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [x] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [x] GVim
    - [x] Neovim

**Comment by vheon** [comment]
what's wrong with

```viml
Plug 'Valloric/YouCompleteMe'
source 'vimrc.d/ycm'
```
?

**Comment by while0pass** [comment]
I've been already using sort of it (`runtime`). But would it be more natural to disable a plugin and all its stuff at once in a single line of code? I see it may look unnecessary.

**Comment by while0pass** [comment]
Ideally, there may be some agreement onto where files for each plugin are located by default and how they are named so that this option would be unnecessary most of the time.

**Comment by junegunn** [comment]
You can hook it up to the User autocmd of the same name as the plugin as shown here:

https://github.com/junegunn/vim-plug#on-demand-loading-of-plugins

**Comment by while0pass** [comment]
thank you all
