### ISSUE TITLE
Plug 'junegunn/vim-plug' 

### ISSUE THREAD

**Issue by drbeco** [junegunn/vim-plug#656]
Is it possible to add

> Plug 'junegunn/vim-plug' 

and make it auto-update itself?

**Comment by drbeco** [comment]
I have a suggestion on how this might work with no need to extra code, but my test didn't worked out.

I've cloned and added a new branch `install` with a single file in it `plug.vim`, so the update will just download the correct file and not stuff things into the `autoload` directory.

Then I added the command to my `.vimrc`:

"Plug 'drbeco/vim-plug', {  'dir': '~/.vim/autoload', 'branch': 'install' }

It sounds reasonable, but it didn't update. Maybe because the `plug.vim` is already updated? Well, it didn't gave any errors also.

**Comment by drbeco** [comment]
Another suggestion, also easy to implement, is a post-install hook with a python script to just copy the file `~/.vim/plugged/vim-plug/plug.vim` to `~/.vim/autoload`

    Plug 'junegunn/vim-plug', { 'do': './install.py' }

or maybe even just:

    Plug 'junegunn/vim-plug', {  'do': 'cp ~/.vim/plugged/vim-plug/plug.vim ~/.vim/autoload' }

But that would fix the directories.

**Comment by junegunn** [comment]
See https://github.com/junegunn/vim-plug/wiki/faq#shouldnt-vim-plug-update-itself-on-plugupdate-like-vundle

**Comment by drbeco** [comment]
Thanks! I'll look into that.

**Comment by drbeco** [comment]
So many duplicates. Sorry to add yet another one.

### Main discussion:

Let vim-plug manage itself #69

### References:

Why not make this plugin manage itself? #73
autoload directory #77
how to automatically install itself? #89
Managing vim-plug with vim-plug #102
Self-management #128
plug.vim should be in autoload directory #203
Allow vim-plug to be managed as a plugin #240

**Comment by drbeco** [comment]
Still, those discussions shade some light in the fact that I need to install `vim-plug` in `/etc/vim/` as a global plugin manager, with plugins at `/etc/vim/plugged`, with write permission only to _root_.

I've searched the issues for `global install` to no avail I'm afraid to create another _duplicate_. Is there any info on how to install `vim-plug` globally?
