### ISSUE TITLE
Plugins not getting loaded

### ISSUE THREAD

**Issue by kshenoy** [junegunn/vim-plug#661]
Ok, this is kind of a weird one. A bit of background first. I'm trying to move all my config files which are spread out in ~/.vim to vim 8's pack folder (~/.vim/pack) such that once everything has been moved, my .vim will have only vimrc, gvimrc and the pack folder. The reason behind doing so is so that I can go to someone else's comp, start vim with `gvim -u vimrc and -U gvimrc` and have all of my config available to me, including plugins. 

vim-plug is one of the last things left to move and in order to do the above, I did a couple of things

1. Moved the file with all my plugin related settings to [pack/bundles/start/bundles/plugin/bundles.vim](https://github.com/kshenoy/dotfiles/blob/5b215a460d6f03ee5be837b5a4afb6ae3dba06ef/vim/pack/bundles/start/bundles/plugin/bundles.vim)

2. Set the path where vim-plug would be installed to [pack/bundles/start/bundles/autoload](https://github.com/kshenoy/dotfiles/blob/5b215a460d6f03ee5be837b5a4afb6ae3dba06ef/vim/pack/bundles/start/bundles/plugin/bundles.vim#L6-L8)

3. Set plug#begin to [pack/bundles/opt](https://github.com/kshenoy/dotfiles/blob/5b215a460d6f03ee5be837b5a4afb6ae3dba06ef/vim/pack/bundles/start/bundles/plugin/bundles.vim#L16)

I was thinking that upon startup, pack/bundles/start/bundles/plugin/bundles.vim would be added to the runtimepath (which it is) and it would invoke all the plug#* calls and load the packages. The startup seems to happen normally without any errors or warnings but I'm not able to use any plugin, it seems like they weren't loaded correctly. `:PlugStatus` shows that a plugin, say vim-unimpaired, has been loaded (Status = OK). However, none of its mappings `[e` etc. have been created.

Here's the rundown of the debug:

* I verified that bundles.vim can find plug functions with [`echom exists("*plug#begin")`](https://github.com/kshenoy/dotfiles/blob/5b215a460d6f03ee5be837b5a4afb6ae3dba06ef/vim/pack/bundles/start/bundles/plugin/bundles.vim#L17) and it returns 1
* Both bundles.vim and plug.vim can be seen in `:scriptnames`
* Additionally, I placed a debug statement inside `plug#(...)` to dump the name of the repo and I can see **tpope/vim-unimpaired** get printed out upon startup so even that function is getting called.

I'm kind of not sure what's happening. If you have some time, can you please take a look at it?
My repo is located [here](https://github.com/kshenoy/dotfiles/tree/5b215a460d6f03ee5be837b5a4afb6ae3dba06ef/vim)

Thanks

------------------------------

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 12 2016 09:59:02)
Included patches: 1-78
Compiled by ks@ubuntu
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +clientserver    +cursorbind      +ex_extra        +gettext         +libcall         +mouse           +mouse_xterm     +persistent_undo +ruby            +tag_old_static  +toolbar         +wildmenu        -xterm_save
+arabic          +clipboard       +cursorshape     +extra_search    -hangul_input    +linebreak       +mouseshape      +multi_byte      +postscript      +scrollbind      -tag_any_white   +user_commands   +windows
+autocmd         +cmdline_compl   +dialog_con_gui  +farsi           +iconv           +lispindent      +mouse_dec       +multi_lang      +printer         +signs           -tcl             +vertsplit       +writebackup
+balloon_eval    +cmdline_hist    +diff            +file_in_path    +insert_expand   +listcmds        +mouse_gpm       -mzscheme        +profile         +smartindent     +termguicolors   +virtualedit     +X11
+browse          +cmdline_info    +digraphs        +find_in_path    +job             +localmap        -mouse_jsbterm   +netbeans_intg   +python/dyn      +startuptime     +terminfo        +visual          -xfontset
++builtin_terms  +comments        +dnd             +float           +jumplist        +lua             +mouse_netterm   +num64           +python3/dyn     +statusline      +termresponse    +visualextra     +xim
+byte_offset     +conceal         -ebcdic          +folding         +keymap          +menu            +mouse_sgr       +packages        +quickfix        -sun_workshop    +textobjects     +viminfo         +xpm
+channel         +cryptv          +emacs_tags      -footer          +lambda          +mksession       -mouse_sysmouse  +path_extra      +reltime         +syntax          +timers          +vreplace        +xsmp_interact
+cindent         +cscope          +eval            +fork()          +langmap         +modify_fname    +mouse_urxvt     +perl            +rightleft       +tag_binary      +title           +wildignore      +xterm_clipboard
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/local/share/vim"
 f-b for $VIMRUNTIME: "/usr/local/share/vim/vim80"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I
/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-lin
ux-gnu/glib-2.0/include -I/usr/include/freetype2   -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgi
o-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux   -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -
L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.22/CORE -lperl -ldl -lm -lpthread -lcrypt    -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm

```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [x] GVim
    - [ ] Neovim

**Comment by janlazo** [comment]
https://github.com/kshenoy/dotfiles/blob/5b215a460d6f03ee5be837b5a4afb6ae3dba06ef/vim/pack/bundles/start/bundles/plugin/bundles.vim#L6-L14
Try installing vim-plug before Vim starts.
I tested moving some plugins like `vim-unimpaired` into `pack a/opt/b/plugin/plug.vim` and load them via `packadd b`. It worked and I got vim-unimpaired and my colorscheme working at the start or after `PlugInstall`. Maybe `pack/*/start/*/` does not work with vim-plug unless each plugin is lazy loaded.
