### ISSUE TITLE
Opening plugin repo from script?

### ISSUE THREAD

**Issue by jon-choi** [junegunn/vim-plug#665]
It would be awesome to be able to have a keyboard shortcut to open the plugin repo from the dotfile. I sometimes forget what a given plugin does and want to clean them up once in a while.

Example:
`Plug 'junegunn/goyo.vim'`

Keyboard shortcut to open up https://github.com/junegunn/goyo.vim

------------------------------

```

```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [x] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [x] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by nfischer** [comment]
I think [this wiki post](https://github.com/junegunn/vim-plug/wiki/extra#gx-to-open-github-urls-on-browser) should be what you're looking for.

**Comment by junegunn** [comment]
@nfischer Thanks for the comment.

@jon-choi Note that the example on the wiki page works on plug window that is opened by one of the Plug commands (PlugStatus, PlugInstall, ...). I believe you can figure out how to write a version that works on vimrc based on the example.
