### ISSUE TITLE
shellescape comment in s:bang

### ISSUE THREAD

**Issue by janlazo** [junegunn/vim-plug#668]
Does porting the `fzf#shellescape` fix the escaping issue here for Windows?

```viml
function! s:bang(cmd, ...)
  try
    let [sh, shrd] = s:chsh(a:0)
    " FIXME: Escaping is incomplete. We could use shellescape with eval,
    "        but it won't work on Windows.
    let cmd = a:0 ? s:with_cd(a:cmd, a:1) : a:cmd
    let g:_plug_bang = '!'.escape(cmd, '#!%')
    execute "normal! :execute g:_plug_bang\<cr>\<cr>"
  finally
    unlet g:_plug_bang
    let [&shell, &shellredir] = [sh, shrd]
  endtry
  return v:shell_error ? 'Exit status: ' . v:shell_error : ''
endfunction
```

- Type:
    - [ ] Bug
    - [X] Enhancement
    - [ ] Feature Request
    - [X] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [X] Windows
- Vim:
    - [X] Terminal Vim
    - [X] GVim
    - [X] Neovim

**Comment by junegunn** [comment]
Possibly. However, no one has ever reported an issue regarding the code. I think it's because no one  really uses complex `do` option value that can cause escaping issues in reality. So I haven't been actively trying to "fix" the code.

**Comment by janlazo** [comment]
It can't handle filepaths with spaces in Windows.

**Comment by janlazo** [comment]
Is the `FIXME` comment still valid?
