### ISSUE TITLE
implicit vim-scripts expansion is deprecated

### ISSUE THREAD

**Issue by youthy** [junegunn/vim-plug#671]
everytime when I start vim, the notice shows:
> [vim-plug] Invalid argument: L9 (implicit `vim-scripts' expansion is deprecated)

------------------------------

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Aug 17 2017 16:58:51)
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
`Plug 'L9'` is not valid. You should write `Plug 'vim-scripts/L9` instead. But before that, you might want to check if `L9` is really needed. You probably have copy-pasted it from some configuration example when you don't need it.
