### ISSUE TITLE
wiki snippet is incorrect 

### ISSUE THREAD

**Issue by cdosborn** [junegunn/vim-plug#672]
This wiki [snippet](https://github.com/junegunn/vim-plug/wiki/extra#automatically-install-missing-plugins-on-startup) results in vim immediately exiting. 
I think the following diff should be applied.
 ```diff
 autocmd VimEnter *
   \  if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
-  \|   PlugInstall --sync | q
+  \|   PlugInstall | q
   \| endif
```
------------------------------

```

```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
Do you have the latest version of vim-plug? (PlugUpgrade)
It works for me as expected.

**Comment by liuchengxu** [comment]
I also encounter a similar problem. In my case, the bare `vim` command will work as expected, but `vim` with a certain argument, e.g., `vim foo.vim` will fail to work. I'm using the snippet from the wiki, i.e., with `--sync` option.

**Comment by cdosborn** [comment]
You're right. I just needed to upgrade.
