### ISSUE TITLE
Run PlugInstall non-interactively from command line

### ISSUE THREAD

**Issue by rightaway** [junegunn/vim-plug#675]
I'd like to run PlugInstall non-interactively from the command line to provision a new system (using Ansible in this case). If I do `vim -c 'PlugInstall'` it works, but it is interactive, opening up a terminal window where you can see the progress of the installation. If I try to run it non-interactively I get an error, e.g. `"Vim: Warning: Output is not to a terminal", "Vim: Warning: Input is not from a terminal"`.

NeoBundle provides a script to install `~/.vim/bundle/neobundle.vim/bin/neoinstall` non-interactively, could `vim-plug` offer something similar?

**Comment by junegunn** [comment]
> Vim: Warning: Output is not to a terminal

It's a warning not an error. As far as I know, vim will proceed to install the plugins even in that case. Since the installer on Vim 8 is asynchronous, you might want to pass `--sync` flag as follows

```sh
vim +'PlugInstall --sync' +qa
```

Let me know if it doesn't work as expected.

**Comment by rightaway** [comment]
That worked, thank you!

What does the `+qa` do btw?

And the `+` near the beginning? I noticed you used that instead of `-c`.

**Comment by junegunn** [comment]
- `:help :qa` (quit all)
- `+` is just a shorthand notation of `-c`, see `man vim`.

**Comment by dgdosen** [comment]
Thanks! - I wish I would have looked this up sooner.   It's great to be able  interact with vim in a shell script.

**Comment by Moshem123** [comment]
Thanks to this:
https://github.com/junegunn/vim-plug/issues/225#issuecomment-583541912
This is the only thing working for nvim:
```
nvim --headless +PlugInstall +qall
```

**Comment by heinosasshallik** [comment]
Note that you need a newer NeoVim version for this. NeoVim 0.2.2 (which is the current version you might get using `apt install` on older distros) won't work.

What worked for me was the **Automatic Installation** section of this github wiki page:
https://github-wiki-see.page/m/junegunn/vim-plug/wiki/tips

*Place the following code in your .vimrc before plug#begin() call*
```
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
```

Make sure you change the `$MYVIMRC` variable and that your data directory is correct.

**Comment by FlorianWanders** [comment]
If you are using [deoplete](https://github.com/Shougo/deoplete.nvim#install) on nvim, adding this line worked for me: 

```
nvim --headless +PlugInstall +qa
nvim +UpdateRemotePlugins +qa
```

First line installs plugins, 2nd line updates remote plugins (required for deoplete).
