### ISSUE TITLE
PlugDiff shows incorrect msg

### ISSUE THREAD

**Issue by winsphinx** [junegunn/vim-plug#680]
Explain the problem here ...

------------------------------
After commit 05c898, `PlugDiff` shows incrrect msg on Windows gvim.
Would you please check it? Thanks!
![snap](https://user-images.githubusercontent.com/5674054/30622143-4b358b6c-9de2-11e7-9c1c-4486e91351ea.PNG)

```

```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [x] Windows
- Vim:
    - [ ] Terminal Vim
    - [x] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
@janlazo Can you look into this? Thanks.

**Comment by janlazo** [comment]
My bad. I noticed that but forgot to handle it. The command is run inside the batchfile so the parser thinks that the passed string for `--pretty` contains variables.

hdscr came from `"%x01%h%x01%d%x01%s%x01%cr"`

**Comment by junegunn** [comment]
@winsphinx Can you upgrade vim-plug and see if it's fixed now?

**Comment by winsphinx** [comment]
Thanks. It is fixed ..but partly.
2 unnecessary quote was added. one is before commit ID, the other is after time. See below.

![snap2](https://user-images.githubusercontent.com/5674054/30624073-ed0cdf8e-9ded-11e7-8ca0-9cb930583c25.PNG)

**Comment by junegunn** [comment]
Hmm yeah, I can reproduce it even on my macbook.

**Comment by junegunn** [comment]
Can you test again?

**Comment by winsphinx** [comment]
Yes, it works perfect.
Thanks all!
