### ISSUE TITLE
fatal: could not read Username for 'https://github.com' error for `PluginInstall` of two plugins by scrooloose

### ISSUE THREAD

**Issue by jimdsouza** [junegunn/vim-plug#682]
I get the following error while updating or trying to install plugins `nerdtree` and `syntastic`. The rest of the plugins seem to install just fine. 

```
 x syntastic:                                                                                                       
 Cloning into '/home/jim/.vim/plugged/syntastic'...                                                            
 fatal: could not read Username for 'https://github.com': terminal prompts disabled                            
 x nerdtree:                                                                                                        
 Cloning into '/home/jim/.vim/plugged/nerdtree'...                                                              |
 fatal: could not read Username for 'https://github.com': terminal prompts disabled  
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by nfischer** [comment]
What do your `Plug` commands look like for those plugins? This error usually indicates a typo, so double check the spelling for `<username>/<pluginname>`
