### ISSUE TITLE
Help file tags not being generated with 'rtp' option

### ISSUE THREAD

**Issue by gwerbin** [junegunn/vim-plug#684]
The [vlime](github.com/l04m33/vlime) plugin source isn't at the top level. It's under './vim'. I works when setting `'rtp': 'vim'` in Vim-Plug, but help tags don't get generated.

```vim
Plug 'l04m33/vlime', { 'rtp': 'vim' }
```

The plugin itself is loaded correctly, but help tags never get generated. I manually generated them with `:helptags` and now it works fine. This isn't an issue with other plugins which do not have a custom runtime path.

------------------------------

#### `:version` output
```
NVIM v0.2.0
Build type: Release
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D
_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unus
ed-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -
DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/config -I/tmp
/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/src -I/usr/local/include -I/usr/local/include -I/usr/loca
l/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/inc
lude -I/usr/include -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/src/nvim/auto -I/tmp/neov
im-20170707-80027-1bg0wcx/neovim-0.2.0/build/include
Compiled by brew@Sierra-2.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.0_1/share/nvim"
```

------------------------------

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [x] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [x] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
Thanks for the report. It should be fixed now.

**Comment by gwerbin** [comment]
Wow, that was fast, thank you!
