### ISSUE TITLE
Local vim plugin that contains mapping not getting loaded

### ISSUE THREAD

**Issue by magicalbanana** [junegunn/vim-plug#685]
Trying to load a local vim file that contains my mapping and it seems that it's not getting loaded.
------------------------------

```
NVIM v0.2.0
Build type: Release
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -
fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/config -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include
 -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/src/nvim/auto -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/include
Compiled by brew@Sierra-2.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.0_1/share/nvim"
```

Here's a sample of my `init.vim`

```
call plug#begin('~/.local/share/nvim/plugged')

Plug 'tpope/vim-sensible'

Plug 'Shougo/unite.vim'
Plug 'Shougo/vimfiler.vim'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }

Plug 'fatih/vim-go', { 'for': 'go' }
Plug 'zchee/deoplete-go', { 'for': 'go' }

Plug '~/.vim/bundle/unite/unite'
Plug '~/.vim/bundle/open/filer'

" Initialize plugin system
call plug#end()

" colonless entrance into command mode
noremap ; :
noremap ! :!
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [x] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by magicalbanana** [comment]
I'm actually getting an error `plugin not found.`

**Comment by junegunn** [comment]
Are they actual plugins, or just some vim script files? vim-plug only add those directories to your `&rtp`. Nothing will happen unless they conform to standard plugin directory structure.

**Comment by magicalbanana** [comment]
@junegunn they're just vim scripts that set the mappings. So I'm actually curious, can I use this plugin manager to configure mappings specific to file types?

**Comment by junegunn** [comment]
I'm not sure why you would want to use a plugin manager for non-plugins. For general Vim questions, I suggest that you ask https://vi.stackexchange.com/, or if you're interested in the standard directory structure of a Vim plugin, see http://learnvimscriptthehardway.stevelosh.com/

**Comment by magicalbanana** [comment]
@junegunn eh, it's because of my current vim config that I modeled after my friend's [sunaku](https://github.com/sunaku/.vim).

I am trying to find out what's causing my [deoplete-go](https://github.com/zchee/deoplete-go) to run really slow so I'm trying to use existing plugin managers and yours had always been something I've been wanting to try.
