### ISSUE TITLE
can't load color scheme in .vim/colors/

### ISSUE THREAD

**Issue by fallinsky** [junegunn/vim-plug#686]
Hi, all
I use wget tool to download a vim color scheme from GitHub into ~/.vim/colors,

and colo it in vimrc file after call plug#end().

However it does not load the color scheme at all,
and lists a lot of lines parsing the .vim file when I type vim xxx.

Please help me out, Thanks. 
------------------------------

```

```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [faq] Question
- OS:
    - [ ] All/Other
    - [faq] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [faq] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
vim-plug does not manage files outside its own directory (e.g. `~/.vim/plugged`), so files in `~/.vim/colors` has nothing to do with it. For general Vim questions unrelated to vim-plug, please consider asking on https://vi.stackexchange.com/ or https://www.reddit.com/r/vim

**Comment by fallinsky** [comment]
I found when I use vim-plug to install a plugin with color theme, the color theme can be loaded correctly.

But when I install a vim color theme, I really don't want to get other stuff that come along with the color scheme. I just want the color scheme.vim to be downloaded.

Can it be done with vim-plug? @junegunn

**Comment by junegunn** [comment]
No.
