### ISSUE TITLE
Why should vim-plug be installed through githubusercontent.com not https://github.com/junegunn/vim-plug?

### ISSUE THREAD

**Issue by nowox** [junegunn/vim-plug#687]
It is advised to install vim-plug using: 

```
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
```

I would feel better using something like this:

```
git clone --depth=1 https://github.com/junegunn/vim-plug.git ~/.vim/autoload/plug.vim
```

What is it the advantage of using this discutable url (raw.githubusercontent.com)? 

Of course my way requires some tricks or place plug.vim in a autoload directory. 

- Type:
    - [ ] Bug
    - [x] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [x] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows

**Comment by janlazo** [comment]
You only need plug.vim and there is `PlugUpgrade` to get the latest. Documentation is at the top of plug.vim.
Unless you are submitting patches, you don't need the other files.
If you want to use git clone (or subtree or submodule) without touching `autoload/`, you have to source plug.vim explicitly in your vimrc.

```viml
" assume vim-plug is cloned in ~/.vim/vim-plug
runtime ~/.vim/vim-plug/plug.vim
call plug#begin('~/.vim/plugged')
```

**Comment by nowox** [comment]
I finally found a working solution using [dotbot](https://github.com/anishathalye/dotbot). I am using vim-plug as a submodule, but I only link `plug.vim` into `~/.vim/autoload/`. With this solution I explicitly know which version of `plug.vim` I am using

**Comment by junegunn** [comment]
> Of course my way requires some tricks or place plug.vim in a autoload directory.

So you already know the drawback of your approach. I would rather not tell the users to run multiple commands to install vim-plug when a single command can do. `raw.githubusercontent.com` is where GitHub serves raw git objects, and I can't see what the issue is. vim-plug has been quite stable for a long time and most users really don't have to upgrade it unless they run into some issues.
