### ISSUE TITLE
YouCompleteMe post installation problem (timeout)

### ISSUE THREAD

**Issue by alexbyk** [junegunn/vim-plug#689]
I'm trying to install YCM this way
```
Plug 'Valloric/YouCompleteMe', { 'do': './install.py' }
```
But the process breaks after around 10% of ```./install.py``` stuff. I can do the job by executing ```./install.py``` from the shell. But is there a way to let ``` { 'do': './install.py' }``` finish the job?

- Type:
    - [x] Bug
- OS:
    - [x] Linux
- Vim:
    - [x] Neovim
```
NVIM v0.2.0
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-LpFVCC/neovim-0.2.0/build/config -I/build/neovim-LpFVCC/neovim-0.2.0/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-LpFVCC/neovim-0.2.0/build/src/nvim/auto -I/build/neovim-LpFVCC/neovim-0.2.0/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by janlazo** [comment]
Can you fill up the issue template for more info?

**Comment by alexbyk** [comment]
ok. done

**Comment by junegunn** [comment]
> But the process breaks after around 10% of ./install.py

Any log messages? Anyway I don't think this is really an issue of vim-plug, as it does not timeout a running `do` process. Note that you can retry it by running the bang version of the command: i.e. `:PlugInstall! YouCompleteMe`

**Comment by alexbyk** [comment]
I don't know how to get log messages. I see only an output of ```./install.py``` and then suddenly "boom":
![screenshot](https://alexbyk.com/vim-plug-ycm-error.png)

**Comment by junegunn** [comment]
You can redirect the output to a log file. i.e. `{ 'do': './install.py > /tmp/ycm.log 2>&1' }`

**Comment by alexbyk** [comment]
@junegunn wow. Thanks for the tip. I was so sure that it's VimPlug bug that an idea to check `install.py` output didn't even cross my mind.

It turned out that it was neither VimPlug no YCM bug. I was messing with CPATH env variable in my vimrc. I've commented it and all works fine.

Thanks for the help
