### ISSUE TITLE
Let vim-plug manage itself

### ISSUE THREAD

**Issue by yous** [junegunn/vim-plug#69]
I used [Vundle.vim](https://github.com/gmarik/Vundle.vim) and liked the way of they [manages itself](https://github.com/gmarik/Vundle.vim#quick-start). I wondered if vim-plug is possible too, so I cloned vim-plug into `~/.vim/plugged/vim-plug` and tested with my .vimrc:

``` vim
set runtimepath=~/.vim/plugged/vim-plug
call plug#begin('~/.vim/plugged')
" Let vim-plug manage itself
Plug 'junegunn/vim-plug'
" Many plugs...
call plug#end()
```

Note that `plug.vim` is in root directory of vim-plug, so I moved it to `vim-plug/autoload/plug.vim` and it works flawlessly.

When this is done, `PlugUpdate` does `PlugUpgrade` too so it can be removed. But I think it can make some compatibility issue for pre-installed users.

**Comment by mgedmin** [comment]
Given that recent versions of vim-plug ship a help file that needs to be installed with

```vim
call plug#begin()
Plug 'junegunn/vim-plug'
...
call plug#(end)
```

I wonder if it would be safe to do

```vim
call plug#begin()
Plug 'junegunn/vim-plug', {'do': ':PlugUpgrade'}
call plug#(end)
```

so vim-plug will update itself whenever it notices new commits in the git repo, when I run `:PlugInstall`?

Or is that sort of thing (replacing the code that is currently running in multiple threads in parallel to update various things) a Bad Idea?

**Comment by yous** [comment]
See https://github.com/junegunn/vim-plug/wiki/faq#shouldnt-vim-plug-update-itself-on-plugupdate-like-vundle:

> If you really, really want to use `PlugUpdate` only, you can set up vim-plug like follows:
>
> ``` sh
> # Manually clone vim-plug and symlink plug.vim to ~/.vim/autoload
> mkdir -p ~/.vim/{autoload,plugged}
> git clone https://github.com/junegunn/vim-plug.git ~/.vim/plugged/vim-plug
> ln -s ~/.vim/plugged/vim-plug/plug.vim ~/.vim/autoload
> ```
>
> and in your .vimrc:
>
> ``` vim
> call plug#begin('~/.vim/plugged')
> Plug 'junegunn/vim-plug'
> " ...
> call plug#end()
> " The caveat is that you should *never* use PlugUpgrade
> delc PlugUpgrade
> ```
>
> Unlike `PlugUpgrade`, you'll have to restart Vim after vim-plug is updated.

You can't use `PlugUpgrade` if you put `Plug 'junegunn/vim-plug'`.

BTW, I can't find `Plug 'junegunn/vim-plug'` in README.md and doc/plug.txt.

**Comment by mgedmin** [comment]
> You can't use PlugUpgrade if you put Plug 'junegunn/vim-plug'.

You can, if ~/.vim/autoload/plug.vim is a file and not a symlink.

> BTW, I can't find Plug 'junegunn/vim-plug' in README.md and doc/plug.txt.

It's documented in https://github.com/junegunn/vim-plug/wiki/tips#vim-help
