### ISSUE TITLE
Python environment not found

### ISSUE THREAD

**Issue by kdbeall** [junegunn/vim-plug#695]
I'm using vim-plug for the [fsharp plugin](https://github.com/fsharp/vim-fsharp)
I get the following error message when opening .fsharp files:

Error detected while processing /home/kdbeall/.vim/plugged/vim-fsharp/ftplugin/fsharp.vim:
line   37:
Python environment not found

However, I have Python installed
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 30 2017 18:21:38)
Included patches: 1-197, 322, 377-378, 550, 703, 706-707
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl             +comments        +extra_search    +keymap          +mouse_dec       +path_extra      +smartindent     +title           -xfontset
+arabic          +conceal         +farsi           +lambda          +mouse_gpm       -perl            +startuptime     -toolbar         -xim
+autocmd         +cryptv          +file_in_path    +langmap         -mouse_jsbterm   +persistent_undo +statusline      +user_commands   -xpm
-balloon_eval    +cscope          +find_in_path    +libcall         +mouse_netterm   +postscript      -sun_workshop    +vertsplit       -xsmp
-browse          +cursorbind      +float           +linebreak       +mouse_sgr       +printer         +syntax          +virtualedit     -xterm_clipboard
++builtin_terms  +cursorshape     +folding         +lispindent      -mouse_sysmouse  +profile         +tag_binary      +visual          -xterm_save
+byte_offset     +dialog_con      -footer          +listcmds        +mouse_urxvt     -python          +tag_old_static  +visualextra
+channel         +diff            +fork()          +localmap        +mouse_xterm     -python3         -tag_any_white   +viminfo
+cindent         +digraphs        +gettext         -lua             +multi_byte      +quickfix        -tcl             +vreplace
-clientserver    -dnd             -hangul_input    +menu            +multi_lang      +reltime         +termguicolors   +wildignore
-clipboard       -ebcdic          +iconv           +mksession       -mzscheme        +rightleft       +terminfo        +wildmenu
+cmdline_compl   +emacs_tags      +insert_expand   +modify_fname    +netbeans_intg   -ruby            +termresponse    +windows
+cmdline_hist    +eval            +job             +mouse           +num64           +scrollbind      +textobjects     +writebackup
+cmdline_info    +ex_extra        +jumplist        -mouseshape      +packages        +signs           +timers          -X11
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-R2d1UQ/vim-8.0.0197=. -fstack-protector-strong -Wformat -Werro
r=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux -lacl -lattr -lgpm -ldl

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x]  Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
It's not an issue of vim-plug, please use the issue tracker of the plugin.
