### ISSUE TITLE
Open readme file for plugin

### ISSUE THREAD

**Issue by Freedzone** [junegunn/vim-plug#696]
Hello.
Some plugins come without help doc, usually they are small additions or color schemes. When you have many plugins and try to manage your collection it could be useful to quickly review its functionality through readme files. You can put the cursor on plugin's name inside .vimrc, call a function and it will open its README file in the new window.

------------------------------

```

```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [x] Feature Request
    - [ ] Question
- OS:
    - [x] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
This is the snippet I use for that purpose. It requires fzf, but you get the idea.

```vim
function! s:plug_help_sink(line)
  let dir = g:plugs[a:line].dir
  for pat in ['doc/*.txt', 'README.md']
    let match = get(split(globpath(dir, pat), "\n"), 0, '')
    if len(match)
      execute 'tabedit' match
      return
    endif
  endfor
  tabnew
  execute 'Explore' dir
endfunction

command! PlugHelp call fzf#run(fzf#wrap({
  \ 'source': sort(keys(g:plugs)),
  \ 'sink':   function('s:plug_help_sink')}))
```

 I added it to the wiki page. https://github.com/junegunn/vim-plug/wiki/extra#browse-help-files-and-readmemd
