### ISSUE TITLE
How to install numbers.vim using vim-plug

### ISSUE THREAD

**Issue by vivekanand1101** [junegunn/vim-plug#697]
How do i install numbers.vim by myusuf3? I tried: Plug 'myusuf3/numbers' , Plug 'myusuf3/numbers.vim' yesterday and it didn't work.
:PlugInstall gave me: 
 x numbers:                                                                                                                                                           
 Invalid URI: https://github.com/myusuf3/numbers.vim.git                                                                                                          
 Expected:    https://github.com/myusuf3/numbers.git                                                                                                              
 PlugClean required.

```
:version                                                                                                                                                                 
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 13 2017 07:02:21)                                                                                                       
Included patches: 1-1187                                                                                                                                                 
Modified by <bugzilla@redhat.com>                                                                                                                                        
Compiled by <bugzilla@redhat.com>  
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [&#10003;] Question
- OS:
    - [ ] All/Other
    - [&#10003; ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [&#10003;] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by vivekanand1101** [comment]
wow, i ruined it

**Comment by KDercksen** [comment]
`Plug 'myusuf3/numbers.vim'` works as intended for me. Try PlugClean or manually removing any numbers plugin directories and then try again maybe?

**Comment by vivekanand1101** [comment]
great. It worked. I don't know why it didn't work before. Does vim-plug need vim to be closed and started again after doing any changes in .vimrc?

**Comment by nfischer** [comment]
> Does vim-plug need vim to be closed and started again after doing any changes in .vimrc?

You at least need to source your vimrc. The simplest way to do so is to close vim and restart it.

**Comment by vivekanand1101** [comment]
Thanks @KDercksen  and @nfischer . Closing this one as it works for me now.
