### ISSUE TITLE
Incorrect oneline range for range=% on-demand command

### ISSUE THREAD

**Issue by SolaWing** [junegunn/vim-plug#698]
when triggering a on-demand command which define as `range=%`, and call as `.,.Command`, the range should be current line range, not the entire file range.

------------------------------

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [x] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [x] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
You should be aware that on-demand loading (via `on` and `for` options) is not guaranteed to work in all cases. In this case, vim-plug cannot know how the command is defined without actually loading the plugin.

A good rule of thumb is not to set up on-demand loading. Don't waste your time trying to make it work when it doesn't.

https://github.com/junegunn/vim-plug/wiki/faq#when-should-i-use-on-or-for-option

**Comment by SolaWing** [comment]
Thank you for response. I now write a specific command calling `plug#load` to deal range consistently.
