### ISSUE TITLE
How to load a plugin for every except a specific language?

### ISSUE THREAD

**Issue by Integralist** [junegunn/vim-plug#700]
I've looked around and couldn't find if there was a way to load a plugin only if the file type _isn't_ a `.go` file?

e.g. I want to load my plugin all the time unless I'm working with a go file, and in those instances I want the plugin turned off

Any ideas?

Thanks.

**Comment by Integralist** [comment]
OK I figured this out using part of the example found in the FAQ...

```viml
fun! LoadSimpleAutoCompletePlugin()
  " Load vim-simple-complete for everything except .go files
  if &ft == "go"
    return
  endif
  call plug#load('vim-simple-complete')
endfun

augroup LoadSACP
  " remove any previously loaded autocmd! for the InsertEnter event
  autocmd!
  autocmd InsertEnter * call LoadSimpleAutoCompletePlugin() | autocmd! LoadSACP
augroup END
```

**Comment by junegunn** [comment]
Yeah, that's basically how it's done, but I wouldn't try too hard to write such custom autocmds. A Vim plugin is just a collection of scripts that change the global state of the Vim process, there's no way of "unloading" a plugin without restarting the process, so once you load a non-go file...
