### ISSUE TITLE
Cannot see colorscheme

### ISSUE THREAD

**Issue by GaryFurash** [junegunn/vim-plug#708]
Explain the problem here ...

------------------------------

```

```

- Type:
    - [X ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [X ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ X] Windows
- Vim:
    - [ ] Terminal Vim
    - [X] GVim
    - [ ] Neovim

If I use PLUG to install the solarized colorscheme, it installs the plugin just fine, but doesn't recognize that the color has been installed unless I move it to ~/.vim/colors. Other plugins work fine.

**Comment by junegunn** [comment]
Load it after `plug#end()`
