### ISSUE TITLE
Unknown function: plug#begin plug#end due to site-folder

### ISSUE THREAD

**Issue by dominicparga** [junegunn/vim-plug#710]
I've added
```vim
if empty(glob("~/.config/nvim/site/autoload/plug.vim"))
    execute "!curl -fLo ~/.config/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
endif
```
to my `~/.config/nvim/init.vim`. Calling `plug#begin("~/.config/nvim/plugged")` and `plug#end()` in `init.vim` failed, because they are not known.

When comparing the path for NeoVim to the given one for vim
```
~/.vim/autoload/plug.vim
~/.config/nvim/site/autoload/plug.vim
```
I recognized the folder `site`, which only exists in the explanation for NeoVim, but not for Vim. After removing `site`, I could use vim-plug as expected (tested via [Townk/vim-autoclose](https://github.com/Townk/vim-autoclose)).

------------------------------

```
NVIM v0.2.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -pipe -Os -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-
parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/opt/local/var/macports
/build/_opt_bblocal_var_buildworker_ports_build_ports_editors_neovim/neovim/work/build/config -I/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_edito
rs_neovim/neovim/work/neovim-0.2.1/src -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/
include -I/opt/local/include -I/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_editors_neovim/neovim/work/build/src/nvim/auto -I/opt/local/var/macpor
ts/build/_opt_bblocal_var_buildworker_ports_build_ports_editors_neovim/neovim/work/build/include
Übersetzt von macports@highsierra.internal.macports.net

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

          System-vimrc-Datei: "$VIM/sysinit.vim"
     Voreinstellung für $VIM: "/opt/local/share/nvim"

Run :checkhealth for more info
```

- Type:
    - [ ] Bug
    - [X] Enhancement
    - [ ] Feature Request
    - [X] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [X] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [X] Neovim

**Comment by junegunn** [comment]
Any reason you're not following the official instruction?

https://github.com/junegunn/vim-plug#neovim

**Comment by dominicparga** [comment]
Ups, thought `.config` is a neovim-specific file and wanted everything collected in there, but `.config` and `.local/share` seem to be a general way of home config management ([understanding-home-config-file-locations](https://unix.stackexchange.com/questions/312988/understanding-home-configuration-file-locations-config-and-local-sha). Will use `.local/share` as described.

Thanks for your quick response, sorry for my misunderstanding of unix-configs :3
