### ISSUE TITLE
Can vim-plug find my right colorscheme file?

### ISSUE THREAD

**Issue by Mamad026** [junegunn/vim-plug#712]
Hi.
I use [this](https://github.com/lifepillar/vim-solarized8) ColorScheme as my default in vimrc and I know there is no difference between colorschemes and plugins in vim-plug and it can be set like plugins.
But if you check that git you will see **vary** .vim file in **vim-solarized8/colors/** and I  setted _solarized8_dark_high.vim_ in vimrc. Now, Where does vim-plug save those colorscheme?
Because if I set a colorscheme after lines vim will search for that in ~/.vim/colors (not in dir that vim-plug saved it) so, How can I set that correctly?

**Comment by Mamad026** [comment]
Now I do a examination and it really doesn't correctly, I added `Plug lifepillar/vim-solarized8` and vim-plug installed it properly. After lines I set colo to solarized_dark_high by add `colo solarized_dark_high` but when I enter :colo in vim command-line it will return "solarized_high" it's wrong, Why? 
Please let me know how can I fix this. Thanks.

**Comment by junegunn** [comment]
It doesn't look like an issue of vim-plug, you should ask the maintainer of the repository.

**Comment by Mamad026** [comment]
OK. Thanks
