### ISSUE TITLE
Pymode requires cloning using flag --recursive

### ISSUE THREAD

**Issue by alnavv** [junegunn/vim-plug#716]
Hi there, simple question:

cloning for the first time requires:
git clone --recursive https://github.com/python-mode/python-mode

how to add the flag "--recursive"  in vim Plug?

thanks,
   A.

**Comment by nfischer** [comment]
I think you can use a post-update hook for something like `git submodule update --init --recursive`. I assume post-update hooks run after installing--I haven't verified this though.

**Comment by junegunn** [comment]
It should be handled automatically.

https://github.com/junegunn/vim-plug/blob/96375cb7d30b7caf2a9417799ff509b59b43a627/plug.vim#L1099-L1103

Please let me know if it doesn't.

**Comment by jeetsukumaran** [comment]
Hi,

I find that this did not work for me when trying to install the vim-jedi plugin.

I have the following in my ``~/.vimrc``:

        Plug 'https://github.com/davidhalter/jedi-vim'

And have run PlugInstall, PlugUpdate etc. numerous times. Still jedi could not be found (and it was not available in my pre-compiled macvim). Finally deleted the 'vim-jedi' directory and manually cloned it myself using 
```
git clone --recursive http://github.com/davidhalter/jedi-vim
```

That did the trick. It would be really nice to have vim-plug handle this as an option.

**Comment by virus-found** [comment]
> It should be handled automatically.
> 
> [vim-plug/plug.vim](https://github.com/junegunn/vim-plug/blob/96375cb7d30b7caf2a9417799ff509b59b43a627/plug.vim#L1099-L1103)
> Lines 1099 to 1103 in [96375cb](/junegunn/vim-plug/commit/96375cb7d30b7caf2a9417799ff509b59b43a627)
>  if !v:shell_error && filereadable(spec.dir.'/.gitmodules') && 
>        \ (s:update.force || has_key(s:update.new, name) || s:is_updated(spec.dir)) 
>    call s:log4(name, 'Updating submodules. This may take a while.') 
>    let out .= s:bang('git submodule update --init --recursive 2>&1', spec.dir) 
>  endif 
> Please let me know if it doesn't.

There is a case, when it doesn't work.
```
Plug 'noah/vim256-color'
```
```
Submodule 'submodules/256-grayvim' (https://github.com/vim-scripts/256-grayvim.git) registered for path 'submodules/256-grayvim'
Submodule 'submodules/256-jungle' (https://github.com/vim-scripts/256-jungle.git) registered for path 'submodules/256-jungle'
Submodule 'submodules/Apprentice' (https://github.com/romainl/Apprentice.git) registered for path 'submodules/Apprentice'
Submodule 'submodules/BusyBee' (https://github.com/vim-scripts/BusyBee.git) registered for path 'submodules/BusyBee'
Submodule 'submodules/C64.vim' (https://github.com/vim-scripts/C64.vim.git) registered for path 'submodules/C64.vim'
Submodule 'submodules/ChasingLogic-colorscheme-vim' (https://github.com/ChasingLogic/ChasingLogic-colorscheme-vim.git) registered for path 'submodules/ChasingLogic-colorscheme-vim'
Submodule 'submodules/Disciple' (https://github.com/romainl/Disciple.git) registered for path 'submodules/Disciple'
fatal: No url found for submodule path 'submodules/FlatColor' in .gitmodules

shell returned 128
```
Manual cloning with --recursive works fine.

**Comment by junegunn** [comment]
The repository seems to have a issue. The standard procedure using `git submodule` doesn't work with it.

```sh
git clone  https://github.com/noah/vim256-color.git
cd vim256-color/
git submodule update --init --recursive
```
