### ISSUE TITLE
I cannot combine options rtp and dir to sync a single file from a repo

### ISSUE THREAD

**Issue by pescobar** [junegunn/vim-plug#717]
I am trying to use vim-plug to install https://github.com/altercation/vim-colors-solarized/blob/master/colors/solarized.vim to `~/.vim/colors/solarized.vim` and I thought I could combine options `rtp` and `dir` to achieve this by adding this line to my `~/.vimrc`

```Plug 'altercation/vim-colors-solarized', { 'rtp': 'colors', 'dir': '~/.vim/colors'}```

But after doing `PlugInstall` I end up with the complete repo cloned in the colors folder:

```
$ ls -a ~/.vim/colors
.  ..  autoload  bitmaps  colors  doc  .git  README.mkd
```

Is this the expected behaviour or am I doing something wrong? Is it possible to use vim-plug to only sync the file `colors/solarized.vim` from the repo to my `~/.vim/colors` folder?

------------------------------

```
:version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl             -clipboard       +dialog_con      +file_in_path    +job             +menu            -mouse_sysmouse  +persistent_undo +scrollbind      +tcl             +visual          -xim
+arabic          +cmdline_compl   +diff            +find_in_path    +jumplist        +mksession       +mouse_urxvt     +postscript      +signs           +terminfo        +visualextra     -xsmp
+autocmd         +cmdline_hist    +digraphs        +float           +keymap          +modify_fname    +mouse_xterm     +printer         +smartindent     +termresponse    +viminfo         -xterm_clipboard
-balloon_eval    +cmdline_info    -dnd             +folding         +langmap         +mouse           +multi_byte      +profile         +startuptime     +textobjects     +vreplace        -xterm_save
-browse          +comments        -ebcdic          -footer          +libcall         -mouseshape      +multi_lang      -python          +statusline      +timers          +wildignore      -xpm
++builtin_terms  +conceal         +emacs_tags      +fork()          +linebreak       +mouse_dec       -mzscheme        +python3         -sun_workshop    +title           +wildmenu
+byte_offset     +cryptv          +eval            +gettext         +lispindent      +mouse_gpm       +netbeans_intg   +quickfix        +syntax          -toolbar         +windows
+channel         +cscope          +ex_extra        -hangul_input    +listcmds        -mouse_jsbterm   +packages        +reltime         +tag_binary      +user_commands   +writebackup
+cindent         +cursorbind      +extra_search    +iconv           +localmap        +mouse_netterm   +path_extra      +rightleft       +tag_old_static  +vertsplit       -X11
-clientserver    +cursorshape     +farsi           +insert_expand   +lua             +mouse_sgr       +perl            +ruby            -tag_any_white   +virtualedit     -xfontset
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim
-lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.22/CORE -lperl -ldl -lm -lpthread -lcrypt
 -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm
```

- Type:
    - [ ] Bug
    - [X] Enhancement
    - [X] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [X] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [X] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by janlazo** [comment]
That colorscheme file relies on `autoload/` in the repo so you cannot optimize by extracting only the colorscheme file out of the entire repo. That repo is designed to be cloned and added to `runtimepath` option as is such that `rtp` option shouldn't be used. `dir` is for installed plugins outside of `~/.vim/plugged/` like fzf.

**Comment by threewholefish** [comment]
Out of interest, does the `rtp` option work on its own? I can't seem to get it to work in Neovim v0.2.1-359-g144f5849

**Comment by janlazo** [comment]
`rtp` is for using a subdirectory of the repo root folder because, by default, the repo root folder is assumed to be a Vim package. It should work on its own.

**Comment by ysooqe** [comment]
> Out of interest, does the `rtp` option work on its own? I can't seem to get it to work in Neovim v0.2.1-359-g144f5849

I do experience the same issue.
When trying to use the `rtp` option, it will always clone the whole repository instead of the specified subdirectory.
Have you figured out, why that could be?

**Comment by junegunn** [comment]
> Is this the expected behaviour or am I doing something wrong? 

It's how it works. There's no option to clone only a subdirectory, a.k.a sparse checkout. We decided not to support it. See #122 and #436.
