### ISSUE TITLE
Dont' advertise disabling SSL verification

### ISSUE THREAD

**Issue by languitar** [junegunn/vim-plug#718]
The [tips wiki page](https://github.com/junegunn/vim-plug/wiki/tips) advertises the following regarding the automatic installation of the plugin in the vimrc:

> (If you're behind an HTTP proxy, you may need to add --insecure option to the curl command. In that case, you also need to set $GIT_SSL_NO_VERIFY to true.)

Please either explain the effect this has and the potential security issues or remove that text at all.

**Comment by janlazo** [comment]
Done https://github.com/junegunn/vim-plug/wiki/tips#http-proxy-issues-warning
