### ISSUE TITLE
Vim-plug Not an Editor command?

### ISSUE THREAD

**Issue by Trueyes** [junegunn/vim-plug#722]
I followed the readme down to the teeth ,but everytime I try to call a PlugInstall, I get an error:
"Not an Editor command"
Furthermore when opening the _vimrc file with vim I get these errors:

Error detected while processing C:\Users\"Name"\Vim\_vimrc:

line    2:

E117: Unknown function: plug#begin

line    4:

E492: Not an editor command: Plug 'tpope/vim-sensible'

line    7:

E117: Unknown function: plug#end

Below is my vim rc file:

"Specify a directory for plugins
call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-sensible'

"Initialize plugin system
call plug#end()

------------------------------
-I am on windows 10
-I use gvim
-I am using the latest version of vim

**Comment by tracyone** [comment]
Execute following command and see if **plug.vim** is in one of  the path of rtp option.

```vim
:set rtp?
```

**Comment by Trueyes** [comment]
I get this:

runtimepath=~/vimfiles,~\Vim/vimfiles,~\Vim\vim80,~\Vim/vimfiles/after,~/vimfiles/after

**Comment by Trueyes** [comment]
I figured it out.I moved plug.vim into autoload and then changed my call plugin to point towards the folder I wanted it to install. Thank you, I had to utilize one of the rumtimepath to get this to work
