### ISSUE TITLE
PlugUpdate/PlugUpgrade is backwards from convention

### ISSUE THREAD

**Issue by Grazfather** [junegunn/vim-plug#729]
I went to update my plugins today and ran `:PlugUpgrade` but was surprised to see that this actually updates vim-plug itself, and not the plugins. `:PlugUpdate` is what I needed.

This goes against popular convention, think `apt` and `brew`.

Would you consider swapping it?

**Comment by junegunn** [comment]
Thanks for the suggestion, but no. People have been using vim-plug for more than 4 years by now, and I wouldn't suddenly change the commands.
