### ISSUE TITLE
Rate Limit or Delay/Sleep option

### ISSUE THREAD

**Issue by skulumani** [junegunn/vim-plug#733]
I am using neovim on a school network with 36 plugins. The network has a malware detection flag that is triggered when my system makes 30 calls to the same IP (github) in a short time period. 

Is there any method to limit the requests, or to add a sleep time in between each plugin?

I know that it is possible update plugins individually but a setting to increase the delays might be useful.

Thank you for the great plugin, and all of the other great tools you've developed. 

------------------------------

```
:version                                                                                                             
NVIM v0.2.2
Build type: RelWithDebInfo
LuaJIT 2.0.4
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wd
ate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_
SOURCE=1 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wst
rict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -
D_GNU_SOURCE -I/build/neovim-HJnLxJ/neovim-0.2.2/build/config -I/build/neovim-HJnLxJ/neovim-0.2.2/src -I/usr/include
-I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-HJnLxJ/neov
im-0.2.2/build/src/nvim/auto -I/build/neovim-HJnLxJ/neovim-0.2.2/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
Press ENTER or type command to continue

```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [X] Feature Request
    - [X] Question
- OS:
    - [ ] All/Other
    - [X] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [X] Terminal Vim
    - [ ] GVim
    - [X] Neovim

**Comment by junegunn** [comment]
You can pass the number of concurrent git processes to `PlugInstall` and `PlugUpdate`, e.g. `:PlugUpdate4`. Or you can permanently set `g:plug_threads` to a smaller number than the default 16. See https://github.com/junegunn/vim-plug#global-options
