### ISSUE TITLE
Produces "implicit `vim-scripts' expansion is deprecated" error when using env. variables with `Plug` command

### ISSUE THREAD

**Issue by kutsan** [junegunn/vim-plug#734]
Because of this line,

```vim
Plug $FZF_HOME | Plug 'junegunn/fzf.vim'
```

vim produces this error when starting it.

```sh
$ sudo vim /etc/hosts
[vim-plug] Invalid argument:  (implicit `vim-scripts' expansion is deprecated)
Press ENTER or type command to continue
```

[`$FZF_HOME`](https://github.com/kutsan/dotfiles/blob/5f1a613f56be88bc79fb1b7a1318fd02b06af469/.zsh/config/plugins.zsh#L1-L18) is a valid environment variable and its value is `/usr/local/opt/fzf` for that machine.

Note that fzf plugin works as intended and there is an empty space after "Invalid argument:" string.

Stack trace for you:

1. https://github.com/junegunn/vim-plug/blob/96375cb7d30b7caf2a9417799ff509b59b43a627/plug.vim#L586
2. https://github.com/junegunn/vim-plug/blob/96375cb7d30b7caf2a9417799ff509b59b43a627/plug.vim#L550
3. https://github.com/junegunn/vim-plug/blob/96375cb7d30b7caf2a9417799ff509b59b43a627/plug.vim#L547
4. https://github.com/junegunn/vim-plug/blob/96375cb7d30b7caf2a9417799ff509b59b43a627/plug.vim#L304

------------------------------

```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVI
M_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wv
la -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20171118-53412-9ielcr/neovim-0.2.2/build/config -I/
tmp/neovim-20171118-53412-9ielcr/neovim-0.2.2/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/incl
ude -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20171118-53412-9ielcr/neovim-0.2.2/build/src/nvim/auto -I/tmp/ne
ovim-20171118-53412-9ielcr/neovim-0.2.2/build/include
Compiled by brew@Sierra-2.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.2/share/nvim"

Run :checkhealth for more info
```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [x] OS X
    - [ ] Windows (I don't know, but probably yes.)
- Vim:
    - [x] Terminal Vim
    - [x] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
`sudo` does not preserve environment variables by default. Try with `sudo -E`.

**Comment by kutsan** [comment]
Duh! Didn't even think that. Thanks!
