### ISSUE TITLE
Not an editor command: PlugInstall neovim

### ISSUE THREAD

**Issue by owencraston** [junegunn/vim-plug#735]
### Problem

I am getting the error `Not an editor command: PlugInstall` after trying to configure `vim-plug` with neovim.

I have followed the instructions but still seem to be getting the error.

### Steps I have taken so far

1. I installed [neovim] (https://github.com/neovim/neovim/wiki/Installing-Neovim) using `brew install neovim` and it was successful.

3. I use a `dotfiles` directory to manage my configs and so I set up a symbolic link between the file `~/dotfiles/nvimrc` and ` ~/.config/nvim/init.vim`.

3. Install `vim-plug` using the following command
```
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
```

4. populate my `init.vim` or in my case `nvimrc` with the following
```
" pecify a directory for plugins
" - For Neovim: ~/.local/share/nvim/plugged
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.config/nvim/autoload/plug.vim')

" Make sure you use single quotes

" Shorthand notation; fetches https://github.com/junegunn/vim-easy-align
Plug 'junegunn/vim-easy-align'

" Any valid git URL is allowed
Plug 'https://github.com/junegunn/vim-github-dashboard.git'

" Initialize plugin system
call plug#end()
```
(yes I did try using `~/.local/share/nvim/plugged` in the `call plug#begin()`)

5. Run `:PlugInstall` and get the error `E492: Not an editor command: PlugInstall`

How can I get this to work? Could it be a probem with the symbolic links?

- `vim: version 8.0.1500`
- neovim: NVIM v0.2.2`
- `macOS high sierra version 10.13.3`

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [x] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by owencraston** [comment]
### Fixed
- I updated the symbolic link to have the correct path (I had previously not included the full pth name when using the `ln` command)
- update `call plug#begin` to `call plug#begin('~/.config/nvim/plugged')`
- `PlugInstall`

**Comment by quangthanh0909** [comment]
Many thanks, It works for me.

**Comment by darklaser28** [comment]
It still doesn't work. And i can't find the nvim folder in .config

**Comment by manojuppala** [comment]
you need to create a ~/.config/nvim/ folder by yourself.

**Comment by jeevanghimire** [comment]
Still says the same problem 
E492: Not an editor command: PlugInstall

**Comment by amirrezaalavi** [comment]
> Still says the same problem E492: Not an editor command: PlugInstall

Hey body, check this out : [https://github.com/junegunn/vim-plug](url)

**Comment by Vivraan** [comment]
Stuck exactly here. Followed official instructions. Tried changing the path. Doesn't work -- help appreciated.

**Comment by Saurav-S-Purushothaman** [comment]
Me as well. Stuck here. Tried changing the path to the path which contains the plug.vim file. Doesn't work --help appreciated.
