### ISSUE TITLE
Suggestion: allow rules between call begin/end

### ISSUE THREAD

**Issue by trevordmiller** [junegunn/vim-plug#736]
Thanks for vim-plug! It's a fantastic tool :) It would be cool if you could put config next to plug commands to keep plugin related stuff together.

## Now

```vim
" VIM-PLUG
call plug#begin('~/.vim/plugged')
Plug 'trevordmiller/nova-vim'
Plug 'sheerun/vim-polyglot'
Plug 'KeyboardFire/vim-minisnip'
call plug#end()

" NOVA-VIM
colorscheme nova

" VIM-POLYGLOT
let g:javascript_plugin_flow = 1

" VIM-MINISNIP
let g:minisnip_dir = '~/.snippets/'
```

## Suggestion

```vim
call plug#begin('~/.vim/plugged')
Plug 'trevordmiller/nova-vim'
  colorscheme nova
Plug 'sheerun/vim-polyglot'
  let g:javascript_plugin_flow = 1
Plug 'KeyboardFire/vim-minisnip'
  let g:minisnip_dir = '~/.snippets/'
call plug#end()
```

## System

I'm on latest Vim + vim-plug.

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [x] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [x] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by trevordmiller** [comment]
Right now if you try this you get an error like:
![image](https://user-images.githubusercontent.com/5497885/36462389-4b757f26-1680-11e8-80f2-3c6fb50d1bca.png)

**Comment by junegunn** [comment]
Plugins are not added to `&runtimepath` until `plug#end()` (see https://github.com/junegunn/vim-plug#usage), so you can't load a color scheme or run a command from a plugin before the point. On the other hand, `let g:foo = ..` is just setting a global variable so you can do it at any point.

The problem you have with `colorscheme` can be easily avoided by deferring the execution of the code using `VimEnter` autocmd. i.e. `autocmd VimEnter * colorscheme nova `
