### ISSUE TITLE
How to roll back to last updates

### ISSUE THREAD

**Issue by vanabel** [junegunn/vim-plug#738]
I am just wondering that is there a quick way to roll back to the last updates? Since after the updates of a plugin, I find it is not work for some reason.

**Comment by junegunn** [comment]
https://github.com/junegunn/vim-plug/wiki/tutorial#reviewing-the-changes

**Comment by mikeslattery** [comment]
@junegunn Although `:PlugDiff` is a very nice feature, I don\'t believe it adequately satisfies this question / feature request.

* If you don\'t notice an issue until the next day after you've restart vim, `PlugDiff` won't give you any output.
* You get a diff, but no easy to way to do a rollback.  `PlugRollback 'yyyy-mm-dd hh:mm'` would be nice.  (Which would pass the date+time to `git` for parsing).

I\'ve written my own script for doing rollbacks.

```sh
#!/bin/bash
set -eu
datetime="$1"

find ~/.local/share/nvim/plugged -mindepth 1 -maxdepth 1 -type d -print0| \
  xargs -r0 -I{} -t git -C {} --no-pager checkout "@\{${datetime}\}"
```
 
As always, I love your plugins and utilities, esp `fzf`.  Thanks for making my work that much easier.
