### ISSUE TITLE
Tips should also describe automatic installation for Neovim

### ISSUE THREAD

**Issue by mastertinner** [junegunn/vim-plug#739]
https://github.com/junegunn/vim-plug/wiki/tips#automatic-installation should also state the code for Neovim:

```vim
if empty(glob('~/.local/share/nvim/site/autoload/plug.vim'))
    silent !curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
```

**Comment by pmav99** [comment]
A minor improvement might be to use `stdpath()` which resolves XDG directories by itself:
``` vimscript
" Bootstrap Plug
let autoload_plug_path = stdpath('data') . '/site/autoload/plug.vim'
if !filereadable(autoload_plug_path)
  silent execute '!curl -fLo ' . autoload_plug_path . ' --create-dirs "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
unlet autoload_plug_path
```

**Comment by MadWombat** [comment]
I am trying to setup auto install on neovim on OS X. The first problem with the above code is that neovim seems to look for config in `~/.config/nvim` rather than `~/.local/share/nvim`, so `stdpath('data')` should be `stdpath('config')`.

The other problem is that VimEnter event happens after all the startup processing, so any directives in the init.vim that require the plugins will fail (yes, the config will get reloaded, but still, getting all those errors for no reason is... inelegant). What seems to work is this

```
let plug_install = 0
let autoload_plug_path = stdpath('config') . '/autoload/plug.vim'
if !filereadable(autoload_plug_path)
    silent exe '!curl -fL --create-dirs -o ' . autoload_plug_path . ' https://raw.github.com/junegunn/vim-plug/master/plug.vim'
    execute 'source ' . fnameescape(autoload_plug_path)
    let plug_install = 1
endif
unlet autoload_plug_path

call plug#begin('~/.config/nvim/plugins')
... plugins ...
call plug#end()

if plug_install
    PlugInstall --sync
endif
unlet plug_install
```

This way, I can just download my init.vim into ~/.config/nvim and start nvim and I am all set :)

**Comment by janlazo** [comment]
See https://github.com/junegunn/vim-plug/issues/758#issuecomment-541817085

**Comment by xerus2000** [comment]
@MadWombat but the _automatically downloaded_ plug.vim is no configuration, so it makes total sense in the data dir, or not?

**Comment by zuqini** [comment]
@janlazo Sorry for digging up an old issue, but this doesn't seem like a duplicate of #758. I vote to reopen this issue.

This is asking to update the wiki to include a neovim version of automatic vim-plug installation:
https://github.com/junegunn/vim-plug/wiki/tips#automatic-installation.

**Comment by janlazo** [comment]
done.

**Comment by Xunius** [comment]
I might be late so the version in the wiki page now is:

```
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
```

Could anyone help clarify that this is a version that works for both vim and neovim?
 But there is a line of description:

> Place the following code in your .vimrc before plug#begin() call

The `.vimrc` seems to imply that this is for vim. So, do we have a neovim version or not?

**Comment by gitsang** [comment]
> let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'

Of course it can use in neovim. `has('nvim')` is the evidence.
