### ISSUE TITLE
Feature request: always run PlugSnapshot before update

### ISSUE THREAD

**Issue by romgrk** [junegunn/vim-plug#742]
I would like to request for this plugin to always keep a snapshot before the last PlugUpdate. Reason is I ran a PlugUpdate a few days ago, and I've been noticing some plugins behaving incorrectly. Now, I'd like to bisect them but I don't know where to start because I didn't knew about PlugSnapshot before a few minutes ago. Therefore, I think it could be interesting for this plugin to always take a snapshot before updating, and maybe save it to some pre-definied standard location. (e.g. `$XDG_CACHE_HOME`).

------------------------------

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [x] Feature Request
    - [ ] Question
- OS:
    - [x] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [x] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
> I don't know where to start

Try `:PlugDiff`.

https://github.com/junegunn/vim-plug/wiki/tutorial#reviewing-the-changes
