### ISSUE TITLE
The ability to get scripts from vim.org

### ISSUE THREAD

**Issue by ukch** [junegunn/vim-plug#744]
Continued from #202 (closed).
Since `vim-scripts` is no longer maintained, there is no way to fetch the latest versions of scripts that do not have their own git repos (e.g. [IndentConsistencyCop](https://www.vim.org/scripts/script.php?script_id=1690)).
It would be awesome if we could continue to be able to update these scripts using `vim-plug`. Do you see supporting the downloading of scripts directly from vim.org anywhere on the horizon?

**Comment by kutsan** [comment]
Allow me to interject, why they don't have git repositories? Are they believe version control system is a sin?

**Comment by chrisbra** [comment]
I know Ingo maintains his plugins on github. Oh quoting from your link:


> INSTALLATION 
> The code is hosted in a Git repo at     https://github.com/inkarkat/vim-IndentConsistencyCop You can use your favorite plugin manager, or "git clone" into a directory used for Vim packages. Releases are on the "stable" branch, the latest unstable development snapshot on "master".
>

**Comment by achilleas-k** [comment]
Came here to ask the same.  YankRing was updated recently (after almost 4 years) https://www.vim.org/scripts/script.php?script_id=1234 but the https://github.com/vim-scripts/YankRing.vim mirror will probably never get updated.

**Comment by Shrekster** [comment]
freq+ ; this is now out of sync too:

https://www.vim.org/scripts/script.php?script_id=2140
https://github.com/vim-scripts/xoria256.vim

**Comment by junegunn** [comment]
vim-plug heavily relies on git (one can even say that it's basically a git wrapper for Vim plugins) and I don't think we're ever going to support different mechanisms.
