### ISSUE TITLE
[feature] 'for' option should work with 'empty' filetype

### ISSUE THREAD

**Issue by NewUserHa** [junegunn/vim-plug#745]
gvim 8
windows

I'm using fidian/hexmode for exe/dll, which is empty filetype, but after the plugin work, it's xxd filetype.

I want this plugin start on-demand for exe/dll/etc. only.

I tried 'for': '' but failed.

can you consider make this valid and become a feature?

thanks!

**Comment by NewUserHa** [comment]
also there's some heavy plugins that you don't want to clean when you're cleaning the disk.
also can use like 'for': 'none' for placeholder or 'for': 'any' for any filetypes!

**Comment by junegunn** [comment]
I guess it doesn't work because on those files, `FileType` event is never triggered which vim-plug listens to. See if a custom autocmd shown below helps.

```vim
augroup vimrc
  autocmd!
  autocmd BufNewFile,BufRead *.exe,*.dll let &filetype = ''
augroup END
```

**Comment by janlazo** [comment]
`:h ftdetect`
`:h hex-editing`
Create autocmds for binary extensions to explicitly set `filetype` before `VimEnter` so that you can use it on the `for` option.
