### ISSUE TITLE
Windows 'after install do' can't find files relative to git repo

### ISSUE THREAD

**Issue by cbcoutinho** [junegunn/vim-plug#746]
I use the post-install `do` feature for a few plugins that require to be installed, which works great on Linux but fails on Windows 10 - both using Neovim. On Linux, the `do` flag executes whatever it needs to from within the cloned plugin repository; however on Windows it tries to run the command from my $HOME directory. This fails because the command expects to be run within the plugin directory itself.

This is the version of `nvim` on Linux where `plug.vim` works.

```
NVIM v0.2.0
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -DNDEB
UG -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-pr
otector --param ssp-buffer-size=4 -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/abuild/rpmbuild/BUILD/neovim-0.2.0/build/config -I/home/abuild/rpmbuild/BUILD/n
eovim-0.2.0/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/home/abuild/rpmbuild/BUILD/neovim-0.2.0/buil
```

And this is the version of `nvim` on Windows where it's failing:

```
NVIM v0.2.2
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/msys64/mingw64/bin/gcc.exe -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -D__USE_MINGW_ANSI_STDIO -D_WIN32_WINNT=0x0600 -Wvla -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
```

I'm not sure if this is a bug or a feature of how plugins are installed on Windows. If it's not a bug then I would submit this as a feature request.

This occurs using both `nvim-qt` and `nvim` on Windows 10

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [x] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [x] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim(-qt)

**Comment by janlazo** [comment]
`do` works for me in https://github.com/janlazo/dotvim8/blob/master/autoload/bundle.vim#L68-L77

**Comment by cbcoutinho** [comment]
For me I'm specifically talking about the rust port of `nvim-parinfer.js` - `rust-parinfer`. To compile this plugin you need to execute `cargo` with a path to a sub-directory:

```vim
Plug 'eraserhd/parinfer-rust', {'do':
	\  'cargo build --manifest-path=cparinfer/Cargo.toml --release'}
```

This works on Linux, but not Windows

**Comment by cbcoutinho** [comment]
I'm not sure what the problem was - deleting the plugin directories and re-running `PlugInstall` showed no problems. I'm not sure what the issue was but it seems to be gone.
