### ISSUE TITLE
Fugitive not loaded in new tab

### ISSUE THREAD

**Issue by memeplex** [junegunn/vim-plug#748]
Say I open vim inside a git repo, I get an empty buffer and execute `:Gstatus`, that works just fine.

Now almost the same, but after getting the initial empty buffer I just open a `:newtab `and there I run `:Gs<tab><tab><tab>...` `Gstatus` is not defined. But my `:pwd`  contains a git repo, indeed.

**Comment by nfischer** [comment]
@memeplex does this relate to vim-plug? If so, could you clarify how vim-plug is used?

**Comment by memeplex** [comment]
I didn't even know what vim-plug was until I read your comment, so I guess it doesn't.

**Comment by nfischer** [comment]
@memeplex the [fugitive repo](https://github.com/tpope/vim-fugitive) may be a better place for your question.

**Comment by memeplex** [comment]
You're right, I filed it up here by mistake, maybe I followed a cross link from tpope repo, I don't know, sorry.
