### ISSUE TITLE
:PlugInstall - fatal: could not read Username for 'https://github.com': terminal prompts disabled

### ISSUE THREAD

**Issue by MichaelBaumgarn** [junegunn/vim-plug#756]
**When trying to install directly from github this happens:** 
```
Updated. Elapsed time: 2.857619 sec.
[====x]

- Finishing ... Done!
- fzf: Already installed
x vim-javascrip:
    Cloning into 'C:/Users/Micha/.vim/plugged/vim-javascrip'...
    fatal: HttpRequestException encountered.
    
    fatal: could not read Username for 'https://github.com': terminal prompts disabled


- lightline.vim: Already installed
- nerdtree: Already installed
- fzf.vim: Already installed
```

My relevant vimrc:

```
call plug#begin('\~/.vim/plugged')
Plug 'itchyny/lightline.vim'
Plug 'scrooloose/nerdtree'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'

Plug 'https://github.com/pangloss/vim-javascrip'
```
note that I try to install pangloss/vim-javascrip.
I have seen people with the same problem here, however none of the solutions work. Its not a spelling error as I have copy pasted and double checked everything.

In addition I tried  `Plug 'pangloss/vim-javascrip'`
as well as 
`Plug 'https://github.com/pangloss/vim-javascrip.git'`
and the command is obviously:
`:PlugInstall`

------------------------------

```

```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [x] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
The message usually indicates that there's a typo in the spec; `vim-javascrip` -> `vim-javascript`.

See https://github.com/junegunn/vim-plug/search?q=could+not+read+Username&type=Issues
