### ISSUE TITLE
problem with plugclean

### ISSUE THREAD

**Issue by GiovanniSM20** [junegunn/vim-plug#757]
I've tried to find some issue with a similar problem, but I did not succeed.

So I'm here because every time I run the ```:Plug Clean``` command it complains that the [Wakatime](https://github.com/wakatime/vim-wakatime) directory can be deleted. Anybody can explain why this happens?

```
Searching for invalid plugins in /home/gmartins/.vim/plugged
[===========================================================]                           
                                                                                        
Canceled.                                                                              

/home/$PATH/.vim/plugged/wakatime/ 
```
```
VIM - Vi IMproved 8.1 (2018 May 17, compiled May 25 2018 00:52:08)
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by m42e** [comment]
Did you run `:Plug Clean` or `:PlugClean`?
