### ISSUE TITLE
Docs/README.md issue: "Proper" autoload location unclear

### ISSUE THREAD

**Issue by adam-m-jcbs** [junegunn/vim-plug#758]
The README.md for this project currently states for installing with neovim: 

```sh
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
```

Most sources I've read (including a comment in a vim-plug issue) and example neovim configurations I've seen have the `autoload` directory as `~/.config/nvim/autoload`.  Why does the above have it as `~/.local/share/nvim/site/autoload/`?  Are there any adverse consequences to using the `~/.config/nvim/autoload` convention?  I'm refactoring my configuration and want to use whichever convention is most likely to be widely used over time.  

------------------------------

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [X] Question
- OS:
    - [ ] All/Other
    - [X] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [X] Neovim

**Comment by janlazo** [comment]
README.md is updated for Neovim. See commit message at https://github.com/junegunn/vim-plug/commit/ff97806e50196d56b2858cd56bada9d48cada2aa for details.

**Comment by janlazo** [comment]
Duplicate of https://github.com/junegunn/vim-plug/issues/739
