### ISSUE TITLE
How to disable auto-indent with vim-plug ?

### ISSUE THREAD

**Issue by bearzyj** [junegunn/vim-plug#759]
After I applied vim-plug within "call plug#begin('~/.vim/bundle')" and "call plug#end()", I found my vim become auto-indent again even if I manually ":set nosmartindent" and ":set noautoindent".

If I remove "call plug#begin('~/.vim/bundle')" and "call plug#end()", no indention again.

So, I guess if this caused by vim-plug? And Is there any special command to disable the indention of this kind of ?

Thanks.

------------------------------

```

```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [x] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
See https://github.com/junegunn/vim-plug#usage

**Comment by bobf** [comment]
@junegunn May I ask why this change to default behaviour is part of Vim Plug ?

This issue had me thinking I was losing my mind for a week or two before I found a Reddit post about this which led me to this issue.

Thank you for the great work on Vim Plug ! This is the only minor "complaint" I can find about this software. Easily fixed so no major issues for me.

**Comment by ankitghag** [comment]
i have set autoindent after the indent trun off
call `plug#end()`
indent off, syntax off
set autoindent autowrite noerrorbells
As per my knowledge the autoindent will take indentaion of previous line and i want the same behaviour , but when i use the plugin my autoindentaion does not work properly and  some extra indenation get apply .
