### ISSUE TITLE
ftplugin not loaded

### ISSUE THREAD

**Issue by Eren121** [junegunn/vim-plug#763]
Explain the problem here ...

------------------------------

```

```

- Type:
    - [x] Bug
    - [x] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
Not enough information, and I haven't experienced any problem with ftplugin.
