### ISSUE TITLE
Symlinking a downloaded Plug does not seems to be managed properly. 

### ISSUE THREAD

**Issue by felixgao** [junegunn/vim-plug#764]
In my company all . prefixed directory is automatically synced between multiple hosts. There is a size limit placed for the informations to be put in the . prefixed directory.  I have used the plugin to install YouCompleteMe which is huge.  To solve this I symlinked  the YouCompleteMe plugin into a different directory outside of the . prefixed directory and now when I run vim on a file it complains the YouCompleteMe is unavailable.

------------------------------
mkdir -p ~/DOT.VIM/bundle
mv ~/.vim/plugged/YouCompleteMe ~/DOT.VIM/bundle
ln -s ~/DOT.VIM/bundle/YouCompleteMe ~/.vim/plugged

Now when I tried to edit a file
vi ~/.custom_vimrc
YouCompleteMe unavailable: requires Vim 7.4.1578+.
Press ENTER or type command to continue

**Comment by janlazo** [comment]
Workaround is to treat it as a local plugin by passing an absolute filepath instead of a url to vim-plug and update YouCompleteMe manually outside of ~/.vim/plugged/.
