### ISSUE TITLE
request - change cursor to commit pane to view patch

### ISSUE THREAD

**Issue by cbcoutinho** [junegunn/vim-plug#768]
After running `PlugUpdate` and viewing all changes with `D`, I sometimes inspect the changes that were made to various plugins. Currently, selecting a commit opens a new pane below the tree of commits, but doesn't move the cursor - I think it makes sense to move the cursor to the new pane when selected instead of doing so manually.

------------------------------

```
NVIM v0.3.1-45-g66a39fce6
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [x] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by nfischer** [comment]
Fugitive moves the cursor focus into the new pane (I'm thinking of the `o` mapping in `Gblame` and `Gstatus`). I think this would be a nice feature (or, an optional snippet in the wiki pages).

**Comment by nfischer** [comment]
Actually, are the `o` or `<CR>` mappings documented anywhere? I couldn't find them on the README (would expect it in [this section](https://github.com/junegunn/vim-plug#keybindings)).

**Comment by junegunn** [comment]
Related #749. I would like to find a way to allow remapping of `o` or `<enter>` without introducing a new plug map, though I'm not sure if it's possible, I'll look into it.

> are the o or <CR> mappings documented anywhere?

No, they're not, I probably thought they were too obvious.

**Comment by junegunn** [comment]
See #769
