### ISSUE TITLE
pluginstall not an editor command

### ISSUE THREAD

**Issue by rihannarickeminem** [junegunn/vim-plug#771]
Have done everything as in description
have `call plug#begin('~/.vim/autoload/plug.vim')
`
line 
have the `plug.vim` in autoload
when i execute `call plug#begin('~/.vim/autoload/plug.vim')` in gvim command line
i got error:  _`git` executable not found._

**Comment by rihannarickeminem** [comment]
Fixed- installed git , and change the command line to `call plug#begin('~/.vim/autoload')`

**Comment by junegunn** [comment]
No, you should not install plugins inside autoload directory. Please reread the instruction.
