### ISSUE TITLE
vim-plug doesn't properly handle plugins with the same name from different users (even with different directory specified for each)

### ISSUE THREAD

**Issue by espoelstra** [junegunn/vim-plug#772]
While setting up a new machine with vim-plug (the auto installation of itself is so fantastic to have in my vimrc, I do the same thing for tpm for tmux), I was trying to install a couple new plugins since I'm doing a lot of Chef cookbook editing. I came across https://github.com/vadv/vim-chef for syntax highlighting and https://github.com/dougireton/vim-chef to allow `gf` to jump to `include_recipes` that use the Ruby class/method syntax. When I have both in my vimrc vim-plug only installs one, even if I specify different directories for each. It appears that vim-plug might be separating the repository from the username too early when setting up the paths to clone into and discarding the second (different) repository without even attempting to clone it.

I'm not sure if there is something about the structure of one or the other, since they each recommend different plugin managers (neither referencing vim-plug), but I don't know if that has anything to do with the issue.

I'm having this issue with Vim 7.4 and Vim 8.

- Type:
    - [X] Bug
    - [ ] Enhancement
    - [X] Feature Request
    - [X] Question
- OS:
    - [ ] All/Other
    - [X] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [X] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
You can use `as` option (e.g. `{ 'as': 'vadv-vim-chef' }`) to avoid name collision.

- https://github.com/junegunn/vim-plug#plug-options
