### ISSUE TITLE
Suggest a PlugRenew feature

### ISSUE THREAD

**Issue by leoatchina** [junegunn/vim-plug#776]
```

```

- Type:
    - [ ] Bug
    - [x] Enhancement
    - [x] Feature Request
    - [ ] Question
- OS:
    - [x] All/Other
    - [x] Linux
    - [x] OS X
    - [x] Windows
- Vim:
    - [x] Terminal Vim
    - [x] GVim
    - [x] Neovim

A comand to do  `PlugClean`, `PlugUpgrade`, `PlugInstall`, `PlugUpgrade` together
Downsite is what I added to my .vimrc
```
function! s:PlugRenew()
    :PlugClean
    :PlugUpgrade
    :PlugInstall
    :PlugUpdate
endfunction
command! PlugRenew call s:PlugRenew()

```
But it sometimes casued some errors when newly install some plugins, for example  `fzf`. So this is my little request that if the author can add this feature in officially?

**Comment by junegunn** [comment]
It won't cause errors, I think you're somehow confused. Also, you don't need to call both PlugInstall and PlugUpdate, since the latter installs or updates the plugins.

```vim
" PlugClean*!* for automatic confirmation
" PlugUpdate --sync for synchronous installation; useful when you want to run this in a script
" e.g. vim +PlugRenew +q
command! PlugRenew PlugUpgrade | PlugClean! | PlugUpdate --sync
```
