### ISSUE TITLE
installed vim with brew, encountering error mentioned in FAQ. Solution in faq not clear?

### ISSUE THREAD

**Issue by pyrofolium** [junegunn/vim-plug#78]
This is the error as mentioned in the troubleshooting section after I install vim-plug and run :PlugInstall

Vim:Caught deadly signal SEGV
Vim: Finished.

Segmentation fault:11

While the troubleshooting section tells me why it may be occurring. Being unfamiliar with ruby I'm not not sure how to solve this issue. like the line g:plug_threads = 1? where does that go? in the vimrc?

**Comment by noraesae** [comment]
For guys using `rvm`, the following command fixed my problem.

```
brew uninstall vim; rvm system; brew install vim
```

Cheers
