### ISSUE TITLE
Feature request: use terminal for running command when possible.

### ISSUE THREAD

**Issue by chemzqm** [junegunn/vim-plug#780]
The post install command could take some time to finish, for example when downloading a binary, it would be better to use terminal for external command instead of `:!cmd`

**Comment by junegunn** [comment]
I prefer running them synchronously to clearly see if there were errors. Since you can pass a lambda expression as `do` option, you can customize the way they are run

```vim
function! RunWithTerminal(command)
  " Start the command in a new terminal buffer
endfunction

" Or maybe
function! RunWithTmux(command)
  " ...
endfunction

Plug 'foo/bar', { 'do': {-> RunWithTerminal('foo')} }
```

**Comment by chemzqm** [comment]
>  to clearly see if there were errors.

What does that mean? Does using terminal make trouble for user to see the errors?
The `:!cmd` has trouble with colored output from terminal command, which prevent the user get the errors.
I know I can use vim script for this purpose, but how could I tell the user to write vimscript like that.
I think that vim-plug could provide an option for running post install command in terminal, no need to change current behavior.

**Comment by junegunn** [comment]
Terminal buffers are inherently asynchronous, and the commands will run after `PlugUpdate` is complete. The users then have to keep their eyes on the buffer to see if it finishes without an error. I agree that the current error reporting is poor, but at least vim-plug can tell you whether if the task has failed or not by looking at the exit status.

Fundamentally, I don't really see the point of making a subset of the installation process asynchronous, when you can't properly use the plugin until the asynchronous task completes. Don't want to expose incomplete installation to the users.

> how could I tell the user to write vimscript like that

If you really want, your plugin can provide the implementation, and instruct users to use it.

```vim
Plug 'foo', { 'do': { -> foo#setup() } }
```
