### ISSUE TITLE
More clear documentation about lazy loading filetype plugins

### ISSUE THREAD

**Issue by lervag** [junegunn/vim-plug#785]
Hi. I've had multiple issues at vimtex due to people using the "for" specifier when loading filetype plugins, see e.g.:

- https://github.com/lervag/vimtex/issues/1213
- https://github.com/lervag/vimtex/issues/885

I think it should be documented in the README.md file that one should in general not use the "for" specifier for properly written filetype plugins, as they are already lazily loaded through Vim's ftplugin system.

- Type:
    - [ ] Bug
    - [x] Enhancement
    - [x] Feature Request
    - [x] Question
- OS:
    - [x] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [x] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
Yeah, I agree, I may add a link to the following wiki page on the README page:

https://github.com/junegunn/vim-plug/wiki/faq#when-should-i-use-on-or-for-option

Interestingly, vimtex does not have `plugin` directory, so there's no point of `for` at all. We can maybe make vim-plug ignore `for` option (except the blank ones) in such cases.

**Comment by junegunn** [comment]
```diff
diff --git a/plug.vim b/plug.vim
index 686dd47..282e642 100644
--- a/plug.vim
+++ b/plug.vim
@@ -193,6 +193,11 @@ function! s:ask_no_interrupt(...)
   endtry
 endfunction
 
+function! s:has_for(plug)
+  return has_key(a:plug, 'for') &&
+        \ (empty(s:to_a(a:plug.for)) || len(s:glob(s:rtp(a:plug), 'plugin')))
+endfunction
+
 function! plug#end()
   if !exists('g:plugs')
     return s:err('Call plug#begin() first')
@@ -214,7 +219,7 @@ function! plug#end()
       continue
     endif
     let plug = g:plugs[name]
-    if get(s:loaded, name, 0) || !has_key(plug, 'on') && !has_key(plug, 'for')
+    if get(s:loaded, name, 0) || !has_key(plug, 'on') && !s:has_for(plug)
       let s:loaded[name] = 1
       continue
     endif
```

**Comment by junegunn** [comment]
Also note that it is already mentioned that *"for option is generally not needed"*, but people don't necessarily read it.

https://github.com/junegunn/vim-plug#on-demand-loading-of-plugins

**Comment by lervag** [comment]
Thanks!

I think it may be close to impossible to make things bullet proof for inexperienced Vim users. I do think that it could be wise to add the link to the [wiki page](https://github.com/junegunn/vim-plug/wiki/faq#when-should-i-use-on-or-for-option) in the [README](
https://github.com/junegunn/vim-plug#on-demand-loading-of-plugins) file, although I expect people will still fail to read it.

**Comment by junegunn** [comment]
With #786 merged, `on` or `for` option for vimtex will be ignored.

**Comment by DenLilleMand** [comment]
When you use lazy loading with `for` for a plugin like `tpope/fugitive` or some other plugin. 

You realize that the plugin doesn't work anymore, and remove the `for`. Calling `source` etc. Maybe even installing the plugins from scratch again.

But it still doesn't work ... 

How do you generally deal with a situation like that? does vim-plug make permanent changes to the plugins or the way it loads them that goes beyond something that changes at `source` time?

**Comment by junegunn** [comment]
`for` option is an unreliable hack that is not guaranteed to work with any plugin. You might be able to make it work by reading the source code of the plugin and manually set up extra initialization steps, but the effort will be in vain once the implementation changes in the future. I don't think it's worth it.

https://github.com/junegunn/vim-plug/wiki/faq#when-should-i-use-on-or-for-option

**Comment by DenLilleMand** [comment]
yeah i know, sorry for not making my question clear. I realize that part you're saying - because i read the nice documentation part about it.
Problem is that i tried to use the `for` value before i read about it, and now the plugins where it didn't work just doesn't load at all. Even after removing the `for` and after reinstalling the plugins from scratch.
