### ISSUE TITLE
after/ftplugin and lazy loading

### ISSUE THREAD

**Issue by mwgkgk** [junegunn/vim-plug#787]
#786 broke after/ftplugin lazy loading. To fix, just need to add one more line:
```
function! s:lazy(plug, opt)
  return has_key(a:plug, a:opt) &&
        \ (empty(s:to_a(a:plug[a:opt]))         ||
        \  !isdirectory(a:plug.dir)             ||
        \  len(s:glob(s:rtp(a:plug), 'plugin')) ||
        \  len(s:glob(s:rtp(a:plug), 'after/ftplugin')) ||
        \  len(s:glob(s:rtp(a:plug), 'after/plugin')))
endfunction
```

**Comment by junegunn** [comment]
`ftplugin` and `after/ftplugin` are not loaded until a file of the type is open. An extra layer of lazy loading is meaningless.

**Comment by junegunn** [comment]
Which plugin are you referring to?

**Comment by mwgkgk** [comment]
I just have some lines like above extracted into `after/ftplugin/markdown/TabPaste.vim` to have some custom markdown editing stuff. It is not a published plugin. Do you maybe have a suggestion on how to handle it some other way?

**Comment by junegunn** [comment]
I can't comment without seeing the code and the structure. All I can say that you shouldn't have any issue if the code is properly structured. ftplugin should be loaded on open. 

I suggest that you read through http://learnvimscriptthehardway.stevelosh.com/
