### ISSUE TITLE
Consider releasing a new version?

### ISSUE THREAD

**Issue by SilverRainZ** [junegunn/vim-plug#790]
Hello, vim-plug developers, the latest version 0.9.1 is released 2 years ago, and it can not works well with current neovim, do you consider releasing a new version?

------------------------------

```
n/a
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [x] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
Okay, I just pushed a new tag.
