### ISSUE TITLE
Automatic installation error

### ISSUE THREAD

**Issue by remydev** [junegunn/vim-plug#792]
Hello,

I get the following error when i add this script in my /etc/vim/vimrc

```
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
```
From https://github.com/junegunn/vim-plug/wiki/tips#automatic-installation

Error detected while processing VimEnter Autocommands for "*":
E492: Not an editor command: PlugInstall --sync | source $MYVIMRC

- OS:
    - [ x ] Linux : alpinelinux with zsh and linuxmint with zsh
- Vim:
    - [ x] Terminal Vim

Where is the mistake please ?

**Comment by joshuaks** [comment]
Hey @remydev, how did you solve this?

**Comment by remydev** [comment]
Yes, but i don't know how, or why.
Thanks

**Comment by markusarro** [comment]
Hi,

Recently came across the same error. It occurs if there is no .vim directory and only on the first time starting vim. When opening vim for the second time, no error is shown. Also, if the [sensible](https://github.com/junegunn/vim-plug#example-a-small-sensible-vim-configuration) plugin is configured to install (or any plugin probably), then no error is shown and plugin installation screen appears as is expected.


To reproduce on a fresh Ubuntu install:

1. Install packages: vim, git, curl
2. Create a minimal .vimrc file as described in the automatic installation. Don't include anything other than this:
```
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
```

3. open vim
vim

  
  
Version info:
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 07 2019 11:42:36)
Included patches: 1-320
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl               -clipboard         -dnd               +gettext           +localmap          +mouse_urxvt       +profile           +syntax            +user_commands     -xfontset
+arabic            +cmdline_compl     -ebcdic            -hangul_input      -lua               +mouse_xterm       -python            +tag_binary        +vartabs           -xim
+autocmd           +cmdline_hist      +emacs_tags        +iconv             +menu              +multi_byte        +python3           +tag_old_static    +vertsplit         -xpm
+autochdir         +cmdline_info      +eval              +insert_expand     +mksession         +multi_lang        +quickfix          -tag_any_white     +virtualedit       -xsmp
-autoservername    +comments          +ex_extra          +job               +modify_fname      -mzscheme          +reltime           -tcl               +visual            -xterm_clipboard
-balloon_eval      +conceal           +extra_search      +jumplist          +mouse             +netbeans_intg     +rightleft         +termguicolors     +visualextra       -xterm_save
+balloon_eval_term +cryptv            +farsi             +keymap            -mouseshape        +num64             -ruby              +terminal          +viminfo
-browse            +cscope            +file_in_path      +lambda            +mouse_dec         +packages          +scrollbind        +terminfo          +vreplace
++builtin_terms    +cursorbind        +find_in_path      +langmap           +mouse_gpm         +path_extra        +signs             +termresponse      +wildignore
+byte_offset       +cursorshape       +float             +libcall           -mouse_jsbterm     -perl              +smartindent       +textobjects       +wildmenu
+channel           +dialog_con        +folding           +linebreak         +mouse_netterm     +persistent_undo   +startuptime       +timers            +windows
+cindent           +diff              -footer            +lispindent        +mouse_sgr         +postscript        +statusline        +title             +writebackup
-clientserver      +digraphs          +fork()            +listcmds          -mouse_sysmouse    +printer           -sun_workshop      -toolbar           -X11
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-cqxBjj/vim-8.1.0320=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_F
ORTIFY_SOURCE=1
Linking: gcc   -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl     -L/usr/lib/python3.7/config-3.7m-x86_64-linux-gnu
-lpython3.7m -lcrypt -lpthread -ldl -lutil -lm
```


- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by linearstream** [comment]
To anyone else that runs into this same issue (like I did) [at least for Ubuntu 18.04 using vim 8.1]...

This was reproducible for me by doing rm ~/.vim/autoload/plug.vim after closing vim.

You will get this error **until** you also add the following line in your .vimrc below the recommended
autoload code (from https://github.com/junegunn/vim-plug/wiki/tips#automatic-installation)
`call plug#begin('~/.vim/plugged')`

So my example looked like:
`" Install vim-plug if not already installed:
"   https://github.com/junegunn/vim-plug/wiki/tips#automatic-installation
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
" NOTE: Line not given in http link above but required or you will get an error on load
call plug#begin('~/.vim/plugged')`

My guess is that @remydev figured this out but did not post the same.

In defense of the vim-plug developers, they probably don't include this line in the autoload
instructions because they are allowing users to define their own directory for plugs. But at the
same time, it would be nice if it were mentioned that it is required to avoid the error so users
like us do not get stuck digging.

I will try to add a NOTE and do a pull request.
