### ISSUE TITLE
Want to prepend "sudo"  

### ISSUE THREAD

**Issue by ericvinod** [junegunn/vim-plug#799]
Explain the problem here ...

By Design on my box i need to pre-pend "sudo" to install and access GIT
What would be the correct way of doing it?

```

```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ .] Question
- OS:
    - [ .] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ .] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by urbainvaes** [comment]
Can you perhaps `alias vim=sudoedit`?
