### ISSUE TITLE
auto source $MYVIMRC?

### ISSUE THREAD

**Issue by zhuangya** [junegunn/vim-plug#8]
i saw this line in the doc:

> If you put Plug 'junegunn/dummy1' in your configuration file, and run :PlugInstall,

but i don't think my vim auto re-source $MYVIMRC anyway..

would it be a good idea to add the "auto re-source $MYVIMRC" functionality in the plugin?

thanks!

**Comment by mayuroks** [comment]
+1 ... quick suggestion: instead user having to reload vimrc ... let PlugInstall reload vimrc before installing the plugins. So basically when user edits his vimrc and fires PlugInstall, this is what PlugInstall should do
```bash
1. reload vimrc
2. install plugins
```

I am no expert on Vim, but hope this is feasible.

**Comment by vheon** [comment]
I usually just do `:source $MYVIMRC | PlugInstall`

**Comment by mayuroks** [comment]
This is my user exp regarding PlugInstall: 

First I ignored that vimrc needs to be reloaded in README, spent 5 minutes wondering why PlugInstall wont work. Then looking at README again, I realized vimrc needs to be reloaded. Funny thing! I didn't know how vimrc is reloaded. I googled and found ```:source $MYVIMRC```. 

But still as a user/developer who loves simplicity I wouldn't prefer such a syntax every time I install plugins. @vheon ... thanks btw

**Comment by junegunn** [comment]
@mayuroks Automatic reloading of vimrc can have unwanted side-effects. For example, user's vimrc may contain free autocmds that are not properly cleared beforehand, such as:

```vim
" Good
augroup vimrc
  autocmd!
  autocmd FileType * echom 1234  
augroup END

" Bad. But it's really common in reality
autocmd FileType * echom 5678
```

In this case, reloading vimrc will have the second autocommand defined multiple times. It's messy, so vim-plug probably shouldn't do that by default.

Instead, as the user's perspective, I would suggest checking out tips on auto-reloading vimrc on save.
http://vim.wikia.com/wiki/Change_vimrc_with_auto_reload
