### ISSUE TITLE
Won't recognize local plugin

### ISSUE THREAD

**Issue by fredaas** [junegunn/vim-plug#801]
I'm trying to make vim-plug recognize a local plugin.

Directory structure:
```
~/.vim/plugged/local-plugin/autoload/local_plugin.vim
```
The plugin is loaded from .vimrc as explained in the README.md at the root of this (junegunn/vim-plug) directory:
```
call plug#begin('~/.vim/plugged')
Plug '~/.vim/plugged/local-plugin'
call plug#end()
```
Content of local_plugin.vim:
```
if exists("g:loaded_hello_world")
  finish
endif
let g:loaded_hello_world=1 

fun! SayHello()
    echom "Hello world!"
endfun

echom "Loaded!"

command! SayHello call SayHello()
```
This does not work.

Any tips on how to resolve the issue would be much appreciated.

Perhaps some more information on how local plugins interface with vim-plug and how to load them should be included in the wiki to reduce friction on the user side?

**Comment by junegunn** [comment]
It's not an issue of vim-plug. Your code is not loaded because it's in autoload directory. You might want to read through Learn Vimscript the Hard Way by Steve Losh, especially this chapter: http://learnvimscriptthehardway.stevelosh.com/chapters/53.html
