### ISSUE TITLE
Output updating log into stdout

### ISSUE THREAD

**Issue by szsdk** [junegunn/vim-plug#809]
I am going to schedule updating plug as a routine with `crontab`. 
Now I am using
```bash
nvim +'PlugUpdate --sync' +qa
```
which basically saves a screenshot of the vim window.

Is there anyway to print those updating information into a normal stdout?

------------------------------

```

```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [X] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [X] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [X] Neovim

**Comment by junegunn** [comment]
No, but you can write the content of the buffer to a file before quitting.

```sh
nvim +'PlugUpdate --sync' +'%w /tmp/vim-plug.log' +qa
```
