### ISSUE TITLE
E117 Uknown function plug#begin

### ISSUE THREAD

**Issue by MarcMdev** [junegunn/vim-plug#812]
Hello. I tried installing Vim-Plug following the github repository guide

https://github.com/junegunn/vim-plug

I ran

`curl -fLo ~/.vim/autoload/plug.vim --create-dirs \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim`

on the terminal.

`~/.vim/autoload/plug.vim` was created.

I also created `~/vim/plugged`

Added

```
call plug#begin('~/.vim/plugged')

call plug#end()
```

to `~/.vimrc` file.

now when I run Vim on vim I get this error:

```
Error detected while processing /home/marcelo/.vimrc:
line   90: E117: Unknown function: plug#begin 
line  93: E117: Unknown function: plug#end Press ENTER or type command to continue
I've been through stackoverflow for over an hour and could'nt find anything helpful
```

if anyone has been through this before and solved it please help me out

------------------------------

```

```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by dabrahim** [comment]
Hello. I have the exact same issue. Could you solve the problem ?

**Comment by sd1l** [comment]
*bump* suspecting that perhaps something has changed in Vim 8+ where the instructions for writing plugins might have a slight change...?

Possibly due to new implementation of native package management? Not experienced enough to say for certain..but the same issue has occured with pathogen and vim plug and my dirs are all good, so?

Help would be much appreciated!

**Comment by Latube** [comment]
I have soled this problem in my win10 machine. My way is setthe file **plug.vim** in the **~\.vim\autoload** directory

**Comment by m42e** [comment]
Execute the following command from within vim and check if the plug.vim is listed:
```
:scriptnames
```

**Comment by sphericalwave** [comment]
I'm working on the same error.
Here's what i see when i run 
`:scriptnames`

 ```
 1: /etc/vimrc
  2: /usr/share/vim/vim74/syntax/syntax.vim
  3: /usr/share/vim/vim74/syntax/synload.vim
  4: /usr/share/vim/vim74/syntax/syncolor.vim
  5: /usr/share/vim/vim74/filetype.vim
  6: /usr/share/vim/vim74/ftplugin.vim
  7: ~/.vim/vimrc
  8: ~/.vim/autoload/plug.vim
  9: /usr/share/vim/vim74/ftoff.vim
 10: /usr/share/vim/vim74/indent.vim
 11: /usr/share/vim/vim74/plugin/getscriptPlugin.vim
 12: /usr/share/vim/vim74/plugin/gzip.vim
 13: /usr/share/vim/vim74/plugin/matchparen.vim
 14: /usr/share/vim/vim74/plugin/netrwPlugin.vim
 15: /usr/share/vim/vim74/plugin/rrhelper.vim
 16: /usr/share/vim/vim74/plugin/spellfile.vim
 17: /usr/share/vim/vim74/plugin/tarPlugin.vim
 18: /usr/share/vim/vim74/plugin/tohtml.vim
 19: /usr/share/vim/vim74/plugin/vimballPlugin.vim
 20: /usr/share/vim/vim74/plugin/zipPlugin.vim
 21: /usr/share/vim/vim74/scripts.vim
 22: /usr/share/vim/vim74/syntax/vim.vim
 23: /usr/share/vim/vim74/syntax/perl.vim
 24: /usr/share/vim/vim74/syntax/pod.vim
 25: /usr/share/vim/vim74/syntax/python.vim
 26: /usr/share/vim/vim74/ftplugin/vim.vim
 27: /usr/share/vim/vim74/indent/vim.vim

```

This looks right
`~/.vim/autoload/plug.vim`

**Comment by bekicot** [comment]
I also encounter this problem. I followed the debugging method as mentioned in #245, and it all seems okay.

I did the installation by specifying my own rtp dir. Because I use vimr and vimr is using neovim.

```
curl -fLo ~/.config/nvim/plug.vim --create-dirs \
https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
```
And in the `init.vim` i added `set rtp +=~/.config/nvim` 1 line before before the `call plug#begin ...`

And it didn't work. I did `:echo &rtp` and it showed the dir I added.

I made it works by moving `~/.config/nvim/plug.vim` to `~/.config/nvim/autoload/plug.vim` after learning how Vundle managed to work on my vimr.

So, in your case, if after you run `:echo &rtp` and it doesn't show `~/.vim`,  maybe you should add
```
set rtp +=~/.vim
```
before `call plug#begin...`

I have no idea why it works on my machine, let me know if anyone knows why I have to put it on `~/.config/nvim/autoload`

**Comment by OpenWaygate** [comment]
I have this problem in my raspberry pi. 
At first I do not have the file `~/.vimrc`, so I add the following lines 
```
call plug#begin('~/.vim/plugged')
Plug 'foo'
call plug#end()
```
to `/etc/vim/vimrc`, it work well with command `vi file_name` but when it comes to `sudo vi file_name`, the error message appears
```
Error detected while processing /usr/share/vim/vimrc:
line 13: E117: Unknown function: plug#begin
line 15: E492: Not an editor command: Plug 'joshdick/onedark.vim'
line 16: E492: Not an editor command: Plug 'sheerun/vim-polyglot'
line 18: E117: Unknown function: plug#end
Press ENTER or type command to continue
```

So I delete these lines just added, `cp /etc/vim/vimrc ~/.vimrc` and add these lines to ~/.vimrc, then it work as I expect.

**Comment by gminova** [comment]
Similar issue on ubuntu 16.04 while trying to use vim-plug and fugitive :cry: 

here is my .vimrc.plug
```bash
call plug#begin('~/.vim/plugged')

"Fugitive Vim Github Wrapper
Plug 'tpope/vim-fugitive'

call plug#end()
```
And here is the error when trying to open vim:
```bash
Error detected while processing /etc/vim/vimplug-plugins/.vimrc.plug:
line    1:
E117: Unknown function: plug#begin
line    4:
E492: Not an editor command: Plug 'tpope/vim-fugitive'
line    6:
E117: Unknown function: plug#end
Press ENTER or type command to continue
```

**Comment by peter279k** [comment]
I also suffer this issue because of the permission on ` $HOME/.vim/autoload/` folder.

When I set the current user with `chown -R $USER:$USER $HOME/.vim/autoload/`, it works fine with `vim` command :).

**Comment by Shmorgel** [comment]
Hello,

nothing here solves the problem for me. So: bump

**Comment by akai54** [comment]
Hello i had the same issue but i just found the solution all you have to do is,
go to ### ~/.config/nvim 
then execute this command 
### **_sudo chmod +rwx autoload/_**
then Enjoy.

**Comment by Dr4kk0nnys** [comment]
> This is what worked for me, in the directory ~/.vim/autoload , I moved the plug.vim there since it wasn't already there. After I added this, it still didn't work. So I used @akai54 's solution but I did the **sudo chmod +rwx autoload** in the ~/.vim directory instead and after that, everything worked fine. If there isn't an autoload folder already in the .vim directory, create one.
> 
> **cd ~/.vim/**
> **mkdir autoload**
> Move the plug.vim from the ~/.config/nvim to ~/.vim/autoload or:
> **sudo mv ~/.config/nvim/plug.vim ~/.vim/autoload**
> **sudo chmod +rwx autoload/**

It worked!!! ( i'm using kubuntu 20.04 )

**Comment by IronToBind** [comment]
> This is what worked for me, in the directory ~/.vim/autoload , I moved the plug.vim there since it wasn't already there. After I added this, it still didn't work. So I used @akai54 's solution but I did the **sudo chmod +rwx autoload** in the ~/.vim directory instead and after that, everything worked fine. If there isn't an autoload folder already in the .vim directory, create one.
> 
> **cd ~/.vim/**
> **mkdir autoload**
> Move the plug.vim from the ~/.config/nvim to ~/.vim/autoload or:
> **sudo mv ~/.config/nvim/plug.vim ~/.vim/autoload**
> **sudo chmod +rwx autoload/**

I was having the same issue but I didn't like having an extra file in ~ because I only use nvim. Anyway ~/.config/nivm/autoload/ is a fine place to put it, the curl command on github puts it in ~/.config/nivm/site/autoload which did not work

**Comment by elin-croft** [comment]
> This is what worked for me, in the directory ~/.vim/autoload , I moved the plug.vim there since it wasn't already there. After I added this, it still didn't work. So I used @akai54 's solution but I did the **sudo chmod +rwx autoload** in the ~/.vim directory instead and after that, everything worked fine. If there isn't an autoload folder already in the .vim directory, create one.
> 
> **cd ~/.vim/**
> **mkdir autoload**
> Move the plug.vim from the ~/.config/nvim to ~/.vim/autoload or:
> **sudo mv ~/.config/nvim/plug.vim ~/.vim/autoload**
> **sudo chmod +rwx autoload/**

thx bro, it worked. The reason why I got this problem is that I cloned all master branch in autoload instead of downloading plug.vim into autoload XD

**Comment by jonasreyes** [comment]
Hola, mi problema era al revés, tenia VIM funcionando con mis plugins pero NVIM no me cargaba los plugin y me daba el mismo error que inició éste hilo, lo solucioné generando un enlace simbólico de la carpeta ~/.vim/autoload a la carpeta **~/.config/nvim/:
$ cd .config/nvim/
$ ln -s ~/.vim/autoload/ .**
fix resuelto

**Comment by BeenLi** [comment]
> I also suffer this issue because of the permission on ` $HOME/.vim/autoload/` folder.
> 
> When I set the current user with `chown -R $USER:$USER $HOME/.vim/autoload/`, it works fine with `vim` command :).

it did works.

**Comment by nacht** [comment]
Might help someone else. You might be running vi instead of vim.

apt install vim on ubuntu 20.04 did it for me.

**Comment by Nickhil1737** [comment]
changing permission on .vim file worked for me
from root user run:
```
chmod -R 0755 ~/.vim
```

**Comment by andres02-art** [comment]
hola.
yo tenia el mismo problema con la ejecución de plugins y @m42e junto con @sphericalwave me dieron la solución así que gracias, aquí lo que hice:

1.al ejecutar ': scriptnames' no se encontraba plug.vim por lo que:
trabajo en Windows y uso Gvim,  por tal motivo se me dificulto la instalación de plugins, para solucionarlo, extraje el archivo plug.vim de junegunn/vim-plug y lo puse no en la carpeta local si no en la que se sitúa Gvim.

2.Luego en el archivo de configuración "_vimrc" añadí 'source $VIMRUNTIME/plug.vim' antes de 'source $VIMRUNTIME/example_vimrc' y al ejecutar 'call plug#begin' dejo de darme el error de "Unknown function: plug#begin".

Supongo que en las distribuciones de linux y mac tendrá la misma solución de importar dicho archivo con "source", o lo realizara de forma automática, pero despues de importarlo y ejecutar ":scriptnames" el archivo aparece listado.

**Comment by Ahmedk-n** [comment]
> Execute the following command from within vim and check if the plug.vim is listed:
> 
> ```
> :scriptnames
> ```
I have the same problem and when i tried to use :scriptname , ~/vimfiles/plug.vim wasn't listed, could you help me pls!
.... 
 ```
1: /etc/vimrc
  2: /usr/share/vim/vim82/defaults.vim
  3: /usr/share/vim/vim82/filetype.vim
  4: /usr/share/vim/vim82/ftplugin.vim
  5: /usr/share/vim/vim82/indent.vim
  6: /usr/share/vim/vim82/syntax/syntax.vim
  7: /usr/share/vim/vim82/syntax/synload.vim
  8: /usr/share/vim/vim82/syntax/syncolor.vim
  9: ~/.vimrc
 10: /usr/share/vim/vim82/syntax/nosyntax.vim
 11: /usr/share/vim/vim82/plugin/getscriptPlugin.vim
 12: /usr/share/vim/vim82/plugin/gzip.vim
 13: /usr/share/vim/vim82/plugin/logiPat.vim
 14: /usr/share/vim/vim82/plugin/manpager.vim
 15: /usr/share/vim/vim82/plugin/matchparen.vim
 16: /usr/share/vim/vim82/plugin/netrwPlugin.vim
 17: /usr/share/vim/vim82/plugin/rrhelper.vim
 18: /usr/share/vim/vim82/plugin/spellfile.vim
 19: /usr/share/vim/vim82/plugin/tarPlugin.vim
 20: /usr/share/vim/vim82/plugin/tohtml.vim
 21: /usr/share/vim/vim82/plugin/vimballPlugin.vim
 22: /usr/share/vim/vim82/plugin/zipPlugin.vim
 23: /usr/share/vim/vim82/scripts.vim
 24: /usr/share/vim/vim82/ftplugin/vim.vim
 25: /usr/share/vim/vim82/indent/vim.vim
 26: /usr/share/vim/vim82/syntax/vim.vim
 27: /usr/share/vim/vim82/syntax/perl.vim
 28: /usr/share/vim/vim82/syntax/pod.vim
```

...

**Comment by arsan-official** [comment]
I have solve this issue on windows 10 machine. 
First make sure the location of your .vmrc file. 

1. open vim 
2. run command :version 
![vimrc](https://user-images.githubusercontent.com/28953607/155076285-81371935-8437-4ae2-acf0-6538f1205f5f.PNG)

3. From command above we know that location of vimrc is at: $HOME/.vimrc  . 
4. Aware of location of vimfiles, for me it is located at $HOME/vimfiles/

![vimfiles](https://user-images.githubusercontent.com/28953607/155077099-d4443ed6-76d1-4683-ab10-8e3605c2b072.PNG)
5. Please note the location of plugin folder, it is at $HOME/vimfiles/plugin/ 
6. Edit our .vimrc at $HOME/.vimrc 
![vimrc_config](https://user-images.githubusercontent.com/28953607/155077353-21adec6d-6815-4f79-aa42-06d4d00055e5.PNG)
7. Save. Quit. 
8. Open vim, try to command PlugInstall
![vim_plug_install](https://user-images.githubusercontent.com/28953607/155077544-575052da-4c74-48d6-b9fe-33f14d2cb54a.PNG)

Maybe there is someone that need this help. Thanks

**Comment by alexya** [comment]
@jonasreyes Using your solution works, thank you very much.

**Comment by pisomanik** [comment]
Okay, So apparently I had both `vim` and `nvim` installed.

I moved my `plug.vim` into `~/.config/nvim/autoload` and gave it the required permissions. And that worked :+1:

**Comment by lidaling** [comment]
cp plug.vim to /usr/share/nvim/autoload 
It works

**Comment by tvendelin** [comment]
Adding my two cents: I forgot to install curl on a fresh Debian VM, and was wondering why my time-tested `.vimrc` didn't work, :rofl: The error message was there, `curl: command not found`

**Comment by w1g0** [comment]
The ``plug.vim`` file needs to be in the autoload folder you specify in your ``init.vim`` file for neovim.
On Windows it downloads in 'c/Users/**YourUserName**/vimfiles/autoload' and I had it specified to 'c/Users/**YourUserName**/Appdata/Local/nvim/autoload' and it returned => Not an editor command: PlugInstall, preceeded with the error message: unknown function plug#begin. It might help you, success!

**Comment by lanxuexing** [comment]
You need to install vim-plug, you can find instructions on how to do that here:
https://github.com/junegunn/vim-plug#installation

Unix
```
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
```

**Comment by dudvdw** [comment]
In my case(based on Debian OS), when I put the plug.vim file in /usr/share/vim/vim90/autoload directory, it works.

**Comment by ncgl-git** [comment]
For windows (non wsl) - my vim sourcing from `/usr/share/vim/vim82/...`, but the install script for vim-plug writes to `HOME/vimfiles/autoload/`.

I had to:
1. ensure I was root / admin
2. copy the installed-via-script-HOME/vimfiles/autoload/plug.vim file into `/usr/share/vim/vim82/autoload/plug.vim`

**Comment by 0mbudsm4n** [comment]
> In my case(based on Debian OS), when I put the plug.vim file in /usr/share/vim/vim90/autoload directory, it works.

This also works for me !

**Comment by JLUVicent** [comment]
> I have this problem in my raspberry pi. At first I do not have the file `~/.vimrc`, so I add the following lines
> 
> ```
> call plug#begin('~/.vim/plugged')
> Plug 'foo'
> call plug#end()
> ```
> 
> to `/etc/vim/vimrc`, it work well with command `vi file_name` but when it comes to `sudo vi file_name`, the error message appears
> 
> ```
> Error detected while processing /usr/share/vim/vimrc:
> line 13: E117: Unknown function: plug#begin
> line 15: E492: Not an editor command: Plug 'joshdick/onedark.vim'
> line 16: E492: Not an editor command: Plug 'sheerun/vim-polyglot'
> line 18: E117: Unknown function: plug#end
> Press ENTER or type command to continue
> ```
> 
> So I delete these lines just added, `cp /etc/vim/vimrc ~/.vimrc` and add these lines to ~/.vimrc, then it work as I expect.

i have the same question with you , and i resolve it by your method ,thank you!!!

**Comment by tess-hartis** [comment]
> I have soled this problem in my win10 machine. My way is setthe file `plug.vim` in the directory`~\.vim\autoload\`

why does this work??
