### ISSUE TITLE
Don’t require relaunching to :PlugInstall

### ISSUE THREAD

**Issue by mcandre** [junegunn/vim-plug#817]
Would it be possible to remove the requirement to relaunch Vim in order to :PlugInstall new plugin entries?

**Comment by jcrd** [comment]
It's not necessary to restart vim. Use `:so $MYVIMRC` to re-source your rc file after changing plugin entries. `:PlugInstall` will then install new plugins.

**Comment by mcandre** [comment]
Hmm, could `:PlugInstall` automatically `:source` my vimrc configuration for us?

**Comment by junegunn** [comment]
Consider doing something like:
```vim
command! MyPlugInstall source $MYVIMRC | PlugInstall
```
