### ISSUE TITLE
PlugInstall oddity in cygwin

### ISSUE THREAD

**Issue by mcandre** [junegunn/vim-plug#818]
When using `:PlugInstall` in a Cygwin environment, Vim disappears.

**Comment by janlazo** [comment]
This should be fixed with the latest commit on master.

**Comment by janlazo** [comment]
Can't replicate the error. Need a vimrc to test. Ran git-bash to launch mintty and run cygwin/msys2 vim.  Ran `PlugInstall` on my vimrc. No issues.
