### ISSUE TITLE
vim-plug breaks auto paste script

### ISSUE THREAD

**Issue by vitmy0000** [junegunn/vim-plug#819]
Looks like vim-plug will break the auto-paste script (https://coderwall.com/p/if9mda/automatically-set-paste-mode-in-vim-when-pasting-in-insert-mode)

I use vim with tmux, so I use the following script in my vimrc and it's pretty handy.
```
function! WrapForTmux(s)
  if !exists('$TMUX')
    return a:s
  endif

  let tmux_start = "\<Esc>Ptmux;"
  let tmux_end = "\<Esc>\\"

  return tmux_start . substitute(a:s, "\<Esc>", "\<Esc>\<Esc>", 'g') . tmux_end
endfunction

let &t_SI .= WrapForTmux("\<Esc>[?2004h")
let &t_EI .= WrapForTmux("\<Esc>[?2004l")

function! XTermPasteBegin()
  set pastetoggle=<Esc>[201~
  set paste
  return ""
endfunction

inoremap <special> <expr> <Esc>[200~ XTermPasteBegin()
```
If my vimrc has only this, the auto-paste works.
But after I add only 
```
call plug#begin('~/.vim/plugged')
call plug#end()
```
auto-paste stops working.

Not exactly sure what's the reason. But I guess it's a vim-plug related issue.
Can someone help on this?

------------------------------

```

```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [X] Question
- OS:
    - [ ] All/Other
    - [X] Linux
    - [X] OS X
    - [ ] Windows
- Vim:
    - [X] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by LukeAI** [comment]
@vitmy0000  I have this problem - did you solve it?
