### ISSUE TITLE
Global gtags.vim with vim-plug?

### ISSUE THREAD

**Issue by ghost** [junegunn/vim-plug#820]
How can I get the local gtags.vim from Global distribution to load with vimplug?
The gtags.vim on vim-scripts seems to be deprecated and according to recommendation I should use the one under the Global installation directory instead.
I've tried a couple of things, manually copying it into .vim/plugged, adding the location with set rtp, but it doesn't seem to load.
Can I point vim-plug to the global installation directory somehow?
Perhaps it isn't an issue with vim-plug at all...

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [X ] Question
- OS:
    - [ ] All/Other
    - [X ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [X ] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by ZhenhanGong** [comment]
According to the doc of [GNU GLOBAL Source Code Tag System](https://www.gnu.org/software/global/globaldoc_toc.html#Vim-editor):

I install gtags like following:
```
cp /usr/local/share/gtags/gtags.vim ~/.vim/`
source ~/.vim/gtags.vim
```

**Comment by junegunn** [comment]
You should copy the file into `~/.vim/plugin` directory. Then no &rtp manipulation is needed.
