### ISSUE TITLE
Can't open vim-plug's help

### ISSUE THREAD

**Issue by tterranigma** [junegunn/vim-plug#829]
Explain the problem here ...

------------------------------

```
:version                                                                                                                                                                                                    
NVIM v0.4.0-370-gc0a29c365
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissi
ng-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM
-I/tmp/yaourt-tmp-nikos/aur-neovim-git/src/neovim-git/build/config -I/tmp/yaourt-tmp-nikos/aur-neovim-git/src/neovim-git/src -I/usr/include -I/tmp/yaourt-tmp-nikos/aur-neovim-git/src/neovim-git/build/src/nvim/au
to -I/tmp/yaourt-tmp-nikos/aur-neovim-git/src/neovim-git/build/include
Compiled by nikos@nikos-laptop

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

I see in this repo that vim-plug has a help file named `plug.txt`. In nvim, I do `:h plug.txt` and get an error that there is no help for plug.txt. Can I access it somehow?

**Comment by Shaedil** [comment]
Hi tterranigma,

If you're still having problems, it may be of 2 reasons:

1. You may need to rebuild the help tags file
2. The command is `:h plug`

In nvim, type: `:helptags runtime/doc` (or the equivalent directory structure)
Restart nvim and try `:h plug`

**Comment by junegunn** [comment]
[The installation instruction](https://github.com/junegunn/vim-plug#installation) only tells you to download `plug.vim` file. The help file is not installed in the process.

You can tell vim-plug to download it by adding `Plug 'junegunn/vim-plug'`

See https://github.com/junegunn/vim-plug/pull/705#issuecomment-347017655
