### ISSUE TITLE
Recommendation for bootstraping plugins getting vimrc from central repo

### ISSUE THREAD

**Issue by filbranden** [junegunn/vim-plug#830]
I'm trying to figure out the best way to bootstrap my vimrc with plugins managed by vim-plug on a new machine from scratch. The main problem I'm getting is that my vimrc has commands which depend on the plug-ins being previously installed, so I get errors on the first run... Yes, after a `:PlugInstall` everything works great, but ideally I would like to make that part all automatic as part of the script I use to set up all dotfiles in a new machine.

For illustrative purposes, here's an example using a minimal reproducer. I'm using a colorscheme here since it's an easy way to reproduce this, but other possible ways would be to call a command or function that's registered by a plug-in.

Consider this simple `.vimrc`:

```vim
set nocompatible
call plug#begin()
Plug 'altercation/vim-colors-solarized'
call plug#end()
colorscheme solarized
syntax on
filetype plugin indent on
```

And install vim-plug using the [official instructions](https://github.com/junegunn/vim-plug#vim).

Then starting vim for the first time gives this error:

```
$ vim
Error detected while processing /home/filbranden/.vimrc:
line    5:
E185: Cannot find color scheme 'solarized'
Press ENTER or type command to continue
```

And the same happens if I start vim to install the plug-ins:

```
$ vim -c PlugInstall
Error detected while processing /home/filbranden/.vimrc:
line    5:
E185: Cannot find color scheme 'solarized'
Press ENTER or type command to continue
```

(After pressing enter, the plug-in gets installed, so future runs of vim will not have this issue anymore.)

I tried adding the snippet to [automatically install missing plugins on startup](https://github.com/junegunn/vim-plug/wiki/extra#automatically-install-missing-plugins-on-startup), but that doesn't help either, since it only runs after the whole .vimrc has been parsed.

Would it maybe be possible to find a solution that would work within vim-plug itself? For example, what if `plug#end()` would look for a variable set and, if it finds it, it would install plug-ins (and quit vim?) as part of its processing? Then I could pass it through `vim --cmd 'let g:plug_install_plugins = 1'` (which runs before `.vimrc` is parsed) so it would install plug-ins before that processing works?

Perhaps one alternative is to move the plug-in declaration (the `:Plug` commands) to a separate `.vim` file and then start vim using `-u` to only source that file, but I wonder if that would miss some of the first instructions in `.vimrc` that might be relevant...

Bonus points if this can be done in a "silent" or "batch" mode (similar to `ex -s`) so I could automate installing plug-ins without blinking the screen while opening vim.

Thanks!
Filipe

------------------------------

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Aug 17 2018 17:24:51)
Included patches: 1-503, 505-680, 682-1283
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
+acl             +cmdline_hist    -ebcdic          -gettext         +listcmds        -mouse_sgr       +persistent_undo +smartindent     +termresponse    +wildignore
-arabic          +cmdline_info    -emacs_tags      -hangul_input    +localmap        -mouse_sysmouse  +postscript      +startuptime     +textobjects     +wildmenu
+autocmd         +comments        +eval            +iconv           -lua             -mouse_urxvt     +printer         +statusline      +timers          +windows
-balloon_eval    -conceal         +ex_extra        +insert_expand   +menu            +mouse_xterm     -profile         -sun_workshop    +title           +writebackup
-browse          +cryptv          +extra_search    +job             +mksession       +multi_byte      +python/dyn      +syntax          -toolbar         -X11
+builtin_terms   +cscope          -farsi           +jumplist        +modify_fname    +multi_lang      -python3         +tag_binary      +user_commands   -xfontset
+byte_offset     +cursorbind      +file_in_path    -keymap          +mouse           -mzscheme        +quickfix        +tag_old_static  +vertsplit       -xim
+channel         +cursorshape     +find_in_path    +lambda          -mouseshape      +netbeans_intg   +reltime         -tag_any_white   +virtualedit     -xpm
+cindent         +dialog_con      +float           -langmap         -mouse_dec       +num64           -rightleft       -tcl             +visual          -xsmp
-clientserver    +diff            +folding         +libcall         -mouse_gpm       +packages        +ruby/dyn        -termguicolors   +visualextra     -xterm_clipboard
-clipboard       +digraphs        -footer          +linebreak       -mouse_jsbterm   +path_extra      +scrollbind      -terminal        +viminfo         -xterm_save
+cmdline_compl   -dnd             +fork()          +lispindent      -mouse_netterm   -perl            +signs           +terminfo        +vreplace
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -o vim        -lm -lncurses  -liconv -framework Cocoa
```

- Type:
    - [ ] Bug
    - [x] Enhancement
    - [x] Feature Request
    - [x] Question
- OS:
    - [x] All/Other
    - [x] Linux
    - [x] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by rr0ss0rr** [comment]
Try adding right above the plug#begin ...

"
" https://github.com/junegunn/vim-plug
"
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
       \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

**Comment by filbranden** [comment]
@rr0ss0rr No, that doesn't really work...

The first part running `curl` to install vim-plug itself I don't really need, since I'm fine with running that myself as part of the automation that's fetching my `.vimrc`...

The second part with the `VimEnter` is similar to [this tip I linked to](https://github.com/junegunn/vim-plug/wiki/extra#automatically-install-missing-plugins-on-startup), but that doesn't work since the `VimEnter` autocmd will only happen *after* `.vimrc` is processed, so the commands in `.vimrc` that need plug-ins will error out before then.

**Comment by filbranden** [comment]
Splitting plugins seems like an acceptable solution, but it looks hacky...

This is `~/.vim/plugins.vim`:

```vim
call plug#begin()
Plug 'altercation/vim-colors-solarized'
call plug#end()
```

And this is `~/.vimrc`:

```vim
set nocompatible
runtime plugins.vim
colorscheme solarized
syntax on
filetype plugin indent on
```

(The `runtime plugins.vim` is the part that's new here.)

Then I can bootstrap it with this command:

```
$ vim -u ~/.vim/plugins.vim -c PlugInstall -c qa
```

It still "blinks" the Vim window but I guess that's better than "Press ENTER ..."

I think a solution coming from vim-plug itself, possibly optionally installing them at `plug#end()` and possibly outputting messages with `:echom` or similar (which would work in Ex mode) would be awesome!

**Comment by junegunn** [comment]
You can just suppress the error message: `silent! colorscheme solarized`
