### ISSUE TITLE
wrong encoding 

### ISSUE THREAD

**Issue by kerwinxu** [junegunn/vim-plug#831]
Explain the problem here ...

exec PlugUpdate
out the below 

Finishing ... Done!
- gundo.vim: ÒѾ­ÊÇ×îÐµġ£
- vim-latex: ÒѾ­ÊÇ×îÐµġ£
- ale: ÒѾ­ÊÇ×îÐµġ£
- vim-preview: ÒѾ­ÊÇ×îÐµġ£
- jedi-vim: ÒѾ­ÊÇ×îÐµġ£
- rainbow_parentheses.vim: ÒѾ­ÊÇ×îÐµġ£
- Tagbar: ÒѾ­ÊÇ×îÐµġ£
- surround.vim: ÒѾ­ÊÇ×îÐµġ£
- ack.vim: ÒѾ­ÊÇ×îÐµġ£
- vim-gutentags: ÒѾ­ÊÇ×îÐµġ£
- gutentags_plus: ÒѾ­ÊÇ×îÐµġ£
- slimv: ÒѾ­ÊÇ×îÐµġ£
- AutoComplPop: ÒѾ­ÊÇ×îÐµġ£
- YankRing.vim: ÒѾ­ÊÇ×îÐµġ£
- ctrlp.vim: ÒѾ­ÊÇ×îÐµġ£
- asyncrun.vim: ÒѾ­ÊÇ×îÐµġ£
- gina.vim: ÒѾ­ÊÇ×îÐµġ£
- The-NERD-Commenter: ÒѾ­ÊÇ×îÐµġ£
- The-NERD-tree: ÒѾ­ÊÇ×îÐµġ£

there are wrong encoding .
if I do not set encoding=utf- 8, it work , but I can not set encoding=utf-8

win 10 , gvim . Bug
------------------------------

```

```

- Type:
    - [* ] Bug
- OS:
    - [* ] Windows
- Vim:
    - [* ] GVim

**Comment by janlazo** [comment]
Need [s:wrap_cmd](https://github.com/junegunn/fzf/commit/cce17ad0a02bfc0b86ed8a667113ff3c9ab79d8d#diff-24d9d57e35df5afce7890f2400917919R52) from fzf.

**Comment by janlazo** [comment]
Please test https://github.com/junegunn/vim-plug/pull/860.
