### ISSUE TITLE
can not disable plugin vimtex even if I only enable it for tex files

### ISSUE THREAD

**Issue by jdhao** [junegunn/vim-plug#835]
I am using vim-plug to manage my plugins and it seems that [vimtex](https://github.com/lervag/vimtex) are loaded even if I have instructed to load it only for tex files.

Here is a minimum `init.vim` to reproduce:

```
call plug#begin("~/.local/share/nvim/plugged")
Plug 'lervag/vimtex', { 'for': 'tex' }
call plug#end()
```

Open a Markdown file with the above settings using Neovim:

```
nvim -u init.vim test.md
```

Use `:PlugStatus` command and it shows that vimtex is actually loaded.

------------------------------

```
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_S
OURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-paramete
r -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnost
ics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_U
NIBI_HAS_VAR_FROM -I/tmp/neovim-20190113-94620-d8vv4n/neovim-0.3.4/build/config -I/tmp/neovim-201
90113-94620-d8vv4n/neovim-0.3.4/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/Appl
ications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/us
r/include -I/tmp/neovim-20190113-94620-d8vv4n/neovim-0.3.4/build/src/nvim/auto -I/tmp/neovim-2019
0113-94620-d8vv4n/neovim-0.3.4/build/include
Compiled by brew@Mojave.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.4/share/nvim"
```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [x] OS X
    - [x] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim (on both platform, the neovim version is 0.3.4)

**Comment by Konfekt** [comment]
This is probably due to the commits folllowing https://github.com/junegunn/vim-plug/issues/785

**Comment by junegunn** [comment]
@Konfekt is on point. `for` option for the plugin gives no benefit at all, rather it would add a small overhead, so we simply ignore the option.

It is stated in https://github.com/junegunn/vim-plug#on-demand-loading-of-plugins

> `for` option is generally not needed as most plugins for specific file types usually don't have too much code in `plugin` directory.

and vimtex doesn't even have `plugin` directory.

I know it can be confusing, but vim-plug is doing the right thing for you. I'll see if the message on `PlugStatus` window can be improved.
