### ISSUE TITLE
The documentation for `frozen` tag is not clear

### ISSUE THREAD

**Issue by p1v0t** [junegunn/vim-plug#840]
Is someone use `frozen` tag? The documentation doesn't say much about it, and I didn't see an example on README. I tried:
```
Plug 'some-plugin', {'frozen'}
Plug 'some-plugin', 'frozen'
```
but it didn't work :(

Thank you kindly.

------------------------------

```

```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [x] All/Other
    - [x] Linux
    - [x] OS X
    - [x] Windows
- Vim:
    - [x] Terminal Vim
    - [x] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
`{'frozen'}` is not a proper VimScript. Use `{'frozen': 1}`.

**Comment by elig0n** [comment]
it could be useful for other (i.e. without internet connection) if it had been explained/exampled in the readme
