### ISSUE TITLE
cmd is not executable

### ISSUE THREAD

**Issue by S1lander** [junegunn/vim-plug#843]
I'm trying to install a Python Syntax Theme.
When I'm using ":PlugInstall" I'm getting a "cmd is not executable" error...?
Did I acidentally delete an important system path definition?

```
Updated. Elapsed time: 1.034419 sec.
  2 [x]
  3
  4 - Finishing ... Done!
  5 x semshi:
  6     cmd is not executable
```

.vimrc
```
call plug#begin('~/.local/share/nvim/plugged')

Plug 'https://github.com/numirias/semshi.git'

call plug#end()

set nu
colorscheme slate
syntax on
set background=dark
```

init.vim (linking to .vimrc)
```
set runtimepath^=~/.vim runtimepath+=~/.vim/after
    let &packpath = &runtimepath
    source ~/.vimrc
```

------------------------------

```
NVIM v0.3.5
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.
exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_D
EPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_
FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/projects/neo
vim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv -jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"
```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [x] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by janlazo** [comment]
Does expanding the tilde before passing the path to `plug#begin` help? Hard to believe that `cmd.exe` is not in `PATH` unless the path from `%TMPDIR%` (or `%USERPROFILE%`) has spaces.

**Comment by janlazo** [comment]
If cmd.exe is not in `%PATH%` and `C:\Windows\System32\cmd.exe`  does not exist, then your environment is broken.
