### ISSUE TITLE
where is the name of a plugin mentioned and how is it used?

### ISSUE THREAD

**Issue by gartha1** [junegunn/vim-plug#844]
Hi

I understand that in the case of bufexplorer I want

> call plug#begin('~/.vim/plugged_plugins')  
> 
> " Buffer explorer
> Plug 'jlanzarotta/bufexplorer'
> " Initialize plugin system
> 
> call plug#end()
> 

And I have   `~/.vim/autoload/plug.vim`

And I have this directory ~/.vim/plugged_plugins/bufexplorer

It works. And I can use bufexplorer with <leader> then b then e.

But I can't see the name jlanzarotta  mentioned in any directory path or in `~/.vim/plugged_plugins/bufexplorer/plugin/bufexplorer.vim`

So I can't really see how it that name is being used when it is mentioned there in the vimrc.

How is it being used?

Thanks

**Comment by mschilli87** [comment]
@gartha1:
> I can't really see how it that name is being used

It's being used when `vim-plug` needs to find the source code for the plugin (for when you run `:PlugInstall` or `:PlugUpdate`) which is at https://github.com/jlanzarotta/bufexplorer.
