### ISSUE TITLE
Not working on Raspberian (Raspberry pi 3b+

### ISSUE THREAD

**Issue by svliantiss** [junegunn/vim-plug#845]
The PlugInstall and PlugUpdate commands are not working on raspberian (Raspberry pi 3b+)
On all of my other machines they work, I even re downloaded the curl file.

What outputs could I give to help you help me?
- Raspberian Stretch Lite
- Neovim

**Comment by danthedeckie** [comment]
In vim, if you press `<esc>:Plug` do you see anything listed at all?  If not, then it's not being loaded into vim yet.
try 
    `:source /home/svliantiss/.vim/autoload/plug.vim`
(or wherever you have it downloaded to)
and see if it appears then...

**Comment by cyh0968** [comment]
When I load plug.vim in raspbian, vi gives the following message

Not an editor command

**Comment by cyh0968** [comment]
Oh it can be resolved with the following command 

sudo apt-get install vim

the default rasbian vim does not support vim runtime 

however sudo apt0get install vim makes it possible

**Comment by janlazo** [comment]
vim-plug does not support tiny/small (see `:h version`) builds of Vim, vi, and vim.tiny.Installing vim via apt-get works because that installs the normal version. For best results, use the huge version and run vim-plug on Vim 7.4+ because that is what's tested in the CI.

**Comment by janlazo** [comment]
vim-plug doesn't define `PlugInstall`, `PlugUpdate` if git is not installed.
