### ISSUE TITLE
More function

### ISSUE THREAD

**Issue by kerwinxu** [junegunn/vim-plug#848]
i want more function named isload , like 

Plug 'vim-scripts/The-NERD-tree' ,{'on':'NERDTreeToggle'} "
if isload('The-NERD-tree')
	map <F8> <ESC>:NERDTreeToggle <CR><ESC>:TagbarToggle<CR><ESC>
	imap <F8> <ESC>:NERDTreeToggle <CR><ESC>:TagbarToggle<CR><ESC>
endif

**Comment by kodaman2** [comment]
This functionality can be easily achievable with vim script.

**Comment by janlazo** [comment]
See https://github.com/junegunn/vim-plug/wiki/tips#conditional-activation
