### ISSUE TITLE
hello how to know whether a plug has loaded?

### ISSUE THREAD

**Issue by fgheng** [junegunn/vim-plug#849]
Explain the problem here ...

------------------------------

```
hello, how can i know whether a plugin has loaded?
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [X] Question
- OS:
    - [ ] All/Other
    - [X] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [X] Neovim

**Comment by wookayin** [comment]
e.g. `has_key(g:plugs, 'vim-sensible')`

**Comment by fgheng** [comment]
> e.g. `has_key(g:plugs, 'vim-sensible')`
> 
> NOTE: It may not work as expected for dynamically loaded (e.g. on, for, etc.) plugins.

thank you very much.

**Comment by wookayin** [comment]
I wish we had some way to tell whether the plugin has actually been loaded: e.g. from `s:loaded` (which is not public) https://github.com/junegunn/vim-plug/blob/0.10.0/plug.vim#L110. We may have an API to query this: e.g. `plug#is_loaded`.

**Comment by junegunn** [comment]
> I wish we had some way to tell whether the plugin has actually been loaded

We could add `loaded` property to each entry in `g:plugs`. It's old code, and I don't quite remember why I didn't go that route.
