### ISSUE TITLE
Feature request: Load plugins based on vim version

### ISSUE THREAD

**Issue by GoldsteinE** [junegunn/vim-plug#851]
There is [Command-T](https://github.com/wincent/Command-T) plugin that requires Ruby. I want to use the same `.vimrc` on all of my hosts, but not all of them have Ruby. So, it'd be cool if I could do something like
```vim
Plug 'wincent/Command-T', { 'vimversion': ['ruby'] }
```
to plug Command-T only when there is ruby support.
Neomake works fine only on Vim 8+, so it'd be
```vim
Plug 'neomake/neomake', { 'vimversion': ['>=8.0'] }
```

- Type:
    - [ ] Bug
    - [x] Enhancement
    - [x] Feature Request
    - [ ] Question
- OS:
    - [x] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows

**Comment by lexpierce** [comment]
Vim already has syntax for the versioning question:
```
if v:version > 800
  Plug 'SirVer/ultisnips'
  Plug 'w0rp/ale'
endif
```

and it works fine.  Seems like this would be unnecessary functionaity.

**Comment by junegunn** [comment]
```vim
if has('ruby')
  Plug 'wincent/Command-T'
endif
```
