### ISSUE TITLE
Fix request: clone default branch, not just "master"

### ISSUE THREAD

**Issue by unclechu** [junegunn/vim-plug#854]
I realized it clones exactly `master` branch of a repo, I guess it supposed to clone default branch (`master` branch isn't always equals to default branch of a repo).

**Comment by kodaman2** [comment]
Did you read the documentation? It has examples for just about everything. You can give it a branch, or tag.

" Using a non-master branch Plug 'rdnetto/YCM-Generator', { 'branch': 'stable' }

**Comment by mschilli87** [comment]
@kodaman2: I understood this as a proposal to make the default branch to clone (*i.e.* when no branch was given explicitely like you suggested), the *default* branch of the repository (which often but not always is `master`). I think this is a sensible thing to do and also what I would expect. What e.g. happens, when I make `production` my default branch and entirely remove any `master` branch? Why would vim-plug *require* explicit branch specification for this repository if git provides a way to ask 'If I have no clue which branch to take, which one should I pick?'. :wink:

**Comment by kodaman2** [comment]
I misunderstood OP question, sorry.

Looking into the code vim-plugin has "master" as a string variable. [L103](https://github.com/junegunn/vim-plug/blob/master/plug.vim#L103). Will have to modify the command where it calls git to get default branch instead which is entirely possible, but to be honest most vim plugins have default as master, I don't know why you would change the default to something else other than master.

[L554-L561](https://github.com/junegunn/vim-plug/blob/master/plug.vim#L554-L561)

I guess there are far better ways to handle from which branch does it clone by vim-plug. vim-plug could select based on latest tag, or latest branch, but then again latest branch might be a WIP. Would be far ideal to pull the latest version tag.

**Comment by mschilli87** [comment]
I think default should be what the repository owner sets as default, so the 'default' git branch as proposed here. That said I agree that naming this branch `master` is a very common convention and if implementing this is non-trivial, I'd totally understand keeping `master` hard-coded.

**Comment by kodaman2** [comment]
Maybe give the option to the user on the config file, if they want plugins to search for default or master could be a good idea in the case for those plugins which master is not the default.

Or do this check when installing a plugin where master is not the default give a warning and let user select branch?

**Comment by unclechu** [comment]
> Did you read the documentation? It has examples for just about everything. You can give it a branch, or tag.
> 
> ```
> " Using a non-master branch Plug 'rdnetto/YCM-Generator', { 'branch': 'stable' } 
> ```

I know how I can do it, I'm about that default behavior isn't perfect.

**Comment by kodaman2** [comment]
How many plugins have you found which the default isn't master out of curiosity.

**Comment by unclechu** [comment]
@kodaman2 [My own fork of a plugin](https://github.com/unclechu/haskell-vim) while I'm keeping `master` branch up-to-date to original repo.

**Comment by unclechu** [comment]
@kodaman2 Well, I just realized there are more:
```bash
grep ^Plug plugins.vim \
  | sed "s/^Plug '\([^']*\)'.*$/\1/" \
  | parallel 'printf "%s: " "{}"; git remote show -- "https://github.com/{}" | grep "HEAD branch" | sed "s/[^:]*: //"' \
  | grep -v ': master$'
```
```text
unclechu/haskell-vim: my-fork
Lokaltog/vim-distinguished: develop
```

**Comment by junegunn** [comment]
This was discussed several times in the past. You should be able to find some related issues here. While I do not disagree with the suggestion, implementing it correctly without complicating the code too much is actually not trivial (e.g. branch validation in PlugStatus, how to find out if the default branch has been changed in the origin after we cloned it, etc.), so it's not exactly something I'd like to look into now. But patches are welcome.
