### ISSUE TITLE
Installation as described- PlugInstall is not a command=(

### ISSUE THREAD

**Issue by IzaGz** [junegunn/vim-plug#855]
Everything as described
call plug$begin('~/.vim/autoload')
 
and everything as described

file plug.vim inside the folder `autoload`

gvim installed as `sudo apt-get install vim-gnome`

linux mint 19.1 Tessa

when starting gvim from terminal, this error :
```
desktop:~$ gvim
[vim-plug] git executable not found. Most commands will not be available. To suppress this message, prepend silent! to call plug#begin(...).
```

**Comment by wookayin** [comment]
The error message tells everything you should do. Install `git`.
