### ISSUE TITLE
Neovim + vim-plug + gitgutter

### ISSUE THREAD

**Issue by wave-blessed** [junegunn/vim-plug#862]
Hello.
I just try to learn vin/neovim and have tried to use gitgutter also (I love git). I install any vim addons by vim-plug manager (this is great plugin manager). `Vim + vim-plug + gitgutter` work perfectly, but if I try install gitgutter to neovim, I see the next things:

* After `:PlugInstall` gitgutter works.
* After restarting neovim plugin doesn't work like it doesn't exist. `:GitGutter` neovim says it's not an editor command. `:scriptnames` doesn't show any gitgutter scripts. Etc.

After manual install gitgutter to neovim (unpacking autoload and plugin folders to `\share\nvim\runtime`) it works.

nvim.exe x64 latest in terminal mode, vim-plug latest, gitgutter latest.
`:checkhealth` shows only some warnings about python2, ruby and node which doesn't installed here.

**Comment by junegunn** [comment]
Make sure that your vim configuration file contains `call plug#end()`.

See https://github.com/junegunn/vim-plug#usage

**Comment by wave-blessed** [comment]
It does. And part of other plugins work fine in neovim and all of them work fine in vim.

I have to add `{'on': 'NERDTreeToggle'}` to `Plug 'scrooloose/nerdtree'` and `Plug 'ryanoasis/vim-devicons'` because they don't work in neovim without this part. And I have some incomprehensible issues for python plugins. But they work.
Shoud I add `{'on': 'some_command'}` to `Plug 'airblade/vim-gitgutter'` and turn on it manually?

**Comment by junegunn** [comment]
> Shoud I add {'on': 'some_command'} to Plug 'airblade/vim-gitgutter' and turn on it manually?

No. It's completely optional. I suggest that you strip down your config file to the bare minimum (three lines, each for `plug#begin`, `Plug 'airblade/vim-gitgutter'`, and `plug#end`) and see if it works.

**Comment by wave-blessed** [comment]
The same thing.
* Thees three line in init.vim.
* Start nvim.exe
* `:e README.md` of some repository
* `:GitGutterEnable` — `E492: Not an editor command: GitGutterEnable`
* `:PlugInstall` — `vim-gitgutter: Already installed`
* `:GitGutterEnable` — shows new\modified\removed lines in README.md

Modified line in init.vim: `Plug 'airblade/vim-gitgutter', {'on': 'GitGutterEnable'}`
* start nvim.exe
* `:e README.md`
* `:GitGutterEnable` — shows new\modified\removed lines in README.md

Ok, some installed via vim-plug plugins in neovim don't load automatically. Only manually. Vim is problemless.

P.s. Tested neovim nightly x86, neovim 3.8 stable x64 and neovim nightly gui version — same behavior.

**Comment by wave-blessed** [comment]
I've foun out if `call plug#begin` — `call plug#end` section is in %AppData% init.vim instead $VIM\runtime\plugin\init.vim — everything work excellent. Otherwise I have use `{'on': somecommand}` for every plugin and call theese commands after that section.
Issue for neovim repository opened.
