### ISSUE TITLE
PlugInstall is using cached version

### ISSUE THREAD

**Issue by kkoomen** [junegunn/vim-plug#863]
When I add a new `Plug ''<name>` to my `.vimrc` or I remove one and I run `:PlugInstall` it doesn't change anything.

To reproduce:

- My current vimrc:

```
Plug 'SirVer/ultisnips'
```

Output of `:PlugInstall`:

```
Updated. Elapsed time: 60.852768 sec.
[=]

- Finishing ... Done!
- ultisnips: Resolving deltas: 100% (221/221), done.
```

- Add another plugin

```
Plug 'SirVer/ultisnips'
Plug 'Yggdroot/indentLine'
```

Output of `:PlugInstall`:

```
Updated. Elapsed time: 0.147873 sec.
[=]

- Finishing ... Done!
- ultisnips: Already installed
``z

------------------------------

<!-- Put the contents of `:version` below -->
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul  8 2019 19:24:38)
macOS version
Included patches: 1-1650
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_any_white
+arabic            +file_in_path      +mouse_urxvt       -tcl
+autocmd           +find_in_path      +mouse_xterm       +termguicolors
+autochdir         +float             +multi_byte        +terminal
-autoservername    +folding           +multi_lang        +terminfo
-balloon_eval      -footer            -mzscheme          +termresponse
+balloon_eval_term +fork()            +netbeans_intg     +textobjects
-browse            +gettext           +num64             +textprop
++builtin_terms    -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     +perl              -toolbar
+cindent           +job               +persistent_undo   +user_commands
-clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           -python            +visual
+cmdline_info      +libcall           +python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          +ruby              +wildmenu
+cursorbind        +lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con        +mksession         +smartindent       -X11
+diff              +modify_fname      -sound             -xfontset
+digraphs          +mouse             +spell             -xim
-dnd               -mouseshape        +startuptime       -xpm
-ebcdic            +mouse_dec         +statusline        -xsmp
+emacs_tags        -mouse_gpm         -sun_workshop      -xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          +mouse_netterm     +tag_binary        
+extra_search      +mouse_sgr         -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -lintl -framework AppKit  -L/usr/local/opt/lua/lib -llua5.3 -mmacosx-version-min=10.14 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.30.0/lib/perl5/5.30.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -framework CoreFoundation  -lruby.2.6     
```

<!-- Check all that apply. -->
- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [x] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by kkoomen** [comment]
Sorry, I had to re-open vim ofc. My bad. T_T

**Comment by contrailk8sdayone** [comment]
why was this closed? I have same issue. 
I add a new line in .vimrc and save it
Plug 'SirVer/ultisnips'
then run PlugInstall, I expect to see the new plugin get installed - without VIM restart.
but that never happens...

am I missing anything?

**Comment by kkoomen** [comment]
You define your plugins in your vimrc. To reload your vimrc and source the new plugins, you can use `so %`. It is expected that you need to re-open Vim or re-source your vimrc.
