### ISSUE TITLE
Remove --no-single-branch to optimise speed for some repos

### ISSUE THREAD

**Issue by kkoomen** [junegunn/vim-plug#864]
Some of the plugins I used toke quite long compared to the other ones since these ones have quite a few branches. I saw that vim-plug uses `--no-single-branch` as a flag. Is this _required_ by something? Otherwise I suggest to remove this. It'll make cloning faster for some repositories.

------------------------------

- Type:
    - [ ] Bug
    - [x] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [x] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
> Is this required by something? 

Yes, we decided that we need it to support switching of branches offline, so we won't remove it. I suggest that you remove the option from your own copy of plug.vim if you really want it removed. vim-plug is extremely stable, so you don't have to worry about keeping in sync with the upstream.
