### ISSUE TITLE
How to manual load the plug one by one manually

### ISSUE THREAD

**Issue by irreallich** [junegunn/vim-plug#865]
Explain the problem here ...

------------------------------

```

```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [yes ] Question
- OS:
    - [yes ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ yes] Terminal Vim
    - [ yes] GVim
    - [ ] Neovim

Hi,
    Thansk for your great plugin , it is very good software.
    There is a questions about manual load.
    If there are file vim plugin , A,B,C,D,E , 
    At the begining , I only want to load  A and B ,so I can do the following 
```
silent! call plug#begin(a:path)
    Plug 'A'
    Plug 'B'
silent! call plug#end()
```
**then I want to add plugin C , I can do the following**
```
silent! call plug#begin(a:path)
    Plug 'C'
silent! call plug#end()   
```

But it is ugly , is there beautiful way to do it ?
Is there other way to remove B and A , and log D and E ?

**Comment by junegunn** [comment]
Write `Plug 'C', { 'on': [] }` ("on nothing") and vim-plug won't load it until you `call plug#load('C')`.
