### ISSUE TITLE
how to use vim-plug install plug when the computer cannot access Github

### ISSUE THREAD

**Issue by Yangel-hide** [junegunn/vim-plug#872]
Hello， I‘m trying to install plugs from local package because my linux server can’t  access Github.

I download vim-easy-align package from github and try two ways in #701 ，and the error shows below:
```
call plug#begin('~/.vim/plugged')


Plug 'file://'.expand('~/.vim/plugged/vim-easy-align') 
"fatal: destination path '~/.vim/plugged/vim-easy-align' already exists and is not an empty directory.


Plug 'file://'.expand('~/otherdir/vim-easy-align') 
"fatal :'~/otherdir/my_plug' does not appear to be a git repository

call plug#end()
```

------------------------------

```

```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
In your use case, remove `file://` prefix so that vim-plug loads the plugin directly from the directory. `:PlugInstall` is not needed.

```vim
Plug '~/otherdir/vim-easy-align'
```

**Comment by Yangel-hide** [comment]
> In your use case, remove `file://` prefix so that vim-plug loads the plugin directly from the directory. `:PlugInstall` is not needed.
> 
> ```viml
> Plug '~/otherdir/vim-easy-align'
> ```

Thank you! 
I solved it.
