### ISSUE TITLE
Invalid URI after PlugUpdate, what happens?

### ISSUE THREAD

**Issue by xaljer** [junegunn/vim-plug#876]
Explain the problem here ...
Errors after :PlugUpdate :
<img width="659" alt="Snipaste_2019-09-11_00-50-39" src="https://user-images.githubusercontent.com/8309631/64634093-13aa7380-d42f-11e9-8642-11250cd109f8.png">
but most plugin works ok.
I try to install and update after delete all plugin files, it appears again.
------------------------------

![image](https://user-images.githubusercontent.com/8309631/64634058-0097a380-d42f-11e9-9baf-abd6976a8e70.png)

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [x] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by janlazo** [comment]
'& %BATCHFILE_PATH%` can happen only if using powershell. Do you set your shell options as recommended in `:h shell-powershell`?

**Comment by thekpaul** [comment]
This happens to me as well, and I did everything `:h shell-powershell` told me to do.
![nvim](https://user-images.githubusercontent.com/44695374/66481457-f0c9b880-eadb-11e9-94f3-5a23b2de8d8d.jpg)
This Error message appeared in NeovimQt.

**Comment by xaljer** [comment]
this issue happens since i update it to a new version~

**Comment by janlazo** [comment]
https://github.com/neovim/neovim/pull/11122 Updating `:h shell-powershell` to suggest `set shellquote=`.

**Comment by thekpaul** [comment]
My `init.vim` includes the `set shellquote=` option:
```vim
if has('win32')
    set shell=powershell
    set shellquote= shellpipe=\| shellxquote=
    set shellcmdflag=\ -NoLogo\ -ExecutionPolicy\ RemoteSigned\ -Command
    set shellredir=\|\ Out-File\ -Encoding\ UTF8
endif | "Set Default Shell Application to PowerShell
```
The problem reoccurs with or without this option, though.

**Comment by xaljer** [comment]
This issue appear from the commit: https://github.com/junegunn/vim-plug/commit/226d6abeb2f02bcd8f5b11288543259fa2e02962 
so what's the correct option of powershell?

**Comment by yatli** [comment]
The batch file syntax does not work with powershell, so currently I'm afraid powershell isn't an option.

**Comment by janlazo** [comment]
powershell should run cmd.exe for `*.bat` files when executed via `&` call operator.

**Comment by yatli** [comment]
yeah, I had a look at the code a while ago: https://github.com/junegunn/vim-plug/blob/849b76be90a2c5a13fd9943b2b76d77a9b6ebc0f/plug.vim#L826-L845

looks alright to me, but it fails to execute.

**Comment by janlazo** [comment]
See https://github.com/junegunn/vim-plug/issues/895#issuecomment-544130552

(neo)vim allows omitting `.exe` and other executable file extensions but it's best to be explicit. `shell` default on Windows includes `.exe` extension.
