### ISSUE TITLE
source .vimrc not working

### ISSUE THREAD

**Issue by shogayaking** [junegunn/vim-plug#877]
Hi, I am trying to install vim-plug and I followed your instructions in your tutorial. I have written in .vimrc like so:
```
call plug#begin('~/.vim/autoload')
call plug#end()
```

but I get the following errors:
```
-bash: /Users/user/.vimrc: line 18: syntax error near unexpected token `('
-bash: /Users/user/.vimrc: line 18: `call plug#begin('~/.vim/autoload')'
```
Do you know what I am doing wrong?
------------------------------

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [x] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by amit-raut** [comment]
Hi @shogayaking 

The reason you're getting error is because you're specifying incorrect location for the plugins to be installed with `vim-plug`. The `vim-plug` plugin manager is located at `~/.vim/autoload` 

I created a directory at path `~/.vim/myPlugins` and referenced that directory in my `.vimrc` like shown in code below

```
call plug#begin('~/.vim/myPlugins/')
Plug 'junegunn/vim-easy-align'
call plug#end()
```

Try creating directory `~/.vim/myPlugins` and adding above code in `.vimrc`. It worked for me. 

Hope this helps! :)

Thank you,
Amit

**Comment by junegunn** [comment]
```
-bash: /Users/user/.vimrc: line 18: syntax error near unexpected token `('
-bash: /Users/user/.vimrc: line 18: `call plug#begin('~/.vim/autoload')'
```

You're sourcing .vimrc file from bash. .vimrc is not a bash script, so it will obviously fail. `:source` it inside Vim or you can just restart Vim.

**Comment by ShubhamBelwal** [comment]
@junegunn I did `source` inside my vim and got the same syntax error.

![image](https://user-images.githubusercontent.com/36201797/65827227-934c9500-e2ad-11e9-9797-2cf3c901c36a.png)

I followed the exact steps mentioned in the tutorial.

**Comment by junegunn** [comment]
The tutorial doesn't tell you to prepend `!` to source command.

**Comment by ShubhamBelwal** [comment]
Apologies for the confusion, this is my first time using linux.

**Comment by CS2Us** [comment]
> The tutorial doesn't tell you to prepend `!` to source command.

Thanks fot the tips. The reason of warning is because execute command `:! source .vimrc` instead of `: source .vimrc' inside vim.
