### ISSUE TITLE
vim-plug "for" statement ignored (plugin loads for all filetypes)

### ISSUE THREAD

**Issue by khughitt** [junegunn/vim-plug#880]
**Overview**

vim-plug ignores "for" limiting plugin to a particular filetype.

In my config I have:

```
Plug 'plasticboy/vim-markdown', { 'for': ['markdown'] }
```

However, opening vim on any document or a new buffer results in the plugin being loaded, e.g.:

```
:filter /mark/ scriptnames
26: ~/.dotfiles/nvim/plugged/vim-markdown/ftdetect/markdown.vim
```

Any ideas what could be going on?

------------------------------

**:version**

```
NVIM v0.4.0-1750-gce9367c25
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -g -DMIN_LOG_LEV
EL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wsh
adow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong
-fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FL
OAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/keith/.cache/yay/neovim-git/src/neovim-git/build/conf
ig -I/home/keith/.cache/yay/neovim-git/src/neovim-git/src -I/usr/include -I/home/keith/.cache
/yay/neovim-git/src/neovim-git/build/src/nvim/auto -I/home/keith/.cache/yay/neovim-git/src/ne
ovim-git/build/include
Compiled by keith@titan

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

- Type:
    - [X] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [X] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [X] Neovim

**Comment by junegunn** [comment]
`ftdetect` files are always loaded; in this case, if it's not loaded, there's no way to tell if a file is of "markdown" type. So it's working as expected.

Having said that, it is pretty likely that you're over-optimizing your setup. See https://github.com/junegunn/vim-plug/wiki/faq#when-should-i-use-on-or-for-option

**Comment by khughitt** [comment]
@junegunn Thanks! Actually, in this case, the issue is that the vim-markdown and nvim-r plugins conflict with one another: loading the former breaks the syntax highlighting of the later. This issue has already been previously reported on both of those packages, but no progress has been made on those fronts, so I thought I would try this route.
