### ISSUE TITLE
Update Wiki documentation for installing plugins with Neovim

### ISSUE THREAD

**Issue by SimonLab** [junegunn/vim-plug#881]
Hello,
The [Installing plugins](https://github.com/junegunn/vim-plug/wiki/tutorial#installing-plugins) section in the the wiki says to add the list of plugins to install in the `~/.local/share/nvim/site/autoload/plug.vim` file for Neovim. 
I think this should be instead the `~/.config/nvim/init.vim` file?

- Type:
    - [ ] Bug
    - [x] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
You're right, thanks for pointing it out. I just fixed it.
