### ISSUE TITLE
Get anonymous plugin statistics

### ISSUE THREAD

**Issue by sooriravindra** [junegunn/vim-plug#882]
- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [X] Feature Request
    - [ ] Question
- OS:
    - [X] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [X] Terminal Vim
    - [X] GVim
    - [X] Neovim

Since vim-plug is one of the most used plugin managers today, I feel it is well poised to collect statistics from the user about the installed plugins. This can aid several things:
- First and the most obvious, a database of what are the most commonly used plugins.
- See which new plugins are getting traction, this will allow vimmers to find plugins that they might be interested in.
- Plugins which might have large number of stars on github but are no more used.

Letting the user turn of reporting statistics should be an option on a per plugin basis. I understand this might develop a need for a server to which vim-plug should report the statistics to. I am curious if you see value in this.

**Comment by mschilli87** [comment]
Just my two cents:
If this is implemented as opt-out, I'll stop using `vim-plug` immediately.
If you really feel the internet needs more data sources to fingerprint users/computers as a side-effect of wanting some sort of 'charts', feel free. But *please* only record data of users that specifically (and actively) decided to do so (i.e. opt-in).

**Comment by sooriravindra** [comment]
@mschilli87 I really am not sure if anonymous statistics would be a concern for fingerprinting. That said, opt-in could also be a good option.

**Comment by VladimirMarkelov** [comment]
To me:

> First and the most obvious, a database of what are the most commonly used plugins

would not be correct. First, if it is opt-in, I doubt a lot of people turn it on. Second, 'vim-plug' is not the only plugin manager, and some of them are quite popular as well(I see vundle or dein used in many configs). So, it seems to me that it never generates credible statistics. From this point of view, I do not see why to implement this.

As for this:

> this will allow vimmers to find plugins that they might be interested in

on vim.org in scripts section any item has the number of downloads and the script's score that may throw light on the script/plugin usefulness for people. Though, (a) some people who install with plugin managers may be excluded from that statistics; (b) some developers may not publish their plugins on vim.org

**Comment by pchampio** [comment]
I think you can already have such statistics using Google Big Query with the Github dataset.
