### ISSUE TITLE
 Why you say vim-scripts.org is no longer maintained?

### ISSUE THREAD

**Issue by hongyi-zhao** [junegunn/vim-plug#883]
Hi,

On this webpage:

https://github.com/junegunn/vim-plug/wiki/tips#automatic-installation

You said that:

Unlike Vundle, vim-plug does not implicitly prepend vim-scripts/ to single-segment argument. So Plugin 'taglist.vim' in Vundle should be explicitly written as Plug 'vim-scripts/taglist.vim'. However, note that vim-scripts.org is no longer maintained.

But, I noticed that the following site: https://www.vim.org/scripts/, is still actively maintained.  

It seems this site is the same as  vim-scripts.org.

**Comment by Konfekt** [comment]
The missing maintenance refers to the account `vim-scripts` at github.com and his repositories, not to the site <www.vim.org/scripts/>.
