### ISSUE TITLE
Windows: bug in function s:wrap_cmds(cmds) if 'chcp' message is in French

### ISSUE THREAD

**Issue by gh4w** [junegunn/vim-plug#885]
Hi.
Output of chcp is not parsed correctly on Windows in the following function on a French install of Windows:
```vim
  " Copied from fzf
  function! s:wrap_cmds(cmds)
    return map(['@echo off', 'for /f "tokens=4" %%a in (''chcp'') do set origchcp=%%a', 'chcp 65001 > nul'] +
    \ (type(a:cmds) == type([]) ? a:cmds : [a:cmds]) +
    \ ['chcp %origchcp% > nul'], 'v:val."\r"')
  endfunction
```
The problem lies in the fact that the output of `chcp` is, for me:
```
Page de codes active : 850
```
instead of (i guess):
```
active code page: 850
```
so `origchcp` is set to `active` instead of 850.
`PlugUpdate` fails later with some message like (translated):
```
parameter format is incorrect - active
```
Fix: for me, the fix is to change `for /f "tokens=4"` to `for /f "tokens=5"`, but obviously that depends on the language.

version info:
```
NVIM v0.4.2
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compilpar appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

         fichier vimrc syste : "$VIM\sysinit.vim"
               $VIM par daut : "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [x] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

That's all.
Thank you for your plugin :)

**Comment by gh4w** [comment]
here's for a proper fix: parse the output of chcp on the colon instead of the space (warning: tested in a batch file but not in vim):

```vim
function! s:wrap_cmds(cmds)
  return map(['@echo off', 'for /f "delims=: tokens=2" %%a in (''chcp'') do set origchcp=%%a', 'set origchcp=%origchcp: =%', 'chcp 65001 > nul'] +
  \ (type(a:cmds) == type([]) ? a:cmds : [a:cmds]) +
  \ ['chcp %origchcp% > nul'], 'v:val."\r"')
endfunction
```

`delims=: tokens=2` select the string after the colon: ` 850`, then `set origchcp=%origchcp: =%` remove the leading space. That should be language-independant, provided the format is always formatted as `<some message>: <the actuel code page>`

**Comment by gh4w** [comment]
btw: probably related to #884 and #874

**Comment by junegunn** [comment]
Thanks for the analysis. I'm not a Windows user, but the suggested patch makes perfect sense. Can you open a pull request with the fix?

/cc @janlazo

**Comment by janlazo** [comment]
Patch works for me. fzf's Vim plugin needs the same fix.

**Comment by gh4w** [comment]
> 
> 
> Thanks for the analysis. I'm not a Windows user, but the suggested patch makes perfect sense. Can you open a pull request with the fix?

There you go: #886

**Comment by gh4w** [comment]
@janlazo: 
> I prefer that the patch is updated to use [DelayedExpansion](https://ss64.com00/nt/delayedexpansion.html) 

Then the patch would be:
```diff
diff --git a/plug.vim b/plug.vim
index 6b4caf8..bc3706c 100644
--- a/plug.vim
+++ b/plug.vim
@@ -353,9 +353,9 @@ if s:is_win
 
   " Copied from fzf
   function! s:wrap_cmds(cmds)
-    return map(['@echo off', 'for /f "tokens=4" %%a in (''chcp'') do set origchcp=%%a', 'chcp 65001 > nul'] +
+    return map(['@echo off','setlocal enabledelayedexpansion','for /f "delims=: tokens=2" %%a in (''chcp'') do set origchcp=%%a','set origchcp=!origchcp: =!','chcp 65001 > nul'] +
     \ (type(a:cmds) == type([]) ? a:cmds : [a:cmds]) +
-    \ ['chcp %origchcp% > nul'], 'v:val."\r"')
+    \ ['chcp !origchcp! > nul','setlocal disabledelayedexpansion'],'v:val."\r"')
   endfunction
 
   function! s:batchfile(cmd)
```
(I don't know about formatting convention in vimscript, the line may be a little too long.)

**Comment by janlazo** [comment]
#886 is merged.
