### ISSUE TITLE
Protect wiki automatic installation with version checking

### ISSUE THREAD

**Issue by evandrocoan** [junegunn/vim-plug#894]
I tried to run the above snipped on Debian 7 with vim 703 and it throws errors:
```
Error detected while processing /root/.vimrc:
line   14:
E117: Unknown function: plug#begin
line   20:
E492: Not an editor command:   Plug 'Shougo/deoplete.nvim'
line   28:
E117: Unknown function: plug#end

"~/.vimrc" 376L, 10606C
Error detected while processing VimEnter Auto commands for "*":
E492: Not an editor command: PlugInstall --sync | source $MYVIMRC
```

I suggest protecting the installation snippet: https://github.com/junegunn/vim-plug/wiki/tips
```vim
if v:version > 703
	if empty(glob('~/.vim/autoload/plug.vim'))
	  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
	    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
	  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
	endif
endif
```

**Comment by janlazo** [comment]
vim-plug depends on `+autoload` feature, included in the normal version (see `:h version`). Is `has('autoload')` enough or does it need a patch check such as `has('patch-7.4.0154')`?

**Comment by evandrocoan** [comment]
I have run:
```vimrc
echo has('patch-7.4.0154')
echo has('autoload')
```

The result is:
```
0
0
```

My output of `vim --version` is:
```
# vim --version
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Feb 10 2013 02:28:47)
Included patches: 1-547
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by jamessan@debian.org
Huge version without GUI.  Features included (+) or not (-):
+arabic +autocmd -balloon_eval -browse ++builtin_terms +byte_offset +cindent 
-clientserver -clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments 
+conceal +cryptv +cscope +cursorbind +cursorshape +dialog_con +diff +digraphs 
-dnd -ebcdic +emacs_tags +eval +ex_extra +extra_search +farsi +file_in_path 
+find_in_path +float +folding -footer +fork() +gettext -hangul_input +iconv 
+insert_expand +jumplist +keymap +langmap +libcall +linebreak +lispindent 
+listcmds +localmap -lua +menu +mksession +modify_fname +mouse -mouseshape 
+mouse_dec +mouse_gpm -mouse_jsbterm +mouse_netterm -mouse_sysmouse 
+mouse_xterm +mouse_urxvt +multi_byte +multi_lang -mzscheme +netbeans_intg 
+path_extra -perl +persistent_undo +postscript +printer +profile -python 
-python3 +quickfix +reltime +rightleft -ruby +scrollbind +signs +smartindent 
-sniff +startuptime +statusline -sun_workshop +syntax +tag_binary 
+tag_old_static -tag_any_white -tcl +terminfo +termresponse +textobjects +title
 -toolbar +user_commands +vertsplit +virtualedit +visual +visualextra +viminfo 
+vreplace +wildignore +wildmenu +windows +writebackup -X11 -xfontset -xim -xsmp
 -xterm_clipboard -xterm_save 
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -Wl,-z,relro -Wl,--as-needed -o vim       -lm -ltinfo -lnsl  -lselinux -lacl -lattr -lgpm
```

**Comment by evandrocoan** [comment]
Also, Debian 9 does not come with curl, then, the installer is fail too. But it has wget.

**Comment by janlazo** [comment]
If you source the file directly (ie. `source ~/.vim/autoload/plug.vim', does `plug#begin` work?

```vim
if v:version < 704
  source ~/.vim/autoload/plug.vim
endif
call plug#begin('~/.vim/plugged')
```

**Comment by evandrocoan** [comment]
I do not have access to the debian 7 machine right now. Next week I will have it back.

**Comment by evandrocoan** [comment]
I just tested it and worked without adding the `source ~/.vim/autoload/plug.vim`.

Then, I added `Plug 'itchyny/lightline.vim'` and it installed the plugin.

**Comment by evandrocoan** [comment]
Now I know why it did not worked on the first time last week, but worked today.

Last week I was using my old script which did not supported `wget` when `curl` is not available. By default `Debian 7` does not come with `curl` installed. Then, it was not downloading the `plug.vim` file, then the `plug#begin()` was failing because no commands were loaded.

Therefore, I am reopening this ticket to update the wiki adding support to `wget` when `curl` is not available. This is the script I am using:
```vim
if empty(glob('~/.vim/autoload/plug.vim'))
  let s:downloadurl = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  let s:destinedirectory = $HOME . "/.vim/autoload"
  let s:destinefile = s:destinedirectory . "/plug.vim"

  if !isdirectory(s:destinedirectory)
    call mkdir(s:destinedirectory, "p")
  endif

  if executable("curl")
    silent execute '!curl --output ' . s:destinefile .
        \ ' --create-dirs --location --fail --silent ' . s:downloadurl

  else
    silent execute '!wget --output-document ' . s:destinefile .
        \ ' --no-host-directories --force-directories --quiet ' . s:downloadurl
  endif

  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
```
Just few notes:
1. The line `let s:destinedirectory = $HOME . "/.vim/autoload"` cannot end with a trailing slash  i.e., `"/.vim/autoload/"`. Because on older versions of vim as `7.3` (default on Debian 7), does not recognize the path. A trailing slash is only accepted by newer versions of vim as 8.
1. The call to `mkdir(s:destinedirectory, "p")` is required because `wget` does not create the directory structure as `curl`. Then, I added the `mkdir` call to both versions because it does not hurt.

**Comment by junegunn** [comment]
Thanks for the suggestion. But the code snippet on the page isn't supposed to provide a robust solution that should work on all environments. (What if `wget` is also unavailable? etc.) Rather, it is there to give the users some idea of how they can automate their setup using VimScript. So I want to keep it as short and straightforward as it is now.
