### ISSUE TITLE
PlugUpdate fails in Windows powershell

### ISSUE THREAD

**Issue by flotisable** [junegunn/vim-plug#895]
When I use the default shell (**cmd.exe**) to update plugins, everything is fine.
Using **powershell** as the shell fails to update all the plugins.
I have simplified my vimrc to be
```
set runtimepath+=~/.vim,~/.vim/after
set packpath+=~/.vim

set shell=powershell
set shellcmdflag=-NoLogo\ -NoProfile\ -ExecutionPolicy\ RemoteSigned\ -Command
set shellpipe=\|
set shellredir=\|\ Out-File\ -Encoding\ UTF8
set shellquote=
set shellxquote=

call plug#begin( '~/.vim/plugged' )

  Plug 'scrooloose/nerdtree'
  Plug 'majutsushi/tagbar'
  Plug 'octol/vim-cpp-enhanced-highlight'

call plug#end()

```

Here's the error message of ```PlugUpdate```
<img width="840" alt="註解 2019-10-17 104121" src="https://user-images.githubusercontent.com/22073008/67136573-ade5ae80-f25a-11e9-82f5-fa46d8781992.png">
<img width="627" alt="註解 2019-10-19 102336" src="https://user-images.githubusercontent.com/22073008/67136575-b2aa6280-f25a-11e9-913b-005264997701.png">

As a side note,
my system language is Traditional Chinese,
not sure if it is related.

------------------------------

```
NVIM v0.4.2
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [x] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by flotisable** [comment]
@janlazo new issue created. https://github.com/junegunn/vim-plug/issues/884#issuecomment-543398369

**Comment by janlazo** [comment]
> my system language is Traditional Chinese

What's the output of `git --version`?

**Comment by flotisable** [comment]
the output of ```git --version``` is
```
git version 2.23.0.windows.1
```
and I find that this issue may be related to #876 since it is also caused by powershell.

**Comment by janlazo** [comment]
With powershell as `&shell`, `echo system('git --version')` includes the UTF8 bom.

**Comment by janlazo** [comment]
@flotisable nvim needs `.exe` for `system`. Perhaps suggest this in the issue tracker if you want the convenience of omitting `.exe`.

```vim
set shell=powershell.exe
```

The error does not happen anymore.

**Comment by flotisable** [comment]
@janlazo Ok, adding the extension ```.exe``` solves the problem, thanks.
