### ISSUE TITLE
Cygwin filepaths and git (windows build) on Cygwin Vim

### ISSUE THREAD

**Issue by evandrocoan** [junegunn/vim-plug#896]
After searching I found https://github.com/junegunn/vim-plug/issues/556 fatal: destination path '/home/...' already exists and is not an empty

Now I see the message `destination path already exists and is not an empty directory` is probably coming from git. The git version on my system path is `git version 2.21.0.windows.1`, and it is the one I want to use. I do not see why it should break a vim package manager.

Installed Cygwin and vim. Now when I run `:PlugInstall` for the second time (after installing everything successfully first) it says `destination path already exists and is not an empty directory`. But it should say something like `All up to date` because everything is already installed and up-to-date:
```
  1 Updated. Elapsed time: 0.218449 sec.
  2 [xxx]
  3
  4 - Finishing ... Done!
  5 x vim-hug-neovim-rpc:
  6     fatal: destination path '/home/Professional/.vim/plugged/vim-hug-neovim-rpc' already exists and is not an empty directory.
  7 x deoplete.nvim:
  8     fatal: destination path '/home/Professional/.vim/plugged/deoplete.nvim' already exists and is not an empty directory.
  9 x nvim-yarp:
 10     fatal: destination path '/home/Professional/.vim/plugged/nvim-yarp' already exists and is not an empty directory.
```
![image](https://user-images.githubusercontent.com/5332158/67152302-82d67b80-f2a9-11e9-822a-e2c0de85d464.png)

___
**.vimrc**
```vim
" https://github.com/junegunn/vim-plug/wiki/tips
" https://github.com/junegunn/vim-plug/issues/894
if v:version >= 740

  if empty(glob('~/.vim/autoload/plug.vim'))
    let s:downloadurl = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    let s:destinedirectory = $HOME . "/.vim/autoload/"
    let s:destinefile = s:destinedirectory . "plug.vim"

    if !isdirectory(s:destinedirectory)
      call mkdir(s:destinedirectory, "p")
    endif

    if executable("curl")
      silent execute '!curl --output ' . s:destinefile .
          \ ' --create-dirs --location --fail --silent ' . s:downloadurl

    else
      silent execute '!wget --output-document ' . s:destinefile .
          \ ' --no-host-directories --force-directories --quiet ' . s:downloadurl
    endif

    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
  endif

  " https://github.com/junegunn/vim-plug
  "
  " Specify a directory for plugins
  " - For Neovim: stdpath('data') . '/plugged'
  " - Avoid using standard Vim directory names like 'plugin'
  call plug#begin('~/.vim/plugged')

  if v:version >= 800

    if has('nvim')
      Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
    else
      Plug 'Shougo/deoplete.nvim'
      Plug 'roxma/nvim-yarp'
      Plug 'roxma/vim-hug-neovim-rpc'
    endif
    let g:deoplete#enable_at_startup = 1

  endif

  " Initialize plugin system
  call plug#end()

endif
```

- Type:
    - [X] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [X] Windows
- Vim:
    - [X] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

```
$ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar  4 2018 23:29:48)
Included patches: 1-1567
Modified by <cygwin@cygwin.com>
Compiled by <cygwin@cygwin.com>
Huge version without GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               +perl/dyn          +vertsplit
+clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           +python/dyn        +vreplace
+conceal           +linebreak         +python3/dyn       +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       +lua/dyn           +ruby/dyn          -X11
+dialog_con        +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             -xim
+digraphs          +modify_fname      +smartindent       -xpm
-dnd               +mouse             +startuptime       -xsmp
-ebcdic            -mouseshape        +statusline        -xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              -mouse_gpm         +syntax
+ex_extra          -mouse_jsbterm     +tag_binary
+extra_search      +mouse_netterm     +tag_old_static
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim80"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -ggdb -O2 -pipe -Wall -Werror=format-security -fstack-protector-strong --param=ssp-buffer-size=4 -fdebug-prefix-map=/usr/src/ports/vim/vim-8.0.1567-1.x86_64/build=/usr/src/debug/vim-8.0.1567-1 -fdebug-prefix-map=/usr/src/ports/vim/vim-8.0.1567-1.x86_64/src/vim-8.0.1567=/usr/src/debug/vim-8.0.1567-1 -fstack-protector-strong -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -fstack-protector  -L/usr/local/lib -Wl,--as-needed -o vim.exe        -lm -lelf -lnsl    -lncursesw -liconv -lacl -lattr -lintl   -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -fstack-protector-strong  -L/usr/lib/perl5/5.26/x86_64-cygwin-threads/CORE -lperl -lpthread -ldl -lcrypt
```

**Comment by yugr** [comment]
This is likely due to Windows git failing to understand Cygwin's path conventions (`~/.vim`, etc.). At least in Vundle this can be workarounded by converting path to mixed style:
```
  let vimdir = '~/.vim/plugged'
  if has('win32unix')
    " Use mixed path on Cygwin so that Windows git works
    let vimdir = substitute(system('cygpath -m ' . vimdir), '\n\+$', '', '')
  endif
  call vundle#begin(vimdir)
```
but same trick does not work for me in `plug#begin`.

**Comment by janlazo** [comment]
Is your vimrc is in `~/.vim/vimrc` where `~` is equal to `$HOME` in Vim or `%USERPROFILE%` in cmd.exe?

```vim
" in vimrc
let s:base_dir = expand('<sfile>:p:h')
call plug#begin(s:base_dir . '/plugged')
```

Does this help?

**Comment by yugr** [comment]
> Is your vimrc is in ~/.vim/vimrc

Actually it's ~/.vimrc.

> call plug#begin(s:base_dir . '/plugged')

I assume you meant '/.vim/plugged'?

> Does this help

Nope, `s:base_dir` is just `/home/iuriig` which is unsuitable for Windows git. But even converting it to `$(cygpath -m /home/iuriig)` (i.e. `C:/cygwin64/home/iuriig`) does not solve the issue.

**Comment by evandrocoan** [comment]
I managed to make `vim-plug` to clone the repositories by changing this line:
https://github.com/junegunn/vim-plug/blob/master/plug.vim#L128

To:
```vim
  let g:plug_home = 'F:\\Cygwin\\home\\Professional\\.vim\\plugged'
```

Then, after successfull cloning the repositories on `.vim\\plugged`, it throw this error:
```
[Plugins]                                                                       [No Name]
Error detected while processing function <SNR>8_install[1]..<SNR>8_update_impl[110]..<SNR>8_job_cb[4]..<SNR>8_job_exit_cb[4]..<SNR>8_tick[6]..<SNR>8_update_fi
nish[56]..<SNR>8_finish[9]..plug#end[89]..<SNR>8_reload_plugins[2]..<SNR>8_load_plugin[1]..<SNR>8_source:
line    4:
E484: Can't open file F:CygwinhomeProfessional.vimplugged/deoplete.nvim/plugin/deoplete.vim
```

**Comment by janlazo** [comment]
Is your request for vim-plug to support both windows and cygwin builds of git?

`s:source` should use `expand` (or use `fnamemodify`) on the filepath before sourcing the file.

**Comment by yugr** [comment]
@evandrocoan Can you try with `'F:/Cygwin/home/Professional/.vim/plugged'`?

**Comment by yugr** [comment]
@janlazo Basically yes, the request is to support using Windows git with Cygwin vim. For this vim-plug can either convert paths internally (from Cygwin's Unix-style format like `/home/user/.vim/plugged` to `c:/cygwin64/home/user/.vim/plugged`, this is achieved by `cygpath` program) or be careful to preserve path given to `plug#begin` (i.e. not let it be converted to Unix-style along the way). I can try to come up with a patch if this feature is considered useful for the project.

**Comment by evandrocoan** [comment]
@yugr, yes. It worked 100% and now I got no errors anymore from `vim-plug`.

@janlazo, yes. As @yugr just showed:
1. The path should be in the form `C:/Users/Home/.vim/plugged` for git for Windows. 
1. The path should be in the form `/home/.vim/plugged` for git for Cygiwn.

**Comment by evandrocoan** [comment]
@janlazo, by running this:
```shell
fixedpath="$(cygpath --mixed --absolute "$HOME/.vim/plugged")"
```
You would get `F:/Cygwin/home/Professional/.vim/plugged` in the variable `fixedpath`

**Comment by yugr** [comment]
@evandrocoan Great.

So basically all that's needed is for vim-plug to preserve path given to `plug#begin` (as `C:/Users/home/user/.vim/plugged`) without converting it to Unix style (`/home/user/.vim/plugged`). Currently this conversion happens in `fnamemodify` at start of `plug#begin`:
```
function! plug#begin(...)
  if a:0 > 0
    let s:plug_home_org = a:1
    let home = s:path(fnamemodify(expand(a:1), ':p'))
```

**Comment by evandrocoan** [comment]
> o basically all that's needed is for vim-plug to preserve path given to `plug#begin` (as `C:/Users/home/user/.vim/plugged`) without converting it to Unix style (`/home/user/.vim/plugged`). Currently this conversion happens in `fnamemodify` at start of `plug#begin`:

@yugr, now I see why I got a lot of trouble while trying to make it work. I was setting the path, but it was being converted back.

Also, do not forget, that this patch should only be used if the the program `cygpath` available. For example:
```
if executable("cygpath")
  if has('win32unix')
    " Use mixed path on Cygwin so that Windows git works
    let home = substitute(system('cygpath -m ' . home), '\n\+$', '', '')
  endif
endif
```

**Comment by yugr** [comment]
"Also, do not forget, that this patch should only be used if the the program cygpath available" - try but `win32unix` guarantees that we are in Cygwin and `cygpath` is always available there.

**Comment by evandrocoan** [comment]
Thanks. I did not known that. 

Just another thing then. I also just tested, and git for Cygwin does not accept absolute paths as `F:/Cygwin/home/Professional/.vim/plugged`. Then, the if checking should cover this:
```vim
if has('win32unix')
  if "is git for Windows?"
    " Use mixed path on Cygwin so that Windows git works
    let home = substitute(system('cygpath -m ' . home), '\n\+$', '', '')
  endif
endif
```

**Comment by yugr** [comment]
"I also just tested, and git for Cygwin does not accept absolute paths" - can you check if your Cygwin git is recent enough? I think I had issues with older version but current 2.21.0 accepts mixed paths (I believe this was fixed in upstream git ~ 1 year ago).

**Comment by evandrocoan** [comment]
My Cygwin git version is `git version 2.17.0`

**Comment by yugr** [comment]
Yes, that one probly lacks support for mixed paths... So we can either ask users to use the latest version or indeed add a check like you suggested above (I'm not sure how to discern Windows vs Cygwin git though, just checking absolute path is not reliable).

**Comment by evandrocoan** [comment]
1. We could create a setting like `let g:git_executable = '/usr/bin/git2.exe'` pointing the path to the git. On this case, I could point to my git for Cygwin, which I renamed to `git2.exe`.
1. Or we could create a setting called `let g:git_for_windows = true` and run the path conversion you suggested.

I think the option 2 would be better because it would not require a git for Cygwin to be installed.

**Comment by yugr** [comment]
2 sounds reasonable to me. Let's wait for comments from maintainers then.

**Comment by janlazo** [comment]
`git --version` includes `windows` if it's the windows build. Did that change in recent cygwin/windows builds?

**Comment by evandrocoan** [comment]
I also noticed that on my computer. I got installed 3 versions of git for Windows, and I ran `git --version` in each one of them:
```
git version 2.21.0.windows.1
git version 2.19.0.rc0.windows.1
git version 2.16.2.windows.1
```

They all seem to have `windows` on the version name.

**Comment by yugr** [comment]
Ah, nice.

**Comment by yugr** [comment]
Unfortunately Mingw gits do not include the ".windows." suffix.

**Comment by evandrocoan** [comment]
Then, we go with the setting. But you could go with both. The Mingw users would have to set the setting while the git for Windows users would not.

**Comment by yugr** [comment]
Proposed patch:
```
diff --git a/README.md b/README.md
index bad081d..fcd6096 100644
--- a/README.md
+++ b/README.md
@@ -169,15 +169,16 @@ Reload .vimrc and `:PlugInstall` to install plugins.
 
 ### Global options
 
-| Flag                | Default                           | Description                                            |
-| ------------------- | --------------------------------- | ------------------------------------------------------ |
-| `g:plug_threads`    | 16                                | Default number of threads to use                       |
-| `g:plug_timeout`    | 60                                | Time limit of each task in seconds (*Ruby & Python*)   |
-| `g:plug_retries`    | 2                                 | Number of retries in case of timeout (*Ruby & Python*) |
-| `g:plug_shallow`    | 1                                 | Use shallow clone                                      |
-| `g:plug_window`     | `vertical topleft new`            | Command to open plug window                            |
-| `g:plug_pwindow`    | `above 12new`                     | Command to open preview window in `PlugDiff`           |
-| `g:plug_url_format` | `https://git::@github.com/%s.git` | `printf` format to build repo URL (Only applies to the subsequent `Plug` commands) |
+| Flag                 | Default                           | Description                                            |
+| -------------------- | --------------------------------- | ------------------------------------------------------ |
+| `g:plug_threads`     | 16                                | Default number of threads to use                       |
+| `g:plug_timeout`     | 60                                | Time limit of each task in seconds (*Ruby & Python*)   |
+| `g:plug_retries`     | 2                                 | Number of retries in case of timeout (*Ruby & Python*) |
+| `g:plug_shallow`     | 1                                 | Use shallow clone                                      |
+| `g:plug_window`      | `vertical topleft new`            | Command to open plug window                            |
+| `g:plug_windows_git` | 0                                 | Use Windows-style paths when calling git on Cygwin     |
+| `g:plug_pwindow`     | `above 12new`                     | Command to open preview window in `PlugDiff`           |
+| `g:plug_url_format`  | `https://git::@github.com/%s.git` | `printf` format to build repo URL (Only applies to the subsequent `Plug` commands) |
 
 
 ### Keybindings
diff --git a/doc/plug.txt b/doc/plug.txt
index 3740e03..e292b94 100644
--- a/doc/plug.txt
+++ b/doc/plug.txt
@@ -223,7 +223,7 @@ Reload .vimrc and `:PlugInstall` to install plugins.
                                                            *plug-global-options*
 
      *g:plug_threads* *g:plug_timeout* *g:plug_retries* *g:plug_shallow* *g:plug_window*
-                                              *g:plug_pwindow* *g:plug_url_format*
+                            g:plug_windows_git*g:plug_pwindow* *g:plug_url_format*
 
  --------------------+-----------------------------------+-----------------------------------------------------------------------------------
  Flag                | Default                           | Description                                                                       ~
@@ -233,6 +233,7 @@ Reload .vimrc and `:PlugInstall` to install plugins.
   `g:plug_retries`     | 2                                 | Number of retries in case of timeout (Ruby & Python)
   `g:plug_shallow`     | 1                                 | Use shallow clone
   `g:plug_window`      |  `verticalΓÇçtopleftΓÇçnew`             | Command to open plug window
+  `g:plug_windows_git` |  0                                | Use Windows-style paths when calling git on Cygwin
   `g:plug_pwindow`     |  `aboveΓÇç12new`                      | Command to open preview window in  `PlugDiff`
   `g:plug_url_format`  |  `https://git::@github.com/%s.git`  |  `printf`  format to build repo URL (Only applies to the subsequent  `Plug`  commands)
  --------------------+-----------------------------------+-----------------------------------------------------------------------------------
diff --git a/plug.vim b/plug.vim
index ab0e082..3483cf9 100644
--- a/plug.vim
+++ b/plug.vim
@@ -124,6 +124,10 @@ function! plug#begin(...)
   if fnamemodify(home, ':t') ==# 'plugin' && fnamemodify(home, ':h') ==# s:first_rtp
     return s:err('Invalid plug home. '.home.' is a standard Vim runtime path and is not allowed.')
   endif
+  if has('win32unix') && exists('g:plug_windows_git') && g:plug_windows_git
+    " Use mixed path fot Windows gits on Cygwin
+    let home = substitute(system('cygpath -m ' . home), '\n\+$', '', '')
+  endif
 
   let g:plug_home = home
   let g:plugs = {}
```

**Comment by evandrocoan** [comment]
@yugr, you can write like this to get syntax highlighting:
````
```patch
diff --git a/README.md b/README.md
index bad081d..fcd6096 100644
--- a/README.md
+++ b/README.md
@@ -169,15 +169,16 @@ Reload .vimrc and `:PlugInstall` to install plugins.
...
```
````

Example:
```patch
diff --git a/README.md b/README.md
index bad081d..fcd6096 100644
--- a/README.md
+++ b/README.md
@@ -169,15 +169,16 @@ Reload .vimrc and `:PlugInstall` to install plugins.
...
```

But may be a pull request would be easier?

**Comment by junegunn** [comment]
Adding an option is usually the last thing I'd choose to do :)

`fnamemodify` is not called if `g:plug_home` is already defined, so does this approach help?

```vim
let g:plug_home = '... YOUR_PATH ...'
call plug#begin()
```

I know this is not ideal, but I'm just trying to see if there's a way to work around the issue without adding an extra option that few users would need.

**Comment by yugr** [comment]
Works for me:
```
let g:plug_home='~/.vim/plugged'
if has('win32unix')
  " Use mixed path on Cygwin so that Windows/MinGW git works
  let g:plug_home = substitute(system('cygpath -m ' . g:plug_home), '\n\+$', '', '')
endif
```
I'm personally fine with the workaround.

**Comment by evandrocoan** [comment]
@yugr, how can I make it work? I tried putting 
```vim
let g:plug_home='~/.vim/plugged'
if has('win32unix')
  " Use mixed path on Cygwin so that Windows/MinGW git works
  let g:plug_home = substitute(system('cygpath -m ' . g:plug_home), '\n\+$', '', '')
endif
call plug#begin(g:plug_home)
```
on `.vimrc` but it did not work. I also tried putting it on `plug.vim`:
```vim
File: .vim/autoload/plug.vim
124:   if fnamemodify(home, ':t') ==# 'plugin' && fnamemodify(home, ':h') ==# s:first_rtp
125:     return s:err('Invalid plug home. '.home.' is a standard Vim runtime path and is not allowed.')
126:   endif
127:   if has('win32unix')
128:     " Use mixed path on Cygwin so that Windows/MinGW git works
129:     let g:plug_home = substitute(system('cygpath -m ' . g:plug_home), '\n\+$', '', '')
130:   endif
131: 
132:   let g:plug_home = home
133:   let g:plugs = {}
134:   let g:plugs_order = []
135:   let s:triggers = {}
136: 
```

But it did not work neither.

I also tried your first solution:
```vim
File: .vim/autoload/plug.vim
124:   if fnamemodify(home, ':t') ==# 'plugin' && fnamemodify(home, ':h') ==# s:first_rtp
125:     return s:err('Invalid plug home. '.home.' is a standard Vim runtime path and is not allowed.')
126:   endif
127: 
128:   if has('win32unix') && exists('g:plug_windows_git') && g:plug_windows_git
129:     " Use mixed path fot Windows gits on Cygwin
130:     let home = substitute(system('cygpath -m ' . home), '\n\+$', '', '')
131:     echo 'home: ' . home
132:   endif
133: 
134:   echo 'exists(g:plug_windows_git): ' . exists('g:plug_windows_git')
135:   echo 'plug_windows_git: ' . g:plug_windows_git
136:   echo 'win32unix: ' . has('win32unix')
137:   echo 'all: ' . has('win32unix') && exists('g:plug_windows_git') && g:plug_windows_git
138:   echo 'home: ' . home
139: 
140:   let g:plug_home = home
141:   let g:plugs = {}
142:   let g:plugs_order = []
143:   let s:triggers = {}
```

But when running it, your main if `has('win32unix') && exists('g:plug_windows_git') && g:plug_windows_git` evaluates to false. See the echo logs result:
```
$ vim
exists(g:plug_windows_git): 1
plug_windows_git: true
win32unix: 1
0
home: /home/Professional/.vim/plugged
```

If I remove the if `has('win32unix') && exists('g:plug_windows_git') && g:plug_windows_git` and directly put `let home = substitute(system('cygpath -m ' . home), '\n\+$', '', '')` to always run, then, it works and install the plugins correctly:
```vim
$ vim
exists(g:plug_windows_git): 1
plug_windows_git: true
win32unix: 1
0
home: F:/Cygwin/home/Professional/.vim/plugged
  1 Installing plugins (3/3)                                                   |
  2 [===]                                                                      |~
  3                                                                            |~
  4 - Finishing ...                                                            |~
  5 - vim-hug-neovim-rpc: remote: Total 40 (delta 17), reused 19 (delta 6), pac|~
  6 - deoplete.nvim: Resolving deltas: 100% (358/358), done.                   |~
  7 - nvim-yarp: remote: Total 27 (delta 7), reused 13 (delta 2), pack-reused 0|~
```

**Comment by janlazo** [comment]
@evandrocoan You can omit the argument to `plug#begin` if you preset `g:plug_home`.

**Comment by janlazo** [comment]
```diff
diff --git a/autoload/plug.vim b/autoload/plug.vim
index ab0e082..a920fe4 100644
--- a/autoload/plug.vim
+++ b/autoload/plug.vim
@@ -124,6 +124,12 @@ function! plug#begin(...)
   if fnamemodify(home, ':t') ==# 'plugin' && fnamemodify(home, ':h') ==# s:first_rtp
     return s:err('Invalid plug home. '.home.' is a standard Vim runtime path and is not allowed.')
   endif
+  if has('win32unix')
+  \ && executable('cygpath')
+  \ && executable('git')
+  \ && split(system('git --version'))[2] =~# 'windows'
+    let home = split(system('cygpath -m ' . home), "\n")[0]
+  endif
 
   let g:plug_home = home
   let g:plugs = {}
```

**Comment by yugr** [comment]
@evandrocoan Here's what worked for me: https://github.com/yugr/scripts-and-dotfiles/blob/c11ae36c9108e48fa1c0633b1a3f27c8a3a6873f/vimrc#L5

@janlazo You are right, I didn't check MinGW.

**Comment by yugr** [comment]
@janlazo I think explicitly checking for "windows" is undesirable because it'll break calling MinGW git from Cygwin vim (check for `git` presense can thus also be removed).

**Comment by janlazo** [comment]
@yugr How does it break MinGW git?

**Comment by yugr** [comment]
@janlazo MinGW `git --version` does not include the "windows" suffix so `cygpath` won't be executed when we call MinGW git from Cygwin. This means that Cygwin's paths (`/home/User/.vim/plugged`, `/cygdrive/c/my-special-vim-dir`, etc.) would be massaged before passing them to MinGW git and will cause aborts similar to ones above.

**Comment by janlazo** [comment]
How about unconditionally running cygpath on cygwin/mingw/msys2 Vim? Convert back if needed (ie. Vim's `&rtp`).

**Comment by evandrocoan** [comment]
Thanks! This worked for me:
```vim
  if has('win32unix')
  \ && executable('cygpath')
  \ && executable('git')
  \ && split(system('git --version'))[2] =~# 'windows'
    " Use mixed path on Cygwin so that Windows git works
    let g:plug_home = substitute(system('cygpath -m ' . g:plug_home), '\n\+$', '', '')
  endif

  " https://github.com/junegunn/vim-plug
  call plug#begin()
```

> MinGW `git --version` does not include the "windows" suffix

I think the MinGW version of git should accept paths on the form `/home/user/`. At least, the Cygwin version of git, accepts it.

**Comment by yugr** [comment]
@evandrocoan 

> I think the MinGW version of git should accept paths on the form /home/user/.

Even if it does accept them, MinGW's `/home` would be different from Cygwin's `/home`. And in any case it won't accept less trivial Cygwin's paths like `/cygdrive/c/my-non-standard-vim-dir`.

**Comment by evandrocoan** [comment]
> Even if it does accept them, MinGW's `/home` would be different from Cygwin's `/home`.

I did not understood this. If I ask to MinGW to open the `/home`, it will open `/home`, even if it is on `C:\Users\`. While Cygwin has its own `/home` directory which is under its installation root. I think MinGw could do the same.

> in any case it won't accept less trivial Cygwin's paths like `/cygdrive/c/my-non-standard-vim-dir`.

Indeed, MinGw will not accept Cygwin paths like `/cygdrive/c/home`. But paths like `~/.vim` should be acceptable. We just need to know how a vim built for MinGw will expand the path `~/.vim`. If it is a vim built for MinGw, then, it should correctly expand it to `/c/mingw/home/.vim`. If it is not, than, we are all doomed.

**Comment by yugr** [comment]
> If I ask to MinGW to open the /home, it will open /home

MinGW's `~/.vim` is `C:/msys64/home/User/.vim`, Cygwin's is `C:\cygwin64\home\User\.vim`. When we reference `~/.vim` in Cygwin vim, we mean the latter but MinGW git will (incorrectly) treat it as the former.

> We just need to know how a vim built for MinGw will expand the path ~/.vim

I guess I disagree here, in my opinion is code should work for any proper location of `.vim` (i.e. not just `~/.vim`).

**Comment by yugr** [comment]
@janlazo What's your opinion on this? We have a workaround now but I'm not sure how to integrate it into vim-plug without a flag (i.e. how to reliably determine if particualr `git` version needs converted paths).

**Comment by janlazo** [comment]
@yugr It looks like a lot of work to cover all the edge cases that using a flag here is a misleading. I suggest adding the workaround and a link to this issue in the [wiki](https://github.com/junegunn/vim-plug/wiki) and suggest the user to use the full path for all filepaths passed to vim-plug, preferably with `cygpath`, before running `:PlugInstall`. The path would be of the form, `/c/Users/foo/.vim`, instead of the emulated path, `/home/foo/.vim`. This is easier to debug and to convert to the Windows path without `cygpath` in `$PATH`.

I don't use cygwin/mingw/msys2 nowadays (aside from installing/debugging windows git itself) because I use scoop for package management and use ConEmu + powershell for my terminal needs. It's a low priority for me to work on this so this issue will remain open.

**Comment by yugr** [comment]
> The path would be of the form, /c/Users/foo/.vim

You mean c:/Users/foo/.vim ?

I agree to the rest except that I don't see why keep it open at all (rather than closing as low-prio).

**Comment by janlazo** [comment]
I use `+win32unix` vim sometimes, mostly when debugging tickets or helping other devs. Open a PR and I'll review and merge if it handles all the edge cases.

> You mean c:/Users/foo/.vim ?

No. I meant `/c/Users/foo/.vim` because the user should avoid windows paths within mingw/cygwin vim. This should be an internal implementation detail.

**Comment by yugr** [comment]
> No. I meant /c/Users/foo/.vim because the user should avoid windows paths within mingw/cygwin vim

But `/c/Users/foo/.vim` is not a valid Cygwin path (it's MinGW-only syntax, whereas `c:/Users/foo/.vim` is supported by all Cygwin/MinGW tools and Windows git), let alone that it points to a non-Cygwin plugins directory (Cygwin's one would be `/cygdrive/c/cygwin64/home/foo/.vim`).

**Comment by janlazo** [comment]
I reposted https://github.com/junegunn/vim-plug/issues/896#issuecomment-545693522 at https://github.com/junegunn/vim-plug/wiki/faq#filepath-issues-with-cygwinmingw-vim-and-windows-git. Can anyone test if the workaround is enough when a plugin has a custom `'dir'` or `rtp`?

```vim
" Plugin outside ~/.vim/plugged with post-update hook
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }

" Plugin options
Plug 'nsf/gocode', { 'tag': 'v.20150303', 'rtp': 'vim' }
```
Use `cygpath` with `dir` if needed and I'll update the wiki entry.`

**Comment by evandrocoan** [comment]
When I ran the command, the `gocode` plugin was installed successfully. But the `.fzf` did not.
```
Updated. Elapsed time: 17.072030 sec.
[====x]

- Finishing ... Done!
x fzf:
    sh: line 0: cd: /home/Professional/.fzf/: No such file or directory
- deoplete.nvim: Already installed
- gocode: Resolving deltas: 100% (2052/2052), done.
- vim-hug-neovim-rpc: Already installed
- nvim-yarp: Already installed
```

**Comment by janlazo** [comment]
https://github.com/junegunn/vim-plug/wiki/faq#filepath-issues-with-cygwinmingw-vim-and-windows-git
Updated to mention 'dir' key for plugins that need a custom directory. Requires cygpath as well based on  https://github.com/junegunn/vim-plug/issues/896

**Comment by DZITZGH** [comment]
After I try the [solution](https://github.com/junegunn/vim-plug/wiki/faq#filepath-issues-with-cygwinmingw-vim-and-windows-git),the cgywin64 show the wrong:
```
E115: Missing quote:  '/.vim/plugged'
E116: Invalid arguments for function s:fix_plug_path($HOME . '/.vim/plugged)
```
I don't know what happened.
![cywin64](https://user-images.githubusercontent.com/51281158/153814445-ae64e47a-9786-4502-bdaf-f245f1c66749.png)
![wrong](https://user-images.githubusercontent.com/51281158/153814477-9cee3968-8afb-4995-8094-c998efb0d584.png)

**Comment by evandrocoan** [comment]
It is missing a quote here (and on the official example)
![image](https://user-images.githubusercontent.com/5332158/153863359-ac2bb669-8deb-4b93-82af-a3d8019ad90d.png)

**Comment by DZITZGH** [comment]
Thanks for your answer.
It's OK now.

**Comment by junegunn** [comment]
Thanks, I fixed the wiki page.

https://github.com/junegunn/vim-plug/wiki/faq/_compare/790042dd4333cd8c0d8d310268e052e4db99fe72...5059231dbfeb00ddd273facb2031e0b4bd3a36a3

**Comment by RivenSkaye** [comment]
I can't find many mentions of specifically MSYS2 envs, except when mentioned in conjunction with cygwin.
I'm _only_ running an MSYS2 environment on my system, for which `/home` is a shared folder for all envs. It's also my main CLI env on Windows and I've not had any issues with paths except for a few edge cases. A workaround is needed for VSCode & forks to play nice with unix-style paths on Windows, some applications written with no regard for the env have some problems (Nu shell's autocomplete just breaks entirely) but I've not had any problems with git or vim itself.

Would a workaround like this still be required for clean MSYS2 envs? Or is more testing needed to see if/how this could work? In the latter case, I'd gladly be the guinea pig
