### ISSUE TITLE
vim-plug + syntastic,  ^[[>1;95;0c

### ISSUE THREAD

**Issue by chenpanhong** [junegunn/vim-plug#897]
vim-plug + syntastic, when `let g:syntastic_check_on_open = 1`, php file header appears `^[[>1;95;0c`
------------------------------

### vim version:  8.1.1
```
" vim-plug
call plug#begin('~/.vim/plugged')

Plug 'vim-syntastic/syntastic'
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1 

call plug#end()
```
![image](https://user-images.githubusercontent.com/4003546/67377982-187b4f00-f5b9-11e9-8650-11dd5ab77f4c.png)

```
" vundle
filetype off                  " required
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'Syntastic'
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1

call vundle#end()            " required
filetype plugin indent on    " required
```
![image](https://user-images.githubusercontent.com/4003546/67378585-12d23900-f5ba-11e9-92e5-88f383d0acdc.png)

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
`Plug 'vim-syntastic/syntastic'` is not equivalent to `Plugin 'Syntastic'`; the latter points to `vim-scripts/syntastic`. So, you're comparing different versions of the plugin here.

**Comment by chenpanhong** [comment]
> `Plug 'vim-syntastic/syntastic'` is not equivalent to `Plugin 'Syntastic'`; the latter points to `vim-scripts/syntastic`. So, you're comparing different versions of the plugin here.

Get it, tks
