### ISSUE TITLE
Unable to install colorscheme properly

### ISSUE THREAD

**Issue by ismailhkose** [junegunn/vim-plug#902]
Explain the problem here ...
This is a great tool I can install most of the plugins faster and convenient way. However, it doesn't seem working or supporting to VIM install color schema.

To install onedark schema; I followed the following steps.

I add this description `"Plug 'joshdick/onedark.vim'`, and source it then install it. I also add the colorshema name in .vimrc file. Once it's installed, I see that color schema is activated and seems working. Once I exit VIM, and open another file, I see that VIM can't find the color schema.

`E185: Cannot find color scheme 'onedark'`
------------------------------

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 06 2019 17:31:41)
```

- Type:
    - [ x] Bug
    - [ x] Enhancement
    - [ x] Feature Request
    - [ x] Question
- OS:
    - [ x] Linux (Ubuntu 18.04)
- Vim:
    - [ x] Terminal Vim

**Comment by janlazo** [comment]
Provide a minimal vimrc like the following:

```vim
call plug#begin('~/.vim/plugged')
Plug 'joshdick/onedark.vim'
call plug#end()
colorscheme onedark
```

**Comment by junegunn** [comment]
Probably related: https://github.com/junegunn/vim-plug/wiki/faq#im-getting-cannot-find-color-scheme--does-vim-plug-support-color-schemes

**Comment by ismailhkose** [comment]
> Provide a minimal vimrc like the following:
> 
> ```viml
> call plug#begin('~/.vim/plugged')
> Plug 'joshdick/onedark.vim'
> call plug#end()
> colorscheme onedark
> ```
> 
> If you have a vimrc like the following, then `onedark` should always load if the other Vim you opened uses the same vimrc.

right, it needs to be loaded every time using the following command.
> ```viml
> call plug#begin('~/.vim/plugged')
> Plug 'joshdick/onedark.vim'
> call plug#end()
> colorscheme onedark
> ```

**Comment by annesteenbeek** [comment]
On a fresh install in a docker container (Ubuntu 20.04), using 
```
call plug#begin('~/.vim/plugged')
Plug 'joshdick/onedark.vim'
call plug#end()
colorscheme onedark
```

I still get the error:
```
E185: Cannot find color scheme 'onedark'
```

This is really annoying as it suddenly requires user input to type ENTER when using ansible.

**Comment by janlazo** [comment]
`silent! colorscheme onedark`.

**Comment by annesteenbeek** [comment]
Thanks, yeah, that solved it. 
However, it's still just supressing the error, not solving the issue. Or is this expected behavior?

**Comment by janlazo** [comment]
Yes, it is expected on a fresh install. `PlugInstall` must run first before `colorscheme onedark` to avoid the error on a new machine.

**Comment by laraconda** [comment]
I have the same issue but `PlugInstall` does not solve the problem. 
This is my .vimrc file. As you can see, `colorscheme` runs after `call plug#end()`:
```
call plug#begin('~/.vim/plugged')
Plug 'dracula/vim', {'as': 'dracula'}
Plug 'andreasvc/vim-256noir', {'as': 'noir'}
Plug 'zacanger/angr.vim', {'as': 'angr'}
Plug 'tyrannicaltoucan/vim-deep-space', {'as': 'deepspace'}
Plug 'yorickpeterse/happy_hacking.vim', {'as': 'happyhacking'}
Plug 'joshdick/onedark.vim'
call plug#end()

filetype on
syntax on
colorscheme onedark

...
```

All of those plugins are themes and none work, all of them throw `E185: Cannot find color scheme [name]`

**Comment by EmreDogann** [comment]
For me, the issue was enabling syntax highlighting (`syntax on`) _before_ loading the theme inside `plug#begin / plug#end`.

For reference, this was the error message I was getting:
```
Error detected while processing .dotfiles/vim/.vimrc[145]../usr/share/vim/vim82/syntax/syntax.vim[19]../usr/share/vim/vim82/syntax/synload.vim:
line   19:
E185: Cannot find color scheme 'catppuccin_macchiato'
``` 

Putting `syntax on` after `plug#end()` seemed to resolve the error.

**Comment by paulzhn** [comment]
For those noob to vim like me, Plug 'navarasu/onedark.nvim' is only used for neovim but not vim :)
