### ISSUE TITLE
ERROR "invalid uri ^" when runing PlugStatus

### ISSUE THREAD

**Issue by CodingCloud9527** [junegunn/vim-plug#908]
Explain the problem here ...
When i running PlugStatus, I always get a error:
Finished. 1 error(s).
[=]

x auto-pairs:
    Invalid URI: ^A
    Expected:    https://git::@github.com/jiangmiao/auto-pairs.git
    PlugClean required.

and i see the variable `result` in https://github.com/junegunn/vim-plug/blob/68fef9c2fd9d4a21b500cc2249b6711a71c6fb9f/plug.vim#L2075 is Irregular letters and symbols , just like "^DA^GHF^D^DGA........."
------------------------------

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 15 2019 23:02:52)
MS-Windows 64-bit console version
包含补丁: 1-2301
```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [x] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by janlazo** [comment]
`git --version` output?
Is `sed` executable in `PATH`?

**Comment by CodingCloud9527** [comment]
hrer is `git --version` output:
`git version 2.24.0.windows.2`
I retry after put `sed` executable in `PATH`,The problem still appears


> `git --version` output?
> Is `sed` executable in `PATH`?

**Comment by janlazo** [comment]
Do you have `set encoding=utf-8' for your console vimrc config and, if you have gvim, does it happen with the same (g)vimrc?

**Comment by CodingCloud9527** [comment]
I have `set encoding=utf-8`, and my gvim has the same problem

**Comment by mattn** [comment]
I god same. I figured out the cause of problem. If using sed provided from msys2 or cygwin, it result from `chcp ^| sed "s/[^0-9]//gp"` is not expected string.

**Comment by mattn** [comment]
This is a patch to fix this.
```diff
diff --git a/plug.vim b/plug.vim
index 02fac8d..b945417 100644
--- a/plug.vim
+++ b/plug.vim
@@ -353,16 +353,11 @@ if s:is_win
 
   " Copied from fzf
   function! s:wrap_cmds(cmds)
-    let use_chcp = executable('sed')
-    return map([
-      \ '@echo off',
-      \ 'setlocal enabledelayedexpansion']
-    \ + (use_chcp ? [
-      \ 'for /f "usebackq" %%a in (`chcp ^| sed "s/[^0-9]//gp"`) do set origchcp=%%a',
-      \ 'chcp 65001 > nul'] : [])
-    \ + (type(a:cmds) == type([]) ? a:cmds : [a:cmds])
-    \ + (use_chcp ? ['chcp !origchcp! > nul'] : [])
-    \ + ['endlocal'],
+    let cp = libcallnr('kernel32.dll', 'GetACP', 0)
+    return map(
+	\ ['@echo off', 'chcp 65001 > nul'] +
+    \ (type(a:cmds) == type([]) ? a:cmds : [a:cmds]) +
+    \ [printf('chcp %d > nul', cp)],
     \ 'v:val."\r"')
   endfunction
 ```

But I suggest to not do "chcp 65001". "chcp 65001" break behavior  on cmd.exe

![screenshot](https://user-images.githubusercontent.com/10111/69809156-7f30ff80-122c-11ea-932f-c04d9042668d.gif)

**Comment by janlazo** [comment]
@mattn Thanks for the patch and the demo of the bug. `chcp` was meant for utf-8 characters but I can see now that it makes matters worse for other locales. It's not required at all for most operations in vim-plug. I can remove it entirely and propose to do the same for fzf but I need an alternative to display unicode characters, at least for en-US locale, when using cmd.exe. Updating the FAQ with a workaround would suffice if there's no easy to do this.

**Comment by mattn** [comment]
FYI: https://dev.to/mattn/please-stop-hack-chcp-65001-27db
