### ISSUE TITLE
[Haiku] Download location wrong

### ISSUE THREAD

**Issue by bitigchi** [junegunn/vim-plug#925]
Hello,

On Haiku, application settings/data are located under ~/config/settings. vim-plug should use ~/config/settings/vim/plugged to download plug-in data. Currently ~/.vim/ is only used by vim-plug. This does not affect use, but would be nice to have.

- Type:
    - [ ] Bug
    - [x] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [x] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [x] GVim
    - [ ] Neovim

Thank you!

**Comment by janlazo** [comment]
`~/.vim/` is a suggestion. You can use `call plug#begin('~/config/settings/vim/plugged')`.

**Comment by bitigchi** [comment]
Thanks for the suggestion and example code, but I ended up using `if has('haiku')`. Example code just downloaded the plugins to ~/bundle, although the solution seems much more elegant. I'd love to use this in some way.

**Comment by janlazo** [comment]
It would go to `~/bundle` if your vimrc is exactly at the home directory. `:h vimrc` shows alternate locations for the vimrc such that the example code will work. It doesn't mention Haiku so perhaps you can create a new issue at https://github.com/vim/vim to document Haiku's config directory for Vim.
