### ISSUE TITLE
Run plug commands without entering vim/neovim

### ISSUE THREAD

**Issue by ChausseBenjamin** [junegunn/vim-plug#929]
Are there shell commands for Vim plug?
This way you wouldn't need to open vim, update plugins, quit vim, and reenter vim.
You could just do for example:
```
vim-plug update && nvim
```
Also, this would allow vim-plug be run from scripts (for example, update vim plugins once per week using crontabs)
------------------------------

- Type:
    - [ ] Bug
    - [X] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [X] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [X] Neovim

**Comment by janlazo** [comment]
```sh
nvim --headless -c PlugInstall -c 'autocmd VimEnter * qa'
nvim
```
