### ISSUE TITLE
Add plugin from bitbucket?

### ISSUE THREAD

**Issue by dgruzd** [junegunn/vim-plug#93]
Trying to add https://bitbucket.org/ns9tks/vim-fuzzyfinder/ but https and ssh formats fails, how can i add this plugin with vim-plug?

**Comment by timfeirg** [comment]
can I install plugins from vim.org? for example http://www.vim.org/scripts/script.php?script_id=2654

**Comment by junegunn** [comment]
@timfeirg You can use this mirror: https://github.com/vim-scripts/Arduino-syntax-file

**Comment by timfeirg** [comment]
@junegunn thanks, didn't mean to let you google things for me though, I now see that almost every vim plugin is either hosted on github or has a mirror on github, so that vim-plug no need to support installing from vim.org or bitbucket repos.
