### ISSUE TITLE
Clean up test/fixtures/ after test run

### ISSUE THREAD

**Issue by henrebotha** [junegunn/vim-plug#932]
After invoking `test/run`, a directory `test/fixtures` is left behind. Can we just clean this up after a test run? Is there a reason to leave it there after a failed run (e.g. to debug)?

------------------------------

- Type:
    - [ ] Bug
    - [x] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
Thanks for pointing it out. Yeah, as you said, it can be helpful when we need to debug failing test cases. It's not that important these days though since vim-plug has been pretty stable for a while. I'll just keep the script leave it as we already have `fixtures` in `.gitignore`.
