### ISSUE TITLE
Fatal: Invalid reference when Install/Update Plugin

### ISSUE THREAD

**Issue by minhchu** [junegunn/vim-plug#933]
I'm using [space-vim](https://github.com/liuchengxu/space-vim).
I'm having these errors when installed or updated plugin.
How can I know where this bug come from and how to fix it ?
Thank you :heart: 

![Screenshot from 2020-02-06 10-56-31](https://user-images.githubusercontent.com/14136809/73905161-fe981a80-48d0-11ea-87b3-cc297556f908.png)

------------------------------

```
NVIM v0.4.3
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissi
ng-prototypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci
/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neo
vim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-9a287301-34f2-4b86-92e3-462594f51f36

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info

```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by janlazo** [comment]
I am not a space-vim user so I need more context on the config and a confirmation from space-vim devs that the bug is on vim-plug.

https://stackoverflow.com/questions/26855990/is-there-a-way-to-do-git-checkout-and-force-the-argument-to-be-interpreted-a

That's likely a git error and it may happen when updating plugins if vim-plug does not fetch everything beforehand.

**Comment by douglarek** [comment]
Maybe same issue as this https://github.com/junegunn/vim-plug/pull/930

**Comment by douglarek** [comment]
@minhchu space-vim master has fixed this issue, just have a try!

**Comment by minhchu** [comment]
Thank guys :heart:

Vào 13:25, Th 3, 18 thg 2, 2020 Jan Edmund Lazo <notifications@github.com>
đã viết:
