### ISSUE TITLE
Git options need to be configurable

### ISSUE THREAD

**Issue by alerque** [junegunn/vim-plug#940]
At the moment vim-plug simply executes `git ...` on the shell using whatever path is supplied by the OS. The vast majority of the time this will work fine, but it does not allow any flexibility with git options. The config that gets used ends up being the user's global git config `~/.gitconfig` and there is no way to change that.

I have an issue with this because by global config has these problematic values (among many others):

```ini
[fetch]
	fsckobjects = true
[transfer]
	fsckObjects = true
[receive]
	fsckObjects = true
```

Sadly _many many_ vim plugin repositories in the wild have corrupted root commits (invalid timestamp formats). (@bronson you [know what you did](https://github.com/preservim/nerdtree/issues/1052#issuecomment-569960609)!) The upshot of this is that my global vim config –which is important to me for other reasons– gets in the way of being able to run `:PlugInstall` or `:PlugUpdate`. First I have to comment out those entries, then run vim-plug stuff, then restore them.

I would like an option in vim-plug to pass parameters like `-o fetch.fsck-objects=false` to git when invoked by vim-plugn. Ideally this would be on a per-plugin basis so I could just mark the corrupted plugins for this treatment, but an option to change the base `git` executable to an alias that includes these options would also work.

**Comment by brainplot** [comment]
Git [reads an environment variable](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables) called `GIT_CONFIG_NOSYSTEM`, which disables the global options.
If you want that to be applied only to vim you can use a shim command like this
```sh
#!/usr/bin/env sh

export GIT_CONFIG_NOSYSTEM=1

nvim "$@"
```
Put this somewhere in your `PATH` and call it `nvim` (or `vim` in case you're using vim)

**Comment by junegunn** [comment]
> export GIT_CONFIG_NOSYSTEM=1

You can put it in your vim configuration file like so

```vim
let $GIT_CONFIG_NOSYSTEM = 1
```

**Comment by alerque** [comment]
@junegunn Thanks for that tip, that's really nifty. However...

Isn't that going to mess up all uses of `git` spawned from inside my editor? For example I make heavy use of Fugitive, and I don't want that environment variable set for those invocations!

Is there a way to isolate this to just the vim-plug run? Could I set it, run the plugin stuff, then unset it after `call plug#end()`?

**Comment by junegunn** [comment]
Well, you could write a set of wrapper commands that do exactly that using plain VimScript; 1. Write a command that sets the variables and runs PlugSomething, 2. and set up an autocmd that unsets ihe variable when vim-plug window is closed.
