### ISSUE TITLE
Support a list of commands for `do`

### ISSUE THREAD

**Issue by alexgenco** [junegunn/vim-plug#944]
Would it be possible to support a list of commands for `do`? I'm trying to do this:

```vim
Plug 'mattn/vim-lsp-settings', {'do': [
      \ ':LspInstallServer bash',
      \ ':LspInstallServer ruby',
      \ ':LspInstallServer rust',
      \ ':LspInstallServer vim',
      \ ]}
```

This fails with `Invalid hook type` when I try to install. Or is there another recommended way to do this?
Thanks!

------------------------------

```
NVIM v0.4.3
```

- Type:
    - [ ] Bug
    - [x] Enhancement
    - [x] Feature Request
    - [x] Question
- OS:
    - [x] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [x] GVim
    - [x] Neovim

**Comment by janlazo** [comment]
https://github.com/junegunn/vim-plug/blob/master/README.md#post-update-hooks

```vim
function InstallLspServers()
   LspInstallServer bash
   LspInstallServer ruby
   LspInstallServer rust
   LspInstallServer vim
endfunction

Plug 'mattn/vim-lsp-settings', {'do': function('InstallLspServers')}
```

**Comment by alexgenco** [comment]
Ah thanks!
