### ISSUE TITLE
README about neovim and vimplug path needs improvement

### ISSUE THREAD

**Issue by rahulbal** [junegunn/vim-plug#946]
Every time I install neovim and vim plug (read every time I install linux) I keep spending about half an hour wrestling with the environment to find out the root cause of Not an editor command :PluginInstall.
Only to punch myself in the face about 40 minutes into it remembering I need to do `cp -r .local/share/nvim/site/autoload .config/nvim/`

Could this be clarified in the README. Please and thank you.

------------------------------

```

```

- Type:
    - [ ] Bug
    - [x] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
The suggested path is correct (it was suggested by the maintainer of Neovim) and you don't need to copy it to another location.

- https://github.com/junegunn/vim-plug/issues/559
- `:help xdg`

```
:scriptnames
  1: ~/.config/nvim/init.vim
  2: ~/.local/share/nvim/site/autoload/plug.vim
  ...
```

**Comment by rahulbal** [comment]
[log.txt](https://github.com/junegunn/vim-plug/files/4342203/log.txt)
this does indeed seem to be the case from the first few lines of the logs post fix. Unfortunately I am currently unable to flash a machine to repro the issue.
You may close this bug for now, but I will keep a tab on this for the future.

Regards,
Rahul
