### ISSUE TITLE
Not enough installation information for Windows users?

### ISSUE THREAD

**Issue by in2Rafi** [junegunn/vim-plug#947]
Explain the problem here ...

------------------------------
 
Hi! I have copied.vim file into autoload folder of my win 7 normal vim. Now which path I should use in the .vimrc file?

**Comment by janlazo** [comment]
Your question is not specific enough. If you placed `plug.vim` in `~/vimfiles/autoload/plug.vim`, you should be able to run `call plug#begin()` in `~/vimfiles/vimrc`.
