### ISSUE TITLE
Helpful install command from outside vim

### ISSUE THREAD

**Issue by juanibiapina** [junegunn/vim-plug#948]
```
nvim -es -u ~/.config/nvim/init.vim +PlugInstall +qa
```

Maybe there's a place for this in the wiki?

**Comment by janlazo** [comment]
https://github.com/junegunn/vim-plug/wiki/tips

The tip should apply for both Vim and Neovim.

**Comment by juanibiapina** [comment]
This also works:

```
vim -es -i NONE -u ~/.config/nvim/init.vim +PlugInstall +qa
```

**Comment by janlazo** [comment]
Done https://github.com/junegunn/vim-plug/wiki/tips#install-plugins-on-the-command-line
