### ISSUE TITLE
Making the ":PlugInstall" step more obvious

### ISSUE THREAD

**Issue by xolio** [junegunn/vim-plug#952]
Hi, I'm a new Vim user, and while I did see your :PlugInstall instruction in the README.md file, it did not immediately occur to me that the :PlugInstall command is to be run from within (Neo)Vim. I just assumed that it was something to be handled inside the (g)init.vim file(s). 

This confusion resulted in some wasted hours, and I'm filing a ticket to see if the language about :PlugInstall could be made more explicit on the front page. For example, perhaps the following could be an acceptable replacement: "Reload .vimrc and run the :PlugInstall command from within (Neo)Vim to install plugins."

------------------------------

```

```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
Thanks, but it feels like stating the obvious and making the instruction unnecessarily verbose. If those steps were to be added to the configuration file, we would have said so. "Reloading .vimrc" inside .vimrc/init.vim doesn't make sense, so the users naturally understand that the instruction is not about the configuration file. I'll think about that. Thanks for the suggestion.

**Comment by xolio** [comment]
Yeah, the replacement candidate that I submitted is badly worded. I was more trying to draw a distinction between the language found on the tutorial page, which read <code>Now run :PlugInstall to install the plugins</code>, and the one found on the front page, which read <code>Reload .vimrc and :PlugInstall to install plugins</code>. Somehow the former registered completely while the latter didn't. 

However, my experience is most likely an outlier and not to be taken seriously. After all, had I been more at ease and less snappy, I would've also deduced the obvious. In any event, thanks for making this plugin; it's been a great aid.

**Comment by junegunn** [comment]
That's a good point, indeed. How about this?

> Now restart Vim (or reload `.vimrc`), and you can run `:PlugInstall` to install plugins.

**Comment by xolio** [comment]
That would work great, and sorry to have troubled you over this. Upon further reflection, I also don't find much issue with the original any more, so please only make the switch if you find it preferable to do so. I did mean it when I indicated that I probably overreacted yesterday to my own failure at reading comprehension. Lastly, thanks very much again for making the tool; I'm now happily chugging along with Vim.
