### ISSUE TITLE
Way to force on-demand plugins to load, e.g. before invoking :help

### ISSUE THREAD

**Issue by dbarnett** [junegunn/vim-plug#953]
Is there a way to force all lazy on-demand plugins to go ahead and load now?

I've found that using a lot of on-demand loading breaks some vim facilities like `:help` that scan through all plugins on `runtimepath`, since it won't see on-demand plugins until you trigger their loading conditions. If I could force all plugins to load before searching `:help` I'd at least have a simple manual workaround for that.

**Comment by Shougo** [comment]
Unfortunately, Vim/neovim does not have the hook.
So you should request it in development team.

**Comment by dbarnett** [comment]
Right, I'm aware there's not a hook to run code right before help is searched. (That's what you mean, right?)

Regardless, there are times you want to ensure everything is loaded, e.g. for troubleshooting. Could there be a way to force loading everything? Could be something like `:Plug!` with no args, which is pretty guessable and not already taken.

**Comment by Shougo** [comment]
> That's what you mean, right?

Yes.  You can check the all hooks in `:help autocommand-events`.

**Comment by Shougo** [comment]
> Regardless, there are times you want to ensure everything is loaded, e.g. for troubleshooting. Could there be a way to force loading everything? Could be something like :Plug! with no args, which is pretty guessable and not already taken.

`plug#load({name})` API exists.
I think you can load all plugins.
Note: You can loop by `g:plugs` variable.

**Comment by dbarnett** [comment]
Okay, convenience aside, I found this recipe to do it:
```vim
call plug#load(keys(g:plugs))
```

For instance, I can wrap fzf.vim's `:Helptags` with a workaround command like this to load all plugins first:
```vim
:command Ht call plug#load(keys(g:plugs)) | Helptags
```

If it's alright, I'd like to add a note about it into `:h plug-on-demand-loading-of-plugins`.

**Comment by janlazo** [comment]
Add the note at https://github.com/junegunn/vim-plug/wiki/tips. I can add it for you if you can post the full note in one post.

**Comment by dbarnett** [comment]
Could the instructions for plug-on-demand-loading-of-plugins reference that, though? Would the wiki be the right place for that if so?

**Comment by junegunn** [comment]
We no longer recommend users to use on-demand loading feature (https://github.com/junegunn/vim-plug/wiki/faq#when-should-i-use-on-or-for-option), and I'd like to avoid talking about it too much on the front page.

**Comment by dbarnett** [comment]
Ah, good to know! Would it be okay to add a link to those specifics in `:help plug-on-demand-loading-of-plugins` to avoid people trying to set it up and wasting time on troubleshooting cases like that?

**Comment by reportaman** [comment]
@junegunn Hey, I just used the on-demand loading feature to reduce my (neovim, vim) startup time by ~300ms! now its (215ms,115ms) respectively. It's a nifty feature to have. Can you please elaborate what you mean by "On-demand loading should only be used as the last resort. It is basically a hacky workaround and is not always guaranteed to work." Anyway a caution would be worth mentioning on the front page. IMO not all plugins are mindfully written, so we will always need some way of not loading them. Would a hard `:source` or `:source!`. As an idea, if you can add a boolean flag that can be set before source to bypass the conditional loading feature, then people can by side effects of conditional loading.
