### ISSUE TITLE
Must install plug-in each time for it to work

### ISSUE THREAD

**Issue by pmdulaney** [junegunn/vim-plug#958]
Explain the problem here ...
I'm using MacVm and for now I'm just trying to get the lightline plug-in to work.

Here is a reproducible sequence:

1. Start MacVim. [No Name] window appears without the lightline embellishments on the statusline, even though I have already installed lightline.

2. I type in   :PlugInstall
The screen is split into left and right halves. The following text is in the left half:

Updated. Elapsed time: 0.08003 sec.
[=]

- Finishing ... Done!
- lightline.vim: Already installed

So it tells me that lightline.vim is already installed, but I still have no statusline embellishments.

3. I enter :q to close the left window
The lightline plug-in now takes effect!

4. In the MacVim File menu I select New Window. A new window appears, but lightline is not activated --  though it is still activated in the first window.

I am new to all this and there is probably something very simple that I'm missing -- I just don't know what...

------------------------------

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  3 2020 12:05:00)
macOS version
Included patches: 1-319
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ X] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ X] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ X] GVim
    - [ ] Neovim

**Comment by pmdulaney** [comment]
I was not able to get vim-plug to work, but I have found a workaround.

On this page:

https://vi.stackexchange.com/questions/613/how-do-i-install-a-plugin-in-vim-vi

In the third answer, entitled "Vim 8+ / Neovim" (which means the answer is applicable to (Vim 8+ OR Neovim) not (Vim 8+ AND Neovim)), Michael Kropat writes:

> Version 8 introduces a new packages mechanism that largely replaces the need for existing plugin managers (pathogen, vim-plug, vundle, etc.) at the time of writing (2017)

See the above link for details. But since I want lightline to work from the get-go (as opposed to on demand) the following few lines of command line entries did the trick:


     (1) $ cd
     (2) $ mkdir -p ~/.vim/pack/bundle/start
     (3) $ cd ~/.vim/pack/bundle/start
     (4) $ git clone https://github.com/itchyny/lightline.vim

Notes on the above which assume you know very little.

The $ is the Mac terminal command line prompt; type just the stuff to the right of the $ and hit return at the end of each line. I have added the numbers (1), (2), (3), and (4) just to make it easier to refer to these command line commands.

(1) - The cd command ("change directory") puts you in your home directory. Since ~ represents the home directory "cd ~" would have done the same thing.

(2) - mkdir creates a new directory. The -p switch tells mkdir to also create any intermediate directories as needed. So if you already had a ~/.vim directory, (2) would create
          ~/.vim/pack
          ~/.vim/pack/bundle
          ~/.vim/pack/bundle/start
From what I understand, "pack" is a keyword in the sense that that first directory beneath .vim MUST be named "pack". On the other hand, the next directory down is called "bundle" only by convention; we could have called it anything we liked. "start" is again a keyword; plugins placed in this directory are loaded at vim startup.

(3) This cd command puts us where we want the plugin code to go. (The mkdir command created the new directory but does not move us out of the home directory.)

(4) The git clone command downloads the plugin code from the appropriate repository at github.com

For me the above worked like a charm. I did not have to reboot my Mac -- I just needed to close MacVim and then open it again.

**Comment by junegunn** [comment]
I believe there was a configuration mistake. Two possibilities.
1. Not putting `call plug#end()` after Plug statements.
2. Putting the code in `.gvimrc` rather than in `.vimrc`.

**Comment by pmdulaney** [comment]
Hi Junegunn Choi,

I did in fact put the code in .gvimrc rather .vimrc. I use MacVim and based
on my testing MacVim doesn't read the .vimrc file.

I also see that you marked the issue a duplicate. I apologize for that -- I
didn't see a similar issue.

Thanks for your response,

Paul Dulaney
Los Angeles, Calif

**Comment by junegunn** [comment]
Macvim or (gvim) does read .vimrc. A detailed explanation can be found here: https://github.com/junegunn/vim-plug/issues/540
