### ISSUE TITLE
Implement an easy way to say "not_for:"

### ISSUE THREAD

**Issue by nerdyness** [junegunn/vim-plug#960]
Hello,

I use [coc.nvim](https://github.com/neoclide/coc.nvim) however for Python, the [coc-python](https://github.com/neoclide/coc-python) extension is rather limited. I like the [jedi-vim](https://github.com/davidhalter/jedi-vim) plugin much better, however the two don't like to be loaded at the same time.

Now, as a work around I have the following:
```
  Plug 'neoclide/coc.nvim', { 'branch': 'release', 'for': ['typescript','yaml','json'] }
  Plug 'davidhalter/jedi-vim', { 'for': 'python' }
```

But, instead of listing all the languages for coc.nvim (the above isn't an exhaustive list), it'd be much simpler if I could say `{ 'not_for': 'python' }` or `{ 'for': '!python' }` or similar.

Maybe there already is a better way to do this and I just don't know. Any ideas would be greatly appreciated.

------------------------------

```
:version
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototyp
es -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HA
S_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/build/config -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-134
03-1or2rj3/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neo
vim-20191107-13403-1or2rj3/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/build/include
Compiled by brew@Mojave.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.3/share/nvim"

Run :checkhealth for more info
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [x] Feature Request
    - [x] Question
- OS:
    - [x] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by kappa** [comment]
Probably a dup of #928

**Comment by junegunn** [comment]
@kappa Thanks.

Closing as wontfix. See my previous comment in #928 
- https://github.com/junegunn/vim-plug/issues/928#issuecomment-619471207

**Comment by nerdyness** [comment]
My bad, I searched for this but clearly missed #928 - thanks for the pointer 👍
