### ISSUE TITLE
Pre-delete hook

### ISSUE THREAD

**Issue by romikabi** [junegunn/vim-plug#968]
At the moment post-update hook `do` exists to run additional installation steps.
I propose pre-delete hook `uninstall` to run steps before removing plugin files.
```bash
Plug 'rkitover/vimpager', { 'do': 'make install', 'uninstall': 'make uninstall' }
```

Since the `Plug` line should be removed in order to delete a plugin, value in `uninstall` could probably be stored on `PlugInstall` or `PlugUpdate` and called when `PlugClean` is going to remove plugin files.

**Comment by junegunn** [comment]
Thanks for the suggestion, but I don't think we are going to implement the option because there are very few plugins that need extra uninstallation steps. And as you have pointed out, it is not trivial to implement the option because of the way PlugClean works.
