### ISSUE TITLE
echofunc install issue (plugin directory is under another directory)

### ISSUE THREAD

**Issue by KyleJeong** [junegunn/vim-plug#972]
Explain the problem here ...
I added "mbbill/echofunc", but the plugin file is located in ./after/plugin.
So I think the plugin is not initiated properly because of that.
Can you tell me how can I handle this case?
------------------------------

```

```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [v] Question
- OS:
    - [ ] All/Other
    - [v] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [v] GVim
    - [ ] Neovim

**Comment by janlazo** [comment]
https://github.com/junegunn/vim-plug#plug-options

You can set `rtp` to the subdirectory, relative to the plugin's root directory.
