### ISSUE TITLE
How to use Plug to load plugin from a git branch

### ISSUE THREAD

**Issue by winksaville** [junegunn/vim-plug#973]
I looked for an email list or discussion group to ask this question but didn't see one. Nor did I see an answer in the FAQ, sorry in advance if I missed it.

Explanation of the problem as the subject line is cryptic. (Note: I also know that I could solve this particular problem by adding [filetype specific settings](https://stackoverflow.com/questions/1562633/setting-vim-whitespace-preferences-by-filetype), but I thought it better to do it in the plugin directly.)

Anyway, I added vim-openscad to my .vimrc:
```
Plug 'https://github.com/sirtaj/vim-openscad.git'
```
And that worked no problem, but I then wanted to tweak the plugin so I forked it, created a branch, commited the change and pushed it to my fork. So now I want to be able to specify a branch in the Plug url, first guess:
```
Plug 'https://github.com/winksaville/vim-openscad.git -b Deefault-to-2-space-tabstops'
```
But that fails:
```
x vim-openscad.git -b Default-to-2-space-tabstops:
    Cloning into '/home/wink/.vim/plugged/vim-openscad.git -b Default-to-2-space-tabstops'...
    fatal: unable to access 'https://github.com/winksaville/vim-openscad.git -b Default-to-2-space-tabstops/': The requested URL returned error: 400
```
I then tried giving it the "tree":
```
Plug 'https://github.com/winksaville/vim-openscad/tree/Default-to-2-space-tabstops'
```
But that fails too:
```
x Default-to-2-space-tabstops:
    Cloning into '/home/wink/.vim/plugged/Default-to-2-space-tabstops'...
    fatal: repository 'https://github.com/winksaville/vim-openscad/tree/Default-to-2-space-tabstops/' not found
```
I can't imagine I'm the first person to want to install a from a branch, I would guess that plugin developers would want to do this all the time. Anyway, I do like vim-plug, THANKS!

**Comment by junegunn** [comment]
You can use `branch` option, see
- https://github.com/junegunn/vim-plug#example
- https://github.com/junegunn/vim-plug#plug-options


```vim
Plug 'winksaville/vim-openscad', { 'branch': 'Default-to-2-space-tabstops' }
```
