### ISSUE TITLE
Vim does find help file

### ISSUE THREAD

**Issue by Melkster** [junegunn/vim-plug#974]
I cannot access any help page for vim-plug. `:help plug.txt`, `:help plug` or `:help plug-toc` do not work.

vim-plug was installed using `curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim`

------------------------------

```vim
:version
NVIM v0.5.0-540-g60c581b35
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -
Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -
DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim
/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/buil
d/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-495222b7-1d16-4b36-9b3a-9e6dacb42070

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"
```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [x] GVim
    - [x] Neovim

**Comment by janlazo** [comment]
Download the help file at https://github.com/junegunn/vim-plug/blob/master/doc/plug.txt and put it in the  `doc/` subdirectory, relative to one of the directories in `&runtimepath` such as `~/.vim/`.
Alternative, add `Plug 'junegunn/vim-plug'` in your vimrc and run `PlugInstall` to let vim-plug handle this.

**Comment by Melkster** [comment]
@janlazo Thanks that makes sense! Adding `Plug 'junegunn/vim-plug'` worked as you said :)
