### ISSUE TITLE
should i remove the call block after plug install?

### ISSUE THREAD

**Issue by therajat08** [junegunn/vim-plug#975]
Explain the problem here ...

------------------------------

```

```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [x] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by junegunn** [comment]
No.
