### ISSUE TITLE
Typo in the deployment procedure on Neovim for Windows 

### ISSUE THREAD

**Issue by Adnn** [junegunn/vim-plug#976]
There seems to be a small error in the procedure of the **README.md**

```
md ~\AppData\Local\nvim\autoload
$uri = 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
(New-Object Net.WebClient).DownloadFile(
  $uri,
  $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath(
    "~\AppData\Local\nvim-data\site\autoload\plug.vim"
  )
)
```

The first line should read:

`md ~\AppData\Local\nvim-data\site\autoload` (otherwise it is not matching the download destination)

Thank you for the awesome project!

- Type:
    - [X] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [X] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [X] Neovim

**Comment by junegunn** [comment]
Fixed, thanks!
