### ISSUE TITLE
[question] How can I update plug with crontab?

### ISSUE THREAD

**Issue by fcying** [junegunn/vim-plug#980]
I'm try use `vim +'PlugUpdate --sync' +'qa'`

but it get a error
```
Jun 19 12:52:01 lin CRON[11766]: (fcying) CMD (vim +'PlugUpdate --sync' +'qa')
Jun 19 12:52:05 lin vim: *** err
Jun 19 12:52:05 lin vim: checking tty name failed
Jun 19 12:52:05 lin vim: *** err
```

**Comment by janlazo** [comment]
Try running it in a shell and redirecting the stdout and stderr to some file.

**Comment by fcying** [comment]
crontab
```
~/script/soft_update.sh > ~/script/update.log 2>&1
```
soft_update.sh
```
vim +'PlugUpdate --sync' +'qa'
```
output
```
Vim: Warning: Output is not to a terminal
Vim: Warning: Input is not from a terminal
 4 * vim-session: Updating ...50lsp-settings: Updating ...
  5 * vim-session: Updating ...4bbye: Updating ...        lsp-settings: Updating ...
  6 * vim-session: Updating ...33surround: Updating ...bbye: Updating ...        lsp-settings: Updating ...
  7 * vim-session: Updating ...28emmet-vim: Updating ...   surround: Updating ...bbye: Updating ...        lsp-settings: Updating ...
Vim: Error reading input, exiting...
```
And the plugin not update.

I try use `vim -c "PlugUpdate --sync" -c "qa" > ~/script/update.log 2>&1` is the same log.

**Comment by janlazo** [comment]
https://github.com/janlazo/dotvim8/blob/master/.ci/script.sh

`:help -E`
`:help -s`

**Comment by fcying** [comment]
I try use a mini_vimrc only use vim-plug and one plugin.
both `vim -u ~/mini_vimrc +"PlugUpdate --sync" +"qa"` and `vim -Es -u ~/mini_vimrc +"PlugUpdate --sync" +"qa"` work fine....
full vimrc can't update plugin also, `vim -Es -u ~/.vim/vimrc +"PlugUpdate --sync" +"qa"`

I will find out which config make error, thanks for your help.

**Comment by fcying** [comment]
`set lazyredraw` make the error.
When I set this in my vimrc. `vim -u ~/mini_vimrc +"PlugUpdate --sync" +"qa"`,
will get a error `Vim: Error reading input, exiting...` and update failed.
disable this set when update from crontab will be fine.
