### ISSUE TITLE
error code

### ISSUE THREAD

**Issue by v-gq** [junegunn/vim-plug#981]
Explain the problem here ...
I an error code occurred after reinstalling vim

![2020-06-20 04-38-52 的屏幕截图](https://user-images.githubusercontent.com/66294501/85178222-8a26ac80-b2b0-11ea-9b26-43ef4f37e2f8.png)
![2020-06-20 04-31-43 的屏幕截图](https://user-images.githubusercontent.com/66294501/85178236-94e14180-b2b0-11ea-9197-22ac463a785b.png)

------------------------------

```

```

- Type:
    - [ *] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [* ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ *] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by janlazo** [comment]
I don't see the error code. Is your vim using unicode encoding? If not, can you enable it and update your screenshots?
