### ISSUE TITLE
autocmd User plugin-name not called

### ISSUE THREAD

**Issue by entropitor** [junegunn/vim-plug#984]
I cannot get the `autocmd User` to actually fire by vim-plug, should those be defined before plug#begin, after?

Whenever I call `doautocmd` myself, it works fine so I'm thinking somethings is either wrong in my setup or there is a bug in vim-plug
------------------------------

```
NVIM v0.5.0-dcd6cf5f3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORT
IFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-par
ameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototype
s -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnosti
cs-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS
_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20200610-344
84-bauodz/build/config -I/tmp/neovim-20200610-34484-bauodz/src -I/usr/local/inc
lude -I/tmp/neovim-20200610-34484-bauodz/deps-build/include -I/Library/Develope
r/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -I/usr/local/opt/gettext/in
clude -I/tmp/neovim-20200610-34484-bauodz/build/src/nvim/auto -I/tmp/neovim-202
00610-34484-bauodz/build/include
```

- Type:
    - [x] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
The `autocmd` is fired only when you set up `on` or `for` option. Please note that we no longer recommend using them.

https://github.com/junegunn/vim-plug/wiki/faq#when-should-i-use-on-or-for-option
