### ISSUE TITLE
Plugins installed but not autoload in vim 

### ISSUE THREAD

**Issue by Sideris35** [junegunn/vim-plug#987]
Hi, i have a problem with vim-plug with vim8.
I have two plugins in .vimrc: 

```
call plug#begin('~/.vim/plugged')

Plug 'itchyny/lightline.vim'
Plug 'neomake/neomake'

call plug#end()
```

Plugins are correctly install but when i edit a new files they don't load automatically.
Do you have an idea please ?

Thanks

- Type:
    - [X] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [X] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [X] Terminal Vim
    - [ ] GVim
    - [ ] Neovim

**Comment by Soj447** [comment]
@Sideris35, seems like the problem is with lightline plugin, other stuff loads normally for me.

**Comment by Sideris35** [comment]
I installed neovim it's works
