### ISSUE TITLE
Newbie Having Issues With vimrc & Plug

### ISSUE THREAD

**Issue by JSchu72** [junegunn/vim-plug#988]
Hello,

First of all, thank you for creating vim-plug, I look forward to using it to setup the TidalCycles plugin on my Raspberry Pi 4.

Secondly, I'm totally new to Vim, relatively new to GitHub, and let's face it, new enough to Linux that I still have to look up commands for that, for Vim, etc.---newbie, but everybody starts somewhere right? :)

I'm trying to set up vim-plug on stock-standard Raspian Buster, using AFAIK the latest, standard version of Vim.

I followed the instructions on the page, downloaded plug.vim using the following command:

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

I then checked the ~/.vim/autoload/ directory to make sure the file was there--it was.

I then went into vimrc and added the following lines:

call plug#begin()
call plug#end()

And went out of vimrc using the :x command.

When I went back into vimrc, I got the following error:

Error detected while processing /usr/share/vim/vimrc:
line    1:
E117: Unknown function: plug#begin
line    2:
E117: Unknown function: plug#end

I followed the directions to my understanding but can't figure out what I may have done wrong?

Any help would be appreciated, thank you for looking at my email and designing this :)

--Jon

**Comment by janlazo** [comment]
1. You are using a version of Vim that disabled the `+autoload` feature. Check the output of `:version`. You can force vim to load vim-plug by running `runtime autoload/vim-plug.vim` or `source /path/to/.vim/autoload/vim-plug.vim`.
2. Vim cannot find vim-plug from the `autoload/` directory relative to your configuration directory. It is set in `runtimepath` option. You can check via `set runtimepath?`.
3. Read/write permission issues.
4. System vimrc ran first and did something. You can force Vim to load only your vimrc by running `vim -u ~/.vim/vimrc` where the file passed to `-u` is the filepath of your vimrc.

**Comment by janlazo** [comment]
Reopen this issue and post a status update if you still have problems.

**Comment by Beanocean** [comment]
> 1. You are using a version of Vim that disabled the `+autoload` feature. Check the output of `:version`. You can force vim to load vim-plug by running `runtime autoload/vim-plug.vim` or `source /path/to/.vim/autoload/vim-plug.vim`.
> 2. Vim cannot find vim-plug from the `autoload/` directory relative to your configuration directory. It is set in `runtimepath` option. You can check via `set runtimepath?`.
> 3. Read/write permission issues.
> 4. System vimrc ran first and did something. You can force Vim to load only your vimrc by running `vim -u ~/.vim/vimrc` where the file passed to `-u` is the filepath of your vimrc.

Hi Janlazo,

I met with a similar problem in my situation. I wanted to set a different `.vim` path instead of the default `~/.vim`. As suggested above, I use the following code in my `/home/xx/newhome/.vimrc`

```
source /home/xx/newhome/.vim/autoload/plug.vim
call plug#begin('/home/xx/newhome/.vim/plugged')
" Make sure you use single quotes
Plug 'scrooloose/nerdtree' 
Plug 'majutsushi/tagbar'
" Initialize plugin system
"call plug#end()
```
In my situation, the commands related to `plug.vim`, e.g. `PlugInstall` or `PlugUpdate` worked correctly, and I was sure the plugins (nerdtree and tagbar) were installed in `/home/xx/newhome/.vim/plugged` correctly. While the command such as `TagbarToggle` did not work at all. I also tried to add the line `set rtp+=/home/xx/newhome/.vim/plugged` in my vimrc and It also didn't work.
BTW, I use `vim -u /home/xx/newhome/.vimrc` to excute the vim.
