### ISSUE TITLE
can i stop update specific plugin.

### ISSUE THREAD

**Issue by qianyingshuo** [junegunn/vim-plug#991]
Hi, can i stop update specific plugin? 
i get a error on plugin "tagbar". it's new version need "pyx" commond. 
so i want this plugin stay on a old version and never update. but other plugin keep on updating.
what should i do?
thk u for you reply.
------------------------------

```

```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [ ] Linux
    - [ ] OS X
    - [x] Windows
- Vim:
    - [ ] Terminal Vim
    - [x] GVim
    - [ ] Neovim

**Comment by janlazo** [comment]
https://github.com/junegunn/vim-plug#plug-options
Set one of the following: frozen, tag, commit.
