### ISSUE TITLE
[Feature request] Split plugs into different places and optionaly include them

### ISSUE THREAD

**Issue by juliancoffee** [junegunn/vim-plug#993]
Explain the problem here ...
------------------------------
I want to split my config into parts, which can be optionally included or not
For example, I may prefer to use coc.nvim but sometimes to experiment with LanguageClientNeovim.

I thought about something like this
**plugins.vim:**
```
plug#begin()
  Plug 'scrooloose/nerdtree', {'on': 'NERDTreeToggle' }  "improved file explorer
plug#end()
```

**coc.vim:**
```
plug#begin()
  Plug 'neoclide/coc.nvim', {'branch': 'release'}        " VSCode like completion
plug#end()

nnoremap gd :call CocAction('jumpDefinition', 'tabe')<CR>
```
**language_client.vim:**
```
call plug#begin()
Plug 'autozimu/LanguageClient-neovim', {
            \'branch': 'next',
            \'do': 'bash install.sh',
            \}
call plug#end()

let g:LanguageClient_serverCommands = {
            \ }

```
**init.vim:**
```
source plugins.vim
source coc.vim
" source language_client.vim
```
And when I want to use LanguageClient, I can just uncomment this line and comment line with coc.vim
But, because https://github.com/junegunn/vim-plug/blob/master/plug.vim#L167, another plug#begin() erase all plugins in the first section.
I've tried to change this line to 
```
if !exists(g:plugs)
    g:plugs = {}
endif
```
And it seems to be working.
Can't we really change this?
Or maybe there may be some workaround?

I know I can create another file with Plug and source it in the plugins sections, but that way I'll need to uncomment/comment in two places for every plugin and it seems annoying.

What if I just add plug#begin() to the beginning of the file, and plug#end() to end of the file and remove them from other files. Can it break something?

```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

```

- Type:
    - [ ] Bug
    - [x] Enhancement
    - [x] Feature Request
    - [ ] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by junegunn** [comment]
> What if I just add plug#begin() to the beginning of the file, and plug#end() to end of the file and remove them from other files. Can it break something?

No.

```vim
call plug#begin()

source plugins.vim
source coc.vim
" source language_client.vim

call plug#end()
```
