### ISSUE TITLE
Invalid arguments for function plug#

### ISSUE THREAD

**Issue by inkuniverse** [junegunn/vim-plug#994]
I used a very simple config:
```vim
call plug#begin('~/.config/nvim/plugs')
Plug 'itchyny/lightline.vim'
call plug#end()
```
```
But I founded some error:
Error detected while processing /home/inkuniverse/.config/nvim/init.vim:
line    9:
E488: Trailing characters
line   10:
E116: Invalid arguments for function plug#
line   11:
E488: Trailing characters
Press ENTER or type command to continue
```
Why that?
------------------------------

```

```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [ ] Feature Request
    - [x] Question
- OS:
    - [ ] All/Other
    - [x] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by janlazo** [comment]
Did you install vim-plug?

**Comment by inkuniverse** [comment]
Yes I did.

**Comment by janlazo** [comment]
Is there an error if you replace `Plug 'itchyny/lightline.vim'` with `call plug#('itchyny/lightline.vim')`?

**Comment by inkuniverse** [comment]
Sorry,I found that I put plug.vim in a error space.
Thanks for your help!
