### ISSUE TITLE
Feature request: loading priority

### ISSUE THREAD

**Issue by yhu266** [junegunn/vim-plug#996]
Now it seems that `vim-plug` loads only the first file when there are multiple autoload files with **the exact same name** in different plugins. See itchyny/lightline.vim#488 and arcticicestudio/nord-vim#215 .

Is it possible to have a priority value assigned to each plugin such that the autoload files in the high-priority plugins are loaded? The fix for now is to carefully decide the order of `Plug` lines, but it is sometimes hard to figure out.

------------------------------

```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedant
ic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdia
gnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-85913-1wbgqz6/n
eovim-0.4.3/build/config -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/deps-bui
ld/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include
-I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/include
Compiled by brew@Catalina.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.3/share/nvim"

Run :checkhealth for more info
```

- Type:
    - [ ] Bug
    - [ ] Enhancement
    - [x] Feature Request
    - [ ] Question
- OS:
    - [x] All/Other
    - [ ] Linux
    - [ ] OS X
    - [ ] Windows
- Vim:
    - [ ] Terminal Vim
    - [ ] GVim
    - [x] Neovim

**Comment by janlazo** [comment]
https://github.com/junegunn/vim-plug/issues/85
You can redefine `g:plugs_order` before calling `plug#end()`.

**Comment by yhu266** [comment]
Yes that's the idea! So if this feature is added, it'll sort `g:plugs_order` based on priority value.

**Comment by Shougo** [comment]
I think the conflicted files should be renamed...

**Comment by yhu266** [comment]
> I think the conflicted files should be renamed...

Ideally yes we should avoid conflicted files. However, I think it'll be an enhancement for `vim-plug` if there's an easy way to decide loading order. Though I'm not sure if it's possible, considering #85 and thr `rtp` issue.

As for the conflicted colorscheme files in `nord-vim` and `lightline`, it can be resolved easily. I'm not sure it'll be easy for other plugins with tangled dependencies.
